//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/gaudi/asic_reg/dma0_qm_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2018 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// DMA0_QM (Prototype: QMAN)
//
// DMA0_QM_GLBL_CFG0
pub const DMA0_QM_GLBL_CFG0_PQF_EN_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_CFG0_PQF_EN_MASK: c_uint = 0xF;
pub const DMA0_QM_GLBL_CFG0_CQF_EN_SHIFT: c_int = 4;
pub const DMA0_QM_GLBL_CFG0_CQF_EN_MASK: c_uint = 0x1F0;
pub const DMA0_QM_GLBL_CFG0_CP_EN_SHIFT: c_int = 9;
pub const DMA0_QM_GLBL_CFG0_CP_EN_MASK: c_uint = 0x3E00;
// DMA0_QM_GLBL_CFG1
pub const DMA0_QM_GLBL_CFG1_PQF_STOP_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_CFG1_PQF_STOP_MASK: c_uint = 0xF;
pub const DMA0_QM_GLBL_CFG1_CQF_STOP_SHIFT: c_int = 4;
pub const DMA0_QM_GLBL_CFG1_CQF_STOP_MASK: c_uint = 0x1F0;
pub const DMA0_QM_GLBL_CFG1_CP_STOP_SHIFT: c_int = 9;
pub const DMA0_QM_GLBL_CFG1_CP_STOP_MASK: c_uint = 0x3E00;
pub const DMA0_QM_GLBL_CFG1_PQF_FLUSH_SHIFT: c_int = 16;
pub const DMA0_QM_GLBL_CFG1_PQF_FLUSH_MASK: c_uint = 0xF0000;
pub const DMA0_QM_GLBL_CFG1_CQF_FLUSH_SHIFT: c_int = 20;
pub const DMA0_QM_GLBL_CFG1_CQF_FLUSH_MASK: c_uint = 0x1F00000;
pub const DMA0_QM_GLBL_CFG1_CP_FLUSH_SHIFT: c_int = 25;
pub const DMA0_QM_GLBL_CFG1_CP_FLUSH_MASK: c_uint = 0x3E000000;
// DMA0_QM_GLBL_PROT
pub const DMA0_QM_GLBL_PROT_PQF_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_PROT_PQF_MASK: c_uint = 0xF;
pub const DMA0_QM_GLBL_PROT_CQF_SHIFT: c_int = 4;
pub const DMA0_QM_GLBL_PROT_CQF_MASK: c_uint = 0x1F0;
pub const DMA0_QM_GLBL_PROT_CP_SHIFT: c_int = 9;
pub const DMA0_QM_GLBL_PROT_CP_MASK: c_uint = 0x3E00;
pub const DMA0_QM_GLBL_PROT_ERR_SHIFT: c_int = 14;
pub const DMA0_QM_GLBL_PROT_ERR_MASK: c_uint = 0x4000;
pub const DMA0_QM_GLBL_PROT_ARB_SHIFT: c_int = 15;
pub const DMA0_QM_GLBL_PROT_ARB_MASK: c_uint = 0x8000;
// DMA0_QM_GLBL_ERR_CFG
pub const DMA0_QM_GLBL_ERR_CFG_PQF_ERR_MSG_EN_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_ERR_CFG_PQF_ERR_MSG_EN_MASK: c_uint = 0xF;
pub const DMA0_QM_GLBL_ERR_CFG_CQF_ERR_MSG_EN_SHIFT: c_int = 4;
pub const DMA0_QM_GLBL_ERR_CFG_CQF_ERR_MSG_EN_MASK: c_uint = 0x1F0;
pub const DMA0_QM_GLBL_ERR_CFG_CP_ERR_MSG_EN_SHIFT: c_int = 9;
pub const DMA0_QM_GLBL_ERR_CFG_CP_ERR_MSG_EN_MASK: c_uint = 0x3E00;
pub const DMA0_QM_GLBL_ERR_CFG_PQF_STOP_ON_ERR_SHIFT: c_int = 16;
pub const DMA0_QM_GLBL_ERR_CFG_PQF_STOP_ON_ERR_MASK: c_uint = 0xF0000;
pub const DMA0_QM_GLBL_ERR_CFG_CQF_STOP_ON_ERR_SHIFT: c_int = 20;
pub const DMA0_QM_GLBL_ERR_CFG_CQF_STOP_ON_ERR_MASK: c_uint = 0x1F00000;
pub const DMA0_QM_GLBL_ERR_CFG_CP_STOP_ON_ERR_SHIFT: c_int = 25;
pub const DMA0_QM_GLBL_ERR_CFG_CP_STOP_ON_ERR_MASK: c_uint = 0x3E000000;
pub const DMA0_QM_GLBL_ERR_CFG_ARB_STOP_ON_ERR_SHIFT: c_int = 31;
pub const DMA0_QM_GLBL_ERR_CFG_ARB_STOP_ON_ERR_MASK: c_uint = 0x80000000;
// DMA0_QM_GLBL_SECURE_PROPS
pub const DMA0_QM_GLBL_SECURE_PROPS_0_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_SECURE_PROPS_0_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_GLBL_SECURE_PROPS_1_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_SECURE_PROPS_1_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_GLBL_SECURE_PROPS_2_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_SECURE_PROPS_2_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_GLBL_SECURE_PROPS_3_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_SECURE_PROPS_3_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_GLBL_SECURE_PROPS_4_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_SECURE_PROPS_4_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_GLBL_SECURE_PROPS_0_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_SECURE_PROPS_0_MMBP_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_SECURE_PROPS_1_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_SECURE_PROPS_1_MMBP_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_SECURE_PROPS_2_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_SECURE_PROPS_2_MMBP_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_SECURE_PROPS_3_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_SECURE_PROPS_3_MMBP_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_SECURE_PROPS_4_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_SECURE_PROPS_4_MMBP_MASK: c_uint = 0x400;
// DMA0_QM_GLBL_NON_SECURE_PROPS
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_0_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_0_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_1_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_1_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_2_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_2_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_3_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_3_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_4_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_4_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_0_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_0_MMBP_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_1_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_1_MMBP_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_2_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_2_MMBP_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_3_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_3_MMBP_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_4_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_NON_SECURE_PROPS_4_MMBP_MASK: c_uint = 0x400;
// DMA0_QM_GLBL_STS0
pub const DMA0_QM_GLBL_STS0_PQF_IDLE_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_STS0_PQF_IDLE_MASK: c_uint = 0xF;
pub const DMA0_QM_GLBL_STS0_CQF_IDLE_SHIFT: c_int = 4;
pub const DMA0_QM_GLBL_STS0_CQF_IDLE_MASK: c_uint = 0x1F0;
pub const DMA0_QM_GLBL_STS0_CP_IDLE_SHIFT: c_int = 9;
pub const DMA0_QM_GLBL_STS0_CP_IDLE_MASK: c_uint = 0x3E00;
pub const DMA0_QM_GLBL_STS0_PQF_IS_STOP_SHIFT: c_int = 16;
pub const DMA0_QM_GLBL_STS0_PQF_IS_STOP_MASK: c_uint = 0xF0000;
pub const DMA0_QM_GLBL_STS0_CQF_IS_STOP_SHIFT: c_int = 20;
pub const DMA0_QM_GLBL_STS0_CQF_IS_STOP_MASK: c_uint = 0x1F00000;
pub const DMA0_QM_GLBL_STS0_CP_IS_STOP_SHIFT: c_int = 25;
pub const DMA0_QM_GLBL_STS0_CP_IS_STOP_MASK: c_uint = 0x3E000000;
pub const DMA0_QM_GLBL_STS0_ARB_IS_STOP_SHIFT: c_int = 31;
pub const DMA0_QM_GLBL_STS0_ARB_IS_STOP_MASK: c_uint = 0x80000000;
// DMA0_QM_GLBL_STS1
pub const DMA0_QM_GLBL_STS1_PQF_RD_ERR_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_STS1_PQF_RD_ERR_MASK: c_uint = 0x1;
pub const DMA0_QM_GLBL_STS1_CQF_RD_ERR_SHIFT: c_int = 1;
pub const DMA0_QM_GLBL_STS1_CQF_RD_ERR_MASK: c_uint = 0x2;
pub const DMA0_QM_GLBL_STS1_CP_RD_ERR_SHIFT: c_int = 2;
pub const DMA0_QM_GLBL_STS1_CP_RD_ERR_MASK: c_uint = 0x4;
pub const DMA0_QM_GLBL_STS1_CP_UNDEF_CMD_ERR_SHIFT: c_int = 3;
pub const DMA0_QM_GLBL_STS1_CP_UNDEF_CMD_ERR_MASK: c_uint = 0x8;
pub const DMA0_QM_GLBL_STS1_CP_STOP_OP_SHIFT: c_int = 4;
pub const DMA0_QM_GLBL_STS1_CP_STOP_OP_MASK: c_uint = 0x10;
pub const DMA0_QM_GLBL_STS1_CP_MSG_WR_ERR_SHIFT: c_int = 5;
pub const DMA0_QM_GLBL_STS1_CP_MSG_WR_ERR_MASK: c_uint = 0x20;
pub const DMA0_QM_GLBL_STS1_CP_WREG_ERR_SHIFT: c_int = 6;
pub const DMA0_QM_GLBL_STS1_CP_WREG_ERR_MASK: c_uint = 0x40;
pub const DMA0_QM_GLBL_STS1_CP_FENCE0_OVF_ERR_SHIFT: c_int = 8;
pub const DMA0_QM_GLBL_STS1_CP_FENCE0_OVF_ERR_MASK: c_uint = 0x100;
pub const DMA0_QM_GLBL_STS1_CP_FENCE1_OVF_ERR_SHIFT: c_int = 9;
pub const DMA0_QM_GLBL_STS1_CP_FENCE1_OVF_ERR_MASK: c_uint = 0x200;
pub const DMA0_QM_GLBL_STS1_CP_FENCE2_OVF_ERR_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_STS1_CP_FENCE2_OVF_ERR_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_STS1_CP_FENCE3_OVF_ERR_SHIFT: c_int = 11;
pub const DMA0_QM_GLBL_STS1_CP_FENCE3_OVF_ERR_MASK: c_uint = 0x800;
pub const DMA0_QM_GLBL_STS1_CP_FENCE0_UDF_ERR_SHIFT: c_int = 12;
pub const DMA0_QM_GLBL_STS1_CP_FENCE0_UDF_ERR_MASK: c_uint = 0x1000;
pub const DMA0_QM_GLBL_STS1_CP_FENCE1_UDF_ERR_SHIFT: c_int = 13;
pub const DMA0_QM_GLBL_STS1_CP_FENCE1_UDF_ERR_MASK: c_uint = 0x2000;
pub const DMA0_QM_GLBL_STS1_CP_FENCE2_UDF_ERR_SHIFT: c_int = 14;
pub const DMA0_QM_GLBL_STS1_CP_FENCE2_UDF_ERR_MASK: c_uint = 0x4000;
pub const DMA0_QM_GLBL_STS1_CP_FENCE3_UDF_ERR_SHIFT: c_int = 15;
pub const DMA0_QM_GLBL_STS1_CP_FENCE3_UDF_ERR_MASK: c_uint = 0x8000;
// DMA0_QM_GLBL_STS1_4
pub const DMA0_QM_GLBL_STS1_4_CQF_RD_ERR_SHIFT: c_int = 1;
pub const DMA0_QM_GLBL_STS1_4_CQF_RD_ERR_MASK: c_uint = 0x2;
pub const DMA0_QM_GLBL_STS1_4_CP_RD_ERR_SHIFT: c_int = 2;
pub const DMA0_QM_GLBL_STS1_4_CP_RD_ERR_MASK: c_uint = 0x4;
pub const DMA0_QM_GLBL_STS1_4_CP_UNDEF_CMD_ERR_SHIFT: c_int = 3;
pub const DMA0_QM_GLBL_STS1_4_CP_UNDEF_CMD_ERR_MASK: c_uint = 0x8;
pub const DMA0_QM_GLBL_STS1_4_CP_STOP_OP_SHIFT: c_int = 4;
pub const DMA0_QM_GLBL_STS1_4_CP_STOP_OP_MASK: c_uint = 0x10;
pub const DMA0_QM_GLBL_STS1_4_CP_MSG_WR_ERR_SHIFT: c_int = 5;
pub const DMA0_QM_GLBL_STS1_4_CP_MSG_WR_ERR_MASK: c_uint = 0x20;
pub const DMA0_QM_GLBL_STS1_4_CP_WREG_ERR_SHIFT: c_int = 6;
pub const DMA0_QM_GLBL_STS1_4_CP_WREG_ERR_MASK: c_uint = 0x40;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE0_OVF_ERR_SHIFT: c_int = 8;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE0_OVF_ERR_MASK: c_uint = 0x100;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE1_OVF_ERR_SHIFT: c_int = 9;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE1_OVF_ERR_MASK: c_uint = 0x200;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE2_OVF_ERR_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE2_OVF_ERR_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE3_OVF_ERR_SHIFT: c_int = 11;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE3_OVF_ERR_MASK: c_uint = 0x800;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE0_UDF_ERR_SHIFT: c_int = 12;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE0_UDF_ERR_MASK: c_uint = 0x1000;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE1_UDF_ERR_SHIFT: c_int = 13;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE1_UDF_ERR_MASK: c_uint = 0x2000;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE2_UDF_ERR_SHIFT: c_int = 14;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE2_UDF_ERR_MASK: c_uint = 0x4000;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE3_UDF_ERR_SHIFT: c_int = 15;
pub const DMA0_QM_GLBL_STS1_4_CP_FENCE3_UDF_ERR_MASK: c_uint = 0x8000;
// DMA0_QM_GLBL_MSG_EN
pub const DMA0_QM_GLBL_MSG_EN_PQF_RD_ERR_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_MSG_EN_PQF_RD_ERR_MASK: c_uint = 0x1;
pub const DMA0_QM_GLBL_MSG_EN_CQF_RD_ERR_SHIFT: c_int = 1;
pub const DMA0_QM_GLBL_MSG_EN_CQF_RD_ERR_MASK: c_uint = 0x2;
pub const DMA0_QM_GLBL_MSG_EN_CP_RD_ERR_SHIFT: c_int = 2;
pub const DMA0_QM_GLBL_MSG_EN_CP_RD_ERR_MASK: c_uint = 0x4;
pub const DMA0_QM_GLBL_MSG_EN_CP_UNDEF_CMD_ERR_SHIFT: c_int = 3;
pub const DMA0_QM_GLBL_MSG_EN_CP_UNDEF_CMD_ERR_MASK: c_uint = 0x8;
pub const DMA0_QM_GLBL_MSG_EN_CP_STOP_OP_SHIFT: c_int = 4;
pub const DMA0_QM_GLBL_MSG_EN_CP_STOP_OP_MASK: c_uint = 0x10;
pub const DMA0_QM_GLBL_MSG_EN_CP_MSG_WR_ERR_SHIFT: c_int = 5;
pub const DMA0_QM_GLBL_MSG_EN_CP_MSG_WR_ERR_MASK: c_uint = 0x20;
pub const DMA0_QM_GLBL_MSG_EN_CP_WREG_ERR_SHIFT: c_int = 6;
pub const DMA0_QM_GLBL_MSG_EN_CP_WREG_ERR_MASK: c_uint = 0x40;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE0_OVF_ERR_SHIFT: c_int = 8;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE0_OVF_ERR_MASK: c_uint = 0x100;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE1_OVF_ERR_SHIFT: c_int = 9;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE1_OVF_ERR_MASK: c_uint = 0x200;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE2_OVF_ERR_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE2_OVF_ERR_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE3_OVF_ERR_SHIFT: c_int = 11;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE3_OVF_ERR_MASK: c_uint = 0x800;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE0_UDF_ERR_SHIFT: c_int = 12;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE0_UDF_ERR_MASK: c_uint = 0x1000;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE1_UDF_ERR_SHIFT: c_int = 13;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE1_UDF_ERR_MASK: c_uint = 0x2000;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE2_UDF_ERR_SHIFT: c_int = 14;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE2_UDF_ERR_MASK: c_uint = 0x4000;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE3_UDF_ERR_SHIFT: c_int = 15;
pub const DMA0_QM_GLBL_MSG_EN_CP_FENCE3_UDF_ERR_MASK: c_uint = 0x8000;
// DMA0_QM_GLBL_MSG_EN_4
pub const DMA0_QM_GLBL_MSG_EN_4_CQF_RD_ERR_SHIFT: c_int = 1;
pub const DMA0_QM_GLBL_MSG_EN_4_CQF_RD_ERR_MASK: c_uint = 0x2;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_RD_ERR_SHIFT: c_int = 2;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_RD_ERR_MASK: c_uint = 0x4;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_UNDEF_CMD_ERR_SHIFT: c_int = 3;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_UNDEF_CMD_ERR_MASK: c_uint = 0x8;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_STOP_OP_SHIFT: c_int = 4;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_STOP_OP_MASK: c_uint = 0x10;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_MSG_WR_ERR_SHIFT: c_int = 5;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_MSG_WR_ERR_MASK: c_uint = 0x20;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_WREG_ERR_SHIFT: c_int = 6;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_WREG_ERR_MASK: c_uint = 0x40;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE0_OVF_ERR_SHIFT: c_int = 8;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE0_OVF_ERR_MASK: c_uint = 0x100;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE1_OVF_ERR_SHIFT: c_int = 9;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE1_OVF_ERR_MASK: c_uint = 0x200;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE2_OVF_ERR_SHIFT: c_int = 10;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE2_OVF_ERR_MASK: c_uint = 0x400;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE3_OVF_ERR_SHIFT: c_int = 11;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE3_OVF_ERR_MASK: c_uint = 0x800;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE0_UDF_ERR_SHIFT: c_int = 12;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE0_UDF_ERR_MASK: c_uint = 0x1000;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE1_UDF_ERR_SHIFT: c_int = 13;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE1_UDF_ERR_MASK: c_uint = 0x2000;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE2_UDF_ERR_SHIFT: c_int = 14;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE2_UDF_ERR_MASK: c_uint = 0x4000;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE3_UDF_ERR_SHIFT: c_int = 15;
pub const DMA0_QM_GLBL_MSG_EN_4_CP_FENCE3_UDF_ERR_MASK: c_uint = 0x8000;
// DMA0_QM_PQ_BASE_LO
pub const DMA0_QM_PQ_BASE_LO_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_PQ_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_PQ_BASE_HI
pub const DMA0_QM_PQ_BASE_HI_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_PQ_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_PQ_SIZE
pub const DMA0_QM_PQ_SIZE_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_PQ_SIZE_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_PQ_PI
pub const DMA0_QM_PQ_PI_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_PQ_PI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_PQ_CI
pub const DMA0_QM_PQ_CI_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_PQ_CI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_PQ_CFG0
pub const DMA0_QM_PQ_CFG0_RESERVED_SHIFT: c_int = 0;
pub const DMA0_QM_PQ_CFG0_RESERVED_MASK: c_uint = 0x1;
// DMA0_QM_PQ_CFG1
pub const DMA0_QM_PQ_CFG1_CREDIT_LIM_SHIFT: c_int = 0;
pub const DMA0_QM_PQ_CFG1_CREDIT_LIM_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_PQ_CFG1_MAX_INFLIGHT_SHIFT: c_int = 16;
pub const DMA0_QM_PQ_CFG1_MAX_INFLIGHT_MASK: c_uint = 0xFFFF0000;
// DMA0_QM_PQ_ARUSER_31_11
pub const DMA0_QM_PQ_ARUSER_31_11_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_PQ_ARUSER_31_11_VAL_MASK: c_uint = 0x1FFFFF;
// DMA0_QM_PQ_STS0
pub const DMA0_QM_PQ_STS0_PQ_CREDIT_CNT_SHIFT: c_int = 0;
pub const DMA0_QM_PQ_STS0_PQ_CREDIT_CNT_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_PQ_STS0_PQ_FREE_CNT_SHIFT: c_int = 16;
pub const DMA0_QM_PQ_STS0_PQ_FREE_CNT_MASK: c_uint = 0xFFFF0000;
// DMA0_QM_PQ_STS1
pub const DMA0_QM_PQ_STS1_PQ_INFLIGHT_CNT_SHIFT: c_int = 0;
pub const DMA0_QM_PQ_STS1_PQ_INFLIGHT_CNT_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_PQ_STS1_PQ_BUF_EMPTY_SHIFT: c_int = 30;
pub const DMA0_QM_PQ_STS1_PQ_BUF_EMPTY_MASK: c_uint = 0x40000000;
pub const DMA0_QM_PQ_STS1_PQ_BUSY_SHIFT: c_int = 31;
pub const DMA0_QM_PQ_STS1_PQ_BUSY_MASK: c_uint = 0x80000000;
// DMA0_QM_CQ_CFG0
pub const DMA0_QM_CQ_CFG0_RESERVED_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_CFG0_RESERVED_MASK: c_uint = 0x1;
// DMA0_QM_CQ_CFG1
pub const DMA0_QM_CQ_CFG1_CREDIT_LIM_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_CFG1_CREDIT_LIM_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_CQ_CFG1_MAX_INFLIGHT_SHIFT: c_int = 16;
pub const DMA0_QM_CQ_CFG1_MAX_INFLIGHT_MASK: c_uint = 0xFFFF0000;
// DMA0_QM_CQ_ARUSER_31_11
pub const DMA0_QM_CQ_ARUSER_31_11_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_ARUSER_31_11_VAL_MASK: c_uint = 0x1FFFFF;
// DMA0_QM_CQ_STS0
pub const DMA0_QM_CQ_STS0_CQ_CREDIT_CNT_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_STS0_CQ_CREDIT_CNT_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_CQ_STS0_CQ_FREE_CNT_SHIFT: c_int = 16;
pub const DMA0_QM_CQ_STS0_CQ_FREE_CNT_MASK: c_uint = 0xFFFF0000;
// DMA0_QM_CQ_STS1
pub const DMA0_QM_CQ_STS1_CQ_INFLIGHT_CNT_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_STS1_CQ_INFLIGHT_CNT_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_CQ_STS1_CQ_BUF_EMPTY_SHIFT: c_int = 30;
pub const DMA0_QM_CQ_STS1_CQ_BUF_EMPTY_MASK: c_uint = 0x40000000;
pub const DMA0_QM_CQ_STS1_CQ_BUSY_SHIFT: c_int = 31;
pub const DMA0_QM_CQ_STS1_CQ_BUSY_MASK: c_uint = 0x80000000;
// DMA0_QM_CQ_PTR_LO_0
pub const DMA0_QM_CQ_PTR_LO_0_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_LO_0_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_PTR_HI_0
pub const DMA0_QM_CQ_PTR_HI_0_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_HI_0_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_TSIZE_0
pub const DMA0_QM_CQ_TSIZE_0_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_TSIZE_0_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_CTL_0
pub const DMA0_QM_CQ_CTL_0_RPT_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_CTL_0_RPT_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_CQ_CTL_0_CTL_SHIFT: c_int = 16;
pub const DMA0_QM_CQ_CTL_0_CTL_MASK: c_uint = 0xFFFF0000;
// DMA0_QM_CQ_PTR_LO_1
pub const DMA0_QM_CQ_PTR_LO_1_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_LO_1_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_PTR_HI_1
pub const DMA0_QM_CQ_PTR_HI_1_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_HI_1_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_TSIZE_1
pub const DMA0_QM_CQ_TSIZE_1_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_TSIZE_1_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_CTL_1
pub const DMA0_QM_CQ_CTL_1_RPT_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_CTL_1_RPT_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_CQ_CTL_1_CTL_SHIFT: c_int = 16;
pub const DMA0_QM_CQ_CTL_1_CTL_MASK: c_uint = 0xFFFF0000;
// DMA0_QM_CQ_PTR_LO_2
pub const DMA0_QM_CQ_PTR_LO_2_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_LO_2_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_PTR_HI_2
pub const DMA0_QM_CQ_PTR_HI_2_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_HI_2_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_TSIZE_2
pub const DMA0_QM_CQ_TSIZE_2_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_TSIZE_2_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_CTL_2
pub const DMA0_QM_CQ_CTL_2_RPT_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_CTL_2_RPT_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_CQ_CTL_2_CTL_SHIFT: c_int = 16;
pub const DMA0_QM_CQ_CTL_2_CTL_MASK: c_uint = 0xFFFF0000;
// DMA0_QM_CQ_PTR_LO_3
pub const DMA0_QM_CQ_PTR_LO_3_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_LO_3_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_PTR_HI_3
pub const DMA0_QM_CQ_PTR_HI_3_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_HI_3_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_TSIZE_3
pub const DMA0_QM_CQ_TSIZE_3_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_TSIZE_3_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_CTL_3
pub const DMA0_QM_CQ_CTL_3_RPT_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_CTL_3_RPT_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_CQ_CTL_3_CTL_SHIFT: c_int = 16;
pub const DMA0_QM_CQ_CTL_3_CTL_MASK: c_uint = 0xFFFF0000;
// DMA0_QM_CQ_PTR_LO_4
pub const DMA0_QM_CQ_PTR_LO_4_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_LO_4_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_PTR_HI_4
pub const DMA0_QM_CQ_PTR_HI_4_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_HI_4_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_TSIZE_4
pub const DMA0_QM_CQ_TSIZE_4_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_TSIZE_4_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_CTL_4
pub const DMA0_QM_CQ_CTL_4_RPT_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_CTL_4_RPT_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_CQ_CTL_4_CTL_SHIFT: c_int = 16;
pub const DMA0_QM_CQ_CTL_4_CTL_MASK: c_uint = 0xFFFF0000;
// DMA0_QM_CQ_PTR_LO_STS
pub const DMA0_QM_CQ_PTR_LO_STS_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_LO_STS_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_PTR_HI_STS
pub const DMA0_QM_CQ_PTR_HI_STS_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_PTR_HI_STS_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_TSIZE_STS
pub const DMA0_QM_CQ_TSIZE_STS_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_TSIZE_STS_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CQ_CTL_STS
pub const DMA0_QM_CQ_CTL_STS_RPT_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_CTL_STS_RPT_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_CQ_CTL_STS_CTL_SHIFT: c_int = 16;
pub const DMA0_QM_CQ_CTL_STS_CTL_MASK: c_uint = 0xFFFF0000;
// DMA0_QM_CQ_IFIFO_CNT
pub const DMA0_QM_CQ_IFIFO_CNT_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CQ_IFIFO_CNT_VAL_MASK: c_uint = 0x3;
// DMA0_QM_CP_MSG_BASE0_ADDR_LO
pub const DMA0_QM_CP_MSG_BASE0_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_MSG_BASE0_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_MSG_BASE0_ADDR_HI
pub const DMA0_QM_CP_MSG_BASE0_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_MSG_BASE0_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_MSG_BASE1_ADDR_LO
pub const DMA0_QM_CP_MSG_BASE1_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_MSG_BASE1_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_MSG_BASE1_ADDR_HI
pub const DMA0_QM_CP_MSG_BASE1_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_MSG_BASE1_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_MSG_BASE2_ADDR_LO
pub const DMA0_QM_CP_MSG_BASE2_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_MSG_BASE2_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_MSG_BASE2_ADDR_HI
pub const DMA0_QM_CP_MSG_BASE2_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_MSG_BASE2_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_MSG_BASE3_ADDR_LO
pub const DMA0_QM_CP_MSG_BASE3_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_MSG_BASE3_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_MSG_BASE3_ADDR_HI
pub const DMA0_QM_CP_MSG_BASE3_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_MSG_BASE3_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_LDMA_TSIZE_OFFSET
pub const DMA0_QM_CP_LDMA_TSIZE_OFFSET_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_LDMA_TSIZE_OFFSET_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_LDMA_SRC_BASE_LO_OFFSET
pub const DMA0_QM_CP_LDMA_SRC_BASE_LO_OFFSET_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_LDMA_SRC_BASE_LO_OFFSET_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_LDMA_DST_BASE_LO_OFFSET
pub const DMA0_QM_CP_LDMA_DST_BASE_LO_OFFSET_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_LDMA_DST_BASE_LO_OFFSET_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_FENCE0_RDATA
pub const DMA0_QM_CP_FENCE0_RDATA_INC_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_FENCE0_RDATA_INC_VAL_MASK: c_uint = 0xF;
// DMA0_QM_CP_FENCE1_RDATA
pub const DMA0_QM_CP_FENCE1_RDATA_INC_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_FENCE1_RDATA_INC_VAL_MASK: c_uint = 0xF;
// DMA0_QM_CP_FENCE2_RDATA
pub const DMA0_QM_CP_FENCE2_RDATA_INC_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_FENCE2_RDATA_INC_VAL_MASK: c_uint = 0xF;
// DMA0_QM_CP_FENCE3_RDATA
pub const DMA0_QM_CP_FENCE3_RDATA_INC_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_FENCE3_RDATA_INC_VAL_MASK: c_uint = 0xF;
// DMA0_QM_CP_FENCE0_CNT
pub const DMA0_QM_CP_FENCE0_CNT_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_FENCE0_CNT_VAL_MASK: c_uint = 0x3FFF;
// DMA0_QM_CP_FENCE1_CNT
pub const DMA0_QM_CP_FENCE1_CNT_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_FENCE1_CNT_VAL_MASK: c_uint = 0x3FFF;
// DMA0_QM_CP_FENCE2_CNT
pub const DMA0_QM_CP_FENCE2_CNT_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_FENCE2_CNT_VAL_MASK: c_uint = 0x3FFF;
// DMA0_QM_CP_FENCE3_CNT
pub const DMA0_QM_CP_FENCE3_CNT_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_FENCE3_CNT_VAL_MASK: c_uint = 0x3FFF;
// DMA0_QM_CP_STS
pub const DMA0_QM_CP_STS_MSG_INFLIGHT_CNT_SHIFT: c_int = 0;
pub const DMA0_QM_CP_STS_MSG_INFLIGHT_CNT_MASK: c_uint = 0xFFFF;
pub const DMA0_QM_CP_STS_ERDY_SHIFT: c_int = 16;
pub const DMA0_QM_CP_STS_ERDY_MASK: c_uint = 0x10000;
pub const DMA0_QM_CP_STS_RRDY_SHIFT: c_int = 17;
pub const DMA0_QM_CP_STS_RRDY_MASK: c_uint = 0x20000;
pub const DMA0_QM_CP_STS_MRDY_SHIFT: c_int = 18;
pub const DMA0_QM_CP_STS_MRDY_MASK: c_uint = 0x40000;
pub const DMA0_QM_CP_STS_SW_STOP_SHIFT: c_int = 19;
pub const DMA0_QM_CP_STS_SW_STOP_MASK: c_uint = 0x80000;
pub const DMA0_QM_CP_STS_FENCE_ID_SHIFT: c_int = 20;
pub const DMA0_QM_CP_STS_FENCE_ID_MASK: c_uint = 0x300000;
pub const DMA0_QM_CP_STS_FENCE_IN_PROGRESS_SHIFT: c_int = 22;
pub const DMA0_QM_CP_STS_FENCE_IN_PROGRESS_MASK: c_uint = 0x400000;
// DMA0_QM_CP_CURRENT_INST_LO
pub const DMA0_QM_CP_CURRENT_INST_LO_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_CURRENT_INST_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_CURRENT_INST_HI
pub const DMA0_QM_CP_CURRENT_INST_HI_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_CURRENT_INST_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_CP_BARRIER_CFG
pub const DMA0_QM_CP_BARRIER_CFG_EBGUARD_SHIFT: c_int = 0;
pub const DMA0_QM_CP_BARRIER_CFG_EBGUARD_MASK: c_uint = 0xFFF;
pub const DMA0_QM_CP_BARRIER_CFG_RBGUARD_SHIFT: c_int = 16;
pub const DMA0_QM_CP_BARRIER_CFG_RBGUARD_MASK: c_uint = 0xF0000;
// DMA0_QM_CP_DBG_0
pub const DMA0_QM_CP_DBG_0_CS_SHIFT: c_int = 0;
pub const DMA0_QM_CP_DBG_0_CS_MASK: c_uint = 0xF;
pub const DMA0_QM_CP_DBG_0_EB_CNT_NOT_ZERO_SHIFT: c_int = 4;
pub const DMA0_QM_CP_DBG_0_EB_CNT_NOT_ZERO_MASK: c_uint = 0x10;
pub const DMA0_QM_CP_DBG_0_BULK_CNT_NOT_ZERO_SHIFT: c_int = 5;
pub const DMA0_QM_CP_DBG_0_BULK_CNT_NOT_ZERO_MASK: c_uint = 0x20;
pub const DMA0_QM_CP_DBG_0_MREB_STALL_SHIFT: c_int = 6;
pub const DMA0_QM_CP_DBG_0_MREB_STALL_MASK: c_uint = 0x40;
pub const DMA0_QM_CP_DBG_0_STALL_SHIFT: c_int = 7;
pub const DMA0_QM_CP_DBG_0_STALL_MASK: c_uint = 0x80;
// DMA0_QM_CP_ARUSER_31_11
pub const DMA0_QM_CP_ARUSER_31_11_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_ARUSER_31_11_VAL_MASK: c_uint = 0x1FFFFF;
// DMA0_QM_CP_AWUSER_31_11
pub const DMA0_QM_CP_AWUSER_31_11_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_CP_AWUSER_31_11_VAL_MASK: c_uint = 0x1FFFFF;
// DMA0_QM_ARB_CFG_0
pub const DMA0_QM_ARB_CFG_0_TYPE_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_CFG_0_TYPE_MASK: c_uint = 0x1;
pub const DMA0_QM_ARB_CFG_0_IS_MASTER_SHIFT: c_int = 4;
pub const DMA0_QM_ARB_CFG_0_IS_MASTER_MASK: c_uint = 0x10;
pub const DMA0_QM_ARB_CFG_0_EN_SHIFT: c_int = 8;
pub const DMA0_QM_ARB_CFG_0_EN_MASK: c_uint = 0x100;
pub const DMA0_QM_ARB_CFG_0_MASK_SHIFT: c_int = 12;
pub const DMA0_QM_ARB_CFG_0_MASK_MASK: c_uint = 0xF000;
pub const DMA0_QM_ARB_CFG_0_MST_MSG_NOSTALL_SHIFT: c_int = 16;
pub const DMA0_QM_ARB_CFG_0_MST_MSG_NOSTALL_MASK: c_uint = 0x10000;
// DMA0_QM_ARB_CHOISE_Q_PUSH
pub const DMA0_QM_ARB_CHOISE_Q_PUSH_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_CHOISE_Q_PUSH_VAL_MASK: c_uint = 0x3;
// DMA0_QM_ARB_WRR_WEIGHT
pub const DMA0_QM_ARB_WRR_WEIGHT_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_WRR_WEIGHT_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_ARB_CFG_1
pub const DMA0_QM_ARB_CFG_1_CLR_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_CFG_1_CLR_MASK: c_uint = 0x1;
// DMA0_QM_ARB_MST_AVAIL_CRED
pub const DMA0_QM_ARB_MST_AVAIL_CRED_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_MST_AVAIL_CRED_VAL_MASK: c_uint = 0x7F;
// DMA0_QM_ARB_MST_CRED_INC
pub const DMA0_QM_ARB_MST_CRED_INC_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_MST_CRED_INC_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_ARB_MST_CHOISE_PUSH_OFST
pub const DMA0_QM_ARB_MST_CHOISE_PUSH_OFST_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_MST_CHOISE_PUSH_OFST_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_ARB_SLV_MASTER_INC_CRED_OFST
pub const DMA0_QM_ARB_SLV_MASTER_INC_CRED_OFST_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_SLV_MASTER_INC_CRED_OFST_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_ARB_MST_SLAVE_EN
pub const DMA0_QM_ARB_MST_SLAVE_EN_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_MST_SLAVE_EN_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_ARB_MST_QUIET_PER
pub const DMA0_QM_ARB_MST_QUIET_PER_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_MST_QUIET_PER_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_ARB_SLV_CHOISE_WDT
pub const DMA0_QM_ARB_SLV_CHOISE_WDT_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_SLV_CHOISE_WDT_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_ARB_SLV_ID
pub const DMA0_QM_ARB_SLV_ID_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_SLV_ID_VAL_MASK: c_uint = 0x1F;
// DMA0_QM_ARB_MSG_MAX_INFLIGHT
pub const DMA0_QM_ARB_MSG_MAX_INFLIGHT_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_MSG_MAX_INFLIGHT_VAL_MASK: c_uint = 0x3F;
// DMA0_QM_ARB_MSG_AWUSER_31_11
pub const DMA0_QM_ARB_MSG_AWUSER_31_11_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_MSG_AWUSER_31_11_VAL_MASK: c_uint = 0x1FFFFF;
// DMA0_QM_ARB_MSG_AWUSER_SEC_PROP
pub const DMA0_QM_ARB_MSG_AWUSER_SEC_PROP_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_MSG_AWUSER_SEC_PROP_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_ARB_MSG_AWUSER_SEC_PROP_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_ARB_MSG_AWUSER_SEC_PROP_MMBP_MASK: c_uint = 0x400;
// DMA0_QM_ARB_MSG_AWUSER_NON_SEC_PROP
pub const DMA0_QM_ARB_MSG_AWUSER_NON_SEC_PROP_ASID_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_MSG_AWUSER_NON_SEC_PROP_ASID_MASK: c_uint = 0x3FF;
pub const DMA0_QM_ARB_MSG_AWUSER_NON_SEC_PROP_MMBP_SHIFT: c_int = 10;
pub const DMA0_QM_ARB_MSG_AWUSER_NON_SEC_PROP_MMBP_MASK: c_uint = 0x400;
// DMA0_QM_ARB_BASE_LO
pub const DMA0_QM_ARB_BASE_LO_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_ARB_BASE_HI
pub const DMA0_QM_ARB_BASE_HI_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_ARB_STATE_STS
pub const DMA0_QM_ARB_STATE_STS_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_STATE_STS_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_ARB_CHOISE_FULLNESS_STS
pub const DMA0_QM_ARB_CHOISE_FULLNESS_STS_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_CHOISE_FULLNESS_STS_VAL_MASK: c_uint = 0x7F;
// DMA0_QM_ARB_MSG_STS
pub const DMA0_QM_ARB_MSG_STS_FULL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_MSG_STS_FULL_MASK: c_uint = 0x1;
pub const DMA0_QM_ARB_MSG_STS_NO_INFLIGHT_SHIFT: c_int = 1;
pub const DMA0_QM_ARB_MSG_STS_NO_INFLIGHT_MASK: c_uint = 0x2;
// DMA0_QM_ARB_SLV_CHOISE_Q_HEAD
pub const DMA0_QM_ARB_SLV_CHOISE_Q_HEAD_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_SLV_CHOISE_Q_HEAD_VAL_MASK: c_uint = 0x3;
// DMA0_QM_ARB_ERR_CAUSE
pub const DMA0_QM_ARB_ERR_CAUSE_CHOISE_OVF_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_ERR_CAUSE_CHOISE_OVF_MASK: c_uint = 0x1;
pub const DMA0_QM_ARB_ERR_CAUSE_CHOISE_WDT_SHIFT: c_int = 1;
pub const DMA0_QM_ARB_ERR_CAUSE_CHOISE_WDT_MASK: c_uint = 0x2;
pub const DMA0_QM_ARB_ERR_CAUSE_AXI_LBW_ERR_SHIFT: c_int = 2;
pub const DMA0_QM_ARB_ERR_CAUSE_AXI_LBW_ERR_MASK: c_uint = 0x4;
// DMA0_QM_ARB_ERR_MSG_EN
pub const DMA0_QM_ARB_ERR_MSG_EN_CHOISE_OVF_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_ERR_MSG_EN_CHOISE_OVF_MASK: c_uint = 0x1;
pub const DMA0_QM_ARB_ERR_MSG_EN_CHOISE_WDT_SHIFT: c_int = 1;
pub const DMA0_QM_ARB_ERR_MSG_EN_CHOISE_WDT_MASK: c_uint = 0x2;
pub const DMA0_QM_ARB_ERR_MSG_EN_AXI_LBW_ERR_SHIFT: c_int = 2;
pub const DMA0_QM_ARB_ERR_MSG_EN_AXI_LBW_ERR_MASK: c_uint = 0x4;
// DMA0_QM_ARB_ERR_STS_DRP
pub const DMA0_QM_ARB_ERR_STS_DRP_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_ERR_STS_DRP_VAL_MASK: c_uint = 0x3;
// DMA0_QM_ARB_MST_CRED_STS
pub const DMA0_QM_ARB_MST_CRED_STS_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_ARB_MST_CRED_STS_VAL_MASK: c_uint = 0x7F;
// DMA0_QM_CGM_CFG
pub const DMA0_QM_CGM_CFG_IDLE_TH_SHIFT: c_int = 0;
pub const DMA0_QM_CGM_CFG_IDLE_TH_MASK: c_uint = 0xFFF;
pub const DMA0_QM_CGM_CFG_G2F_TH_SHIFT: c_int = 16;
pub const DMA0_QM_CGM_CFG_G2F_TH_MASK: c_uint = 0xFF0000;
pub const DMA0_QM_CGM_CFG_CP_IDLE_MASK_SHIFT: c_int = 24;
pub const DMA0_QM_CGM_CFG_CP_IDLE_MASK_MASK: c_uint = 0x1F000000;
pub const DMA0_QM_CGM_CFG_EN_SHIFT: c_int = 31;
pub const DMA0_QM_CGM_CFG_EN_MASK: c_uint = 0x80000000;
// DMA0_QM_CGM_STS
pub const DMA0_QM_CGM_STS_ST_SHIFT: c_int = 0;
pub const DMA0_QM_CGM_STS_ST_MASK: c_uint = 0x3;
pub const DMA0_QM_CGM_STS_CG_SHIFT: c_int = 4;
pub const DMA0_QM_CGM_STS_CG_MASK: c_uint = 0x10;
pub const DMA0_QM_CGM_STS_AGENT_IDLE_SHIFT: c_int = 8;
pub const DMA0_QM_CGM_STS_AGENT_IDLE_MASK: c_uint = 0x100;
pub const DMA0_QM_CGM_STS_AXI_IDLE_SHIFT: c_int = 9;
pub const DMA0_QM_CGM_STS_AXI_IDLE_MASK: c_uint = 0x200;
pub const DMA0_QM_CGM_STS_CP_IDLE_SHIFT: c_int = 10;
pub const DMA0_QM_CGM_STS_CP_IDLE_MASK: c_uint = 0x400;
// DMA0_QM_CGM_CFG1
pub const DMA0_QM_CGM_CFG1_MASK_TH_SHIFT: c_int = 0;
pub const DMA0_QM_CGM_CFG1_MASK_TH_MASK: c_uint = 0xFF;
// DMA0_QM_LOCAL_RANGE_BASE
pub const DMA0_QM_LOCAL_RANGE_BASE_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_LOCAL_RANGE_BASE_VAL_MASK: c_uint = 0xFFFF;
// DMA0_QM_LOCAL_RANGE_SIZE
pub const DMA0_QM_LOCAL_RANGE_SIZE_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_LOCAL_RANGE_SIZE_VAL_MASK: c_uint = 0xFFFF;
// DMA0_QM_CSMR_STRICT_PRIO_CFG
pub const DMA0_QM_CSMR_STRICT_PRIO_CFG_TYPE_SHIFT: c_int = 0;
pub const DMA0_QM_CSMR_STRICT_PRIO_CFG_TYPE_MASK: c_uint = 0x1;
// DMA0_QM_HBW_RD_RATE_LIM_CFG_1
pub const DMA0_QM_HBW_RD_RATE_LIM_CFG_1_TOUT_SHIFT: c_int = 0;
pub const DMA0_QM_HBW_RD_RATE_LIM_CFG_1_TOUT_MASK: c_uint = 0xFF;
pub const DMA0_QM_HBW_RD_RATE_LIM_CFG_1_EN_SHIFT: c_int = 31;
pub const DMA0_QM_HBW_RD_RATE_LIM_CFG_1_EN_MASK: c_uint = 0x80000000;
// DMA0_QM_LBW_WR_RATE_LIM_CFG_0
pub const DMA0_QM_LBW_WR_RATE_LIM_CFG_0_RST_TOKEN_SHIFT: c_int = 0;
pub const DMA0_QM_LBW_WR_RATE_LIM_CFG_0_RST_TOKEN_MASK: c_uint = 0xFF;
pub const DMA0_QM_LBW_WR_RATE_LIM_CFG_0_SAT_SHIFT: c_int = 16;
pub const DMA0_QM_LBW_WR_RATE_LIM_CFG_0_SAT_MASK: c_uint = 0xFF0000;
// DMA0_QM_LBW_WR_RATE_LIM_CFG_1
pub const DMA0_QM_LBW_WR_RATE_LIM_CFG_1_TOUT_SHIFT: c_int = 0;
pub const DMA0_QM_LBW_WR_RATE_LIM_CFG_1_TOUT_MASK: c_uint = 0xFF;
pub const DMA0_QM_LBW_WR_RATE_LIM_CFG_1_EN_SHIFT: c_int = 31;
pub const DMA0_QM_LBW_WR_RATE_LIM_CFG_1_EN_MASK: c_uint = 0x80000000;
// DMA0_QM_HBW_RD_RATE_LIM_CFG_0
pub const DMA0_QM_HBW_RD_RATE_LIM_CFG_0_RST_TOKEN_SHIFT: c_int = 0;
pub const DMA0_QM_HBW_RD_RATE_LIM_CFG_0_RST_TOKEN_MASK: c_uint = 0xFF;
pub const DMA0_QM_HBW_RD_RATE_LIM_CFG_0_SAT_SHIFT: c_int = 16;
pub const DMA0_QM_HBW_RD_RATE_LIM_CFG_0_SAT_MASK: c_uint = 0xFF0000;
// DMA0_QM_GLBL_AXCACHE
pub const DMA0_QM_GLBL_AXCACHE_AR_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_AXCACHE_AR_MASK: c_uint = 0xF;
pub const DMA0_QM_GLBL_AXCACHE_AW_SHIFT: c_int = 16;
pub const DMA0_QM_GLBL_AXCACHE_AW_MASK: c_uint = 0xF0000;
// DMA0_QM_IND_GW_APB_CFG
pub const DMA0_QM_IND_GW_APB_CFG_ADDR_SHIFT: c_int = 0;
pub const DMA0_QM_IND_GW_APB_CFG_ADDR_MASK: c_uint = 0x7FFFFFFF;
pub const DMA0_QM_IND_GW_APB_CFG_CMD_SHIFT: c_int = 31;
pub const DMA0_QM_IND_GW_APB_CFG_CMD_MASK: c_uint = 0x80000000;
// DMA0_QM_IND_GW_APB_WDATA
pub const DMA0_QM_IND_GW_APB_WDATA_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_IND_GW_APB_WDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_IND_GW_APB_RDATA
pub const DMA0_QM_IND_GW_APB_RDATA_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_IND_GW_APB_RDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_IND_GW_APB_STATUS
pub const DMA0_QM_IND_GW_APB_STATUS_RDY_SHIFT: c_int = 0;
pub const DMA0_QM_IND_GW_APB_STATUS_RDY_MASK: c_uint = 0x1;
pub const DMA0_QM_IND_GW_APB_STATUS_ERR_SHIFT: c_int = 1;
pub const DMA0_QM_IND_GW_APB_STATUS_ERR_MASK: c_uint = 0x2;
// DMA0_QM_GLBL_ERR_ADDR_LO
pub const DMA0_QM_GLBL_ERR_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_ERR_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_GLBL_ERR_ADDR_HI
pub const DMA0_QM_GLBL_ERR_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_ERR_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_GLBL_ERR_WDATA
pub const DMA0_QM_GLBL_ERR_WDATA_VAL_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_ERR_WDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// DMA0_QM_GLBL_MEM_INIT_BUSY
pub const DMA0_QM_GLBL_MEM_INIT_BUSY_RBUF_SHIFT: c_int = 0;
pub const DMA0_QM_GLBL_MEM_INIT_BUSY_RBUF_MASK: c_uint = 0xF;
