//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/net/ethernet/chelsio/cxgb3/sge_defs.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// This file is automatically generated --- any changes will be lost.
//
pub const S_EC_CREDITS: c_int = 0;
pub const M_EC_CREDITS: c_uint = 0x7FFF;

pub const S_EC_GTS: c_int = 15;

pub const S_EC_INDEX: c_int = 16;
pub const M_EC_INDEX: c_uint = 0xFFFF;

pub const S_EC_SIZE: c_int = 0;
pub const M_EC_SIZE: c_uint = 0xFFFF;

pub const S_EC_BASE_LO: c_int = 16;
pub const M_EC_BASE_LO: c_uint = 0xFFFF;

pub const S_EC_BASE_HI: c_int = 0;
pub const M_EC_BASE_HI: c_uint = 0xF;

pub const S_EC_RESPQ: c_int = 4;
pub const M_EC_RESPQ: c_uint = 0x7;

pub const S_EC_TYPE: c_int = 7;
pub const M_EC_TYPE: c_uint = 0x7;

pub const S_EC_GEN: c_int = 10;

pub const S_EC_UP_TOKEN: c_int = 11;
pub const M_EC_UP_TOKEN: c_uint = 0xFFFFF;

pub const S_EC_VALID: c_int = 31;

pub const S_RQ_MSI_VEC: c_int = 20;
pub const M_RQ_MSI_VEC: c_uint = 0x3F;

pub const S_RQ_INTR_EN: c_int = 26;

pub const S_RQ_GEN: c_int = 28;

pub const S_CQ_INDEX: c_int = 0;
pub const M_CQ_INDEX: c_uint = 0xFFFF;

pub const S_CQ_SIZE: c_int = 16;
pub const M_CQ_SIZE: c_uint = 0xFFFF;

pub const S_CQ_BASE_HI: c_int = 0;
pub const M_CQ_BASE_HI: c_uint = 0xFFFFF;

pub const S_CQ_RSPQ: c_int = 20;
pub const M_CQ_RSPQ: c_uint = 0x3F;

pub const S_CQ_ASYNC_NOTIF: c_int = 26;

pub const S_CQ_ARMED: c_int = 27;

pub const S_CQ_ASYNC_NOTIF_SOL: c_int = 28;

pub const S_CQ_GEN: c_int = 29;

pub const S_CQ_ERR: c_int = 30;

pub const S_CQ_OVERFLOW_MODE: c_int = 31;

pub const S_CQ_CREDITS: c_int = 0;
pub const M_CQ_CREDITS: c_uint = 0xFFFF;

pub const S_CQ_CREDIT_THRES: c_int = 16;
pub const M_CQ_CREDIT_THRES: c_uint = 0x1FFF;

pub const S_FL_BASE_HI: c_int = 0;
pub const M_FL_BASE_HI: c_uint = 0xFFFFF;

pub const S_FL_INDEX_LO: c_int = 20;
pub const M_FL_INDEX_LO: c_uint = 0xFFF;

pub const S_FL_INDEX_HI: c_int = 0;
pub const M_FL_INDEX_HI: c_uint = 0xF;

pub const S_FL_SIZE: c_int = 4;
pub const M_FL_SIZE: c_uint = 0xFFFF;

pub const S_FL_GEN: c_int = 20;

pub const S_FL_ENTRY_SIZE_LO: c_int = 21;
pub const M_FL_ENTRY_SIZE_LO: c_uint = 0x7FF;

pub const S_FL_ENTRY_SIZE_HI: c_int = 0;
pub const M_FL_ENTRY_SIZE_HI: c_uint = 0x1FFFFF;

pub const S_FL_CONG_THRES: c_int = 21;
pub const M_FL_CONG_THRES: c_uint = 0x3FF;

pub const S_FL_GTS: c_int = 31;

pub const S_FLD_GEN1: c_int = 31;

pub const S_FLD_GEN2: c_int = 0;

pub const S_RSPD_TXQ1_CR: c_int = 0;
pub const M_RSPD_TXQ1_CR: c_uint = 0x7F;

pub const S_RSPD_TXQ1_GTS: c_int = 7;

pub const S_RSPD_TXQ2_CR: c_int = 8;
pub const M_RSPD_TXQ2_CR: c_uint = 0x7F;

pub const S_RSPD_TXQ2_GTS: c_int = 15;

pub const S_RSPD_TXQ0_CR: c_int = 16;
pub const M_RSPD_TXQ0_CR: c_uint = 0x7F;

pub const S_RSPD_TXQ0_GTS: c_int = 23;

pub const S_RSPD_EOP: c_int = 24;

pub const S_RSPD_SOP: c_int = 25;

pub const S_RSPD_ASYNC_NOTIF: c_int = 26;

pub const S_RSPD_FL0_GTS: c_int = 27;

pub const S_RSPD_FL1_GTS: c_int = 28;

pub const S_RSPD_IMM_DATA_VALID: c_int = 29;

pub const S_RSPD_OFFLOAD: c_int = 30;

pub const S_RSPD_GEN1: c_int = 31;

pub const S_RSPD_LEN: c_int = 0;
pub const M_RSPD_LEN: c_uint = 0x7FFFFFFF;

pub const S_RSPD_FLQ: c_int = 31;

pub const S_RSPD_GEN2: c_int = 0;

pub const S_RSPD_INR_VEC: c_int = 1;
pub const M_RSPD_INR_VEC: c_uint = 0x7F;

