//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/goya/asic_reg/mme_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2018 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// MME (Prototype: MME)
//
// MME_ARCH_STATUS
pub const MME_ARCH_STATUS_A_SHIFT: c_int = 0;
pub const MME_ARCH_STATUS_A_MASK: c_uint = 0x1;
pub const MME_ARCH_STATUS_B_SHIFT: c_int = 1;
pub const MME_ARCH_STATUS_B_MASK: c_uint = 0x2;
pub const MME_ARCH_STATUS_CIN_SHIFT: c_int = 2;
pub const MME_ARCH_STATUS_CIN_MASK: c_uint = 0x4;
pub const MME_ARCH_STATUS_COUT_SHIFT: c_int = 3;
pub const MME_ARCH_STATUS_COUT_MASK: c_uint = 0x8;
pub const MME_ARCH_STATUS_TE_SHIFT: c_int = 4;
pub const MME_ARCH_STATUS_TE_MASK: c_uint = 0x10;
pub const MME_ARCH_STATUS_LD_SHIFT: c_int = 5;
pub const MME_ARCH_STATUS_LD_MASK: c_uint = 0x20;
pub const MME_ARCH_STATUS_ST_SHIFT: c_int = 6;
pub const MME_ARCH_STATUS_ST_MASK: c_uint = 0x40;
pub const MME_ARCH_STATUS_SB_A_EMPTY_SHIFT: c_int = 7;
pub const MME_ARCH_STATUS_SB_A_EMPTY_MASK: c_uint = 0x80;
pub const MME_ARCH_STATUS_SB_B_EMPTY_SHIFT: c_int = 8;
pub const MME_ARCH_STATUS_SB_B_EMPTY_MASK: c_uint = 0x100;
pub const MME_ARCH_STATUS_SB_CIN_EMPTY_SHIFT: c_int = 9;
pub const MME_ARCH_STATUS_SB_CIN_EMPTY_MASK: c_uint = 0x200;
pub const MME_ARCH_STATUS_SB_COUT_EMPTY_SHIFT: c_int = 10;
pub const MME_ARCH_STATUS_SB_COUT_EMPTY_MASK: c_uint = 0x400;
pub const MME_ARCH_STATUS_SM_IDLE_SHIFT: c_int = 11;
pub const MME_ARCH_STATUS_SM_IDLE_MASK: c_uint = 0x800;
pub const MME_ARCH_STATUS_WBC_AXI_IDLE_SHIFT: c_int = 12;
pub const MME_ARCH_STATUS_WBC_AXI_IDLE_MASK: c_uint = 0xF000;
pub const MME_ARCH_STATUS_SBC_AXI_IDLE_SHIFT: c_int = 16;
pub const MME_ARCH_STATUS_SBC_AXI_IDLE_MASK: c_uint = 0x30000;
pub const MME_ARCH_STATUS_SBB_AXI_IDLE_SHIFT: c_int = 18;
pub const MME_ARCH_STATUS_SBB_AXI_IDLE_MASK: c_uint = 0xC0000;
pub const MME_ARCH_STATUS_SBA_AXI_IDLE_SHIFT: c_int = 20;
pub const MME_ARCH_STATUS_SBA_AXI_IDLE_MASK: c_uint = 0x300000;
pub const MME_ARCH_STATUS_FREE_ACCUMS_SHIFT: c_int = 22;
pub const MME_ARCH_STATUS_FREE_ACCUMS_MASK: c_uint = 0x1C00000;
// MME_ARCH_A_BASE_ADDR_HIGH
pub const MME_ARCH_A_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_ARCH_A_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_B_BASE_ADDR_HIGH
pub const MME_ARCH_B_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_ARCH_B_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_CIN_BASE_ADDR_HIGH
pub const MME_ARCH_CIN_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_ARCH_CIN_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_COUT_BASE_ADDR_HIGH
pub const MME_ARCH_COUT_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_ARCH_COUT_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_BIAS_BASE_ADDR_HIGH
pub const MME_ARCH_BIAS_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_ARCH_BIAS_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_A_BASE_ADDR_LOW
pub const MME_ARCH_A_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_ARCH_A_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_B_BASE_ADDR_LOW
pub const MME_ARCH_B_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_ARCH_B_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_CIN_BASE_ADDR_LOW
pub const MME_ARCH_CIN_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_ARCH_CIN_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_COUT_BASE_ADDR_LOW
pub const MME_ARCH_COUT_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_ARCH_COUT_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_BIAS_BASE_ADDR_LOW
pub const MME_ARCH_BIAS_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_ARCH_BIAS_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_HEADER
pub const MME_ARCH_HEADER_SIGNAL_MASK_SHIFT: c_int = 0;
pub const MME_ARCH_HEADER_SIGNAL_MASK_MASK: c_uint = 0x1F;
pub const MME_ARCH_HEADER_SIGNAL_EN_SHIFT: c_int = 5;
pub const MME_ARCH_HEADER_SIGNAL_EN_MASK: c_uint = 0x20;
pub const MME_ARCH_HEADER_TRANS_A_SHIFT: c_int = 6;
pub const MME_ARCH_HEADER_TRANS_A_MASK: c_uint = 0x40;
pub const MME_ARCH_HEADER_LOWER_A_SHIFT: c_int = 7;
pub const MME_ARCH_HEADER_LOWER_A_MASK: c_uint = 0x80;
pub const MME_ARCH_HEADER_ACCUM_MASK_SHIFT: c_int = 8;
pub const MME_ARCH_HEADER_ACCUM_MASK_MASK: c_uint = 0xF00;
pub const MME_ARCH_HEADER_LOAD_BIAS_SHIFT: c_int = 12;
pub const MME_ARCH_HEADER_LOAD_BIAS_MASK: c_uint = 0x1000;
pub const MME_ARCH_HEADER_LOAD_CIN_SHIFT: c_int = 13;
pub const MME_ARCH_HEADER_LOAD_CIN_MASK: c_uint = 0x2000;
pub const MME_ARCH_HEADER_STORE_OUT_SHIFT: c_int = 15;
pub const MME_ARCH_HEADER_STORE_OUT_MASK: c_uint = 0x8000;
pub const MME_ARCH_HEADER_ACC_LD_INC_DISABLE_SHIFT: c_int = 16;
pub const MME_ARCH_HEADER_ACC_LD_INC_DISABLE_MASK: c_uint = 0x10000;
pub const MME_ARCH_HEADER_ADVANCE_A_SHIFT: c_int = 17;
pub const MME_ARCH_HEADER_ADVANCE_A_MASK: c_uint = 0x20000;
pub const MME_ARCH_HEADER_ADVANCE_B_SHIFT: c_int = 18;
pub const MME_ARCH_HEADER_ADVANCE_B_MASK: c_uint = 0x40000;
pub const MME_ARCH_HEADER_ADVANCE_CIN_SHIFT: c_int = 19;
pub const MME_ARCH_HEADER_ADVANCE_CIN_MASK: c_uint = 0x80000;
pub const MME_ARCH_HEADER_ADVANCE_COUT_SHIFT: c_int = 20;
pub const MME_ARCH_HEADER_ADVANCE_COUT_MASK: c_uint = 0x100000;
pub const MME_ARCH_HEADER_COMPRESSED_B_SHIFT: c_int = 21;
pub const MME_ARCH_HEADER_COMPRESSED_B_MASK: c_uint = 0x200000;
pub const MME_ARCH_HEADER_MASK_CONV_END_SHIFT: c_int = 22;
pub const MME_ARCH_HEADER_MASK_CONV_END_MASK: c_uint = 0x400000;
pub const MME_ARCH_HEADER_ACC_ST_INC_DISABLE_SHIFT: c_int = 23;
pub const MME_ARCH_HEADER_ACC_ST_INC_DISABLE_MASK: c_uint = 0x800000;
pub const MME_ARCH_HEADER_AB_DATA_TYPE_SHIFT: c_int = 24;
pub const MME_ARCH_HEADER_AB_DATA_TYPE_MASK: c_uint = 0x3000000;
pub const MME_ARCH_HEADER_CIN_DATA_TYPE_SHIFT: c_int = 26;
pub const MME_ARCH_HEADER_CIN_DATA_TYPE_MASK: c_uint = 0x1C000000;
pub const MME_ARCH_HEADER_COUT_DATA_TYPE_SHIFT: c_int = 29;
pub const MME_ARCH_HEADER_COUT_DATA_TYPE_MASK: c_uint = 0xE0000000;
// MME_ARCH_KERNEL_SIZE_MINUS_1
pub const MME_ARCH_KERNEL_SIZE_MINUS_1_DIM_0_SHIFT: c_int = 0;
pub const MME_ARCH_KERNEL_SIZE_MINUS_1_DIM_0_MASK: c_uint = 0xFF;
pub const MME_ARCH_KERNEL_SIZE_MINUS_1_DIM_1_SHIFT: c_int = 8;
pub const MME_ARCH_KERNEL_SIZE_MINUS_1_DIM_1_MASK: c_uint = 0xFF00;
pub const MME_ARCH_KERNEL_SIZE_MINUS_1_DIM_2_SHIFT: c_int = 16;
pub const MME_ARCH_KERNEL_SIZE_MINUS_1_DIM_2_MASK: c_uint = 0xFF0000;
pub const MME_ARCH_KERNEL_SIZE_MINUS_1_DIM_3_SHIFT: c_int = 24;
pub const MME_ARCH_KERNEL_SIZE_MINUS_1_DIM_3_MASK: c_uint = 0xFF000000;
// MME_ARCH_ASSOCIATED_DIMS
pub const MME_ARCH_ASSOCIATED_DIMS_A_0_SHIFT: c_int = 0;
pub const MME_ARCH_ASSOCIATED_DIMS_A_0_MASK: c_uint = 0x7;
pub const MME_ARCH_ASSOCIATED_DIMS_B_0_SHIFT: c_int = 3;
pub const MME_ARCH_ASSOCIATED_DIMS_B_0_MASK: c_uint = 0x38;
pub const MME_ARCH_ASSOCIATED_DIMS_CIN_0_SHIFT: c_int = 6;
pub const MME_ARCH_ASSOCIATED_DIMS_CIN_0_MASK: c_uint = 0x1C0;
pub const MME_ARCH_ASSOCIATED_DIMS_COUT_0_SHIFT: c_int = 9;
pub const MME_ARCH_ASSOCIATED_DIMS_COUT_0_MASK: c_uint = 0xE00;
pub const MME_ARCH_ASSOCIATED_DIMS_A_1_SHIFT: c_int = 16;
pub const MME_ARCH_ASSOCIATED_DIMS_A_1_MASK: c_uint = 0x70000;
pub const MME_ARCH_ASSOCIATED_DIMS_B_1_SHIFT: c_int = 19;
pub const MME_ARCH_ASSOCIATED_DIMS_B_1_MASK: c_uint = 0x380000;
pub const MME_ARCH_ASSOCIATED_DIMS_CIN_1_SHIFT: c_int = 22;
pub const MME_ARCH_ASSOCIATED_DIMS_CIN_1_MASK: c_uint = 0x1C00000;
pub const MME_ARCH_ASSOCIATED_DIMS_COUT_1_SHIFT: c_int = 25;
pub const MME_ARCH_ASSOCIATED_DIMS_COUT_1_MASK: c_uint = 0xE000000;
// MME_ARCH_COUT_SCALE
pub const MME_ARCH_COUT_SCALE_V_SHIFT: c_int = 0;
pub const MME_ARCH_COUT_SCALE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_CIN_SCALE
pub const MME_ARCH_CIN_SCALE_V_SHIFT: c_int = 0;
pub const MME_ARCH_CIN_SCALE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_GEMMLOWP_ZP
pub const MME_ARCH_GEMMLOWP_ZP_ZP_CIN_SHIFT: c_int = 0;
pub const MME_ARCH_GEMMLOWP_ZP_ZP_CIN_MASK: c_uint = 0x1FF;
pub const MME_ARCH_GEMMLOWP_ZP_ZP_COUT_SHIFT: c_int = 9;
pub const MME_ARCH_GEMMLOWP_ZP_ZP_COUT_MASK: c_uint = 0x3FE00;
pub const MME_ARCH_GEMMLOWP_ZP_ZP_B_SHIFT: c_int = 18;
pub const MME_ARCH_GEMMLOWP_ZP_ZP_B_MASK: c_uint = 0x7FC0000;
pub const MME_ARCH_GEMMLOWP_ZP_GEMMLOWP_EU_EN_SHIFT: c_int = 27;
pub const MME_ARCH_GEMMLOWP_ZP_GEMMLOWP_EU_EN_MASK: c_uint = 0x8000000;
pub const MME_ARCH_GEMMLOWP_ZP_ACCUM_SHIFT: c_int = 28;
pub const MME_ARCH_GEMMLOWP_ZP_ACCUM_MASK: c_uint = 0x10000000;
pub const MME_ARCH_GEMMLOWP_ZP_ACCUM_BIAS_SHIFT: c_int = 29;
pub const MME_ARCH_GEMMLOWP_ZP_ACCUM_BIAS_MASK: c_uint = 0x20000000;
pub const MME_ARCH_GEMMLOWP_ZP_RELU_EN_SHIFT: c_int = 30;
pub const MME_ARCH_GEMMLOWP_ZP_RELU_EN_MASK: c_uint = 0x40000000;
// MME_ARCH_GEMMLOWP_EXPONENT
pub const MME_ARCH_GEMMLOWP_EXPONENT_EXPONENT_CIN_SHIFT: c_int = 0;
pub const MME_ARCH_GEMMLOWP_EXPONENT_EXPONENT_CIN_MASK: c_uint = 0x3F;
pub const MME_ARCH_GEMMLOWP_EXPONENT_EXPONENT_COUT_SHIFT: c_int = 8;
pub const MME_ARCH_GEMMLOWP_EXPONENT_EXPONENT_COUT_MASK: c_uint = 0x3F00;
pub const MME_ARCH_GEMMLOWP_EXPONENT_MUL_CIN_EN_SHIFT: c_int = 16;
pub const MME_ARCH_GEMMLOWP_EXPONENT_MUL_CIN_EN_MASK: c_uint = 0x10000;
pub const MME_ARCH_GEMMLOWP_EXPONENT_MUL_COUT_EN_SHIFT: c_int = 17;
pub const MME_ARCH_GEMMLOWP_EXPONENT_MUL_COUT_EN_MASK: c_uint = 0x20000;
// MME_ARCH_A_ROI_BASE_OFFSET
pub const MME_ARCH_A_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_ARCH_A_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_A_VALID_ELEMENTS
pub const MME_ARCH_A_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_ARCH_A_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_A_LOOP_STRIDE
pub const MME_ARCH_A_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_ARCH_A_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_A_ROI_SIZE
pub const MME_ARCH_A_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_ARCH_A_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_A_SPATIAL_START_OFFSET
pub const MME_ARCH_A_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_ARCH_A_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_A_SPATIAL_STRIDE
pub const MME_ARCH_A_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_ARCH_A_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_A_SPATIAL_SIZE_MINUS_1
pub const MME_ARCH_A_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_ARCH_A_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_B_ROI_BASE_OFFSET
pub const MME_ARCH_B_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_ARCH_B_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_B_VALID_ELEMENTS
pub const MME_ARCH_B_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_ARCH_B_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_B_LOOP_STRIDE
pub const MME_ARCH_B_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_ARCH_B_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_B_ROI_SIZE
pub const MME_ARCH_B_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_ARCH_B_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_B_SPATIAL_START_OFFSET
pub const MME_ARCH_B_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_ARCH_B_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_B_SPATIAL_STRIDE
pub const MME_ARCH_B_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_ARCH_B_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_B_SPATIAL_SIZE_MINUS_1
pub const MME_ARCH_B_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_ARCH_B_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_C_ROI_BASE_OFFSET
pub const MME_ARCH_C_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_ARCH_C_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_C_VALID_ELEMENTS
pub const MME_ARCH_C_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_ARCH_C_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_C_LOOP_STRIDE
pub const MME_ARCH_C_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_ARCH_C_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_C_ROI_SIZE
pub const MME_ARCH_C_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_ARCH_C_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_C_SPATIAL_START_OFFSET
pub const MME_ARCH_C_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_ARCH_C_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_C_SPATIAL_STRIDE
pub const MME_ARCH_C_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_ARCH_C_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_C_SPATIAL_SIZE_MINUS_1
pub const MME_ARCH_C_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_ARCH_C_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_SYNC_OBJECT_MESSAGE
pub const MME_ARCH_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_SHIFT: c_int = 0;
pub const MME_ARCH_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_MASK: c_uint = 0xFFFF;
pub const MME_ARCH_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_SHIFT: c_int = 16;
pub const MME_ARCH_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_MASK: c_uint = 0x7FFF0000;
pub const MME_ARCH_SYNC_OBJECT_MESSAGE_SO_OPERATION_SHIFT: c_int = 31;
pub const MME_ARCH_SYNC_OBJECT_MESSAGE_SO_OPERATION_MASK: c_uint = 0x80000000;
// MME_ARCH_E_PADDING_VALUE_A
pub const MME_ARCH_E_PADDING_VALUE_A_V_SHIFT: c_int = 0;
pub const MME_ARCH_E_PADDING_VALUE_A_V_MASK: c_uint = 0xFFFF;
// MME_ARCH_E_NUM_ITERATION_MINUS_1
pub const MME_ARCH_E_NUM_ITERATION_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_ARCH_E_NUM_ITERATION_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_ARCH_E_BUBBLES_PER_SPLIT
pub const MME_ARCH_E_BUBBLES_PER_SPLIT_A_SHIFT: c_int = 0;
pub const MME_ARCH_E_BUBBLES_PER_SPLIT_A_MASK: c_uint = 0xFF;
pub const MME_ARCH_E_BUBBLES_PER_SPLIT_B_SHIFT: c_int = 8;
pub const MME_ARCH_E_BUBBLES_PER_SPLIT_B_MASK: c_uint = 0xFF00;
pub const MME_ARCH_E_BUBBLES_PER_SPLIT_CIN_SHIFT: c_int = 16;
pub const MME_ARCH_E_BUBBLES_PER_SPLIT_CIN_MASK: c_uint = 0xFF0000;
pub const MME_ARCH_E_BUBBLES_PER_SPLIT_ID_SHIFT: c_int = 24;
pub const MME_ARCH_E_BUBBLES_PER_SPLIT_ID_MASK: c_uint = 0xFF000000;
// MME_CMD
pub const MME_CMD_EXECUTE_SHIFT: c_int = 0;
pub const MME_CMD_EXECUTE_MASK: c_uint = 0x1;
// MME_DUMMY
pub const MME_DUMMY_V_SHIFT: c_int = 0;
pub const MME_DUMMY_V_MASK: c_uint = 0xFFFFFFFF;
// MME_RESET
pub const MME_RESET_V_SHIFT: c_int = 0;
pub const MME_RESET_V_MASK: c_uint = 0x1;
// MME_STALL
pub const MME_STALL_V_SHIFT: c_int = 0;
pub const MME_STALL_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SM_BASE_ADDRESS_LOW
pub const MME_SM_BASE_ADDRESS_LOW_V_SHIFT: c_int = 0;
pub const MME_SM_BASE_ADDRESS_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SM_BASE_ADDRESS_HIGH
pub const MME_SM_BASE_ADDRESS_HIGH_V_SHIFT: c_int = 0;
pub const MME_SM_BASE_ADDRESS_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_DBGMEM_ADD
pub const MME_DBGMEM_ADD_V_SHIFT: c_int = 0;
pub const MME_DBGMEM_ADD_V_MASK: c_uint = 0xFFFFFFFF;
// MME_DBGMEM_DATA_WR
pub const MME_DBGMEM_DATA_WR_V_SHIFT: c_int = 0;
pub const MME_DBGMEM_DATA_WR_V_MASK: c_uint = 0xFFFFFFFF;
// MME_DBGMEM_DATA_RD
pub const MME_DBGMEM_DATA_RD_V_SHIFT: c_int = 0;
pub const MME_DBGMEM_DATA_RD_V_MASK: c_uint = 0xFFFFFFFF;
// MME_DBGMEM_CTRL
pub const MME_DBGMEM_CTRL_WR_NRD_SHIFT: c_int = 0;
pub const MME_DBGMEM_CTRL_WR_NRD_MASK: c_uint = 0x1;
// MME_DBGMEM_RC
pub const MME_DBGMEM_RC_VALID_SHIFT: c_int = 0;
pub const MME_DBGMEM_RC_VALID_MASK: c_uint = 0x1;
pub const MME_DBGMEM_RC_FULL_SHIFT: c_int = 1;
pub const MME_DBGMEM_RC_FULL_MASK: c_uint = 0x2;
// MME_LOG_SHADOW
pub const MME_LOG_SHADOW_MASK_0_SHIFT: c_int = 0;
pub const MME_LOG_SHADOW_MASK_0_MASK: c_uint = 0x7F;
pub const MME_LOG_SHADOW_MASK_1_SHIFT: c_int = 8;
pub const MME_LOG_SHADOW_MASK_1_MASK: c_uint = 0x7F00;
pub const MME_LOG_SHADOW_MASK_2_SHIFT: c_int = 16;
pub const MME_LOG_SHADOW_MASK_2_MASK: c_uint = 0x7F0000;
pub const MME_LOG_SHADOW_MASK_3_SHIFT: c_int = 24;
pub const MME_LOG_SHADOW_MASK_3_MASK: c_uint = 0x7F000000;
// MME_STORE_MAX_CREDIT
pub const MME_STORE_MAX_CREDIT_V_SHIFT: c_int = 0;
pub const MME_STORE_MAX_CREDIT_V_MASK: c_uint = 0x3F;
// MME_AGU
pub const MME_AGU_SBA_MAX_CREDIT_SHIFT: c_int = 0;
pub const MME_AGU_SBA_MAX_CREDIT_MASK: c_uint = 0x1F;
pub const MME_AGU_SBB_MAX_CREDIT_SHIFT: c_int = 8;
pub const MME_AGU_SBB_MAX_CREDIT_MASK: c_uint = 0x1F00;
pub const MME_AGU_SBC_MAX_CREDIT_SHIFT: c_int = 16;
pub const MME_AGU_SBC_MAX_CREDIT_MASK: c_uint = 0x1F0000;
pub const MME_AGU_WBC_MAX_CREDIT_SHIFT: c_int = 24;
pub const MME_AGU_WBC_MAX_CREDIT_MASK: c_uint = 0x3F000000;
// MME_SBA
pub const MME_SBA_MAX_SIZE_SHIFT: c_int = 0;
pub const MME_SBA_MAX_SIZE_MASK: c_uint = 0x3FF;
pub const MME_SBA_EU_MAX_CREDIT_SHIFT: c_int = 16;
pub const MME_SBA_EU_MAX_CREDIT_MASK: c_uint = 0x1F0000;
// MME_SBB
pub const MME_SBB_MAX_SIZE_SHIFT: c_int = 0;
pub const MME_SBB_MAX_SIZE_MASK: c_uint = 0x3FF;
pub const MME_SBB_EU_MAX_CREDIT_SHIFT: c_int = 16;
pub const MME_SBB_EU_MAX_CREDIT_MASK: c_uint = 0x1F0000;
// MME_SBC
pub const MME_SBC_MAX_SIZE_SHIFT: c_int = 0;
pub const MME_SBC_MAX_SIZE_MASK: c_uint = 0x3FF;
pub const MME_SBC_EU_MAX_CREDIT_SHIFT: c_int = 16;
pub const MME_SBC_EU_MAX_CREDIT_MASK: c_uint = 0x1F0000;
// MME_WBC
pub const MME_WBC_MAX_OUTSTANDING_SHIFT: c_int = 0;
pub const MME_WBC_MAX_OUTSTANDING_MASK: c_uint = 0xFFF;
pub const MME_WBC_DISABLE_FAST_END_PE_SHIFT: c_int = 12;
pub const MME_WBC_DISABLE_FAST_END_PE_MASK: c_uint = 0x1000;
pub const MME_WBC_LD_INSERT_BUBBLE_DIS_SHIFT: c_int = 13;
pub const MME_WBC_LD_INSERT_BUBBLE_DIS_MASK: c_uint = 0x2000;
// MME_SBA_CONTROL_DATA
pub const MME_SBA_CONTROL_DATA_ASID_SHIFT: c_int = 0;
pub const MME_SBA_CONTROL_DATA_ASID_MASK: c_uint = 0x3FF;
pub const MME_SBA_CONTROL_DATA_MMBP_SHIFT: c_int = 10;
pub const MME_SBA_CONTROL_DATA_MMBP_MASK: c_uint = 0x400;
// MME_SBB_CONTROL_DATA
pub const MME_SBB_CONTROL_DATA_ASID_SHIFT: c_int = 0;
pub const MME_SBB_CONTROL_DATA_ASID_MASK: c_uint = 0x3FF;
pub const MME_SBB_CONTROL_DATA_MMBP_SHIFT: c_int = 10;
pub const MME_SBB_CONTROL_DATA_MMBP_MASK: c_uint = 0x400;
// MME_SBC_CONTROL_DATA
pub const MME_SBC_CONTROL_DATA_ASID_SHIFT: c_int = 0;
pub const MME_SBC_CONTROL_DATA_ASID_MASK: c_uint = 0x3FF;
pub const MME_SBC_CONTROL_DATA_MMBP_SHIFT: c_int = 10;
pub const MME_SBC_CONTROL_DATA_MMBP_MASK: c_uint = 0x400;
// MME_WBC_CONTROL_DATA
pub const MME_WBC_CONTROL_DATA_ASID_SHIFT: c_int = 0;
pub const MME_WBC_CONTROL_DATA_ASID_MASK: c_uint = 0x3FF;
pub const MME_WBC_CONTROL_DATA_MMBP_SHIFT: c_int = 10;
pub const MME_WBC_CONTROL_DATA_MMBP_MASK: c_uint = 0x400;
// MME_TE
pub const MME_TE_MAX_CREDIT_SHIFT: c_int = 0;
pub const MME_TE_MAX_CREDIT_MASK: c_uint = 0x1F;
pub const MME_TE_DESC_MAX_CREDIT_SHIFT: c_int = 8;
pub const MME_TE_DESC_MAX_CREDIT_MASK: c_uint = 0x1F00;
// MME_TE2DEC
pub const MME_TE2DEC_MAX_CREDIT_SHIFT: c_int = 0;
pub const MME_TE2DEC_MAX_CREDIT_MASK: c_uint = 0x1F;
// MME_REI_STATUS
pub const MME_REI_STATUS_V_SHIFT: c_int = 0;
pub const MME_REI_STATUS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_REI_MASK
pub const MME_REI_MASK_V_SHIFT: c_int = 0;
pub const MME_REI_MASK_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SEI_STATUS
pub const MME_SEI_STATUS_V_SHIFT: c_int = 0;
pub const MME_SEI_STATUS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SEI_MASK
pub const MME_SEI_MASK_V_SHIFT: c_int = 0;
pub const MME_SEI_MASK_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SPI_STATUS
pub const MME_SPI_STATUS_V_SHIFT: c_int = 0;
pub const MME_SPI_STATUS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SPI_MASK
pub const MME_SPI_MASK_V_SHIFT: c_int = 0;
pub const MME_SPI_MASK_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_STATUS
pub const MME_SHADOW_0_STATUS_A_SHIFT: c_int = 0;
pub const MME_SHADOW_0_STATUS_A_MASK: c_uint = 0x1;
pub const MME_SHADOW_0_STATUS_B_SHIFT: c_int = 1;
pub const MME_SHADOW_0_STATUS_B_MASK: c_uint = 0x2;
pub const MME_SHADOW_0_STATUS_CIN_SHIFT: c_int = 2;
pub const MME_SHADOW_0_STATUS_CIN_MASK: c_uint = 0x4;
pub const MME_SHADOW_0_STATUS_COUT_SHIFT: c_int = 3;
pub const MME_SHADOW_0_STATUS_COUT_MASK: c_uint = 0x8;
pub const MME_SHADOW_0_STATUS_TE_SHIFT: c_int = 4;
pub const MME_SHADOW_0_STATUS_TE_MASK: c_uint = 0x10;
pub const MME_SHADOW_0_STATUS_LD_SHIFT: c_int = 5;
pub const MME_SHADOW_0_STATUS_LD_MASK: c_uint = 0x20;
pub const MME_SHADOW_0_STATUS_ST_SHIFT: c_int = 6;
pub const MME_SHADOW_0_STATUS_ST_MASK: c_uint = 0x40;
// MME_SHADOW_0_A_BASE_ADDR_HIGH
pub const MME_SHADOW_0_A_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_A_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_B_BASE_ADDR_HIGH
pub const MME_SHADOW_0_B_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_B_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_CIN_BASE_ADDR_HIGH
pub const MME_SHADOW_0_CIN_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_CIN_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_COUT_BASE_ADDR_HIGH
pub const MME_SHADOW_0_COUT_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_COUT_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_BIAS_BASE_ADDR_HIGH
pub const MME_SHADOW_0_BIAS_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_BIAS_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_A_BASE_ADDR_LOW
pub const MME_SHADOW_0_A_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_A_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_B_BASE_ADDR_LOW
pub const MME_SHADOW_0_B_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_B_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_CIN_BASE_ADDR_LOW
pub const MME_SHADOW_0_CIN_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_CIN_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_COUT_BASE_ADDR_LOW
pub const MME_SHADOW_0_COUT_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_COUT_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_BIAS_BASE_ADDR_LOW
pub const MME_SHADOW_0_BIAS_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_BIAS_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_HEADER
pub const MME_SHADOW_0_HEADER_SIGNAL_MASK_SHIFT: c_int = 0;
pub const MME_SHADOW_0_HEADER_SIGNAL_MASK_MASK: c_uint = 0x1F;
pub const MME_SHADOW_0_HEADER_SIGNAL_EN_SHIFT: c_int = 5;
pub const MME_SHADOW_0_HEADER_SIGNAL_EN_MASK: c_uint = 0x20;
pub const MME_SHADOW_0_HEADER_TRANS_A_SHIFT: c_int = 6;
pub const MME_SHADOW_0_HEADER_TRANS_A_MASK: c_uint = 0x40;
pub const MME_SHADOW_0_HEADER_LOWER_A_SHIFT: c_int = 7;
pub const MME_SHADOW_0_HEADER_LOWER_A_MASK: c_uint = 0x80;
pub const MME_SHADOW_0_HEADER_ACCUM_MASK_SHIFT: c_int = 8;
pub const MME_SHADOW_0_HEADER_ACCUM_MASK_MASK: c_uint = 0xF00;
pub const MME_SHADOW_0_HEADER_LOAD_BIAS_SHIFT: c_int = 12;
pub const MME_SHADOW_0_HEADER_LOAD_BIAS_MASK: c_uint = 0x1000;
pub const MME_SHADOW_0_HEADER_LOAD_CIN_SHIFT: c_int = 13;
pub const MME_SHADOW_0_HEADER_LOAD_CIN_MASK: c_uint = 0x2000;
pub const MME_SHADOW_0_HEADER_STORE_OUT_SHIFT: c_int = 15;
pub const MME_SHADOW_0_HEADER_STORE_OUT_MASK: c_uint = 0x8000;
pub const MME_SHADOW_0_HEADER_ACC_LD_INC_DISABLE_SHIFT: c_int = 16;
pub const MME_SHADOW_0_HEADER_ACC_LD_INC_DISABLE_MASK: c_uint = 0x10000;
pub const MME_SHADOW_0_HEADER_ADVANCE_A_SHIFT: c_int = 17;
pub const MME_SHADOW_0_HEADER_ADVANCE_A_MASK: c_uint = 0x20000;
pub const MME_SHADOW_0_HEADER_ADVANCE_B_SHIFT: c_int = 18;
pub const MME_SHADOW_0_HEADER_ADVANCE_B_MASK: c_uint = 0x40000;
pub const MME_SHADOW_0_HEADER_ADVANCE_CIN_SHIFT: c_int = 19;
pub const MME_SHADOW_0_HEADER_ADVANCE_CIN_MASK: c_uint = 0x80000;
pub const MME_SHADOW_0_HEADER_ADVANCE_COUT_SHIFT: c_int = 20;
pub const MME_SHADOW_0_HEADER_ADVANCE_COUT_MASK: c_uint = 0x100000;
pub const MME_SHADOW_0_HEADER_COMPRESSED_B_SHIFT: c_int = 21;
pub const MME_SHADOW_0_HEADER_COMPRESSED_B_MASK: c_uint = 0x200000;
pub const MME_SHADOW_0_HEADER_MASK_CONV_END_SHIFT: c_int = 22;
pub const MME_SHADOW_0_HEADER_MASK_CONV_END_MASK: c_uint = 0x400000;
pub const MME_SHADOW_0_HEADER_ACC_ST_INC_DISABLE_SHIFT: c_int = 23;
pub const MME_SHADOW_0_HEADER_ACC_ST_INC_DISABLE_MASK: c_uint = 0x800000;
pub const MME_SHADOW_0_HEADER_AB_DATA_TYPE_SHIFT: c_int = 24;
pub const MME_SHADOW_0_HEADER_AB_DATA_TYPE_MASK: c_uint = 0x3000000;
pub const MME_SHADOW_0_HEADER_CIN_DATA_TYPE_SHIFT: c_int = 26;
pub const MME_SHADOW_0_HEADER_CIN_DATA_TYPE_MASK: c_uint = 0x1C000000;
pub const MME_SHADOW_0_HEADER_COUT_DATA_TYPE_SHIFT: c_int = 29;
pub const MME_SHADOW_0_HEADER_COUT_DATA_TYPE_MASK: c_uint = 0xE0000000;
// MME_SHADOW_0_KERNEL_SIZE_MINUS_1
pub const MME_SHADOW_0_KERNEL_SIZE_MINUS_1_DIM_0_SHIFT: c_int = 0;
pub const MME_SHADOW_0_KERNEL_SIZE_MINUS_1_DIM_0_MASK: c_uint = 0xFF;
pub const MME_SHADOW_0_KERNEL_SIZE_MINUS_1_DIM_1_SHIFT: c_int = 8;
pub const MME_SHADOW_0_KERNEL_SIZE_MINUS_1_DIM_1_MASK: c_uint = 0xFF00;
pub const MME_SHADOW_0_KERNEL_SIZE_MINUS_1_DIM_2_SHIFT: c_int = 16;
pub const MME_SHADOW_0_KERNEL_SIZE_MINUS_1_DIM_2_MASK: c_uint = 0xFF0000;
pub const MME_SHADOW_0_KERNEL_SIZE_MINUS_1_DIM_3_SHIFT: c_int = 24;
pub const MME_SHADOW_0_KERNEL_SIZE_MINUS_1_DIM_3_MASK: c_uint = 0xFF000000;
// MME_SHADOW_0_ASSOCIATED_DIMS
pub const MME_SHADOW_0_ASSOCIATED_DIMS_A_0_SHIFT: c_int = 0;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_A_0_MASK: c_uint = 0x7;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_B_0_SHIFT: c_int = 3;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_B_0_MASK: c_uint = 0x38;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_CIN_0_SHIFT: c_int = 6;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_CIN_0_MASK: c_uint = 0x1C0;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_COUT_0_SHIFT: c_int = 9;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_COUT_0_MASK: c_uint = 0xE00;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_A_1_SHIFT: c_int = 16;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_A_1_MASK: c_uint = 0x70000;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_B_1_SHIFT: c_int = 19;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_B_1_MASK: c_uint = 0x380000;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_CIN_1_SHIFT: c_int = 22;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_CIN_1_MASK: c_uint = 0x1C00000;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_COUT_1_SHIFT: c_int = 25;
pub const MME_SHADOW_0_ASSOCIATED_DIMS_COUT_1_MASK: c_uint = 0xE000000;
// MME_SHADOW_0_COUT_SCALE
pub const MME_SHADOW_0_COUT_SCALE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_COUT_SCALE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_CIN_SCALE
pub const MME_SHADOW_0_CIN_SCALE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_CIN_SCALE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_GEMMLOWP_ZP
pub const MME_SHADOW_0_GEMMLOWP_ZP_ZP_CIN_SHIFT: c_int = 0;
pub const MME_SHADOW_0_GEMMLOWP_ZP_ZP_CIN_MASK: c_uint = 0x1FF;
pub const MME_SHADOW_0_GEMMLOWP_ZP_ZP_COUT_SHIFT: c_int = 9;
pub const MME_SHADOW_0_GEMMLOWP_ZP_ZP_COUT_MASK: c_uint = 0x3FE00;
pub const MME_SHADOW_0_GEMMLOWP_ZP_ZP_B_SHIFT: c_int = 18;
pub const MME_SHADOW_0_GEMMLOWP_ZP_ZP_B_MASK: c_uint = 0x7FC0000;
pub const MME_SHADOW_0_GEMMLOWP_ZP_GEMMLOWP_EU_EN_SHIFT: c_int = 27;
pub const MME_SHADOW_0_GEMMLOWP_ZP_GEMMLOWP_EU_EN_MASK: c_uint = 0x8000000;
pub const MME_SHADOW_0_GEMMLOWP_ZP_ACCUM_SHIFT: c_int = 28;
pub const MME_SHADOW_0_GEMMLOWP_ZP_ACCUM_MASK: c_uint = 0x10000000;
pub const MME_SHADOW_0_GEMMLOWP_ZP_ACCUM_BIAS_SHIFT: c_int = 29;
pub const MME_SHADOW_0_GEMMLOWP_ZP_ACCUM_BIAS_MASK: c_uint = 0x20000000;
pub const MME_SHADOW_0_GEMMLOWP_ZP_RELU_EN_SHIFT: c_int = 30;
pub const MME_SHADOW_0_GEMMLOWP_ZP_RELU_EN_MASK: c_uint = 0x40000000;
// MME_SHADOW_0_GEMMLOWP_EXPONENT
pub const MME_SHADOW_0_GEMMLOWP_EXPONENT_EXPONENT_CIN_SHIFT: c_int = 0;
pub const MME_SHADOW_0_GEMMLOWP_EXPONENT_EXPONENT_CIN_MASK: c_uint = 0x3F;
pub const MME_SHADOW_0_GEMMLOWP_EXPONENT_EXPONENT_COUT_SHIFT: c_int = 8;
pub const MME_SHADOW_0_GEMMLOWP_EXPONENT_EXPONENT_COUT_MASK: c_uint = 0x3F00;
pub const MME_SHADOW_0_GEMMLOWP_EXPONENT_MUL_CIN_EN_SHIFT: c_int = 16;
pub const MME_SHADOW_0_GEMMLOWP_EXPONENT_MUL_CIN_EN_MASK: c_uint = 0x10000;
pub const MME_SHADOW_0_GEMMLOWP_EXPONENT_MUL_COUT_EN_SHIFT: c_int = 17;
pub const MME_SHADOW_0_GEMMLOWP_EXPONENT_MUL_COUT_EN_MASK: c_uint = 0x20000;
// MME_SHADOW_0_A_ROI_BASE_OFFSET
pub const MME_SHADOW_0_A_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_A_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_A_VALID_ELEMENTS
pub const MME_SHADOW_0_A_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_A_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_A_LOOP_STRIDE
pub const MME_SHADOW_0_A_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_A_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_A_ROI_SIZE
pub const MME_SHADOW_0_A_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_A_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_A_SPATIAL_START_OFFSET
pub const MME_SHADOW_0_A_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_A_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_A_SPATIAL_STRIDE
pub const MME_SHADOW_0_A_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_A_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_A_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_0_A_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_A_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_B_ROI_BASE_OFFSET
pub const MME_SHADOW_0_B_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_B_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_B_VALID_ELEMENTS
pub const MME_SHADOW_0_B_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_B_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_B_LOOP_STRIDE
pub const MME_SHADOW_0_B_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_B_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_B_ROI_SIZE
pub const MME_SHADOW_0_B_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_B_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_B_SPATIAL_START_OFFSET
pub const MME_SHADOW_0_B_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_B_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_B_SPATIAL_STRIDE
pub const MME_SHADOW_0_B_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_B_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_B_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_0_B_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_B_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_C_ROI_BASE_OFFSET
pub const MME_SHADOW_0_C_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_C_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_C_VALID_ELEMENTS
pub const MME_SHADOW_0_C_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_C_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_C_LOOP_STRIDE
pub const MME_SHADOW_0_C_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_C_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_C_ROI_SIZE
pub const MME_SHADOW_0_C_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_C_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_C_SPATIAL_START_OFFSET
pub const MME_SHADOW_0_C_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_C_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_C_SPATIAL_STRIDE
pub const MME_SHADOW_0_C_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_C_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_C_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_0_C_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_C_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_SYNC_OBJECT_MESSAGE
pub const MME_SHADOW_0_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_SHIFT: c_int = 0;
pub const MME_SHADOW_0_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_MASK: c_uint = 0xFFFF;
pub const MME_SHADOW_0_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_SHIFT: c_int = 16;
pub const MME_SHADOW_0_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_MASK: c_uint = 0x7FFF0000;
pub const MME_SHADOW_0_SYNC_OBJECT_MESSAGE_SO_OPERATION_SHIFT: c_int = 31;
pub const MME_SHADOW_0_SYNC_OBJECT_MESSAGE_SO_OPERATION_MASK: c_uint = 0x80000000;
// MME_SHADOW_0_E_PADDING_VALUE_A
pub const MME_SHADOW_0_E_PADDING_VALUE_A_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_E_PADDING_VALUE_A_V_MASK: c_uint = 0xFFFF;
// MME_SHADOW_0_E_NUM_ITERATION_MINUS_1
pub const MME_SHADOW_0_E_NUM_ITERATION_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_0_E_NUM_ITERATION_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_0_E_BUBBLES_PER_SPLIT
pub const MME_SHADOW_0_E_BUBBLES_PER_SPLIT_A_SHIFT: c_int = 0;
pub const MME_SHADOW_0_E_BUBBLES_PER_SPLIT_A_MASK: c_uint = 0xFF;
pub const MME_SHADOW_0_E_BUBBLES_PER_SPLIT_B_SHIFT: c_int = 8;
pub const MME_SHADOW_0_E_BUBBLES_PER_SPLIT_B_MASK: c_uint = 0xFF00;
pub const MME_SHADOW_0_E_BUBBLES_PER_SPLIT_CIN_SHIFT: c_int = 16;
pub const MME_SHADOW_0_E_BUBBLES_PER_SPLIT_CIN_MASK: c_uint = 0xFF0000;
pub const MME_SHADOW_0_E_BUBBLES_PER_SPLIT_ID_SHIFT: c_int = 24;
pub const MME_SHADOW_0_E_BUBBLES_PER_SPLIT_ID_MASK: c_uint = 0xFF000000;
// MME_SHADOW_1_STATUS
pub const MME_SHADOW_1_STATUS_A_SHIFT: c_int = 0;
pub const MME_SHADOW_1_STATUS_A_MASK: c_uint = 0x1;
pub const MME_SHADOW_1_STATUS_B_SHIFT: c_int = 1;
pub const MME_SHADOW_1_STATUS_B_MASK: c_uint = 0x2;
pub const MME_SHADOW_1_STATUS_CIN_SHIFT: c_int = 2;
pub const MME_SHADOW_1_STATUS_CIN_MASK: c_uint = 0x4;
pub const MME_SHADOW_1_STATUS_COUT_SHIFT: c_int = 3;
pub const MME_SHADOW_1_STATUS_COUT_MASK: c_uint = 0x8;
pub const MME_SHADOW_1_STATUS_TE_SHIFT: c_int = 4;
pub const MME_SHADOW_1_STATUS_TE_MASK: c_uint = 0x10;
pub const MME_SHADOW_1_STATUS_LD_SHIFT: c_int = 5;
pub const MME_SHADOW_1_STATUS_LD_MASK: c_uint = 0x20;
pub const MME_SHADOW_1_STATUS_ST_SHIFT: c_int = 6;
pub const MME_SHADOW_1_STATUS_ST_MASK: c_uint = 0x40;
// MME_SHADOW_1_A_BASE_ADDR_HIGH
pub const MME_SHADOW_1_A_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_A_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_B_BASE_ADDR_HIGH
pub const MME_SHADOW_1_B_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_B_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_CIN_BASE_ADDR_HIGH
pub const MME_SHADOW_1_CIN_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_CIN_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_COUT_BASE_ADDR_HIGH
pub const MME_SHADOW_1_COUT_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_COUT_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_BIAS_BASE_ADDR_HIGH
pub const MME_SHADOW_1_BIAS_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_BIAS_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_A_BASE_ADDR_LOW
pub const MME_SHADOW_1_A_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_A_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_B_BASE_ADDR_LOW
pub const MME_SHADOW_1_B_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_B_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_CIN_BASE_ADDR_LOW
pub const MME_SHADOW_1_CIN_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_CIN_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_COUT_BASE_ADDR_LOW
pub const MME_SHADOW_1_COUT_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_COUT_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_BIAS_BASE_ADDR_LOW
pub const MME_SHADOW_1_BIAS_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_BIAS_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_HEADER
pub const MME_SHADOW_1_HEADER_SIGNAL_MASK_SHIFT: c_int = 0;
pub const MME_SHADOW_1_HEADER_SIGNAL_MASK_MASK: c_uint = 0x1F;
pub const MME_SHADOW_1_HEADER_SIGNAL_EN_SHIFT: c_int = 5;
pub const MME_SHADOW_1_HEADER_SIGNAL_EN_MASK: c_uint = 0x20;
pub const MME_SHADOW_1_HEADER_TRANS_A_SHIFT: c_int = 6;
pub const MME_SHADOW_1_HEADER_TRANS_A_MASK: c_uint = 0x40;
pub const MME_SHADOW_1_HEADER_LOWER_A_SHIFT: c_int = 7;
pub const MME_SHADOW_1_HEADER_LOWER_A_MASK: c_uint = 0x80;
pub const MME_SHADOW_1_HEADER_ACCUM_MASK_SHIFT: c_int = 8;
pub const MME_SHADOW_1_HEADER_ACCUM_MASK_MASK: c_uint = 0xF00;
pub const MME_SHADOW_1_HEADER_LOAD_BIAS_SHIFT: c_int = 12;
pub const MME_SHADOW_1_HEADER_LOAD_BIAS_MASK: c_uint = 0x1000;
pub const MME_SHADOW_1_HEADER_LOAD_CIN_SHIFT: c_int = 13;
pub const MME_SHADOW_1_HEADER_LOAD_CIN_MASK: c_uint = 0x2000;
pub const MME_SHADOW_1_HEADER_STORE_OUT_SHIFT: c_int = 15;
pub const MME_SHADOW_1_HEADER_STORE_OUT_MASK: c_uint = 0x8000;
pub const MME_SHADOW_1_HEADER_ACC_LD_INC_DISABLE_SHIFT: c_int = 16;
pub const MME_SHADOW_1_HEADER_ACC_LD_INC_DISABLE_MASK: c_uint = 0x10000;
pub const MME_SHADOW_1_HEADER_ADVANCE_A_SHIFT: c_int = 17;
pub const MME_SHADOW_1_HEADER_ADVANCE_A_MASK: c_uint = 0x20000;
pub const MME_SHADOW_1_HEADER_ADVANCE_B_SHIFT: c_int = 18;
pub const MME_SHADOW_1_HEADER_ADVANCE_B_MASK: c_uint = 0x40000;
pub const MME_SHADOW_1_HEADER_ADVANCE_CIN_SHIFT: c_int = 19;
pub const MME_SHADOW_1_HEADER_ADVANCE_CIN_MASK: c_uint = 0x80000;
pub const MME_SHADOW_1_HEADER_ADVANCE_COUT_SHIFT: c_int = 20;
pub const MME_SHADOW_1_HEADER_ADVANCE_COUT_MASK: c_uint = 0x100000;
pub const MME_SHADOW_1_HEADER_COMPRESSED_B_SHIFT: c_int = 21;
pub const MME_SHADOW_1_HEADER_COMPRESSED_B_MASK: c_uint = 0x200000;
pub const MME_SHADOW_1_HEADER_MASK_CONV_END_SHIFT: c_int = 22;
pub const MME_SHADOW_1_HEADER_MASK_CONV_END_MASK: c_uint = 0x400000;
pub const MME_SHADOW_1_HEADER_ACC_ST_INC_DISABLE_SHIFT: c_int = 23;
pub const MME_SHADOW_1_HEADER_ACC_ST_INC_DISABLE_MASK: c_uint = 0x800000;
pub const MME_SHADOW_1_HEADER_AB_DATA_TYPE_SHIFT: c_int = 24;
pub const MME_SHADOW_1_HEADER_AB_DATA_TYPE_MASK: c_uint = 0x3000000;
pub const MME_SHADOW_1_HEADER_CIN_DATA_TYPE_SHIFT: c_int = 26;
pub const MME_SHADOW_1_HEADER_CIN_DATA_TYPE_MASK: c_uint = 0x1C000000;
pub const MME_SHADOW_1_HEADER_COUT_DATA_TYPE_SHIFT: c_int = 29;
pub const MME_SHADOW_1_HEADER_COUT_DATA_TYPE_MASK: c_uint = 0xE0000000;
// MME_SHADOW_1_KERNEL_SIZE_MINUS_1
pub const MME_SHADOW_1_KERNEL_SIZE_MINUS_1_DIM_0_SHIFT: c_int = 0;
pub const MME_SHADOW_1_KERNEL_SIZE_MINUS_1_DIM_0_MASK: c_uint = 0xFF;
pub const MME_SHADOW_1_KERNEL_SIZE_MINUS_1_DIM_1_SHIFT: c_int = 8;
pub const MME_SHADOW_1_KERNEL_SIZE_MINUS_1_DIM_1_MASK: c_uint = 0xFF00;
pub const MME_SHADOW_1_KERNEL_SIZE_MINUS_1_DIM_2_SHIFT: c_int = 16;
pub const MME_SHADOW_1_KERNEL_SIZE_MINUS_1_DIM_2_MASK: c_uint = 0xFF0000;
pub const MME_SHADOW_1_KERNEL_SIZE_MINUS_1_DIM_3_SHIFT: c_int = 24;
pub const MME_SHADOW_1_KERNEL_SIZE_MINUS_1_DIM_3_MASK: c_uint = 0xFF000000;
// MME_SHADOW_1_ASSOCIATED_DIMS
pub const MME_SHADOW_1_ASSOCIATED_DIMS_A_0_SHIFT: c_int = 0;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_A_0_MASK: c_uint = 0x7;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_B_0_SHIFT: c_int = 3;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_B_0_MASK: c_uint = 0x38;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_CIN_0_SHIFT: c_int = 6;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_CIN_0_MASK: c_uint = 0x1C0;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_COUT_0_SHIFT: c_int = 9;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_COUT_0_MASK: c_uint = 0xE00;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_A_1_SHIFT: c_int = 16;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_A_1_MASK: c_uint = 0x70000;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_B_1_SHIFT: c_int = 19;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_B_1_MASK: c_uint = 0x380000;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_CIN_1_SHIFT: c_int = 22;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_CIN_1_MASK: c_uint = 0x1C00000;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_COUT_1_SHIFT: c_int = 25;
pub const MME_SHADOW_1_ASSOCIATED_DIMS_COUT_1_MASK: c_uint = 0xE000000;
// MME_SHADOW_1_COUT_SCALE
pub const MME_SHADOW_1_COUT_SCALE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_COUT_SCALE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_CIN_SCALE
pub const MME_SHADOW_1_CIN_SCALE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_CIN_SCALE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_GEMMLOWP_ZP
pub const MME_SHADOW_1_GEMMLOWP_ZP_ZP_CIN_SHIFT: c_int = 0;
pub const MME_SHADOW_1_GEMMLOWP_ZP_ZP_CIN_MASK: c_uint = 0x1FF;
pub const MME_SHADOW_1_GEMMLOWP_ZP_ZP_COUT_SHIFT: c_int = 9;
pub const MME_SHADOW_1_GEMMLOWP_ZP_ZP_COUT_MASK: c_uint = 0x3FE00;
pub const MME_SHADOW_1_GEMMLOWP_ZP_ZP_B_SHIFT: c_int = 18;
pub const MME_SHADOW_1_GEMMLOWP_ZP_ZP_B_MASK: c_uint = 0x7FC0000;
pub const MME_SHADOW_1_GEMMLOWP_ZP_GEMMLOWP_EU_EN_SHIFT: c_int = 27;
pub const MME_SHADOW_1_GEMMLOWP_ZP_GEMMLOWP_EU_EN_MASK: c_uint = 0x8000000;
pub const MME_SHADOW_1_GEMMLOWP_ZP_ACCUM_SHIFT: c_int = 28;
pub const MME_SHADOW_1_GEMMLOWP_ZP_ACCUM_MASK: c_uint = 0x10000000;
pub const MME_SHADOW_1_GEMMLOWP_ZP_ACCUM_BIAS_SHIFT: c_int = 29;
pub const MME_SHADOW_1_GEMMLOWP_ZP_ACCUM_BIAS_MASK: c_uint = 0x20000000;
pub const MME_SHADOW_1_GEMMLOWP_ZP_RELU_EN_SHIFT: c_int = 30;
pub const MME_SHADOW_1_GEMMLOWP_ZP_RELU_EN_MASK: c_uint = 0x40000000;
// MME_SHADOW_1_GEMMLOWP_EXPONENT
pub const MME_SHADOW_1_GEMMLOWP_EXPONENT_EXPONENT_CIN_SHIFT: c_int = 0;
pub const MME_SHADOW_1_GEMMLOWP_EXPONENT_EXPONENT_CIN_MASK: c_uint = 0x3F;
pub const MME_SHADOW_1_GEMMLOWP_EXPONENT_EXPONENT_COUT_SHIFT: c_int = 8;
pub const MME_SHADOW_1_GEMMLOWP_EXPONENT_EXPONENT_COUT_MASK: c_uint = 0x3F00;
pub const MME_SHADOW_1_GEMMLOWP_EXPONENT_MUL_CIN_EN_SHIFT: c_int = 16;
pub const MME_SHADOW_1_GEMMLOWP_EXPONENT_MUL_CIN_EN_MASK: c_uint = 0x10000;
pub const MME_SHADOW_1_GEMMLOWP_EXPONENT_MUL_COUT_EN_SHIFT: c_int = 17;
pub const MME_SHADOW_1_GEMMLOWP_EXPONENT_MUL_COUT_EN_MASK: c_uint = 0x20000;
// MME_SHADOW_1_A_ROI_BASE_OFFSET
pub const MME_SHADOW_1_A_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_A_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_A_VALID_ELEMENTS
pub const MME_SHADOW_1_A_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_A_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_A_LOOP_STRIDE
pub const MME_SHADOW_1_A_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_A_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_A_ROI_SIZE
pub const MME_SHADOW_1_A_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_A_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_A_SPATIAL_START_OFFSET
pub const MME_SHADOW_1_A_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_A_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_A_SPATIAL_STRIDE
pub const MME_SHADOW_1_A_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_A_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_A_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_1_A_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_A_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_B_ROI_BASE_OFFSET
pub const MME_SHADOW_1_B_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_B_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_B_VALID_ELEMENTS
pub const MME_SHADOW_1_B_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_B_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_B_LOOP_STRIDE
pub const MME_SHADOW_1_B_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_B_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_B_ROI_SIZE
pub const MME_SHADOW_1_B_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_B_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_B_SPATIAL_START_OFFSET
pub const MME_SHADOW_1_B_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_B_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_B_SPATIAL_STRIDE
pub const MME_SHADOW_1_B_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_B_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_B_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_1_B_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_B_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_C_ROI_BASE_OFFSET
pub const MME_SHADOW_1_C_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_C_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_C_VALID_ELEMENTS
pub const MME_SHADOW_1_C_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_C_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_C_LOOP_STRIDE
pub const MME_SHADOW_1_C_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_C_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_C_ROI_SIZE
pub const MME_SHADOW_1_C_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_C_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_C_SPATIAL_START_OFFSET
pub const MME_SHADOW_1_C_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_C_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_C_SPATIAL_STRIDE
pub const MME_SHADOW_1_C_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_C_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_C_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_1_C_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_C_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_SYNC_OBJECT_MESSAGE
pub const MME_SHADOW_1_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_SHIFT: c_int = 0;
pub const MME_SHADOW_1_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_MASK: c_uint = 0xFFFF;
pub const MME_SHADOW_1_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_SHIFT: c_int = 16;
pub const MME_SHADOW_1_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_MASK: c_uint = 0x7FFF0000;
pub const MME_SHADOW_1_SYNC_OBJECT_MESSAGE_SO_OPERATION_SHIFT: c_int = 31;
pub const MME_SHADOW_1_SYNC_OBJECT_MESSAGE_SO_OPERATION_MASK: c_uint = 0x80000000;
// MME_SHADOW_1_E_PADDING_VALUE_A
pub const MME_SHADOW_1_E_PADDING_VALUE_A_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_E_PADDING_VALUE_A_V_MASK: c_uint = 0xFFFF;
// MME_SHADOW_1_E_NUM_ITERATION_MINUS_1
pub const MME_SHADOW_1_E_NUM_ITERATION_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_1_E_NUM_ITERATION_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_1_E_BUBBLES_PER_SPLIT
pub const MME_SHADOW_1_E_BUBBLES_PER_SPLIT_A_SHIFT: c_int = 0;
pub const MME_SHADOW_1_E_BUBBLES_PER_SPLIT_A_MASK: c_uint = 0xFF;
pub const MME_SHADOW_1_E_BUBBLES_PER_SPLIT_B_SHIFT: c_int = 8;
pub const MME_SHADOW_1_E_BUBBLES_PER_SPLIT_B_MASK: c_uint = 0xFF00;
pub const MME_SHADOW_1_E_BUBBLES_PER_SPLIT_CIN_SHIFT: c_int = 16;
pub const MME_SHADOW_1_E_BUBBLES_PER_SPLIT_CIN_MASK: c_uint = 0xFF0000;
pub const MME_SHADOW_1_E_BUBBLES_PER_SPLIT_ID_SHIFT: c_int = 24;
pub const MME_SHADOW_1_E_BUBBLES_PER_SPLIT_ID_MASK: c_uint = 0xFF000000;
// MME_SHADOW_2_STATUS
pub const MME_SHADOW_2_STATUS_A_SHIFT: c_int = 0;
pub const MME_SHADOW_2_STATUS_A_MASK: c_uint = 0x1;
pub const MME_SHADOW_2_STATUS_B_SHIFT: c_int = 1;
pub const MME_SHADOW_2_STATUS_B_MASK: c_uint = 0x2;
pub const MME_SHADOW_2_STATUS_CIN_SHIFT: c_int = 2;
pub const MME_SHADOW_2_STATUS_CIN_MASK: c_uint = 0x4;
pub const MME_SHADOW_2_STATUS_COUT_SHIFT: c_int = 3;
pub const MME_SHADOW_2_STATUS_COUT_MASK: c_uint = 0x8;
pub const MME_SHADOW_2_STATUS_TE_SHIFT: c_int = 4;
pub const MME_SHADOW_2_STATUS_TE_MASK: c_uint = 0x10;
pub const MME_SHADOW_2_STATUS_LD_SHIFT: c_int = 5;
pub const MME_SHADOW_2_STATUS_LD_MASK: c_uint = 0x20;
pub const MME_SHADOW_2_STATUS_ST_SHIFT: c_int = 6;
pub const MME_SHADOW_2_STATUS_ST_MASK: c_uint = 0x40;
// MME_SHADOW_2_A_BASE_ADDR_HIGH
pub const MME_SHADOW_2_A_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_A_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_B_BASE_ADDR_HIGH
pub const MME_SHADOW_2_B_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_B_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_CIN_BASE_ADDR_HIGH
pub const MME_SHADOW_2_CIN_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_CIN_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_COUT_BASE_ADDR_HIGH
pub const MME_SHADOW_2_COUT_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_COUT_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_BIAS_BASE_ADDR_HIGH
pub const MME_SHADOW_2_BIAS_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_BIAS_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_A_BASE_ADDR_LOW
pub const MME_SHADOW_2_A_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_A_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_B_BASE_ADDR_LOW
pub const MME_SHADOW_2_B_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_B_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_CIN_BASE_ADDR_LOW
pub const MME_SHADOW_2_CIN_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_CIN_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_COUT_BASE_ADDR_LOW
pub const MME_SHADOW_2_COUT_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_COUT_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_BIAS_BASE_ADDR_LOW
pub const MME_SHADOW_2_BIAS_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_BIAS_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_HEADER
pub const MME_SHADOW_2_HEADER_SIGNAL_MASK_SHIFT: c_int = 0;
pub const MME_SHADOW_2_HEADER_SIGNAL_MASK_MASK: c_uint = 0x1F;
pub const MME_SHADOW_2_HEADER_SIGNAL_EN_SHIFT: c_int = 5;
pub const MME_SHADOW_2_HEADER_SIGNAL_EN_MASK: c_uint = 0x20;
pub const MME_SHADOW_2_HEADER_TRANS_A_SHIFT: c_int = 6;
pub const MME_SHADOW_2_HEADER_TRANS_A_MASK: c_uint = 0x40;
pub const MME_SHADOW_2_HEADER_LOWER_A_SHIFT: c_int = 7;
pub const MME_SHADOW_2_HEADER_LOWER_A_MASK: c_uint = 0x80;
pub const MME_SHADOW_2_HEADER_ACCUM_MASK_SHIFT: c_int = 8;
pub const MME_SHADOW_2_HEADER_ACCUM_MASK_MASK: c_uint = 0xF00;
pub const MME_SHADOW_2_HEADER_LOAD_BIAS_SHIFT: c_int = 12;
pub const MME_SHADOW_2_HEADER_LOAD_BIAS_MASK: c_uint = 0x1000;
pub const MME_SHADOW_2_HEADER_LOAD_CIN_SHIFT: c_int = 13;
pub const MME_SHADOW_2_HEADER_LOAD_CIN_MASK: c_uint = 0x2000;
pub const MME_SHADOW_2_HEADER_STORE_OUT_SHIFT: c_int = 15;
pub const MME_SHADOW_2_HEADER_STORE_OUT_MASK: c_uint = 0x8000;
pub const MME_SHADOW_2_HEADER_ACC_LD_INC_DISABLE_SHIFT: c_int = 16;
pub const MME_SHADOW_2_HEADER_ACC_LD_INC_DISABLE_MASK: c_uint = 0x10000;
pub const MME_SHADOW_2_HEADER_ADVANCE_A_SHIFT: c_int = 17;
pub const MME_SHADOW_2_HEADER_ADVANCE_A_MASK: c_uint = 0x20000;
pub const MME_SHADOW_2_HEADER_ADVANCE_B_SHIFT: c_int = 18;
pub const MME_SHADOW_2_HEADER_ADVANCE_B_MASK: c_uint = 0x40000;
pub const MME_SHADOW_2_HEADER_ADVANCE_CIN_SHIFT: c_int = 19;
pub const MME_SHADOW_2_HEADER_ADVANCE_CIN_MASK: c_uint = 0x80000;
pub const MME_SHADOW_2_HEADER_ADVANCE_COUT_SHIFT: c_int = 20;
pub const MME_SHADOW_2_HEADER_ADVANCE_COUT_MASK: c_uint = 0x100000;
pub const MME_SHADOW_2_HEADER_COMPRESSED_B_SHIFT: c_int = 21;
pub const MME_SHADOW_2_HEADER_COMPRESSED_B_MASK: c_uint = 0x200000;
pub const MME_SHADOW_2_HEADER_MASK_CONV_END_SHIFT: c_int = 22;
pub const MME_SHADOW_2_HEADER_MASK_CONV_END_MASK: c_uint = 0x400000;
pub const MME_SHADOW_2_HEADER_ACC_ST_INC_DISABLE_SHIFT: c_int = 23;
pub const MME_SHADOW_2_HEADER_ACC_ST_INC_DISABLE_MASK: c_uint = 0x800000;
pub const MME_SHADOW_2_HEADER_AB_DATA_TYPE_SHIFT: c_int = 24;
pub const MME_SHADOW_2_HEADER_AB_DATA_TYPE_MASK: c_uint = 0x3000000;
pub const MME_SHADOW_2_HEADER_CIN_DATA_TYPE_SHIFT: c_int = 26;
pub const MME_SHADOW_2_HEADER_CIN_DATA_TYPE_MASK: c_uint = 0x1C000000;
pub const MME_SHADOW_2_HEADER_COUT_DATA_TYPE_SHIFT: c_int = 29;
pub const MME_SHADOW_2_HEADER_COUT_DATA_TYPE_MASK: c_uint = 0xE0000000;
// MME_SHADOW_2_KERNEL_SIZE_MINUS_1
pub const MME_SHADOW_2_KERNEL_SIZE_MINUS_1_DIM_0_SHIFT: c_int = 0;
pub const MME_SHADOW_2_KERNEL_SIZE_MINUS_1_DIM_0_MASK: c_uint = 0xFF;
pub const MME_SHADOW_2_KERNEL_SIZE_MINUS_1_DIM_1_SHIFT: c_int = 8;
pub const MME_SHADOW_2_KERNEL_SIZE_MINUS_1_DIM_1_MASK: c_uint = 0xFF00;
pub const MME_SHADOW_2_KERNEL_SIZE_MINUS_1_DIM_2_SHIFT: c_int = 16;
pub const MME_SHADOW_2_KERNEL_SIZE_MINUS_1_DIM_2_MASK: c_uint = 0xFF0000;
pub const MME_SHADOW_2_KERNEL_SIZE_MINUS_1_DIM_3_SHIFT: c_int = 24;
pub const MME_SHADOW_2_KERNEL_SIZE_MINUS_1_DIM_3_MASK: c_uint = 0xFF000000;
// MME_SHADOW_2_ASSOCIATED_DIMS
pub const MME_SHADOW_2_ASSOCIATED_DIMS_A_0_SHIFT: c_int = 0;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_A_0_MASK: c_uint = 0x7;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_B_0_SHIFT: c_int = 3;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_B_0_MASK: c_uint = 0x38;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_CIN_0_SHIFT: c_int = 6;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_CIN_0_MASK: c_uint = 0x1C0;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_COUT_0_SHIFT: c_int = 9;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_COUT_0_MASK: c_uint = 0xE00;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_A_1_SHIFT: c_int = 16;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_A_1_MASK: c_uint = 0x70000;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_B_1_SHIFT: c_int = 19;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_B_1_MASK: c_uint = 0x380000;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_CIN_1_SHIFT: c_int = 22;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_CIN_1_MASK: c_uint = 0x1C00000;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_COUT_1_SHIFT: c_int = 25;
pub const MME_SHADOW_2_ASSOCIATED_DIMS_COUT_1_MASK: c_uint = 0xE000000;
// MME_SHADOW_2_COUT_SCALE
pub const MME_SHADOW_2_COUT_SCALE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_COUT_SCALE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_CIN_SCALE
pub const MME_SHADOW_2_CIN_SCALE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_CIN_SCALE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_GEMMLOWP_ZP
pub const MME_SHADOW_2_GEMMLOWP_ZP_ZP_CIN_SHIFT: c_int = 0;
pub const MME_SHADOW_2_GEMMLOWP_ZP_ZP_CIN_MASK: c_uint = 0x1FF;
pub const MME_SHADOW_2_GEMMLOWP_ZP_ZP_COUT_SHIFT: c_int = 9;
pub const MME_SHADOW_2_GEMMLOWP_ZP_ZP_COUT_MASK: c_uint = 0x3FE00;
pub const MME_SHADOW_2_GEMMLOWP_ZP_ZP_B_SHIFT: c_int = 18;
pub const MME_SHADOW_2_GEMMLOWP_ZP_ZP_B_MASK: c_uint = 0x7FC0000;
pub const MME_SHADOW_2_GEMMLOWP_ZP_GEMMLOWP_EU_EN_SHIFT: c_int = 27;
pub const MME_SHADOW_2_GEMMLOWP_ZP_GEMMLOWP_EU_EN_MASK: c_uint = 0x8000000;
pub const MME_SHADOW_2_GEMMLOWP_ZP_ACCUM_SHIFT: c_int = 28;
pub const MME_SHADOW_2_GEMMLOWP_ZP_ACCUM_MASK: c_uint = 0x10000000;
pub const MME_SHADOW_2_GEMMLOWP_ZP_ACCUM_BIAS_SHIFT: c_int = 29;
pub const MME_SHADOW_2_GEMMLOWP_ZP_ACCUM_BIAS_MASK: c_uint = 0x20000000;
pub const MME_SHADOW_2_GEMMLOWP_ZP_RELU_EN_SHIFT: c_int = 30;
pub const MME_SHADOW_2_GEMMLOWP_ZP_RELU_EN_MASK: c_uint = 0x40000000;
// MME_SHADOW_2_GEMMLOWP_EXPONENT
pub const MME_SHADOW_2_GEMMLOWP_EXPONENT_EXPONENT_CIN_SHIFT: c_int = 0;
pub const MME_SHADOW_2_GEMMLOWP_EXPONENT_EXPONENT_CIN_MASK: c_uint = 0x3F;
pub const MME_SHADOW_2_GEMMLOWP_EXPONENT_EXPONENT_COUT_SHIFT: c_int = 8;
pub const MME_SHADOW_2_GEMMLOWP_EXPONENT_EXPONENT_COUT_MASK: c_uint = 0x3F00;
pub const MME_SHADOW_2_GEMMLOWP_EXPONENT_MUL_CIN_EN_SHIFT: c_int = 16;
pub const MME_SHADOW_2_GEMMLOWP_EXPONENT_MUL_CIN_EN_MASK: c_uint = 0x10000;
pub const MME_SHADOW_2_GEMMLOWP_EXPONENT_MUL_COUT_EN_SHIFT: c_int = 17;
pub const MME_SHADOW_2_GEMMLOWP_EXPONENT_MUL_COUT_EN_MASK: c_uint = 0x20000;
// MME_SHADOW_2_A_ROI_BASE_OFFSET
pub const MME_SHADOW_2_A_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_A_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_A_VALID_ELEMENTS
pub const MME_SHADOW_2_A_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_A_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_A_LOOP_STRIDE
pub const MME_SHADOW_2_A_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_A_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_A_ROI_SIZE
pub const MME_SHADOW_2_A_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_A_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_A_SPATIAL_START_OFFSET
pub const MME_SHADOW_2_A_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_A_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_A_SPATIAL_STRIDE
pub const MME_SHADOW_2_A_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_A_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_A_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_2_A_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_A_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_B_ROI_BASE_OFFSET
pub const MME_SHADOW_2_B_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_B_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_B_VALID_ELEMENTS
pub const MME_SHADOW_2_B_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_B_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_B_LOOP_STRIDE
pub const MME_SHADOW_2_B_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_B_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_B_ROI_SIZE
pub const MME_SHADOW_2_B_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_B_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_B_SPATIAL_START_OFFSET
pub const MME_SHADOW_2_B_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_B_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_B_SPATIAL_STRIDE
pub const MME_SHADOW_2_B_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_B_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_B_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_2_B_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_B_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_C_ROI_BASE_OFFSET
pub const MME_SHADOW_2_C_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_C_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_C_VALID_ELEMENTS
pub const MME_SHADOW_2_C_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_C_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_C_LOOP_STRIDE
pub const MME_SHADOW_2_C_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_C_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_C_ROI_SIZE
pub const MME_SHADOW_2_C_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_C_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_C_SPATIAL_START_OFFSET
pub const MME_SHADOW_2_C_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_C_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_C_SPATIAL_STRIDE
pub const MME_SHADOW_2_C_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_C_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_C_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_2_C_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_C_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_SYNC_OBJECT_MESSAGE
pub const MME_SHADOW_2_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_SHIFT: c_int = 0;
pub const MME_SHADOW_2_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_MASK: c_uint = 0xFFFF;
pub const MME_SHADOW_2_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_SHIFT: c_int = 16;
pub const MME_SHADOW_2_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_MASK: c_uint = 0x7FFF0000;
pub const MME_SHADOW_2_SYNC_OBJECT_MESSAGE_SO_OPERATION_SHIFT: c_int = 31;
pub const MME_SHADOW_2_SYNC_OBJECT_MESSAGE_SO_OPERATION_MASK: c_uint = 0x80000000;
// MME_SHADOW_2_E_PADDING_VALUE_A
pub const MME_SHADOW_2_E_PADDING_VALUE_A_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_E_PADDING_VALUE_A_V_MASK: c_uint = 0xFFFF;
// MME_SHADOW_2_E_NUM_ITERATION_MINUS_1
pub const MME_SHADOW_2_E_NUM_ITERATION_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_2_E_NUM_ITERATION_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_2_E_BUBBLES_PER_SPLIT
pub const MME_SHADOW_2_E_BUBBLES_PER_SPLIT_A_SHIFT: c_int = 0;
pub const MME_SHADOW_2_E_BUBBLES_PER_SPLIT_A_MASK: c_uint = 0xFF;
pub const MME_SHADOW_2_E_BUBBLES_PER_SPLIT_B_SHIFT: c_int = 8;
pub const MME_SHADOW_2_E_BUBBLES_PER_SPLIT_B_MASK: c_uint = 0xFF00;
pub const MME_SHADOW_2_E_BUBBLES_PER_SPLIT_CIN_SHIFT: c_int = 16;
pub const MME_SHADOW_2_E_BUBBLES_PER_SPLIT_CIN_MASK: c_uint = 0xFF0000;
pub const MME_SHADOW_2_E_BUBBLES_PER_SPLIT_ID_SHIFT: c_int = 24;
pub const MME_SHADOW_2_E_BUBBLES_PER_SPLIT_ID_MASK: c_uint = 0xFF000000;
// MME_SHADOW_3_STATUS
pub const MME_SHADOW_3_STATUS_A_SHIFT: c_int = 0;
pub const MME_SHADOW_3_STATUS_A_MASK: c_uint = 0x1;
pub const MME_SHADOW_3_STATUS_B_SHIFT: c_int = 1;
pub const MME_SHADOW_3_STATUS_B_MASK: c_uint = 0x2;
pub const MME_SHADOW_3_STATUS_CIN_SHIFT: c_int = 2;
pub const MME_SHADOW_3_STATUS_CIN_MASK: c_uint = 0x4;
pub const MME_SHADOW_3_STATUS_COUT_SHIFT: c_int = 3;
pub const MME_SHADOW_3_STATUS_COUT_MASK: c_uint = 0x8;
pub const MME_SHADOW_3_STATUS_TE_SHIFT: c_int = 4;
pub const MME_SHADOW_3_STATUS_TE_MASK: c_uint = 0x10;
pub const MME_SHADOW_3_STATUS_LD_SHIFT: c_int = 5;
pub const MME_SHADOW_3_STATUS_LD_MASK: c_uint = 0x20;
pub const MME_SHADOW_3_STATUS_ST_SHIFT: c_int = 6;
pub const MME_SHADOW_3_STATUS_ST_MASK: c_uint = 0x40;
// MME_SHADOW_3_A_BASE_ADDR_HIGH
pub const MME_SHADOW_3_A_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_A_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_B_BASE_ADDR_HIGH
pub const MME_SHADOW_3_B_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_B_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_CIN_BASE_ADDR_HIGH
pub const MME_SHADOW_3_CIN_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_CIN_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_COUT_BASE_ADDR_HIGH
pub const MME_SHADOW_3_COUT_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_COUT_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_BIAS_BASE_ADDR_HIGH
pub const MME_SHADOW_3_BIAS_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_BIAS_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_A_BASE_ADDR_LOW
pub const MME_SHADOW_3_A_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_A_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_B_BASE_ADDR_LOW
pub const MME_SHADOW_3_B_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_B_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_CIN_BASE_ADDR_LOW
pub const MME_SHADOW_3_CIN_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_CIN_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_COUT_BASE_ADDR_LOW
pub const MME_SHADOW_3_COUT_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_COUT_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_BIAS_BASE_ADDR_LOW
pub const MME_SHADOW_3_BIAS_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_BIAS_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_HEADER
pub const MME_SHADOW_3_HEADER_SIGNAL_MASK_SHIFT: c_int = 0;
pub const MME_SHADOW_3_HEADER_SIGNAL_MASK_MASK: c_uint = 0x1F;
pub const MME_SHADOW_3_HEADER_SIGNAL_EN_SHIFT: c_int = 5;
pub const MME_SHADOW_3_HEADER_SIGNAL_EN_MASK: c_uint = 0x20;
pub const MME_SHADOW_3_HEADER_TRANS_A_SHIFT: c_int = 6;
pub const MME_SHADOW_3_HEADER_TRANS_A_MASK: c_uint = 0x40;
pub const MME_SHADOW_3_HEADER_LOWER_A_SHIFT: c_int = 7;
pub const MME_SHADOW_3_HEADER_LOWER_A_MASK: c_uint = 0x80;
pub const MME_SHADOW_3_HEADER_ACCUM_MASK_SHIFT: c_int = 8;
pub const MME_SHADOW_3_HEADER_ACCUM_MASK_MASK: c_uint = 0xF00;
pub const MME_SHADOW_3_HEADER_LOAD_BIAS_SHIFT: c_int = 12;
pub const MME_SHADOW_3_HEADER_LOAD_BIAS_MASK: c_uint = 0x1000;
pub const MME_SHADOW_3_HEADER_LOAD_CIN_SHIFT: c_int = 13;
pub const MME_SHADOW_3_HEADER_LOAD_CIN_MASK: c_uint = 0x2000;
pub const MME_SHADOW_3_HEADER_STORE_OUT_SHIFT: c_int = 15;
pub const MME_SHADOW_3_HEADER_STORE_OUT_MASK: c_uint = 0x8000;
pub const MME_SHADOW_3_HEADER_ACC_LD_INC_DISABLE_SHIFT: c_int = 16;
pub const MME_SHADOW_3_HEADER_ACC_LD_INC_DISABLE_MASK: c_uint = 0x10000;
pub const MME_SHADOW_3_HEADER_ADVANCE_A_SHIFT: c_int = 17;
pub const MME_SHADOW_3_HEADER_ADVANCE_A_MASK: c_uint = 0x20000;
pub const MME_SHADOW_3_HEADER_ADVANCE_B_SHIFT: c_int = 18;
pub const MME_SHADOW_3_HEADER_ADVANCE_B_MASK: c_uint = 0x40000;
pub const MME_SHADOW_3_HEADER_ADVANCE_CIN_SHIFT: c_int = 19;
pub const MME_SHADOW_3_HEADER_ADVANCE_CIN_MASK: c_uint = 0x80000;
pub const MME_SHADOW_3_HEADER_ADVANCE_COUT_SHIFT: c_int = 20;
pub const MME_SHADOW_3_HEADER_ADVANCE_COUT_MASK: c_uint = 0x100000;
pub const MME_SHADOW_3_HEADER_COMPRESSED_B_SHIFT: c_int = 21;
pub const MME_SHADOW_3_HEADER_COMPRESSED_B_MASK: c_uint = 0x200000;
pub const MME_SHADOW_3_HEADER_MASK_CONV_END_SHIFT: c_int = 22;
pub const MME_SHADOW_3_HEADER_MASK_CONV_END_MASK: c_uint = 0x400000;
pub const MME_SHADOW_3_HEADER_ACC_ST_INC_DISABLE_SHIFT: c_int = 23;
pub const MME_SHADOW_3_HEADER_ACC_ST_INC_DISABLE_MASK: c_uint = 0x800000;
pub const MME_SHADOW_3_HEADER_AB_DATA_TYPE_SHIFT: c_int = 24;
pub const MME_SHADOW_3_HEADER_AB_DATA_TYPE_MASK: c_uint = 0x3000000;
pub const MME_SHADOW_3_HEADER_CIN_DATA_TYPE_SHIFT: c_int = 26;
pub const MME_SHADOW_3_HEADER_CIN_DATA_TYPE_MASK: c_uint = 0x1C000000;
pub const MME_SHADOW_3_HEADER_COUT_DATA_TYPE_SHIFT: c_int = 29;
pub const MME_SHADOW_3_HEADER_COUT_DATA_TYPE_MASK: c_uint = 0xE0000000;
// MME_SHADOW_3_KERNEL_SIZE_MINUS_1
pub const MME_SHADOW_3_KERNEL_SIZE_MINUS_1_DIM_0_SHIFT: c_int = 0;
pub const MME_SHADOW_3_KERNEL_SIZE_MINUS_1_DIM_0_MASK: c_uint = 0xFF;
pub const MME_SHADOW_3_KERNEL_SIZE_MINUS_1_DIM_1_SHIFT: c_int = 8;
pub const MME_SHADOW_3_KERNEL_SIZE_MINUS_1_DIM_1_MASK: c_uint = 0xFF00;
pub const MME_SHADOW_3_KERNEL_SIZE_MINUS_1_DIM_2_SHIFT: c_int = 16;
pub const MME_SHADOW_3_KERNEL_SIZE_MINUS_1_DIM_2_MASK: c_uint = 0xFF0000;
pub const MME_SHADOW_3_KERNEL_SIZE_MINUS_1_DIM_3_SHIFT: c_int = 24;
pub const MME_SHADOW_3_KERNEL_SIZE_MINUS_1_DIM_3_MASK: c_uint = 0xFF000000;
// MME_SHADOW_3_ASSOCIATED_DIMS
pub const MME_SHADOW_3_ASSOCIATED_DIMS_A_0_SHIFT: c_int = 0;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_A_0_MASK: c_uint = 0x7;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_B_0_SHIFT: c_int = 3;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_B_0_MASK: c_uint = 0x38;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_CIN_0_SHIFT: c_int = 6;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_CIN_0_MASK: c_uint = 0x1C0;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_COUT_0_SHIFT: c_int = 9;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_COUT_0_MASK: c_uint = 0xE00;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_A_1_SHIFT: c_int = 16;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_A_1_MASK: c_uint = 0x70000;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_B_1_SHIFT: c_int = 19;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_B_1_MASK: c_uint = 0x380000;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_CIN_1_SHIFT: c_int = 22;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_CIN_1_MASK: c_uint = 0x1C00000;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_COUT_1_SHIFT: c_int = 25;
pub const MME_SHADOW_3_ASSOCIATED_DIMS_COUT_1_MASK: c_uint = 0xE000000;
// MME_SHADOW_3_COUT_SCALE
pub const MME_SHADOW_3_COUT_SCALE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_COUT_SCALE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_CIN_SCALE
pub const MME_SHADOW_3_CIN_SCALE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_CIN_SCALE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_GEMMLOWP_ZP
pub const MME_SHADOW_3_GEMMLOWP_ZP_ZP_CIN_SHIFT: c_int = 0;
pub const MME_SHADOW_3_GEMMLOWP_ZP_ZP_CIN_MASK: c_uint = 0x1FF;
pub const MME_SHADOW_3_GEMMLOWP_ZP_ZP_COUT_SHIFT: c_int = 9;
pub const MME_SHADOW_3_GEMMLOWP_ZP_ZP_COUT_MASK: c_uint = 0x3FE00;
pub const MME_SHADOW_3_GEMMLOWP_ZP_ZP_B_SHIFT: c_int = 18;
pub const MME_SHADOW_3_GEMMLOWP_ZP_ZP_B_MASK: c_uint = 0x7FC0000;
pub const MME_SHADOW_3_GEMMLOWP_ZP_GEMMLOWP_EU_EN_SHIFT: c_int = 27;
pub const MME_SHADOW_3_GEMMLOWP_ZP_GEMMLOWP_EU_EN_MASK: c_uint = 0x8000000;
pub const MME_SHADOW_3_GEMMLOWP_ZP_ACCUM_SHIFT: c_int = 28;
pub const MME_SHADOW_3_GEMMLOWP_ZP_ACCUM_MASK: c_uint = 0x10000000;
pub const MME_SHADOW_3_GEMMLOWP_ZP_ACCUM_BIAS_SHIFT: c_int = 29;
pub const MME_SHADOW_3_GEMMLOWP_ZP_ACCUM_BIAS_MASK: c_uint = 0x20000000;
pub const MME_SHADOW_3_GEMMLOWP_ZP_RELU_EN_SHIFT: c_int = 30;
pub const MME_SHADOW_3_GEMMLOWP_ZP_RELU_EN_MASK: c_uint = 0x40000000;
// MME_SHADOW_3_GEMMLOWP_EXPONENT
pub const MME_SHADOW_3_GEMMLOWP_EXPONENT_EXPONENT_CIN_SHIFT: c_int = 0;
pub const MME_SHADOW_3_GEMMLOWP_EXPONENT_EXPONENT_CIN_MASK: c_uint = 0x3F;
pub const MME_SHADOW_3_GEMMLOWP_EXPONENT_EXPONENT_COUT_SHIFT: c_int = 8;
pub const MME_SHADOW_3_GEMMLOWP_EXPONENT_EXPONENT_COUT_MASK: c_uint = 0x3F00;
pub const MME_SHADOW_3_GEMMLOWP_EXPONENT_MUL_CIN_EN_SHIFT: c_int = 16;
pub const MME_SHADOW_3_GEMMLOWP_EXPONENT_MUL_CIN_EN_MASK: c_uint = 0x10000;
pub const MME_SHADOW_3_GEMMLOWP_EXPONENT_MUL_COUT_EN_SHIFT: c_int = 17;
pub const MME_SHADOW_3_GEMMLOWP_EXPONENT_MUL_COUT_EN_MASK: c_uint = 0x20000;
// MME_SHADOW_3_A_ROI_BASE_OFFSET
pub const MME_SHADOW_3_A_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_A_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_A_VALID_ELEMENTS
pub const MME_SHADOW_3_A_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_A_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_A_LOOP_STRIDE
pub const MME_SHADOW_3_A_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_A_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_A_ROI_SIZE
pub const MME_SHADOW_3_A_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_A_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_A_SPATIAL_START_OFFSET
pub const MME_SHADOW_3_A_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_A_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_A_SPATIAL_STRIDE
pub const MME_SHADOW_3_A_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_A_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_A_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_3_A_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_A_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_B_ROI_BASE_OFFSET
pub const MME_SHADOW_3_B_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_B_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_B_VALID_ELEMENTS
pub const MME_SHADOW_3_B_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_B_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_B_LOOP_STRIDE
pub const MME_SHADOW_3_B_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_B_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_B_ROI_SIZE
pub const MME_SHADOW_3_B_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_B_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_B_SPATIAL_START_OFFSET
pub const MME_SHADOW_3_B_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_B_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_B_SPATIAL_STRIDE
pub const MME_SHADOW_3_B_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_B_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_B_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_3_B_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_B_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_C_ROI_BASE_OFFSET
pub const MME_SHADOW_3_C_ROI_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_C_ROI_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_C_VALID_ELEMENTS
pub const MME_SHADOW_3_C_VALID_ELEMENTS_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_C_VALID_ELEMENTS_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_C_LOOP_STRIDE
pub const MME_SHADOW_3_C_LOOP_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_C_LOOP_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_C_ROI_SIZE
pub const MME_SHADOW_3_C_ROI_SIZE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_C_ROI_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_C_SPATIAL_START_OFFSET
pub const MME_SHADOW_3_C_SPATIAL_START_OFFSET_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_C_SPATIAL_START_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_C_SPATIAL_STRIDE
pub const MME_SHADOW_3_C_SPATIAL_STRIDE_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_C_SPATIAL_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_C_SPATIAL_SIZE_MINUS_1
pub const MME_SHADOW_3_C_SPATIAL_SIZE_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_C_SPATIAL_SIZE_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_SYNC_OBJECT_MESSAGE
pub const MME_SHADOW_3_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_SHIFT: c_int = 0;
pub const MME_SHADOW_3_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_MASK: c_uint = 0xFFFF;
pub const MME_SHADOW_3_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_SHIFT: c_int = 16;
pub const MME_SHADOW_3_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_MASK: c_uint = 0x7FFF0000;
pub const MME_SHADOW_3_SYNC_OBJECT_MESSAGE_SO_OPERATION_SHIFT: c_int = 31;
pub const MME_SHADOW_3_SYNC_OBJECT_MESSAGE_SO_OPERATION_MASK: c_uint = 0x80000000;
// MME_SHADOW_3_E_PADDING_VALUE_A
pub const MME_SHADOW_3_E_PADDING_VALUE_A_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_E_PADDING_VALUE_A_V_MASK: c_uint = 0xFFFF;
// MME_SHADOW_3_E_NUM_ITERATION_MINUS_1
pub const MME_SHADOW_3_E_NUM_ITERATION_MINUS_1_V_SHIFT: c_int = 0;
pub const MME_SHADOW_3_E_NUM_ITERATION_MINUS_1_V_MASK: c_uint = 0xFFFFFFFF;
// MME_SHADOW_3_E_BUBBLES_PER_SPLIT
pub const MME_SHADOW_3_E_BUBBLES_PER_SPLIT_A_SHIFT: c_int = 0;
pub const MME_SHADOW_3_E_BUBBLES_PER_SPLIT_A_MASK: c_uint = 0xFF;
pub const MME_SHADOW_3_E_BUBBLES_PER_SPLIT_B_SHIFT: c_int = 8;
pub const MME_SHADOW_3_E_BUBBLES_PER_SPLIT_B_MASK: c_uint = 0xFF00;
pub const MME_SHADOW_3_E_BUBBLES_PER_SPLIT_CIN_SHIFT: c_int = 16;
pub const MME_SHADOW_3_E_BUBBLES_PER_SPLIT_CIN_MASK: c_uint = 0xFF0000;
pub const MME_SHADOW_3_E_BUBBLES_PER_SPLIT_ID_SHIFT: c_int = 24;
pub const MME_SHADOW_3_E_BUBBLES_PER_SPLIT_ID_MASK: c_uint = 0xFF000000;
