//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/goya/asic_reg/psoc_global_conf_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2018 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// PSOC_GLOBAL_CONF (Prototype: GLOBAL_CONF)
//
// PSOC_GLOBAL_CONF_NON_RST_FLOPS
pub const PSOC_GLOBAL_CONF_NON_RST_FLOPS_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_NON_RST_FLOPS_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_PCI_FW_FSM
pub const PSOC_GLOBAL_CONF_PCI_FW_FSM_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PCI_FW_FSM_EN_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_BTM_FSM
pub const PSOC_GLOBAL_CONF_BTM_FSM_STATE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BTM_FSM_STATE_MASK: c_uint = 0xF;
// PSOC_GLOBAL_CONF_SW_BTM_FSM
pub const PSOC_GLOBAL_CONF_SW_BTM_FSM_CTRL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SW_BTM_FSM_CTRL_MASK: c_uint = 0xF;
// PSOC_GLOBAL_CONF_SW_BOOT_SEQ_FSM
pub const PSOC_GLOBAL_CONF_SW_BOOT_SEQ_FSM_CTRL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SW_BOOT_SEQ_FSM_CTRL_MASK: c_uint = 0xF;
// PSOC_GLOBAL_CONF_BOOT_SEQ_TIMEOUT
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_TIMEOUT_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_TIMEOUT_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SPI_MEM_EN
pub const PSOC_GLOBAL_CONF_SPI_MEM_EN_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_MEM_EN_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PRSTN
pub const PSOC_GLOBAL_CONF_PRSTN_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PRSTN_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PCIE_EN
pub const PSOC_GLOBAL_CONF_PCIE_EN_MASK_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PCIE_EN_MASK_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_SPI_IMG_STS
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRI_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRI_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_SEC_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_SEC_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRSTN_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRSTN_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PCI_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PCI_MASK: c_uint = 0x8;
// PSOC_GLOBAL_CONF_BOOT_SEQ_FSM
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_IDLE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_IDLE_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_BOOT_INIT_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_BOOT_INIT_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRI_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRI_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_SEC_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_SEC_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRSTN_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRSTN_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PCIE_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PCIE_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_ROM_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_ROM_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_PCLK_READY_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_PCLK_READY_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_LTSSM_EN_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_LTSSM_EN_MASK: c_uint = 0x100;
// PSOC_GLOBAL_CONF_SCRATCHPAD
pub const PSOC_GLOBAL_CONF_SCRATCHPAD_REG_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SCRATCHPAD_REG_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SEMAPHORE
pub const PSOC_GLOBAL_CONF_SEMAPHORE_REG_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SEMAPHORE_REG_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_WARM_REBOOT
pub const PSOC_GLOBAL_CONF_WARM_REBOOT_CNTR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_WARM_REBOOT_CNTR_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_UBOOT_MAGIC
pub const PSOC_GLOBAL_CONF_UBOOT_MAGIC_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_UBOOT_MAGIC_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SPL_SOURCE
pub const PSOC_GLOBAL_CONF_SPL_SOURCE_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPL_SOURCE_VAL_MASK: c_uint = 0x7;
// PSOC_GLOBAL_CONF_I2C_MSTR1_DBG
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_S_GEN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_S_GEN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_P_GEN_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_P_GEN_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_DATA_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_DATA_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_RD_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_RD_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_WR_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_WR_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_HS_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_HS_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_MASTER_ACT_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_MASTER_ACT_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_SLAVE_ACT_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_SLAVE_ACT_MASK: c_uint = 0x100;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_10BIT_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_10BIT_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_MST_CSTATE_SHIFT: c_int = 10;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_MST_CSTATE_MASK: c_uint = 0x7C00;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_SLV_CSTATE_SHIFT: c_int = 15;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_SLV_CSTATE_MASK: c_uint = 0x78000;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_IC_EN_SHIFT: c_int = 19;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_IC_EN_MASK: c_uint = 0x80000;
// PSOC_GLOBAL_CONF_I2C_SLV
pub const PSOC_GLOBAL_CONF_I2C_SLV_CPU_CTRL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_I2C_SLV_CPU_CTRL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_I2C_SLV_INTR_MASK
pub const PSOC_GLOBAL_CONF_I2C_SLV_INTR_MASK_FLD_INT_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_I2C_SLV_INTR_MASK_FLD_INT_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_APP_STATUS
pub const PSOC_GLOBAL_CONF_APP_STATUS_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_APP_STATUS_IND_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_BTL_STS
pub const PSOC_GLOBAL_CONF_BTL_STS_DONE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BTL_STS_DONE_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_BTL_STS_FAIL_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_BTL_STS_FAIL_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_BTL_STS_FAIL_CODE_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_BTL_STS_FAIL_CODE_MASK: c_uint = 0xF00;
// PSOC_GLOBAL_CONF_TIMEOUT_INTR
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_0_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_0_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_1_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_1_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_2_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_2_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_3_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_3_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_4_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_4_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_TIMER_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_TIMER_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_UART_0_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_UART_0_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_UART_1_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_UART_1_MASK: c_uint = 0x80;
// PSOC_GLOBAL_CONF_COMB_TIMEOUT_INTR
pub const PSOC_GLOBAL_CONF_COMB_TIMEOUT_INTR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_COMB_TIMEOUT_INTR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PERIPH_INTR
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_TX_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_TX_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_RX_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_RX_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_TXOVR_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_TXOVR_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_RXOVR_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_RXOVR_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_TX_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_TX_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_RX_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_RX_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_TXOVR_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_TXOVR_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_RXOVR_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_RXOVR_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_EMMC_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_EMMC_MASK: c_uint = 0x1000;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_EMMC_WAKEUP_SHIFT: c_int = 13;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_EMMC_WAKEUP_MASK: c_uint = 0x2000;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_MII_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_MII_MASK: c_uint = 0x10000;
// PSOC_GLOBAL_CONF_COMB_PERIPH_INTR
pub const PSOC_GLOBAL_CONF_COMB_PERIPH_INTR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_COMB_PERIPH_INTR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_AXI_ERR_INTR
pub const PSOC_GLOBAL_CONF_AXI_ERR_INTR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_ERR_INTR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_TARGETID
pub const PSOC_GLOBAL_CONF_TARGETID_TDESIGNER_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_TARGETID_TDESIGNER_MASK: c_uint = 0xFFE;
pub const PSOC_GLOBAL_CONF_TARGETID_TPARTNO_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_TARGETID_TPARTNO_MASK: c_uint = 0xFFFF000;
pub const PSOC_GLOBAL_CONF_TARGETID_TREVISION_SHIFT: c_int = 28;
pub const PSOC_GLOBAL_CONF_TARGETID_TREVISION_MASK: c_uint = 0xF0000000;
// PSOC_GLOBAL_CONF_EMMC_INT_VOL_STABLE
pub const PSOC_GLOBAL_CONF_EMMC_INT_VOL_STABLE_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_EMMC_INT_VOL_STABLE_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_MII_ADDR
pub const PSOC_GLOBAL_CONF_MII_ADDR_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MII_ADDR_VAL_MASK: c_uint = 0xFF;
// PSOC_GLOBAL_CONF_MII_SPEED
pub const PSOC_GLOBAL_CONF_MII_SPEED_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MII_SPEED_VAL_MASK: c_uint = 0x3;
// PSOC_GLOBAL_CONF_BOOT_STRAP_PINS
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_CPOL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_CPOL_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_CPHA_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_CPHA_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_BTL_EN_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_BTL_EN_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_BTL_ROM_EN_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_BTL_ROM_EN_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_PCIE_EN_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_PCIE_EN_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_I2C_SLV_ADDR_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_I2C_SLV_ADDR_MASK: c_uint = 0xFE0;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_BOOT_STG2_SRC_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_BOOT_STG2_SRC_MASK: c_uint = 0x3000;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_PLL_BPS_SHIFT: c_int = 14;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_PLL_BPS_MASK: c_uint = 0x1FC000;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_SRIOV_EN_SHIFT: c_int = 21;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_SRIOV_EN_MASK: c_uint = 0x200000;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_PLL_CFG_SHIFT: c_int = 22;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_PLL_CFG_MASK: c_uint = 0x1C00000;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_MEM_REPAIR_BPS_SHIFT: c_int = 25;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_MEM_REPAIR_BPS_MASK: c_uint = 0x2000000;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_SPARE_SHIFT: c_int = 26;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_SPARE_MASK: c_uint = 0x1C000000;
// PSOC_GLOBAL_CONF_MEM_REPAIR_CTRL
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_CTRL_SET_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_CTRL_SET_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_CTRL_CLR_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_CTRL_CLR_MASK: c_uint = 0x2;
// PSOC_GLOBAL_CONF_MEM_REPAIR_STS
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_STS_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_STS_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_OUTSTANT_TRANS
pub const PSOC_GLOBAL_CONF_OUTSTANT_TRANS_RD_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_OUTSTANT_TRANS_RD_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_OUTSTANT_TRANS_WR_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_OUTSTANT_TRANS_WR_MASK: c_uint = 0x2;
// PSOC_GLOBAL_CONF_MASK_REQ
pub const PSOC_GLOBAL_CONF_MASK_REQ_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MASK_REQ_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PRSTN_RST_CFG
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_PCI_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_PCI_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_PCI_IF_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_PCI_IF_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_PLL_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_PLL_MASK: c_uint = 0x1FC;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_TPC_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_TPC_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_MME_SHIFT: c_int = 10;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_MME_MASK: c_uint = 0x400;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_MC_SHIFT: c_int = 11;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_MC_MASK: c_uint = 0x800;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_CPU_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_CPU_MASK: c_uint = 0x1000;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_IC_IF_SHIFT: c_int = 13;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_IC_IF_MASK: c_uint = 0x2000;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_PSOC_SHIFT: c_int = 14;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_PSOC_MASK: c_uint = 0x4000;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_SRAM_SHIFT: c_int = 15;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_SRAM_MASK: c_uint = 0x1F8000;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_DMA_SHIFT: c_int = 21;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_DMA_MASK: c_uint = 0x200000;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_DMA_IF_SHIFT: c_int = 22;
pub const PSOC_GLOBAL_CONF_PRSTN_RST_CFG_DMA_IF_MASK: c_uint = 0x400000;
// PSOC_GLOBAL_CONF_SW_ALL_RST_CFG
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_PCI_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_PCI_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_PCI_IF_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_PCI_IF_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_PLL_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_PLL_MASK: c_uint = 0x1FC;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_TPC_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_TPC_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_MME_SHIFT: c_int = 10;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_MME_MASK: c_uint = 0x400;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_MC_SHIFT: c_int = 11;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_MC_MASK: c_uint = 0x800;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_CPU_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_CPU_MASK: c_uint = 0x1000;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_IC_IF_SHIFT: c_int = 13;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_IC_IF_MASK: c_uint = 0x2000;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_PSOC_SHIFT: c_int = 14;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_PSOC_MASK: c_uint = 0x4000;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_SRAM_SHIFT: c_int = 15;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_SRAM_MASK: c_uint = 0x1F8000;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_DMA_SHIFT: c_int = 21;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_DMA_MASK: c_uint = 0x200000;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_DMA_IF_SHIFT: c_int = 22;
pub const PSOC_GLOBAL_CONF_SW_ALL_RST_CFG_DMA_IF_MASK: c_uint = 0x400000;
// PSOC_GLOBAL_CONF_WD_RST_CFG
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_PCI_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_PCI_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_PCI_IF_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_PCI_IF_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_PLL_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_PLL_MASK: c_uint = 0x1FC;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_TPC_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_TPC_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_MME_SHIFT: c_int = 10;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_MME_MASK: c_uint = 0x400;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_MC_SHIFT: c_int = 11;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_MC_MASK: c_uint = 0x800;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_CPU_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_CPU_MASK: c_uint = 0x1000;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_IC_IF_SHIFT: c_int = 13;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_IC_IF_MASK: c_uint = 0x2000;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_PSOC_SHIFT: c_int = 14;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_PSOC_MASK: c_uint = 0x4000;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_SRAM_SHIFT: c_int = 15;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_SRAM_MASK: c_uint = 0x1F8000;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_DMA_SHIFT: c_int = 21;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_DMA_MASK: c_uint = 0x200000;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_DMA_IF_SHIFT: c_int = 22;
pub const PSOC_GLOBAL_CONF_WD_RST_CFG_DMA_IF_MASK: c_uint = 0x400000;
// PSOC_GLOBAL_CONF_MNL_RST_CFG
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_PCI_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_PCI_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_PCI_IF_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_PCI_IF_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_PLL_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_PLL_MASK: c_uint = 0x1FC;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_TPC_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_TPC_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_MME_SHIFT: c_int = 10;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_MME_MASK: c_uint = 0x400;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_MC_SHIFT: c_int = 11;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_MC_MASK: c_uint = 0x800;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_CPU_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_CPU_MASK: c_uint = 0x1000;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_IC_IF_SHIFT: c_int = 13;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_IC_IF_MASK: c_uint = 0x2000;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_PSOC_SHIFT: c_int = 14;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_PSOC_MASK: c_uint = 0x4000;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_SRAM_SHIFT: c_int = 15;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_SRAM_MASK: c_uint = 0x1F8000;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_DMA_SHIFT: c_int = 21;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_DMA_MASK: c_uint = 0x200000;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_DMA_IF_SHIFT: c_int = 22;
pub const PSOC_GLOBAL_CONF_MNL_RST_CFG_DMA_IF_MASK: c_uint = 0x400000;
// PSOC_GLOBAL_CONF_UNIT_RST_N
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_PCI_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_PCI_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_PCI_IF_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_PCI_IF_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_PLL_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_PLL_MASK: c_uint = 0x1FC;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_TPC_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_TPC_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_MME_SHIFT: c_int = 10;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_MME_MASK: c_uint = 0x400;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_MC_SHIFT: c_int = 11;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_MC_MASK: c_uint = 0x800;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_CPU_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_CPU_MASK: c_uint = 0x1000;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_IC_IF_SHIFT: c_int = 13;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_IC_IF_MASK: c_uint = 0x2000;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_PSOC_SHIFT: c_int = 14;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_PSOC_MASK: c_uint = 0x4000;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_SRAM_SHIFT: c_int = 15;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_SRAM_MASK: c_uint = 0x1F8000;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_DMA_SHIFT: c_int = 21;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_DMA_MASK: c_uint = 0x200000;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_DMA_IF_SHIFT: c_int = 22;
pub const PSOC_GLOBAL_CONF_UNIT_RST_N_DMA_IF_MASK: c_uint = 0x400000;
// PSOC_GLOBAL_CONF_PRSTN_MASK
pub const PSOC_GLOBAL_CONF_PRSTN_MASK_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PRSTN_MASK_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_WD_MASK
pub const PSOC_GLOBAL_CONF_WD_MASK_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_WD_MASK_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_RST_SRC
pub const PSOC_GLOBAL_CONF_RST_SRC_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_RST_SRC_VAL_MASK: c_uint = 0xF;
// PSOC_GLOBAL_CONF_PAD_1V8_CFG
pub const PSOC_GLOBAL_CONF_PAD_1V8_CFG_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PAD_1V8_CFG_VAL_MASK: c_uint = 0x7F;
// PSOC_GLOBAL_CONF_PAD_3V3_CFG
pub const PSOC_GLOBAL_CONF_PAD_3V3_CFG_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PAD_3V3_CFG_VAL_MASK: c_uint = 0x7F;
// PSOC_GLOBAL_CONF_PAD_1V8_INPUT
pub const PSOC_GLOBAL_CONF_PAD_1V8_INPUT_CFG_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PAD_1V8_INPUT_CFG_MASK: c_uint = 0x7;
// PSOC_GLOBAL_CONF_BNK3V3_MS
pub const PSOC_GLOBAL_CONF_BNK3V3_MS_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BNK3V3_MS_VAL_MASK: c_uint = 0x3;
// PSOC_GLOBAL_CONF_PAD_DEFAULT
pub const PSOC_GLOBAL_CONF_PAD_DEFAULT_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PAD_DEFAULT_VAL_MASK: c_uint = 0xF;
// PSOC_GLOBAL_CONF_PAD_SEL
pub const PSOC_GLOBAL_CONF_PAD_SEL_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PAD_SEL_VAL_MASK: c_uint = 0x3;
