//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/goya/asic_reg/tpc0_eml_cfg_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2018 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// TPC0_EML_CFG (Prototype: TPC_EML_CFG)
//
// TPC0_EML_CFG_DBG_CNT
pub const TPC0_EML_CFG_DBG_CNT_DBG_ENTER_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_CNT_DBG_ENTER_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_DBG_CNT_DBG_EN_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_DBG_CNT_DBG_EN_MASK: c_uint = 0x2;
pub const TPC0_EML_CFG_DBG_CNT_CORE_RST_SHIFT: c_int = 2;
pub const TPC0_EML_CFG_DBG_CNT_CORE_RST_MASK: c_uint = 0x4;
pub const TPC0_EML_CFG_DBG_CNT_DCACHE_INV_SHIFT: c_int = 4;
pub const TPC0_EML_CFG_DBG_CNT_DCACHE_INV_MASK: c_uint = 0x10;
pub const TPC0_EML_CFG_DBG_CNT_ICACHE_INV_SHIFT: c_int = 5;
pub const TPC0_EML_CFG_DBG_CNT_ICACHE_INV_MASK: c_uint = 0x20;
pub const TPC0_EML_CFG_DBG_CNT_DBG_EXIT_SHIFT: c_int = 6;
pub const TPC0_EML_CFG_DBG_CNT_DBG_EXIT_MASK: c_uint = 0x40;
pub const TPC0_EML_CFG_DBG_CNT_SNG_STEP_SHIFT: c_int = 7;
pub const TPC0_EML_CFG_DBG_CNT_SNG_STEP_MASK: c_uint = 0x80;
pub const TPC0_EML_CFG_DBG_CNT_BP_DBGSW_EN_SHIFT: c_int = 16;
pub const TPC0_EML_CFG_DBG_CNT_BP_DBGSW_EN_MASK: c_uint = 0x10000;
// TPC0_EML_CFG_DBG_STS
pub const TPC0_EML_CFG_DBG_STS_DBG_MODE_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_STS_DBG_MODE_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_DBG_STS_CORE_READY_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_DBG_STS_CORE_READY_MASK: c_uint = 0x2;
pub const TPC0_EML_CFG_DBG_STS_DURING_KERNEL_SHIFT: c_int = 2;
pub const TPC0_EML_CFG_DBG_STS_DURING_KERNEL_MASK: c_uint = 0x4;
pub const TPC0_EML_CFG_DBG_STS_ICACHE_IDLE_SHIFT: c_int = 3;
pub const TPC0_EML_CFG_DBG_STS_ICACHE_IDLE_MASK: c_uint = 0x8;
pub const TPC0_EML_CFG_DBG_STS_DCACHE_IDLE_SHIFT: c_int = 4;
pub const TPC0_EML_CFG_DBG_STS_DCACHE_IDLE_MASK: c_uint = 0x10;
pub const TPC0_EML_CFG_DBG_STS_QM_IDLE_SHIFT: c_int = 5;
pub const TPC0_EML_CFG_DBG_STS_QM_IDLE_MASK: c_uint = 0x20;
pub const TPC0_EML_CFG_DBG_STS_WQ_IDLE_SHIFT: c_int = 6;
pub const TPC0_EML_CFG_DBG_STS_WQ_IDLE_MASK: c_uint = 0x40;
pub const TPC0_EML_CFG_DBG_STS_MSS_IDLE_SHIFT: c_int = 7;
pub const TPC0_EML_CFG_DBG_STS_MSS_IDLE_MASK: c_uint = 0x80;
pub const TPC0_EML_CFG_DBG_STS_DBG_CAUSE_SHIFT: c_int = 8;
pub const TPC0_EML_CFG_DBG_STS_DBG_CAUSE_MASK: c_uint = 0xFFFFFF00;
// TPC0_EML_CFG_DBG_PADD
pub const TPC0_EML_CFG_DBG_PADD_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_PADD_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_PADD_COUNT
pub const TPC0_EML_CFG_DBG_PADD_COUNT_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_PADD_COUNT_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_PADD_COUNT_MATCH
pub const TPC0_EML_CFG_DBG_PADD_COUNT_MATCH_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_PADD_COUNT_MATCH_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_PADD_EN
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE0_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE0_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE1_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE1_MASK: c_uint = 0x2;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE2_SHIFT: c_int = 2;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE2_MASK: c_uint = 0x4;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE3_SHIFT: c_int = 3;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE3_MASK: c_uint = 0x8;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE4_SHIFT: c_int = 4;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE4_MASK: c_uint = 0x10;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE5_SHIFT: c_int = 5;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE5_MASK: c_uint = 0x20;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE6_SHIFT: c_int = 6;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE6_MASK: c_uint = 0x40;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE7_SHIFT: c_int = 7;
pub const TPC0_EML_CFG_DBG_PADD_EN_ENABLE7_MASK: c_uint = 0x80;
// TPC0_EML_CFG_DBG_VPADD_HIGH
pub const TPC0_EML_CFG_DBG_VPADD_HIGH_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_VPADD_HIGH_ADDRESS_MASK: c_uint = 0x1FF;
// TPC0_EML_CFG_DBG_VPADD_LOW
pub const TPC0_EML_CFG_DBG_VPADD_LOW_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_VPADD_LOW_ADDRESS_MASK: c_uint = 0x1FF;
// TPC0_EML_CFG_DBG_VPADD_COUNT
pub const TPC0_EML_CFG_DBG_VPADD_COUNT_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_VPADD_COUNT_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_VPADD_COUNT_MATCH
pub const TPC0_EML_CFG_DBG_VPADD_COUNT_MATCH_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_VPADD_COUNT_MATCH_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_VPADD_EN
pub const TPC0_EML_CFG_DBG_VPADD_EN_ENABLE0_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_VPADD_EN_ENABLE0_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_DBG_VPADD_EN_ENABLE1_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_DBG_VPADD_EN_ENABLE1_MASK: c_uint = 0x2;
pub const TPC0_EML_CFG_DBG_VPADD_EN_RW_N0_SHIFT: c_int = 2;
pub const TPC0_EML_CFG_DBG_VPADD_EN_RW_N0_MASK: c_uint = 0x4;
pub const TPC0_EML_CFG_DBG_VPADD_EN_RW_N1_SHIFT: c_int = 3;
pub const TPC0_EML_CFG_DBG_VPADD_EN_RW_N1_MASK: c_uint = 0x8;
// TPC0_EML_CFG_DBG_SPADD_HIGH
pub const TPC0_EML_CFG_DBG_SPADD_HIGH_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_SPADD_HIGH_ADDRESS_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_SPADD_LOW
pub const TPC0_EML_CFG_DBG_SPADD_LOW_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_SPADD_LOW_ADDRESS_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_SPADD_COUNT
pub const TPC0_EML_CFG_DBG_SPADD_COUNT_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_SPADD_COUNT_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_SPADD_COUNT_MATCH
pub const TPC0_EML_CFG_DBG_SPADD_COUNT_MATCH_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_SPADD_COUNT_MATCH_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_SPADD_EN
pub const TPC0_EML_CFG_DBG_SPADD_EN_ENABLE0_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_SPADD_EN_ENABLE0_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_DBG_SPADD_EN_ENABLE1_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_DBG_SPADD_EN_ENABLE1_MASK: c_uint = 0x2;
pub const TPC0_EML_CFG_DBG_SPADD_EN_RW_N0_SHIFT: c_int = 2;
pub const TPC0_EML_CFG_DBG_SPADD_EN_RW_N0_MASK: c_uint = 0x4;
pub const TPC0_EML_CFG_DBG_SPADD_EN_RW_N1_SHIFT: c_int = 3;
pub const TPC0_EML_CFG_DBG_SPADD_EN_RW_N1_MASK: c_uint = 0x8;
// TPC0_EML_CFG_DBG_AGUADD_MSB_HIGH
pub const TPC0_EML_CFG_DBG_AGUADD_MSB_HIGH_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AGUADD_MSB_HIGH_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AGUADD_MSB_LOW
pub const TPC0_EML_CFG_DBG_AGUADD_MSB_LOW_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AGUADD_MSB_LOW_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AGUADD_LSB_HIGH
pub const TPC0_EML_CFG_DBG_AGUADD_LSB_HIGH_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AGUADD_LSB_HIGH_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AGUADD_LSB_LOW
pub const TPC0_EML_CFG_DBG_AGUADD_LSB_LOW_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AGUADD_LSB_LOW_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AGUADD_COUNT
pub const TPC0_EML_CFG_DBG_AGUADD_COUNT_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AGUADD_COUNT_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_AGUADD_COUNT_MATCH
pub const TPC0_EML_CFG_DBG_AGUADD_COUNT_MATCH_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AGUADD_COUNT_MATCH_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_AGUADD_EN
pub const TPC0_EML_CFG_DBG_AGUADD_EN_ENABLE0_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AGUADD_EN_ENABLE0_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_DBG_AGUADD_EN_ENABLE1_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_DBG_AGUADD_EN_ENABLE1_MASK: c_uint = 0x2;
pub const TPC0_EML_CFG_DBG_AGUADD_EN_RW_N0_SHIFT: c_int = 2;
pub const TPC0_EML_CFG_DBG_AGUADD_EN_RW_N0_MASK: c_uint = 0x4;
pub const TPC0_EML_CFG_DBG_AGUADD_EN_RW_N1_SHIFT: c_int = 3;
pub const TPC0_EML_CFG_DBG_AGUADD_EN_RW_N1_MASK: c_uint = 0x8;
// TPC0_EML_CFG_DBG_AXIHBWADD_MSB_HIGH
pub const TPC0_EML_CFG_DBG_AXIHBWADD_MSB_HIGH_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_MSB_HIGH_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AXIHBWADD_MSB_LOW
pub const TPC0_EML_CFG_DBG_AXIHBWADD_MSB_LOW_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_MSB_LOW_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AXIHBWADD_LSB_HIGH
pub const TPC0_EML_CFG_DBG_AXIHBWADD_LSB_HIGH_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_LSB_HIGH_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AXIHBWADD_LSB_LOW
pub const TPC0_EML_CFG_DBG_AXIHBWADD_LSB_LOW_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_LSB_LOW_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AXIHBWADD_COUNT
pub const TPC0_EML_CFG_DBG_AXIHBWADD_COUNT_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_COUNT_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_AXIHBWADD_COUNT_MATCH
pub const TPC0_EML_CFG_DBG_AXIHBWADD_COUNT_MATCH_MATCH_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_COUNT_MATCH_MATCH_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_AXIHBWADD_EN
pub const TPC0_EML_CFG_DBG_AXIHBWADD_EN_ENABLE0_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_EN_ENABLE0_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_EN_ENABLE1_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_EN_ENABLE1_MASK: c_uint = 0x2;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_EN_RW_N0_SHIFT: c_int = 2;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_EN_RW_N0_MASK: c_uint = 0x4;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_EN_RW_N1_SHIFT: c_int = 3;
pub const TPC0_EML_CFG_DBG_AXIHBWADD_EN_RW_N1_MASK: c_uint = 0x8;
// TPC0_EML_CFG_DBG_AXILBWADD_MSB_HIGH
pub const TPC0_EML_CFG_DBG_AXILBWADD_MSB_HIGH_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXILBWADD_MSB_HIGH_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AXILBWADD_MSB_LOW
pub const TPC0_EML_CFG_DBG_AXILBWADD_MSB_LOW_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXILBWADD_MSB_LOW_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AXILBWADD_LSB_HIGH
pub const TPC0_EML_CFG_DBG_AXILBWADD_LSB_HIGH_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXILBWADD_LSB_HIGH_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AXILBWADD_LSB_LOW
pub const TPC0_EML_CFG_DBG_AXILBWADD_LSB_LOW_ADDRESS_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXILBWADD_LSB_LOW_ADDRESS_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AXILBWADD_COUNT
pub const TPC0_EML_CFG_DBG_AXILBWADD_COUNT_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXILBWADD_COUNT_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_AXILBWADD_COUNT_MATCH
pub const TPC0_EML_CFG_DBG_AXILBWADD_COUNT_MATCH_MATCH_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXILBWADD_COUNT_MATCH_MATCH_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_AXILBWADD_EN
pub const TPC0_EML_CFG_DBG_AXILBWADD_EN_ENABLE0_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXILBWADD_EN_ENABLE0_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_DBG_AXILBWADD_EN_ENABLE1_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_DBG_AXILBWADD_EN_ENABLE1_MASK: c_uint = 0x2;
pub const TPC0_EML_CFG_DBG_AXILBWADD_EN_RW_N0_SHIFT: c_int = 2;
pub const TPC0_EML_CFG_DBG_AXILBWADD_EN_RW_N0_MASK: c_uint = 0x4;
pub const TPC0_EML_CFG_DBG_AXILBWADD_EN_RW_N1_SHIFT: c_int = 3;
pub const TPC0_EML_CFG_DBG_AXILBWADD_EN_RW_N1_MASK: c_uint = 0x8;
// TPC0_EML_CFG_DBG_SPDATA
pub const TPC0_EML_CFG_DBG_SPDATA_DATA_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_SPDATA_DATA_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_SPDATA_COUNT
pub const TPC0_EML_CFG_DBG_SPDATA_COUNT_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_SPDATA_COUNT_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_SPDATA_COUNT_MATCH
pub const TPC0_EML_CFG_DBG_SPDATA_COUNT_MATCH_MATCH_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_SPDATA_COUNT_MATCH_MATCH_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_SPDATA_EN
pub const TPC0_EML_CFG_DBG_SPDATA_EN_ENABLE0_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_SPDATA_EN_ENABLE0_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_DBG_SPDATA_EN_ENABLE1_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_DBG_SPDATA_EN_ENABLE1_MASK: c_uint = 0x2;
pub const TPC0_EML_CFG_DBG_SPDATA_EN_RW_N0_SHIFT: c_int = 2;
pub const TPC0_EML_CFG_DBG_SPDATA_EN_RW_N0_MASK: c_uint = 0x4;
pub const TPC0_EML_CFG_DBG_SPDATA_EN_RW_N1_SHIFT: c_int = 3;
pub const TPC0_EML_CFG_DBG_SPDATA_EN_RW_N1_MASK: c_uint = 0x8;
// TPC0_EML_CFG_DBG_AXIHBWDATA
pub const TPC0_EML_CFG_DBG_AXIHBWDATA_DATA_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXIHBWDATA_DATA_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AXIHBWDATA_COUNT
pub const TPC0_EML_CFG_DBG_AXIHBWDATA_COUNT_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXIHBWDATA_COUNT_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_AXIHBWDAT_COUNT_MATCH
pub const TPC0_EML_CFG_DBG_AXIHBWDAT_COUNT_MATCH_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXIHBWDAT_COUNT_MATCH_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_AXIHBWDATA_EN
pub const TPC0_EML_CFG_DBG_AXIHBWDATA_EN_ENABLE_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXIHBWDATA_EN_ENABLE_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_DBG_AXIHBWDATA_EN_RW_N_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_DBG_AXIHBWDATA_EN_RW_N_MASK: c_uint = 0x2;
// TPC0_EML_CFG_DBG_AXILBWDATA
pub const TPC0_EML_CFG_DBG_AXILBWDATA_DATA_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXILBWDATA_DATA_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_AXILBWDATA_COUNT
pub const TPC0_EML_CFG_DBG_AXILBWDATA_COUNT_COUNT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXILBWDATA_COUNT_COUNT_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_AXILBWDAT_COUNT_MATCH
pub const TPC0_EML_CFG_DBG_AXILBWDAT_COUNT_MATCH_MATCH_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXILBWDAT_COUNT_MATCH_MATCH_MASK: c_uint = 0xFF;
// TPC0_EML_CFG_DBG_AXILBWDATA_EN
pub const TPC0_EML_CFG_DBG_AXILBWDATA_EN_ENABLE_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_AXILBWDATA_EN_ENABLE_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_DBG_AXILBWDATA_EN_RW_N_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_DBG_AXILBWDATA_EN_RW_N_MASK: c_uint = 0x2;
// TPC0_EML_CFG_DBG_D0_PC
pub const TPC0_EML_CFG_DBG_D0_PC_PC_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_D0_PC_PC_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_RTTCONFIG
pub const TPC0_EML_CFG_RTTCONFIG_TR_EN_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_RTTCONFIG_TR_EN_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_RTTCONFIG_PRIO_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_RTTCONFIG_PRIO_MASK: c_uint = 0x2;
// TPC0_EML_CFG_RTTPREDICATE
pub const TPC0_EML_CFG_RTTPREDICATE_TR_EN_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_RTTPREDICATE_TR_EN_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_RTTPREDICATE_GEN_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_RTTPREDICATE_GEN_MASK: c_uint = 0x2;
pub const TPC0_EML_CFG_RTTPREDICATE_USE_INTERVAL_SHIFT: c_int = 2;
pub const TPC0_EML_CFG_RTTPREDICATE_USE_INTERVAL_MASK: c_uint = 0x4;
pub const TPC0_EML_CFG_RTTPREDICATE_SPRF_MASK_SHIFT: c_int = 16;
pub const TPC0_EML_CFG_RTTPREDICATE_SPRF_MASK_MASK: c_uint = 0xFFFF0000;
// TPC0_EML_CFG_RTTPREDICATE_INTV
pub const TPC0_EML_CFG_RTTPREDICATE_INTV_INTERVAL_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_RTTPREDICATE_INTV_INTERVAL_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_RTTTS
pub const TPC0_EML_CFG_RTTTS_TR_EN_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_RTTTS_TR_EN_MASK: c_uint = 0x1;
pub const TPC0_EML_CFG_RTTTS_GEN_SHIFT: c_int = 1;
pub const TPC0_EML_CFG_RTTTS_GEN_MASK: c_uint = 0x2;
pub const TPC0_EML_CFG_RTTTS_COMPRESS_EN_SHIFT: c_int = 2;
pub const TPC0_EML_CFG_RTTTS_COMPRESS_EN_MASK: c_uint = 0x4;
// TPC0_EML_CFG_RTTTS_INTV
pub const TPC0_EML_CFG_RTTTS_INTV_INTERVAL_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_RTTTS_INTV_INTERVAL_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_INST_INSERT
pub const TPC0_EML_CFG_DBG_INST_INSERT_INST_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_INST_INSERT_INST_MASK: c_uint = 0xFFFFFFFF;
// TPC0_EML_CFG_DBG_INST_INSERT_CTL
pub const TPC0_EML_CFG_DBG_INST_INSERT_CTL_INSERT_SHIFT: c_int = 0;
pub const TPC0_EML_CFG_DBG_INST_INSERT_CTL_INSERT_MASK: c_uint = 0x1;
