//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/goya/asic_reg/tpc0_cfg_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2018 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// TPC0_CFG (Prototype: TPC)
//
// TPC0_CFG_KERNEL_TENSOR_0_BASE_ADDR_LOW
pub const TPC0_CFG_KERNEL_TENSOR_0_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_BASE_ADDR_HIGH
pub const TPC0_CFG_KERNEL_TENSOR_0_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_PADDING_VALUE
pub const TPC0_CFG_KERNEL_TENSOR_0_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_TENSOR_CONFIG
pub const TPC0_CFG_KERNEL_TENSOR_0_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_KERNEL_TENSOR_0_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_KERNEL_TENSOR_0_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_KERNEL_TENSOR_0_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_KERNEL_TENSOR_0_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_0_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_0_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_0_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_1_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_1_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_1_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_2_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_2_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_2_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_3_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_3_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_3_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_4_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_4_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_0_DIM_4_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_0_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_BASE_ADDR_LOW
pub const TPC0_CFG_KERNEL_TENSOR_1_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_BASE_ADDR_HIGH
pub const TPC0_CFG_KERNEL_TENSOR_1_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_PADDING_VALUE
pub const TPC0_CFG_KERNEL_TENSOR_1_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_TENSOR_CONFIG
pub const TPC0_CFG_KERNEL_TENSOR_1_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_KERNEL_TENSOR_1_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_KERNEL_TENSOR_1_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_KERNEL_TENSOR_1_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_KERNEL_TENSOR_1_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_0_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_0_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_0_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_1_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_1_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_1_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_2_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_2_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_2_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_3_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_3_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_3_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_4_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_4_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_1_DIM_4_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_1_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_BASE_ADDR_LOW
pub const TPC0_CFG_KERNEL_TENSOR_2_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_BASE_ADDR_HIGH
pub const TPC0_CFG_KERNEL_TENSOR_2_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_PADDING_VALUE
pub const TPC0_CFG_KERNEL_TENSOR_2_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_TENSOR_CONFIG
pub const TPC0_CFG_KERNEL_TENSOR_2_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_KERNEL_TENSOR_2_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_KERNEL_TENSOR_2_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_KERNEL_TENSOR_2_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_KERNEL_TENSOR_2_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_0_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_0_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_0_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_1_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_1_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_1_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_2_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_2_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_2_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_3_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_3_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_3_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_4_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_4_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_2_DIM_4_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_2_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_BASE_ADDR_LOW
pub const TPC0_CFG_KERNEL_TENSOR_3_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_BASE_ADDR_HIGH
pub const TPC0_CFG_KERNEL_TENSOR_3_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_PADDING_VALUE
pub const TPC0_CFG_KERNEL_TENSOR_3_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_TENSOR_CONFIG
pub const TPC0_CFG_KERNEL_TENSOR_3_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_KERNEL_TENSOR_3_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_KERNEL_TENSOR_3_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_KERNEL_TENSOR_3_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_KERNEL_TENSOR_3_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_0_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_0_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_0_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_1_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_1_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_1_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_2_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_2_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_2_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_3_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_3_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_3_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_4_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_4_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_3_DIM_4_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_3_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_BASE_ADDR_LOW
pub const TPC0_CFG_KERNEL_TENSOR_4_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_BASE_ADDR_HIGH
pub const TPC0_CFG_KERNEL_TENSOR_4_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_PADDING_VALUE
pub const TPC0_CFG_KERNEL_TENSOR_4_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_TENSOR_CONFIG
pub const TPC0_CFG_KERNEL_TENSOR_4_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_KERNEL_TENSOR_4_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_KERNEL_TENSOR_4_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_KERNEL_TENSOR_4_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_KERNEL_TENSOR_4_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_0_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_0_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_0_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_1_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_1_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_1_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_2_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_2_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_2_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_3_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_3_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_3_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_4_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_4_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_4_DIM_4_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_4_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_BASE_ADDR_LOW
pub const TPC0_CFG_KERNEL_TENSOR_5_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_BASE_ADDR_HIGH
pub const TPC0_CFG_KERNEL_TENSOR_5_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_PADDING_VALUE
pub const TPC0_CFG_KERNEL_TENSOR_5_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_TENSOR_CONFIG
pub const TPC0_CFG_KERNEL_TENSOR_5_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_KERNEL_TENSOR_5_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_KERNEL_TENSOR_5_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_KERNEL_TENSOR_5_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_KERNEL_TENSOR_5_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_0_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_0_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_0_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_1_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_1_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_1_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_2_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_2_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_2_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_3_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_3_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_3_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_4_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_4_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_5_DIM_4_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_5_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_BASE_ADDR_LOW
pub const TPC0_CFG_KERNEL_TENSOR_6_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_BASE_ADDR_HIGH
pub const TPC0_CFG_KERNEL_TENSOR_6_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_PADDING_VALUE
pub const TPC0_CFG_KERNEL_TENSOR_6_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_TENSOR_CONFIG
pub const TPC0_CFG_KERNEL_TENSOR_6_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_KERNEL_TENSOR_6_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_KERNEL_TENSOR_6_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_KERNEL_TENSOR_6_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_KERNEL_TENSOR_6_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_0_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_0_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_0_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_1_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_1_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_1_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_2_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_2_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_2_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_3_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_3_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_3_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_4_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_4_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_6_DIM_4_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_6_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_BASE_ADDR_LOW
pub const TPC0_CFG_KERNEL_TENSOR_7_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_BASE_ADDR_HIGH
pub const TPC0_CFG_KERNEL_TENSOR_7_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_PADDING_VALUE
pub const TPC0_CFG_KERNEL_TENSOR_7_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_TENSOR_CONFIG
pub const TPC0_CFG_KERNEL_TENSOR_7_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_KERNEL_TENSOR_7_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_KERNEL_TENSOR_7_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_KERNEL_TENSOR_7_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_KERNEL_TENSOR_7_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_0_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_0_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_0_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_1_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_1_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_1_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_2_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_2_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_2_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_3_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_3_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_3_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_4_SIZE
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_4_STRIDE
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TENSOR_7_DIM_4_BASE_OFFSET
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TENSOR_7_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_KERNEL_BASE_ADDRESS_LOW
pub const TPC0_CFG_KERNEL_KERNEL_BASE_ADDRESS_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_KERNEL_BASE_ADDRESS_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_KERNEL_BASE_ADDRESS_HIGH
pub const TPC0_CFG_KERNEL_KERNEL_BASE_ADDRESS_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_KERNEL_BASE_ADDRESS_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TID_BASE_DIM_0
pub const TPC0_CFG_KERNEL_TID_BASE_DIM_0_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TID_BASE_DIM_0_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TID_SIZE_DIM_0
pub const TPC0_CFG_KERNEL_TID_SIZE_DIM_0_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TID_SIZE_DIM_0_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TID_BASE_DIM_1
pub const TPC0_CFG_KERNEL_TID_BASE_DIM_1_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TID_BASE_DIM_1_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TID_SIZE_DIM_1
pub const TPC0_CFG_KERNEL_TID_SIZE_DIM_1_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TID_SIZE_DIM_1_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TID_BASE_DIM_2
pub const TPC0_CFG_KERNEL_TID_BASE_DIM_2_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TID_BASE_DIM_2_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TID_SIZE_DIM_2
pub const TPC0_CFG_KERNEL_TID_SIZE_DIM_2_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TID_SIZE_DIM_2_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TID_BASE_DIM_3
pub const TPC0_CFG_KERNEL_TID_BASE_DIM_3_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TID_BASE_DIM_3_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TID_SIZE_DIM_3
pub const TPC0_CFG_KERNEL_TID_SIZE_DIM_3_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TID_SIZE_DIM_3_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TID_BASE_DIM_4
pub const TPC0_CFG_KERNEL_TID_BASE_DIM_4_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TID_BASE_DIM_4_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_TID_SIZE_DIM_4
pub const TPC0_CFG_KERNEL_TID_SIZE_DIM_4_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_TID_SIZE_DIM_4_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_SRF
pub const TPC0_CFG_KERNEL_SRF_V_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_SRF_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_KERNEL_KERNEL_CONFIG
pub const TPC0_CFG_KERNEL_KERNEL_CONFIG_SMALL_VLM_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_KERNEL_CONFIG_SMALL_VLM_MASK: c_uint = 0x1;
pub const TPC0_CFG_KERNEL_KERNEL_CONFIG_ASO_EVICT_L0_SHIFT: c_int = 1;
pub const TPC0_CFG_KERNEL_KERNEL_CONFIG_ASO_EVICT_L0_MASK: c_uint = 0x2;
pub const TPC0_CFG_KERNEL_KERNEL_CONFIG_NUM_VALID_SRFS_SHIFT: c_int = 8;
pub const TPC0_CFG_KERNEL_KERNEL_CONFIG_NUM_VALID_SRFS_MASK: c_uint = 0x3F00;
// TPC0_CFG_KERNEL_SYNC_OBJECT_MESSAGE
pub const TPC0_CFG_KERNEL_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_SHIFT: c_int = 0;
pub const TPC0_CFG_KERNEL_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_MASK: c_uint = 0xFFFF;
pub const TPC0_CFG_KERNEL_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_SHIFT: c_int = 16;
pub const TPC0_CFG_KERNEL_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_MASK: c_uint = 0x7FFF0000;
pub const TPC0_CFG_KERNEL_SYNC_OBJECT_MESSAGE_SO_OPERATION_SHIFT: c_int = 31;
pub const TPC0_CFG_KERNEL_SYNC_OBJECT_MESSAGE_SO_OPERATION_MASK: c_uint = 0x80000000;
// TPC0_CFG_RESERVED_DESC_END
pub const TPC0_CFG_RESERVED_DESC_END_V_SHIFT: c_int = 0;
pub const TPC0_CFG_RESERVED_DESC_END_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_ROUND_CSR
pub const TPC0_CFG_ROUND_CSR_MODE_SHIFT: c_int = 0;
pub const TPC0_CFG_ROUND_CSR_MODE_MASK: c_uint = 0x7;
// TPC0_CFG_TBUF_BASE_ADDR_LOW
pub const TPC0_CFG_TBUF_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_TBUF_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_TBUF_BASE_ADDR_HIGH
pub const TPC0_CFG_TBUF_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_TBUF_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_SEMAPHORE
pub const TPC0_CFG_SEMAPHORE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_SEMAPHORE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_VFLAGS
pub const TPC0_CFG_VFLAGS_V_SHIFT: c_int = 0;
pub const TPC0_CFG_VFLAGS_V_MASK: c_uint = 0xF;
// TPC0_CFG_SFLAGS
pub const TPC0_CFG_SFLAGS_V_SHIFT: c_int = 0;
pub const TPC0_CFG_SFLAGS_V_MASK: c_uint = 0xF;
// TPC0_CFG_LFSR_POLYNOM
pub const TPC0_CFG_LFSR_POLYNOM_V_SHIFT: c_int = 0;
pub const TPC0_CFG_LFSR_POLYNOM_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_STATUS
pub const TPC0_CFG_STATUS_SCALAR_PIPE_EMPTY_SHIFT: c_int = 1;
pub const TPC0_CFG_STATUS_SCALAR_PIPE_EMPTY_MASK: c_uint = 0x2;
pub const TPC0_CFG_STATUS_VECTOR_PIPE_EMPTY_SHIFT: c_int = 2;
pub const TPC0_CFG_STATUS_VECTOR_PIPE_EMPTY_MASK: c_uint = 0x4;
pub const TPC0_CFG_STATUS_IQ_EMPTY_SHIFT: c_int = 3;
pub const TPC0_CFG_STATUS_IQ_EMPTY_MASK: c_uint = 0x8;
pub const TPC0_CFG_STATUS_NO_INFLIGH_MEM_ACCESSES_SHIFT: c_int = 4;
pub const TPC0_CFG_STATUS_NO_INFLIGH_MEM_ACCESSES_MASK: c_uint = 0x10;
// TPC0_CFG_CFG_BASE_ADDRESS_HIGH
pub const TPC0_CFG_CFG_BASE_ADDRESS_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_CFG_BASE_ADDRESS_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_CFG_SUBTRACT_VALUE
pub const TPC0_CFG_CFG_SUBTRACT_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_CFG_SUBTRACT_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_SM_BASE_ADDRESS_LOW
pub const TPC0_CFG_SM_BASE_ADDRESS_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_SM_BASE_ADDRESS_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_SM_BASE_ADDRESS_HIGH
pub const TPC0_CFG_SM_BASE_ADDRESS_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_SM_BASE_ADDRESS_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_TPC_CMD
pub const TPC0_CFG_TPC_CMD_ICACHE_INVALIDATE_SHIFT: c_int = 0;
pub const TPC0_CFG_TPC_CMD_ICACHE_INVALIDATE_MASK: c_uint = 0x1;
pub const TPC0_CFG_TPC_CMD_DCACHE_INVALIDATE_SHIFT: c_int = 1;
pub const TPC0_CFG_TPC_CMD_DCACHE_INVALIDATE_MASK: c_uint = 0x2;
pub const TPC0_CFG_TPC_CMD_LCACHE_INVALIDATE_SHIFT: c_int = 2;
pub const TPC0_CFG_TPC_CMD_LCACHE_INVALIDATE_MASK: c_uint = 0x4;
pub const TPC0_CFG_TPC_CMD_TCACHE_INVALIDATE_SHIFT: c_int = 3;
pub const TPC0_CFG_TPC_CMD_TCACHE_INVALIDATE_MASK: c_uint = 0x8;
pub const TPC0_CFG_TPC_CMD_ICACHE_PREFETCH_64KB_SHIFT: c_int = 4;
pub const TPC0_CFG_TPC_CMD_ICACHE_PREFETCH_64KB_MASK: c_uint = 0x10;
pub const TPC0_CFG_TPC_CMD_ICACHE_PREFETCH_32KB_SHIFT: c_int = 5;
pub const TPC0_CFG_TPC_CMD_ICACHE_PREFETCH_32KB_MASK: c_uint = 0x20;
pub const TPC0_CFG_TPC_CMD_QMAN_STOP_SHIFT: c_int = 6;
pub const TPC0_CFG_TPC_CMD_QMAN_STOP_MASK: c_uint = 0x40;
// TPC0_CFG_TPC_EXECUTE
pub const TPC0_CFG_TPC_EXECUTE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_TPC_EXECUTE_V_MASK: c_uint = 0x1;
// TPC0_CFG_TPC_STALL
pub const TPC0_CFG_TPC_STALL_V_SHIFT: c_int = 0;
pub const TPC0_CFG_TPC_STALL_V_MASK: c_uint = 0x1;
// TPC0_CFG_ICACHE_BASE_ADDERESS_LOW
pub const TPC0_CFG_ICACHE_BASE_ADDERESS_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_ICACHE_BASE_ADDERESS_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_ICACHE_BASE_ADDERESS_HIGH
pub const TPC0_CFG_ICACHE_BASE_ADDERESS_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_ICACHE_BASE_ADDERESS_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_MSS_CONFIG
pub const TPC0_CFG_MSS_CONFIG_AWCACHE_SHIFT: c_int = 0;
pub const TPC0_CFG_MSS_CONFIG_AWCACHE_MASK: c_uint = 0xF;
pub const TPC0_CFG_MSS_CONFIG_ARCACHE_SHIFT: c_int = 4;
pub const TPC0_CFG_MSS_CONFIG_ARCACHE_MASK: c_uint = 0xF0;
pub const TPC0_CFG_MSS_CONFIG_ICACHE_FETCH_LINE_NUM_SHIFT: c_int = 8;
pub const TPC0_CFG_MSS_CONFIG_ICACHE_FETCH_LINE_NUM_MASK: c_uint = 0x300;
pub const TPC0_CFG_MSS_CONFIG_EXPOSED_PIPE_DIS_SHIFT: c_int = 10;
pub const TPC0_CFG_MSS_CONFIG_EXPOSED_PIPE_DIS_MASK: c_uint = 0x400;
// TPC0_CFG_TPC_INTR_CAUSE
pub const TPC0_CFG_TPC_INTR_CAUSE_CAUSE_SHIFT: c_int = 0;
pub const TPC0_CFG_TPC_INTR_CAUSE_CAUSE_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_TPC_INTR_MASK
pub const TPC0_CFG_TPC_INTR_MASK_MASK_SHIFT: c_int = 0;
pub const TPC0_CFG_TPC_INTR_MASK_MASK_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_TSB_CONFIG
pub const TPC0_CFG_TSB_CONFIG_TSB_AGU_MAX_CREDIT_SHIFT: c_int = 0;
pub const TPC0_CFG_TSB_CONFIG_TSB_AGU_MAX_CREDIT_MASK: c_uint = 0x1F;
pub const TPC0_CFG_TSB_CONFIG_TSB_EU_MAX_CREDIT_SHIFT: c_int = 5;
pub const TPC0_CFG_TSB_CONFIG_TSB_EU_MAX_CREDIT_MASK: c_uint = 0x3E0;
pub const TPC0_CFG_TSB_CONFIG_MAX_OUTSTANDING_SHIFT: c_int = 10;
pub const TPC0_CFG_TSB_CONFIG_MAX_OUTSTANDING_MASK: c_uint = 0xFFC00;
pub const TPC0_CFG_TSB_CONFIG_MAX_SIZE_SHIFT: c_int = 20;
pub const TPC0_CFG_TSB_CONFIG_MAX_SIZE_MASK: c_uint = 0x3FF00000;
// TPC0_CFG_QM_TENSOR_0_BASE_ADDR_LOW
pub const TPC0_CFG_QM_TENSOR_0_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_BASE_ADDR_HIGH
pub const TPC0_CFG_QM_TENSOR_0_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_PADDING_VALUE
pub const TPC0_CFG_QM_TENSOR_0_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_TENSOR_CONFIG
pub const TPC0_CFG_QM_TENSOR_0_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_QM_TENSOR_0_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_QM_TENSOR_0_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_QM_TENSOR_0_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_QM_TENSOR_0_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_QM_TENSOR_0_DIM_0_SIZE
pub const TPC0_CFG_QM_TENSOR_0_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_0_STRIDE
pub const TPC0_CFG_QM_TENSOR_0_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_0_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_0_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_1_SIZE
pub const TPC0_CFG_QM_TENSOR_0_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_1_STRIDE
pub const TPC0_CFG_QM_TENSOR_0_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_1_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_0_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_2_SIZE
pub const TPC0_CFG_QM_TENSOR_0_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_2_STRIDE
pub const TPC0_CFG_QM_TENSOR_0_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_2_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_0_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_3_SIZE
pub const TPC0_CFG_QM_TENSOR_0_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_3_STRIDE
pub const TPC0_CFG_QM_TENSOR_0_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_3_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_0_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_4_SIZE
pub const TPC0_CFG_QM_TENSOR_0_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_4_STRIDE
pub const TPC0_CFG_QM_TENSOR_0_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_0_DIM_4_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_0_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_0_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_BASE_ADDR_LOW
pub const TPC0_CFG_QM_TENSOR_1_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_BASE_ADDR_HIGH
pub const TPC0_CFG_QM_TENSOR_1_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_PADDING_VALUE
pub const TPC0_CFG_QM_TENSOR_1_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_TENSOR_CONFIG
pub const TPC0_CFG_QM_TENSOR_1_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_QM_TENSOR_1_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_QM_TENSOR_1_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_QM_TENSOR_1_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_QM_TENSOR_1_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_QM_TENSOR_1_DIM_0_SIZE
pub const TPC0_CFG_QM_TENSOR_1_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_0_STRIDE
pub const TPC0_CFG_QM_TENSOR_1_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_0_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_1_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_1_SIZE
pub const TPC0_CFG_QM_TENSOR_1_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_1_STRIDE
pub const TPC0_CFG_QM_TENSOR_1_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_1_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_1_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_2_SIZE
pub const TPC0_CFG_QM_TENSOR_1_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_2_STRIDE
pub const TPC0_CFG_QM_TENSOR_1_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_2_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_1_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_3_SIZE
pub const TPC0_CFG_QM_TENSOR_1_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_3_STRIDE
pub const TPC0_CFG_QM_TENSOR_1_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_3_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_1_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_4_SIZE
pub const TPC0_CFG_QM_TENSOR_1_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_4_STRIDE
pub const TPC0_CFG_QM_TENSOR_1_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_1_DIM_4_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_1_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_1_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_BASE_ADDR_LOW
pub const TPC0_CFG_QM_TENSOR_2_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_BASE_ADDR_HIGH
pub const TPC0_CFG_QM_TENSOR_2_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_PADDING_VALUE
pub const TPC0_CFG_QM_TENSOR_2_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_TENSOR_CONFIG
pub const TPC0_CFG_QM_TENSOR_2_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_QM_TENSOR_2_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_QM_TENSOR_2_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_QM_TENSOR_2_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_QM_TENSOR_2_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_QM_TENSOR_2_DIM_0_SIZE
pub const TPC0_CFG_QM_TENSOR_2_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_0_STRIDE
pub const TPC0_CFG_QM_TENSOR_2_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_0_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_2_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_1_SIZE
pub const TPC0_CFG_QM_TENSOR_2_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_1_STRIDE
pub const TPC0_CFG_QM_TENSOR_2_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_1_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_2_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_2_SIZE
pub const TPC0_CFG_QM_TENSOR_2_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_2_STRIDE
pub const TPC0_CFG_QM_TENSOR_2_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_2_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_2_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_3_SIZE
pub const TPC0_CFG_QM_TENSOR_2_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_3_STRIDE
pub const TPC0_CFG_QM_TENSOR_2_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_3_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_2_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_4_SIZE
pub const TPC0_CFG_QM_TENSOR_2_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_4_STRIDE
pub const TPC0_CFG_QM_TENSOR_2_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_2_DIM_4_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_2_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_2_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_BASE_ADDR_LOW
pub const TPC0_CFG_QM_TENSOR_3_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_BASE_ADDR_HIGH
pub const TPC0_CFG_QM_TENSOR_3_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_PADDING_VALUE
pub const TPC0_CFG_QM_TENSOR_3_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_TENSOR_CONFIG
pub const TPC0_CFG_QM_TENSOR_3_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_QM_TENSOR_3_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_QM_TENSOR_3_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_QM_TENSOR_3_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_QM_TENSOR_3_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_QM_TENSOR_3_DIM_0_SIZE
pub const TPC0_CFG_QM_TENSOR_3_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_0_STRIDE
pub const TPC0_CFG_QM_TENSOR_3_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_0_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_3_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_1_SIZE
pub const TPC0_CFG_QM_TENSOR_3_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_1_STRIDE
pub const TPC0_CFG_QM_TENSOR_3_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_1_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_3_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_2_SIZE
pub const TPC0_CFG_QM_TENSOR_3_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_2_STRIDE
pub const TPC0_CFG_QM_TENSOR_3_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_2_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_3_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_3_SIZE
pub const TPC0_CFG_QM_TENSOR_3_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_3_STRIDE
pub const TPC0_CFG_QM_TENSOR_3_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_3_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_3_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_4_SIZE
pub const TPC0_CFG_QM_TENSOR_3_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_4_STRIDE
pub const TPC0_CFG_QM_TENSOR_3_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_3_DIM_4_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_3_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_3_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_BASE_ADDR_LOW
pub const TPC0_CFG_QM_TENSOR_4_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_BASE_ADDR_HIGH
pub const TPC0_CFG_QM_TENSOR_4_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_PADDING_VALUE
pub const TPC0_CFG_QM_TENSOR_4_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_TENSOR_CONFIG
pub const TPC0_CFG_QM_TENSOR_4_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_QM_TENSOR_4_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_QM_TENSOR_4_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_QM_TENSOR_4_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_QM_TENSOR_4_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_QM_TENSOR_4_DIM_0_SIZE
pub const TPC0_CFG_QM_TENSOR_4_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_0_STRIDE
pub const TPC0_CFG_QM_TENSOR_4_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_0_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_4_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_1_SIZE
pub const TPC0_CFG_QM_TENSOR_4_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_1_STRIDE
pub const TPC0_CFG_QM_TENSOR_4_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_1_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_4_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_2_SIZE
pub const TPC0_CFG_QM_TENSOR_4_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_2_STRIDE
pub const TPC0_CFG_QM_TENSOR_4_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_2_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_4_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_3_SIZE
pub const TPC0_CFG_QM_TENSOR_4_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_3_STRIDE
pub const TPC0_CFG_QM_TENSOR_4_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_3_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_4_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_4_SIZE
pub const TPC0_CFG_QM_TENSOR_4_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_4_STRIDE
pub const TPC0_CFG_QM_TENSOR_4_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_4_DIM_4_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_4_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_4_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_BASE_ADDR_LOW
pub const TPC0_CFG_QM_TENSOR_5_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_BASE_ADDR_HIGH
pub const TPC0_CFG_QM_TENSOR_5_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_PADDING_VALUE
pub const TPC0_CFG_QM_TENSOR_5_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_TENSOR_CONFIG
pub const TPC0_CFG_QM_TENSOR_5_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_QM_TENSOR_5_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_QM_TENSOR_5_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_QM_TENSOR_5_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_QM_TENSOR_5_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_QM_TENSOR_5_DIM_0_SIZE
pub const TPC0_CFG_QM_TENSOR_5_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_0_STRIDE
pub const TPC0_CFG_QM_TENSOR_5_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_0_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_5_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_1_SIZE
pub const TPC0_CFG_QM_TENSOR_5_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_1_STRIDE
pub const TPC0_CFG_QM_TENSOR_5_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_1_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_5_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_2_SIZE
pub const TPC0_CFG_QM_TENSOR_5_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_2_STRIDE
pub const TPC0_CFG_QM_TENSOR_5_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_2_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_5_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_3_SIZE
pub const TPC0_CFG_QM_TENSOR_5_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_3_STRIDE
pub const TPC0_CFG_QM_TENSOR_5_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_3_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_5_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_4_SIZE
pub const TPC0_CFG_QM_TENSOR_5_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_4_STRIDE
pub const TPC0_CFG_QM_TENSOR_5_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_5_DIM_4_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_5_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_5_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_BASE_ADDR_LOW
pub const TPC0_CFG_QM_TENSOR_6_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_BASE_ADDR_HIGH
pub const TPC0_CFG_QM_TENSOR_6_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_PADDING_VALUE
pub const TPC0_CFG_QM_TENSOR_6_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_TENSOR_CONFIG
pub const TPC0_CFG_QM_TENSOR_6_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_QM_TENSOR_6_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_QM_TENSOR_6_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_QM_TENSOR_6_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_QM_TENSOR_6_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_QM_TENSOR_6_DIM_0_SIZE
pub const TPC0_CFG_QM_TENSOR_6_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_0_STRIDE
pub const TPC0_CFG_QM_TENSOR_6_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_0_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_6_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_1_SIZE
pub const TPC0_CFG_QM_TENSOR_6_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_1_STRIDE
pub const TPC0_CFG_QM_TENSOR_6_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_1_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_6_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_2_SIZE
pub const TPC0_CFG_QM_TENSOR_6_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_2_STRIDE
pub const TPC0_CFG_QM_TENSOR_6_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_2_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_6_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_3_SIZE
pub const TPC0_CFG_QM_TENSOR_6_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_3_STRIDE
pub const TPC0_CFG_QM_TENSOR_6_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_3_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_6_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_4_SIZE
pub const TPC0_CFG_QM_TENSOR_6_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_4_STRIDE
pub const TPC0_CFG_QM_TENSOR_6_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_6_DIM_4_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_6_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_6_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_BASE_ADDR_LOW
pub const TPC0_CFG_QM_TENSOR_7_BASE_ADDR_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_BASE_ADDR_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_BASE_ADDR_HIGH
pub const TPC0_CFG_QM_TENSOR_7_BASE_ADDR_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_BASE_ADDR_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_PADDING_VALUE
pub const TPC0_CFG_QM_TENSOR_7_PADDING_VALUE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_PADDING_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_TENSOR_CONFIG
pub const TPC0_CFG_QM_TENSOR_7_TENSOR_CONFIG_DATA_TYPE_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_TENSOR_CONFIG_DATA_TYPE_MASK: c_uint = 0x3;
pub const TPC0_CFG_QM_TENSOR_7_TENSOR_CONFIG_VALID_DIM_MASK_SHIFT: c_int = 8;
pub const TPC0_CFG_QM_TENSOR_7_TENSOR_CONFIG_VALID_DIM_MASK_MASK: c_uint = 0x1F00;
pub const TPC0_CFG_QM_TENSOR_7_TENSOR_CONFIG_LAST_DIM_SHIFT: c_int = 16;
pub const TPC0_CFG_QM_TENSOR_7_TENSOR_CONFIG_LAST_DIM_MASK: c_uint = 0x70000;
// TPC0_CFG_QM_TENSOR_7_DIM_0_SIZE
pub const TPC0_CFG_QM_TENSOR_7_DIM_0_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_0_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_0_STRIDE
pub const TPC0_CFG_QM_TENSOR_7_DIM_0_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_0_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_0_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_7_DIM_0_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_0_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_1_SIZE
pub const TPC0_CFG_QM_TENSOR_7_DIM_1_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_1_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_1_STRIDE
pub const TPC0_CFG_QM_TENSOR_7_DIM_1_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_1_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_1_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_7_DIM_1_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_1_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_2_SIZE
pub const TPC0_CFG_QM_TENSOR_7_DIM_2_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_2_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_2_STRIDE
pub const TPC0_CFG_QM_TENSOR_7_DIM_2_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_2_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_2_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_7_DIM_2_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_2_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_3_SIZE
pub const TPC0_CFG_QM_TENSOR_7_DIM_3_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_3_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_3_STRIDE
pub const TPC0_CFG_QM_TENSOR_7_DIM_3_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_3_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_3_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_7_DIM_3_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_3_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_4_SIZE
pub const TPC0_CFG_QM_TENSOR_7_DIM_4_SIZE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_4_SIZE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_4_STRIDE
pub const TPC0_CFG_QM_TENSOR_7_DIM_4_STRIDE_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_4_STRIDE_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TENSOR_7_DIM_4_BASE_OFFSET
pub const TPC0_CFG_QM_TENSOR_7_DIM_4_BASE_OFFSET_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TENSOR_7_DIM_4_BASE_OFFSET_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_KERNEL_BASE_ADDRESS_LOW
pub const TPC0_CFG_QM_KERNEL_BASE_ADDRESS_LOW_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_KERNEL_BASE_ADDRESS_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_KERNEL_BASE_ADDRESS_HIGH
pub const TPC0_CFG_QM_KERNEL_BASE_ADDRESS_HIGH_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_KERNEL_BASE_ADDRESS_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TID_BASE_DIM_0
pub const TPC0_CFG_QM_TID_BASE_DIM_0_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TID_BASE_DIM_0_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TID_SIZE_DIM_0
pub const TPC0_CFG_QM_TID_SIZE_DIM_0_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TID_SIZE_DIM_0_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TID_BASE_DIM_1
pub const TPC0_CFG_QM_TID_BASE_DIM_1_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TID_BASE_DIM_1_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TID_SIZE_DIM_1
pub const TPC0_CFG_QM_TID_SIZE_DIM_1_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TID_SIZE_DIM_1_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TID_BASE_DIM_2
pub const TPC0_CFG_QM_TID_BASE_DIM_2_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TID_BASE_DIM_2_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TID_SIZE_DIM_2
pub const TPC0_CFG_QM_TID_SIZE_DIM_2_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TID_SIZE_DIM_2_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TID_BASE_DIM_3
pub const TPC0_CFG_QM_TID_BASE_DIM_3_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TID_BASE_DIM_3_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TID_SIZE_DIM_3
pub const TPC0_CFG_QM_TID_SIZE_DIM_3_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TID_SIZE_DIM_3_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TID_BASE_DIM_4
pub const TPC0_CFG_QM_TID_BASE_DIM_4_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TID_BASE_DIM_4_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_TID_SIZE_DIM_4
pub const TPC0_CFG_QM_TID_SIZE_DIM_4_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_TID_SIZE_DIM_4_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_SRF
pub const TPC0_CFG_QM_SRF_V_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_SRF_V_MASK: c_uint = 0xFFFFFFFF;
// TPC0_CFG_QM_KERNEL_CONFIG
pub const TPC0_CFG_QM_KERNEL_CONFIG_SMALL_VLM_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_KERNEL_CONFIG_SMALL_VLM_MASK: c_uint = 0x1;
pub const TPC0_CFG_QM_KERNEL_CONFIG_ASO_EVICT_L0_SHIFT: c_int = 1;
pub const TPC0_CFG_QM_KERNEL_CONFIG_ASO_EVICT_L0_MASK: c_uint = 0x2;
pub const TPC0_CFG_QM_KERNEL_CONFIG_NUM_VALID_SRFS_SHIFT: c_int = 8;
pub const TPC0_CFG_QM_KERNEL_CONFIG_NUM_VALID_SRFS_MASK: c_uint = 0x3F00;
// TPC0_CFG_QM_SYNC_OBJECT_MESSAGE
pub const TPC0_CFG_QM_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_SHIFT: c_int = 0;
pub const TPC0_CFG_QM_SYNC_OBJECT_MESSAGE_SO_WRITE_VALUE_MASK: c_uint = 0xFFFF;
pub const TPC0_CFG_QM_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_SHIFT: c_int = 16;
pub const TPC0_CFG_QM_SYNC_OBJECT_MESSAGE_SO_ADDRESS_OFFSET_MASK: c_uint = 0x7FFF0000;
pub const TPC0_CFG_QM_SYNC_OBJECT_MESSAGE_SO_OPERATION_SHIFT: c_int = 31;
pub const TPC0_CFG_QM_SYNC_OBJECT_MESSAGE_SO_OPERATION_MASK: c_uint = 0x80000000;
// TPC0_CFG_ARUSER
pub const TPC0_CFG_ARUSER_ASID_SHIFT: c_int = 0;
pub const TPC0_CFG_ARUSER_ASID_MASK: c_uint = 0x3FF;
pub const TPC0_CFG_ARUSER_MMBP_SHIFT: c_int = 10;
pub const TPC0_CFG_ARUSER_MMBP_MASK: c_uint = 0x400;
pub const TPC0_CFG_ARUSER_V_SHIFT: c_int = 11;
pub const TPC0_CFG_ARUSER_V_MASK: c_uint = 0xFFFFF800;
// TPC0_CFG_AWUSER
pub const TPC0_CFG_AWUSER_ASID_SHIFT: c_int = 0;
pub const TPC0_CFG_AWUSER_ASID_MASK: c_uint = 0x3FF;
pub const TPC0_CFG_AWUSER_MMBP_SHIFT: c_int = 10;
pub const TPC0_CFG_AWUSER_MMBP_MASK: c_uint = 0x400;
pub const TPC0_CFG_AWUSER_V_SHIFT: c_int = 11;
pub const TPC0_CFG_AWUSER_V_MASK: c_uint = 0xFFFFF800;
// TPC0_CFG_FUNC_MBIST_CNTRL
pub const TPC0_CFG_FUNC_MBIST_CNTRL_MBIST_START_SHIFT: c_int = 0;
pub const TPC0_CFG_FUNC_MBIST_CNTRL_MBIST_START_MASK: c_uint = 0x1;
pub const TPC0_CFG_FUNC_MBIST_CNTRL_MBIST_DONE_SHIFT: c_int = 1;
pub const TPC0_CFG_FUNC_MBIST_CNTRL_MBIST_DONE_MASK: c_uint = 0x2;
pub const TPC0_CFG_FUNC_MBIST_CNTRL_MBIST_ACTIVE_SHIFT: c_int = 2;
pub const TPC0_CFG_FUNC_MBIST_CNTRL_MBIST_ACTIVE_MASK: c_uint = 0x4;
pub const TPC0_CFG_FUNC_MBIST_CNTRL_MBIST_FAILED_SHIFT: c_int = 16;
pub const TPC0_CFG_FUNC_MBIST_CNTRL_MBIST_FAILED_MASK: c_uint = 0x3FF0000;
// TPC0_CFG_FUNC_MBIST_PAT
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN0_EVEN_SHIFT: c_int = 0;
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN0_EVEN_MASK: c_uint = 0x3;
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN0_ODD_SHIFT: c_int = 2;
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN0_ODD_MASK: c_uint = 0xC;
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN1_EVEN_SHIFT: c_int = 4;
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN1_EVEN_MASK: c_uint = 0x30;
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN1_ODD_SHIFT: c_int = 6;
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN1_ODD_MASK: c_uint = 0xC0;
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN2_EVEN_SHIFT: c_int = 8;
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN2_EVEN_MASK: c_uint = 0x300;
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN2_ODD_SHIFT: c_int = 10;
pub const TPC0_CFG_FUNC_MBIST_PAT_MBIST_PATTERN2_ODD_MASK: c_uint = 0xC00;
// TPC0_CFG_FUNC_MBIST_MEM
pub const TPC0_CFG_FUNC_MBIST_MEM_MAX_ADDR_SHIFT: c_int = 0;
pub const TPC0_CFG_FUNC_MBIST_MEM_MAX_ADDR_MASK: c_uint = 0x7FF;
pub const TPC0_CFG_FUNC_MBIST_MEM_PATTERN_EN_SHIFT: c_int = 12;
pub const TPC0_CFG_FUNC_MBIST_MEM_PATTERN_EN_MASK: c_uint = 0x7000;
pub const TPC0_CFG_FUNC_MBIST_MEM_LAST_FAILED_ADDR_SHIFT: c_int = 16;
pub const TPC0_CFG_FUNC_MBIST_MEM_LAST_FAILED_ADDR_MASK: c_uint = 0x7FF0000;
pub const TPC0_CFG_FUNC_MBIST_MEM_LAST_FAILED_PATTERN_SHIFT: c_int = 28;
pub const TPC0_CFG_FUNC_MBIST_MEM_LAST_FAILED_PATTERN_MASK: c_uint = 0x70000000;
