//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/amd/include/asic_reg/mp/mp_13_0_6_sh_mask.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// Copyright 2022 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

// Macro flag: #define _mp_13_0_6_SH_MASK_HEADER
// addressBlock: aid_mp_SmuMp0_SmnDec
// MP0_SMN_C2PMSG_32
pub const MP0_SMN_C2PMSG_32__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_32__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_33
pub const MP0_SMN_C2PMSG_33__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_33__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_34
pub const MP0_SMN_C2PMSG_34__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_34__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_35
pub const MP0_SMN_C2PMSG_35__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_35__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_36
pub const MP0_SMN_C2PMSG_36__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_36__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_37
pub const MP0_SMN_C2PMSG_37__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_37__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_38
pub const MP0_SMN_C2PMSG_38__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_38__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_39
pub const MP0_SMN_C2PMSG_39__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_39__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_40
pub const MP0_SMN_C2PMSG_40__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_40__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_41
pub const MP0_SMN_C2PMSG_41__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_41__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_42
pub const MP0_SMN_C2PMSG_42__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_42__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_43
pub const MP0_SMN_C2PMSG_43__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_43__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_44
pub const MP0_SMN_C2PMSG_44__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_44__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_45
pub const MP0_SMN_C2PMSG_45__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_45__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_46
pub const MP0_SMN_C2PMSG_46__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_46__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_47
pub const MP0_SMN_C2PMSG_47__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_47__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_48
pub const MP0_SMN_C2PMSG_48__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_48__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_49
pub const MP0_SMN_C2PMSG_49__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_49__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_50
pub const MP0_SMN_C2PMSG_50__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_50__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_51
pub const MP0_SMN_C2PMSG_51__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_51__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_52
pub const MP0_SMN_C2PMSG_52__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_52__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_53
pub const MP0_SMN_C2PMSG_53__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_53__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_54
pub const MP0_SMN_C2PMSG_54__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_54__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_55
pub const MP0_SMN_C2PMSG_55__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_55__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_56
pub const MP0_SMN_C2PMSG_56__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_56__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_57
pub const MP0_SMN_C2PMSG_57__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_57__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_58
pub const MP0_SMN_C2PMSG_58__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_58__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_59
pub const MP0_SMN_C2PMSG_59__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_59__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_60
pub const MP0_SMN_C2PMSG_60__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_60__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_61
pub const MP0_SMN_C2PMSG_61__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_61__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_62
pub const MP0_SMN_C2PMSG_62__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_62__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_63
pub const MP0_SMN_C2PMSG_63__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_63__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_64
pub const MP0_SMN_C2PMSG_64__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_64__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_65
pub const MP0_SMN_C2PMSG_65__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_65__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_66
pub const MP0_SMN_C2PMSG_66__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_66__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_67
pub const MP0_SMN_C2PMSG_67__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_67__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_68
pub const MP0_SMN_C2PMSG_68__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_68__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_69
pub const MP0_SMN_C2PMSG_69__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_69__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_70
pub const MP0_SMN_C2PMSG_70__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_70__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_71
pub const MP0_SMN_C2PMSG_71__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_71__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_72
pub const MP0_SMN_C2PMSG_72__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_72__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_73
pub const MP0_SMN_C2PMSG_73__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_73__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_74
pub const MP0_SMN_C2PMSG_74__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_74__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_75
pub const MP0_SMN_C2PMSG_75__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_75__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_76
pub const MP0_SMN_C2PMSG_76__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_76__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_77
pub const MP0_SMN_C2PMSG_77__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_77__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_78
pub const MP0_SMN_C2PMSG_78__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_78__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_79
pub const MP0_SMN_C2PMSG_79__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_79__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_80
pub const MP0_SMN_C2PMSG_80__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_80__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_81
pub const MP0_SMN_C2PMSG_81__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_81__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_82
pub const MP0_SMN_C2PMSG_82__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_82__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_83
pub const MP0_SMN_C2PMSG_83__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_83__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_84
pub const MP0_SMN_C2PMSG_84__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_84__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_85
pub const MP0_SMN_C2PMSG_85__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_85__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_86
pub const MP0_SMN_C2PMSG_86__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_86__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_87
pub const MP0_SMN_C2PMSG_87__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_87__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_88
pub const MP0_SMN_C2PMSG_88__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_88__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_89
pub const MP0_SMN_C2PMSG_89__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_89__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_90
pub const MP0_SMN_C2PMSG_90__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_90__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_91
pub const MP0_SMN_C2PMSG_91__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_91__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_92
pub const MP0_SMN_C2PMSG_92__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_92__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_93
pub const MP0_SMN_C2PMSG_93__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_93__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_94
pub const MP0_SMN_C2PMSG_94__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_94__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_95
pub const MP0_SMN_C2PMSG_95__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_95__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_96
pub const MP0_SMN_C2PMSG_96__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_96__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_97
pub const MP0_SMN_C2PMSG_97__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_97__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_98
pub const MP0_SMN_C2PMSG_98__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_98__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_99
pub const MP0_SMN_C2PMSG_99__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_99__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_100
pub const MP0_SMN_C2PMSG_100__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_100__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_101
pub const MP0_SMN_C2PMSG_101__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_101__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_102
pub const MP0_SMN_C2PMSG_102__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_102__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_C2PMSG_103
pub const MP0_SMN_C2PMSG_103__CONTENT__SHIFT: c_uint = 0x0;
pub const MP0_SMN_C2PMSG_103__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP0_SMN_IH_CREDIT
pub const MP0_SMN_IH_CREDIT__CREDIT_VALUE__SHIFT: c_uint = 0x0;
pub const MP0_SMN_IH_CREDIT__CLIENT_ID__SHIFT: c_uint = 0x10;
pub const MP0_SMN_IH_CREDIT__CREDIT_VALUE_MASK: c_uint = 0x00000003L;
pub const MP0_SMN_IH_CREDIT__CLIENT_ID_MASK: c_uint = 0x00FF0000L;
// MP0_SMN_IH_SW_INT
pub const MP0_SMN_IH_SW_INT__ID__SHIFT: c_uint = 0x0;
pub const MP0_SMN_IH_SW_INT__VALID__SHIFT: c_uint = 0x8;
pub const MP0_SMN_IH_SW_INT__ID_MASK: c_uint = 0x000000FFL;
pub const MP0_SMN_IH_SW_INT__VALID_MASK: c_uint = 0x00000100L;
// MP0_SMN_IH_SW_INT_CTRL
pub const MP0_SMN_IH_SW_INT_CTRL__INT_MASK__SHIFT: c_uint = 0x0;
pub const MP0_SMN_IH_SW_INT_CTRL__INT_ACK__SHIFT: c_uint = 0x8;
pub const MP0_SMN_IH_SW_INT_CTRL__INT_MASK_MASK: c_uint = 0x00000001L;
pub const MP0_SMN_IH_SW_INT_CTRL__INT_ACK_MASK: c_uint = 0x00000100L;
// addressBlock: aid_mp_SmuMp1_SmnDec
// MP1_SMN_C2PMSG_32
pub const MP1_SMN_C2PMSG_32__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_32__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_33
pub const MP1_SMN_C2PMSG_33__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_33__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_34
pub const MP1_SMN_C2PMSG_34__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_34__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_35
pub const MP1_SMN_C2PMSG_35__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_35__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_36
pub const MP1_SMN_C2PMSG_36__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_36__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_37
pub const MP1_SMN_C2PMSG_37__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_37__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_38
pub const MP1_SMN_C2PMSG_38__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_38__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_39
pub const MP1_SMN_C2PMSG_39__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_39__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_40
pub const MP1_SMN_C2PMSG_40__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_40__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_41
pub const MP1_SMN_C2PMSG_41__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_41__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_42
pub const MP1_SMN_C2PMSG_42__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_42__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_43
pub const MP1_SMN_C2PMSG_43__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_43__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_44
pub const MP1_SMN_C2PMSG_44__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_44__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_45
pub const MP1_SMN_C2PMSG_45__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_45__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_46
pub const MP1_SMN_C2PMSG_46__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_46__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_47
pub const MP1_SMN_C2PMSG_47__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_47__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_48
pub const MP1_SMN_C2PMSG_48__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_48__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_49
pub const MP1_SMN_C2PMSG_49__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_49__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_50
pub const MP1_SMN_C2PMSG_50__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_50__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_51
pub const MP1_SMN_C2PMSG_51__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_51__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_52
pub const MP1_SMN_C2PMSG_52__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_52__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_53
pub const MP1_SMN_C2PMSG_53__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_53__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_54
pub const MP1_SMN_C2PMSG_54__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_54__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_55
pub const MP1_SMN_C2PMSG_55__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_55__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_56
pub const MP1_SMN_C2PMSG_56__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_56__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_57
pub const MP1_SMN_C2PMSG_57__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_57__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_58
pub const MP1_SMN_C2PMSG_58__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_58__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_59
pub const MP1_SMN_C2PMSG_59__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_59__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_60
pub const MP1_SMN_C2PMSG_60__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_60__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_61
pub const MP1_SMN_C2PMSG_61__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_61__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_62
pub const MP1_SMN_C2PMSG_62__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_62__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_63
pub const MP1_SMN_C2PMSG_63__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_63__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_64
pub const MP1_SMN_C2PMSG_64__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_64__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_65
pub const MP1_SMN_C2PMSG_65__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_65__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_66
pub const MP1_SMN_C2PMSG_66__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_66__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_67
pub const MP1_SMN_C2PMSG_67__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_67__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_68
pub const MP1_SMN_C2PMSG_68__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_68__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_69
pub const MP1_SMN_C2PMSG_69__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_69__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_70
pub const MP1_SMN_C2PMSG_70__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_70__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_71
pub const MP1_SMN_C2PMSG_71__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_71__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_72
pub const MP1_SMN_C2PMSG_72__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_72__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_73
pub const MP1_SMN_C2PMSG_73__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_73__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_74
pub const MP1_SMN_C2PMSG_74__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_74__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_75
pub const MP1_SMN_C2PMSG_75__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_75__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_76
pub const MP1_SMN_C2PMSG_76__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_76__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_77
pub const MP1_SMN_C2PMSG_77__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_77__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_78
pub const MP1_SMN_C2PMSG_78__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_78__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_79
pub const MP1_SMN_C2PMSG_79__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_79__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_80
pub const MP1_SMN_C2PMSG_80__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_80__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_81
pub const MP1_SMN_C2PMSG_81__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_81__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_82
pub const MP1_SMN_C2PMSG_82__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_82__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_83
pub const MP1_SMN_C2PMSG_83__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_83__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_84
pub const MP1_SMN_C2PMSG_84__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_84__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_85
pub const MP1_SMN_C2PMSG_85__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_85__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_86
pub const MP1_SMN_C2PMSG_86__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_86__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_87
pub const MP1_SMN_C2PMSG_87__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_87__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_88
pub const MP1_SMN_C2PMSG_88__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_88__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_89
pub const MP1_SMN_C2PMSG_89__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_89__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_90
pub const MP1_SMN_C2PMSG_90__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_90__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_91
pub const MP1_SMN_C2PMSG_91__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_91__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_92
pub const MP1_SMN_C2PMSG_92__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_92__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_93
pub const MP1_SMN_C2PMSG_93__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_93__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_94
pub const MP1_SMN_C2PMSG_94__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_94__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_95
pub const MP1_SMN_C2PMSG_95__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_95__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_96
pub const MP1_SMN_C2PMSG_96__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_96__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_97
pub const MP1_SMN_C2PMSG_97__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_97__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_98
pub const MP1_SMN_C2PMSG_98__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_98__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_99
pub const MP1_SMN_C2PMSG_99__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_99__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_100
pub const MP1_SMN_C2PMSG_100__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_100__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_101
pub const MP1_SMN_C2PMSG_101__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_101__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_102
pub const MP1_SMN_C2PMSG_102__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_102__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_103
pub const MP1_SMN_C2PMSG_103__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_103__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_104
pub const MP1_SMN_C2PMSG_104__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_104__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_105
pub const MP1_SMN_C2PMSG_105__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_105__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_106
pub const MP1_SMN_C2PMSG_106__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_106__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_107
pub const MP1_SMN_C2PMSG_107__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_107__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_108
pub const MP1_SMN_C2PMSG_108__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_108__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_109
pub const MP1_SMN_C2PMSG_109__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_109__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_110
pub const MP1_SMN_C2PMSG_110__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_110__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_111
pub const MP1_SMN_C2PMSG_111__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_111__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_112
pub const MP1_SMN_C2PMSG_112__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_112__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_113
pub const MP1_SMN_C2PMSG_113__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_113__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_114
pub const MP1_SMN_C2PMSG_114__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_114__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_115
pub const MP1_SMN_C2PMSG_115__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_115__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_116
pub const MP1_SMN_C2PMSG_116__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_116__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_117
pub const MP1_SMN_C2PMSG_117__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_117__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_118
pub const MP1_SMN_C2PMSG_118__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_118__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_119
pub const MP1_SMN_C2PMSG_119__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_119__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_120
pub const MP1_SMN_C2PMSG_120__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_120__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_121
pub const MP1_SMN_C2PMSG_121__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_121__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_122
pub const MP1_SMN_C2PMSG_122__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_122__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_123
pub const MP1_SMN_C2PMSG_123__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_123__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_124
pub const MP1_SMN_C2PMSG_124__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_124__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_125
pub const MP1_SMN_C2PMSG_125__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_125__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_126
pub const MP1_SMN_C2PMSG_126__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_126__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_C2PMSG_127
pub const MP1_SMN_C2PMSG_127__CONTENT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_C2PMSG_127__CONTENT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_IH_CREDIT
pub const MP1_SMN_IH_CREDIT__CREDIT_VALUE__SHIFT: c_uint = 0x0;
pub const MP1_SMN_IH_CREDIT__CLIENT_ID__SHIFT: c_uint = 0x10;
pub const MP1_SMN_IH_CREDIT__CREDIT_VALUE_MASK: c_uint = 0x00000003L;
pub const MP1_SMN_IH_CREDIT__CLIENT_ID_MASK: c_uint = 0x00FF0000L;
// MP1_SMN_IH_SW_INT
pub const MP1_SMN_IH_SW_INT__ID__SHIFT: c_uint = 0x0;
pub const MP1_SMN_IH_SW_INT__VALID__SHIFT: c_uint = 0x8;
pub const MP1_SMN_IH_SW_INT__ID_MASK: c_uint = 0x000000FFL;
pub const MP1_SMN_IH_SW_INT__VALID_MASK: c_uint = 0x00000100L;
// MP1_SMN_IH_SW_INT_CTRL
pub const MP1_SMN_IH_SW_INT_CTRL__INT_MASK__SHIFT: c_uint = 0x0;
pub const MP1_SMN_IH_SW_INT_CTRL__INT_ACK__SHIFT: c_uint = 0x8;
pub const MP1_SMN_IH_SW_INT_CTRL__INT_MASK_MASK: c_uint = 0x00000001L;
pub const MP1_SMN_IH_SW_INT_CTRL__INT_ACK_MASK: c_uint = 0x00000100L;
// MP1_SMN_FPS_CNT
pub const MP1_SMN_FPS_CNT__COUNT__SHIFT: c_uint = 0x0;
pub const MP1_SMN_FPS_CNT__COUNT_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_PUB_CTRL
pub const MP1_SMN_PUB_CTRL__LX3_RESET__SHIFT: c_uint = 0x0;
pub const MP1_SMN_PUB_CTRL__LX3_RESET_MASK: c_uint = 0x00000001L;
// MP1_SMN_EXT_SCRATCH0
pub const MP1_SMN_EXT_SCRATCH0__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH0__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH1
pub const MP1_SMN_EXT_SCRATCH1__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH1__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH2
pub const MP1_SMN_EXT_SCRATCH2__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH2__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH3
pub const MP1_SMN_EXT_SCRATCH3__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH3__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH4
pub const MP1_SMN_EXT_SCRATCH4__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH4__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH5
pub const MP1_SMN_EXT_SCRATCH5__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH5__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH6
pub const MP1_SMN_EXT_SCRATCH6__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH6__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH7
pub const MP1_SMN_EXT_SCRATCH7__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH7__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH8
pub const MP1_SMN_EXT_SCRATCH8__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH8__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH10
pub const MP1_SMN_EXT_SCRATCH10__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH10__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH11
pub const MP1_SMN_EXT_SCRATCH11__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH11__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH12
pub const MP1_SMN_EXT_SCRATCH12__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH12__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH13
pub const MP1_SMN_EXT_SCRATCH13__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH13__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH14
pub const MP1_SMN_EXT_SCRATCH14__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH14__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH15
pub const MP1_SMN_EXT_SCRATCH15__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH15__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH16
pub const MP1_SMN_EXT_SCRATCH16__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH16__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH17
pub const MP1_SMN_EXT_SCRATCH17__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH17__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH18
pub const MP1_SMN_EXT_SCRATCH18__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH18__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH19
pub const MP1_SMN_EXT_SCRATCH19__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH19__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH20
pub const MP1_SMN_EXT_SCRATCH20__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH20__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH21
pub const MP1_SMN_EXT_SCRATCH21__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH21__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH22
pub const MP1_SMN_EXT_SCRATCH22__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH22__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH23
pub const MP1_SMN_EXT_SCRATCH23__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH23__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH24
pub const MP1_SMN_EXT_SCRATCH24__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH24__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH25
pub const MP1_SMN_EXT_SCRATCH25__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH25__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH26
pub const MP1_SMN_EXT_SCRATCH26__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH26__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH27
pub const MP1_SMN_EXT_SCRATCH27__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH27__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH28
pub const MP1_SMN_EXT_SCRATCH28__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH28__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH29
pub const MP1_SMN_EXT_SCRATCH29__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH29__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH30
pub const MP1_SMN_EXT_SCRATCH30__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH30__DATA_MASK: c_uint = 0xFFFFFFFFL;
// MP1_SMN_EXT_SCRATCH31
pub const MP1_SMN_EXT_SCRATCH31__DATA__SHIFT: c_uint = 0x0;
pub const MP1_SMN_EXT_SCRATCH31__DATA_MASK: c_uint = 0xFFFFFFFFL;
// addressBlock: aid_mp_SmuMp1Pub_CruDec
// MP1_FIRMWARE_FLAGS
pub const MP1_FIRMWARE_FLAGS__INTERRUPTS_ENABLED__SHIFT: c_uint = 0x0;
pub const MP1_FIRMWARE_FLAGS__RESERVED__SHIFT: c_uint = 0x1;
pub const MP1_FIRMWARE_FLAGS__INTERRUPTS_ENABLED_MASK: c_uint = 0x00000001L;
pub const MP1_FIRMWARE_FLAGS__RESERVED_MASK: c_uint = 0xFFFFFFFEL;
// MCMP1_IPIDT0
pub const MCMP1_IPIDT0__InstanceIdLo__SHIFT: c_uint = 0x0;
pub const MCMP1_IPIDT0__HardwareID__SHIFT: c_uint = 0x20;
pub const MCMP1_IPIDT0__InstanceIdHi__SHIFT: c_uint = 0x2c;
pub const MCMP1_IPIDT0__McaType__SHIFT: c_uint = 0x30;
pub const MCMP1_IPIDT0__InstanceIdLo_MASK: c_uint = 0x00000000FFFFFFFFL;
pub const MCMP1_IPIDT0__HardwareID_MASK: c_uint = 0x00000FFF00000000L;
pub const MCMP1_IPIDT0__InstanceIdHi_MASK: c_uint = 0x0000F00000000000L;
pub const MCMP1_IPIDT0__McaType_MASK: c_uint = 0xFFFF000000000000L;
// MCMP1_STATUST0
pub const MCMP1_STATUST0__ErrorCode__SHIFT: c_uint = 0x0;
pub const MCMP1_STATUST0__ErrorCodeExt__SHIFT: c_uint = 0x10;
pub const MCMP1_STATUST0__PCC__SHIFT: c_uint = 0x39;
pub const MCMP1_STATUST0__UC__SHIFT: c_uint = 0x3d;
pub const MCMP1_STATUST0__Val__SHIFT: c_uint = 0x3f;
pub const MCMP1_STATUST0__ErrorCode_MASK: c_uint = 0x000000000000FFFFL;
pub const MCMP1_STATUST0__ErrorCodeExt_MASK: c_uint = 0x00000000003F0000L;
pub const MCMP1_STATUST0__PCC_MASK: c_uint = 0x0200000000000000L;
pub const MCMP1_STATUST0__UC_MASK: c_uint = 0x2000000000000000L;
pub const MCMP1_STATUST0__Val_MASK: c_uint = 0x8000000000000000L;
// MCMP1_MISC0T0
pub const MCMP1_MISC0T0__ErrCnt__SHIFT: c_uint = 0x20;
pub const MCMP1_MISC0T0__ErrCnt_MASK: c_uint = 0x00000FFF00000000L;
