//! Automatically rewritten from C Header to Rust Module
//! Source: lib/crc/riscv/crc-clmul-consts.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0-or-later
//
// CRC constants generated by:
//
// ./scripts/gen-crc-consts.py riscv_clmul crc16_msb_0x8bb7,crc32_msb_0x04c11db7,crc32_lsb_0xedb88320,crc32_lsb_0x82f63b78,crc64_msb_0x42f0e1eba9ea3693,crc64_lsb_0x9a6c9329ac4bc9b5
//
// Do not edit manually.
//
#[repr(C)]
#[derive(Copy, Clone)]
pub struct crc_clmul_consts {
    pub fold_across_2_longs_const_hi: c_ulong,
    pub fold_across_2_longs_const_lo: c_ulong,
    pub barrett_reduction_const_1: c_ulong,
    pub barrett_reduction_const_2: c_ulong,
}

//
// Constants generated for most-significant-bit-first CRC-16 using
// G(x) = x^16 + x^15 + x^11 + x^9 + x^8 + x^7 + x^5 + x^4 + x^2 + x^1 + x^0
//

//
// Constants generated for most-significant-bit-first CRC-32 using
// G(x) = x^32 + x^26 + x^23 + x^22 + x^16 + x^12 + x^11 + x^10 + x^8 + x^7 +
// x^5 + x^4 + x^2 + x^1 + x^0
//

//
// Constants generated for least-significant-bit-first CRC-32 using
// G(x) = x^32 + x^26 + x^23 + x^22 + x^16 + x^12 + x^11 + x^10 + x^8 + x^7 +
// x^5 + x^4 + x^2 + x^1 + x^0
//

//
// Constants generated for least-significant-bit-first CRC-32 using
// G(x) = x^32 + x^28 + x^27 + x^26 + x^25 + x^23 + x^22 + x^20 + x^19 + x^18 +
// x^14 + x^13 + x^11 + x^10 + x^9 + x^8 + x^6 + x^0
//

//
// Constants generated for most-significant-bit-first CRC-64 using
// G(x) = x^64 + x^62 + x^57 + x^55 + x^54 + x^53 + x^52 + x^47 + x^46 + x^45 +
// x^40 + x^39 + x^38 + x^37 + x^35 + x^33 + x^32 + x^31 + x^29 + x^27 +
// x^24 + x^23 + x^22 + x^21 + x^19 + x^17 + x^13 + x^12 + x^10 + x^9 +
// x^7 + x^4 + x^1 + x^0
//

//
// Constants generated for least-significant-bit-first CRC-64 using
// G(x) = x^64 + x^63 + x^61 + x^59 + x^58 + x^56 + x^55 + x^52 + x^49 + x^48 +
// x^47 + x^46 + x^44 + x^41 + x^37 + x^36 + x^34 + x^32 + x^31 + x^28 +
// x^26 + x^23 + x^22 + x^19 + x^16 + x^13 + x^12 + x^10 + x^9 + x^6 +
// x^4 + x^3 + x^0
//

