//! Automatically rewritten from C Header to Rust Module
//! Source: include/linux/fsnotify.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// include/linux/fsnotify.h - generic hooks for filesystem notification, to
// reduce in-source duplication from both dnotify and inotify.
//
// We don't compile any of this away in some complicated menagerie of ifdefs.
// Instead, we rely on the code inside to optimize away as needed.
//
// (C) Copyright 2005 Robert Love
//

// Are there any inode/mount/sb objects watched with priority prio or above?
// Were any marks ever added to any object on this sb?
extern "C" {
    pub fn atomic_long_read(_arg: &sbinfo->watched_objects[prio]) -> return;
}
// Are there any inode/mount/sb objects that are being watched at all?
extern "C" {
    pub fn fsnotify_sb_has_priority_watchers(_arg: sb, _arg: 0) -> return;
}
//
// Notify this @dir inode about a change in a child directory entry.
// The directory entry may have turned positive or negative or its inode may
// have changed (i.e. renamed over).
//
// Unlike fsnotify_parent(), the event will be reported regardless of the
// FS_EVENT_ON_CHILD mask on the parent inode and will not be reported if only
// the child is interested and not the parent.
//
extern "C" {
    pub fn fsnotify(_arg: mask, _arg: data, _arg: data_type, _arg: dir, _arg: name, _arg: NULL, _arg: cookie) -> return;
}
// Notify this dentry's parent about a child's events.
// sb/mount marks are not interested in name of directory
// disconnected dentry cannot notify parent
extern "C" {
    pub fn __fsnotify_parent(_arg: dentry, _arg: mask, _arg: data, _arg: data_type) -> return;
}
extern "C" {
    pub fn fsnotify(_arg: mask, _arg: data, _arg: data_type, _arg: NULL, _arg: NULL, _arg: inode, _arg: 0) -> return;
}
//
// Simple wrappers to consolidate calls to fsnotify_parent() when an event
// is on a file/dentry.
//
extern "C" {
    pub fn fsnotify_parent(_arg: path->dentry, _arg: mask, _arg: path, _arg: FSNOTIFY_EVENT_PATH) -> return;
}
//
// FMODE_NONOTIFY are fds generated by fanotify itself which should not
// generate new events. We also don't want to generate events for
// FMODE_PATH fds (involves open & close events) as they are just
// handle creation / destruction events and not "real" file events.
//
extern "C" {
    pub fn fsnotify_path(_arg: &file->f_path, _arg: mask) -> return;
}

extern "C" {
    pub fn fsnotify_open_perm_and_set_mode(file: *mut file) -> c_int;
}
//
// fsnotify_file_area_perm - permission hook before access to file range
//
// filesystem may be modified in the context of permission events
// (e.g. by HSM filling a file on access), so sb freeze protection
// must not be held.
//
// read()/write() and other types of access generate pre-content events.
//
// read() also generates the legacy FS_ACCESS_PERM event, so content
// scanners can inspect the content filled by pre-content event.
//
extern "C" {
    pub fn fsnotify_path(_arg: &file->f_path, _arg: FS_ACCESS_PERM) -> return;
}
//
// fsnotify_mmap_perm - permission hook before mmap of file range
//
// mmap() generates only pre-content events.
//
extern "C" {
    pub fn fsnotify_pre_content(_arg: &file->f_path, _arg: &off, _arg: len) -> return;
}
//
// fsnotify_truncate_perm - permission hook before file truncate
//
extern "C" {
    pub fn fsnotify_pre_content(_arg: path, _arg: &length, _arg: 0) -> return;
}
//
// fsnotify_file_perm - permission hook before file access (unknown range)
//
extern "C" {
    pub fn fsnotify_file_area_perm(_arg: file, _arg: perm_mask, _arg: NULL, _arg: 0) -> return;
}

//
// fsnotify_link_count - inode's link count changed
//
// fsnotify_move - file old_name at old_dir was moved to new_name at new_dir
//
// Event with information about both old and new parent+name
//
// fsnotify_inode_delete - and inode is being evicted from cache, clean up is needed
//
// fsnotify_vfsmount_delete - a vfsmount is being destroyed, clean up is needed
//
// fsnotify_inoderemove - an inode is going away
//
// fsnotify_create - 'name' was linked in
//
// Caller must make sure that dentry->d_name is stable.
// Note: some filesystems (e.g. kernfs) leave @dentry negative and instantiate
// ->d_inode later
//
// fsnotify_link - new hardlink in 'inode' directory
//
// Caller must make sure that new_dentry->d_name is stable.
// Note: We have to pass also the linked inode ptr as some filesystems leave
// new_dentry->d_inode NULL and instantiate inode pointer later
//
// fsnotify_delete - @dentry was unlinked and unhashed
//
// Caller must make sure that dentry->d_name is stable.
//
// Note: unlike fsnotify_unlink(), we have to pass also the unlinked inode
// as this may be called after d_delete() and old_dentry may be negative.
//
// d_delete_notify - delete a dentry and call fsnotify_delete()
// @dentry: The dentry to delete
//
// This helper is used to guaranty that the unlinked inode cannot be found
// by lookup of this name after fsnotify_delete() event has been delivered.
//
// fsnotify_unlink - 'name' was unlinked
//
// Caller must make sure that dentry->d_name is stable.
//
// fsnotify_mkdir - directory 'name' was created
//
// Caller must make sure that dentry->d_name is stable.
// Note: some filesystems (e.g. kernfs) leave @dentry negative and instantiate
// ->d_inode later
//
// fsnotify_rmdir - directory 'name' was removed
//
// Caller must make sure that dentry->d_name is stable.
//
// fsnotify_access - file was read
//
// fsnotify_modify - file was modified
//
// fsnotify_open - file was opened
//
// fsnotify_close - file was closed
//
// fsnotify_xattr - extended attributes were changed
//
// fsnotify_change - notify_change event.  file was modified and/or metadata
// was changed.
//
// both times implies a utime(s) call
