//! Automatically rewritten from C Header to Rust Module
//! Source: block/blk.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0

//
// Default upper limit for the software max_sectors limit used for regular I/Os.
// This can be increased through sysfs.
//
// This should not be confused with the max_hw_sector limit that is entirely
// controlled by the block device driver, usually based on hardware limits.
//

pub const BLK_MIN_SEGMENT_SIZE: c_int = 4096;
// Max future timer expiry for timeouts

#[repr(C)]
#[derive(Copy, Clone)]
pub struct blk_flush_queue {
    pub mq_flush_lock: spinlock_t,
    pub flush_pending_idx:1: c_uint,
    pub flush_running_idx:1: c_uint,
    pub rq_status: blk_status_t,
    pub flush_pending_since: c_ulong,
    pub flush_queue: [list_head; 2],
    pub flush_data_in_flight: c_ulong,
    pub flush_rq: *mut request,
    pub rcu_head: rcu_head,
}

extern "C" {
    pub fn is_flush_rq(req: *mut request) -> bool;
}
extern "C" {
    pub fn blk_free_flush_queue(q: *mut blk_flush_queue);
}
extern "C" {
    pub fn tag_to_blk_status(tag: *const c_char) -> blk_status_t;
}
extern "C" {
    pub fn str_to_blk_op(op: *const c_char) -> req_op;
}
extern "C" {
    pub fn __blk_mq_unfreeze_queue(q: *mut request_queue, force_atomic: bool) -> bool;
}
extern "C" {
    pub fn blk_queue_start_drain(q: *mut request_queue) -> bool;
}
extern "C" {
    pub fn __bio_queue_enter(q: *mut request_queue, bio: *mut bio) -> c_int;
}
extern "C" {
    pub fn submit_bio_noacct_nocheck(bio: *mut bio, split: bool);
}
extern "C" {
    pub fn bio_submit_or_kill(bio: *mut bio, flags: c_uint) -> c_int;
}
//
// The code that increments the pm_only counter must ensure that the
// counter is globally visible before the queue is unfrozen.
//
extern "C" {
    pub fn __bio_queue_enter(_arg: q, _arg: bio) -> return;
}
// Prevent hang_check timer from firing at us during very long I/O
extern "C" {
    pub fn blkdev_put_no_open(bdev: *mut block_device);
}
//
// Merging adjacent physical pages may not work correctly under KMSAN
// if their metadata pages aren't adjacent. Just disable merging.
//
// Check if two pages from potentially different zone device pgmaps can
// coexist as separate bvec entries in the same bio.
//
// The block DMA iterator (blk_dma_map_iter_start) caches the P2PDMA mapping
// state from the first segment and applies it to all subsequent segments, so
// P2PDMA pages from different pgmaps must not be mixed in the same bio.
//
// Other zone device types (FS_DAX, GENERIC) use the same dma_map_phys() path
// as normal RAM.  PRIVATE and COHERENT pages never appear in bios.
//
extern "C" {
    pub fn zone_device_pages_have_same_pgmap(_arg: a, _arg: b) -> return;
}
//
// Check if adding a bio_vec after bprv with offset would create a gap in
// the SG list. Most drivers don't care about this, but some do.
//
extern "C" {
    pub fn __bvec_gap_to_prev(_arg: lim, _arg: bprv, _arg: offset) -> return;
}
//
// There are two different ways to handle DISCARD merges:
// 1) If max_discard_segments > 1, the driver treats every bio as a range and
// send the bios to controller together. The ranges don't need to be
// contiguous.
// 2) Otherwise, the request will be normal read/write requests.  The ranges
// need to be contiguous.
//
extern "C" {
    pub fn queue_max_discard_segments(_arg: rq->q) -> return;
}
extern "C" {
    pub fn queue_max_segments(_arg: rq->q) -> return;
}

extern "C" {
    pub fn blk_flush_integrity();
}
extern "C" {
    pub fn bio_integrity_free(bio: *mut bio);
}
//
// Integrity payloads can either be owned by the submitter, in which case
// bio_uninit will free them, or owned and generated by the block layer,
// in which case we'll verify them here (for reads) and free them before
// the bio is handed back to the submitted.
//
extern "C" {
    pub fn __bio_integrity_endio(bio: *mut bio) -> bool;
}
extern "C" {
    pub fn __bio_integrity_endio(_arg: bio) -> return;
}

extern "C" {
    pub fn blk_rq_timeout(timeout: c_ulong) -> c_ulong;
}
extern "C" {
    pub fn blk_add_timer(req: *mut request);
}
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum bio_merge_status {
    BIO_MERGE_OK,
    BIO_MERGE_NONE,
    BIO_MERGE_FAILED,
}

//
// Plug flush limits
//
pub const BLK_MAX_REQUEST_COUNT: c_int = 32;

//
// Internal elevator interface
//

extern "C" {
    pub fn blk_insert_flush(rq: *mut request) -> bool;
}
extern "C" {
    pub fn elevator_set_default(q: *mut request_queue);
}
extern "C" {
    pub fn elevator_set_none(q: *mut request_queue);
}
extern "C" {
    pub fn part_timeout_show(: *mut device, : *mut device_attribute, : *mut c_char) -> isize;
}
//
// All drivers must accept single-segments bios that are smaller than PAGE_SIZE.
//
// This is a quick and dirty check that relies on the fact that bi_io_vec[0] is
// always valid if a bio has data.  The check might lead to occasional false
// positives when bios are cloned, but compared to the performance impact of
// cloned bios themselves the loop below doesn't matter anyway.
//
// __bio_split_to_limits - split a bio to fit the queue limits
// @bio:     bio to be split
// @lim:     queue limits to split based on
// @nr_segs: returns the number of segments in the returned bio
//
// Check if @bio needs splitting based on the queue limits, and if so split off
// a bio fitting the limits from the beginning of @bio and return it.  @bio is
// shortened to the remainder and re-submitted.
//
// The split bio is allocated from @q->bio_split, which is provided by the
// block layer.
//
extern "C" {
    pub fn bio_split_rw(_arg: bio, _arg: lim, _arg: nr_segs) -> return;
}
// nr_segs = 1;
extern "C" {
    pub fn bio_split_zone_append(_arg: bio, _arg: lim, _arg: nr_segs) -> return;
}
extern "C" {
    pub fn bio_split_discard(_arg: bio, _arg: lim, _arg: nr_segs) -> return;
}
extern "C" {
    pub fn bio_split_write_zeroes(_arg: bio, _arg: lim, _arg: nr_segs) -> return;
}
// other operations can't be split
// nr_segs = 0;
//
// get_max_segment_size() - maximum number of bytes to add as a single segment
// @lim: Request queue limits.
// @paddr: address of the range to add
// @len: maximum length available to add at @paddr
//
// Returns the maximum number of bytes of the range starting at @paddr that can
// be added to a single segment.
//
// Prevent an overflow if mask = ULONG_MAX and offset = 0 by adding 1
// after having calculated the minimum.
//
extern "C" {
    pub fn blk_recalc_rq_segments(rq: *mut request) -> c_uint;
}
extern "C" {
    pub fn blk_rq_merge_ok(rq: *mut request, bio: *mut bio) -> bool;
}
extern "C" {
    pub fn blk_try_merge(rq: *mut request, bio: *mut bio) -> elv_merge;
}
extern "C" {
    pub fn blk_set_default_limits(lim: *mut queue_limits) -> c_int;
}
extern "C" {
    pub fn blk_dev_init() -> c_int;
}
extern "C" {
    pub fn update_io_ticks(part: *mut block_device, now: c_ulong, end: bool);
}
//
// Internal io_context interface
//

extern "C" {
    pub fn ioc_clear_queue(q: *mut request_queue);
}

extern "C" {
    pub fn disk_init_zone_resources(disk: *mut gendisk);
}
extern "C" {
    pub fn disk_release_zone_resources(disk: *mut gendisk);
}
extern "C" {
    pub fn bio_flagged(_arg: bio, _arg: BIO_ZONE_WRITE_PLUGGING) -> return;
}
extern "C" {
    pub fn blk_zone_write_plug_bio_merged(bio: *mut bio);
}
extern "C" {
    pub fn blk_zone_write_plug_init_request(rq: *mut request);
}
extern "C" {
    pub fn blk_zone_append_update_request_bio(rq: *mut request, bio: *mut bio);
}
extern "C" {
    pub fn blk_zone_mgmt_bio_endio(bio: *mut bio);
}
extern "C" {
    pub fn blk_zone_write_plug_bio_endio(bio: *mut bio);
}
//
// Zone management BIOs may impact zone write plugs (e.g. a zone reset
// changes a zone write plug zone write pointer offset), but these
// operation do not go through zone write plugging as they may operate
// on zones that do not have a zone write
// plug. blk_zone_mgmt_bio_endio() handles the potential changes to zone
// write plugs that are present.
//
// For write BIOs to zoned devices, signal the completion of the BIO so
// that the next write BIO can be submitted by zone write plugging.
//
extern "C" {
    pub fn blk_zone_write_plug_finish_request(rq: *mut request);
}

extern "C" {
    pub fn bdev_add(bdev: *mut block_device, dev: dev_t);
}
extern "C" {
    pub fn bdev_unhash(bdev: *mut block_device);
}
extern "C" {
    pub fn bdev_drop(bdev: *mut block_device);
}
extern "C" {
    pub fn blk_alloc_ext_minor() -> c_int;
}
extern "C" {
    pub fn blk_free_ext_minor(minor: c_uint);
}
pub const ADDPART_FLAG_NONE: c_int = 0;
pub const ADDPART_FLAG_RAID: c_int = 1;
pub const ADDPART_FLAG_WHOLEDISK: c_int = 2;
pub const ADDPART_FLAG_READONLY: c_int = 4;
extern "C" {
    pub fn bdev_del_partition(disk: *mut gendisk, partno: c_int) -> c_int;
}
extern "C" {
    pub fn drop_partition(part: *mut block_device);
}
extern "C" {
    pub fn bdev_set_nr_sectors(bdev: *mut block_device, sectors: sector_t);
}
extern "C" {
    pub fn disk_scan_partitions(disk: *mut gendisk, mode: blk_mode_t) -> c_int;
}
extern "C" {
    pub fn disk_alloc_events(disk: *mut gendisk) -> c_int;
}
extern "C" {
    pub fn disk_add_events(disk: *mut gendisk);
}
extern "C" {
    pub fn disk_del_events(disk: *mut gendisk);
}
extern "C" {
    pub fn disk_release_events(disk: *mut gendisk);
}
extern "C" {
    pub fn disk_block_events(disk: *mut gendisk);
}
extern "C" {
    pub fn disk_unblock_events(disk: *mut gendisk);
}
extern "C" {
    pub fn disk_flush_events(disk: *mut gendisk, mask: c_uint);
}
extern "C" {
    pub fn file_to_blk_mode(file: *mut file) -> blk_mode_t;
}
extern "C" {
    pub fn blkdev_ioctl(file: *mut file, cmd: unsigned, arg: c_ulong) -> c_long;
}
extern "C" {
    pub fn blkdev_uring_cmd(cmd: *mut io_uring_cmd, issue_flags: c_uint) -> c_int;
}
extern "C" {
    pub fn compat_blkdev_ioctl(file: *mut file, cmd: unsigned, arg: c_ulong) -> c_long;
}
extern "C" {
    pub fn disk_register_independent_access_ranges(disk: *mut gendisk) -> c_int;
}
extern "C" {
    pub fn disk_unregister_independent_access_ranges(disk: *mut gendisk);
}
extern "C" {
    pub fn should_fail_bio(bio: *mut bio) -> c_int;
}

extern "C" {
    pub fn should_fail_request(part: *mut block_device, bytes: c_uint) -> bool;
}

//
// Optimized request reference counting. Ideally we'd make timeouts be more
// clever, as that's the only reason we need references at all... But until
// this happens, this is faster than using refcount_t. Also see:
//
// abc54d634334 ("io_uring: switch to atomic_t for io_kiocb reference count")
//

extern "C" {
    pub fn atomic_inc_not_zero(_arg: &req->ref) -> return;
}
extern "C" {
    pub fn atomic_dec_and_test(_arg: &req->ref) -> return;
}
extern "C" {
    pub fn atomic_read(_arg: &req->ref) -> return;
}
extern "C" {
    pub fn ktime_get_ns() -> return;
}
//
// 0 could very well be a valid time, but rather than flag "this is
// a valid timestamp" separately, just accept that we'll do an extra
// ktime_get_ns() if we just happen to get 0 as the current time.
//
// cur_ktime can be zeroed by pre-emption the moment PF_BLOCK_TS is set.
//
// Ensure PF_BLOCK_TS is set after cur_ktime.
extern "C" {
    pub fn ns_to_ktime(_arg: blk_time_get_ns()) -> return;
}
extern "C" {
    pub fn bdev_release(bdev_file: *mut file);
}
extern "C" {
    pub fn bdev_permission(dev: dev_t, mode: blk_mode_t, holder: *mut c_void) -> c_int;
}
extern "C" {
    pub fn bio_integrity_generate(bio: *mut bio);
}
extern "C" {
    pub fn blk_integrity_prepare(rq: *mut request);
}
extern "C" {
    pub fn blk_integrity_complete(rq: *mut request, nr_bytes: c_uint);
}

//
// debugfs directory and file creation can trigger fs reclaim, which can enter
// back into the block layer request_queue. This can cause deadlock if the
// queue is frozen. Use NOIO context together with debugfs_mutex to prevent fs
// reclaim from triggering block I/O.
//
