//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/amd/include/asic_reg/oss/osssys_6_0_0_sh_mask.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// Copyright 2021 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

// Macro flag: #define _osssys_6_0_0_SH_MASK_HEADER
// addressBlock: osssys_osssysdec
// IH_VMID_0_LUT
pub const IH_VMID_0_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_0_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_1_LUT
pub const IH_VMID_1_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_1_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_2_LUT
pub const IH_VMID_2_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_2_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_3_LUT
pub const IH_VMID_3_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_3_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_4_LUT
pub const IH_VMID_4_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_4_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_5_LUT
pub const IH_VMID_5_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_5_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_6_LUT
pub const IH_VMID_6_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_6_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_7_LUT
pub const IH_VMID_7_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_7_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_8_LUT
pub const IH_VMID_8_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_8_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_9_LUT
pub const IH_VMID_9_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_9_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_10_LUT
pub const IH_VMID_10_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_10_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_11_LUT
pub const IH_VMID_11_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_11_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_12_LUT
pub const IH_VMID_12_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_12_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_13_LUT
pub const IH_VMID_13_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_13_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_14_LUT
pub const IH_VMID_14_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_14_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_15_LUT
pub const IH_VMID_15_LUT__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_15_LUT__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_0_LUT_MM
pub const IH_VMID_0_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_0_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_1_LUT_MM
pub const IH_VMID_1_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_1_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_2_LUT_MM
pub const IH_VMID_2_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_2_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_3_LUT_MM
pub const IH_VMID_3_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_3_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_4_LUT_MM
pub const IH_VMID_4_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_4_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_5_LUT_MM
pub const IH_VMID_5_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_5_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_6_LUT_MM
pub const IH_VMID_6_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_6_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_7_LUT_MM
pub const IH_VMID_7_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_7_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_8_LUT_MM
pub const IH_VMID_8_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_8_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_9_LUT_MM
pub const IH_VMID_9_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_9_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_10_LUT_MM
pub const IH_VMID_10_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_10_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_11_LUT_MM
pub const IH_VMID_11_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_11_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_12_LUT_MM
pub const IH_VMID_12_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_12_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_13_LUT_MM
pub const IH_VMID_13_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_13_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_14_LUT_MM
pub const IH_VMID_14_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_14_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_VMID_15_LUT_MM
pub const IH_VMID_15_LUT_MM__PASID__SHIFT: c_uint = 0x0;
pub const IH_VMID_15_LUT_MM__PASID_MASK: c_uint = 0x0000FFFFL;
// IH_COOKIE_0
pub const IH_COOKIE_0__CLIENT_ID__SHIFT: c_uint = 0x0;
pub const IH_COOKIE_0__SOURCE_ID__SHIFT: c_uint = 0x8;
pub const IH_COOKIE_0__RING_ID__SHIFT: c_uint = 0x10;
pub const IH_COOKIE_0__VM_ID__SHIFT: c_uint = 0x18;
pub const IH_COOKIE_0__RESERVED__SHIFT: c_uint = 0x1c;
pub const IH_COOKIE_0__VMID_TYPE__SHIFT: c_uint = 0x1f;
pub const IH_COOKIE_0__CLIENT_ID_MASK: c_uint = 0x000000FFL;
pub const IH_COOKIE_0__SOURCE_ID_MASK: c_uint = 0x0000FF00L;
pub const IH_COOKIE_0__RING_ID_MASK: c_uint = 0x00FF0000L;
pub const IH_COOKIE_0__VM_ID_MASK: c_uint = 0x0F000000L;
pub const IH_COOKIE_0__RESERVED_MASK: c_uint = 0x70000000L;
pub const IH_COOKIE_0__VMID_TYPE_MASK: c_uint = 0x80000000L;
// IH_COOKIE_1
pub const IH_COOKIE_1__TIMESTAMP_31_0__SHIFT: c_uint = 0x0;
pub const IH_COOKIE_1__TIMESTAMP_31_0_MASK: c_uint = 0xFFFFFFFFL;
// IH_COOKIE_2
pub const IH_COOKIE_2__TIMESTAMP_47_32__SHIFT: c_uint = 0x0;
pub const IH_COOKIE_2__RESERVED__SHIFT: c_uint = 0x10;
pub const IH_COOKIE_2__TIMESTAMP_SRC__SHIFT: c_uint = 0x1f;
pub const IH_COOKIE_2__TIMESTAMP_47_32_MASK: c_uint = 0x0000FFFFL;
pub const IH_COOKIE_2__RESERVED_MASK: c_uint = 0x7FFF0000L;
pub const IH_COOKIE_2__TIMESTAMP_SRC_MASK: c_uint = 0x80000000L;
// IH_COOKIE_3
pub const IH_COOKIE_3__PAS_ID__SHIFT: c_uint = 0x0;
pub const IH_COOKIE_3__RESERVED__SHIFT: c_uint = 0x10;
pub const IH_COOKIE_3__PASID_SRC__SHIFT: c_uint = 0x1f;
pub const IH_COOKIE_3__PAS_ID_MASK: c_uint = 0x0000FFFFL;
pub const IH_COOKIE_3__RESERVED_MASK: c_uint = 0x7FFF0000L;
pub const IH_COOKIE_3__PASID_SRC_MASK: c_uint = 0x80000000L;
// IH_COOKIE_4
pub const IH_COOKIE_4__CONTEXT_ID_31_0__SHIFT: c_uint = 0x0;
pub const IH_COOKIE_4__CONTEXT_ID_31_0_MASK: c_uint = 0xFFFFFFFFL;
// IH_COOKIE_5
pub const IH_COOKIE_5__CONTEXT_ID_63_32__SHIFT: c_uint = 0x0;
pub const IH_COOKIE_5__CONTEXT_ID_63_32_MASK: c_uint = 0xFFFFFFFFL;
// IH_COOKIE_6
pub const IH_COOKIE_6__CONTEXT_ID_95_64__SHIFT: c_uint = 0x0;
pub const IH_COOKIE_6__CONTEXT_ID_95_64_MASK: c_uint = 0xFFFFFFFFL;
// IH_COOKIE_7
pub const IH_COOKIE_7__CONTEXT_ID_128_96__SHIFT: c_uint = 0x0;
pub const IH_COOKIE_7__CONTEXT_ID_128_96_MASK: c_uint = 0xFFFFFFFFL;
// IH_REGISTER_LAST_PART0
pub const IH_REGISTER_LAST_PART0__RESERVED__SHIFT: c_uint = 0x0;
pub const IH_REGISTER_LAST_PART0__RESERVED_MASK: c_uint = 0xFFFFFFFFL;
// IH_RB_CNTL
pub const IH_RB_CNTL__RB_ENABLE__SHIFT: c_uint = 0x0;
pub const IH_RB_CNTL__RB_SIZE__SHIFT: c_uint = 0x1;
pub const IH_RB_CNTL__WPTR_WRITEBACK_ENABLE__SHIFT: c_uint = 0x8;
pub const IH_RB_CNTL__RB_FULL_DRAIN_ENABLE__SHIFT: c_uint = 0x9;
pub const IH_RB_CNTL__FULL_DRAIN_CLEAR__SHIFT: c_uint = 0xa;
pub const IH_RB_CNTL__PAGE_RB_CLEAR__SHIFT: c_uint = 0xb;
pub const IH_RB_CNTL__RB_USED_INT_THRESHOLD__SHIFT: c_uint = 0xc;
pub const IH_RB_CNTL__WPTR_OVERFLOW_ENABLE__SHIFT: c_uint = 0x10;
pub const IH_RB_CNTL__ENABLE_INTR__SHIFT: c_uint = 0x11;
pub const IH_RB_CNTL__MC_SWAP__SHIFT: c_uint = 0x12;
pub const IH_RB_CNTL__MC_SNOOP__SHIFT: c_uint = 0x14;
pub const IH_RB_CNTL__RPTR_REARM__SHIFT: c_uint = 0x15;
pub const IH_RB_CNTL__MC_RO__SHIFT: c_uint = 0x16;
pub const IH_RB_CNTL__MC_VMID__SHIFT: c_uint = 0x18;
pub const IH_RB_CNTL__MC_SPACE__SHIFT: c_uint = 0x1c;
pub const IH_RB_CNTL__WPTR_OVERFLOW_CLEAR__SHIFT: c_uint = 0x1f;
pub const IH_RB_CNTL__RB_ENABLE_MASK: c_uint = 0x00000001L;
pub const IH_RB_CNTL__RB_SIZE_MASK: c_uint = 0x0000003EL;
pub const IH_RB_CNTL__WPTR_WRITEBACK_ENABLE_MASK: c_uint = 0x00000100L;
pub const IH_RB_CNTL__RB_FULL_DRAIN_ENABLE_MASK: c_uint = 0x00000200L;
pub const IH_RB_CNTL__FULL_DRAIN_CLEAR_MASK: c_uint = 0x00000400L;
pub const IH_RB_CNTL__PAGE_RB_CLEAR_MASK: c_uint = 0x00000800L;
pub const IH_RB_CNTL__RB_USED_INT_THRESHOLD_MASK: c_uint = 0x0000F000L;
pub const IH_RB_CNTL__WPTR_OVERFLOW_ENABLE_MASK: c_uint = 0x00010000L;
pub const IH_RB_CNTL__ENABLE_INTR_MASK: c_uint = 0x00020000L;
pub const IH_RB_CNTL__MC_SWAP_MASK: c_uint = 0x000C0000L;
pub const IH_RB_CNTL__MC_SNOOP_MASK: c_uint = 0x00100000L;
pub const IH_RB_CNTL__RPTR_REARM_MASK: c_uint = 0x00200000L;
pub const IH_RB_CNTL__MC_RO_MASK: c_uint = 0x00400000L;
pub const IH_RB_CNTL__MC_VMID_MASK: c_uint = 0x0F000000L;
pub const IH_RB_CNTL__MC_SPACE_MASK: c_uint = 0x70000000L;
pub const IH_RB_CNTL__WPTR_OVERFLOW_CLEAR_MASK: c_uint = 0x80000000L;
// IH_RB_BASE
pub const IH_RB_BASE__ADDR__SHIFT: c_uint = 0x0;
pub const IH_RB_BASE__ADDR_MASK: c_uint = 0xFFFFFFFFL;
// IH_RB_BASE_HI
pub const IH_RB_BASE_HI__ADDR__SHIFT: c_uint = 0x0;
pub const IH_RB_BASE_HI__ADDR_MASK: c_uint = 0x000000FFL;
// IH_RB_RPTR
pub const IH_RB_RPTR__OFFSET__SHIFT: c_uint = 0x2;
pub const IH_RB_RPTR__OFFSET_MASK: c_uint = 0x0003FFFCL;
// IH_RB_WPTR
pub const IH_RB_WPTR__RB_OVERFLOW__SHIFT: c_uint = 0x0;
pub const IH_RB_WPTR__OFFSET__SHIFT: c_uint = 0x2;
pub const IH_RB_WPTR__RB_LEFT_NONE__SHIFT: c_uint = 0x12;
pub const IH_RB_WPTR__RB_MAY_OVERFLOW__SHIFT: c_uint = 0x13;
pub const IH_RB_WPTR__RB_OVERFLOW_MASK: c_uint = 0x00000001L;
pub const IH_RB_WPTR__OFFSET_MASK: c_uint = 0x0003FFFCL;
pub const IH_RB_WPTR__RB_LEFT_NONE_MASK: c_uint = 0x00040000L;
pub const IH_RB_WPTR__RB_MAY_OVERFLOW_MASK: c_uint = 0x00080000L;
// IH_RB_WPTR_ADDR_HI
pub const IH_RB_WPTR_ADDR_HI__ADDR__SHIFT: c_uint = 0x0;
pub const IH_RB_WPTR_ADDR_HI__ADDR_MASK: c_uint = 0x0000FFFFL;
// IH_RB_WPTR_ADDR_LO
pub const IH_RB_WPTR_ADDR_LO__ADDR__SHIFT: c_uint = 0x2;
pub const IH_RB_WPTR_ADDR_LO__ADDR_MASK: c_uint = 0xFFFFFFFCL;
// IH_DOORBELL_RPTR
pub const IH_DOORBELL_RPTR__OFFSET__SHIFT: c_uint = 0x0;
pub const IH_DOORBELL_RPTR__ENABLE__SHIFT: c_uint = 0x1c;
pub const IH_DOORBELL_RPTR__OFFSET_MASK: c_uint = 0x03FFFFFFL;
pub const IH_DOORBELL_RPTR__ENABLE_MASK: c_uint = 0x10000000L;
// IH_DOORBELL_RETRY_CAM
pub const IH_DOORBELL_RETRY_CAM__OFFSET__SHIFT: c_uint = 0x0;
pub const IH_DOORBELL_RETRY_CAM__ENABLE__SHIFT: c_uint = 0x1c;
pub const IH_DOORBELL_RETRY_CAM__OFFSET_MASK: c_uint = 0x03FFFFFFL;
pub const IH_DOORBELL_RETRY_CAM__ENABLE_MASK: c_uint = 0x10000000L;
// IH_RB_CNTL_RING1
pub const IH_RB_CNTL_RING1__RB_ENABLE__SHIFT: c_uint = 0x0;
pub const IH_RB_CNTL_RING1__RB_SIZE__SHIFT: c_uint = 0x1;
pub const IH_RB_CNTL_RING1__RB_FULL_DRAIN_ENABLE__SHIFT: c_uint = 0x9;
pub const IH_RB_CNTL_RING1__FULL_DRAIN_CLEAR__SHIFT: c_uint = 0xa;
pub const IH_RB_CNTL_RING1__PAGE_RB_CLEAR__SHIFT: c_uint = 0xb;
pub const IH_RB_CNTL_RING1__RB_USED_INT_THRESHOLD__SHIFT: c_uint = 0xc;
pub const IH_RB_CNTL_RING1__WPTR_OVERFLOW_ENABLE__SHIFT: c_uint = 0x10;
pub const IH_RB_CNTL_RING1__MC_SWAP__SHIFT: c_uint = 0x12;
pub const IH_RB_CNTL_RING1__MC_SNOOP__SHIFT: c_uint = 0x14;
pub const IH_RB_CNTL_RING1__MC_RO__SHIFT: c_uint = 0x16;
pub const IH_RB_CNTL_RING1__MC_VMID__SHIFT: c_uint = 0x18;
pub const IH_RB_CNTL_RING1__MC_SPACE__SHIFT: c_uint = 0x1c;
pub const IH_RB_CNTL_RING1__WPTR_OVERFLOW_CLEAR__SHIFT: c_uint = 0x1f;
pub const IH_RB_CNTL_RING1__RB_ENABLE_MASK: c_uint = 0x00000001L;
pub const IH_RB_CNTL_RING1__RB_SIZE_MASK: c_uint = 0x0000003EL;
pub const IH_RB_CNTL_RING1__RB_FULL_DRAIN_ENABLE_MASK: c_uint = 0x00000200L;
pub const IH_RB_CNTL_RING1__FULL_DRAIN_CLEAR_MASK: c_uint = 0x00000400L;
pub const IH_RB_CNTL_RING1__PAGE_RB_CLEAR_MASK: c_uint = 0x00000800L;
pub const IH_RB_CNTL_RING1__RB_USED_INT_THRESHOLD_MASK: c_uint = 0x0000F000L;
pub const IH_RB_CNTL_RING1__WPTR_OVERFLOW_ENABLE_MASK: c_uint = 0x00010000L;
pub const IH_RB_CNTL_RING1__MC_SWAP_MASK: c_uint = 0x000C0000L;
pub const IH_RB_CNTL_RING1__MC_SNOOP_MASK: c_uint = 0x00100000L;
pub const IH_RB_CNTL_RING1__MC_RO_MASK: c_uint = 0x00400000L;
pub const IH_RB_CNTL_RING1__MC_VMID_MASK: c_uint = 0x0F000000L;
pub const IH_RB_CNTL_RING1__MC_SPACE_MASK: c_uint = 0x70000000L;
pub const IH_RB_CNTL_RING1__WPTR_OVERFLOW_CLEAR_MASK: c_uint = 0x80000000L;
// IH_RB_BASE_RING1
pub const IH_RB_BASE_RING1__ADDR__SHIFT: c_uint = 0x0;
pub const IH_RB_BASE_RING1__ADDR_MASK: c_uint = 0xFFFFFFFFL;
// IH_RB_BASE_HI_RING1
pub const IH_RB_BASE_HI_RING1__ADDR__SHIFT: c_uint = 0x0;
pub const IH_RB_BASE_HI_RING1__ADDR_MASK: c_uint = 0x000000FFL;
// IH_RB_RPTR_RING1
pub const IH_RB_RPTR_RING1__OFFSET__SHIFT: c_uint = 0x2;
pub const IH_RB_RPTR_RING1__OFFSET_MASK: c_uint = 0x0003FFFCL;
// IH_RB_WPTR_RING1
pub const IH_RB_WPTR_RING1__RB_OVERFLOW__SHIFT: c_uint = 0x0;
pub const IH_RB_WPTR_RING1__OFFSET__SHIFT: c_uint = 0x2;
pub const IH_RB_WPTR_RING1__RB_LEFT_NONE__SHIFT: c_uint = 0x12;
pub const IH_RB_WPTR_RING1__RB_MAY_OVERFLOW__SHIFT: c_uint = 0x13;
pub const IH_RB_WPTR_RING1__RB_OVERFLOW_MASK: c_uint = 0x00000001L;
pub const IH_RB_WPTR_RING1__OFFSET_MASK: c_uint = 0x0003FFFCL;
pub const IH_RB_WPTR_RING1__RB_LEFT_NONE_MASK: c_uint = 0x00040000L;
pub const IH_RB_WPTR_RING1__RB_MAY_OVERFLOW_MASK: c_uint = 0x00080000L;
// IH_DOORBELL_RPTR_RING1
pub const IH_DOORBELL_RPTR_RING1__OFFSET__SHIFT: c_uint = 0x0;
pub const IH_DOORBELL_RPTR_RING1__ENABLE__SHIFT: c_uint = 0x1c;
pub const IH_DOORBELL_RPTR_RING1__OFFSET_MASK: c_uint = 0x03FFFFFFL;
pub const IH_DOORBELL_RPTR_RING1__ENABLE_MASK: c_uint = 0x10000000L;
// IH_RETRY_CAM_ACK
pub const IH_RETRY_CAM_ACK__INDEX__SHIFT: c_uint = 0x0;
pub const IH_RETRY_CAM_ACK__INDEX_MASK: c_uint = 0x000003FFL;
// IH_VERSION
pub const IH_VERSION__MINVER__SHIFT: c_uint = 0x0;
pub const IH_VERSION__MAJVER__SHIFT: c_uint = 0x8;
pub const IH_VERSION__REV__SHIFT: c_uint = 0x10;
pub const IH_VERSION__MINVER_MASK: c_uint = 0x0000007FL;
pub const IH_VERSION__MAJVER_MASK: c_uint = 0x00007F00L;
pub const IH_VERSION__REV_MASK: c_uint = 0x003F0000L;
// IH_CNTL
pub const IH_CNTL__WPTR_WRITEBACK_TIMER__SHIFT: c_uint = 0x0;
pub const IH_CNTL__IH_IDLE_HYSTERESIS_CNTL__SHIFT: c_uint = 0x6;
pub const IH_CNTL__IH_FIFO_HIGHWATER__SHIFT: c_uint = 0x8;
pub const IH_CNTL__MC_WR_CLEAN_CNT__SHIFT: c_uint = 0x14;
pub const IH_CNTL__WPTR_WRITEBACK_TIMER_MASK: c_uint = 0x0000001FL;
pub const IH_CNTL__IH_IDLE_HYSTERESIS_CNTL_MASK: c_uint = 0x000000C0L;
pub const IH_CNTL__IH_FIFO_HIGHWATER_MASK: c_uint = 0x00007F00L;
pub const IH_CNTL__MC_WR_CLEAN_CNT_MASK: c_uint = 0x01F00000L;
// IH_CNTL2
pub const IH_CNTL2__SELF_IV_FORCE_WPTR_UPDATE_TIMEOUT__SHIFT: c_uint = 0x0;
pub const IH_CNTL2__SELF_IV_FORCE_WPTR_UPDATE_ENABLE__SHIFT: c_uint = 0x8;
pub const IH_CNTL2__SELF_IV_FORCE_WPTR_UPDATE_TIMEOUT_MASK: c_uint = 0x0000001FL;
pub const IH_CNTL2__SELF_IV_FORCE_WPTR_UPDATE_ENABLE_MASK: c_uint = 0x00000100L;
// IH_STATUS
pub const IH_STATUS__IDLE__SHIFT: c_uint = 0x0;
pub const IH_STATUS__INPUT_IDLE__SHIFT: c_uint = 0x1;
pub const IH_STATUS__BUFFER_IDLE__SHIFT: c_uint = 0x2;
pub const IH_STATUS__RB_FULL__SHIFT: c_uint = 0x3;
pub const IH_STATUS__RB_FULL_DRAIN__SHIFT: c_uint = 0x4;
pub const IH_STATUS__RB_OVERFLOW__SHIFT: c_uint = 0x5;
pub const IH_STATUS__MC_WR_IDLE__SHIFT: c_uint = 0x6;
pub const IH_STATUS__MC_WR_STALL__SHIFT: c_uint = 0x7;
pub const IH_STATUS__MC_WR_CLEAN_PENDING__SHIFT: c_uint = 0x8;
pub const IH_STATUS__MC_WR_CLEAN_STALL__SHIFT: c_uint = 0x9;
pub const IH_STATUS__BIF_INTERRUPT_LINE__SHIFT: c_uint = 0xa;
pub const IH_STATUS__SWITCH_READY__SHIFT: c_uint = 0xb;
pub const IH_STATUS__RB1_FULL__SHIFT: c_uint = 0xc;
pub const IH_STATUS__RB1_FULL_DRAIN__SHIFT: c_uint = 0xd;
pub const IH_STATUS__RB1_OVERFLOW__SHIFT: c_uint = 0xe;
pub const IH_STATUS__SELF_INT_GEN_IDLE__SHIFT: c_uint = 0x12;
pub const IH_STATUS__RETRY_INT_CAM_IDLE__SHIFT: c_uint = 0x13;
pub const IH_STATUS__ZSTATES_FENCE__SHIFT: c_uint = 0x14;
pub const IH_STATUS__IH_BUFFER_MEM_POWER_GATED__SHIFT: c_uint = 0x15;
pub const IH_STATUS__IH_RETRY_INT_CAM_MEM_POWER_GATED__SHIFT: c_uint = 0x16;
pub const IH_STATUS__IH_PASID_LUT_MEM_POWER_GATED__SHIFT: c_uint = 0x17;
pub const IH_STATUS__IDLE_MASK: c_uint = 0x00000001L;
pub const IH_STATUS__INPUT_IDLE_MASK: c_uint = 0x00000002L;
pub const IH_STATUS__BUFFER_IDLE_MASK: c_uint = 0x00000004L;
pub const IH_STATUS__RB_FULL_MASK: c_uint = 0x00000008L;
pub const IH_STATUS__RB_FULL_DRAIN_MASK: c_uint = 0x00000010L;
pub const IH_STATUS__RB_OVERFLOW_MASK: c_uint = 0x00000020L;
pub const IH_STATUS__MC_WR_IDLE_MASK: c_uint = 0x00000040L;
pub const IH_STATUS__MC_WR_STALL_MASK: c_uint = 0x00000080L;
pub const IH_STATUS__MC_WR_CLEAN_PENDING_MASK: c_uint = 0x00000100L;
pub const IH_STATUS__MC_WR_CLEAN_STALL_MASK: c_uint = 0x00000200L;
pub const IH_STATUS__BIF_INTERRUPT_LINE_MASK: c_uint = 0x00000400L;
pub const IH_STATUS__SWITCH_READY_MASK: c_uint = 0x00000800L;
pub const IH_STATUS__RB1_FULL_MASK: c_uint = 0x00001000L;
pub const IH_STATUS__RB1_FULL_DRAIN_MASK: c_uint = 0x00002000L;
pub const IH_STATUS__RB1_OVERFLOW_MASK: c_uint = 0x00004000L;
pub const IH_STATUS__SELF_INT_GEN_IDLE_MASK: c_uint = 0x00040000L;
pub const IH_STATUS__RETRY_INT_CAM_IDLE_MASK: c_uint = 0x00080000L;
pub const IH_STATUS__ZSTATES_FENCE_MASK: c_uint = 0x00100000L;
pub const IH_STATUS__IH_BUFFER_MEM_POWER_GATED_MASK: c_uint = 0x00200000L;
pub const IH_STATUS__IH_RETRY_INT_CAM_MEM_POWER_GATED_MASK: c_uint = 0x00400000L;
pub const IH_STATUS__IH_PASID_LUT_MEM_POWER_GATED_MASK: c_uint = 0x00800000L;
// IH_PERFMON_CNTL
pub const IH_PERFMON_CNTL__ENABLE0__SHIFT: c_uint = 0x0;
pub const IH_PERFMON_CNTL__CLEAR0__SHIFT: c_uint = 0x1;
pub const IH_PERFMON_CNTL__PERF_SEL0__SHIFT: c_uint = 0x2;
pub const IH_PERFMON_CNTL__ENABLE1__SHIFT: c_uint = 0x10;
pub const IH_PERFMON_CNTL__CLEAR1__SHIFT: c_uint = 0x11;
pub const IH_PERFMON_CNTL__PERF_SEL1__SHIFT: c_uint = 0x12;
pub const IH_PERFMON_CNTL__ENABLE0_MASK: c_uint = 0x00000001L;
pub const IH_PERFMON_CNTL__CLEAR0_MASK: c_uint = 0x00000002L;
pub const IH_PERFMON_CNTL__PERF_SEL0_MASK: c_uint = 0x00000FFCL;
pub const IH_PERFMON_CNTL__ENABLE1_MASK: c_uint = 0x00010000L;
pub const IH_PERFMON_CNTL__CLEAR1_MASK: c_uint = 0x00020000L;
pub const IH_PERFMON_CNTL__PERF_SEL1_MASK: c_uint = 0x0FFC0000L;
// IH_PERFCOUNTER0_RESULT
pub const IH_PERFCOUNTER0_RESULT__PERF_COUNT__SHIFT: c_uint = 0x0;
pub const IH_PERFCOUNTER0_RESULT__PERF_COUNT_MASK: c_uint = 0xFFFFFFFFL;
// IH_PERFCOUNTER1_RESULT
pub const IH_PERFCOUNTER1_RESULT__PERF_COUNT__SHIFT: c_uint = 0x0;
pub const IH_PERFCOUNTER1_RESULT__PERF_COUNT_MASK: c_uint = 0xFFFFFFFFL;
// IH_DSM_MATCH_VALUE_BIT_31_0
pub const IH_DSM_MATCH_VALUE_BIT_31_0__VALUE__SHIFT: c_uint = 0x0;
pub const IH_DSM_MATCH_VALUE_BIT_31_0__VALUE_MASK: c_uint = 0xFFFFFFFFL;
// IH_DSM_MATCH_VALUE_BIT_63_32
pub const IH_DSM_MATCH_VALUE_BIT_63_32__VALUE__SHIFT: c_uint = 0x0;
pub const IH_DSM_MATCH_VALUE_BIT_63_32__VALUE_MASK: c_uint = 0xFFFFFFFFL;
// IH_DSM_MATCH_VALUE_BIT_95_64
pub const IH_DSM_MATCH_VALUE_BIT_95_64__VALUE__SHIFT: c_uint = 0x0;
pub const IH_DSM_MATCH_VALUE_BIT_95_64__VALUE_MASK: c_uint = 0xFFFFFFFFL;
// IH_DSM_MATCH_FIELD_CONTROL
pub const IH_DSM_MATCH_FIELD_CONTROL__SRC_EN__SHIFT: c_uint = 0x0;
pub const IH_DSM_MATCH_FIELD_CONTROL__FCNID_EN__SHIFT: c_uint = 0x1;
pub const IH_DSM_MATCH_FIELD_CONTROL__TIMESTAMP_EN__SHIFT: c_uint = 0x2;
pub const IH_DSM_MATCH_FIELD_CONTROL__RINGID_EN__SHIFT: c_uint = 0x3;
pub const IH_DSM_MATCH_FIELD_CONTROL__VMID_EN__SHIFT: c_uint = 0x4;
pub const IH_DSM_MATCH_FIELD_CONTROL__PASID_EN__SHIFT: c_uint = 0x5;
pub const IH_DSM_MATCH_FIELD_CONTROL__CLIENT_ID_EN__SHIFT: c_uint = 0x6;
pub const IH_DSM_MATCH_FIELD_CONTROL__SRC_EN_MASK: c_uint = 0x00000001L;
pub const IH_DSM_MATCH_FIELD_CONTROL__FCNID_EN_MASK: c_uint = 0x00000002L;
pub const IH_DSM_MATCH_FIELD_CONTROL__TIMESTAMP_EN_MASK: c_uint = 0x00000004L;
pub const IH_DSM_MATCH_FIELD_CONTROL__RINGID_EN_MASK: c_uint = 0x00000008L;
pub const IH_DSM_MATCH_FIELD_CONTROL__VMID_EN_MASK: c_uint = 0x00000010L;
pub const IH_DSM_MATCH_FIELD_CONTROL__PASID_EN_MASK: c_uint = 0x00000020L;
pub const IH_DSM_MATCH_FIELD_CONTROL__CLIENT_ID_EN_MASK: c_uint = 0x00000040L;
// IH_DSM_MATCH_DATA_CONTROL
pub const IH_DSM_MATCH_DATA_CONTROL__VALUE__SHIFT: c_uint = 0x0;
pub const IH_DSM_MATCH_DATA_CONTROL__VALUE_MASK: c_uint = 0x0FFFFFFFL;
// IH_DSM_MATCH_FCN_ID
pub const IH_DSM_MATCH_FCN_ID__VF_ID__SHIFT: c_uint = 0x0;
pub const IH_DSM_MATCH_FCN_ID__PF_VF__SHIFT: c_uint = 0x7;
pub const IH_DSM_MATCH_FCN_ID__VF_ID_MASK: c_uint = 0x0000000FL;
pub const IH_DSM_MATCH_FCN_ID__PF_VF_MASK: c_uint = 0x00000080L;
// IH_LIMIT_INT_RATE_CNTL
pub const IH_LIMIT_INT_RATE_CNTL__LIMIT_ENABLE__SHIFT: c_uint = 0x0;
pub const IH_LIMIT_INT_RATE_CNTL__PERF_INTERVAL__SHIFT: c_uint = 0x1;
pub const IH_LIMIT_INT_RATE_CNTL__PERF_THRESHOLD__SHIFT: c_uint = 0x5;
pub const IH_LIMIT_INT_RATE_CNTL__RETURN_DELAY__SHIFT: c_uint = 0x11;
pub const IH_LIMIT_INT_RATE_CNTL__PERF_RESULT__SHIFT: c_uint = 0x15;
pub const IH_LIMIT_INT_RATE_CNTL__LIMIT_ENABLE_MASK: c_uint = 0x00000001L;
pub const IH_LIMIT_INT_RATE_CNTL__PERF_INTERVAL_MASK: c_uint = 0x0000001EL;
pub const IH_LIMIT_INT_RATE_CNTL__PERF_THRESHOLD_MASK: c_uint = 0x0000FFE0L;
pub const IH_LIMIT_INT_RATE_CNTL__RETURN_DELAY_MASK: c_uint = 0x001E0000L;
pub const IH_LIMIT_INT_RATE_CNTL__PERF_RESULT_MASK: c_uint = 0xFFE00000L;
// IH_VF_RB_STATUS
pub const IH_VF_RB_STATUS__RB_FULL_DRAIN_VF__SHIFT: c_uint = 0x0;
pub const IH_VF_RB_STATUS__RB_FULL_DRAIN_VF_MASK: c_uint = 0x0000FFFFL;
// IH_VF_RB_STATUS2
pub const IH_VF_RB_STATUS2__RB_FULL_VF__SHIFT: c_uint = 0x0;
pub const IH_VF_RB_STATUS2__RB_FULL_VF_MASK: c_uint = 0x0000FFFFL;
// IH_VF_RB1_STATUS
pub const IH_VF_RB1_STATUS__RB_FULL_DRAIN_VF__SHIFT: c_uint = 0x0;
pub const IH_VF_RB1_STATUS__RB_FULL_DRAIN_VF_MASK: c_uint = 0x0000FFFFL;
// IH_VF_RB1_STATUS2
pub const IH_VF_RB1_STATUS2__RB_FULL_VF__SHIFT: c_uint = 0x0;
pub const IH_VF_RB1_STATUS2__RB_FULL_VF_MASK: c_uint = 0x0000FFFFL;
// IH_RB_STATUS
pub const IH_RB_STATUS__RB_FULL__SHIFT: c_uint = 0x0;
pub const IH_RB_STATUS__RB_FULL_DRAIN__SHIFT: c_uint = 0x1;
pub const IH_RB_STATUS__RB_OVERFLOW__SHIFT: c_uint = 0x2;
pub const IH_RB_STATUS__RB1_FULL__SHIFT: c_uint = 0x4;
pub const IH_RB_STATUS__RB1_FULL_DRAIN__SHIFT: c_uint = 0x5;
pub const IH_RB_STATUS__RB1_OVERFLOW__SHIFT: c_uint = 0x6;
pub const IH_RB_STATUS__RB_FULL_MASK: c_uint = 0x00000001L;
pub const IH_RB_STATUS__RB_FULL_DRAIN_MASK: c_uint = 0x00000002L;
pub const IH_RB_STATUS__RB_OVERFLOW_MASK: c_uint = 0x00000004L;
pub const IH_RB_STATUS__RB1_FULL_MASK: c_uint = 0x00000010L;
pub const IH_RB_STATUS__RB1_FULL_DRAIN_MASK: c_uint = 0x00000020L;
pub const IH_RB_STATUS__RB1_OVERFLOW_MASK: c_uint = 0x00000040L;
// IH_INT_FLOOD_CNTL
pub const IH_INT_FLOOD_CNTL__HIGHWATER__SHIFT: c_uint = 0x0;
pub const IH_INT_FLOOD_CNTL__FLOOD_CNTL_ENABLE__SHIFT: c_uint = 0x3;
pub const IH_INT_FLOOD_CNTL__CLEAR_INT_FLOOD_STATUS__SHIFT: c_uint = 0x4;
pub const IH_INT_FLOOD_CNTL__HIGHWATER_MASK: c_uint = 0x00000007L;
pub const IH_INT_FLOOD_CNTL__FLOOD_CNTL_ENABLE_MASK: c_uint = 0x00000008L;
pub const IH_INT_FLOOD_CNTL__CLEAR_INT_FLOOD_STATUS_MASK: c_uint = 0x00000010L;
// IH_RB0_INT_FLOOD_STATUS
pub const IH_RB0_INT_FLOOD_STATUS__RB_INT_DROPPED_VF__SHIFT: c_uint = 0x0;
pub const IH_RB0_INT_FLOOD_STATUS__RB_INT_DROPPED__SHIFT: c_uint = 0x1f;
pub const IH_RB0_INT_FLOOD_STATUS__RB_INT_DROPPED_VF_MASK: c_uint = 0x0000FFFFL;
pub const IH_RB0_INT_FLOOD_STATUS__RB_INT_DROPPED_MASK: c_uint = 0x80000000L;
// IH_RB1_INT_FLOOD_STATUS
pub const IH_RB1_INT_FLOOD_STATUS__RB_INT_DROPPED_VF__SHIFT: c_uint = 0x0;
pub const IH_RB1_INT_FLOOD_STATUS__RB_INT_DROPPED__SHIFT: c_uint = 0x1f;
pub const IH_RB1_INT_FLOOD_STATUS__RB_INT_DROPPED_VF_MASK: c_uint = 0x0000FFFFL;
pub const IH_RB1_INT_FLOOD_STATUS__RB_INT_DROPPED_MASK: c_uint = 0x80000000L;
// IH_INT_FLOOD_STATUS
pub const IH_INT_FLOOD_STATUS__INT_DROP_CNT__SHIFT: c_uint = 0x0;
pub const IH_INT_FLOOD_STATUS__FIRST_DROP_INT_CLIENT_ID__SHIFT: c_uint = 0x8;
pub const IH_INT_FLOOD_STATUS__FIRST_DROP_INT_SOURCE_ID__SHIFT: c_uint = 0x10;
pub const IH_INT_FLOOD_STATUS__FIRST_DROP_INT_VF_ID__SHIFT: c_uint = 0x18;
pub const IH_INT_FLOOD_STATUS__FIRST_DROP_INT_VF__SHIFT: c_uint = 0x1d;
pub const IH_INT_FLOOD_STATUS__INT_DROPPED__SHIFT: c_uint = 0x1e;
pub const IH_INT_FLOOD_STATUS__INT_DROP_CNT_MASK: c_uint = 0x000000FFL;
pub const IH_INT_FLOOD_STATUS__FIRST_DROP_INT_CLIENT_ID_MASK: c_uint = 0x0000FF00L;
pub const IH_INT_FLOOD_STATUS__FIRST_DROP_INT_SOURCE_ID_MASK: c_uint = 0x00FF0000L;
pub const IH_INT_FLOOD_STATUS__FIRST_DROP_INT_VF_ID_MASK: c_uint = 0x0F000000L;
pub const IH_INT_FLOOD_STATUS__FIRST_DROP_INT_VF_MASK: c_uint = 0x20000000L;
pub const IH_INT_FLOOD_STATUS__INT_DROPPED_MASK: c_uint = 0x40000000L;
// IH_STORM_CLIENT_LIST_CNTL
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT1_IS_STORM_CLIENT__SHIFT: c_uint = 0x1;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT2_IS_STORM_CLIENT__SHIFT: c_uint = 0x2;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT3_IS_STORM_CLIENT__SHIFT: c_uint = 0x3;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT4_IS_STORM_CLIENT__SHIFT: c_uint = 0x4;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT5_IS_STORM_CLIENT__SHIFT: c_uint = 0x5;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT6_IS_STORM_CLIENT__SHIFT: c_uint = 0x6;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT7_IS_STORM_CLIENT__SHIFT: c_uint = 0x7;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT8_IS_STORM_CLIENT__SHIFT: c_uint = 0x8;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT9_IS_STORM_CLIENT__SHIFT: c_uint = 0x9;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT10_IS_STORM_CLIENT__SHIFT: c_uint = 0xa;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT11_IS_STORM_CLIENT__SHIFT: c_uint = 0xb;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT12_IS_STORM_CLIENT__SHIFT: c_uint = 0xc;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT13_IS_STORM_CLIENT__SHIFT: c_uint = 0xd;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT14_IS_STORM_CLIENT__SHIFT: c_uint = 0xe;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT15_IS_STORM_CLIENT__SHIFT: c_uint = 0xf;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT16_IS_STORM_CLIENT__SHIFT: c_uint = 0x10;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT17_IS_STORM_CLIENT__SHIFT: c_uint = 0x11;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT18_IS_STORM_CLIENT__SHIFT: c_uint = 0x12;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT19_IS_STORM_CLIENT__SHIFT: c_uint = 0x13;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT20_IS_STORM_CLIENT__SHIFT: c_uint = 0x14;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT21_IS_STORM_CLIENT__SHIFT: c_uint = 0x15;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT22_IS_STORM_CLIENT__SHIFT: c_uint = 0x16;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT23_IS_STORM_CLIENT__SHIFT: c_uint = 0x17;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT24_IS_STORM_CLIENT__SHIFT: c_uint = 0x18;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT25_IS_STORM_CLIENT__SHIFT: c_uint = 0x19;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT26_IS_STORM_CLIENT__SHIFT: c_uint = 0x1a;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT27_IS_STORM_CLIENT__SHIFT: c_uint = 0x1b;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT28_IS_STORM_CLIENT__SHIFT: c_uint = 0x1c;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT29_IS_STORM_CLIENT__SHIFT: c_uint = 0x1d;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT30_IS_STORM_CLIENT__SHIFT: c_uint = 0x1e;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT31_IS_STORM_CLIENT__SHIFT: c_uint = 0x1f;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT1_IS_STORM_CLIENT_MASK: c_uint = 0x00000002L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT2_IS_STORM_CLIENT_MASK: c_uint = 0x00000004L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT3_IS_STORM_CLIENT_MASK: c_uint = 0x00000008L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT4_IS_STORM_CLIENT_MASK: c_uint = 0x00000010L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT5_IS_STORM_CLIENT_MASK: c_uint = 0x00000020L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT6_IS_STORM_CLIENT_MASK: c_uint = 0x00000040L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT7_IS_STORM_CLIENT_MASK: c_uint = 0x00000080L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT8_IS_STORM_CLIENT_MASK: c_uint = 0x00000100L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT9_IS_STORM_CLIENT_MASK: c_uint = 0x00000200L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT10_IS_STORM_CLIENT_MASK: c_uint = 0x00000400L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT11_IS_STORM_CLIENT_MASK: c_uint = 0x00000800L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT12_IS_STORM_CLIENT_MASK: c_uint = 0x00001000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT13_IS_STORM_CLIENT_MASK: c_uint = 0x00002000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT14_IS_STORM_CLIENT_MASK: c_uint = 0x00004000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT15_IS_STORM_CLIENT_MASK: c_uint = 0x00008000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT16_IS_STORM_CLIENT_MASK: c_uint = 0x00010000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT17_IS_STORM_CLIENT_MASK: c_uint = 0x00020000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT18_IS_STORM_CLIENT_MASK: c_uint = 0x00040000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT19_IS_STORM_CLIENT_MASK: c_uint = 0x00080000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT20_IS_STORM_CLIENT_MASK: c_uint = 0x00100000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT21_IS_STORM_CLIENT_MASK: c_uint = 0x00200000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT22_IS_STORM_CLIENT_MASK: c_uint = 0x00400000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT23_IS_STORM_CLIENT_MASK: c_uint = 0x00800000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT24_IS_STORM_CLIENT_MASK: c_uint = 0x01000000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT25_IS_STORM_CLIENT_MASK: c_uint = 0x02000000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT26_IS_STORM_CLIENT_MASK: c_uint = 0x04000000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT27_IS_STORM_CLIENT_MASK: c_uint = 0x08000000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT28_IS_STORM_CLIENT_MASK: c_uint = 0x10000000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT29_IS_STORM_CLIENT_MASK: c_uint = 0x20000000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT30_IS_STORM_CLIENT_MASK: c_uint = 0x40000000L;
pub const IH_STORM_CLIENT_LIST_CNTL__CLIENT31_IS_STORM_CLIENT_MASK: c_uint = 0x80000000L;
// IH_CLK_CTRL
pub const IH_CLK_CTRL__IH_PASID_LUT_MEM_CLK_SOFT_OVERRIDE__SHIFT: c_uint = 0x17;
pub const IH_CLK_CTRL__MSI_STORM_COUNTER_CLK_SOFT_OVERRIDE__SHIFT: c_uint = 0x18;
pub const IH_CLK_CTRL__IH_RETRY_INT_CAM_MEM_CLK_SOFT_OVERRIDE__SHIFT: c_uint = 0x19;
pub const IH_CLK_CTRL__IH_BUFFER_MEM_CLK_SOFT_OVERRIDE__SHIFT: c_uint = 0x1a;
pub const IH_CLK_CTRL__DBUS_MUX_CLK_SOFT_OVERRIDE__SHIFT: c_uint = 0x1b;
pub const IH_CLK_CTRL__OSSSYS_SHARE_CLK_SOFT_OVERRIDE__SHIFT: c_uint = 0x1c;
pub const IH_CLK_CTRL__LIMIT_SMN_CLK_SOFT_OVERRIDE__SHIFT: c_uint = 0x1d;
pub const IH_CLK_CTRL__DYN_CLK_SOFT_OVERRIDE__SHIFT: c_uint = 0x1e;
pub const IH_CLK_CTRL__REG_CLK_SOFT_OVERRIDE__SHIFT: c_uint = 0x1f;
pub const IH_CLK_CTRL__IH_PASID_LUT_MEM_CLK_SOFT_OVERRIDE_MASK: c_uint = 0x00800000L;
pub const IH_CLK_CTRL__MSI_STORM_COUNTER_CLK_SOFT_OVERRIDE_MASK: c_uint = 0x01000000L;
pub const IH_CLK_CTRL__IH_RETRY_INT_CAM_MEM_CLK_SOFT_OVERRIDE_MASK: c_uint = 0x02000000L;
pub const IH_CLK_CTRL__IH_BUFFER_MEM_CLK_SOFT_OVERRIDE_MASK: c_uint = 0x04000000L;
pub const IH_CLK_CTRL__DBUS_MUX_CLK_SOFT_OVERRIDE_MASK: c_uint = 0x08000000L;
pub const IH_CLK_CTRL__OSSSYS_SHARE_CLK_SOFT_OVERRIDE_MASK: c_uint = 0x10000000L;
pub const IH_CLK_CTRL__LIMIT_SMN_CLK_SOFT_OVERRIDE_MASK: c_uint = 0x20000000L;
pub const IH_CLK_CTRL__DYN_CLK_SOFT_OVERRIDE_MASK: c_uint = 0x40000000L;
pub const IH_CLK_CTRL__REG_CLK_SOFT_OVERRIDE_MASK: c_uint = 0x80000000L;
// IH_INT_FLAGS
pub const IH_INT_FLAGS__CLIENT_0_FLAG__SHIFT: c_uint = 0x0;
pub const IH_INT_FLAGS__CLIENT_1_FLAG__SHIFT: c_uint = 0x1;
pub const IH_INT_FLAGS__CLIENT_2_FLAG__SHIFT: c_uint = 0x2;
pub const IH_INT_FLAGS__CLIENT_3_FLAG__SHIFT: c_uint = 0x3;
pub const IH_INT_FLAGS__CLIENT_4_FLAG__SHIFT: c_uint = 0x4;
pub const IH_INT_FLAGS__CLIENT_5_FLAG__SHIFT: c_uint = 0x5;
pub const IH_INT_FLAGS__CLIENT_6_FLAG__SHIFT: c_uint = 0x6;
pub const IH_INT_FLAGS__CLIENT_7_FLAG__SHIFT: c_uint = 0x7;
pub const IH_INT_FLAGS__CLIENT_8_FLAG__SHIFT: c_uint = 0x8;
pub const IH_INT_FLAGS__CLIENT_9_FLAG__SHIFT: c_uint = 0x9;
pub const IH_INT_FLAGS__CLIENT_10_FLAG__SHIFT: c_uint = 0xa;
pub const IH_INT_FLAGS__CLIENT_11_FLAG__SHIFT: c_uint = 0xb;
pub const IH_INT_FLAGS__CLIENT_12_FLAG__SHIFT: c_uint = 0xc;
pub const IH_INT_FLAGS__CLIENT_13_FLAG__SHIFT: c_uint = 0xd;
pub const IH_INT_FLAGS__CLIENT_14_FLAG__SHIFT: c_uint = 0xe;
pub const IH_INT_FLAGS__CLIENT_15_FLAG__SHIFT: c_uint = 0xf;
pub const IH_INT_FLAGS__CLIENT_16_FLAG__SHIFT: c_uint = 0x10;
pub const IH_INT_FLAGS__CLIENT_17_FLAG__SHIFT: c_uint = 0x11;
pub const IH_INT_FLAGS__CLIENT_18_FLAG__SHIFT: c_uint = 0x12;
pub const IH_INT_FLAGS__CLIENT_19_FLAG__SHIFT: c_uint = 0x13;
pub const IH_INT_FLAGS__CLIENT_20_FLAG__SHIFT: c_uint = 0x14;
pub const IH_INT_FLAGS__CLIENT_21_FLAG__SHIFT: c_uint = 0x15;
pub const IH_INT_FLAGS__CLIENT_22_FLAG__SHIFT: c_uint = 0x16;
pub const IH_INT_FLAGS__CLIENT_23_FLAG__SHIFT: c_uint = 0x17;
pub const IH_INT_FLAGS__CLIENT_24_FLAG__SHIFT: c_uint = 0x18;
pub const IH_INT_FLAGS__CLIENT_25_FLAG__SHIFT: c_uint = 0x19;
pub const IH_INT_FLAGS__CLIENT_26_FLAG__SHIFT: c_uint = 0x1a;
pub const IH_INT_FLAGS__CLIENT_27_FLAG__SHIFT: c_uint = 0x1b;
pub const IH_INT_FLAGS__CLIENT_28_FLAG__SHIFT: c_uint = 0x1c;
pub const IH_INT_FLAGS__CLIENT_29_FLAG__SHIFT: c_uint = 0x1d;
pub const IH_INT_FLAGS__CLIENT_30_FLAG__SHIFT: c_uint = 0x1e;
pub const IH_INT_FLAGS__CLIENT_31_FLAG__SHIFT: c_uint = 0x1f;
pub const IH_INT_FLAGS__CLIENT_0_FLAG_MASK: c_uint = 0x00000001L;
pub const IH_INT_FLAGS__CLIENT_1_FLAG_MASK: c_uint = 0x00000002L;
pub const IH_INT_FLAGS__CLIENT_2_FLAG_MASK: c_uint = 0x00000004L;
pub const IH_INT_FLAGS__CLIENT_3_FLAG_MASK: c_uint = 0x00000008L;
pub const IH_INT_FLAGS__CLIENT_4_FLAG_MASK: c_uint = 0x00000010L;
pub const IH_INT_FLAGS__CLIENT_5_FLAG_MASK: c_uint = 0x00000020L;
pub const IH_INT_FLAGS__CLIENT_6_FLAG_MASK: c_uint = 0x00000040L;
pub const IH_INT_FLAGS__CLIENT_7_FLAG_MASK: c_uint = 0x00000080L;
pub const IH_INT_FLAGS__CLIENT_8_FLAG_MASK: c_uint = 0x00000100L;
pub const IH_INT_FLAGS__CLIENT_9_FLAG_MASK: c_uint = 0x00000200L;
pub const IH_INT_FLAGS__CLIENT_10_FLAG_MASK: c_uint = 0x00000400L;
pub const IH_INT_FLAGS__CLIENT_11_FLAG_MASK: c_uint = 0x00000800L;
pub const IH_INT_FLAGS__CLIENT_12_FLAG_MASK: c_uint = 0x00001000L;
pub const IH_INT_FLAGS__CLIENT_13_FLAG_MASK: c_uint = 0x00002000L;
pub const IH_INT_FLAGS__CLIENT_14_FLAG_MASK: c_uint = 0x00004000L;
pub const IH_INT_FLAGS__CLIENT_15_FLAG_MASK: c_uint = 0x00008000L;
pub const IH_INT_FLAGS__CLIENT_16_FLAG_MASK: c_uint = 0x00010000L;
pub const IH_INT_FLAGS__CLIENT_17_FLAG_MASK: c_uint = 0x00020000L;
pub const IH_INT_FLAGS__CLIENT_18_FLAG_MASK: c_uint = 0x00040000L;
pub const IH_INT_FLAGS__CLIENT_19_FLAG_MASK: c_uint = 0x00080000L;
pub const IH_INT_FLAGS__CLIENT_20_FLAG_MASK: c_uint = 0x00100000L;
pub const IH_INT_FLAGS__CLIENT_21_FLAG_MASK: c_uint = 0x00200000L;
pub const IH_INT_FLAGS__CLIENT_22_FLAG_MASK: c_uint = 0x00400000L;
pub const IH_INT_FLAGS__CLIENT_23_FLAG_MASK: c_uint = 0x00800000L;
pub const IH_INT_FLAGS__CLIENT_24_FLAG_MASK: c_uint = 0x01000000L;
pub const IH_INT_FLAGS__CLIENT_25_FLAG_MASK: c_uint = 0x02000000L;
pub const IH_INT_FLAGS__CLIENT_26_FLAG_MASK: c_uint = 0x04000000L;
pub const IH_INT_FLAGS__CLIENT_27_FLAG_MASK: c_uint = 0x08000000L;
pub const IH_INT_FLAGS__CLIENT_28_FLAG_MASK: c_uint = 0x10000000L;
pub const IH_INT_FLAGS__CLIENT_29_FLAG_MASK: c_uint = 0x20000000L;
pub const IH_INT_FLAGS__CLIENT_30_FLAG_MASK: c_uint = 0x40000000L;
pub const IH_INT_FLAGS__CLIENT_31_FLAG_MASK: c_uint = 0x80000000L;
// IH_LAST_INT_INFO0
pub const IH_LAST_INT_INFO0__CLIENT_ID__SHIFT: c_uint = 0x0;
pub const IH_LAST_INT_INFO0__SOURCE_ID__SHIFT: c_uint = 0x8;
pub const IH_LAST_INT_INFO0__RING_ID__SHIFT: c_uint = 0x10;
pub const IH_LAST_INT_INFO0__VM_ID__SHIFT: c_uint = 0x18;
pub const IH_LAST_INT_INFO0__VMID_TYPE__SHIFT: c_uint = 0x1f;
pub const IH_LAST_INT_INFO0__CLIENT_ID_MASK: c_uint = 0x000000FFL;
pub const IH_LAST_INT_INFO0__SOURCE_ID_MASK: c_uint = 0x0000FF00L;
pub const IH_LAST_INT_INFO0__RING_ID_MASK: c_uint = 0x00FF0000L;
pub const IH_LAST_INT_INFO0__VM_ID_MASK: c_uint = 0x0F000000L;
pub const IH_LAST_INT_INFO0__VMID_TYPE_MASK: c_uint = 0x80000000L;
// IH_LAST_INT_INFO1
pub const IH_LAST_INT_INFO1__CONTEXT_ID__SHIFT: c_uint = 0x0;
pub const IH_LAST_INT_INFO1__CONTEXT_ID_MASK: c_uint = 0xFFFFFFFFL;
// IH_LAST_INT_INFO2
pub const IH_LAST_INT_INFO2__PAS_ID__SHIFT: c_uint = 0x0;
pub const IH_LAST_INT_INFO2__VF_ID__SHIFT: c_uint = 0x10;
pub const IH_LAST_INT_INFO2__VF__SHIFT: c_uint = 0x17;
pub const IH_LAST_INT_INFO2__PAS_ID_MASK: c_uint = 0x0000FFFFL;
pub const IH_LAST_INT_INFO2__VF_ID_MASK: c_uint = 0x000F0000L;
pub const IH_LAST_INT_INFO2__VF_MASK: c_uint = 0x00800000L;
// IH_SCRATCH
pub const IH_SCRATCH__DATA__SHIFT: c_uint = 0x0;
pub const IH_SCRATCH__DATA_MASK: c_uint = 0xFFFFFFFFL;
// IH_CLIENT_CREDIT_ERROR
pub const IH_CLIENT_CREDIT_ERROR__CLEAR__SHIFT: c_uint = 0x0;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_1_ERROR__SHIFT: c_uint = 0x1;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_2_ERROR__SHIFT: c_uint = 0x2;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_3_ERROR__SHIFT: c_uint = 0x3;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_4_ERROR__SHIFT: c_uint = 0x4;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_5_ERROR__SHIFT: c_uint = 0x5;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_6_ERROR__SHIFT: c_uint = 0x6;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_7_ERROR__SHIFT: c_uint = 0x7;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_8_ERROR__SHIFT: c_uint = 0x8;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_9_ERROR__SHIFT: c_uint = 0x9;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_10_ERROR__SHIFT: c_uint = 0xa;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_11_ERROR__SHIFT: c_uint = 0xb;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_12_ERROR__SHIFT: c_uint = 0xc;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_13_ERROR__SHIFT: c_uint = 0xd;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_14_ERROR__SHIFT: c_uint = 0xe;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_15_ERROR__SHIFT: c_uint = 0xf;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_16_ERROR__SHIFT: c_uint = 0x10;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_17_ERROR__SHIFT: c_uint = 0x11;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_18_ERROR__SHIFT: c_uint = 0x12;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_19_ERROR__SHIFT: c_uint = 0x13;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_20_ERROR__SHIFT: c_uint = 0x14;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_21_ERROR__SHIFT: c_uint = 0x15;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_22_ERROR__SHIFT: c_uint = 0x16;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_23_ERROR__SHIFT: c_uint = 0x17;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_24_ERROR__SHIFT: c_uint = 0x18;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_25_ERROR__SHIFT: c_uint = 0x19;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_26_ERROR__SHIFT: c_uint = 0x1a;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_27_ERROR__SHIFT: c_uint = 0x1b;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_28_ERROR__SHIFT: c_uint = 0x1c;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_29_ERROR__SHIFT: c_uint = 0x1d;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_30_ERROR__SHIFT: c_uint = 0x1e;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_31_ERROR__SHIFT: c_uint = 0x1f;
pub const IH_CLIENT_CREDIT_ERROR__CLEAR_MASK: c_uint = 0x00000001L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_1_ERROR_MASK: c_uint = 0x00000002L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_2_ERROR_MASK: c_uint = 0x00000004L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_3_ERROR_MASK: c_uint = 0x00000008L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_4_ERROR_MASK: c_uint = 0x00000010L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_5_ERROR_MASK: c_uint = 0x00000020L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_6_ERROR_MASK: c_uint = 0x00000040L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_7_ERROR_MASK: c_uint = 0x00000080L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_8_ERROR_MASK: c_uint = 0x00000100L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_9_ERROR_MASK: c_uint = 0x00000200L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_10_ERROR_MASK: c_uint = 0x00000400L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_11_ERROR_MASK: c_uint = 0x00000800L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_12_ERROR_MASK: c_uint = 0x00001000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_13_ERROR_MASK: c_uint = 0x00002000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_14_ERROR_MASK: c_uint = 0x00004000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_15_ERROR_MASK: c_uint = 0x00008000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_16_ERROR_MASK: c_uint = 0x00010000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_17_ERROR_MASK: c_uint = 0x00020000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_18_ERROR_MASK: c_uint = 0x00040000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_19_ERROR_MASK: c_uint = 0x00080000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_20_ERROR_MASK: c_uint = 0x00100000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_21_ERROR_MASK: c_uint = 0x00200000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_22_ERROR_MASK: c_uint = 0x00400000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_23_ERROR_MASK: c_uint = 0x00800000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_24_ERROR_MASK: c_uint = 0x01000000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_25_ERROR_MASK: c_uint = 0x02000000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_26_ERROR_MASK: c_uint = 0x04000000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_27_ERROR_MASK: c_uint = 0x08000000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_28_ERROR_MASK: c_uint = 0x10000000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_29_ERROR_MASK: c_uint = 0x20000000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_30_ERROR_MASK: c_uint = 0x40000000L;
pub const IH_CLIENT_CREDIT_ERROR__CLIENT_31_ERROR_MASK: c_uint = 0x80000000L;
// IH_COOKIE_REC_VIOLATION_LOG
pub const IH_COOKIE_REC_VIOLATION_LOG__VIOLATION_STATUS__SHIFT: c_uint = 0x0;
pub const IH_COOKIE_REC_VIOLATION_LOG__CLIENT_ID__SHIFT: c_uint = 0x8;
pub const IH_COOKIE_REC_VIOLATION_LOG__INITIATOR_ID__SHIFT: c_uint = 0x10;
pub const IH_COOKIE_REC_VIOLATION_LOG__VIOLATION_STATUS_MASK: c_uint = 0x00000001L;
pub const IH_COOKIE_REC_VIOLATION_LOG__CLIENT_ID_MASK: c_uint = 0x0000FF00L;
pub const IH_COOKIE_REC_VIOLATION_LOG__INITIATOR_ID_MASK: c_uint = 0x03FF0000L;
// IH_CREDIT_STATUS
pub const IH_CREDIT_STATUS__CLIENT_1_CREDIT_RETURNED__SHIFT: c_uint = 0x1;
pub const IH_CREDIT_STATUS__CLIENT_2_CREDIT_RETURNED__SHIFT: c_uint = 0x2;
pub const IH_CREDIT_STATUS__CLIENT_3_CREDIT_RETURNED__SHIFT: c_uint = 0x3;
pub const IH_CREDIT_STATUS__CLIENT_4_CREDIT_RETURNED__SHIFT: c_uint = 0x4;
pub const IH_CREDIT_STATUS__CLIENT_5_CREDIT_RETURNED__SHIFT: c_uint = 0x5;
pub const IH_CREDIT_STATUS__CLIENT_6_CREDIT_RETURNED__SHIFT: c_uint = 0x6;
pub const IH_CREDIT_STATUS__CLIENT_7_CREDIT_RETURNED__SHIFT: c_uint = 0x7;
pub const IH_CREDIT_STATUS__CLIENT_8_CREDIT_RETURNED__SHIFT: c_uint = 0x8;
pub const IH_CREDIT_STATUS__CLIENT_9_CREDIT_RETURNED__SHIFT: c_uint = 0x9;
pub const IH_CREDIT_STATUS__CLIENT_10_CREDIT_RETURNED__SHIFT: c_uint = 0xa;
pub const IH_CREDIT_STATUS__CLIENT_11_CREDIT_RETURNED__SHIFT: c_uint = 0xb;
pub const IH_CREDIT_STATUS__CLIENT_12_CREDIT_RETURNED__SHIFT: c_uint = 0xc;
pub const IH_CREDIT_STATUS__CLIENT_13_CREDIT_RETURNED__SHIFT: c_uint = 0xd;
pub const IH_CREDIT_STATUS__CLIENT_14_CREDIT_RETURNED__SHIFT: c_uint = 0xe;
pub const IH_CREDIT_STATUS__CLIENT_15_CREDIT_RETURNED__SHIFT: c_uint = 0xf;
pub const IH_CREDIT_STATUS__CLIENT_16_CREDIT_RETURNED__SHIFT: c_uint = 0x10;
pub const IH_CREDIT_STATUS__CLIENT_17_CREDIT_RETURNED__SHIFT: c_uint = 0x11;
pub const IH_CREDIT_STATUS__CLIENT_18_CREDIT_RETURNED__SHIFT: c_uint = 0x12;
pub const IH_CREDIT_STATUS__CLIENT_19_CREDIT_RETURNED__SHIFT: c_uint = 0x13;
pub const IH_CREDIT_STATUS__CLIENT_20_CREDIT_RETURNED__SHIFT: c_uint = 0x14;
pub const IH_CREDIT_STATUS__CLIENT_21_CREDIT_RETURNED__SHIFT: c_uint = 0x15;
pub const IH_CREDIT_STATUS__CLIENT_22_CREDIT_RETURNED__SHIFT: c_uint = 0x16;
pub const IH_CREDIT_STATUS__CLIENT_23_CREDIT_RETURNED__SHIFT: c_uint = 0x17;
pub const IH_CREDIT_STATUS__CLIENT_24_CREDIT_RETURNED__SHIFT: c_uint = 0x18;
pub const IH_CREDIT_STATUS__CLIENT_25_CREDIT_RETURNED__SHIFT: c_uint = 0x19;
pub const IH_CREDIT_STATUS__CLIENT_26_CREDIT_RETURNED__SHIFT: c_uint = 0x1a;
pub const IH_CREDIT_STATUS__CLIENT_27_CREDIT_RETURNED__SHIFT: c_uint = 0x1b;
pub const IH_CREDIT_STATUS__CLIENT_28_CREDIT_RETURNED__SHIFT: c_uint = 0x1c;
pub const IH_CREDIT_STATUS__CLIENT_29_CREDIT_RETURNED__SHIFT: c_uint = 0x1d;
pub const IH_CREDIT_STATUS__CLIENT_30_CREDIT_RETURNED__SHIFT: c_uint = 0x1e;
pub const IH_CREDIT_STATUS__CLIENT_31_CREDIT_RETURNED__SHIFT: c_uint = 0x1f;
pub const IH_CREDIT_STATUS__CLIENT_1_CREDIT_RETURNED_MASK: c_uint = 0x00000002L;
pub const IH_CREDIT_STATUS__CLIENT_2_CREDIT_RETURNED_MASK: c_uint = 0x00000004L;
pub const IH_CREDIT_STATUS__CLIENT_3_CREDIT_RETURNED_MASK: c_uint = 0x00000008L;
pub const IH_CREDIT_STATUS__CLIENT_4_CREDIT_RETURNED_MASK: c_uint = 0x00000010L;
pub const IH_CREDIT_STATUS__CLIENT_5_CREDIT_RETURNED_MASK: c_uint = 0x00000020L;
pub const IH_CREDIT_STATUS__CLIENT_6_CREDIT_RETURNED_MASK: c_uint = 0x00000040L;
pub const IH_CREDIT_STATUS__CLIENT_7_CREDIT_RETURNED_MASK: c_uint = 0x00000080L;
pub const IH_CREDIT_STATUS__CLIENT_8_CREDIT_RETURNED_MASK: c_uint = 0x00000100L;
pub const IH_CREDIT_STATUS__CLIENT_9_CREDIT_RETURNED_MASK: c_uint = 0x00000200L;
pub const IH_CREDIT_STATUS__CLIENT_10_CREDIT_RETURNED_MASK: c_uint = 0x00000400L;
pub const IH_CREDIT_STATUS__CLIENT_11_CREDIT_RETURNED_MASK: c_uint = 0x00000800L;
pub const IH_CREDIT_STATUS__CLIENT_12_CREDIT_RETURNED_MASK: c_uint = 0x00001000L;
pub const IH_CREDIT_STATUS__CLIENT_13_CREDIT_RETURNED_MASK: c_uint = 0x00002000L;
pub const IH_CREDIT_STATUS__CLIENT_14_CREDIT_RETURNED_MASK: c_uint = 0x00004000L;
pub const IH_CREDIT_STATUS__CLIENT_15_CREDIT_RETURNED_MASK: c_uint = 0x00008000L;
pub const IH_CREDIT_STATUS__CLIENT_16_CREDIT_RETURNED_MASK: c_uint = 0x00010000L;
pub const IH_CREDIT_STATUS__CLIENT_17_CREDIT_RETURNED_MASK: c_uint = 0x00020000L;
pub const IH_CREDIT_STATUS__CLIENT_18_CREDIT_RETURNED_MASK: c_uint = 0x00040000L;
pub const IH_CREDIT_STATUS__CLIENT_19_CREDIT_RETURNED_MASK: c_uint = 0x00080000L;
pub const IH_CREDIT_STATUS__CLIENT_20_CREDIT_RETURNED_MASK: c_uint = 0x00100000L;
pub const IH_CREDIT_STATUS__CLIENT_21_CREDIT_RETURNED_MASK: c_uint = 0x00200000L;
pub const IH_CREDIT_STATUS__CLIENT_22_CREDIT_RETURNED_MASK: c_uint = 0x00400000L;
pub const IH_CREDIT_STATUS__CLIENT_23_CREDIT_RETURNED_MASK: c_uint = 0x00800000L;
pub const IH_CREDIT_STATUS__CLIENT_24_CREDIT_RETURNED_MASK: c_uint = 0x01000000L;
pub const IH_CREDIT_STATUS__CLIENT_25_CREDIT_RETURNED_MASK: c_uint = 0x02000000L;
pub const IH_CREDIT_STATUS__CLIENT_26_CREDIT_RETURNED_MASK: c_uint = 0x04000000L;
pub const IH_CREDIT_STATUS__CLIENT_27_CREDIT_RETURNED_MASK: c_uint = 0x08000000L;
pub const IH_CREDIT_STATUS__CLIENT_28_CREDIT_RETURNED_MASK: c_uint = 0x10000000L;
pub const IH_CREDIT_STATUS__CLIENT_29_CREDIT_RETURNED_MASK: c_uint = 0x20000000L;
pub const IH_CREDIT_STATUS__CLIENT_30_CREDIT_RETURNED_MASK: c_uint = 0x40000000L;
pub const IH_CREDIT_STATUS__CLIENT_31_CREDIT_RETURNED_MASK: c_uint = 0x80000000L;
// IH_MMHUB_ERROR
pub const IH_MMHUB_ERROR__IH_BRESP_01__SHIFT: c_uint = 0x1;
pub const IH_MMHUB_ERROR__IH_BRESP_10__SHIFT: c_uint = 0x2;
pub const IH_MMHUB_ERROR__IH_BRESP_11__SHIFT: c_uint = 0x3;
pub const IH_MMHUB_ERROR__IH_BUSER_NACK_01__SHIFT: c_uint = 0x5;
pub const IH_MMHUB_ERROR__IH_BUSER_NACK_10__SHIFT: c_uint = 0x6;
pub const IH_MMHUB_ERROR__IH_BUSER_NACK_11__SHIFT: c_uint = 0x7;
pub const IH_MMHUB_ERROR__IH_BRESP_01_MASK: c_uint = 0x00000002L;
pub const IH_MMHUB_ERROR__IH_BRESP_10_MASK: c_uint = 0x00000004L;
pub const IH_MMHUB_ERROR__IH_BRESP_11_MASK: c_uint = 0x00000008L;
pub const IH_MMHUB_ERROR__IH_BUSER_NACK_01_MASK: c_uint = 0x00000020L;
pub const IH_MMHUB_ERROR__IH_BUSER_NACK_10_MASK: c_uint = 0x00000040L;
pub const IH_MMHUB_ERROR__IH_BUSER_NACK_11_MASK: c_uint = 0x00000080L;
// IH_MEM_POWER_CTRL
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_CTRL_EN__SHIFT: c_uint = 0x0;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_LS_EN__SHIFT: c_uint = 0x1;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_DS_EN__SHIFT: c_uint = 0x2;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_SD_EN__SHIFT: c_uint = 0x3;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_IDLE_HYSTERESIS__SHIFT: c_uint = 0x4;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_UP_RECOVER_DELAY__SHIFT: c_uint = 0x8;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_DOWN_ENTER_DELAY__SHIFT: c_uint = 0xe;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_CTRL_EN__SHIFT: c_uint = 0x10;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_LS_EN__SHIFT: c_uint = 0x11;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_DS_EN__SHIFT: c_uint = 0x12;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_SD_EN__SHIFT: c_uint = 0x13;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_IDLE_HYSTERESIS__SHIFT: c_uint = 0x14;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_UP_RECOVER_DELAY__SHIFT: c_uint = 0x18;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_DOWN_ENTER_DELAY__SHIFT: c_uint = 0x1e;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_CTRL_EN_MASK: c_uint = 0x00000001L;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_LS_EN_MASK: c_uint = 0x00000002L;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_DS_EN_MASK: c_uint = 0x00000004L;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_SD_EN_MASK: c_uint = 0x00000008L;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_IDLE_HYSTERESIS_MASK: c_uint = 0x00000070L;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_UP_RECOVER_DELAY_MASK: c_uint = 0x00003F00L;
pub const IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_DOWN_ENTER_DELAY_MASK: c_uint = 0x0000C000L;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_CTRL_EN_MASK: c_uint = 0x00010000L;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_LS_EN_MASK: c_uint = 0x00020000L;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_DS_EN_MASK: c_uint = 0x00040000L;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_SD_EN_MASK: c_uint = 0x00080000L;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_IDLE_HYSTERESIS_MASK: c_uint = 0x00700000L;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_UP_RECOVER_DELAY_MASK: c_uint = 0x3F000000L;
pub const IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_DOWN_ENTER_DELAY_MASK: c_uint = 0xC0000000L;
// IH_VF_RB_STATUS3
pub const IH_VF_RB_STATUS3__RB_OVERFLOW_VF__SHIFT: c_uint = 0x0;
pub const IH_VF_RB_STATUS3__RB_OVERFLOW_VF_MASK: c_uint = 0x0000FFFFL;
// IH_VF_RB_STATUS4
pub const IH_VF_RB_STATUS4__BIF_INTERRUPT_LINE_VF__SHIFT: c_uint = 0x0;
pub const IH_VF_RB_STATUS4__BIF_INTERRUPT_LINE_VF_MASK: c_uint = 0x0000FFFFL;
// IH_VF_RB1_STATUS3
pub const IH_VF_RB1_STATUS3__RB_OVERFLOW_VF__SHIFT: c_uint = 0x0;
pub const IH_VF_RB1_STATUS3__RB_OVERFLOW_VF_MASK: c_uint = 0x0000FFFFL;
// IH_RETRY_INT_CAM_CNTL
pub const IH_RETRY_INT_CAM_CNTL__CAM_SIZE__SHIFT: c_uint = 0x0;
pub const IH_RETRY_INT_CAM_CNTL__BACK_PRESSURE_SKID_VALUE__SHIFT: c_uint = 0x8;
pub const IH_RETRY_INT_CAM_CNTL__ENABLE__SHIFT: c_uint = 0x10;
pub const IH_RETRY_INT_CAM_CNTL__MM_BACK_PRESSURE_ENABLE__SHIFT: c_uint = 0x11;
pub const IH_RETRY_INT_CAM_CNTL__GC_BACK_PRESSURE_ENABLE__SHIFT: c_uint = 0x12;
pub const IH_RETRY_INT_CAM_CNTL__PER_VF_ENTRY_SIZE__SHIFT: c_uint = 0x14;
pub const IH_RETRY_INT_CAM_CNTL__CAM_SIZE_MASK: c_uint = 0x0000001FL;
pub const IH_RETRY_INT_CAM_CNTL__BACK_PRESSURE_SKID_VALUE_MASK: c_uint = 0x00003F00L;
pub const IH_RETRY_INT_CAM_CNTL__ENABLE_MASK: c_uint = 0x00010000L;
pub const IH_RETRY_INT_CAM_CNTL__MM_BACK_PRESSURE_ENABLE_MASK: c_uint = 0x00020000L;
pub const IH_RETRY_INT_CAM_CNTL__GC_BACK_PRESSURE_ENABLE_MASK: c_uint = 0x00040000L;
pub const IH_RETRY_INT_CAM_CNTL__PER_VF_ENTRY_SIZE_MASK: c_uint = 0x00300000L;
// IH_MEM_POWER_CTRL2
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_CTRL_EN__SHIFT: c_uint = 0x0;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_LS_EN__SHIFT: c_uint = 0x1;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_DS_EN__SHIFT: c_uint = 0x2;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_SD_EN__SHIFT: c_uint = 0x3;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_IDLE_HYSTERESIS__SHIFT: c_uint = 0x4;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_UP_RECOVER_DELAY__SHIFT: c_uint = 0x8;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_DOWN_ENTER_DELAY__SHIFT: c_uint = 0xe;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_CTRL_EN_MASK: c_uint = 0x00000001L;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_LS_EN_MASK: c_uint = 0x00000002L;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_DS_EN_MASK: c_uint = 0x00000004L;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_SD_EN_MASK: c_uint = 0x00000008L;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_IDLE_HYSTERESIS_MASK: c_uint = 0x00000070L;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_UP_RECOVER_DELAY_MASK: c_uint = 0x00003F00L;
pub const IH_MEM_POWER_CTRL2__IH_PASID_LUT_MEM_POWER_DOWN_ENTER_DELAY_MASK: c_uint = 0x0000C000L;
// IH_MSI_STORM_CTRL
pub const IH_MSI_STORM_CTRL__DELAY__SHIFT: c_uint = 0x0;
pub const IH_MSI_STORM_CTRL__DELAY_MASK: c_uint = 0x00000FFFL;
// IH_MSI_STORM_CLIENT_INDEX
pub const IH_MSI_STORM_CLIENT_INDEX__INDEX__SHIFT: c_uint = 0x0;
pub const IH_MSI_STORM_CLIENT_INDEX__INDEX_MASK: c_uint = 0x00000007L;
// IH_MSI_STORM_CLIENT_DATA
pub const IH_MSI_STORM_CLIENT_DATA__CLIENT_ID__SHIFT: c_uint = 0x0;
pub const IH_MSI_STORM_CLIENT_DATA__SOURCE_ID__SHIFT: c_uint = 0x8;
pub const IH_MSI_STORM_CLIENT_DATA__SOURCE_ID_MATCH_ENABLE__SHIFT: c_uint = 0x10;
pub const IH_MSI_STORM_CLIENT_DATA__UTCL2_PAGE_FAULT_MATCH_ENABLE__SHIFT: c_uint = 0x11;
pub const IH_MSI_STORM_CLIENT_DATA__ENTRY_VALID__SHIFT: c_uint = 0x1f;
pub const IH_MSI_STORM_CLIENT_DATA__CLIENT_ID_MASK: c_uint = 0x000000FFL;
pub const IH_MSI_STORM_CLIENT_DATA__SOURCE_ID_MASK: c_uint = 0x0000FF00L;
pub const IH_MSI_STORM_CLIENT_DATA__SOURCE_ID_MATCH_ENABLE_MASK: c_uint = 0x00010000L;
pub const IH_MSI_STORM_CLIENT_DATA__UTCL2_PAGE_FAULT_MATCH_ENABLE_MASK: c_uint = 0x00020000L;
pub const IH_MSI_STORM_CLIENT_DATA__ENTRY_VALID_MASK: c_uint = 0x80000000L;
// IH_REGISTER_LAST_PART2
pub const IH_REGISTER_LAST_PART2__RESERVED__SHIFT: c_uint = 0x0;
pub const IH_REGISTER_LAST_PART2__RESERVED_MASK: c_uint = 0xFFFFFFFFL;
// SEM_MAILBOX
pub const SEM_MAILBOX__HOSTPORT__SHIFT: c_uint = 0x0;
pub const SEM_MAILBOX__RESERVED__SHIFT: c_uint = 0x10;
pub const SEM_MAILBOX__HOSTPORT_MASK: c_uint = 0x0000FFFFL;
pub const SEM_MAILBOX__RESERVED_MASK: c_uint = 0xFFFF0000L;
// SEM_MAILBOX_CLEAR
pub const SEM_MAILBOX_CLEAR__CLEAR__SHIFT: c_uint = 0x0;
pub const SEM_MAILBOX_CLEAR__RESERVED__SHIFT: c_uint = 0x10;
pub const SEM_MAILBOX_CLEAR__CLEAR_MASK: c_uint = 0x0000FFFFL;
pub const SEM_MAILBOX_CLEAR__RESERVED_MASK: c_uint = 0xFFFF0000L;
// SEM_REGISTER_LAST_PART2
pub const SEM_REGISTER_LAST_PART2__RESERVED__SHIFT: c_uint = 0x0;
pub const SEM_REGISTER_LAST_PART2__RESERVED_MASK: c_uint = 0xFFFFFFFFL;
// IH_CLIENT_CFG
pub const IH_CLIENT_CFG__TOTAL_CLIENT_NUM__SHIFT: c_uint = 0x0;
pub const IH_CLIENT_CFG__TOTAL_CLIENT_NUM_MASK: c_uint = 0x0000003FL;
// IH_RING1_CLIENT_CFG_INDEX
pub const IH_RING1_CLIENT_CFG_INDEX__INDEX__SHIFT: c_uint = 0x0;
pub const IH_RING1_CLIENT_CFG_INDEX__INDEX_MASK: c_uint = 0x00000007L;
// IH_RING1_CLIENT_CFG_DATA
pub const IH_RING1_CLIENT_CFG_DATA__CLIENT_ID__SHIFT: c_uint = 0x0;
pub const IH_RING1_CLIENT_CFG_DATA__SOURCE_ID__SHIFT: c_uint = 0x8;
pub const IH_RING1_CLIENT_CFG_DATA__SOURCE_ID_MATCH_ENABLE__SHIFT: c_uint = 0x10;
pub const IH_RING1_CLIENT_CFG_DATA__CLIENT_ID_MASK: c_uint = 0x000000FFL;
pub const IH_RING1_CLIENT_CFG_DATA__SOURCE_ID_MASK: c_uint = 0x0000FF00L;
pub const IH_RING1_CLIENT_CFG_DATA__SOURCE_ID_MATCH_ENABLE_MASK: c_uint = 0x00010000L;
// IH_CLIENT_CFG_INDEX
pub const IH_CLIENT_CFG_INDEX__INDEX__SHIFT: c_uint = 0x0;
pub const IH_CLIENT_CFG_INDEX__INDEX_MASK: c_uint = 0x0000001FL;
// IH_CLIENT_CFG_DATA
pub const IH_CLIENT_CFG_DATA__CLIENT_TYPE__SHIFT: c_uint = 0x12;
pub const IH_CLIENT_CFG_DATA__VF_RB_SELECT__SHIFT: c_uint = 0x16;
pub const IH_CLIENT_CFG_DATA__INTERFACE_TYPE__SHIFT: c_uint = 0x19;
pub const IH_CLIENT_CFG_DATA__CLIENT_TYPE_MASK: c_uint = 0x000C0000L;
pub const IH_CLIENT_CFG_DATA__VF_RB_SELECT_MASK: c_uint = 0x00C00000L;
pub const IH_CLIENT_CFG_DATA__INTERFACE_TYPE_MASK: c_uint = 0x02000000L;
// IH_CID_REMAP_INDEX
pub const IH_CID_REMAP_INDEX__INDEX__SHIFT: c_uint = 0x0;
pub const IH_CID_REMAP_INDEX__INDEX_MASK: c_uint = 0x00000003L;
// IH_CID_REMAP_DATA
pub const IH_CID_REMAP_DATA__CLIENT_ID__SHIFT: c_uint = 0x0;
pub const IH_CID_REMAP_DATA__INITIATOR_ID__SHIFT: c_uint = 0x8;
pub const IH_CID_REMAP_DATA__CLIENT_ID_REMAP__SHIFT: c_uint = 0x18;
pub const IH_CID_REMAP_DATA__CLIENT_ID_MASK: c_uint = 0x000000FFL;
pub const IH_CID_REMAP_DATA__INITIATOR_ID_MASK: c_uint = 0x0003FF00L;
pub const IH_CID_REMAP_DATA__CLIENT_ID_REMAP_MASK: c_uint = 0xFF000000L;
// IH_CHICKEN
pub const IH_CHICKEN__CROSS_TRIGGER_ENABLE__SHIFT: c_uint = 0x2;
pub const IH_CHICKEN__MC_SPACE_FBPA_ENABLE__SHIFT: c_uint = 0x3;
pub const IH_CHICKEN__MC_SPACE_GPA_ENABLE__SHIFT: c_uint = 0x4;
pub const IH_CHICKEN__CROSS_TRIGGER_ENABLE_MASK: c_uint = 0x00000004L;
pub const IH_CHICKEN__MC_SPACE_FBPA_ENABLE_MASK: c_uint = 0x00000008L;
pub const IH_CHICKEN__MC_SPACE_GPA_ENABLE_MASK: c_uint = 0x00000010L;
// IH_INT_DROP_CNTL
pub const IH_INT_DROP_CNTL__INT_DROP_EN__SHIFT: c_uint = 0x0;
pub const IH_INT_DROP_CNTL__CLIENT_ID_MATCH_EN__SHIFT: c_uint = 0x1;
pub const IH_INT_DROP_CNTL__SOURCE_ID_MATCH_EN__SHIFT: c_uint = 0x2;
pub const IH_INT_DROP_CNTL__VF_ID_MATCH_EN__SHIFT: c_uint = 0x3;
pub const IH_INT_DROP_CNTL__VF_MATCH_EN__SHIFT: c_uint = 0x4;
pub const IH_INT_DROP_CNTL__CONTEXT_ID_MATCH_EN__SHIFT: c_uint = 0x5;
pub const IH_INT_DROP_CNTL__INT_DROP_MODE__SHIFT: c_uint = 0x6;
pub const IH_INT_DROP_CNTL__UTCL2_RETRY_INT_DROP_EN__SHIFT: c_uint = 0x8;
pub const IH_INT_DROP_CNTL__INT_DROPPED__SHIFT: c_uint = 0x10;
pub const IH_INT_DROP_CNTL__INT_DROP_EN_MASK: c_uint = 0x00000001L;
pub const IH_INT_DROP_CNTL__CLIENT_ID_MATCH_EN_MASK: c_uint = 0x00000002L;
pub const IH_INT_DROP_CNTL__SOURCE_ID_MATCH_EN_MASK: c_uint = 0x00000004L;
pub const IH_INT_DROP_CNTL__VF_ID_MATCH_EN_MASK: c_uint = 0x00000008L;
pub const IH_INT_DROP_CNTL__VF_MATCH_EN_MASK: c_uint = 0x00000010L;
pub const IH_INT_DROP_CNTL__CONTEXT_ID_MATCH_EN_MASK: c_uint = 0x00000020L;
pub const IH_INT_DROP_CNTL__INT_DROP_MODE_MASK: c_uint = 0x000000C0L;
pub const IH_INT_DROP_CNTL__UTCL2_RETRY_INT_DROP_EN_MASK: c_uint = 0x00000100L;
pub const IH_INT_DROP_CNTL__INT_DROPPED_MASK: c_uint = 0x00010000L;
// IH_INT_DROP_MATCH_VALUE0
pub const IH_INT_DROP_MATCH_VALUE0__CLIENT_ID_MATCH_VALUE__SHIFT: c_uint = 0x0;
pub const IH_INT_DROP_MATCH_VALUE0__SOURCE_ID_MATCH_VALUE__SHIFT: c_uint = 0x8;
pub const IH_INT_DROP_MATCH_VALUE0__VF_ID_MATCH_VALUE__SHIFT: c_uint = 0x10;
pub const IH_INT_DROP_MATCH_VALUE0__VF_MATCH_VALUE__SHIFT: c_uint = 0x17;
pub const IH_INT_DROP_MATCH_VALUE0__CONTEXT_ID_39_32_MATCH_VALUE__SHIFT: c_uint = 0x18;
pub const IH_INT_DROP_MATCH_VALUE0__CLIENT_ID_MATCH_VALUE_MASK: c_uint = 0x000000FFL;
pub const IH_INT_DROP_MATCH_VALUE0__SOURCE_ID_MATCH_VALUE_MASK: c_uint = 0x0000FF00L;
pub const IH_INT_DROP_MATCH_VALUE0__VF_ID_MATCH_VALUE_MASK: c_uint = 0x001F0000L;
pub const IH_INT_DROP_MATCH_VALUE0__VF_MATCH_VALUE_MASK: c_uint = 0x00800000L;
pub const IH_INT_DROP_MATCH_VALUE0__CONTEXT_ID_39_32_MATCH_VALUE_MASK: c_uint = 0xFF000000L;
// IH_INT_DROP_MATCH_VALUE1
pub const IH_INT_DROP_MATCH_VALUE1__CONTEXT_ID_31_0_MATCH_VALUE__SHIFT: c_uint = 0x0;
pub const IH_INT_DROP_MATCH_VALUE1__CONTEXT_ID_31_0_MATCH_VALUE_MASK: c_uint = 0xFFFFFFFFL;
// IH_INT_DROP_MATCH_MASK0
pub const IH_INT_DROP_MATCH_MASK0__CLIENT_ID_MATCH_MASK__SHIFT: c_uint = 0x0;
pub const IH_INT_DROP_MATCH_MASK0__SOURCE_ID_MATCH_MASK__SHIFT: c_uint = 0x8;
pub const IH_INT_DROP_MATCH_MASK0__VF_ID_MATCH_MASK__SHIFT: c_uint = 0x10;
pub const IH_INT_DROP_MATCH_MASK0__VF_MATCH_MASK__SHIFT: c_uint = 0x17;
pub const IH_INT_DROP_MATCH_MASK0__CONTEXT_ID_39_32_MATCH_MASK__SHIFT: c_uint = 0x18;
pub const IH_INT_DROP_MATCH_MASK0__CLIENT_ID_MATCH_MASK_MASK: c_uint = 0x000000FFL;
pub const IH_INT_DROP_MATCH_MASK0__SOURCE_ID_MATCH_MASK_MASK: c_uint = 0x0000FF00L;
pub const IH_INT_DROP_MATCH_MASK0__VF_ID_MATCH_MASK_MASK: c_uint = 0x001F0000L;
pub const IH_INT_DROP_MATCH_MASK0__VF_MATCH_MASK_MASK: c_uint = 0x00800000L;
pub const IH_INT_DROP_MATCH_MASK0__CONTEXT_ID_39_32_MATCH_MASK_MASK: c_uint = 0xFF000000L;
// IH_INT_DROP_MATCH_MASK1
pub const IH_INT_DROP_MATCH_MASK1__CONTEXT_ID_31_0_MATCH_MASK__SHIFT: c_uint = 0x0;
pub const IH_INT_DROP_MATCH_MASK1__CONTEXT_ID_31_0_MATCH_MASK_MASK: c_uint = 0xFFFFFFFFL;
// IH_REGISTER_LAST_PART1
pub const IH_REGISTER_LAST_PART1__RESERVED__SHIFT: c_uint = 0x0;
pub const IH_REGISTER_LAST_PART1__RESERVED_MASK: c_uint = 0xFFFFFFFFL;
