//! Automatically rewritten from C Header to Rust Module
//! Source: sound/pci/oxygen/oxygen_regs.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0

// Macro flag: #define OXYGEN_REGS_H_INCLUDED
// recording channel A
pub const OXYGEN_DMA_A_ADDRESS: c_uint = 0x00	/* 32-bit base address */;
pub const OXYGEN_DMA_A_COUNT: c_uint = 0x04	/* buffer counter (dwords) */;
pub const OXYGEN_DMA_A_TCOUNT: c_uint = 0x06	/* interrupt counter (dwords) */;
// recording channel B
pub const OXYGEN_DMA_B_ADDRESS: c_uint = 0x08;
pub const OXYGEN_DMA_B_COUNT: c_uint = 0x0c;
pub const OXYGEN_DMA_B_TCOUNT: c_uint = 0x0e;
// recording channel C
pub const OXYGEN_DMA_C_ADDRESS: c_uint = 0x10;
pub const OXYGEN_DMA_C_COUNT: c_uint = 0x14;
pub const OXYGEN_DMA_C_TCOUNT: c_uint = 0x16;
// SPDIF playback channel
pub const OXYGEN_DMA_SPDIF_ADDRESS: c_uint = 0x18;
pub const OXYGEN_DMA_SPDIF_COUNT: c_uint = 0x1c;
pub const OXYGEN_DMA_SPDIF_TCOUNT: c_uint = 0x1e;
// multichannel playback channel
pub const OXYGEN_DMA_MULTICH_ADDRESS: c_uint = 0x20;
pub const OXYGEN_DMA_MULTICH_COUNT: c_uint = 0x24	/* 24 bits */;
pub const OXYGEN_DMA_MULTICH_TCOUNT: c_uint = 0x28	/* 24 bits */;
// AC'97 (front panel) playback channel
pub const OXYGEN_DMA_AC97_ADDRESS: c_uint = 0x30;
pub const OXYGEN_DMA_AC97_COUNT: c_uint = 0x34;
pub const OXYGEN_DMA_AC97_TCOUNT: c_uint = 0x36;
// all registers 0x00..0x36 return current position on read
pub const OXYGEN_DMA_STATUS: c_uint = 0x40	/* 1 = running, 0 = stop */;
pub const OXYGEN_CHANNEL_A: c_uint = 0x01;
pub const OXYGEN_CHANNEL_B: c_uint = 0x02;
pub const OXYGEN_CHANNEL_C: c_uint = 0x04;
pub const OXYGEN_CHANNEL_SPDIF: c_uint = 0x08;
pub const OXYGEN_CHANNEL_MULTICH: c_uint = 0x10;
pub const OXYGEN_CHANNEL_AC97: c_uint = 0x20;
pub const OXYGEN_DMA_PAUSE: c_uint = 0x41	/* 1 = pause */;
// OXYGEN_CHANNEL_*
pub const OXYGEN_DMA_RESET: c_uint = 0x42;
// OXYGEN_CHANNEL_*
pub const OXYGEN_PLAY_CHANNELS: c_uint = 0x43;
pub const OXYGEN_PLAY_CHANNELS_MASK: c_uint = 0x03;
pub const OXYGEN_PLAY_CHANNELS_2: c_uint = 0x00;
pub const OXYGEN_PLAY_CHANNELS_4: c_uint = 0x01;
pub const OXYGEN_PLAY_CHANNELS_6: c_uint = 0x02;
pub const OXYGEN_PLAY_CHANNELS_8: c_uint = 0x03;
pub const OXYGEN_DMA_A_BURST_MASK: c_uint = 0x04;
pub const OXYGEN_DMA_A_BURST_8: c_uint = 0x00	/* dwords */;
pub const OXYGEN_DMA_A_BURST_16: c_uint = 0x04;
pub const OXYGEN_DMA_MULTICH_BURST_MASK: c_uint = 0x08;
pub const OXYGEN_DMA_MULTICH_BURST_8: c_uint = 0x00;
pub const OXYGEN_DMA_MULTICH_BURST_16: c_uint = 0x08;
pub const OXYGEN_INTERRUPT_MASK: c_uint = 0x44;
// OXYGEN_CHANNEL_*
pub const OXYGEN_INT_SPDIF_IN_DETECT: c_uint = 0x0100;
pub const OXYGEN_INT_MCU: c_uint = 0x0200;
pub const OXYGEN_INT_2WIRE: c_uint = 0x0400;
pub const OXYGEN_INT_GPIO: c_uint = 0x0800;
pub const OXYGEN_INT_MCB: c_uint = 0x2000;
pub const OXYGEN_INT_AC97: c_uint = 0x4000;
pub const OXYGEN_INTERRUPT_STATUS: c_uint = 0x46;
// OXYGEN_CHANNEL_* amd OXYGEN_INT_*
pub const OXYGEN_INT_MIDI: c_uint = 0x1000;
pub const OXYGEN_MISC: c_uint = 0x48;
pub const OXYGEN_MISC_WRITE_PCI_SUBID: c_uint = 0x01;
pub const OXYGEN_MISC_LATENCY_3F: c_uint = 0x02;
pub const OXYGEN_MISC_REC_C_FROM_SPDIF: c_uint = 0x04;
pub const OXYGEN_MISC_REC_B_FROM_AC97: c_uint = 0x08;
pub const OXYGEN_MISC_REC_A_FROM_MULTICH: c_uint = 0x10;
pub const OXYGEN_MISC_PCI_MEM_W_1_CLOCK: c_uint = 0x20;
pub const OXYGEN_MISC_MIDI: c_uint = 0x40;
pub const OXYGEN_MISC_CRYSTAL_MASK: c_uint = 0x80;
pub const OXYGEN_MISC_CRYSTAL_24576: c_uint = 0x00;
pub const OXYGEN_MISC_CRYSTAL_27: c_uint = 0x80	/* MHz */;
pub const OXYGEN_REC_FORMAT: c_uint = 0x4a;
pub const OXYGEN_REC_FORMAT_A_MASK: c_uint = 0x03;
pub const OXYGEN_REC_FORMAT_A_SHIFT: c_int = 0;
pub const OXYGEN_REC_FORMAT_B_MASK: c_uint = 0x0c;
pub const OXYGEN_REC_FORMAT_B_SHIFT: c_int = 2;
pub const OXYGEN_REC_FORMAT_C_MASK: c_uint = 0x30;
pub const OXYGEN_REC_FORMAT_C_SHIFT: c_int = 4;
pub const OXYGEN_FORMAT_16: c_uint = 0x00;
pub const OXYGEN_FORMAT_24: c_uint = 0x01;
pub const OXYGEN_FORMAT_32: c_uint = 0x02;
pub const OXYGEN_PLAY_FORMAT: c_uint = 0x4b;
pub const OXYGEN_SPDIF_FORMAT_MASK: c_uint = 0x03;
pub const OXYGEN_SPDIF_FORMAT_SHIFT: c_int = 0;
pub const OXYGEN_MULTICH_FORMAT_MASK: c_uint = 0x0c;
pub const OXYGEN_MULTICH_FORMAT_SHIFT: c_int = 2;
// OXYGEN_FORMAT_*
pub const OXYGEN_REC_CHANNELS: c_uint = 0x4c;
pub const OXYGEN_REC_CHANNELS_MASK: c_uint = 0x07;
pub const OXYGEN_REC_CHANNELS_2_2_2: c_uint = 0x00	/* DMA A, B, C */;
pub const OXYGEN_REC_CHANNELS_4_2_2: c_uint = 0x01;
pub const OXYGEN_REC_CHANNELS_6_0_2: c_uint = 0x02;
pub const OXYGEN_REC_CHANNELS_6_2_0: c_uint = 0x03;
pub const OXYGEN_REC_CHANNELS_8_0_0: c_uint = 0x04;
pub const OXYGEN_FUNCTION: c_uint = 0x50;
pub const OXYGEN_FUNCTION_CLOCK_MASK: c_uint = 0x01;
pub const OXYGEN_FUNCTION_CLOCK_PLL: c_uint = 0x00;
pub const OXYGEN_FUNCTION_CLOCK_CRYSTAL: c_uint = 0x01;
pub const OXYGEN_FUNCTION_RESET_CODEC: c_uint = 0x02;
pub const OXYGEN_FUNCTION_RESET_POL: c_uint = 0x04;
pub const OXYGEN_FUNCTION_PWDN: c_uint = 0x08;
pub const OXYGEN_FUNCTION_PWDN_EN: c_uint = 0x10;
pub const OXYGEN_FUNCTION_PWDN_POL: c_uint = 0x20;
pub const OXYGEN_FUNCTION_2WIRE_SPI_MASK: c_uint = 0x40;
pub const OXYGEN_FUNCTION_SPI: c_uint = 0x00;
pub const OXYGEN_FUNCTION_2WIRE: c_uint = 0x40;
pub const OXYGEN_FUNCTION_ENABLE_SPI_4_5: c_uint = 0x80	/* 0 = EEPROM */;
pub const OXYGEN_I2S_MULTICH_FORMAT: c_uint = 0x60;
pub const OXYGEN_I2S_RATE_MASK: c_uint = 0x0007	/* LRCK */;
pub const OXYGEN_RATE_32000: c_uint = 0x0000;
pub const OXYGEN_RATE_44100: c_uint = 0x0001;
pub const OXYGEN_RATE_48000: c_uint = 0x0002;
pub const OXYGEN_RATE_64000: c_uint = 0x0003;
pub const OXYGEN_RATE_88200: c_uint = 0x0004;
pub const OXYGEN_RATE_96000: c_uint = 0x0005;
pub const OXYGEN_RATE_176400: c_uint = 0x0006;
pub const OXYGEN_RATE_192000: c_uint = 0x0007;
pub const OXYGEN_I2S_FORMAT_MASK: c_uint = 0x0008;
pub const OXYGEN_I2S_FORMAT_I2S: c_uint = 0x0000;
pub const OXYGEN_I2S_FORMAT_LJUST: c_uint = 0x0008;
pub const OXYGEN_I2S_MCLK_MASK: c_uint = 0x0030	/* MCLK/LRCK */;
pub const OXYGEN_I2S_MCLK_SHIFT: c_int = 4;
pub const MCLK_128: c_int = 0;
pub const MCLK_256: c_int = 1;
pub const MCLK_512: c_int = 2;

pub const OXYGEN_I2S_BITS_MASK: c_uint = 0x00c0;
pub const OXYGEN_I2S_BITS_16: c_uint = 0x0000;
pub const OXYGEN_I2S_BITS_20: c_uint = 0x0040;
pub const OXYGEN_I2S_BITS_24: c_uint = 0x0080;
pub const OXYGEN_I2S_BITS_32: c_uint = 0x00c0;
pub const OXYGEN_I2S_MASTER: c_uint = 0x0100;
pub const OXYGEN_I2S_BCLK_MASK: c_uint = 0x0600	/* BCLK/LRCK */;
pub const OXYGEN_I2S_BCLK_64: c_uint = 0x0000;
pub const OXYGEN_I2S_BCLK_128: c_uint = 0x0200;
pub const OXYGEN_I2S_BCLK_256: c_uint = 0x0400;
pub const OXYGEN_I2S_MUTE_MCLK: c_uint = 0x0800;
pub const OXYGEN_I2S_A_FORMAT: c_uint = 0x62;
pub const OXYGEN_I2S_B_FORMAT: c_uint = 0x64;
pub const OXYGEN_I2S_C_FORMAT: c_uint = 0x66;
// like OXYGEN_I2S_MULTICH_FORMAT
pub const OXYGEN_SPDIF_CONTROL: c_uint = 0x70;
pub const OXYGEN_SPDIF_OUT_ENABLE: c_uint = 0x00000002;
pub const OXYGEN_SPDIF_LOOPBACK: c_uint = 0x00000004	/* in to out */;
pub const OXYGEN_SPDIF_SENSE_MASK: c_uint = 0x00000008;
pub const OXYGEN_SPDIF_LOCK_MASK: c_uint = 0x00000010;
pub const OXYGEN_SPDIF_RATE_MASK: c_uint = 0x00000020;
pub const OXYGEN_SPDIF_SPDVALID: c_uint = 0x00000040;
pub const OXYGEN_SPDIF_SENSE_PAR: c_uint = 0x00000200;
pub const OXYGEN_SPDIF_LOCK_PAR: c_uint = 0x00000400;
pub const OXYGEN_SPDIF_SENSE_STATUS: c_uint = 0x00000800;
pub const OXYGEN_SPDIF_LOCK_STATUS: c_uint = 0x00001000;
pub const OXYGEN_SPDIF_SENSE_INT: c_uint = 0x00002000	/* r/wc */;
pub const OXYGEN_SPDIF_LOCK_INT: c_uint = 0x00004000	/* r/wc */;
pub const OXYGEN_SPDIF_RATE_INT: c_uint = 0x00008000	/* r/wc */;
pub const OXYGEN_SPDIF_IN_CLOCK_MASK: c_uint = 0x00010000;
pub const OXYGEN_SPDIF_IN_CLOCK_96: c_uint = 0x00000000	/* <= 96 kHz */;
pub const OXYGEN_SPDIF_IN_CLOCK_192: c_uint = 0x00010000	/* > 96 kHz */;
pub const OXYGEN_SPDIF_OUT_RATE_MASK: c_uint = 0x07000000;
pub const OXYGEN_SPDIF_OUT_RATE_SHIFT: c_int = 24;
// OXYGEN_RATE_* << OXYGEN_SPDIF_OUT_RATE_SHIFT
pub const OXYGEN_SPDIF_OUTPUT_BITS: c_uint = 0x74;
pub const OXYGEN_SPDIF_NONAUDIO: c_uint = 0x00000002;
pub const OXYGEN_SPDIF_C: c_uint = 0x00000004;
pub const OXYGEN_SPDIF_PREEMPHASIS: c_uint = 0x00000008;
pub const OXYGEN_SPDIF_CATEGORY_MASK: c_uint = 0x000007f0;
pub const OXYGEN_SPDIF_CATEGORY_SHIFT: c_int = 4;
pub const OXYGEN_SPDIF_ORIGINAL: c_uint = 0x00000800;
pub const OXYGEN_SPDIF_CS_RATE_MASK: c_uint = 0x0000f000;
pub const OXYGEN_SPDIF_CS_RATE_SHIFT: c_int = 12;
pub const OXYGEN_SPDIF_V: c_uint = 0x00010000	/* 0 = valid */;
pub const OXYGEN_SPDIF_INPUT_BITS: c_uint = 0x78;
// 32 bits, IEC958_AES_*
pub const OXYGEN_EEPROM_CONTROL: c_uint = 0x80;
pub const OXYGEN_EEPROM_ADDRESS_MASK: c_uint = 0x7f;
pub const OXYGEN_EEPROM_DIR_MASK: c_uint = 0x80;
pub const OXYGEN_EEPROM_DIR_READ: c_uint = 0x00;
pub const OXYGEN_EEPROM_DIR_WRITE: c_uint = 0x80;
pub const OXYGEN_EEPROM_STATUS: c_uint = 0x81;
pub const OXYGEN_EEPROM_VALID: c_uint = 0x40;
pub const OXYGEN_EEPROM_BUSY: c_uint = 0x80;
pub const OXYGEN_EEPROM_DATA: c_uint = 0x82	/* 16 bits */;
pub const OXYGEN_2WIRE_CONTROL: c_uint = 0x90;
pub const OXYGEN_2WIRE_DIR_MASK: c_uint = 0x01;
pub const OXYGEN_2WIRE_DIR_WRITE: c_uint = 0x00;
pub const OXYGEN_2WIRE_DIR_READ: c_uint = 0x01;
pub const OXYGEN_2WIRE_ADDRESS_MASK: c_uint = 0xfe	/* slave device address */;
pub const OXYGEN_2WIRE_ADDRESS_SHIFT: c_int = 1;
pub const OXYGEN_2WIRE_MAP: c_uint = 0x91	/* address, 8 bits */;
pub const OXYGEN_2WIRE_DATA: c_uint = 0x92	/* data, 16 bits */;
pub const OXYGEN_2WIRE_BUS_STATUS: c_uint = 0x94;
pub const OXYGEN_2WIRE_BUSY: c_uint = 0x0001;
pub const OXYGEN_2WIRE_LENGTH_MASK: c_uint = 0x0002;
pub const OXYGEN_2WIRE_LENGTH_8: c_uint = 0x0000;
pub const OXYGEN_2WIRE_LENGTH_16: c_uint = 0x0002;
pub const OXYGEN_2WIRE_MANUAL_READ: c_uint = 0x0004	/* 0 = auto read */;
pub const OXYGEN_2WIRE_WRITE_MAP_ONLY: c_uint = 0x0008;
pub const OXYGEN_2WIRE_SLAVE_AD_MASK: c_uint = 0x0030	/* AD0, AD1 */;
pub const OXYGEN_2WIRE_INTERRUPT_MASK: c_uint = 0x0040	/* 0 = int. if not responding */;
pub const OXYGEN_2WIRE_SLAVE_NO_RESPONSE: c_uint = 0x0080;
pub const OXYGEN_2WIRE_SPEED_MASK: c_uint = 0x0100;
pub const OXYGEN_2WIRE_SPEED_STANDARD: c_uint = 0x0000;
pub const OXYGEN_2WIRE_SPEED_FAST: c_uint = 0x0100;
pub const OXYGEN_2WIRE_CLOCK_SYNC: c_uint = 0x0200;
pub const OXYGEN_2WIRE_BUS_RESET: c_uint = 0x0400;
pub const OXYGEN_SPI_CONTROL: c_uint = 0x98;
pub const OXYGEN_SPI_BUSY: c_uint = 0x01	/* read */;
pub const OXYGEN_SPI_TRIGGER: c_uint = 0x01	/* write */;
pub const OXYGEN_SPI_DATA_LENGTH_MASK: c_uint = 0x02;
pub const OXYGEN_SPI_DATA_LENGTH_2: c_uint = 0x00;
pub const OXYGEN_SPI_DATA_LENGTH_3: c_uint = 0x02;
pub const OXYGEN_SPI_CLOCK_MASK: c_uint = 0x0c;
pub const OXYGEN_SPI_CLOCK_160: c_uint = 0x00	/* ns */;
pub const OXYGEN_SPI_CLOCK_320: c_uint = 0x04;
pub const OXYGEN_SPI_CLOCK_640: c_uint = 0x08;
pub const OXYGEN_SPI_CLOCK_1280: c_uint = 0x0c;
pub const OXYGEN_SPI_CODEC_MASK: c_uint = 0x70	/* 0..5 */;
pub const OXYGEN_SPI_CODEC_SHIFT: c_int = 4;
pub const OXYGEN_SPI_CEN_MASK: c_uint = 0x80;
pub const OXYGEN_SPI_CEN_LATCH_CLOCK_LO: c_uint = 0x00;
pub const OXYGEN_SPI_CEN_LATCH_CLOCK_HI: c_uint = 0x80;
pub const OXYGEN_SPI_DATA1: c_uint = 0x99;
pub const OXYGEN_SPI_DATA2: c_uint = 0x9a;
pub const OXYGEN_SPI_DATA3: c_uint = 0x9b;
pub const OXYGEN_MPU401: c_uint = 0xa0;
pub const OXYGEN_MPU401_CONTROL: c_uint = 0xa2;
pub const OXYGEN_MPU401_LOOPBACK: c_uint = 0x01	/* TXD to RXD */;
pub const OXYGEN_GPI_DATA: c_uint = 0xa4;
// bits 0..5 = pin XGPI0..XGPI5
pub const OXYGEN_GPI_INTERRUPT_MASK: c_uint = 0xa5;
// bits 0..5, 1 = enable
pub const OXYGEN_GPIO_DATA: c_uint = 0xa6;
// bits 0..9
pub const OXYGEN_GPIO_CONTROL: c_uint = 0xa8;
// bits 0..9, 0 = input, 1 = output
pub const OXYGEN_GPIO1_XSLAVE_RDY: c_uint = 0x8000;
pub const OXYGEN_GPIO_INTERRUPT_MASK: c_uint = 0xaa;
// bits 0..9, 1 = enable
pub const OXYGEN_DEVICE_SENSE: c_uint = 0xac;
pub const OXYGEN_HEAD_PHONE_DETECT: c_uint = 0x01;
pub const OXYGEN_HEAD_PHONE_MASK: c_uint = 0x06;
pub const OXYGEN_HEAD_PHONE_PASSIVE_SPK: c_uint = 0x00;
pub const OXYGEN_HEAD_PHONE_HP: c_uint = 0x02;
pub const OXYGEN_HEAD_PHONE_ACTIVE_SPK: c_uint = 0x04;
pub const OXYGEN_MCU_2WIRE_DATA: c_uint = 0xb0;
pub const OXYGEN_MCU_2WIRE_MAP: c_uint = 0xb2;
pub const OXYGEN_MCU_2WIRE_STATUS: c_uint = 0xb3;
pub const OXYGEN_MCU_2WIRE_BUSY: c_uint = 0x01;
pub const OXYGEN_MCU_2WIRE_LENGTH_MASK: c_uint = 0x06;
pub const OXYGEN_MCU_2WIRE_LENGTH_1: c_uint = 0x00;
pub const OXYGEN_MCU_2WIRE_LENGTH_2: c_uint = 0x02;
pub const OXYGEN_MCU_2WIRE_LENGTH_3: c_uint = 0x04;
pub const OXYGEN_MCU_2WIRE_WRITE: c_uint = 0x08	/* r/wc */;
pub const OXYGEN_MCU_2WIRE_READ: c_uint = 0x10	/* r/wc */;
pub const OXYGEN_MCU_2WIRE_DRV_XACT_FAIL: c_uint = 0x20	/* r/wc */;
pub const OXYGEN_MCU_2WIRE_RESET: c_uint = 0x40;
pub const OXYGEN_MCU_2WIRE_CONTROL: c_uint = 0xb4;
pub const OXYGEN_MCU_2WIRE_DRV_ACK: c_uint = 0x01;
pub const OXYGEN_MCU_2WIRE_DRV_XACT: c_uint = 0x02;
pub const OXYGEN_MCU_2WIRE_INT_MASK: c_uint = 0x04;
pub const OXYGEN_MCU_2WIRE_SYNC_MASK: c_uint = 0x08;
pub const OXYGEN_MCU_2WIRE_SYNC_RDY_PIN: c_uint = 0x00;
pub const OXYGEN_MCU_2WIRE_SYNC_DATA: c_uint = 0x08;
pub const OXYGEN_MCU_2WIRE_ADDRESS_MASK: c_uint = 0x30;
pub const OXYGEN_MCU_2WIRE_ADDRESS_10: c_uint = 0x00;
pub const OXYGEN_MCU_2WIRE_ADDRESS_12: c_uint = 0x10;
pub const OXYGEN_MCU_2WIRE_ADDRESS_14: c_uint = 0x20;
pub const OXYGEN_MCU_2WIRE_ADDRESS_16: c_uint = 0x30;
pub const OXYGEN_MCU_2WIRE_INT_POL: c_uint = 0x40;
pub const OXYGEN_MCU_2WIRE_SYNC_ENABLE: c_uint = 0x80;
pub const OXYGEN_PLAY_ROUTING: c_uint = 0xc0;
pub const OXYGEN_PLAY_MUTE01: c_uint = 0x0001;
pub const OXYGEN_PLAY_MUTE23: c_uint = 0x0002;
pub const OXYGEN_PLAY_MUTE45: c_uint = 0x0004;
pub const OXYGEN_PLAY_MUTE67: c_uint = 0x0008;
pub const OXYGEN_PLAY_MUTE_MASK: c_uint = 0x000f;
pub const OXYGEN_PLAY_MULTICH_MASK: c_uint = 0x0010;
pub const OXYGEN_PLAY_MULTICH_I2S_DAC: c_uint = 0x0000;
pub const OXYGEN_PLAY_MULTICH_AC97: c_uint = 0x0010;
pub const OXYGEN_PLAY_SPDIF_MASK: c_uint = 0x00e0;
pub const OXYGEN_PLAY_SPDIF_SPDIF: c_uint = 0x0000;
pub const OXYGEN_PLAY_SPDIF_MULTICH_01: c_uint = 0x0020;
pub const OXYGEN_PLAY_SPDIF_MULTICH_23: c_uint = 0x0040;
pub const OXYGEN_PLAY_SPDIF_MULTICH_45: c_uint = 0x0060;
pub const OXYGEN_PLAY_SPDIF_MULTICH_67: c_uint = 0x0080;
pub const OXYGEN_PLAY_SPDIF_REC_A: c_uint = 0x00a0;
pub const OXYGEN_PLAY_SPDIF_REC_B: c_uint = 0x00c0;
pub const OXYGEN_PLAY_SPDIF_I2S_ADC_3: c_uint = 0x00e0;
pub const OXYGEN_PLAY_DAC0_SOURCE_MASK: c_uint = 0x0300;
pub const OXYGEN_PLAY_DAC0_SOURCE_SHIFT: c_int = 8;
pub const OXYGEN_PLAY_DAC1_SOURCE_MASK: c_uint = 0x0c00;
pub const OXYGEN_PLAY_DAC1_SOURCE_SHIFT: c_int = 10;
pub const OXYGEN_PLAY_DAC2_SOURCE_MASK: c_uint = 0x3000;
pub const OXYGEN_PLAY_DAC2_SOURCE_SHIFT: c_int = 12;
pub const OXYGEN_PLAY_DAC3_SOURCE_MASK: c_uint = 0xc000;
pub const OXYGEN_PLAY_DAC3_SOURCE_SHIFT: c_int = 14;
pub const OXYGEN_REC_ROUTING: c_uint = 0xc2;
pub const OXYGEN_MUTE_I2S_ADC_1: c_uint = 0x01;
pub const OXYGEN_MUTE_I2S_ADC_2: c_uint = 0x02;
pub const OXYGEN_MUTE_I2S_ADC_3: c_uint = 0x04;
pub const OXYGEN_REC_A_ROUTE_MASK: c_uint = 0x08;
pub const OXYGEN_REC_A_ROUTE_I2S_ADC_1: c_uint = 0x00;
pub const OXYGEN_REC_A_ROUTE_AC97_0: c_uint = 0x08;
pub const OXYGEN_REC_B_ROUTE_MASK: c_uint = 0x10;
pub const OXYGEN_REC_B_ROUTE_I2S_ADC_2: c_uint = 0x00;
pub const OXYGEN_REC_B_ROUTE_AC97_1: c_uint = 0x10;
pub const OXYGEN_REC_C_ROUTE_MASK: c_uint = 0x20;
pub const OXYGEN_REC_C_ROUTE_SPDIF: c_uint = 0x00;
pub const OXYGEN_REC_C_ROUTE_I2S_ADC_3: c_uint = 0x20;
pub const OXYGEN_ADC_MONITOR: c_uint = 0xc3;
pub const OXYGEN_ADC_MONITOR_A: c_uint = 0x01;
pub const OXYGEN_ADC_MONITOR_A_HALF_VOL: c_uint = 0x02;
pub const OXYGEN_ADC_MONITOR_B: c_uint = 0x04;
pub const OXYGEN_ADC_MONITOR_B_HALF_VOL: c_uint = 0x08;
pub const OXYGEN_ADC_MONITOR_C: c_uint = 0x10;
pub const OXYGEN_ADC_MONITOR_C_HALF_VOL: c_uint = 0x20;
pub const OXYGEN_A_MONITOR_ROUTING: c_uint = 0xc4;
pub const OXYGEN_A_MONITOR_ROUTE_0_MASK: c_uint = 0x03;
pub const OXYGEN_A_MONITOR_ROUTE_0_SHIFT: c_int = 0;
pub const OXYGEN_A_MONITOR_ROUTE_1_MASK: c_uint = 0x0c;
pub const OXYGEN_A_MONITOR_ROUTE_1_SHIFT: c_int = 2;
pub const OXYGEN_A_MONITOR_ROUTE_2_MASK: c_uint = 0x30;
pub const OXYGEN_A_MONITOR_ROUTE_2_SHIFT: c_int = 4;
pub const OXYGEN_A_MONITOR_ROUTE_3_MASK: c_uint = 0xc0;
pub const OXYGEN_A_MONITOR_ROUTE_3_SHIFT: c_int = 6;
pub const OXYGEN_AC97_CONTROL: c_uint = 0xd0;
pub const OXYGEN_AC97_COLD_RESET: c_uint = 0x0001;
pub const OXYGEN_AC97_SUSPENDED: c_uint = 0x0002	/* read */;
pub const OXYGEN_AC97_RESUME: c_uint = 0x0002	/* write */;
pub const OXYGEN_AC97_CLOCK_DISABLE: c_uint = 0x0004;
pub const OXYGEN_AC97_NO_CODEC_0: c_uint = 0x0008;
pub const OXYGEN_AC97_CODEC_0: c_uint = 0x0010;
pub const OXYGEN_AC97_CODEC_1: c_uint = 0x0020;
pub const OXYGEN_AC97_INTERRUPT_MASK: c_uint = 0xd2;
pub const OXYGEN_AC97_INT_READ_DONE: c_uint = 0x01;
pub const OXYGEN_AC97_INT_WRITE_DONE: c_uint = 0x02;
pub const OXYGEN_AC97_INT_CODEC_0: c_uint = 0x10;
pub const OXYGEN_AC97_INT_CODEC_1: c_uint = 0x20;
pub const OXYGEN_AC97_INTERRUPT_STATUS: c_uint = 0xd3;
// OXYGEN_AC97_INT_*
pub const OXYGEN_AC97_OUT_CONFIG: c_uint = 0xd4;
pub const OXYGEN_AC97_CODEC1_SLOT3: c_uint = 0x00000001;
pub const OXYGEN_AC97_CODEC1_SLOT3_VSR: c_uint = 0x00000002;
pub const OXYGEN_AC97_CODEC1_SLOT4: c_uint = 0x00000010;
pub const OXYGEN_AC97_CODEC1_SLOT4_VSR: c_uint = 0x00000020;
pub const OXYGEN_AC97_CODEC0_FRONTL: c_uint = 0x00000100;
pub const OXYGEN_AC97_CODEC0_FRONTR: c_uint = 0x00000200;
pub const OXYGEN_AC97_CODEC0_SIDEL: c_uint = 0x00000400;
pub const OXYGEN_AC97_CODEC0_SIDER: c_uint = 0x00000800;
pub const OXYGEN_AC97_CODEC0_CENTER: c_uint = 0x00001000;
pub const OXYGEN_AC97_CODEC0_BASE: c_uint = 0x00002000;
pub const OXYGEN_AC97_CODEC0_REARL: c_uint = 0x00004000;
pub const OXYGEN_AC97_CODEC0_REARR: c_uint = 0x00008000;
pub const OXYGEN_AC97_IN_CONFIG: c_uint = 0xd8;
pub const OXYGEN_AC97_CODEC1_LINEL: c_uint = 0x00000001;
pub const OXYGEN_AC97_CODEC1_LINEL_VSR: c_uint = 0x00000002;
pub const OXYGEN_AC97_CODEC1_LINEL_16: c_uint = 0x00000000;
pub const OXYGEN_AC97_CODEC1_LINEL_18: c_uint = 0x00000004;
pub const OXYGEN_AC97_CODEC1_LINEL_20: c_uint = 0x00000008;
pub const OXYGEN_AC97_CODEC1_LINER: c_uint = 0x00000010;
pub const OXYGEN_AC97_CODEC1_LINER_VSR: c_uint = 0x00000020;
pub const OXYGEN_AC97_CODEC1_LINER_16: c_uint = 0x00000000;
pub const OXYGEN_AC97_CODEC1_LINER_18: c_uint = 0x00000040;
pub const OXYGEN_AC97_CODEC1_LINER_20: c_uint = 0x00000080;
pub const OXYGEN_AC97_CODEC0_LINEL: c_uint = 0x00000100;
pub const OXYGEN_AC97_CODEC0_LINER: c_uint = 0x00000200;
pub const OXYGEN_AC97_REGS: c_uint = 0xdc;
pub const OXYGEN_AC97_REG_DATA_MASK: c_uint = 0x0000ffff;
pub const OXYGEN_AC97_REG_ADDR_MASK: c_uint = 0x007f0000;
pub const OXYGEN_AC97_REG_ADDR_SHIFT: c_int = 16;
pub const OXYGEN_AC97_REG_DIR_MASK: c_uint = 0x00800000;
pub const OXYGEN_AC97_REG_DIR_WRITE: c_uint = 0x00000000;
pub const OXYGEN_AC97_REG_DIR_READ: c_uint = 0x00800000;
pub const OXYGEN_AC97_REG_CODEC_MASK: c_uint = 0x01000000;
pub const OXYGEN_AC97_REG_CODEC_SHIFT: c_int = 24;
pub const OXYGEN_TEST: c_uint = 0xe0;
pub const OXYGEN_TEST_RAM_SUCCEEDED: c_uint = 0x01;
pub const OXYGEN_TEST_PLAYBACK_RAM: c_uint = 0x02;
pub const OXYGEN_TEST_RECORD_RAM: c_uint = 0x04;
pub const OXYGEN_TEST_PLL: c_uint = 0x08;
pub const OXYGEN_TEST_2WIRE_LOOPBACK: c_uint = 0x10;
pub const OXYGEN_DMA_FLUSH: c_uint = 0xe1;
// OXYGEN_CHANNEL_*
pub const OXYGEN_CODEC_VERSION: c_uint = 0xe4;
pub const OXYGEN_CODEC_ID_MASK: c_uint = 0x07;
pub const OXYGEN_REVISION: c_uint = 0xe6;
pub const OXYGEN_PACKAGE_ID_MASK: c_uint = 0x0007;
pub const OXYGEN_PACKAGE_ID_8786: c_uint = 0x0004;
pub const OXYGEN_PACKAGE_ID_8787: c_uint = 0x0006;
pub const OXYGEN_PACKAGE_ID_8788: c_uint = 0x0007;
pub const OXYGEN_REVISION_MASK: c_uint = 0xfff8;
pub const OXYGEN_REVISION_2: c_uint = 0x0008;
pub const OXYGEN_OFFSIN_48K: c_uint = 0xe8;
pub const OXYGEN_OFFSBASE_48K: c_uint = 0xe9;
pub const OXYGEN_OFFSBASE_MASK: c_uint = 0x0fff;
pub const OXYGEN_OFFSIN_44K: c_uint = 0xec;
pub const OXYGEN_OFFSBASE_44K: c_uint = 0xed;
