//! Automatically rewritten from C Header to Rust Module
//! Source: include/linux/atomic/atomic-arch-fallback.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
// Generated by scripts/atomic/gen-atomic-fallback.sh
// DO NOT MODIFY THIS FILE DIRECTLY

extern "C" {
    pub fn raw_xchg_not_implemented();
}

extern "C" {
    pub fn raw_xchg_acquire_not_implemented();
}

extern "C" {
    pub fn raw_xchg_release_not_implemented();
}

extern "C" {
    pub fn raw_xchg_relaxed_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg_acquire_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg_release_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg_relaxed_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg64_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg64_acquire_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg64_release_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg64_relaxed_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg128_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg128_acquire_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg128_release_not_implemented();
}

extern "C" {
    pub fn raw_cmpxchg128_relaxed_not_implemented();
}

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

// ___op = ___r; \

//
// raw_atomic_read() - atomic load with relaxed ordering
// @v: pointer to atomic_t
//
// Atomically loads the value of @v with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_read() elsewhere.
//
// Return: The value loaded from @v.
//
extern "C" {
    pub fn arch_atomic_read(_arg: v) -> return;
}
//
// raw_atomic_read_acquire() - atomic load with acquire ordering
// @v: pointer to atomic_t
//
// Atomically loads the value of @v with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_read_acquire() elsewhere.
//
// Return: The value loaded from @v.
//

extern "C" {
    pub fn arch_atomic_read_acquire(_arg: v) -> return;
}

//
// raw_atomic_set() - atomic set with relaxed ordering
// @v: pointer to atomic_t
// @i: int value to assign
//
// Atomically sets @v to @i with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_set() elsewhere.
//
// Return: Nothing.
//
// raw_atomic_set_release() - atomic set with release ordering
// @v: pointer to atomic_t
// @i: int value to assign
//
// Atomically sets @v to @i with release ordering.
//
// Safe to use in noinstr code; prefer atomic_set_release() elsewhere.
//
// Return: Nothing.
//

//
// raw_atomic_add() - atomic add with relaxed ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_add() elsewhere.
//
// Return: Nothing.
//
// raw_atomic_add_return() - atomic add with full ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_add_return() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_add_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_add_return_acquire() - atomic add with acquire ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_add_return_acquire() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_add_return_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_add_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_add_return_release() - atomic add with release ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_add_return_release() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_add_return_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_add_return_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_add_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_add_return_relaxed() - atomic add with relaxed ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_add_return_relaxed() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_add_return_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_add_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_add() - atomic add with full ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_add() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_add(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_add_acquire() - atomic add with acquire ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_add_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_add_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_add(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_add_release() - atomic add with release ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_add_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_add_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_add_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_add(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_add_relaxed() - atomic add with relaxed ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_add_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_add_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_add(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_sub() - atomic subtract with relaxed ordering
// @i: int value to subtract
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_sub() elsewhere.
//
// Return: Nothing.
//
// raw_atomic_sub_return() - atomic subtract with full ordering
// @i: int value to subtract
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_sub_return() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_sub_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_sub_return_acquire() - atomic subtract with acquire ordering
// @i: int value to subtract
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_sub_return_acquire() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_sub_return_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_sub_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_sub_return_release() - atomic subtract with release ordering
// @i: int value to subtract
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_sub_return_release() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_sub_return_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_sub_return_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_sub_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_sub_return_relaxed() - atomic subtract with relaxed ordering
// @i: int value to subtract
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_sub_return_relaxed() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_sub_return_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_sub_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_sub() - atomic subtract with full ordering
// @i: int value to subtract
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_sub() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_sub(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_sub_acquire() - atomic subtract with acquire ordering
// @i: int value to subtract
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_sub_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_sub_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_sub(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_sub_release() - atomic subtract with release ordering
// @i: int value to subtract
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_sub_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_sub_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_sub_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_sub(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_sub_relaxed() - atomic subtract with relaxed ordering
// @i: int value to subtract
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_sub_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_sub_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_sub(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_inc() - atomic increment with relaxed ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_inc() elsewhere.
//
// Return: Nothing.
//

//
// raw_atomic_inc_return() - atomic increment with full ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_inc_return() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_inc_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_add_return(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_inc_return_acquire() - atomic increment with acquire ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + 1) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_inc_return_acquire() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_inc_return_acquire(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_inc_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_add_return_acquire(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_inc_return_release() - atomic increment with release ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + 1) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_inc_return_release() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_inc_return_release(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_inc_return_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_inc_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_add_return_release(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_inc_return_relaxed() - atomic increment with relaxed ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_inc_return_relaxed() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_inc_return_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_inc_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_add_return_relaxed(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_fetch_inc() - atomic increment with full ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_inc() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_inc(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_add(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_fetch_inc_acquire() - atomic increment with acquire ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + 1) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_inc_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_inc_acquire(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_inc(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_add_acquire(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_fetch_inc_release() - atomic increment with release ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + 1) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_inc_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_inc_release(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_inc_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_inc(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_add_release(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_fetch_inc_relaxed() - atomic increment with relaxed ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_inc_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_inc_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_inc(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_add_relaxed(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_dec() - atomic decrement with relaxed ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_dec() elsewhere.
//
// Return: Nothing.
//

//
// raw_atomic_dec_return() - atomic decrement with full ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_dec_return() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_dec_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_sub_return(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_dec_return_acquire() - atomic decrement with acquire ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - 1) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_dec_return_acquire() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_dec_return_acquire(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_dec_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_sub_return_acquire(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_dec_return_release() - atomic decrement with release ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - 1) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_dec_return_release() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_dec_return_release(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_dec_return_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_dec_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_sub_return_release(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_dec_return_relaxed() - atomic decrement with relaxed ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_dec_return_relaxed() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic_dec_return_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_dec_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_sub_return_relaxed(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_fetch_dec() - atomic decrement with full ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_dec() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_dec(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_sub(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_fetch_dec_acquire() - atomic decrement with acquire ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - 1) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_dec_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_dec_acquire(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_dec(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_sub_acquire(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_fetch_dec_release() - atomic decrement with release ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - 1) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_dec_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_dec_release(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_dec_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_dec(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_sub_release(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_fetch_dec_relaxed() - atomic decrement with relaxed ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_dec_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_dec_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_dec(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_sub_relaxed(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic_and() - atomic bitwise AND with relaxed ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v & @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_and() elsewhere.
//
// Return: Nothing.
//
// raw_atomic_fetch_and() - atomic bitwise AND with full ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v & @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_and() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_and(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_and_acquire() - atomic bitwise AND with acquire ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v & @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_and_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_and_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_and(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_and_release() - atomic bitwise AND with release ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v & @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_and_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_and_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_and_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_and(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_and_relaxed() - atomic bitwise AND with relaxed ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v & @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_and_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_and_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_and(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_andnot() - atomic bitwise AND NOT with relaxed ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v & ~@i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_andnot() elsewhere.
//
// Return: Nothing.
//

//
// raw_atomic_fetch_andnot() - atomic bitwise AND NOT with full ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v & ~@i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_andnot() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_andnot(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_and(_arg: ~i, _arg: v) -> return;
}

//
// raw_atomic_fetch_andnot_acquire() - atomic bitwise AND NOT with acquire ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v & ~@i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_andnot_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_andnot_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_andnot(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_and_acquire(_arg: ~i, _arg: v) -> return;
}

//
// raw_atomic_fetch_andnot_release() - atomic bitwise AND NOT with release ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v & ~@i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_andnot_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_andnot_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_andnot_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_andnot(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_and_release(_arg: ~i, _arg: v) -> return;
}

//
// raw_atomic_fetch_andnot_relaxed() - atomic bitwise AND NOT with relaxed ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v & ~@i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_andnot_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_andnot_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_andnot(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_fetch_and_relaxed(_arg: ~i, _arg: v) -> return;
}

//
// raw_atomic_or() - atomic bitwise OR with relaxed ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v | @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_or() elsewhere.
//
// Return: Nothing.
//
// raw_atomic_fetch_or() - atomic bitwise OR with full ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v | @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_or() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_or(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_or_acquire() - atomic bitwise OR with acquire ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v | @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_or_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_or_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_or(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_or_release() - atomic bitwise OR with release ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v | @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_or_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_or_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_or_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_or(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_or_relaxed() - atomic bitwise OR with relaxed ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v | @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_or_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_or_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_or(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_xor() - atomic bitwise XOR with relaxed ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v ^ @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_xor() elsewhere.
//
// Return: Nothing.
//
// raw_atomic_fetch_xor() - atomic bitwise XOR with full ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v ^ @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_xor() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_xor(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_xor_acquire() - atomic bitwise XOR with acquire ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v ^ @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_xor_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_xor_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_xor(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_xor_release() - atomic bitwise XOR with release ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v ^ @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_xor_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_xor_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_xor_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_xor(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_xor_relaxed() - atomic bitwise XOR with relaxed ordering
// @i: int value
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v ^ @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_fetch_xor_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_xor_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_fetch_xor(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_xchg() - atomic exchange with full ordering
// @v: pointer to atomic_t
// @new: int value to assign
//
// Atomically updates @v to @new with full ordering.
//
// Safe to use in noinstr code; prefer atomic_xchg() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_xchg(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn raw_xchg(_arg: &v->counter, _arg: new) -> return;
}

//
// raw_atomic_xchg_acquire() - atomic exchange with acquire ordering
// @v: pointer to atomic_t
// @new: int value to assign
//
// Atomically updates @v to @new with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_xchg_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_xchg_acquire(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_xchg(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn raw_xchg_acquire(_arg: &v->counter, _arg: new) -> return;
}

//
// raw_atomic_xchg_release() - atomic exchange with release ordering
// @v: pointer to atomic_t
// @new: int value to assign
//
// Atomically updates @v to @new with release ordering.
//
// Safe to use in noinstr code; prefer atomic_xchg_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_xchg_release(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_xchg_relaxed(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_xchg(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn raw_xchg_release(_arg: &v->counter, _arg: new) -> return;
}

//
// raw_atomic_xchg_relaxed() - atomic exchange with relaxed ordering
// @v: pointer to atomic_t
// @new: int value to assign
//
// Atomically updates @v to @new with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_xchg_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_xchg_relaxed(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_xchg(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn raw_xchg_relaxed(_arg: &v->counter, _arg: new) -> return;
}

//
// raw_atomic_cmpxchg() - atomic compare and exchange with full ordering
// @v: pointer to atomic_t
// @old: int value to compare with
// @new: int value to assign
//
// If (@v == @old), atomically updates @v to @new with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_cmpxchg() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn raw_cmpxchg(_arg: &v->counter, _arg: old, _arg: new) -> return;
}

//
// raw_atomic_cmpxchg_acquire() - atomic compare and exchange with acquire ordering
// @v: pointer to atomic_t
// @old: int value to compare with
// @new: int value to assign
//
// If (@v == @old), atomically updates @v to @new with acquire ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_cmpxchg_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_cmpxchg_acquire(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn raw_cmpxchg_acquire(_arg: &v->counter, _arg: old, _arg: new) -> return;
}

//
// raw_atomic_cmpxchg_release() - atomic compare and exchange with release ordering
// @v: pointer to atomic_t
// @old: int value to compare with
// @new: int value to assign
//
// If (@v == @old), atomically updates @v to @new with release ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_cmpxchg_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_cmpxchg_release(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_cmpxchg_relaxed(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn raw_cmpxchg_release(_arg: &v->counter, _arg: old, _arg: new) -> return;
}

//
// raw_atomic_cmpxchg_relaxed() - atomic compare and exchange with relaxed ordering
// @v: pointer to atomic_t
// @old: int value to compare with
// @new: int value to assign
//
// If (@v == @old), atomically updates @v to @new with relaxed ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_cmpxchg_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_cmpxchg_relaxed(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn raw_cmpxchg_relaxed(_arg: &v->counter, _arg: old, _arg: new) -> return;
}

//
// raw_atomic_try_cmpxchg() - atomic compare and exchange with full ordering
// @v: pointer to atomic_t
// @old: pointer to int value to compare with
// @new: int value to assign
//
// If (@v == @old), atomically updates @v to @new with full ordering.
// Otherwise, @v is not modified, @old is updated to the current value of @v,
// and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_try_cmpxchg() elsewhere.
//
// Return: @true if the exchange occurred, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_try_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

// old = r;
extern "C" {
    pub fn likely(o: r ==) -> return;
}

//
// raw_atomic_try_cmpxchg_acquire() - atomic compare and exchange with acquire ordering
// @v: pointer to atomic_t
// @old: pointer to int value to compare with
// @new: int value to assign
//
// If (@v == @old), atomically updates @v to @new with acquire ordering.
// Otherwise, @v is not modified, @old is updated to the current value of @v,
// and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_try_cmpxchg_acquire() elsewhere.
//
// Return: @true if the exchange occurred, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_try_cmpxchg_acquire(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_try_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

// old = r;
extern "C" {
    pub fn likely(o: r ==) -> return;
}

//
// raw_atomic_try_cmpxchg_release() - atomic compare and exchange with release ordering
// @v: pointer to atomic_t
// @old: pointer to int value to compare with
// @new: int value to assign
//
// If (@v == @old), atomically updates @v to @new with release ordering.
// Otherwise, @v is not modified, @old is updated to the current value of @v,
// and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_try_cmpxchg_release() elsewhere.
//
// Return: @true if the exchange occurred, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_try_cmpxchg_release(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_try_cmpxchg_relaxed(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_try_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

// old = r;
extern "C" {
    pub fn likely(o: r ==) -> return;
}

//
// raw_atomic_try_cmpxchg_relaxed() - atomic compare and exchange with relaxed ordering
// @v: pointer to atomic_t
// @old: pointer to int value to compare with
// @new: int value to assign
//
// If (@v == @old), atomically updates @v to @new with relaxed ordering.
// Otherwise, @v is not modified, @old is updated to the current value of @v,
// and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_try_cmpxchg_relaxed() elsewhere.
//
// Return: @true if the exchange occurred, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_try_cmpxchg_relaxed(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic_try_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

// old = r;
extern "C" {
    pub fn likely(o: r ==) -> return;
}

//
// raw_atomic_sub_and_test() - atomic subtract and test if zero with full ordering
// @i: int value to subtract
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_sub_and_test() elsewhere.
//
// Return: @true if the resulting value of @v is zero, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_sub_and_test(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_dec_and_test() - atomic decrement and test if zero with full ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v - 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_dec_and_test() elsewhere.
//
// Return: @true if the resulting value of @v is zero, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_dec_and_test(_arg: v) -> return;
}

//
// raw_atomic_inc_and_test() - atomic increment and test if zero with full ordering
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_inc_and_test() elsewhere.
//
// Return: @true if the resulting value of @v is zero, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_inc_and_test(_arg: v) -> return;
}

//
// raw_atomic_add_negative() - atomic add and test if negative with full ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic_add_negative() elsewhere.
//
// Return: @true if the resulting value of @v is negative, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_add_negative(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_add_negative_acquire() - atomic add and test if negative with acquire ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic_add_negative_acquire() elsewhere.
//
// Return: @true if the resulting value of @v is negative, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_add_negative_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_add_negative(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_add_negative_release() - atomic add and test if negative with release ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic_add_negative_release() elsewhere.
//
// Return: @true if the resulting value of @v is negative, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_add_negative_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_add_negative_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_add_negative(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_add_negative_relaxed() - atomic add and test if negative with relaxed ordering
// @i: int value to add
// @v: pointer to atomic_t
//
// Atomically updates @v to (@v + @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic_add_negative_relaxed() elsewhere.
//
// Return: @true if the resulting value of @v is negative, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_add_negative_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic_add_negative(_arg: i, _arg: v) -> return;
}

//
// raw_atomic_fetch_add_unless() - atomic add unless value with full ordering
// @v: pointer to atomic_t
// @a: int value to add
// @u: int value to compare with
//
// If (@v != @u), atomically updates @v to (@v + @a) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_fetch_add_unless() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic_fetch_add_unless(_arg: v, _arg: a, _arg: u) -> return;
}

//
// raw_atomic_add_unless() - atomic add unless value with full ordering
// @v: pointer to atomic_t
// @a: int value to add
// @u: int value to compare with
//
// If (@v != @u), atomically updates @v to (@v + @a) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_add_unless() elsewhere.
//
// Return: @true if @v was updated, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_add_unless(_arg: v, _arg: a, _arg: u) -> return;
}

//
// raw_atomic_inc_not_zero() - atomic increment unless zero with full ordering
// @v: pointer to atomic_t
//
// If (@v != 0), atomically updates @v to (@v + 1) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_inc_not_zero() elsewhere.
//
// Return: @true if @v was updated, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_inc_not_zero(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic_add_unless(_arg: v, _arg: 1, _arg: 0) -> return;
}

//
// raw_atomic_inc_unless_negative() - atomic increment unless negative with full ordering
// @v: pointer to atomic_t
//
// If (@v >= 0), atomically updates @v to (@v + 1) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_inc_unless_negative() elsewhere.
//
// Return: @true if @v was updated, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_inc_unless_negative(_arg: v) -> return;
}

//
// raw_atomic_dec_unless_positive() - atomic decrement unless positive with full ordering
// @v: pointer to atomic_t
//
// If (@v <= 0), atomically updates @v to (@v - 1) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_dec_unless_positive() elsewhere.
//
// Return: @true if @v was updated, @false otherwise.
//

extern "C" {
    pub fn arch_atomic_dec_unless_positive(_arg: v) -> return;
}

//
// raw_atomic_dec_if_positive() - atomic decrement if positive with full ordering
// @v: pointer to atomic_t
//
// If (@v > 0), atomically updates @v to (@v - 1) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic_dec_if_positive() elsewhere.
//
// Return: The old value of (@v - 1), regardless of whether @v was updated.
//

extern "C" {
    pub fn arch_atomic_dec_if_positive(_arg: v) -> return;
}

//
// raw_atomic64_read() - atomic load with relaxed ordering
// @v: pointer to atomic64_t
//
// Atomically loads the value of @v with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_read() elsewhere.
//
// Return: The value loaded from @v.
//
extern "C" {
    pub fn arch_atomic64_read(_arg: v) -> return;
}
//
// raw_atomic64_read_acquire() - atomic load with acquire ordering
// @v: pointer to atomic64_t
//
// Atomically loads the value of @v with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_read_acquire() elsewhere.
//
// Return: The value loaded from @v.
//

extern "C" {
    pub fn arch_atomic64_read_acquire(_arg: v) -> return;
}

//
// raw_atomic64_set() - atomic set with relaxed ordering
// @v: pointer to atomic64_t
// @i: s64 value to assign
//
// Atomically sets @v to @i with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_set() elsewhere.
//
// Return: Nothing.
//
// raw_atomic64_set_release() - atomic set with release ordering
// @v: pointer to atomic64_t
// @i: s64 value to assign
//
// Atomically sets @v to @i with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_set_release() elsewhere.
//
// Return: Nothing.
//

//
// raw_atomic64_add() - atomic add with relaxed ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_add() elsewhere.
//
// Return: Nothing.
//
// raw_atomic64_add_return() - atomic add with full ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_add_return() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_add_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_add_return_acquire() - atomic add with acquire ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_add_return_acquire() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_add_return_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_add_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_add_return_release() - atomic add with release ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_add_return_release() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_add_return_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_add_return_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_add_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_add_return_relaxed() - atomic add with relaxed ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_add_return_relaxed() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_add_return_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_add_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_add() - atomic add with full ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_add() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_add(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_add_acquire() - atomic add with acquire ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_add_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_add_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_add(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_add_release() - atomic add with release ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_add_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_add_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_add_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_add(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_add_relaxed() - atomic add with relaxed ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_add_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_add_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_add(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_sub() - atomic subtract with relaxed ordering
// @i: s64 value to subtract
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_sub() elsewhere.
//
// Return: Nothing.
//
// raw_atomic64_sub_return() - atomic subtract with full ordering
// @i: s64 value to subtract
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_sub_return() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_sub_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_sub_return_acquire() - atomic subtract with acquire ordering
// @i: s64 value to subtract
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_sub_return_acquire() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_sub_return_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_sub_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_sub_return_release() - atomic subtract with release ordering
// @i: s64 value to subtract
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_sub_return_release() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_sub_return_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_sub_return_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_sub_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_sub_return_relaxed() - atomic subtract with relaxed ordering
// @i: s64 value to subtract
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_sub_return_relaxed() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_sub_return_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_sub_return(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_sub() - atomic subtract with full ordering
// @i: s64 value to subtract
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_sub() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_sub(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_sub_acquire() - atomic subtract with acquire ordering
// @i: s64 value to subtract
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_sub_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_sub_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_sub(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_sub_release() - atomic subtract with release ordering
// @i: s64 value to subtract
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_sub_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_sub_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_sub_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_sub(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_sub_relaxed() - atomic subtract with relaxed ordering
// @i: s64 value to subtract
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_sub_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_sub_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_sub(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_inc() - atomic increment with relaxed ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_inc() elsewhere.
//
// Return: Nothing.
//

//
// raw_atomic64_inc_return() - atomic increment with full ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_inc_return() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_inc_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_add_return(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_inc_return_acquire() - atomic increment with acquire ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + 1) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_inc_return_acquire() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_inc_return_acquire(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_inc_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_add_return_acquire(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_inc_return_release() - atomic increment with release ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + 1) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_inc_return_release() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_inc_return_release(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_inc_return_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_inc_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_add_return_release(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_inc_return_relaxed() - atomic increment with relaxed ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_inc_return_relaxed() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_inc_return_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_inc_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_add_return_relaxed(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_fetch_inc() - atomic increment with full ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_inc() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_inc(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_add(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_fetch_inc_acquire() - atomic increment with acquire ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + 1) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_inc_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_inc_acquire(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_inc(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_add_acquire(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_fetch_inc_release() - atomic increment with release ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + 1) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_inc_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_inc_release(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_inc_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_inc(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_add_release(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_fetch_inc_relaxed() - atomic increment with relaxed ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_inc_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_inc_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_inc(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_add_relaxed(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_dec() - atomic decrement with relaxed ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_dec() elsewhere.
//
// Return: Nothing.
//

//
// raw_atomic64_dec_return() - atomic decrement with full ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_dec_return() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_dec_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_sub_return(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_dec_return_acquire() - atomic decrement with acquire ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - 1) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_dec_return_acquire() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_dec_return_acquire(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_dec_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_sub_return_acquire(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_dec_return_release() - atomic decrement with release ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - 1) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_dec_return_release() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_dec_return_release(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_dec_return_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_dec_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_sub_return_release(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_dec_return_relaxed() - atomic decrement with relaxed ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_dec_return_relaxed() elsewhere.
//
// Return: The updated value of @v.
//

extern "C" {
    pub fn arch_atomic64_dec_return_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_dec_return(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_sub_return_relaxed(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_fetch_dec() - atomic decrement with full ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_dec() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_dec(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_sub(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_fetch_dec_acquire() - atomic decrement with acquire ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - 1) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_dec_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_dec_acquire(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_dec(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_sub_acquire(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_fetch_dec_release() - atomic decrement with release ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - 1) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_dec_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_dec_release(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_dec_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_dec(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_sub_release(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_fetch_dec_relaxed() - atomic decrement with relaxed ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - 1) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_dec_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_dec_relaxed(_arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_dec(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_sub_relaxed(_arg: 1, _arg: v) -> return;
}

//
// raw_atomic64_and() - atomic bitwise AND with relaxed ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v & @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_and() elsewhere.
//
// Return: Nothing.
//
// raw_atomic64_fetch_and() - atomic bitwise AND with full ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v & @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_and() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_and(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_and_acquire() - atomic bitwise AND with acquire ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v & @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_and_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_and_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_and(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_and_release() - atomic bitwise AND with release ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v & @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_and_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_and_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_and_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_and(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_and_relaxed() - atomic bitwise AND with relaxed ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v & @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_and_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_and_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_and(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_andnot() - atomic bitwise AND NOT with relaxed ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v & ~@i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_andnot() elsewhere.
//
// Return: Nothing.
//

//
// raw_atomic64_fetch_andnot() - atomic bitwise AND NOT with full ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v & ~@i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_andnot() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_andnot(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_and(_arg: ~i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_andnot_acquire() - atomic bitwise AND NOT with acquire ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v & ~@i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_andnot_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_andnot_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_andnot(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_and_acquire(_arg: ~i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_andnot_release() - atomic bitwise AND NOT with release ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v & ~@i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_andnot_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_andnot_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_andnot_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_andnot(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_and_release(_arg: ~i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_andnot_relaxed() - atomic bitwise AND NOT with relaxed ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v & ~@i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_andnot_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_andnot_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_andnot(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_fetch_and_relaxed(_arg: ~i, _arg: v) -> return;
}

//
// raw_atomic64_or() - atomic bitwise OR with relaxed ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v | @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_or() elsewhere.
//
// Return: Nothing.
//
// raw_atomic64_fetch_or() - atomic bitwise OR with full ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v | @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_or() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_or(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_or_acquire() - atomic bitwise OR with acquire ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v | @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_or_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_or_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_or(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_or_release() - atomic bitwise OR with release ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v | @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_or_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_or_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_or_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_or(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_or_relaxed() - atomic bitwise OR with relaxed ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v | @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_or_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_or_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_or(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_xor() - atomic bitwise XOR with relaxed ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v ^ @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_xor() elsewhere.
//
// Return: Nothing.
//
// raw_atomic64_fetch_xor() - atomic bitwise XOR with full ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v ^ @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_xor() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_xor(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_xor_acquire() - atomic bitwise XOR with acquire ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v ^ @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_xor_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_xor_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_xor(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_xor_release() - atomic bitwise XOR with release ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v ^ @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_xor_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_xor_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_xor_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_xor(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_xor_relaxed() - atomic bitwise XOR with relaxed ordering
// @i: s64 value
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v ^ @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_fetch_xor_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_xor_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_fetch_xor(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_xchg() - atomic exchange with full ordering
// @v: pointer to atomic64_t
// @new: s64 value to assign
//
// Atomically updates @v to @new with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_xchg() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_xchg(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn raw_xchg(_arg: &v->counter, _arg: new) -> return;
}

//
// raw_atomic64_xchg_acquire() - atomic exchange with acquire ordering
// @v: pointer to atomic64_t
// @new: s64 value to assign
//
// Atomically updates @v to @new with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_xchg_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_xchg_acquire(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_xchg(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn raw_xchg_acquire(_arg: &v->counter, _arg: new) -> return;
}

//
// raw_atomic64_xchg_release() - atomic exchange with release ordering
// @v: pointer to atomic64_t
// @new: s64 value to assign
//
// Atomically updates @v to @new with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_xchg_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_xchg_release(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_xchg_relaxed(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_xchg(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn raw_xchg_release(_arg: &v->counter, _arg: new) -> return;
}

//
// raw_atomic64_xchg_relaxed() - atomic exchange with relaxed ordering
// @v: pointer to atomic64_t
// @new: s64 value to assign
//
// Atomically updates @v to @new with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_xchg_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_xchg_relaxed(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_xchg(_arg: v, _arg: new) -> return;
}

extern "C" {
    pub fn raw_xchg_relaxed(_arg: &v->counter, _arg: new) -> return;
}

//
// raw_atomic64_cmpxchg() - atomic compare and exchange with full ordering
// @v: pointer to atomic64_t
// @old: s64 value to compare with
// @new: s64 value to assign
//
// If (@v == @old), atomically updates @v to @new with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_cmpxchg() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn raw_cmpxchg(_arg: &v->counter, _arg: old, _arg: new) -> return;
}

//
// raw_atomic64_cmpxchg_acquire() - atomic compare and exchange with acquire ordering
// @v: pointer to atomic64_t
// @old: s64 value to compare with
// @new: s64 value to assign
//
// If (@v == @old), atomically updates @v to @new with acquire ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_cmpxchg_acquire() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_cmpxchg_acquire(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn raw_cmpxchg_acquire(_arg: &v->counter, _arg: old, _arg: new) -> return;
}

//
// raw_atomic64_cmpxchg_release() - atomic compare and exchange with release ordering
// @v: pointer to atomic64_t
// @old: s64 value to compare with
// @new: s64 value to assign
//
// If (@v == @old), atomically updates @v to @new with release ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_cmpxchg_release() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_cmpxchg_release(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_cmpxchg_relaxed(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn raw_cmpxchg_release(_arg: &v->counter, _arg: old, _arg: new) -> return;
}

//
// raw_atomic64_cmpxchg_relaxed() - atomic compare and exchange with relaxed ordering
// @v: pointer to atomic64_t
// @old: s64 value to compare with
// @new: s64 value to assign
//
// If (@v == @old), atomically updates @v to @new with relaxed ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_cmpxchg_relaxed() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_cmpxchg_relaxed(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn raw_cmpxchg_relaxed(_arg: &v->counter, _arg: old, _arg: new) -> return;
}

//
// raw_atomic64_try_cmpxchg() - atomic compare and exchange with full ordering
// @v: pointer to atomic64_t
// @old: pointer to s64 value to compare with
// @new: s64 value to assign
//
// If (@v == @old), atomically updates @v to @new with full ordering.
// Otherwise, @v is not modified, @old is updated to the current value of @v,
// and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_try_cmpxchg() elsewhere.
//
// Return: @true if the exchange occurred, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_try_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

// old = r;
extern "C" {
    pub fn likely(o: r ==) -> return;
}

//
// raw_atomic64_try_cmpxchg_acquire() - atomic compare and exchange with acquire ordering
// @v: pointer to atomic64_t
// @old: pointer to s64 value to compare with
// @new: s64 value to assign
//
// If (@v == @old), atomically updates @v to @new with acquire ordering.
// Otherwise, @v is not modified, @old is updated to the current value of @v,
// and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_try_cmpxchg_acquire() elsewhere.
//
// Return: @true if the exchange occurred, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_try_cmpxchg_acquire(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_try_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

// old = r;
extern "C" {
    pub fn likely(o: r ==) -> return;
}

//
// raw_atomic64_try_cmpxchg_release() - atomic compare and exchange with release ordering
// @v: pointer to atomic64_t
// @old: pointer to s64 value to compare with
// @new: s64 value to assign
//
// If (@v == @old), atomically updates @v to @new with release ordering.
// Otherwise, @v is not modified, @old is updated to the current value of @v,
// and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_try_cmpxchg_release() elsewhere.
//
// Return: @true if the exchange occurred, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_try_cmpxchg_release(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_try_cmpxchg_relaxed(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_try_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

// old = r;
extern "C" {
    pub fn likely(o: r ==) -> return;
}

//
// raw_atomic64_try_cmpxchg_relaxed() - atomic compare and exchange with relaxed ordering
// @v: pointer to atomic64_t
// @old: pointer to s64 value to compare with
// @new: s64 value to assign
//
// If (@v == @old), atomically updates @v to @new with relaxed ordering.
// Otherwise, @v is not modified, @old is updated to the current value of @v,
// and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_try_cmpxchg_relaxed() elsewhere.
//
// Return: @true if the exchange occurred, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_try_cmpxchg_relaxed(_arg: v, _arg: old, _arg: new) -> return;
}

extern "C" {
    pub fn arch_atomic64_try_cmpxchg(_arg: v, _arg: old, _arg: new) -> return;
}

// old = r;
extern "C" {
    pub fn likely(o: r ==) -> return;
}

//
// raw_atomic64_sub_and_test() - atomic subtract and test if zero with full ordering
// @i: s64 value to subtract
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_sub_and_test() elsewhere.
//
// Return: @true if the resulting value of @v is zero, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_sub_and_test(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_dec_and_test() - atomic decrement and test if zero with full ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v - 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_dec_and_test() elsewhere.
//
// Return: @true if the resulting value of @v is zero, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_dec_and_test(_arg: v) -> return;
}

//
// raw_atomic64_inc_and_test() - atomic increment and test if zero with full ordering
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + 1) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_inc_and_test() elsewhere.
//
// Return: @true if the resulting value of @v is zero, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_inc_and_test(_arg: v) -> return;
}

//
// raw_atomic64_add_negative() - atomic add and test if negative with full ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with full ordering.
//
// Safe to use in noinstr code; prefer atomic64_add_negative() elsewhere.
//
// Return: @true if the resulting value of @v is negative, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_add_negative(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_add_negative_acquire() - atomic add and test if negative with acquire ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with acquire ordering.
//
// Safe to use in noinstr code; prefer atomic64_add_negative_acquire() elsewhere.
//
// Return: @true if the resulting value of @v is negative, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_add_negative_acquire(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_add_negative(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_add_negative_release() - atomic add and test if negative with release ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with release ordering.
//
// Safe to use in noinstr code; prefer atomic64_add_negative_release() elsewhere.
//
// Return: @true if the resulting value of @v is negative, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_add_negative_release(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_add_negative_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_add_negative(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_add_negative_relaxed() - atomic add and test if negative with relaxed ordering
// @i: s64 value to add
// @v: pointer to atomic64_t
//
// Atomically updates @v to (@v + @i) with relaxed ordering.
//
// Safe to use in noinstr code; prefer atomic64_add_negative_relaxed() elsewhere.
//
// Return: @true if the resulting value of @v is negative, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_add_negative_relaxed(_arg: i, _arg: v) -> return;
}

extern "C" {
    pub fn arch_atomic64_add_negative(_arg: i, _arg: v) -> return;
}

//
// raw_atomic64_fetch_add_unless() - atomic add unless value with full ordering
// @v: pointer to atomic64_t
// @a: s64 value to add
// @u: s64 value to compare with
//
// If (@v != @u), atomically updates @v to (@v + @a) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_fetch_add_unless() elsewhere.
//
// Return: The original value of @v.
//

extern "C" {
    pub fn arch_atomic64_fetch_add_unless(_arg: v, _arg: a, _arg: u) -> return;
}

//
// raw_atomic64_add_unless() - atomic add unless value with full ordering
// @v: pointer to atomic64_t
// @a: s64 value to add
// @u: s64 value to compare with
//
// If (@v != @u), atomically updates @v to (@v + @a) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_add_unless() elsewhere.
//
// Return: @true if @v was updated, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_add_unless(_arg: v, _arg: a, _arg: u) -> return;
}

//
// raw_atomic64_inc_not_zero() - atomic increment unless zero with full ordering
// @v: pointer to atomic64_t
//
// If (@v != 0), atomically updates @v to (@v + 1) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_inc_not_zero() elsewhere.
//
// Return: @true if @v was updated, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_inc_not_zero(_arg: v) -> return;
}

extern "C" {
    pub fn raw_atomic64_add_unless(_arg: v, _arg: 1, _arg: 0) -> return;
}

//
// raw_atomic64_inc_unless_negative() - atomic increment unless negative with full ordering
// @v: pointer to atomic64_t
//
// If (@v >= 0), atomically updates @v to (@v + 1) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_inc_unless_negative() elsewhere.
//
// Return: @true if @v was updated, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_inc_unless_negative(_arg: v) -> return;
}

//
// raw_atomic64_dec_unless_positive() - atomic decrement unless positive with full ordering
// @v: pointer to atomic64_t
//
// If (@v <= 0), atomically updates @v to (@v - 1) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_dec_unless_positive() elsewhere.
//
// Return: @true if @v was updated, @false otherwise.
//

extern "C" {
    pub fn arch_atomic64_dec_unless_positive(_arg: v) -> return;
}

//
// raw_atomic64_dec_if_positive() - atomic decrement if positive with full ordering
// @v: pointer to atomic64_t
//
// If (@v > 0), atomically updates @v to (@v - 1) with full ordering.
// Otherwise, @v is not modified and relaxed ordering is provided.
//
// Safe to use in noinstr code; prefer atomic64_dec_if_positive() elsewhere.
//
// Return: The old value of (@v - 1), regardless of whether @v was updated.
//

extern "C" {
    pub fn arch_atomic64_dec_if_positive(_arg: v) -> return;
}

// 206314f82b8b73a5c3aa69cf7f35ac9e7b5d6b58
