//! Automatically rewritten from C to Rust
//! Source: drivers/platform/cznic/turris-omnia-mcu-trng.c
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// CZ.NIC's Turris Omnia MCU TRNG driver
//
// 2024 by Marek Behún <kabel@kernel.org>
//

pub const OMNIA_CMD_TRNG_MAX_ENTROPY_LEN: c_int = 64;
#[no_mangle]
unsafe extern "C" fn omnia_trng_irq_handler(irq: c_int, dev_id: *mut c_void) -> irqreturn_t {
    static irqreturn_t omnia_trng_irq_handler(int irq, void *dev_id)
    {
    struct omnia_mcu *mcu = dev_id;
    complete(&mcu.trng_entropy_ready);
    return IRQ_HANDLED;
    }
#[no_mangle]
unsafe extern "C" fn omnia_trng_read(rng: *mut hwrng, data: *mut c_void, max: usize, wait: bool) -> c_int {
    static int omnia_trng_read(struct hwrng *rng, void *data, size_t max, bool wait)
    {
    struct omnia_mcu *mcu = container_of(rng, struct omnia_mcu, trng);
    u8 reply[1 + OMNIA_CMD_TRNG_MAX_ENTROPY_LEN];
    int err, bytes;
    if (!wait && !completion_done(&mcu.trng_entropy_ready))
    return 0;
    do {
    if (wait_for_completion_interruptible(&mcu.trng_entropy_ready))
    return -ERESTARTSYS;
    err = omnia_cmd_read(mcu.client,
    OMNIA_CMD_TRNG_COLLECT_ENTROPY,
    reply, sizeof(reply));
    if (err)
    return err;
    bytes = min3(reply[0], max, OMNIA_CMD_TRNG_MAX_ENTROPY_LEN);
    } while (wait && !bytes);
    memcpy(data, &reply[1], bytes);
    return bytes;
    }
#[no_mangle]
pub unsafe extern "C" fn omnia_mcu_register_trng(mcu: *mut omnia_mcu) -> c_int {
    int omnia_mcu_register_trng(struct omnia_mcu *mcu)
    {
    struct device *dev = &mcu.client.dev;
    u8 dummy;
    int err;
    if (!(mcu.features & OMNIA_FEAT_TRNG))
    return 0;
//
// If someone else cleared the TRNG interrupt but did not read the
// entropy, a new interrupt won't be generated, and entropy collection
// will be stuck. Ensure an interrupt will be generated by executing
// the collect entropy command (and discarding the result).
//
    err = omnia_cmd_read(mcu.client, OMNIA_CMD_TRNG_COLLECT_ENTROPY,
    &dummy, 1);
    if (err)
    return err;
    init_completion(&mcu.trng_entropy_ready);
    err = omnia_mcu_request_irq(mcu, OMNIA_INT_TRNG, omnia_trng_irq_handler,
    "turris-omnia-mcu-trng");
    if (err)
    return dev_err_probe(dev, err, "Cannot request TRNG IRQ\n");
    mcu.trng.name = "turris-omnia-mcu-trng";
    mcu.trng.read = omnia_trng_read;
    err = devm_hwrng_register(dev, &mcu.trng);
    if (err)
    return dev_err_probe(dev, err, "Cannot register TRNG\n");
    return 0;
    }
