//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/nouveau/nvkm/subdev/gsp/rm/r570/nvrm/gsp.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: MIT
// Copyright (c) 2025, NVIDIA CORPORATION. All rights reserved.

// Excerpt of RM headers from https://github.com/NVIDIA/open-gpu-kernel-modules/tree/570.144

pub const NV0080_CTRL_GR_CAPS_TBL_SIZE: c_int = 23;

pub const MAX_GPC_COUNT: c_int = 32;

pub const NVGPU_ENGINE_CAPS_MASK_BITS: c_int = 32;

pub const MAX_GROUP_COUNT: c_int = 2;
// "Total Board Power" refers to power requirement of GPU,
// while in GC6 state. Majority of this power will be used
// to keep V-RAM active to preserve its content.
// Some energy maybe consumed by Always-on components on GPU chip.
// This power will be provided by 3.3v voltage rail.
//
// PERST# (i.e. PCI Express Reset) is a sideband signal
// generated by the PCIe Host to indicate the PCIe devices,
// that the power-rails and the reference-clock are stable.
// The endpoint device typically uses this signal as a global reset.
//
// Client handle for internal RMAPI control.
// Device handle for internal RMAPI control.
// Subdevice handle for internal RMAPI control.

// Link capabilities
// Magic
// BL to use for verification (i.e. Booter locked it in WPR2)
// Revision number of Booter-BL-Sequencer handoff interface
// Bumped up when we change this interface so it is not backward compatible.
// Bumped up when we revoke GSP-RM ucode
// ---- Members regarding data in SYSMEM ----------------------------
// Consumed by Booter for DMA
// Offsets inside bootloader image needed by Booter
// Used only at initial boot
//
// Used at suspend/resume to read GspFwHeapFreeList
// Offset relative to GspFwWprMeta FBMEM PA (gspFwWprStart)
//
// ---- Members describing FB layout --------------------------------
// GSP-RM to use to setup heap.
// BL to use to find ELF for jump
// Size is sizeOfRadix3Elf above.
// Size is sizeOfBootloader above.
// GSP-RM to use for fbRegionInfo?
// ---- Other members -----------------------------------------------
// GSP-RM to use for fbRegionInfo?
// Boot count.  Used to determine whether to load the firmware image.
// This union is organized the way it is to start at an 8-byte boundary and achieve natural
// packing of the internal struct fields.
// TODO: the partitionRpc* fields below do not really belong in this
// structure. The values are patched in by the partition bootstrapper
// when GSP-RM is booted in a partition, and this structure was a
// convenient place for the bootstrapper to access them. These should
// be moved to a different comm. mechanism between the bootstrapper
// and the GSP-RM tasks.
// Shared partition RPC memory (physical address)
// Offsets relative to partitionRpcAddr
// Code section and dataSection offset and size.
// Used during GSP-RM resume to check for revocation
// Pad for the partitionRpc* fields, plus 4 bytes
// CrashCat (contiguous) buffer size/location - occupies same bytes as the
// elf(Code|Data)(Offset|Size) fields above.
// TODO: move to GSP_FMC_INIT_PARAMS
// Pad for the lsUcodeVersion field
// Number of VF partitions allocating sub-heaps from the WPR heap
// Used during boot to ensure the heap is adequately sized
// Flags to help decide GSP-FW flow.
// Pad structure to exactly 256 bytes.  Can replace padding with additional
// fields without incrementing revision.  Padding initialized to 0.
//
// Starts at gspFwWprEnd+frtsSize b/c FRTS is positioned
// to end where this allocation starts (when RM requests FSP to create
// FRTS).
//
// BL to use for verification (i.e. Booter says OK to boot)
pub const GSP_FW_WPR_META_MAGIC: c_uint = 0xdc3aae21371a60b3ULL;
pub const GSP_FW_WPR_META_REVISION: c_int = 1;

// Magic for verification by secure ucode
//
// Revision number
// Bumped up when we change this interface so it is not backward compatible.
//
// Members regarding data in SYSMEM
//
// Internal members for use by secure ucode
// Must be exactly GSP_FW_SR_META_INTERNAL_SIZE bytes.
//
// Same as flags of GspFwWprMeta
// Subrevision number used by secure ucode
//
// Pad structure to exactly 256 bytes (1 DMA chunk).
// Padding initialized to zero.
//

// CC initialization "registry keys"
// Physical memory aperture through which gspRmDescPa is accessed
// Size in bytes of the GSP-RM descriptor structure
// Physical offset in the target aperture of the GSP-RM descriptor structure
// Physical offset in FB to set the start of the WPR containing GSP-RM
// Size in bytes of the WPR containing GSP-RM
// Whether to boot GSP-RM or GSP-Proxy through ACR
// Physical memory aperture through which bootArgsOffset is accessed
// Physical offset in the memory aperture that will be passed to GSP-RM
// Physical Memory Aperture through which all addresses are accessed
// Physical offset in the memory aperture where SPDM payload is stored
// Size of the above payload buffer

