//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/media/platform/samsung/s5p-mfc/s5p_mfc_opr.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0-only
//
// drivers/media/platform/samsung/s5p-mfc/s5p_mfc_opr.h
//
// Header file for Samsung MFC (Multi Function Codec - FIMV) driver
// Contains declarations of hw related functions.
//
// Kamil Debski, Copyright (C) 2012 Samsung Electronics Co., Ltd.
// http://www.samsung.com
//

#[repr(C)]
#[derive(Copy, Clone)]
pub struct s5p_mfc_regs {
// codec common registers
    pub risc_on: *mut void __iomem,
    pub risc2host_int: *mut void __iomem,
    pub host2risc_int: *mut void __iomem,
    pub risc_base_address: *mut void __iomem,
    pub mfc_reset: *mut void __iomem,
    pub host2risc_command: *mut void __iomem,
    pub risc2host_command: *mut void __iomem,
    pub mfc_bus_reset_ctrl: *mut void __iomem,
    pub firmware_version: *mut void __iomem,
    pub instance_id: *mut void __iomem,
    pub codec_type: *mut void __iomem,
    pub context_mem_addr: *mut void __iomem,
    pub context_mem_size: *mut void __iomem,
    pub pixel_format: *mut void __iomem,
    pub metadata_enable: *mut void __iomem,
    pub mfc_version: *mut void __iomem,
    pub dbg_info_enable: *mut void __iomem,
    pub dbg_buffer_addr: *mut void __iomem,
    pub dbg_buffer_size: *mut void __iomem,
    pub hed_control: *mut void __iomem,
    pub mfc_timeout_value: *mut void __iomem,
    pub hed_shared_mem_addr: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem dis_shared_mem_addr;/ only v7,
    pub ret_instance_id: *mut void __iomem,
    pub error_code: *mut void __iomem,
    pub dbg_buffer_output_size: *mut void __iomem,
    pub metadata_status: *mut void __iomem,
    pub metadata_addr_mb_info: *mut void __iomem,
    pub metadata_size_mb_info: *mut void __iomem,
    pub dbg_info_stage_counter: *mut void __iomem,
// decoder registers
    pub d_crc_ctrl: *mut void __iomem,
    pub d_dec_options: *mut void __iomem,
    pub d_display_delay: *mut void __iomem,
    pub d_set_frame_width: *mut void __iomem,
    pub d_set_frame_height: *mut void __iomem,
    pub d_sei_enable: *mut void __iomem,
    pub d_min_num_dpb: *mut void __iomem,
    pub d_min_first_plane_dpb_size: *mut void __iomem,
    pub d_min_second_plane_dpb_size: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_min_third_plane_dpb_size;/ only v8,
    pub d_min_num_mv: *mut void __iomem,
    pub d_mvc_num_views: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_min_num_dis;/ only v7,
    pub /: *mut *mut *mut void __iomem d_min_first_dis_size;/ only v7,
    pub /: *mut *mut *mut void __iomem d_min_second_dis_size;/ only v7,
    pub /: *mut *mut *mut void __iomem d_min_third_dis_size;/ only v7,
    pub /: *mut *mut *mut void __iomem d_post_filter_luma_dpb0;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_post_filter_luma_dpb1;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_post_filter_luma_dpb2;/ only v7,
    pub /: *mut *mut *mut void __iomem d_post_filter_chroma_dpb0;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_post_filter_chroma_dpb1;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_post_filter_chroma_dpb2;/ only v7,
    pub d_num_dpb: *mut void __iomem,
    pub d_num_mv: *mut void __iomem,
    pub d_init_buffer_options: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_first_plane_dpb_stride_size;/ only v8,
    pub /: *mut *mut *mut void __iomem d_second_plane_dpb_stride_size;/ only v8,
    pub /: *mut *mut *mut void __iomem d_third_plane_dpb_stride_size;/ only v8,
    pub d_first_plane_dpb_size: *mut void __iomem,
    pub d_second_plane_dpb_size: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_third_plane_dpb_size;/ only v8,
    pub d_mv_buffer_size: *mut void __iomem,
    pub d_first_plane_dpb: *mut void __iomem,
    pub d_second_plane_dpb: *mut void __iomem,
    pub d_third_plane_dpb: *mut void __iomem,
    pub d_mv_buffer: *mut void __iomem,
    pub d_scratch_buffer_addr: *mut void __iomem,
    pub d_scratch_buffer_size: *mut void __iomem,
    pub d_metadata_buffer_addr: *mut void __iomem,
    pub d_metadata_buffer_size: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_nal_start_options;/ v7 and v8,
    pub d_cpb_buffer_addr: *mut void __iomem,
    pub d_cpb_buffer_size: *mut void __iomem,
    pub d_available_dpb_flag_upper: *mut void __iomem,
    pub d_available_dpb_flag_lower: *mut void __iomem,
    pub d_cpb_buffer_offset: *mut void __iomem,
    pub d_slice_if_enable: *mut void __iomem,
    pub d_picture_tag: *mut void __iomem,
    pub d_stream_data_size: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_dynamic_dpb_flag_upper;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_dynamic_dpb_flag_lower;/ v7 and v8,
    pub d_display_frame_width: *mut void __iomem,
    pub d_display_frame_height: *mut void __iomem,
    pub d_display_status: *mut void __iomem,
    pub d_display_first_plane_addr: *mut void __iomem,
    pub d_display_second_plane_addr: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_display_third_plane_addr;/ only v8,
    pub d_display_frame_type: *mut void __iomem,
    pub d_display_crop_info1: *mut void __iomem,
    pub d_display_crop_info2: *mut void __iomem,
    pub d_display_picture_profile: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_display_luma_crc;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_display_chroma0_crc;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_display_chroma1_crc;/ only v8,
    pub /: *mut *mut *mut void __iomem d_display_luma_crc_top;/ only v6,
    pub /: *mut *mut *mut void __iomem d_display_chroma_crc_top;/ only v6,
    pub /: *mut *mut *mut void __iomem d_display_luma_crc_bot;/ only v6,
    pub /: *mut *mut *mut void __iomem d_display_chroma_crc_bot;/ only v6,
    pub d_display_aspect_ratio: *mut void __iomem,
    pub d_display_extended_ar: *mut void __iomem,
    pub d_decoded_frame_width: *mut void __iomem,
    pub d_decoded_frame_height: *mut void __iomem,
    pub d_decoded_status: *mut void __iomem,
    pub d_decoded_first_plane_addr: *mut void __iomem,
    pub d_decoded_second_plane_addr: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_decoded_third_plane_addr;/ only v8,
    pub d_decoded_frame_type: *mut void __iomem,
    pub d_decoded_crop_info1: *mut void __iomem,
    pub d_decoded_crop_info2: *mut void __iomem,
    pub d_decoded_picture_profile: *mut void __iomem,
    pub d_decoded_nal_size: *mut void __iomem,
    pub d_decoded_luma_crc: *mut void __iomem,
    pub d_decoded_chroma0_crc: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_decoded_chroma1_crc;/ only v8,
    pub d_ret_picture_tag_top: *mut void __iomem,
    pub d_ret_picture_tag_bot: *mut void __iomem,
    pub d_ret_picture_time_top: *mut void __iomem,
    pub d_ret_picture_time_bot: *mut void __iomem,
    pub d_chroma_format: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_vc1_info;/ v7 and v8,
    pub d_mpeg4_info: *mut void __iomem,
    pub d_h264_info: *mut void __iomem,
    pub d_metadata_addr_concealed_mb: *mut void __iomem,
    pub d_metadata_size_concealed_mb: *mut void __iomem,
    pub d_metadata_addr_vc1_param: *mut void __iomem,
    pub d_metadata_size_vc1_param: *mut void __iomem,
    pub d_metadata_addr_sei_nal: *mut void __iomem,
    pub d_metadata_size_sei_nal: *mut void __iomem,
    pub d_metadata_addr_vui: *mut void __iomem,
    pub d_metadata_size_vui: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_metadata_addr_mvcvui;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_metadata_size_mvcvui;/ v7 and v8,
    pub d_mvc_view_id: *mut void __iomem,
    pub d_frame_pack_sei_avail: *mut void __iomem,
    pub d_frame_pack_arrgment_id: *mut void __iomem,
    pub d_frame_pack_sei_info: *mut void __iomem,
    pub d_frame_pack_grid_pos: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem d_display_recovery_sei_info;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_decoded_recovery_sei_info;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_display_first_addr;/ only v7,
    pub /: *mut *mut *mut void __iomem d_display_second_addr;/ only v7,
    pub /: *mut *mut *mut void __iomem d_display_third_addr;/ only v7,
    pub /: *mut *mut *mut void __iomem d_decoded_first_addr;/ only v7,
    pub /: *mut *mut *mut void __iomem d_decoded_second_addr;/ only v7,
    pub /: *mut *mut *mut void __iomem d_decoded_third_addr;/ only v7,
    pub /: *mut *mut *mut void __iomem d_used_dpb_flag_upper;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_used_dpb_flag_lower;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem d_min_scratch_buffer_size; / v10 and v12,
    pub /: *mut *mut *mut void __iomem d_static_buffer_addr; / v10 and v12,
    pub /: *mut *mut *mut void __iomem d_static_buffer_size; / v10 and v12,
// encoder registers
    pub e_frame_width: *mut void __iomem,
    pub e_frame_height: *mut void __iomem,
    pub e_cropped_frame_width: *mut void __iomem,
    pub e_cropped_frame_height: *mut void __iomem,
    pub e_frame_crop_offset: *mut void __iomem,
    pub e_enc_options: *mut void __iomem,
    pub e_picture_profile: *mut void __iomem,
    pub e_vbv_buffer_size: *mut void __iomem,
    pub e_vbv_init_delay: *mut void __iomem,
    pub e_fixed_picture_qp: *mut void __iomem,
    pub e_rc_config: *mut void __iomem,
    pub e_rc_qp_bound: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem e_rc_qp_bound_pb;/ v7 and v8,
    pub e_rc_mode: *mut void __iomem,
    pub e_mb_rc_config: *mut void __iomem,
    pub e_padding_ctrl: *mut void __iomem,
    pub e_air_threshold: *mut void __iomem,
    pub e_mv_hor_range: *mut void __iomem,
    pub e_mv_ver_range: *mut void __iomem,
    pub e_num_dpb: *mut void __iomem,
    pub e_luma_dpb: *mut void __iomem,
    pub e_chroma_dpb: *mut void __iomem,
    pub e_me_buffer: *mut void __iomem,
    pub e_scratch_buffer_addr: *mut void __iomem,
    pub e_scratch_buffer_size: *mut void __iomem,
    pub e_tmv_buffer0: *mut void __iomem,
    pub e_tmv_buffer1: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem e_ir_buffer_addr;/ v7 and v8,
    pub e_source_first_plane_addr: *mut void __iomem,
    pub e_source_second_plane_addr: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem e_source_third_plane_addr;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem e_source_first_plane_stride;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem e_source_second_plane_stride;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem e_source_third_plane_stride;/ v7 and v8,
    pub e_stream_buffer_addr: *mut void __iomem,
    pub e_stream_buffer_size: *mut void __iomem,
    pub e_roi_buffer_addr: *mut void __iomem,
    pub e_param_change: *mut void __iomem,
    pub e_ir_size: *mut void __iomem,
    pub e_gop_config: *mut void __iomem,
    pub e_mslice_mode: *mut void __iomem,
    pub e_mslice_size_mb: *mut void __iomem,
    pub e_mslice_size_bits: *mut void __iomem,
    pub e_frame_insertion: *mut void __iomem,
    pub e_rc_frame_rate: *mut void __iomem,
    pub e_rc_bit_rate: *mut void __iomem,
    pub e_rc_roi_ctrl: *mut void __iomem,
    pub e_picture_tag: *mut void __iomem,
    pub e_bit_count_enable: *mut void __iomem,
    pub e_max_bit_count: *mut void __iomem,
    pub e_min_bit_count: *mut void __iomem,
    pub e_metadata_buffer_addr: *mut void __iomem,
    pub e_metadata_buffer_size: *mut void __iomem,
    pub e_encoded_source_first_plane_addr: *mut void __iomem,
    pub e_encoded_source_second_plane_addr: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem e_encoded_source_third_plane_addr;/ v7 and v8,
    pub e_stream_size: *mut void __iomem,
    pub e_slice_type: *mut void __iomem,
    pub e_picture_count: *mut void __iomem,
    pub e_ret_picture_tag: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem e_stream_buffer_write_pointer; / only v6,
    pub e_recon_luma_dpb_addr: *mut void __iomem,
    pub e_recon_chroma_dpb_addr: *mut void __iomem,
    pub e_metadata_addr_enc_slice: *mut void __iomem,
    pub e_metadata_size_enc_slice: *mut void __iomem,
    pub e_mpeg4_options: *mut void __iomem,
    pub e_mpeg4_hec_period: *mut void __iomem,
    pub e_aspect_ratio: *mut void __iomem,
    pub e_extended_sar: *mut void __iomem,
    pub e_h264_options: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem e_h264_options_2;/ v7 and v8,
    pub e_h264_lf_alpha_offset: *mut void __iomem,
    pub e_h264_lf_beta_offset: *mut void __iomem,
    pub e_h264_i_period: *mut void __iomem,
    pub e_h264_fmo_slice_grp_map_type: *mut void __iomem,
    pub e_h264_fmo_num_slice_grp_minus1: *mut void __iomem,
    pub e_h264_fmo_slice_grp_change_dir: *mut void __iomem,
    pub e_h264_fmo_slice_grp_change_rate_minus1: *mut void __iomem,
    pub e_h264_fmo_run_length_minus1_0: *mut void __iomem,
    pub e_h264_aso_slice_order_0: *mut void __iomem,
    pub e_h264_chroma_qp_offset: *mut void __iomem,
    pub e_h264_num_t_layer: *mut void __iomem,
    pub e_h264_hierarchical_qp_layer0: *mut void __iomem,
    pub e_h264_frame_packing_sei_info: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem e_h264_nal_control;/ v7 and v8,
    pub e_mvc_frame_qp_view1: *mut void __iomem,
    pub e_mvc_rc_bit_rate_view1: *mut void __iomem,
    pub e_mvc_rc_qbound_view1: *mut void __iomem,
    pub e_mvc_rc_mode_view1: *mut void __iomem,
    pub e_mvc_inter_view_prediction_on: *mut void __iomem,
    pub /: *mut *mut *mut void __iomem e_vp8_options;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem e_vp8_filter_options;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem e_vp8_golden_frame_option;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem e_vp8_num_t_layer;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem e_vp8_hierarchical_qp_layer0;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem e_vp8_hierarchical_qp_layer1;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem e_vp8_hierarchical_qp_layer2;/ v7 and v8,
    pub /: *mut *mut *mut void __iomem e_min_scratch_buffer_size; / v10 and v12,
    pub /: *mut *mut *mut void __iomem e_num_t_layer; / v10,
    pub /: *mut *mut *mut void __iomem e_hier_qp_layer0; / v10,
    pub /: *mut *mut *mut void __iomem e_hier_bit_rate_layer0; / v10,
    pub /: *mut *mut *mut void __iomem e_hevc_options; / v10,
    pub /: *mut *mut *mut void __iomem e_hevc_refresh_period; / v10,
    pub /: *mut *mut *mut void __iomem e_hevc_lf_beta_offset_div2; / v10,
    pub /: *mut *mut *mut void __iomem e_hevc_lf_tc_offset_div2; / v10,
    pub /: *mut *mut *mut void __iomem e_hevc_nal_control; / v10,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct s5p_mfc_hw_ops {
    pub ctx): *mut *mut int (alloc_dec_temp_buffers)(struct s5p_mfc_ctx,
    pub ctx): *mut *mut void (release_dec_desc_buffer)(struct s5p_mfc_ctx,
    pub ctx): *mut *mut int (alloc_codec_buffers)(struct s5p_mfc_ctx,
    pub ctx): *mut *mut void (release_codec_buffers)(struct s5p_mfc_ctx,
    pub ctx): *mut *mut int (alloc_instance_buffer)(struct s5p_mfc_ctx,
    pub ctx): *mut *mut void (release_instance_buffer)(struct s5p_mfc_ctx,
    pub dev): *mut *mut int (alloc_dev_context_buffer)(struct s5p_mfc_dev,
    pub dev): *mut *mut void (release_dev_context_buffer)(struct s5p_mfc_dev,
    pub ctx): *mut *mut void (dec_calc_dpb_size)(struct s5p_mfc_ctx,
    pub ctx): *mut *mut void (enc_calc_src_size)(struct s5p_mfc_ctx,
    pub size): unsigned long addr, unsigned int,
    pub c_1_addr): c_ulong,
    pub c_1_addr): *mut c_ulong,
    pub dev): *mut *mut void (try_run)(struct s5p_mfc_dev,
    pub dev): *mut *mut void (clear_int_flags)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_dspl_y_adr)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_dec_y_adr)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_dspl_status)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_dec_status)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_dec_frame_type)(struct s5p_mfc_dev,
    pub ctx): *mut *mut int (get_disp_frame_type)(struct s5p_mfc_ctx,
    pub dev): *mut *mut int (get_consumed_stream)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_int_reason)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_int_err)(struct s5p_mfc_dev,
    pub err): *mut *mut int (err_dec)(unsigned int,
    pub dev): *mut *mut int (get_img_width)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_img_height)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_dpb_count)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_mv_count)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_inst_no)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_enc_strm_size)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_enc_slice_type)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_enc_dpb_count)(struct s5p_mfc_dev,
    pub ctx): *mut *mut unsigned int (get_pic_type_top)(struct s5p_mfc_ctx,
    pub ctx): *mut *mut unsigned int (get_pic_type_bot)(struct s5p_mfc_ctx,
    pub ctx): *mut *mut unsigned int (get_crop_info_h)(struct s5p_mfc_ctx,
    pub ctx): *mut *mut unsigned int (get_crop_info_v)(struct s5p_mfc_ctx,
    pub dev): *mut *mut int (get_min_scratch_buf_size)(struct s5p_mfc_dev,
    pub dev): *mut *mut int (get_e_min_scratch_buf_size)(struct s5p_mfc_dev,
}

extern "C" {
    pub fn s5p_mfc_init_hw_ops(dev: *mut s5p_mfc_dev);
}
extern "C" {
    pub fn s5p_mfc_init_regs(dev: *mut s5p_mfc_dev);
}
