//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/amd/display/dc/dml/display_mode_vba.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// Copyright 2017 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// Authors: AMD
//
extern "C" {
    pub fn ModeSupportAndSystemConfiguration(mode_lib: *mut display_mode_lib);
}

extern "C" {
    pub fn PixelClockAdjustmentForProgressiveToInterlaceUnit(mode_lib: *mut display_mode_lib);
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct DISPCLKDPPCLKDCFCLKDeepSleepPrefetchParametersWatermarksAndPerformanceCalculation {
    pub dummy_integer_array: [c_uint; 2][DC__NUM_DPP__MAX],
    pub dummy_single_array: [double; 2][DC__NUM_DPP__MAX],
    pub dummy_long_array: [c_uint; 2][DC__NUM_DPP__MAX],
    pub dummy_double_array: [double; 2][DC__NUM_DPP__MAX],
    pub dummy_boolean_array: [bool; DC__NUM_DPP__MAX],
    pub dummy_boolean: bool,
    pub dummy_boolean2: bool,
    pub dummy_output_encoder_array: [output_encoder_class; DC__NUM_DPP__MAX],
    pub SurfaceParameters: [DmlPipe; DC__NUM_DPP__MAX],
    pub dummy_boolean_array2: [bool; 2][DC__NUM_DPP__MAX],
    pub ReorderBytes: c_uint,
    pub VMDataOnlyReturnBW: c_uint,
    pub HostVMInefficiencyFactor: double,
    pub myPipe: DmlPipe,
    pub mmSOCParameters: SOCParametersList,
    pub dummy_unit_vector: [double; DC__NUM_DPP__MAX],
    pub dummy_single: [double; 2],
    pub dummy_dramchange_support: clock_change_support,
    pub dummy_fclkchange_support: dm_fclock_change_support,
    pub dummy_USRRetrainingSupport: bool,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct dml32_ModeSupportAndSystemConfigurationFull {
    pub dummy_integer_array: [c_uint; 22][DC__NUM_DPP__MAX],
    pub dummy_double_array: [double; 2][DC__NUM_DPP__MAX],
    pub SurfParameters: [DmlPipe; DC__NUM_DPP__MAX],
    pub dummy_single: [double; 5],
    pub dummy_single2: [double; 5],
    pub mSOCParameters: SOCParametersList,
    pub MaximumSwathWidthSupportLuma: c_uint,
    pub MaximumSwathWidthSupportChroma: c_uint,
    pub DSTYAfterScaler: [double; DC__NUM_DPP__MAX],
    pub DSTXAfterScaler: [double; DC__NUM_DPP__MAX],
    pub MaxTotalVActiveRDBandwidth: double,
    pub dummy_boolean_array: [bool; 2][DC__NUM_DPP__MAX],
    pub dummy_odm_mode: [odm_combine_mode; DC__NUM_DPP__MAX],
    pub myPipe: DmlPipe,
    pub dummy_integer: [c_uint; 4],
    pub TotalNumberOfActiveOTG: c_uint,
    pub TotalNumberOfActiveHDMIFRL: c_uint,
    pub TotalNumberOfActiveDP2p0: c_uint,
    pub TotalNumberOfActiveDP2p0Outputs: c_uint,
    pub TotalDSCUnitsRequired: c_uint,
    pub ReorderingBytes: c_uint,
    pub TotalSlots: c_uint,
    pub NumberOfDPPDSC: c_uint,
    pub NumberOfDPPNoDSC: c_uint,
    pub NextPrefetchModeState: c_uint,
    pub MPCCombineMethodAsNeededForPStateChangeAndVoltage: bool,
    pub MPCCombineMethodAsPossible: bool,
    pub FullFrameMALLPStateMethod: bool,
    pub SubViewportMALLPStateMethod: bool,
    pub PhantomPipeMALLPStateMethod: bool,
    pub NoChroma: bool,
    pub TotalAvailablePipesSupportNoDSC: bool,
    pub TotalAvailablePipesSupportDSC: bool,
    pub ODMModeNoDSC: odm_combine_mode,
    pub ODMModeDSC: odm_combine_mode,
    pub RequiredDISPCLKPerSurfaceNoDSC: double,
    pub RequiredDISPCLKPerSurfaceDSC: double,
    pub BWOfNonCombinedSurfaceOfMaximumBandwidth: double,
    pub VMDataOnlyReturnBWPerState: double,
    pub HostVMInefficiencyFactor: double,
    pub dummy_boolean: [bool; 2],
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct dummy_vars {
    pub dml32_ModeSupportAndSystemConfigurationFull: dml32_ModeSupportAndSystemConfigurationFull,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct vba_vars_st {
    pub ip: ip_params_st,
    pub soc: soc_bounding_box_st,
    pub maxMpcComb: c_int,
    pub UseMaximumVStartup: bool,
    pub MaxVRatioPre: double,
    pub WritebackDISPCLK: double,
    pub DPPCLKUsingSingleDPPLuma: double,
    pub DPPCLKUsingSingleDPPChroma: double,
    pub DISPCLKWithRamping: double,
    pub DISPCLKWithoutRamping: double,
    pub GlobalDPPCLK: double,
    pub DISPCLKWithRampingRoundedToDFSGranularity: double,
    pub DISPCLKWithoutRampingRoundedToDFSGranularity: double,
    pub MaxDispclkRoundedToDFSGranularity: double,
    pub DCCEnabledAnyPlane: bool,
    pub ReturnBandwidthToDCN: double,
    pub TotalActiveDPP: c_uint,
    pub TotalDCCActiveDPP: c_uint,
    pub UrgentRoundTripAndOutOfOrderLatency: double,
    pub StutterPeriod: double,
    pub FrameTimeForMinFullDETBufferingTime: double,
    pub AverageReadBandwidth: double,
    pub TotalRowReadBandwidth: double,
    pub PartOfBurstThatFitsInROB: double,
    pub StutterBurstTime: double,
    pub NextPrefetchMode: c_uint,
    pub NextMaxVStartup: double,
    pub VBlankTime: double,
    pub SmallestVBlank: double,
    pub only: dm_prefetch_modes AllowForPStateChangeOrStutterInVBlankFinal; // Mode Support,
    pub DCFCLKDeepSleepPerPlane: [double; DC__NUM_DPP__MAX],
    pub EffectiveDETPlusLBLinesLuma: double,
    pub EffectiveDETPlusLBLinesChroma: double,
    pub UrgentLatencySupportUsLuma: double,
    pub UrgentLatencySupportUsChroma: double,
    pub DSCFormatFactor: c_uint,
    pub DummyPStateCheck: bool,
    pub DRAMClockChangeSupportsVActive: bool,
    pub PrefetchModeSupported: bool,
    pub PrefetchAndImmediateFlipSupported: bool,
    pub only: self_refresh_affinity AllowDRAMSelfRefreshOrDRAMClockChangeInVblank; // Mode Support,
    pub XFCRemoteSurfaceFlipDelay: double,
    pub TInitXFill: double,
    pub TslvChk: double,
    pub SrcActiveDrainRate: double,
    pub ImmediateFlipSupported: bool,
    pub only: mpc_combine_affinity WhenToDoMPCCombine; // Mode Support,
    pub PrefetchERROR: bool,
    pub VStartupLines: c_uint,
    pub ActiveDPPs: c_uint,
    pub LBLatencyHidingSourceLinesY: c_uint,
    pub LBLatencyHidingSourceLinesC: c_uint,
    pub state: double ActiveDRAMClockChangeLatencyMarginPerState[DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX];// DML doesn't save active margin per,
    pub ActiveDRAMClockChangeLatencyMargin: [double; DC__NUM_DPP__MAX],
    pub only: double CachedActiveDRAMClockChangeLatencyMargin[DC__NUM_DPP__MAX]; // Cache in dml_get_voltage_level for debug purposes,
    pub MinActiveDRAMClockChangeMargin: double,
    pub InitFillLevel: double,
    pub FinalFillMargin: double,
    pub FinalFillLevel: double,
    pub RemainingFillLevel: double,
    pub TFinalxFill: double,
//
// SOC Bounding Box Parameters
//
    pub SRExitTime: double,
    pub SREnterPlusExitTime: double,
    pub UrgentLatencyPixelDataOnly: double,
    pub UrgentLatencyPixelMixedWithVMData: double,
    pub UrgentLatencyVMDataOnly: double,
    pub three: double UrgentLatency; // max of the above,
    pub USRRetrainingLatency: double,
    pub SMNLatency: double,
    pub FCLKChangeLatency: double,
    pub MALLAllocatedForDCNFinal: c_uint,
    pub MaxAveragePercentOfIdealFabricBWDisplayCanUseInNormalSystemOperation: double,
    pub MaxAveragePercentOfIdealDRAMBWDisplayCanUseInNormalSystemOperationSTROBE: double,
    pub PercentOfIdealDRAMBWReceivedAfterUrgLatencySTROBE: double,
    pub WritebackLatency: double,
    pub Support: double PercentOfIdealDRAMFabricAndSDPPortBWReceivedAfterUrgLatencyPixelDataOnly; // Mode,
    pub Support: double PercentOfIdealDRAMFabricAndSDPPortBWReceivedAfterUrgLatencyPixelMixedWithVMData; // Mode,
    pub Support: double PercentOfIdealDRAMFabricAndSDPPortBWReceivedAfterUrgLatencyVMDataOnly; // Mode,
    pub Support: double MaxAveragePercentOfIdealSDPPortBWDisplayCanUseInNormalSystemOperation; // Mode,
    pub Support: double MaxAveragePercentOfIdealDRAMBWDisplayCanUseInNormalSystemOperation; // Mode,
    pub NumberOfChannels: double,
    pub DRAMChannelWidth: double,
    pub FabricDatapathToDCNDataReturn: double,
    pub ReturnBusWidth: double,
    pub Downspreading: double,
    pub DISPCLKDPPCLKDSCCLKDownSpreading: double,
    pub DISPCLKDPPCLKVCOSpeed: double,
    pub RoundTripPingLatencyCycles: double,
    pub UrgentOutOfOrderReturnPerChannel: double,
    pub UrgentOutOfOrderReturnPerChannelPixelDataOnly: double,
    pub UrgentOutOfOrderReturnPerChannelPixelMixedWithVMData: double,
    pub UrgentOutOfOrderReturnPerChannelVMDataOnly: double,
    pub VMMPageSize: c_uint,
    pub DRAMClockChangeLatency: double,
    pub XFCBusTransportTime: double,
    pub UseUrgentBurstBandwidth: bool,
    pub XFCXBUFLatencyTolerance: double,
//
// IP Parameters
//
    pub ROBBufferSizeInKByte: c_uint,
    pub DETBufferSizeInKByte: [c_uint; DC__NUM_DPP__MAX],
    pub DETBufferSizeInTime: double,
    pub DPPOutputBufferPixels: c_uint,
    pub OPPOutputBufferLines: c_uint,
    pub PixelChunkSizeInKByte: c_uint,
    pub ReturnBW: double,
    pub GPUVMEnable: bool,
    pub HostVMEnable: bool,
    pub GPUVMMaxPageTableLevels: c_uint,
    pub HostVMMaxPageTableLevels: c_uint,
    pub HostVMCachedPageTableLevels: c_uint,
    pub OverrideGPUVMPageTableLevels: c_uint,
    pub OverrideHostVMPageTableLevels: c_uint,
    pub MetaChunkSize: c_uint,
    pub MinMetaChunkSizeBytes: c_uint,
    pub WritebackChunkSize: c_uint,
    pub ODMCapability: bool,
    pub NumberOfDSC: c_uint,
    pub LineBufferSize: c_uint,
    pub MaxLineBufferLines: c_uint,
    pub WritebackInterfaceLumaBufferSize: c_uint,
    pub WritebackInterfaceChromaBufferSize: c_uint,
    pub WritebackChromaLineBufferWidth: c_uint,
    pub WritebackConfiguration: writeback_config,
    pub MaxDCHUBToPSCLThroughput: double,
    pub MaxPSCLToLBThroughput: double,
    pub PTEBufferSizeInRequestsLuma: c_uint,
    pub PTEBufferSizeInRequestsChroma: c_uint,
    pub DISPCLKRampingMargin: double,
    pub MaxInterDCNTileRepeaters: c_uint,
    pub XFCSupported: bool,
    pub XFCSlvChunkSize: double,
    pub XFCFillBWOverhead: double,
    pub XFCFillConstant: double,
    pub XFCTSlvVupdateOffset: double,
    pub XFCTSlvVupdateWidth: double,
    pub XFCTSlvVreadyOffset: double,
    pub DPPCLKDelaySubtotal: double,
    pub DPPCLKDelaySCL: double,
    pub DPPCLKDelaySCLLBOnly: double,
    pub DPPCLKDelayCNVCFormater: double,
    pub DPPCLKDelayCNVCCursor: double,
    pub DISPCLKDelaySubtotal: double,
    pub ProgressiveToInterlaceUnitInOPP: bool,
    pub CompressedBufferSegmentSizeInkByteFinal: c_uint,
    pub CompbufReservedSpace64B: c_uint,
    pub CompbufReservedSpaceZs: c_uint,
    pub LineBufferSizeFinal: c_uint,
    pub MaximumPixelsPerLinePerDSCUnit: c_uint,
    pub AlphaPixelChunkSizeInKByte: c_uint,
    pub MinPixelChunkSizeBytes: double,
    pub DCCMetaBufferSizeBytes: c_uint,
// Pipe/Plane Parameters
// @VoltageLevel:
// Every ASIC has a fixed number of DPM states, and some devices might
// have some particular voltage configuration that does not map
// directly to the DPM states. This field tells how many states the
// target device supports; even though this field combines the DPM and
// special SOC voltages, it mostly matches the total number of DPM
// states.
//
    pub VoltageLevel: c_int,
    pub FabricClock: double,
    pub DRAMSpeed: double,
    pub DISPCLK: double,
    pub SOCCLK: double,
    pub DCFCLK: double,
    pub MaxTotalDETInKByte: c_uint,
    pub MinCompressedBufferSizeInKByte: c_uint,
    pub NumberOfActiveSurfaces: c_uint,
    pub ViewportStationary: [bool; DC__NUM_DPP__MAX],
    pub RefreshRate: [c_uint; DC__NUM_DPP__MAX],
    pub OutputBPP: [double; DC__NUM_DPP__MAX],
    pub GPUVMMinPageSizeKBytes: [c_uint; DC__NUM_DPP__MAX],
    pub SynchronizeTimingsFinal: bool,
    pub SynchronizeDRRDisplaysForUCLKPStateChangeFinal: bool,
    pub ForceOneRowForFrame: [bool; DC__NUM_DPP__MAX],
    pub ViewportXStartY: [c_uint; DC__NUM_DPP__MAX],
    pub ViewportXStartC: [c_uint; DC__NUM_DPP__MAX],
    pub SourceRotation: [dm_rotation_angle; DC__NUM_DPP__MAX],
    pub DRRDisplay: [bool; DC__NUM_DPP__MAX],
    pub PteBufferMode: [bool; DC__NUM_DPP__MAX],
    pub OutputType: [dm_output_type; DC__NUM_DPP__MAX],
    pub OutputRate: [dm_output_rate; DC__NUM_DPP__MAX],
    pub NumberOfActivePlanes: c_uint,
    pub NumberOfDSCSlices: [c_uint; DC__NUM_DPP__MAX],
    pub ViewportWidth: [c_uint; DC__NUM_DPP__MAX],
    pub ViewportHeight: [c_uint; DC__NUM_DPP__MAX],
    pub ViewportYStartY: [c_uint; DC__NUM_DPP__MAX],
    pub ViewportYStartC: [c_uint; DC__NUM_DPP__MAX],
    pub PitchY: [c_uint; DC__NUM_DPP__MAX],
    pub PitchC: [c_uint; DC__NUM_DPP__MAX],
    pub HRatio: [double; DC__NUM_DPP__MAX],
    pub VRatio: [double; DC__NUM_DPP__MAX],
    pub htaps: [c_uint; DC__NUM_DPP__MAX],
    pub vtaps: [c_uint; DC__NUM_DPP__MAX],
    pub HTAPsChroma: [c_uint; DC__NUM_DPP__MAX],
    pub VTAPsChroma: [c_uint; DC__NUM_DPP__MAX],
    pub HTotal: [c_uint; DC__NUM_DPP__MAX],
    pub VTotal: [c_uint; DC__NUM_DPP__MAX],
    pub VTotal_Max: [c_uint; DC__NUM_DPP__MAX],
    pub VTotal_Min: [c_uint; DC__NUM_DPP__MAX],
    pub DPPPerPlane: [c_uint; DC__NUM_DPP__MAX],
    pub PixelClock: [double; DC__NUM_DPP__MAX],
    pub PixelClockBackEnd: [double; DC__NUM_DPP__MAX],
    pub DCCEnable: [bool; DC__NUM_DPP__MAX],
    pub FECEnable: [bool; DC__NUM_DPP__MAX],
    pub DCCMetaPitchY: [c_uint; DC__NUM_DPP__MAX],
    pub DCCMetaPitchC: [c_uint; DC__NUM_DPP__MAX],
    pub SourceScan: [scan_direction_class; DC__NUM_DPP__MAX],
    pub SourcePixelFormat: [source_format_class; DC__NUM_DPP__MAX],
    pub WritebackEnable: [bool; DC__NUM_DPP__MAX],
    pub ActiveWritebacksPerPlane: [c_uint; DC__NUM_DPP__MAX],
    pub WritebackDestinationWidth: [double; DC__NUM_DPP__MAX],
    pub WritebackDestinationHeight: [double; DC__NUM_DPP__MAX],
    pub WritebackSourceHeight: [double; DC__NUM_DPP__MAX],
    pub WritebackPixelFormat: [source_format_class; DC__NUM_DPP__MAX],
    pub WritebackLumaHTaps: [c_uint; DC__NUM_DPP__MAX],
    pub WritebackLumaVTaps: [c_uint; DC__NUM_DPP__MAX],
    pub WritebackChromaHTaps: [c_uint; DC__NUM_DPP__MAX],
    pub WritebackChromaVTaps: [c_uint; DC__NUM_DPP__MAX],
    pub WritebackHRatio: [double; DC__NUM_DPP__MAX],
    pub WritebackVRatio: [double; DC__NUM_DPP__MAX],
    pub HActive: [c_uint; DC__NUM_DPP__MAX],
    pub VActive: [c_uint; DC__NUM_DPP__MAX],
    pub Interlace: [bool; DC__NUM_DPP__MAX],
    pub SurfaceTiling: [dm_swizzle_mode; DC__NUM_DPP__MAX],
    pub ScalerRecoutWidth: [c_uint; DC__NUM_DPP__MAX],
    pub DynamicMetadataEnable: [bool; DC__NUM_DPP__MAX],
    pub DynamicMetadataLinesBeforeActiveRequired: [c_int; DC__NUM_DPP__MAX],
    pub DynamicMetadataTransmittedBytes: [c_uint; DC__NUM_DPP__MAX],
    pub DCCRate: [double; DC__NUM_DPP__MAX],
    pub AverageDCCCompressionRate: double,
    pub ODMCombineEnabled: [odm_combine_mode; DC__NUM_DPP__MAX],
    pub OutputBpp: [double; DC__NUM_DPP__MAX],
    pub DSCEnabled: [bool; DC__NUM_DPP__MAX],
    pub DSCInputBitPerComponent: [c_uint; DC__NUM_DPP__MAX],
    pub OutputFormat: [output_format_class; DC__NUM_DPP__MAX],
    pub Output: [output_encoder_class; DC__NUM_DPP__MAX],
    pub skip_dio_check: [bool; DC__NUM_DPP__MAX],
    pub BlendingAndTiming: [c_uint; DC__NUM_DPP__MAX],
    pub SynchronizedVBlank: bool,
    pub NumberOfCursors: [c_uint; DC__NUM_DPP__MAX],
    pub CursorWidth: [c_uint; DC__NUM_DPP__MAX][DC__NUM_CURSOR__MAX],
    pub CursorBPP: [c_uint; DC__NUM_DPP__MAX][DC__NUM_CURSOR__MAX],
    pub XFCEnabled: [bool; DC__NUM_DPP__MAX],
    pub ScalerEnabled: [bool; DC__NUM_DPP__MAX],
    pub VBlankNom: [c_uint; DC__NUM_DPP__MAX],
    pub DisableUnboundRequestIfCompBufReservedSpaceNeedAdjustment: bool,
// Intermediates/Informational
    pub ImmediateFlipSupport: bool,
    pub DETBufferSizeY: [c_uint; DC__NUM_DPP__MAX],
    pub DETBufferSizeC: [c_uint; DC__NUM_DPP__MAX],
    pub SwathHeightY: [c_uint; DC__NUM_DPP__MAX],
    pub SwathHeightC: [c_uint; DC__NUM_DPP__MAX],
    pub LBBitPerPixel: [c_uint; DC__NUM_DPP__MAX],
    pub LastPixelOfLineExtraWatermark: double,
    pub TotalDataReadBandwidth: double,
    pub TotalActiveWriteback: c_uint,
    pub EffectiveLBLatencyHidingSourceLinesLuma: c_uint,
    pub EffectiveLBLatencyHidingSourceLinesChroma: c_uint,
    pub BandwidthAvailableForImmediateFlip: double,
    pub PrefetchMode: [c_uint; DC__VOLTAGE_STATES][2],
    pub PrefetchModePerState: [c_uint; DC__VOLTAGE_STATES][2],
    pub MinPrefetchMode: c_uint,
    pub MaxPrefetchMode: c_uint,
    pub AnyLinesForVMOrRowTooLarge: bool,
    pub MaxVStartup: double,
    pub IgnoreViewportPositioning: bool,
    pub ErrorResult: [bool; DC__NUM_DPP__MAX],
//
// Calculated dml_ml->vba.Outputs
//
    pub DCFCLKDeepSleep: double,
    pub UrgentWatermark: double,
    pub UrgentExtraLatency: double,
    pub WritebackUrgentWatermark: double,
    pub StutterExitWatermark: double,
    pub StutterEnterPlusExitWatermark: double,
    pub DRAMClockChangeWatermark: double,
    pub WritebackDRAMClockChangeWatermark: double,
    pub StutterEfficiency: double,
    pub StutterEfficiencyNotIncludingVBlank: double,
    pub NonUrgentLatencyTolerance: double,
    pub MinActiveDRAMClockChangeLatencySupported: double,
    pub Z8StutterEfficiencyBestCase: double,
    pub Z8NumberOfStutterBurstsPerFrameBestCase: c_uint,
    pub Z8StutterEfficiencyNotIncludingVBlankBestCase: double,
    pub StutterPeriodBestCase: double,
    pub Watermark: Watermarks,
    pub DCHUBBUB_ARB_CSTATE_MAX_CAP_MODE: bool,
    pub CompBufReservedSpaceKBytes: c_uint,
    pub CompBufReservedSpace64B: c_uint,
    pub CompBufReservedSpaceZs: c_uint,
    pub CompBufReservedSpaceNeedAdjustment: bool,
// These are the clocks calcuated by the library but they are not actually
// used explicitly. They are fetched by tests and then possibly used. The
// ultimate values to use are the ones specified by the parameters to DML
    pub DISPCLK_calculated: double,
    pub DPPCLK_calculated: [double; DC__NUM_DPP__MAX],
    pub ImmediateFlipSupportedSurface: [bool; DC__NUM_DPP__MAX],
    pub Use_One_Row_For_Frame: [bool; DC__NUM_DPP__MAX],
    pub Use_One_Row_For_Frame_Flip: [bool; DC__NUM_DPP__MAX],
    pub VUpdateOffsetPix: [c_uint; DC__NUM_DPP__MAX],
    pub VUpdateWidthPix: [double; DC__NUM_DPP__MAX],
    pub VReadyOffsetPix: [double; DC__NUM_DPP__MAX],
    pub TotImmediateFlipBytes: c_uint,
    pub TCalc: double,
    pub cache_pipes: [display_e2e_pipe_params_st; DC__NUM_DPP__MAX],
    pub cache_num_pipes: c_uint,
    pub pipe_plane: [c_uint; DC__NUM_DPP__MAX],
// vba mode support
// inputs
    pub SupportGFX7CompatibleTilingIn32bppAnd64bpp: bool,
    pub MaxHSCLRatio: double,
    pub MaxVSCLRatio: double,
    pub MaxNumWriteback: c_uint,
    pub WritebackLumaAndChromaScalingSupported: bool,
    pub Cursor64BppSupport: bool,
    pub DCFCLKPerState: [double; DC__VOLTAGE_STATES],
    pub DCFCLKState: [double; DC__VOLTAGE_STATES][2],
    pub FabricClockPerState: [double; DC__VOLTAGE_STATES],
    pub SOCCLKPerState: [double; DC__VOLTAGE_STATES],
    pub PHYCLKPerState: [double; DC__VOLTAGE_STATES],
    pub DTBCLKPerState: [double; DC__VOLTAGE_STATES],
    pub MaxDppclk: [double; DC__VOLTAGE_STATES],
    pub MaxDSCCLK: [double; DC__VOLTAGE_STATES],
    pub DRAMSpeedPerState: [double; DC__VOLTAGE_STATES],
    pub MaxDispclk: [double; DC__VOLTAGE_STATES],
    pub VoltageOverrideLevel: c_int,
    pub PHYCLKD32PerState: [double; DC__VOLTAGE_STATES],
// outputs
    pub ScaleRatioAndTapsSupport: bool,
    pub SourceFormatPixelAndScanSupport: bool,
    pub TotalBandwidthConsumedGBytePerSecond: double,
    pub DCCEnabledInAnyPlane: bool,
    pub WritebackLatencySupport: bool,
    pub WritebackModeSupport: bool,
    pub Writeback10bpc420Supported: bool,
    pub BandwidthSupport: [bool; DC__VOLTAGE_STATES],
    pub TotalNumberOfActiveWriteback: c_uint,
    pub CriticalPoint: double,
    pub ReturnBWToDCNPerState: double,
    pub IsErrorResult: [bool; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub prefetch_vm_bw_valid: bool,
    pub prefetch_row_bw_valid: bool,
    pub NumberOfOTGSupport: bool,
    pub NonsupportedDSCInputBPC: bool,
    pub WritebackScaleRatioAndTapsSupport: bool,
    pub CursorSupport: bool,
    pub PitchSupport: bool,
    pub ValidationStatus: [dm_validation_status; DC__VOLTAGE_STATES],
// Mode Support Reason
    pub P2IWith420: bool,
    pub DSCOnlyIfNecessaryWithBPP: bool,
    pub DSC422NativeNotSupported: bool,
    pub LinkRateDoesNotMatchDPVersion: bool,
    pub LinkRateForMultistreamNotIndicated: bool,
    pub BPPForMultistreamNotIndicated: bool,
    pub MultistreamWithHDMIOreDP: bool,
    pub MSOOrODMSplitWithNonDPLink: bool,
    pub NotEnoughLanesForMSO: bool,
    pub ViewportExceedsSurface: bool,
    pub ImmediateFlipRequiredButTheRequirementForEachSurfaceIsNotSpecified: bool,
    pub ImmediateFlipOrHostVMAndPStateWithMALLFullFrameOrPhantomPipe: bool,
    pub InvalidCombinationOfMALLUseForPStateAndStaticScreen: bool,
    pub InvalidCombinationOfMALLUseForPState: bool,
    pub OutputLinkDPRate: [dm_output_link_dp_rate; DC__NUM_DPP__MAX],
    pub PrefetchLinesYThisState: [double; DC__NUM_DPP__MAX],
    pub PrefetchLinesCThisState: [double; DC__NUM_DPP__MAX],
    pub meta_row_bandwidth_this_state: [double; DC__NUM_DPP__MAX],
    pub dpte_row_bandwidth_this_state: [double; DC__NUM_DPP__MAX],
    pub DPTEBytesPerRowThisState: [double; DC__NUM_DPP__MAX],
    pub PDEAndMetaPTEBytesPerFrameThisState: [double; DC__NUM_DPP__MAX],
    pub MetaRowBytesThisState: [double; DC__NUM_DPP__MAX],
    pub use_one_row_for_frame: [bool; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub use_one_row_for_frame_flip: [bool; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub use_one_row_for_frame_this_state: [bool; DC__NUM_DPP__MAX],
    pub use_one_row_for_frame_flip_this_state: [bool; DC__NUM_DPP__MAX],
    pub OutputTypeAndRatePerState: [c_uint; DC__VOLTAGE_STATES][DC__NUM_DPP__MAX],
    pub RequiredDISPCLKPerSurface: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub MacroTileHeightY: [c_uint; DC__NUM_DPP__MAX],
    pub MacroTileHeightC: [c_uint; DC__NUM_DPP__MAX],
    pub MacroTileWidthY: [c_uint; DC__NUM_DPP__MAX],
    pub MacroTileWidthC: [c_uint; DC__NUM_DPP__MAX],
    pub ImmediateFlipRequiredFinal: bool,
    pub DCCProgrammingAssumesScanDirectionUnknownFinal: bool,
    pub EnoughWritebackUnits: bool,
    pub ODMCombine2To1SupportCheckOK: [bool; DC__VOLTAGE_STATES],
    pub NumberOfDP2p0Support: bool,
    pub MaxNumDP2p0Streams: c_uint,
    pub MaxNumDP2p0Outputs: c_uint,
    pub OutputTypePerState: [dm_output_type; DC__VOLTAGE_STATES][DC__NUM_DPP__MAX],
    pub OutputRatePerState: [dm_output_rate; DC__VOLTAGE_STATES][DC__NUM_DPP__MAX],
    pub WritebackLineBufferLumaBufferSize: double,
    pub WritebackLineBufferChromaBufferSize: double,
    pub WritebackMinHSCLRatio: double,
    pub WritebackMinVSCLRatio: double,
    pub WritebackMaxHSCLRatio: double,
    pub WritebackMaxVSCLRatio: double,
    pub WritebackMaxHSCLTaps: double,
    pub WritebackMaxVSCLTaps: double,
    pub MaxNumDPP: c_uint,
    pub MaxNumOTG: c_uint,
    pub CursorBufferSize: double,
    pub CursorChunkSize: double,
    pub Mode: c_uint,
    pub OutputLinkDPLanes: [double; DC__NUM_DPP__MAX],
    pub only: double ForcedOutputLinkBPP[DC__NUM_DPP__MAX]; // Mode Support,
    pub ImmediateFlipBW: [double; DC__NUM_DPP__MAX],
    pub MaxMaxVStartup: [double; DC__VOLTAGE_STATES][2],
    pub WritebackLumaVExtra: double,
    pub WritebackChromaVExtra: double,
    pub WritebackRequiredDISPCLK: double,
    pub MaximumSwathWidthSupport: double,
    pub MaximumSwathWidthInDETBuffer: double,
    pub MaximumSwathWidthInLineBuffer: double,
    pub MaxDispclkRoundedDownToDFSGranularity: double,
    pub MaxDppclkRoundedDownToDFSGranularity: double,
    pub PlaneRequiredDISPCLKWithoutODMCombine: double,
    pub PlaneRequiredDISPCLKWithODMCombine: double,
    pub PlaneRequiredDISPCLK: double,
    pub TotalNumberOfActiveOTG: double,
    pub FECOverhead: double,
    pub EffectiveFECOverhead: double,
    pub Outbpp: double,
    pub OutbppDSC: c_uint,
    pub TotalDSCUnitsRequired: double,
    pub bpp: double,
    pub slices: c_uint,
    pub SwathWidthGranularityY: double,
    pub RoundedUpMaxSwathSizeBytesY: double,
    pub SwathWidthGranularityC: double,
    pub RoundedUpMaxSwathSizeBytesC: double,
    pub EffectiveDETLBLinesLuma: double,
    pub EffectiveDETLBLinesChroma: double,
    pub ProjectedDCFCLKDeepSleep: [double; DC__VOLTAGE_STATES][2],
    pub PDEAndMetaPTEBytesPerFrameY: double,
    pub PDEAndMetaPTEBytesPerFrameC: double,
    pub MetaRowBytesY: c_uint,
    pub MetaRowBytesC: c_uint,
    pub DPTEBytesPerRowC: c_uint,
    pub DPTEBytesPerRowY: c_uint,
    pub ExtraLatency: double,
    pub TimeCalc: double,
    pub TWait: double,
    pub MaximumReadBandwidthWithPrefetch: double,
    pub MaximumReadBandwidthWithoutPrefetch: double,
    pub total_dcn_read_bw_with_flip: double,
    pub total_dcn_read_bw_with_flip_no_urgent_burst: double,
    pub FractionOfUrgentBandwidth: double,
    pub output: double FractionOfUrgentBandwidthImmediateFlip; // Mode Support debugging,
// ms locals
    pub IdealSDPPortBandwidthPerState: [double; DC__VOLTAGE_STATES][2],
    pub NoOfDPP: [c_uint; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub NoOfDPPThisState: [c_uint; DC__NUM_DPP__MAX],
    pub ODMCombineEnablePerState: [odm_combine_mode; DC__VOLTAGE_STATES][DC__NUM_DPP__MAX],
    pub SwathWidthYThisState: [double; DC__NUM_DPP__MAX],
    pub SwathHeightCPerState: [c_uint; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub SwathHeightYThisState: [c_uint; DC__NUM_DPP__MAX],
    pub SwathHeightCThisState: [c_uint; DC__NUM_DPP__MAX],
    pub VRatioPreY: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub VRatioPreC: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub RequiredPrefetchPixelDataBWLuma: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub RequiredPrefetchPixelDataBWChroma: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub RequiredDPPCLK: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub RequiredDPPCLKThisState: [double; DC__NUM_DPP__MAX],
    pub PTEBufferSizeNotExceededY: [bool; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub PTEBufferSizeNotExceededC: [bool; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub BandwidthWithoutPrefetchSupported: [bool; DC__VOLTAGE_STATES][2],
    pub PrefetchSupported: [bool; DC__VOLTAGE_STATES][2],
    pub VRatioInPrefetchSupported: [bool; DC__VOLTAGE_STATES][2],
    pub RequiredDISPCLK: [double; DC__VOLTAGE_STATES][2],
    pub DISPCLK_DPPCLK_Support: [bool; DC__VOLTAGE_STATES][2],
    pub TotalAvailablePipesSupport: [bool; DC__VOLTAGE_STATES][2],
    pub TotalNumberOfActiveDPP: [c_uint; DC__VOLTAGE_STATES][2],
    pub TotalNumberOfDCCActiveDPP: [c_uint; DC__VOLTAGE_STATES][2],
    pub ModeSupport: [bool; DC__VOLTAGE_STATES][2],
    pub ReturnBWPerState: [double; DC__VOLTAGE_STATES][2],
    pub DIOSupport: [bool; DC__VOLTAGE_STATES],
    pub NotEnoughDSCUnits: [bool; DC__VOLTAGE_STATES],
    pub DSCCLKRequiredMoreThanSupported: [bool; DC__VOLTAGE_STATES],
    pub DTBCLKRequiredMoreThanSupported: [bool; DC__VOLTAGE_STATES],
    pub UrgentRoundTripAndOutOfOrderLatencyPerState: [double; DC__VOLTAGE_STATES],
    pub ROBSupport: [bool; DC__VOLTAGE_STATES][2],
// based on rev 99: Dim DCCMetaBufferSizeSupport(NumberOfStates, 1) As Boolean
    pub DCCMetaBufferSizeSupport: [bool; DC__VOLTAGE_STATES][2],
    pub PTEBufferSizeNotExceeded: [bool; DC__VOLTAGE_STATES][2],
    pub TotalVerticalActiveBandwidthSupport: [bool; DC__VOLTAGE_STATES][2],
    pub MaxTotalVerticalActiveAvailableBandwidth: [double; DC__VOLTAGE_STATES][2],
    pub PrefetchBW: [double; DC__NUM_DPP__MAX],
    pub PDEAndMetaPTEBytesPerFrame: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub MetaRowBytes: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub DPTEBytesPerRow: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub PrefetchLinesY: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub PrefetchLinesC: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub MaxNumSwY: [c_uint; DC__NUM_DPP__MAX],
    pub MaxNumSwC: [c_uint; DC__NUM_DPP__MAX],
    pub PrefillY: [double; DC__NUM_DPP__MAX],
    pub PrefillC: [double; DC__NUM_DPP__MAX],
    pub LineTimesForPrefetch: [double; DC__NUM_DPP__MAX],
    pub LinesForMetaPTE: [double; DC__NUM_DPP__MAX],
    pub LinesForMetaAndDPTERow: [double; DC__NUM_DPP__MAX],
    pub MinDPPCLKUsingSingleDPP: [double; DC__NUM_DPP__MAX],
    pub SwathWidthYSingleDPP: [double; DC__NUM_DPP__MAX],
    pub BytePerPixelInDETY: [double; DC__NUM_DPP__MAX],
    pub BytePerPixelInDETC: [double; DC__NUM_DPP__MAX],
    pub RequiresDSC: [bool; DC__VOLTAGE_STATES][DC__NUM_DPP__MAX],
    pub NumberOfDSCSlice: [c_uint; DC__VOLTAGE_STATES][DC__NUM_DPP__MAX],
    pub RequiresFEC: [double; DC__VOLTAGE_STATES][DC__NUM_DPP__MAX],
    pub OutputBppPerState: [double; DC__VOLTAGE_STATES][DC__NUM_DPP__MAX],
    pub DSCDelayPerState: [double; DC__VOLTAGE_STATES][DC__NUM_DPP__MAX],
    pub ViewportSizeSupport: [bool; DC__VOLTAGE_STATES][2],
    pub Read256BlockHeightY: [c_uint; DC__NUM_DPP__MAX],
    pub Read256BlockWidthY: [c_uint; DC__NUM_DPP__MAX],
    pub Read256BlockHeightC: [c_uint; DC__NUM_DPP__MAX],
    pub Read256BlockWidthC: [c_uint; DC__NUM_DPP__MAX],
    pub MaxSwathHeightY: [double; DC__NUM_DPP__MAX],
    pub MaxSwathHeightC: [double; DC__NUM_DPP__MAX],
    pub MinSwathHeightY: [double; DC__NUM_DPP__MAX],
    pub MinSwathHeightC: [double; DC__NUM_DPP__MAX],
    pub ReadBandwidthLuma: [double; DC__NUM_DPP__MAX],
    pub ReadBandwidthChroma: [double; DC__NUM_DPP__MAX],
    pub ReadBandwidth: [double; DC__NUM_DPP__MAX],
    pub WriteBandwidth: [double; DC__NUM_DPP__MAX],
    pub PSCL_FACTOR: [double; DC__NUM_DPP__MAX],
    pub PSCL_FACTOR_CHROMA: [double; DC__NUM_DPP__MAX],
    pub MaximumVStartup: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub AlignedDCCMetaPitch: [double; DC__NUM_DPP__MAX],
    pub AlignedYPitch: [double; DC__NUM_DPP__MAX],
    pub AlignedCPitch: [double; DC__NUM_DPP__MAX],
    pub MaximumSwathWidth: [double; DC__NUM_DPP__MAX],
    pub cursor_bw: [double; DC__NUM_DPP__MAX],
    pub cursor_bw_pre: [double; DC__NUM_DPP__MAX],
    pub Tno_bw: [double; DC__NUM_DPP__MAX],
    pub prefetch_vmrow_bw: [double; DC__NUM_DPP__MAX],
    pub DestinationLinesToRequestVMInImmediateFlip: [double; DC__NUM_DPP__MAX],
    pub DestinationLinesToRequestRowInImmediateFlip: [double; DC__NUM_DPP__MAX],
    pub final_flip_bw: [double; DC__NUM_DPP__MAX],
    pub ImmediateFlipSupportedForState: [bool; DC__VOLTAGE_STATES][2],
    pub WritebackDelay: [double; DC__VOLTAGE_STATES][DC__NUM_DPP__MAX],
    pub vm_group_bytes: [c_uint; DC__NUM_DPP__MAX],
    pub dpte_group_bytes: [c_uint; DC__NUM_DPP__MAX],
    pub dpte_row_height: [c_uint; DC__NUM_DPP__MAX],
    pub meta_req_height: [c_uint; DC__NUM_DPP__MAX],
    pub meta_req_width: [c_uint; DC__NUM_DPP__MAX],
    pub meta_row_height: [c_uint; DC__NUM_DPP__MAX],
    pub meta_row_width: [c_uint; DC__NUM_DPP__MAX],
    pub dpte_row_height_chroma: [c_uint; DC__NUM_DPP__MAX],
    pub meta_req_height_chroma: [c_uint; DC__NUM_DPP__MAX],
    pub meta_req_width_chroma: [c_uint; DC__NUM_DPP__MAX],
    pub meta_row_height_chroma: [c_uint; DC__NUM_DPP__MAX],
    pub meta_row_width_chroma: [c_uint; DC__NUM_DPP__MAX],
    pub ImmediateFlipSupportedForPipe: [bool; DC__NUM_DPP__MAX],
    pub meta_row_bw: [double; DC__NUM_DPP__MAX],
    pub dpte_row_bw: [double; DC__NUM_DPP__MAX],
    pub WM: double DisplayPipeLineDeliveryTimeLuma[DC__NUM_DPP__MAX]; //,
    pub WM: double DisplayPipeLineDeliveryTimeChroma[DC__NUM_DPP__MAX]; //,
    pub DisplayPipeRequestDeliveryTimeLuma: [double; DC__NUM_DPP__MAX],
    pub DisplayPipeRequestDeliveryTimeChroma: [double; DC__NUM_DPP__MAX],
    pub DRAMClockChangeSupport: [clock_change_support; DC__VOLTAGE_STATES][2],
    pub UrgentBurstFactorCursor: [double; DC__NUM_DPP__MAX],
    pub UrgentBurstFactorCursorPre: [double; DC__NUM_DPP__MAX],
    pub UrgentBurstFactorLuma: [double; DC__NUM_DPP__MAX],
    pub UrgentBurstFactorLumaPre: [double; DC__NUM_DPP__MAX],
    pub UrgentBurstFactorChroma: [double; DC__NUM_DPP__MAX],
    pub UrgentBurstFactorChromaPre: [double; DC__NUM_DPP__MAX],
    pub MPCCombine: [bool; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub SwathWidthCSingleDPP: [double; DC__NUM_DPP__MAX],
    pub MaximumSwathWidthInLineBufferLuma: double,
    pub MaximumSwathWidthInLineBufferChroma: double,
    pub MaximumSwathWidthLuma: [double; DC__NUM_DPP__MAX],
    pub MaximumSwathWidthChroma: [double; DC__NUM_DPP__MAX],
    pub odm_combine_dummy: [odm_combine_mode; DC__NUM_DPP__MAX],
    pub dummy1: [double; DC__NUM_DPP__MAX],
    pub dummy2: [double; DC__NUM_DPP__MAX],
    pub dummy3: [c_uint; DC__NUM_DPP__MAX],
    pub dummy4: [c_uint; DC__NUM_DPP__MAX],
    pub dummy5: double,
    pub dummy6: double,
    pub dummy7: [double; DC__NUM_DPP__MAX],
    pub dummy8: [double; DC__NUM_DPP__MAX],
    pub dummy13: [double; DC__NUM_DPP__MAX],
    pub dummy_double_array: [double; 2][DC__NUM_DPP__MAX],
    pub dummyinteger3: [c_uint; DC__NUM_DPP__MAX],
    pub dummyinteger4: [c_uint; DC__NUM_DPP__MAX],
    pub dummyinteger5: c_uint,
    pub dummyinteger6: c_uint,
    pub dummyinteger7: c_uint,
    pub dummyinteger8: c_uint,
    pub dummyinteger9: c_uint,
    pub dummyinteger10: c_uint,
    pub dummyinteger11: c_uint,
    pub dummy_integer_array: [c_uint; 8][DC__NUM_DPP__MAX],
    pub dummysinglestring: bool,
    pub SingleDPPViewportSizeSupportPerPlane: [bool; DC__NUM_DPP__MAX],
    pub PlaneRequiredDISPCLKWithODMCombine2To1: double,
    pub PlaneRequiredDISPCLKWithODMCombine4To1: double,
    pub TotalNumberOfSingleDPPPlanes: [c_uint; DC__VOLTAGE_STATES][2],
    pub LinkDSCEnable: bool,
    pub ODMCombine4To1SupportCheckOK: [bool; DC__VOLTAGE_STATES],
    pub ODMCombineEnableThisState: [odm_combine_mode; DC__NUM_DPP__MAX],
    pub SwathWidthCThisState: [double; DC__NUM_DPP__MAX],
    pub ViewportSizeSupportPerPlane: [bool; DC__NUM_DPP__MAX],
    pub AlignedDCCMetaPitchY: [double; DC__NUM_DPP__MAX],
    pub AlignedDCCMetaPitchC: [double; DC__NUM_DPP__MAX],
    pub NotEnoughUrgentLatencyHiding: [c_uint; DC__VOLTAGE_STATES][2],
    pub NotEnoughUrgentLatencyHidingPre: c_uint,
    pub PTEBufferSizeInRequestsForLuma: c_int,
    pub PTEBufferSizeInRequestsForChroma: c_int,
// Missing from VBA
    pub dpte_group_bytes_chroma: c_uint,
    pub vm_group_bytes_chroma: c_uint,
    pub dst_x_after_scaler: double,
    pub dst_y_after_scaler: double,
    pub VStartupRequiredWhenNotEnoughTimeForDynamicMetadata: c_uint,
// perf locals
    pub PrefetchBandwidth: [double; DC__NUM_DPP__MAX],
    pub VInitPreFillY: [double; DC__NUM_DPP__MAX],
    pub VInitPreFillC: [double; DC__NUM_DPP__MAX],
    pub MaxNumSwathY: [c_uint; DC__NUM_DPP__MAX],
    pub MaxNumSwathC: [c_uint; DC__NUM_DPP__MAX],
    pub VStartup: [c_uint; DC__NUM_DPP__MAX],
    pub DSTYAfterScaler: [double; DC__NUM_DPP__MAX],
    pub DSTXAfterScaler: [double; DC__NUM_DPP__MAX],
    pub AllowDRAMClockChangeDuringVBlank: [bool; DC__NUM_DPP__MAX],
    pub AllowDRAMSelfRefreshDuringVBlank: [bool; DC__NUM_DPP__MAX],
    pub VRatioPrefetchY: [double; DC__NUM_DPP__MAX],
    pub VRatioPrefetchC: [double; DC__NUM_DPP__MAX],
    pub DestinationLinesForPrefetch: [double; DC__NUM_DPP__MAX],
    pub DestinationLinesToRequestVMInVBlank: [double; DC__NUM_DPP__MAX],
    pub DestinationLinesToRequestRowInVBlank: [double; DC__NUM_DPP__MAX],
    pub MinTTUVBlank: [double; DC__NUM_DPP__MAX],
    pub BytePerPixelDETY: [double; DC__NUM_DPP__MAX],
    pub BytePerPixelDETC: [double; DC__NUM_DPP__MAX],
    pub SwathWidthY: [double; DC__NUM_DPP__MAX],
    pub SwathWidthSingleDPPY: [double; DC__NUM_DPP__MAX],
    pub CursorRequestDeliveryTime: [double; DC__NUM_DPP__MAX],
    pub CursorRequestDeliveryTimePrefetch: [double; DC__NUM_DPP__MAX],
    pub ReadBandwidthPlaneLuma: [double; DC__NUM_DPP__MAX],
    pub ReadBandwidthPlaneChroma: [double; DC__NUM_DPP__MAX],
    pub DisplayPipeLineDeliveryTimeLumaPrefetch: [double; DC__NUM_DPP__MAX],
    pub DisplayPipeLineDeliveryTimeChromaPrefetch: [double; DC__NUM_DPP__MAX],
    pub DisplayPipeRequestDeliveryTimeLumaPrefetch: [double; DC__NUM_DPP__MAX],
    pub DisplayPipeRequestDeliveryTimeChromaPrefetch: [double; DC__NUM_DPP__MAX],
    pub PixelPTEBytesPerRow: [double; DC__NUM_DPP__MAX],
    pub PDEAndMetaPTEBytesFrame: [double; DC__NUM_DPP__MAX],
    pub MetaRowByte: [double; DC__NUM_DPP__MAX],
    pub PrefetchSourceLinesY: [double; DC__NUM_DPP__MAX],
    pub RequiredPrefetchPixDataBWLuma: [double; DC__NUM_DPP__MAX],
    pub RequiredPrefetchPixDataBWChroma: [double; DC__NUM_DPP__MAX],
    pub PrefetchSourceLinesC: [double; DC__NUM_DPP__MAX],
    pub PSCL_THROUGHPUT_LUMA: [double; DC__NUM_DPP__MAX],
    pub PSCL_THROUGHPUT_CHROMA: [double; DC__NUM_DPP__MAX],
    pub DSCCLK_calculated: [double; DC__NUM_DPP__MAX],
    pub DSCDelay: [c_uint; DC__NUM_DPP__MAX],
    pub MaxVStartupLines: [c_uint; DC__NUM_DPP__MAX],
    pub DPPCLKUsingSingleDPP: [double; DC__NUM_DPP__MAX],
    pub DPPCLK: [double; DC__NUM_DPP__MAX],
    pub DCCYMaxUncompressedBlock: [c_uint; DC__NUM_DPP__MAX],
    pub DCCYMaxCompressedBlock: [c_uint; DC__NUM_DPP__MAX],
    pub DCCYIndependent64ByteBlock: [c_uint; DC__NUM_DPP__MAX],
    pub MaximumDCCCompressionYSurface: [double; DC__NUM_DPP__MAX],
    pub BlockHeight256BytesY: [c_uint; DC__NUM_DPP__MAX],
    pub BlockHeight256BytesC: [c_uint; DC__NUM_DPP__MAX],
    pub BlockWidth256BytesY: [c_uint; DC__NUM_DPP__MAX],
    pub BlockWidth256BytesC: [c_uint; DC__NUM_DPP__MAX],
    pub XFCSlaveVUpdateOffset: [double; DC__NUM_DPP__MAX],
    pub XFCSlaveVupdateWidth: [double; DC__NUM_DPP__MAX],
    pub XFCSlaveVReadyOffset: [double; DC__NUM_DPP__MAX],
    pub XFCTransferDelay: [double; DC__NUM_DPP__MAX],
    pub XFCPrechargeDelay: [double; DC__NUM_DPP__MAX],
    pub XFCRemoteSurfaceFlipLatency: [double; DC__NUM_DPP__MAX],
    pub XFCPrefetchMargin: [double; DC__NUM_DPP__MAX],
    pub dpte_row_width_luma_ub: [c_uint; DC__NUM_DPP__MAX],
    pub dpte_row_width_chroma_ub: [c_uint; DC__NUM_DPP__MAX],
    pub WM: double FullDETBufferingTimeY[DC__NUM_DPP__MAX]; //,
    pub WM: double FullDETBufferingTimeC[DC__NUM_DPP__MAX]; //,
    pub DST_Y_PER_PTE_ROW_NOM_L: [double; DC__NUM_DPP__MAX],
    pub DST_Y_PER_PTE_ROW_NOM_C: [double; DC__NUM_DPP__MAX],
    pub DST_Y_PER_META_ROW_NOM_L: [double; DC__NUM_DPP__MAX],
    pub TimePerMetaChunkNominal: [double; DC__NUM_DPP__MAX],
    pub TimePerMetaChunkVBlank: [double; DC__NUM_DPP__MAX],
    pub TimePerMetaChunkFlip: [double; DC__NUM_DPP__MAX],
    pub swath_width_luma_ub: [c_uint; DC__NUM_DPP__MAX],
    pub swath_width_chroma_ub: [c_uint; DC__NUM_DPP__MAX],
    pub PixelPTEReqWidthY: [c_uint; DC__NUM_DPP__MAX],
    pub PixelPTEReqHeightY: [c_uint; DC__NUM_DPP__MAX],
    pub PTERequestSizeY: [c_uint; DC__NUM_DPP__MAX],
    pub PixelPTEReqWidthC: [c_uint; DC__NUM_DPP__MAX],
    pub PixelPTEReqHeightC: [c_uint; DC__NUM_DPP__MAX],
    pub PTERequestSizeC: [c_uint; DC__NUM_DPP__MAX],
    pub time_per_pte_group_nom_luma: [double; DC__NUM_DPP__MAX],
    pub time_per_pte_group_nom_chroma: [double; DC__NUM_DPP__MAX],
    pub time_per_pte_group_vblank_luma: [double; DC__NUM_DPP__MAX],
    pub time_per_pte_group_vblank_chroma: [double; DC__NUM_DPP__MAX],
    pub time_per_pte_group_flip_luma: [double; DC__NUM_DPP__MAX],
    pub time_per_pte_group_flip_chroma: [double; DC__NUM_DPP__MAX],
    pub TimePerVMGroupVBlank: [double; DC__NUM_DPP__MAX],
    pub TimePerVMGroupFlip: [double; DC__NUM_DPP__MAX],
    pub TimePerVMRequestVBlank: [double; DC__NUM_DPP__MAX],
    pub TimePerVMRequestFlip: [double; DC__NUM_DPP__MAX],
    pub dpde0_bytes_per_frame_ub_l: [c_uint; DC__NUM_DPP__MAX],
    pub meta_pte_bytes_per_frame_ub_l: [c_uint; DC__NUM_DPP__MAX],
    pub dpde0_bytes_per_frame_ub_c: [c_uint; DC__NUM_DPP__MAX],
    pub meta_pte_bytes_per_frame_ub_c: [c_uint; DC__NUM_DPP__MAX],
    pub LinesToFinishSwathTransferStutterCriticalPlane: double,
    pub BytePerPixelYCriticalPlane: c_uint,
    pub SwathWidthYCriticalPlane: double,
    pub LinesInDETY: [double; DC__NUM_DPP__MAX],
    pub LinesInDETYRoundedDownToSwath: [double; DC__NUM_DPP__MAX],
    pub SwathWidthSingleDPPC: [double; DC__NUM_DPP__MAX],
    pub SwathWidthC: [double; DC__NUM_DPP__MAX],
    pub BytePerPixelY: [c_uint; DC__NUM_DPP__MAX],
    pub BytePerPixelC: [c_uint; DC__NUM_DPP__MAX],
    pub dummyinteger1: c_uint,
    pub dummyinteger2: c_uint,
    pub FinalDRAMClockChangeLatency: double,
    pub Tdmdl_vm: [double; DC__NUM_DPP__MAX],
    pub Tdmdl: [double; DC__NUM_DPP__MAX],
    pub TSetup: [double; DC__NUM_DPP__MAX],
    pub ThisVStartup: c_uint,
    pub WritebackAllowDRAMClockChangeEndPosition: [bool; DC__NUM_DPP__MAX],
    pub DST_Y_PER_META_ROW_NOM_C: [double; DC__NUM_DPP__MAX],
    pub TimePerChromaMetaChunkNominal: [double; DC__NUM_DPP__MAX],
    pub TimePerChromaMetaChunkVBlank: [double; DC__NUM_DPP__MAX],
    pub TimePerChromaMetaChunkFlip: [double; DC__NUM_DPP__MAX],
    pub DCCCMaxUncompressedBlock: [c_uint; DC__NUM_DPP__MAX],
    pub DCCCMaxCompressedBlock: [c_uint; DC__NUM_DPP__MAX],
    pub VStartupMargin: double,
    pub NotEnoughTimeForDynamicMetadata: [bool; DC__NUM_DPP__MAX],
// Missing from VBA
    pub MaximumMaxVStartupLines: c_uint,
    pub FabricAndDRAMBandwidth: double,
    pub LinesInDETLuma: double,
    pub LinesInDETChroma: double,
    pub ImmediateFlipBytes: [c_uint; DC__NUM_DPP__MAX],
    pub LinesInDETC: [c_uint; DC__NUM_DPP__MAX],
    pub LinesInDETCRoundedDownToSwath: [c_uint; DC__NUM_DPP__MAX],
    pub UrgentLatencySupportUsPerState: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub UrgentLatencySupportUs: [double; DC__NUM_DPP__MAX],
    pub FabricAndDRAMBandwidthPerState: [double; DC__VOLTAGE_STATES],
    pub UrgentLatencySupport: [bool; DC__VOLTAGE_STATES][2],
    pub SwathWidthYPerState: [c_uint; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub SwathHeightYPerState: [c_uint; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub qual_row_bw: [double; DC__NUM_DPP__MAX],
    pub prefetch_row_bw: [double; DC__NUM_DPP__MAX],
    pub prefetch_vm_bw: [double; DC__NUM_DPP__MAX],
    pub PTEGroupSize: double,
    pub PDEProcessingBufIn64KBReqs: c_uint,
    pub MaxTotalVActiveRDBandwidth: double,
    pub DoUrgentLatencyAdjustment: bool,
    pub UrgentLatencyAdjustmentFabricClockComponent: double,
    pub UrgentLatencyAdjustmentFabricClockReference: double,
    pub MinUrgentLatencySupportUs: double,
    pub MinFullDETBufferingTime: double,
    pub AverageReadBandwidthGBytePerSecond: double,
    pub FirstMainPlane: bool,
    pub NotEnoughDETSwathFillLatencyHiding: bool,
    pub ViewportWidthChroma: [c_uint; DC__NUM_DPP__MAX],
    pub ViewportHeightChroma: [c_uint; DC__NUM_DPP__MAX],
    pub HRatioChroma: [double; DC__NUM_DPP__MAX],
    pub VRatioChroma: [double; DC__NUM_DPP__MAX],
    pub WritebackSourceWidth: [c_int; DC__NUM_DPP__MAX],
    pub ModeIsSupported: bool,
    pub ODMCombine4To1Supported: bool,
    pub SurfaceWidthY: [c_uint; DC__NUM_DPP__MAX],
    pub SurfaceWidthC: [c_uint; DC__NUM_DPP__MAX],
    pub SurfaceHeightY: [c_uint; DC__NUM_DPP__MAX],
    pub SurfaceHeightC: [c_uint; DC__NUM_DPP__MAX],
    pub WritebackHTaps: [c_uint; DC__NUM_DPP__MAX],
    pub WritebackVTaps: [c_uint; DC__NUM_DPP__MAX],
    pub DSCEnable: [bool; DC__NUM_DPP__MAX],
    pub DRAMClockChangeLatencyOverride: double,
    pub GPUVMMinPageSize: double,
    pub HostVMMinPageSize: double,
    pub MPCCombineEnable: [bool; DC__NUM_DPP__MAX],
    pub HostVMMaxNonCachedPageTableLevels: c_uint,
    pub DynamicMetadataVMEnabled: bool,
    pub WritebackInterfaceBufferSize: double,
    pub WritebackLineBufferSize: double,
    pub DCCRateLuma: [double; DC__NUM_DPP__MAX],
    pub DCCRateChroma: [double; DC__NUM_DPP__MAX],
    pub PHYCLKD18PerState: [double; DC__VOLTAGE_STATES],
    pub WritebackSupportInterleaveAndUsingWholeBufferForASingleStream: bool,
    pub NumberOfHDMIFRLSupport: bool,
    pub MaxNumHDMIFRLOutputs: c_uint,
    pub AudioSampleRate: [c_int; DC__NUM_DPP__MAX],
    pub AudioSampleLayout: [c_int; DC__NUM_DPP__MAX],
    pub PercentMarginOverMinimumRequiredDCFCLK: c_int,
    pub DynamicMetadataSupported: [bool; DC__VOLTAGE_STATES][2],
    pub ImmediateFlipRequirement: [immediate_flip_requirement; DC__NUM_DPP__MAX],
    pub DETBufferSizeYThisState: [c_uint; DC__NUM_DPP__MAX],
    pub DETBufferSizeCThisState: [c_uint; DC__NUM_DPP__MAX],
    pub NoUrgentLatencyHiding: [bool; DC__NUM_DPP__MAX],
    pub NoUrgentLatencyHidingPre: [bool; DC__NUM_DPP__MAX],
    pub swath_width_luma_ub_this_state: [c_uint; DC__NUM_DPP__MAX],
    pub swath_width_chroma_ub_this_state: [c_uint; DC__NUM_DPP__MAX],
    pub UrgLatency: [double; DC__VOLTAGE_STATES],
    pub VActiveCursorBandwidth: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub VActivePixelBandwidth: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub NoTimeForPrefetch: [bool; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub NoTimeForDynamicMetadata: [bool; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub dpte_row_bandwidth: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub meta_row_bandwidth: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub DETBufferSizeYAllStates: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub DETBufferSizeCAllStates: [double; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub swath_width_luma_ub_all_states: [c_uint; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub swath_width_chroma_ub_all_states: [c_uint; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub NotUrgentLatencyHiding: [bool; DC__VOLTAGE_STATES][2],
    pub SwathHeightYAllStates: [c_uint; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub SwathHeightCAllStates: [c_uint; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub SwathWidthYAllStates: [c_uint; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub SwathWidthCAllStates: [c_uint; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub TotalDPTERowBandwidth: [double; DC__VOLTAGE_STATES][2],
    pub TotalMetaRowBandwidth: [double; DC__VOLTAGE_STATES][2],
    pub TotalVActiveCursorBandwidth: [double; DC__VOLTAGE_STATES][2],
    pub TotalVActivePixelBandwidth: [double; DC__VOLTAGE_STATES][2],
    pub WritebackDelayTime: [double; DC__NUM_DPP__MAX],
    pub DCCYIndependentBlock: [c_uint; DC__NUM_DPP__MAX],
    pub DCCCIndependentBlock: [c_uint; DC__NUM_DPP__MAX],
    pub dummyinteger17: c_uint,
    pub dummyinteger18: c_uint,
    pub dummyinteger19: c_uint,
    pub dummyinteger20: c_uint,
    pub dummyinteger21: c_uint,
    pub dummyinteger22: c_uint,
    pub dummyinteger23: c_uint,
    pub dummyinteger24: c_uint,
    pub dummyinteger25: c_uint,
    pub dummyinteger26: c_uint,
    pub dummyinteger27: c_uint,
    pub dummyinteger28: c_uint,
    pub dummyinteger29: c_uint,
    pub dummystring: [bool; DC__NUM_DPP__MAX],
    pub BPP: double,
    pub ODMCombinePolicy: odm_combine_policy,
    pub UseMinimumRequiredDCFCLK: bool,
    pub ClampMinDCFCLK: bool,
    pub AllowDramClockChangeOneDisplayVactive: bool,
    pub MaxAveragePercentOfIdealFabricAndSDPPortBWDisplayCanUseInNormalSystemOperation: double,
    pub PercentOfIdealFabricAndSDPPortBWReceivedAfterUrgLatency: double,
    pub PercentOfIdealDRAMBWReceivedAfterUrgLatencyPixelMixedWithVMData: double,
    pub PercentOfIdealDRAMBWReceivedAfterUrgLatencyVMDataOnly: double,
    pub PercentOfIdealDRAMBWReceivedAfterUrgLatencyPixelDataOnly: double,
    pub SRExitZ8Time: double,
    pub SREnterPlusExitZ8Time: double,
    pub Z8StutterExitWatermark: double,
    pub Z8StutterEnterPlusExitWatermark: double,
    pub Z8StutterEfficiencyNotIncludingVBlank: double,
    pub Z8StutterEfficiency: double,
    pub DCCFractionOfZeroSizeRequestsLuma: [double; DC__NUM_DPP__MAX],
    pub DCCFractionOfZeroSizeRequestsChroma: [double; DC__NUM_DPP__MAX],
    pub UrgBurstFactorCursor: [double; DC__NUM_DPP__MAX],
    pub UrgBurstFactorLuma: [double; DC__NUM_DPP__MAX],
    pub UrgBurstFactorChroma: [double; DC__NUM_DPP__MAX],
    pub UrgBurstFactorCursorPre: [double; DC__NUM_DPP__MAX],
    pub UrgBurstFactorLumaPre: [double; DC__NUM_DPP__MAX],
    pub UrgBurstFactorChromaPre: [double; DC__NUM_DPP__MAX],
    pub NotUrgentLatencyHidingPre: [bool; DC__NUM_DPP__MAX],
    pub LinkCapacitySupport: [bool; DC__VOLTAGE_STATES],
    pub VREADY_AT_OR_AFTER_VSYNC: [bool; DC__NUM_DPP__MAX],
    pub MIN_DST_Y_NEXT_START: [c_uint; DC__NUM_DPP__MAX],
    pub VFrontPorch: [c_uint; DC__NUM_DPP__MAX],
    pub ConfigReturnBufferSizeInKByte: c_int,
    pub UseUnboundedRequesting: unbounded_requesting_policy,
    pub CompressedBufferSegmentSizeInkByte: c_int,
    pub CompressedBufferSizeInkByte: c_uint,
    pub MetaFIFOSizeInKEntries: c_int,
    pub ZeroSizeBufferEntries: c_int,
    pub COMPBUF_RESERVED_SPACE_64B: c_int,
    pub COMPBUF_RESERVED_SPACE_ZS: c_int,
    pub UnboundedRequestEnabled: bool,
    pub DSC422NativeSupport: bool,
    pub NoEnoughUrgentLatencyHiding: bool,
    pub NoEnoughUrgentLatencyHidingPre: bool,
    pub NumberOfStutterBurstsPerFrame: c_int,
    pub Z8NumberOfStutterBurstsPerFrame: c_int,
    pub MaximumDSCBitsPerComponent: c_uint,
    pub NotEnoughUrgentLatencyHidingA: [c_uint; DC__VOLTAGE_STATES][2],
    pub ReadBandwidthSurfaceLuma: [double; DC__NUM_DPP__MAX],
    pub ReadBandwidthSurfaceChroma: [double; DC__NUM_DPP__MAX],
    pub SurfaceRequiredDISPCLKWithoutODMCombine: double,
    pub SurfaceRequiredDISPCLK: double,
    pub MinActiveFCLKChangeLatencySupported: double,
    pub MinVoltageLevel: c_int,
    pub MaxVoltageLevel: c_int,
    pub TotalNumberOfSingleDPPSurfaces: [c_uint; DC__VOLTAGE_STATES][2],
    pub CompressedBufferSizeInkByteAllStates: [c_uint; DC__VOLTAGE_STATES][2],
    pub DETBufferSizeInKByteAllStates: [c_uint; DC__VOLTAGE_STATES][2][DC__NUM_DPP__MAX],
    pub DETBufferSizeInKByteThisState: [c_uint; DC__NUM_DPP__MAX],
    pub SurfaceSizeInMALL: [c_uint; DC__NUM_DPP__MAX],
    pub ExceededMALLSize: bool,
    pub PTE_BUFFER_MODE: [bool; DC__NUM_DPP__MAX],
    pub BIGK_FRAGMENT_SIZE: [c_uint; DC__NUM_DPP__MAX],
    pub CompressedBufferSizeInkByteThisState: c_uint,
    pub FCLKChangeSupport: [dm_fclock_change_support; DC__VOLTAGE_STATES][2],
    pub USRRetrainingSupport: [bool; DC__VOLTAGE_STATES][2],
    pub UsesMALLForPStateChange: [dm_use_mall_for_pstate_change_mode; DC__NUM_DPP__MAX],
    pub UnboundedRequestEnabledAllStates: [bool; DC__VOLTAGE_STATES][2],
    pub SingleDPPViewportSizeSupportPerSurface: [bool; DC__NUM_DPP__MAX],
    pub UseMALLForStaticScreen: [dm_use_mall_for_static_screen_mode; DC__NUM_DPP__MAX],
    pub UnboundedRequestEnabledThisState: bool,
    pub DRAMClockChangeRequirementFinal: bool,
    pub FCLKChangeRequirementFinal: bool,
    pub USRRetrainingRequiredFinal: bool,
    pub DETSizeOverride: [c_uint; DC__NUM_DPP__MAX],
    pub nomDETInKByte: c_uint,
    pub MPCCombineUse: [mpc_combine_affinity; DC__NUM_DPP__MAX],
    pub MPCCombineMethodIncompatible: bool,
    pub RequiredSlots: [c_uint; DC__VOLTAGE_STATES][DC__NUM_DPP__MAX],
    pub ExceededMultistreamSlots: [bool; DC__VOLTAGE_STATES],
    pub ODMUse: [odm_combine_policy; DC__NUM_DPP__MAX],
    pub OutputMultistreamId: [c_uint; DC__NUM_DPP__MAX],
    pub OutputMultistreamEn: [bool; DC__NUM_DPP__MAX],
    pub UsesMALLForStaticScreen: [bool; DC__NUM_DPP__MAX],
    pub MaxActiveDRAMClockChangeLatencySupported: [double; DC__NUM_DPP__MAX],
    pub WritebackAllowFCLKChangeEndPosition: [double; DC__NUM_DPP__MAX],
    pub DML32: bool PTEBufferSizeNotExceededPerState[DC__NUM_DPP__MAX]; // new in,
    pub DML32: bool DCCMetaBufferSizeNotExceededPerState[DC__NUM_DPP__MAX]; // new in,
    pub NotEnoughDSCSlices: [bool; DC__VOLTAGE_STATES],
    pub PixelsPerLinePerDSCUnitSupport: [bool; DC__VOLTAGE_STATES],
    pub DCCMetaBufferSizeNotExceeded: [bool; DC__VOLTAGE_STATES][2],
    pub dpte_row_height_linear: [c_uint; DC__NUM_DPP__MAX],
    pub dpte_row_height_linear_chroma: [c_uint; DC__NUM_DPP__MAX],
    pub BlockHeightY: [c_uint; DC__NUM_DPP__MAX],
    pub BlockHeightC: [c_uint; DC__NUM_DPP__MAX],
    pub BlockWidthY: [c_uint; DC__NUM_DPP__MAX],
    pub BlockWidthC: [c_uint; DC__NUM_DPP__MAX],
    pub SubViewportLinesNeededInMALL: [c_uint; DC__NUM_DPP__MAX],
    pub VActiveBandwithSupport: [bool; DC__VOLTAGE_STATES][2],
    pub NotEnoughDETSwathFillLatencyHidingPerState: [bool; DC__VOLTAGE_STATES][2],
    pub dummy_vars: dummy_vars,
}
