//! Automatically rewritten from C Header to Rust Module
//! Source: arch/x86/include/asm/nmi.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0

extern "C" {
    pub fn reserve_perfctr_nmi(int: unsigned) -> c_int;
}
extern "C" {
    pub fn release_perfctr_nmi(int: unsigned);
}
extern "C" {
    pub fn reserve_evntsel_nmi(int: unsigned) -> c_int;
}
extern "C" {
    pub fn release_evntsel_nmi(int: unsigned);
}

// NMI handler flags
pub const NMI_FLAG_FIRST: c_int = 1;
//
// enum - NMI types.
// @NMI_LOCAL:    Local NMI, CPU-specific NMI generated by the Local APIC.
// @NMI_UNKNOWN:  Unknown NMI, the source of the NMI may not be identified.
// @NMI_SERR:     System Error NMI, typically triggered by PCI errors.
// @NMI_IO_CHECK: I/O Check NMI, related to I/O errors.
// @NMI_MAX:      Maximum value for NMI types.
//
// NMI types are used to categorize NMIs and to dispatch them to the
// appropriate handler.
//
// NMI handler return values
pub const NMI_DONE: c_int = 0;
pub const NMI_HANDLED: c_int = 1;
extern "C" {
    pub fn int(int: *mut *mut nmi_handler_t)(unsigned, : *mut pt_regs) -> typedef;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nmiaction {
    pub list: list_head,
    pub handler: nmi_handler_t,
    pub max_duration: u64,
    pub flags: c_ulong,
    pub name: *const c_char,
}

//
// register_nmi_handler - Register a handler for a specific NMI type
// @t:    NMI type (e.g. NMI_LOCAL)
// @fn:   The NMI handler
// @fg:   Flags associated with the NMI handler
// @n:    Name of the NMI handler
// @init: Optional __init* attributes for struct nmiaction
//
// Adds the provided handler to the list of handlers for the specified
// NMI type. Handlers flagged with NMI_FLAG_FIRST would be executed first.
//
// Sometimes the source of an NMI can't be reliably determined which
// results in an NMI being tagged as "unknown". Register an additional
// handler using the NMI type - NMI_UNKNOWN to handle such cases. The
// caller would get one last chance to assume responsibility for the
// NMI.
//
// Return: 0 on success, or an error code on failure.
//

extern "C" {
    pub fn __register_nmi_handler(int: unsigned, : *mut nmiaction) -> c_int;
}
//
// unregister_nmi_handler - Unregister a handler for a specific NMI type
// @type: NMI type (e.g. NMI_LOCAL)
// @name: Name of the NMI handler used during registration
//
// Removes the handler associated with the specified NMI type from the
// NMI handler list. The "name" is used as a lookup key to identify the
// handler.
//
extern "C" {
    pub fn unregister_nmi_handler(type: c_uint, name: *const c_char);
}
extern "C" {
    pub fn set_emergency_nmi_handler(type: c_uint, handler: nmi_handler_t);
}
extern "C" {
    pub fn stop_nmi();
}
extern "C" {
    pub fn restart_nmi();
}
extern "C" {
    pub fn local_touch_nmi();
}
