//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/media/dvb-frontends/drx39xyj/drx_driver_version.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// WARNING - THIS FILE HAS BEEN GENERATED - DO NOT CHANGE
//
// Filename:        drx_driver_version.h
// Generated on:    Mon Jan 18 12:09:23 2010
// Generated by:    IDF:x 1.3.0
// Generated from:  ../../../device/drxj/version
// Output start:    [entry point]
//
// filename         last modified               re-use
//
// Redistributions of source code must retain the above copyright notice,
// Redistributions in binary form must reproduce the above copyright notice,
// Neither the name of Trident Microsystems nor Hauppauge Computer Works
//
// -----------------------------------------------------
// version.idf      Mon Jan 18 11:56:10 2010    -
//

//
// ==============================================================================
// VERSION
// version@/var/cvs/projects/drxj.cvsroot/hostcode/drxdriver/device/drxj
// ==============================================================================
//
pub const VERSION__A: c_uint = 0x0;
pub const VERSION_MAJOR: c_int = 1;
pub const VERSION_MINOR: c_int = 0;
pub const VERSION_PATCH: c_int = 56;

//
// End of file (drx_driver_version.h)
//
