//! Automatically rewritten from C to Rust
//! Source: fs/signalfd.c
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// fs/signalfd.c
//
// Copyright (C) 2003  Linus Torvalds
//
// Mon Mar 5, 2007: Davide Libenzi <davidel@xmailserver.org>
// Changed ->read() to return a siginfo strcture instead of signal number.
// Fixed locking in ->poll().
// Added sighand-detach notification.
// Added fd re-use in sys_signalfd() syscall.
// Now using anonymous inode source.
// Thanks to Oleg Nesterov for useful code review and suggestions.
// More comments and suggestions from Arnd Bergmann.
// Sat May 19, 2007: Davi E. M. Arnaut <davi@haxent.com.br>
// Retrieve multiple signals with one read() call
// Sun Jul 15, 2007: Davide Libenzi <davidel@xmailserver.org>
// Attach to the sighand only during read() and poll().
//

#[no_mangle]
pub unsafe extern "C" fn signalfd_cleanup(sighand: *mut sighand_struct) {
    void signalfd_cleanup(struct sighand_struct *sighand)
    {
    wake_up_pollfree(&sighand.signalfd_wqh);
    }
#[repr(C)]
#[derive(Copy, Clone)]
pub struct signalfd_ctx {
    pub sigmask: sigset_t,
}

#[no_mangle]
unsafe extern "C" fn signalfd_release(inode: *mut inode, file: *mut file) -> c_int {
    static int signalfd_release(struct inode *inode, struct file *file)
    {
    kfree(file.private_data);
    return 0;
    }
#[no_mangle]
unsafe extern "C" fn signalfd_poll(file: *mut file, wait: *mut poll_table) -> __poll_t {
    static __poll_t signalfd_poll(struct file *file, poll_table *wait)
    {
    struct signalfd_ctx *ctx = file.private_data;
    let mut events: __poll_t = 0;
    poll_wait(file, &current.sighand.signalfd_wqh, wait);
    spin_lock_irq(&current.sighand.siglock);
    if (next_signal(&current.pending, &ctx.sigmask) ||
    next_signal(&current.signal.shared_pending,
    &ctx.sigmask))
    events |= EPOLLIN;
    spin_unlock_irq(&current.sighand.siglock);
    return events;
    }
//
// Copied from copy_siginfo_to_user() in kernel/signal.c
//
#[no_mangle]
unsafe extern "C" fn signalfd_copyinfo(to: *mut iov_iter, kinfo: *const kernel_siginfo_t) -> c_int {
    static int signalfd_copyinfo(struct iov_iter *to, kernel_siginfo_t const *kinfo)
    {
    struct signalfd_siginfo new;
    BUILD_BUG_ON(sizeof(struct signalfd_siginfo) != 128);
//
// Unused members should be zero ...
//
    memset(&new, 0, sizeof(new));
//
// If you change siginfo_t structure, please be sure
// this code is fixed accordingly.
//
    new.ssi_signo = kinfo.si_signo;
    new.ssi_errno = kinfo.si_errno;
    new.ssi_code  = kinfo.si_code;
    switch (siginfo_layout(kinfo.si_signo, kinfo.si_code)) {
    case SIL_KILL:
    new.ssi_pid = kinfo.si_pid;
    new.ssi_uid = kinfo.si_uid;
    break;
    case SIL_TIMER:
    new.ssi_tid = kinfo.si_tid;
    new.ssi_overrun = kinfo.si_overrun;
    new.ssi_ptr = (long) kinfo.si_ptr;
    new.ssi_int = kinfo.si_int;
    break;
    case SIL_POLL:
    new.ssi_band = kinfo.si_band;
    new.ssi_fd   = kinfo.si_fd;
    break;
    case SIL_FAULT_BNDERR:
    case SIL_FAULT_PKUERR:
    case SIL_FAULT_PERF_EVENT:
//
// Fall through to the SIL_FAULT case.  SIL_FAULT_BNDERR,
// SIL_FAULT_PKUERR, and SIL_FAULT_PERF_EVENT are only
// generated by faults that deliver them synchronously to
// userspace.  In case someone injects one of these signals
// and signalfd catches it treat it as SIL_FAULT.
//
    case SIL_FAULT:
    new.ssi_addr = (long) kinfo.si_addr;
    break;
    case SIL_FAULT_TRAPNO:
    new.ssi_addr = (long) kinfo.si_addr;
    new.ssi_trapno = kinfo.si_trapno;
    break;
    case SIL_FAULT_MCEERR:
    new.ssi_addr = (long) kinfo.si_addr;
    new.ssi_addr_lsb = (short) kinfo.si_addr_lsb;
    break;
    case SIL_CHLD:
    new.ssi_pid    = kinfo.si_pid;
    new.ssi_uid    = kinfo.si_uid;
    new.ssi_status = kinfo.si_status;
    new.ssi_utime  = kinfo.si_utime;
    new.ssi_stime  = kinfo.si_stime;
    break;
    case SIL_RT:
//
// This case catches also the signals queued by sigqueue().
//
    new.ssi_pid = kinfo.si_pid;
    new.ssi_uid = kinfo.si_uid;
    new.ssi_ptr = (long) kinfo.si_ptr;
    new.ssi_int = kinfo.si_int;
    break;
    case SIL_SYS:
    new.ssi_call_addr = (long) kinfo.si_call_addr;
    new.ssi_syscall   = kinfo.si_syscall;
    new.ssi_arch      = kinfo.si_arch;
    break;
    }
    if (!copy_to_iter_full(&new, sizeof(struct signalfd_siginfo), to))
    return -EFAULT;
    return sizeof(struct signalfd_siginfo);
    }
    static ssize_t signalfd_dequeue(struct signalfd_ctx *ctx, kernel_siginfo_t *info,
    int nonblock)
    {
    enum pid_type type;
    ssize_t ret;
    DECLARE_WAITQUEUE(wait, current);
    spin_lock_irq(&current.sighand.siglock);
    ret = dequeue_signal(&ctx.sigmask, info, &type);
    switch (ret) {
    case 0:
    if (!nonblock)
    break;
    ret = -EAGAIN;
    fallthrough;
    default:
    spin_unlock_irq(&current.sighand.siglock);
    return ret;
    }
    add_wait_queue(&current.sighand.signalfd_wqh, &wait);
    for (;;) {
    set_current_state(TASK_INTERRUPTIBLE);
    ret = dequeue_signal(&ctx.sigmask, info, &type);
    if (ret != 0)
    break;
    if (signal_pending(current)) {
    ret = -ERESTARTSYS;
    break;
    }
    spin_unlock_irq(&current.sighand.siglock);
    schedule();
    spin_lock_irq(&current.sighand.siglock);
    }
    spin_unlock_irq(&current.sighand.siglock);
    remove_wait_queue(&current.sighand.signalfd_wqh, &wait);
    __set_current_state(TASK_RUNNING);
    return ret;
    }
//
// Returns a multiple of the size of a "struct signalfd_siginfo", or a negative
// error code. The "count" parameter must be at least the size of a
// "struct signalfd_siginfo".
//
#[no_mangle]
unsafe extern "C" fn signalfd_read_iter(iocb: *mut kiocb, to: *mut iov_iter) -> isize {
    static ssize_t signalfd_read_iter(struct kiocb *iocb, struct iov_iter *to)
    {
    struct file *file = iocb.ki_filp;
    struct signalfd_ctx *ctx = file.private_data;
    let mut count: usize = iov_iter_count(to);
    ssize_t ret, total = 0;
    kernel_siginfo_t info;
    bool nonblock;
    count /= sizeof(struct signalfd_siginfo);
    if (!count)
    return -EINVAL;
    nonblock = file.f_flags & O_NONBLOCK || iocb.ki_flags & IOCB_NOWAIT;
    do {
    ret = signalfd_dequeue(ctx, &info, nonblock);
    if (unlikely(ret <= 0))
    break;
    ret = signalfd_copyinfo(to, &info);
    if (ret < 0)
    break;
    total += ret;
    nonblock = 1;
    } while (--count);
    return total ? total: ret;
    }

#[no_mangle]
unsafe extern "C" fn signalfd_show_fdinfo(m: *mut seq_file, f: *mut file) {
    static void signalfd_show_fdinfo(struct seq_file *m, struct file *f)
    {
    struct signalfd_ctx *ctx = f.private_data;
    sigset_t sigmask;
    sigmask = ctx.sigmask;
    signotset(&sigmask);
    render_sigset_t(m, "sigmask:\t", &sigmask);
    }

    static const struct file_operations signalfd_fops = {

    .show_fdinfo	= signalfd_show_fdinfo,

    .release	= signalfd_release,
    .poll		= signalfd_poll,
    .read_iter	= signalfd_read_iter,
    .llseek		= noop_llseek,
    };
#[no_mangle]
unsafe extern "C" fn do_signalfd4(ufd: c_int, mask: *mut sigset_t, flags: c_int) -> c_int {
    static int do_signalfd4(int ufd, sigset_t *mask, int flags)
    {
// Check the SFD_* constants for consistency.
    BUILD_BUG_ON(SFD_CLOEXEC != O_CLOEXEC);
    BUILD_BUG_ON(SFD_NONBLOCK != O_NONBLOCK);
    if (flags & ~(SFD_CLOEXEC | SFD_NONBLOCK))
    return -EINVAL;
    sigdelsetmask(mask, sigmask(SIGKILL) | sigmask(SIGSTOP));
    signotset(mask);
    if (ufd == -1) {
    int fd;
    struct signalfd_ctx *ctx __free(kfree) = core::ptr::null_mut();
    ctx = kmalloc_obj(*ctx);
    if (!ctx)
    return -ENOMEM;
    ctx.sigmask = *mask;
    fd = FD_ADD(flags & O_CLOEXEC,
    anon_inode_getfile_fmode(
    "[signalfd]", &signalfd_fops, ctx,
    O_RDWR | (flags & O_NONBLOCK), FMODE_NOWAIT));
    if (fd >= 0)
    retain_and_null_ptr(ctx);
    return fd;
    } else {
    struct signalfd_ctx *ctx;
    CLASS(fd, f)(ufd);
    if (fd_empty(f))
    return -EBADF;
    ctx = fd_file(f).private_data;
    if (fd_file(f).f_op != &signalfd_fops)
    return -EINVAL;
    spin_lock_irq(&current.sighand.siglock);
    ctx.sigmask = *mask;
    spin_unlock_irq(&current.sighand.siglock);
    wake_up(&current.sighand.signalfd_wqh);
    }
    return ufd;
    }
    SYSCALL_DEFINE4(signalfd4, int, ufd, sigset_t __user *, user_mask,
    size_t, sizemask, int, flags)
    {
    sigset_t mask;
    if (sizemask != sizeof(sigset_t))
    return -EINVAL;
    if (copy_from_user(&mask, user_mask, sizeof(mask)))
    return -EFAULT;
    return do_signalfd4(ufd, &mask, flags);
    }
    SYSCALL_DEFINE3(signalfd, int, ufd, sigset_t __user *, user_mask,
    size_t, sizemask)
    {
    sigset_t mask;
    if (sizemask != sizeof(sigset_t))
    return -EINVAL;
    if (copy_from_user(&mask, user_mask, sizeof(mask)))
    return -EFAULT;
    return do_signalfd4(ufd, &mask, 0);
    }

    static long do_compat_signalfd4(int ufd,
    const compat_sigset_t __user *user_mask,
    compat_size_t sigsetsize, int flags)
    {
    sigset_t mask;
    if (sigsetsize != sizeof(compat_sigset_t))
    return -EINVAL;
    if (get_compat_sigset(&mask, user_mask))
    return -EFAULT;
    return do_signalfd4(ufd, &mask, flags);
    }
    COMPAT_SYSCALL_DEFINE4(signalfd4, int, ufd,
    const compat_sigset_t __user *, user_mask,
    compat_size_t, sigsetsize,
    int, flags)
    {
    return do_compat_signalfd4(ufd, user_mask, sigsetsize, flags);
    }
    COMPAT_SYSCALL_DEFINE3(signalfd, int, ufd,
    const compat_sigset_t __user *, user_mask,
    compat_size_t, sigsetsize)
    {
    return do_compat_signalfd4(ufd, user_mask, sigsetsize, 0);
    }
