//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/amd/include/asic_reg/dpcs/dpcs_4_0_1_sh_mask.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.

// Macro flag: #define _dpcs_4_0_1_SH_MASK_HEADER
// addressBlock: dpcssys_dcio_dcio_dispdec
// DC_GENERICA
pub const DC_GENERICA__GENERICA_SEL__SHIFT: c_uint = 0x7;
pub const DC_GENERICA__GENERICA_SEL_MASK: c_uint = 0x00000F80L;
// DC_GENERICB
pub const DC_GENERICB__GENERICB_SEL__SHIFT: c_uint = 0x8;
pub const DC_GENERICB__GENERICB_SEL_MASK: c_uint = 0x00000F00L;
// DCIO_CLOCK_CNTL
pub const DCIO_CLOCK_CNTL__DCIO_TEST_CLK_SEL__SHIFT: c_uint = 0x0;
pub const DCIO_CLOCK_CNTL__DISPCLK_R_DCIO_GATE_DIS__SHIFT: c_uint = 0x5;
pub const DCIO_CLOCK_CNTL__DCIO_TEST_CLK_SEL_MASK: c_uint = 0x0000001FL;
pub const DCIO_CLOCK_CNTL__DISPCLK_R_DCIO_GATE_DIS_MASK: c_uint = 0x00000020L;
// DC_REF_CLK_CNTL
pub const DC_REF_CLK_CNTL__GENLK_CLK_OUTPUT_SEL__SHIFT: c_uint = 0x8;
pub const DC_REF_CLK_CNTL__GENLK_CLK_OUTPUT_SEL_MASK: c_uint = 0x00000300L;
// UNIPHYA_LINK_CNTL
pub const UNIPHYA_LINK_CNTL__UNIPHY_CHANNEL0_INVERT__SHIFT: c_uint = 0xc;
pub const UNIPHYA_LINK_CNTL__UNIPHY_CHANNEL1_INVERT__SHIFT: c_uint = 0xd;
pub const UNIPHYA_LINK_CNTL__UNIPHY_CHANNEL2_INVERT__SHIFT: c_uint = 0xe;
pub const UNIPHYA_LINK_CNTL__UNIPHY_CHANNEL3_INVERT__SHIFT: c_uint = 0xf;
pub const UNIPHYA_LINK_CNTL__UNIPHY_CHANNEL0_INVERT_MASK: c_uint = 0x00001000L;
pub const UNIPHYA_LINK_CNTL__UNIPHY_CHANNEL1_INVERT_MASK: c_uint = 0x00002000L;
pub const UNIPHYA_LINK_CNTL__UNIPHY_CHANNEL2_INVERT_MASK: c_uint = 0x00004000L;
pub const UNIPHYA_LINK_CNTL__UNIPHY_CHANNEL3_INVERT_MASK: c_uint = 0x00008000L;
// UNIPHYA_CHANNEL_XBAR_CNTL
pub const UNIPHYA_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL0_XBAR_SOURCE__SHIFT: c_uint = 0x0;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL1_XBAR_SOURCE__SHIFT: c_uint = 0x8;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL2_XBAR_SOURCE__SHIFT: c_uint = 0x10;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL3_XBAR_SOURCE__SHIFT: c_uint = 0x18;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL0_EN__SHIFT: c_uint = 0x1c;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL1_EN__SHIFT: c_uint = 0x1d;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL2_EN__SHIFT: c_uint = 0x1e;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL3_EN__SHIFT: c_uint = 0x1f;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL0_XBAR_SOURCE_MASK: c_uint = 0x00000003L;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL1_XBAR_SOURCE_MASK: c_uint = 0x00000300L;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL2_XBAR_SOURCE_MASK: c_uint = 0x00030000L;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL3_XBAR_SOURCE_MASK: c_uint = 0x03000000L;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL0_EN_MASK: c_uint = 0x10000000L;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL1_EN_MASK: c_uint = 0x20000000L;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL2_EN_MASK: c_uint = 0x40000000L;
pub const UNIPHYA_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL3_EN_MASK: c_uint = 0x80000000L;
// UNIPHYB_LINK_CNTL
pub const UNIPHYB_LINK_CNTL__UNIPHY_CHANNEL0_INVERT__SHIFT: c_uint = 0xc;
pub const UNIPHYB_LINK_CNTL__UNIPHY_CHANNEL1_INVERT__SHIFT: c_uint = 0xd;
pub const UNIPHYB_LINK_CNTL__UNIPHY_CHANNEL2_INVERT__SHIFT: c_uint = 0xe;
pub const UNIPHYB_LINK_CNTL__UNIPHY_CHANNEL3_INVERT__SHIFT: c_uint = 0xf;
pub const UNIPHYB_LINK_CNTL__UNIPHY_CHANNEL0_INVERT_MASK: c_uint = 0x00001000L;
pub const UNIPHYB_LINK_CNTL__UNIPHY_CHANNEL1_INVERT_MASK: c_uint = 0x00002000L;
pub const UNIPHYB_LINK_CNTL__UNIPHY_CHANNEL2_INVERT_MASK: c_uint = 0x00004000L;
pub const UNIPHYB_LINK_CNTL__UNIPHY_CHANNEL3_INVERT_MASK: c_uint = 0x00008000L;
// UNIPHYB_CHANNEL_XBAR_CNTL
pub const UNIPHYB_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL0_XBAR_SOURCE__SHIFT: c_uint = 0x0;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL1_XBAR_SOURCE__SHIFT: c_uint = 0x8;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL2_XBAR_SOURCE__SHIFT: c_uint = 0x10;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL3_XBAR_SOURCE__SHIFT: c_uint = 0x18;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL0_EN__SHIFT: c_uint = 0x1c;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL1_EN__SHIFT: c_uint = 0x1d;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL2_EN__SHIFT: c_uint = 0x1e;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL3_EN__SHIFT: c_uint = 0x1f;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL0_XBAR_SOURCE_MASK: c_uint = 0x00000003L;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL1_XBAR_SOURCE_MASK: c_uint = 0x00000300L;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL2_XBAR_SOURCE_MASK: c_uint = 0x00030000L;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL3_XBAR_SOURCE_MASK: c_uint = 0x03000000L;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL0_EN_MASK: c_uint = 0x10000000L;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL1_EN_MASK: c_uint = 0x20000000L;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL2_EN_MASK: c_uint = 0x40000000L;
pub const UNIPHYB_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL3_EN_MASK: c_uint = 0x80000000L;
// UNIPHYC_LINK_CNTL
pub const UNIPHYC_LINK_CNTL__UNIPHY_CHANNEL0_INVERT__SHIFT: c_uint = 0xc;
pub const UNIPHYC_LINK_CNTL__UNIPHY_CHANNEL1_INVERT__SHIFT: c_uint = 0xd;
pub const UNIPHYC_LINK_CNTL__UNIPHY_CHANNEL2_INVERT__SHIFT: c_uint = 0xe;
pub const UNIPHYC_LINK_CNTL__UNIPHY_CHANNEL3_INVERT__SHIFT: c_uint = 0xf;
pub const UNIPHYC_LINK_CNTL__UNIPHY_CHANNEL0_INVERT_MASK: c_uint = 0x00001000L;
pub const UNIPHYC_LINK_CNTL__UNIPHY_CHANNEL1_INVERT_MASK: c_uint = 0x00002000L;
pub const UNIPHYC_LINK_CNTL__UNIPHY_CHANNEL2_INVERT_MASK: c_uint = 0x00004000L;
pub const UNIPHYC_LINK_CNTL__UNIPHY_CHANNEL3_INVERT_MASK: c_uint = 0x00008000L;
// UNIPHYC_CHANNEL_XBAR_CNTL
pub const UNIPHYC_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL0_XBAR_SOURCE__SHIFT: c_uint = 0x0;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL1_XBAR_SOURCE__SHIFT: c_uint = 0x8;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL2_XBAR_SOURCE__SHIFT: c_uint = 0x10;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL3_XBAR_SOURCE__SHIFT: c_uint = 0x18;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL0_EN__SHIFT: c_uint = 0x1c;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL1_EN__SHIFT: c_uint = 0x1d;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL2_EN__SHIFT: c_uint = 0x1e;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL3_EN__SHIFT: c_uint = 0x1f;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL0_XBAR_SOURCE_MASK: c_uint = 0x00000003L;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL1_XBAR_SOURCE_MASK: c_uint = 0x00000300L;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL2_XBAR_SOURCE_MASK: c_uint = 0x00030000L;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL3_XBAR_SOURCE_MASK: c_uint = 0x03000000L;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL0_EN_MASK: c_uint = 0x10000000L;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL1_EN_MASK: c_uint = 0x20000000L;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL2_EN_MASK: c_uint = 0x40000000L;
pub const UNIPHYC_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL3_EN_MASK: c_uint = 0x80000000L;
// UNIPHYD_LINK_CNTL
pub const UNIPHYD_LINK_CNTL__UNIPHY_CHANNEL0_INVERT__SHIFT: c_uint = 0xc;
pub const UNIPHYD_LINK_CNTL__UNIPHY_CHANNEL1_INVERT__SHIFT: c_uint = 0xd;
pub const UNIPHYD_LINK_CNTL__UNIPHY_CHANNEL2_INVERT__SHIFT: c_uint = 0xe;
pub const UNIPHYD_LINK_CNTL__UNIPHY_CHANNEL3_INVERT__SHIFT: c_uint = 0xf;
pub const UNIPHYD_LINK_CNTL__UNIPHY_CHANNEL0_INVERT_MASK: c_uint = 0x00001000L;
pub const UNIPHYD_LINK_CNTL__UNIPHY_CHANNEL1_INVERT_MASK: c_uint = 0x00002000L;
pub const UNIPHYD_LINK_CNTL__UNIPHY_CHANNEL2_INVERT_MASK: c_uint = 0x00004000L;
pub const UNIPHYD_LINK_CNTL__UNIPHY_CHANNEL3_INVERT_MASK: c_uint = 0x00008000L;
// UNIPHYD_CHANNEL_XBAR_CNTL
pub const UNIPHYD_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL0_XBAR_SOURCE__SHIFT: c_uint = 0x0;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL1_XBAR_SOURCE__SHIFT: c_uint = 0x8;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL2_XBAR_SOURCE__SHIFT: c_uint = 0x10;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL3_XBAR_SOURCE__SHIFT: c_uint = 0x18;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL0_EN__SHIFT: c_uint = 0x1c;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL1_EN__SHIFT: c_uint = 0x1d;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL2_EN__SHIFT: c_uint = 0x1e;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL3_EN__SHIFT: c_uint = 0x1f;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL0_XBAR_SOURCE_MASK: c_uint = 0x00000003L;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL1_XBAR_SOURCE_MASK: c_uint = 0x00000300L;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL2_XBAR_SOURCE_MASK: c_uint = 0x00030000L;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL3_XBAR_SOURCE_MASK: c_uint = 0x03000000L;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL0_EN_MASK: c_uint = 0x10000000L;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL1_EN_MASK: c_uint = 0x20000000L;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL2_EN_MASK: c_uint = 0x40000000L;
pub const UNIPHYD_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL3_EN_MASK: c_uint = 0x80000000L;
// UNIPHYE_LINK_CNTL
pub const UNIPHYE_LINK_CNTL__UNIPHY_CHANNEL0_INVERT__SHIFT: c_uint = 0xc;
pub const UNIPHYE_LINK_CNTL__UNIPHY_CHANNEL1_INVERT__SHIFT: c_uint = 0xd;
pub const UNIPHYE_LINK_CNTL__UNIPHY_CHANNEL2_INVERT__SHIFT: c_uint = 0xe;
pub const UNIPHYE_LINK_CNTL__UNIPHY_CHANNEL3_INVERT__SHIFT: c_uint = 0xf;
pub const UNIPHYE_LINK_CNTL__UNIPHY_CHANNEL0_INVERT_MASK: c_uint = 0x00001000L;
pub const UNIPHYE_LINK_CNTL__UNIPHY_CHANNEL1_INVERT_MASK: c_uint = 0x00002000L;
pub const UNIPHYE_LINK_CNTL__UNIPHY_CHANNEL2_INVERT_MASK: c_uint = 0x00004000L;
pub const UNIPHYE_LINK_CNTL__UNIPHY_CHANNEL3_INVERT_MASK: c_uint = 0x00008000L;
// UNIPHYE_CHANNEL_XBAR_CNTL
pub const UNIPHYE_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL0_XBAR_SOURCE__SHIFT: c_uint = 0x0;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL1_XBAR_SOURCE__SHIFT: c_uint = 0x8;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL2_XBAR_SOURCE__SHIFT: c_uint = 0x10;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL3_XBAR_SOURCE__SHIFT: c_uint = 0x18;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL0_EN__SHIFT: c_uint = 0x1c;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL1_EN__SHIFT: c_uint = 0x1d;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL2_EN__SHIFT: c_uint = 0x1e;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL3_EN__SHIFT: c_uint = 0x1f;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL0_XBAR_SOURCE_MASK: c_uint = 0x00000003L;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL1_XBAR_SOURCE_MASK: c_uint = 0x00000300L;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL2_XBAR_SOURCE_MASK: c_uint = 0x00030000L;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__UNIPHY_CHANNEL3_XBAR_SOURCE_MASK: c_uint = 0x03000000L;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL0_EN_MASK: c_uint = 0x10000000L;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL1_EN_MASK: c_uint = 0x20000000L;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL2_EN_MASK: c_uint = 0x40000000L;
pub const UNIPHYE_CHANNEL_XBAR_CNTL__DOUT_PHY_CHANNEL3_EN_MASK: c_uint = 0x80000000L;
// DCIO_WRCMD_DELAY
pub const DCIO_WRCMD_DELAY__UNIPHY_DELAY__SHIFT: c_uint = 0x18;
pub const DCIO_WRCMD_DELAY__UNIPHY_DELAY_MASK: c_uint = 0xFF000000L;
// DC_PINSTRAPS
pub const DC_PINSTRAPS__DC_PINSTRAPS_AUDIO__SHIFT: c_uint = 0xe;
pub const DC_PINSTRAPS__DC_PINSTRAPS_AUDIO_MASK: c_uint = 0x0000C000L;
// DCIO_SPARE
pub const DCIO_SPARE__DCIO_SPARE__SHIFT: c_uint = 0x0;
pub const DCIO_SPARE__DCIO_SPARE_MASK: c_uint = 0xFFFFFFFFL;
// INTERCEPT_STATE
pub const INTERCEPT_STATE__PWRSEQ0_INTERCEPTB_STATE__SHIFT: c_uint = 0x0;
pub const INTERCEPT_STATE__DLPC_INTERCEPTB_STATE__SHIFT: c_uint = 0x2;
pub const INTERCEPT_STATE__DPCS0_INTERCEPTB_STATE__SHIFT: c_uint = 0x4;
pub const INTERCEPT_STATE__DPCS1_INTERCEPTB_STATE__SHIFT: c_uint = 0x5;
pub const INTERCEPT_STATE__DPCS2_INTERCEPTB_STATE__SHIFT: c_uint = 0x6;
pub const INTERCEPT_STATE__DPCS3_INTERCEPTB_STATE__SHIFT: c_uint = 0x7;
pub const INTERCEPT_STATE__DPCS4_INTERCEPTB_STATE__SHIFT: c_uint = 0x8;
pub const INTERCEPT_STATE__DPCS0_DC_INTERCEPTB_STATE__SHIFT: c_uint = 0x10;
pub const INTERCEPT_STATE__DPCS1_DC_INTERCEPTB_STATE__SHIFT: c_uint = 0x11;
pub const INTERCEPT_STATE__DPCS2_DC_INTERCEPTB_STATE__SHIFT: c_uint = 0x12;
pub const INTERCEPT_STATE__DPCS3_DC_INTERCEPTB_STATE__SHIFT: c_uint = 0x13;
pub const INTERCEPT_STATE__DPCS4_DC_INTERCEPTB_STATE__SHIFT: c_uint = 0x14;
pub const INTERCEPT_STATE__PWRSEQ0_INTERCEPTB_STATE_MASK: c_uint = 0x00000001L;
pub const INTERCEPT_STATE__DLPC_INTERCEPTB_STATE_MASK: c_uint = 0x00000004L;
pub const INTERCEPT_STATE__DPCS0_INTERCEPTB_STATE_MASK: c_uint = 0x00000010L;
pub const INTERCEPT_STATE__DPCS1_INTERCEPTB_STATE_MASK: c_uint = 0x00000020L;
pub const INTERCEPT_STATE__DPCS2_INTERCEPTB_STATE_MASK: c_uint = 0x00000040L;
pub const INTERCEPT_STATE__DPCS3_INTERCEPTB_STATE_MASK: c_uint = 0x00000080L;
pub const INTERCEPT_STATE__DPCS4_INTERCEPTB_STATE_MASK: c_uint = 0x00000100L;
pub const INTERCEPT_STATE__DPCS0_DC_INTERCEPTB_STATE_MASK: c_uint = 0x00010000L;
pub const INTERCEPT_STATE__DPCS1_DC_INTERCEPTB_STATE_MASK: c_uint = 0x00020000L;
pub const INTERCEPT_STATE__DPCS2_DC_INTERCEPTB_STATE_MASK: c_uint = 0x00040000L;
pub const INTERCEPT_STATE__DPCS3_DC_INTERCEPTB_STATE_MASK: c_uint = 0x00080000L;
pub const INTERCEPT_STATE__DPCS4_DC_INTERCEPTB_STATE_MASK: c_uint = 0x00100000L;
// DCIO_PATTERN_GEN_PAT
pub const DCIO_PATTERN_GEN_PAT__DCIO_PATTERN_GEN_PAT__SHIFT: c_uint = 0x0;
pub const DCIO_PATTERN_GEN_PAT__DCIO_PATTERN_GEN_PAT_MASK: c_uint = 0xFFFFFFFFL;
// DCIO_PATTERN_GEN_EN
pub const DCIO_PATTERN_GEN_EN__DCIO_PATTERN_GEN_EN__SHIFT: c_uint = 0x0;
pub const DCIO_PATTERN_GEN_EN__DCIO_PATTERN_GEN_EN_MASK: c_uint = 0x00000001L;
// DCIO_BL_PWM_FRAME_START_DISP_SEL
pub const DCIO_BL_PWM_FRAME_START_DISP_SEL__BL_PWM0_GRP1_FRAME_START_DISP_SEL__SHIFT: c_uint = 0x0;
pub const DCIO_BL_PWM_FRAME_START_DISP_SEL__BL_PWM0_GRP1_FRAME_START_DISP_SEL_MASK: c_uint = 0x00000007L;
// DCIO_GSL_GENLK_PAD_CNTL
pub const DCIO_GSL_GENLK_PAD_CNTL__DCIO_GENLK_CLK_GSL_FLIP_READY_SEL__SHIFT: c_uint = 0x4;
pub const DCIO_GSL_GENLK_PAD_CNTL__DCIO_GENLK_CLK_GSL_MASK__SHIFT: c_uint = 0x8;
pub const DCIO_GSL_GENLK_PAD_CNTL__DCIO_GENLK_VSYNC_GSL_FLIP_READY_SEL__SHIFT: c_uint = 0x14;
pub const DCIO_GSL_GENLK_PAD_CNTL__DCIO_GENLK_VSYNC_GSL_MASK__SHIFT: c_uint = 0x18;
pub const DCIO_GSL_GENLK_PAD_CNTL__DCIO_GENLK_CLK_GSL_FLIP_READY_SEL_MASK: c_uint = 0x00000030L;
pub const DCIO_GSL_GENLK_PAD_CNTL__DCIO_GENLK_CLK_GSL_MASK_MASK: c_uint = 0x00000300L;
pub const DCIO_GSL_GENLK_PAD_CNTL__DCIO_GENLK_VSYNC_GSL_FLIP_READY_SEL_MASK: c_uint = 0x00300000L;
pub const DCIO_GSL_GENLK_PAD_CNTL__DCIO_GENLK_VSYNC_GSL_MASK_MASK: c_uint = 0x03000000L;
// DCIO_GSL_SWAPLOCK_PAD_CNTL
pub const DCIO_GSL_SWAPLOCK_PAD_CNTL__DCIO_SWAPLOCK_A_GSL_FLIP_READY_SEL__SHIFT: c_uint = 0x4;
pub const DCIO_GSL_SWAPLOCK_PAD_CNTL__DCIO_SWAPLOCK_A_GSL_MASK__SHIFT: c_uint = 0x8;
pub const DCIO_GSL_SWAPLOCK_PAD_CNTL__DCIO_SWAPLOCK_B_GSL_FLIP_READY_SEL__SHIFT: c_uint = 0x14;
pub const DCIO_GSL_SWAPLOCK_PAD_CNTL__DCIO_SWAPLOCK_B_GSL_MASK__SHIFT: c_uint = 0x18;
pub const DCIO_GSL_SWAPLOCK_PAD_CNTL__DCIO_SWAPLOCK_A_GSL_FLIP_READY_SEL_MASK: c_uint = 0x00000030L;
pub const DCIO_GSL_SWAPLOCK_PAD_CNTL__DCIO_SWAPLOCK_A_GSL_MASK_MASK: c_uint = 0x00000300L;
pub const DCIO_GSL_SWAPLOCK_PAD_CNTL__DCIO_SWAPLOCK_B_GSL_FLIP_READY_SEL_MASK: c_uint = 0x00300000L;
pub const DCIO_GSL_SWAPLOCK_PAD_CNTL__DCIO_SWAPLOCK_B_GSL_MASK_MASK: c_uint = 0x03000000L;
// DPCS_DCIO_TEST_CLK_SRC
pub const DPCS_DCIO_TEST_CLK_SRC__DPCS_TEST_CLK_SRC_SEL__SHIFT: c_uint = 0x0;
pub const DPCS_DCIO_TEST_CLK_SRC__DPCS_TEST_CLK_SRC_SEL_MASK: c_uint = 0x00000007L;
// DCIO_TEST_DEBUG_INDEX
pub const DCIO_TEST_DEBUG_INDEX__DCIO_TEST_DEBUG_INDEX__SHIFT: c_uint = 0x0;
pub const DCIO_TEST_DEBUG_INDEX__DCIO_TEST_DEBUG_INDEX_MASK: c_uint = 0x000000FFL;
// DCIO_TEST_DEBUG_DATA
pub const DCIO_TEST_DEBUG_DATA__DCIO_TEST_DEBUG_DATA__SHIFT: c_uint = 0x0;
pub const DCIO_TEST_DEBUG_DATA__DCIO_TEST_DEBUG_DATA_MASK: c_uint = 0xFFFFFFFFL;
// DBG_OUT_CNTL
pub const DBG_OUT_CNTL__DBG_OUT_BLK_SEL__SHIFT: c_uint = 0x0;
pub const DBG_OUT_CNTL__DBG_OUT_4BIT_SEL__SHIFT: c_uint = 0x5;
pub const DBG_OUT_CNTL__DBG_OUT_12BIT_TEST_DATA__SHIFT: c_uint = 0xc;
pub const DBG_OUT_CNTL__DBG_OUT_BLK_SEL_MASK: c_uint = 0x00000003L;
pub const DBG_OUT_CNTL__DBG_OUT_4BIT_SEL_MASK: c_uint = 0x000000E0L;
pub const DBG_OUT_CNTL__DBG_OUT_12BIT_TEST_DATA_MASK: c_uint = 0x00FFF000L;
// DCIO_DEBUG_CONFIG
pub const DCIO_DEBUG_CONFIG__DCIO_DBG_EN__SHIFT: c_uint = 0x0;
pub const DCIO_DEBUG_CONFIG__DCIO_DBG_EN_MASK: c_uint = 0x00000001L;
// DCIO_SOFT_RESET
pub const DCIO_SOFT_RESET__UNIPHYA_SOFT_RESET__SHIFT: c_uint = 0x0;
pub const DCIO_SOFT_RESET__UNIPHYB_SOFT_RESET__SHIFT: c_uint = 0x1;
pub const DCIO_SOFT_RESET__UNIPHYC_SOFT_RESET__SHIFT: c_uint = 0x2;
pub const DCIO_SOFT_RESET__UNIPHYD_SOFT_RESET__SHIFT: c_uint = 0x3;
pub const DCIO_SOFT_RESET__UNIPHYE_SOFT_RESET__SHIFT: c_uint = 0x4;
pub const DCIO_SOFT_RESET__PWRSEQ0_SOFT_RESET__SHIFT: c_uint = 0x10;
pub const DCIO_SOFT_RESET__DLPC_SOFT_RESET__SHIFT: c_uint = 0x14;
pub const DCIO_SOFT_RESET__UNIPHYA_SOFT_RESET_MASK: c_uint = 0x00000001L;
pub const DCIO_SOFT_RESET__UNIPHYB_SOFT_RESET_MASK: c_uint = 0x00000002L;
pub const DCIO_SOFT_RESET__UNIPHYC_SOFT_RESET_MASK: c_uint = 0x00000004L;
pub const DCIO_SOFT_RESET__UNIPHYD_SOFT_RESET_MASK: c_uint = 0x00000008L;
pub const DCIO_SOFT_RESET__UNIPHYE_SOFT_RESET_MASK: c_uint = 0x00000010L;
pub const DCIO_SOFT_RESET__PWRSEQ0_SOFT_RESET_MASK: c_uint = 0x00010000L;
pub const DCIO_SOFT_RESET__DLPC_SOFT_RESET_MASK: c_uint = 0x00100000L;
// addressBlock: dpcssys_dcio_dcio_chip_dispdec
// DC_GPIO_DDC1_MASK
pub const DC_GPIO_DDC1_MASK__AUX_PAD1_MODE__SHIFT: c_uint = 0x10;
pub const DC_GPIO_DDC1_MASK__AUX1_POL__SHIFT: c_uint = 0x14;
pub const DC_GPIO_DDC1_MASK__AUX_PAD1_MODE_MASK: c_uint = 0x00010000L;
pub const DC_GPIO_DDC1_MASK__AUX1_POL_MASK: c_uint = 0x00100000L;
// DC_GPIO_DDC2_MASK
pub const DC_GPIO_DDC2_MASK__AUX_PAD2_MODE__SHIFT: c_uint = 0x10;
pub const DC_GPIO_DDC2_MASK__AUX2_POL__SHIFT: c_uint = 0x14;
pub const DC_GPIO_DDC2_MASK__AUX_PAD2_MODE_MASK: c_uint = 0x00010000L;
pub const DC_GPIO_DDC2_MASK__AUX2_POL_MASK: c_uint = 0x00100000L;
// DC_GPIO_DDC3_MASK
pub const DC_GPIO_DDC3_MASK__AUX_PAD3_MODE__SHIFT: c_uint = 0x10;
pub const DC_GPIO_DDC3_MASK__AUX3_POL__SHIFT: c_uint = 0x14;
pub const DC_GPIO_DDC3_MASK__AUX_PAD3_MODE_MASK: c_uint = 0x00010000L;
pub const DC_GPIO_DDC3_MASK__AUX3_POL_MASK: c_uint = 0x00100000L;
// DC_GPIO_DDCVGA_MASK
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGACLK_MASK__SHIFT: c_uint = 0x0;
pub const DC_GPIO_DDCVGA_MASK__DDCVGA_INVERT_INPUT_POLARITY__SHIFT: c_uint = 0x4;
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGACLK_RECV__SHIFT: c_uint = 0x6;
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGADATA_MASK__SHIFT: c_uint = 0x8;
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGADATA_PD_EN__SHIFT: c_uint = 0xc;
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGADATA_RECV__SHIFT: c_uint = 0xe;
pub const DC_GPIO_DDCVGA_MASK__ALLOW_HW_DDCVGA_PD_EN__SHIFT: c_uint = 0x16;
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGADATA_STR__SHIFT: c_uint = 0x1c;
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGACLK_MASK_MASK: c_uint = 0x00000001L;
pub const DC_GPIO_DDCVGA_MASK__DDCVGA_INVERT_INPUT_POLARITY_MASK: c_uint = 0x00000010L;
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGACLK_RECV_MASK: c_uint = 0x00000040L;
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGADATA_MASK_MASK: c_uint = 0x00000100L;
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGADATA_PD_EN_MASK: c_uint = 0x00001000L;
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGADATA_RECV_MASK: c_uint = 0x00004000L;
pub const DC_GPIO_DDCVGA_MASK__ALLOW_HW_DDCVGA_PD_EN_MASK: c_uint = 0x00400000L;
pub const DC_GPIO_DDCVGA_MASK__DC_GPIO_DDCVGADATA_STR_MASK: c_uint = 0xF0000000L;
// DC_GPIO_DDCVGA_A
pub const DC_GPIO_DDCVGA_A__DC_GPIO_DDCVGACLK_A__SHIFT: c_uint = 0x0;
pub const DC_GPIO_DDCVGA_A__DC_GPIO_DDCVGADATA_A__SHIFT: c_uint = 0x8;
pub const DC_GPIO_DDCVGA_A__DC_GPIO_DDCVGACLK_A_MASK: c_uint = 0x00000001L;
pub const DC_GPIO_DDCVGA_A__DC_GPIO_DDCVGADATA_A_MASK: c_uint = 0x00000100L;
// DC_GPIO_DDCVGA_EN
pub const DC_GPIO_DDCVGA_EN__DC_GPIO_DDCVGACLK_EN__SHIFT: c_uint = 0x0;
pub const DC_GPIO_DDCVGA_EN__DC_GPIO_DDCVGADATA_EN__SHIFT: c_uint = 0x8;
pub const DC_GPIO_DDCVGA_EN__DC_GPIO_DDCVGACLK_EN_MASK: c_uint = 0x00000001L;
pub const DC_GPIO_DDCVGA_EN__DC_GPIO_DDCVGADATA_EN_MASK: c_uint = 0x00000100L;
// DC_GPIO_DDCVGA_Y
pub const DC_GPIO_DDCVGA_Y__DC_GPIO_DDCVGACLK_Y__SHIFT: c_uint = 0x0;
pub const DC_GPIO_DDCVGA_Y__DC_GPIO_DDCVGADATA_Y__SHIFT: c_uint = 0x8;
pub const DC_GPIO_DDCVGA_Y__DC_GPIO_DDCVGACLK_Y_MASK: c_uint = 0x00000001L;
pub const DC_GPIO_DDCVGA_Y__DC_GPIO_DDCVGADATA_Y_MASK: c_uint = 0x00000100L;
// DC_GPIO_PWRSEQ0_EN
pub const DC_GPIO_PWRSEQ0_EN__DC_GPIO_VARY_BL_OTG_VSYNC_EN__SHIFT: c_uint = 0x14;
pub const DC_GPIO_PWRSEQ0_EN__DC_GPIO_VARY_BL_OTG_VSYNC_SEL__SHIFT: c_uint = 0x15;
pub const DC_GPIO_PWRSEQ0_EN__DC_GPIO_BLON_OTG_VSYNC_EN__SHIFT: c_uint = 0x19;
pub const DC_GPIO_PWRSEQ0_EN__DC_GPIO_BLON_OTG_VSYNC_SEL__SHIFT: c_uint = 0x1a;
pub const DC_GPIO_PWRSEQ0_EN__DC_GPIO_VARY_BL_GENERICA_EN__SHIFT: c_uint = 0x1d;
pub const DC_GPIO_PWRSEQ0_EN__DC_GPIO_VARY_BL_OTG_VSYNC_EN_MASK: c_uint = 0x00100000L;
pub const DC_GPIO_PWRSEQ0_EN__DC_GPIO_VARY_BL_OTG_VSYNC_SEL_MASK: c_uint = 0x00E00000L;
pub const DC_GPIO_PWRSEQ0_EN__DC_GPIO_BLON_OTG_VSYNC_EN_MASK: c_uint = 0x02000000L;
pub const DC_GPIO_PWRSEQ0_EN__DC_GPIO_BLON_OTG_VSYNC_SEL_MASK: c_uint = 0x1C000000L;
pub const DC_GPIO_PWRSEQ0_EN__DC_GPIO_VARY_BL_GENERICA_EN_MASK: c_uint = 0x20000000L;
// DC_GPIO_PAD_STRENGTH_1
pub const DC_GPIO_PAD_STRENGTH_1__GENLK_STRENGTH_SN__SHIFT: c_uint = 0x0;
pub const DC_GPIO_PAD_STRENGTH_1__GENLK_STRENGTH_SP__SHIFT: c_uint = 0x4;
pub const DC_GPIO_PAD_STRENGTH_1__SYNC_STRENGTH_SN__SHIFT: c_uint = 0x18;
pub const DC_GPIO_PAD_STRENGTH_1__SYNC_STRENGTH_SP__SHIFT: c_uint = 0x1c;
pub const DC_GPIO_PAD_STRENGTH_1__GENLK_STRENGTH_SN_MASK: c_uint = 0x0000000FL;
pub const DC_GPIO_PAD_STRENGTH_1__GENLK_STRENGTH_SP_MASK: c_uint = 0x000000F0L;
pub const DC_GPIO_PAD_STRENGTH_1__SYNC_STRENGTH_SN_MASK: c_uint = 0x0F000000L;
pub const DC_GPIO_PAD_STRENGTH_1__SYNC_STRENGTH_SP_MASK: c_uint = 0xF0000000L;
// PHY_AUX_CNTL
pub const PHY_AUX_CNTL__AUX1_PAD_RXSEL__SHIFT: c_uint = 0xa;
pub const PHY_AUX_CNTL__AUX2_PAD_RXSEL__SHIFT: c_uint = 0xc;
pub const PHY_AUX_CNTL__AUX3_PAD_RXSEL__SHIFT: c_uint = 0xe;
pub const PHY_AUX_CNTL__AUX1_PAD_RXSEL_MASK: c_uint = 0x00000C00L;
pub const PHY_AUX_CNTL__AUX2_PAD_RXSEL_MASK: c_uint = 0x00003000L;
pub const PHY_AUX_CNTL__AUX3_PAD_RXSEL_MASK: c_uint = 0x0000C000L;
// DC_GPIO_AUX_CTRL_0
pub const DC_GPIO_AUX_CTRL_0__DC_GPIO_DDCVGA_FALLSLEWSEL__SHIFT: c_uint = 0xc;
pub const DC_GPIO_AUX_CTRL_0__DC_GPIO_DDCVGA_SPIKERCEN__SHIFT: c_uint = 0x16;
pub const DC_GPIO_AUX_CTRL_0__DC_GPIO_DDCVGA_SPIKERCSEL__SHIFT: c_uint = 0x1e;
pub const DC_GPIO_AUX_CTRL_0__DC_GPIO_DDCVGA_FALLSLEWSEL_MASK: c_uint = 0x00003000L;
pub const DC_GPIO_AUX_CTRL_0__DC_GPIO_DDCVGA_SPIKERCEN_MASK: c_uint = 0x00C00000L;
pub const DC_GPIO_AUX_CTRL_0__DC_GPIO_DDCVGA_SPIKERCSEL_MASK: c_uint = 0xC0000000L;
// DC_GPIO_AUX_CTRL_1
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_CSEL_0P9__SHIFT: c_uint = 0x4;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_CSEL_1P1__SHIFT: c_uint = 0x5;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_RSEL_0P9__SHIFT: c_uint = 0x6;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_RSEL_1P1__SHIFT: c_uint = 0x7;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_RESBIASEN__SHIFT: c_uint = 0xb;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_AUX1_COMPSEL__SHIFT: c_uint = 0xd;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_DDCVGA_SPARE__SHIFT: c_uint = 0xe;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_BIASCRTEN__SHIFT: c_uint = 0x10;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_DDCVGA_SLEWN__SHIFT: c_uint = 0x12;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_DDCVGA_RXSEL__SHIFT: c_uint = 0x14;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_AUX2_COMPSEL__SHIFT: c_uint = 0x19;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_AUX3_COMPSEL__SHIFT: c_uint = 0x1a;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_DDCVGA_COMPSEL__SHIFT: c_uint = 0x1e;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_CSEL_0P9_MASK: c_uint = 0x00000010L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_CSEL_1P1_MASK: c_uint = 0x00000020L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_RSEL_0P9_MASK: c_uint = 0x00000040L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_RSEL_1P1_MASK: c_uint = 0x00000080L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_RESBIASEN_MASK: c_uint = 0x00001800L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_AUX1_COMPSEL_MASK: c_uint = 0x00002000L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_DDCVGA_SPARE_MASK: c_uint = 0x0000C000L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_I2C_BIASCRTEN_MASK: c_uint = 0x00030000L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_DDCVGA_SLEWN_MASK: c_uint = 0x000C0000L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_DDCVGA_RXSEL_MASK: c_uint = 0x00300000L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_AUX2_COMPSEL_MASK: c_uint = 0x02000000L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_AUX3_COMPSEL_MASK: c_uint = 0x04000000L;
pub const DC_GPIO_AUX_CTRL_1__DC_GPIO_DDCVGA_COMPSEL_MASK: c_uint = 0xC0000000L;
// DC_GPIO_AUX_CTRL_3
pub const DC_GPIO_AUX_CTRL_3__AUX1_NEN_RTERM__SHIFT: c_uint = 0x0;
pub const DC_GPIO_AUX_CTRL_3__AUX2_NEN_RTERM__SHIFT: c_uint = 0x1;
pub const DC_GPIO_AUX_CTRL_3__AUX3_NEN_RTERM__SHIFT: c_uint = 0x2;
pub const DC_GPIO_AUX_CTRL_3__AUX1_DP_DN_SWAP__SHIFT: c_uint = 0x8;
pub const DC_GPIO_AUX_CTRL_3__AUX2_DP_DN_SWAP__SHIFT: c_uint = 0x9;
pub const DC_GPIO_AUX_CTRL_3__AUX3_DP_DN_SWAP__SHIFT: c_uint = 0xa;
pub const DC_GPIO_AUX_CTRL_3__AUX1_HYS_TUNE__SHIFT: c_uint = 0x10;
pub const DC_GPIO_AUX_CTRL_3__AUX2_HYS_TUNE__SHIFT: c_uint = 0x12;
pub const DC_GPIO_AUX_CTRL_3__AUX3_HYS_TUNE__SHIFT: c_uint = 0x14;
pub const DC_GPIO_AUX_CTRL_3__AUX1_NEN_RTERM_MASK: c_uint = 0x00000001L;
pub const DC_GPIO_AUX_CTRL_3__AUX2_NEN_RTERM_MASK: c_uint = 0x00000002L;
pub const DC_GPIO_AUX_CTRL_3__AUX3_NEN_RTERM_MASK: c_uint = 0x00000004L;
pub const DC_GPIO_AUX_CTRL_3__AUX1_DP_DN_SWAP_MASK: c_uint = 0x00000100L;
pub const DC_GPIO_AUX_CTRL_3__AUX2_DP_DN_SWAP_MASK: c_uint = 0x00000200L;
pub const DC_GPIO_AUX_CTRL_3__AUX3_DP_DN_SWAP_MASK: c_uint = 0x00000400L;
pub const DC_GPIO_AUX_CTRL_3__AUX1_HYS_TUNE_MASK: c_uint = 0x00030000L;
pub const DC_GPIO_AUX_CTRL_3__AUX2_HYS_TUNE_MASK: c_uint = 0x000C0000L;
pub const DC_GPIO_AUX_CTRL_3__AUX3_HYS_TUNE_MASK: c_uint = 0x00300000L;
// DC_GPIO_AUX_CTRL_4
pub const DC_GPIO_AUX_CTRL_4__AUX1_AUX_CTRL__SHIFT: c_uint = 0x0;
pub const DC_GPIO_AUX_CTRL_4__AUX2_AUX_CTRL__SHIFT: c_uint = 0x4;
pub const DC_GPIO_AUX_CTRL_4__AUX3_AUX_CTRL__SHIFT: c_uint = 0x8;
pub const DC_GPIO_AUX_CTRL_4__AUX1_AUX_CTRL_MASK: c_uint = 0x0000000FL;
pub const DC_GPIO_AUX_CTRL_4__AUX2_AUX_CTRL_MASK: c_uint = 0x000000F0L;
pub const DC_GPIO_AUX_CTRL_4__AUX3_AUX_CTRL_MASK: c_uint = 0x00000F00L;
// DC_GPIO_AUX_CTRL_5
pub const DC_GPIO_AUX_CTRL_5__AUX1_VOD_TUNE__SHIFT: c_uint = 0x0;
pub const DC_GPIO_AUX_CTRL_5__AUX2_VOD_TUNE__SHIFT: c_uint = 0x2;
pub const DC_GPIO_AUX_CTRL_5__AUX3_VOD_TUNE__SHIFT: c_uint = 0x4;
pub const DC_GPIO_AUX_CTRL_5__DDC_PAD1_I2CMODE__SHIFT: c_uint = 0xc;
pub const DC_GPIO_AUX_CTRL_5__DDC_PAD2_I2CMODE__SHIFT: c_uint = 0xd;
pub const DC_GPIO_AUX_CTRL_5__DDC_PAD3_I2CMODE__SHIFT: c_uint = 0xe;
pub const DC_GPIO_AUX_CTRL_5__DDC1_PAD_I2C_CTRL__SHIFT: c_uint = 0x18;
pub const DC_GPIO_AUX_CTRL_5__DDC2_PAD_I2C_CTRL__SHIFT: c_uint = 0x19;
pub const DC_GPIO_AUX_CTRL_5__DDC3_PAD_I2C_CTRL__SHIFT: c_uint = 0x1a;
pub const DC_GPIO_AUX_CTRL_5__AUX1_VOD_TUNE_MASK: c_uint = 0x00000003L;
pub const DC_GPIO_AUX_CTRL_5__AUX2_VOD_TUNE_MASK: c_uint = 0x0000000CL;
pub const DC_GPIO_AUX_CTRL_5__AUX3_VOD_TUNE_MASK: c_uint = 0x00000030L;
pub const DC_GPIO_AUX_CTRL_5__DDC_PAD1_I2CMODE_MASK: c_uint = 0x00001000L;
pub const DC_GPIO_AUX_CTRL_5__DDC_PAD2_I2CMODE_MASK: c_uint = 0x00002000L;
pub const DC_GPIO_AUX_CTRL_5__DDC_PAD3_I2CMODE_MASK: c_uint = 0x00004000L;
pub const DC_GPIO_AUX_CTRL_5__DDC1_PAD_I2C_CTRL_MASK: c_uint = 0x01000000L;
pub const DC_GPIO_AUX_CTRL_5__DDC2_PAD_I2C_CTRL_MASK: c_uint = 0x02000000L;
pub const DC_GPIO_AUX_CTRL_5__DDC3_PAD_I2C_CTRL_MASK: c_uint = 0x04000000L;
// AUXI2C_PAD_ALL_PWR_OK
pub const AUXI2C_PAD_ALL_PWR_OK__AUXI2C_PHY1_ALL_PWR_OK__SHIFT: c_uint = 0x0;
pub const AUXI2C_PAD_ALL_PWR_OK__AUXI2C_PHY2_ALL_PWR_OK__SHIFT: c_uint = 0x1;
pub const AUXI2C_PAD_ALL_PWR_OK__AUXI2C_PHY3_ALL_PWR_OK__SHIFT: c_uint = 0x2;
pub const AUXI2C_PAD_ALL_PWR_OK__AUXI2C_PHY1_ALL_PWR_OK_MASK: c_uint = 0x00000001L;
pub const AUXI2C_PAD_ALL_PWR_OK__AUXI2C_PHY2_ALL_PWR_OK_MASK: c_uint = 0x00000002L;
pub const AUXI2C_PAD_ALL_PWR_OK__AUXI2C_PHY3_ALL_PWR_OK_MASK: c_uint = 0x00000004L;
