//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/amd/include/asic_reg/smuio/smuio_11_0_0_sh_mask.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// Copyright (C) 2019  Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
// AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

// Macro flag: #define _smuio_11_0_0_SH_MASK_HEADER
// addressBlock: smuio_smuio_SmuSmuioDec
// SMUSVI0_TEL_PLANE0
pub const SMUSVI0_TEL_PLANE0__SVI0_PLANE0_IDDCOR__SHIFT: c_uint = 0x0;
pub const SMUSVI0_TEL_PLANE0__SVI0_PLANE0_VDDCOR__SHIFT: c_uint = 0x10;
pub const SMUSVI0_TEL_PLANE0__SVI0_PLANE0_IDDCOR_MASK: c_uint = 0x000000FFL;
pub const SMUSVI0_TEL_PLANE0__SVI0_PLANE0_VDDCOR_MASK: c_uint = 0x01FF0000L;
// SMUIO_MCM_CONFIG
pub const SMUIO_MCM_CONFIG__DIE_ID__SHIFT: c_uint = 0x0;
pub const SMUIO_MCM_CONFIG__PKG_TYPE__SHIFT: c_uint = 0x2;
pub const SMUIO_MCM_CONFIG__SOCKET_ID__SHIFT: c_uint = 0x5;
pub const SMUIO_MCM_CONFIG__PKG_SUBTYPE__SHIFT: c_uint = 0x6;
pub const SMUIO_MCM_CONFIG__DIE_ID_MASK: c_uint = 0x00000003L;
pub const SMUIO_MCM_CONFIG__PKG_TYPE_MASK: c_uint = 0x0000001CL;
pub const SMUIO_MCM_CONFIG__SOCKET_ID_MASK: c_uint = 0x00000020L;
pub const SMUIO_MCM_CONFIG__PKG_SUBTYPE_MASK: c_uint = 0x000000C0L;
// CKSVII2C_IC_CON
pub const CKSVII2C_IC_CON__IC_MASTER_MODE__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_CON__IC_MAX_SPEED_MODE__SHIFT: c_uint = 0x1;
pub const CKSVII2C_IC_CON__IC_10BITADDR_SLAVE__SHIFT: c_uint = 0x3;
pub const CKSVII2C_IC_CON__IC_10BITADDR_MASTER__SHIFT: c_uint = 0x4;
pub const CKSVII2C_IC_CON__IC_RESTART_EN__SHIFT: c_uint = 0x5;
pub const CKSVII2C_IC_CON__IC_SLAVE_DISABLE__SHIFT: c_uint = 0x6;
pub const CKSVII2C_IC_CON__STOP_DET_IFADDRESSED__SHIFT: c_uint = 0x7;
pub const CKSVII2C_IC_CON__TX_EMPTY_CTRL__SHIFT: c_uint = 0x8;
pub const CKSVII2C_IC_CON__RX_FIFO_FULL_HLD_CTRL__SHIFT: c_uint = 0x9;
pub const CKSVII2C_IC_CON__IC_MASTER_MODE_MASK: c_uint = 0x00000001L;
pub const CKSVII2C_IC_CON__IC_MAX_SPEED_MODE_MASK: c_uint = 0x00000006L;
pub const CKSVII2C_IC_CON__IC_10BITADDR_SLAVE_MASK: c_uint = 0x00000008L;
pub const CKSVII2C_IC_CON__IC_10BITADDR_MASTER_MASK: c_uint = 0x00000010L;
pub const CKSVII2C_IC_CON__IC_RESTART_EN_MASK: c_uint = 0x00000020L;
pub const CKSVII2C_IC_CON__IC_SLAVE_DISABLE_MASK: c_uint = 0x00000040L;
pub const CKSVII2C_IC_CON__STOP_DET_IFADDRESSED_MASK: c_uint = 0x00000080L;
pub const CKSVII2C_IC_CON__TX_EMPTY_CTRL_MASK: c_uint = 0x00000100L;
pub const CKSVII2C_IC_CON__RX_FIFO_FULL_HLD_CTRL_MASK: c_uint = 0x00000200L;
// CKSVII2C_IC_TAR
pub const CKSVII2C_IC_TAR__IC_TAR__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_TAR__GC_OR_START__SHIFT: c_uint = 0xa;
pub const CKSVII2C_IC_TAR__SPECIAL__SHIFT: c_uint = 0xb;
pub const CKSVII2C_IC_TAR__IC_10BITADDR_MASTER__SHIFT: c_uint = 0xc;
pub const CKSVII2C_IC_TAR__IC_TAR_MASK: c_uint = 0x000003FFL;
pub const CKSVII2C_IC_TAR__GC_OR_START_MASK: c_uint = 0x00000400L;
pub const CKSVII2C_IC_TAR__SPECIAL_MASK: c_uint = 0x00000800L;
pub const CKSVII2C_IC_TAR__IC_10BITADDR_MASTER_MASK: c_uint = 0x00001000L;
// CKSVII2C_IC_SAR
pub const CKSVII2C_IC_SAR__IC_SAR__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_SAR__IC_SAR_MASK: c_uint = 0x000003FFL;
// CKSVII2C_IC_HS_MADDR
pub const CKSVII2C_IC_HS_MADDR__IC_HS_MADDR__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_HS_MADDR__IC_HS_MADDR_MASK: c_uint = 0x00000007L;
// CKSVII2C_IC_DATA_CMD
pub const CKSVII2C_IC_DATA_CMD__DAT__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_DATA_CMD__CMD__SHIFT: c_uint = 0x8;
pub const CKSVII2C_IC_DATA_CMD__STOP__SHIFT: c_uint = 0x9;
pub const CKSVII2C_IC_DATA_CMD__RESTART__SHIFT: c_uint = 0xa;
pub const CKSVII2C_IC_DATA_CMD__DAT_MASK: c_uint = 0x000000FFL;
pub const CKSVII2C_IC_DATA_CMD__CMD_MASK: c_uint = 0x00000100L;
pub const CKSVII2C_IC_DATA_CMD__STOP_MASK: c_uint = 0x00000200L;
pub const CKSVII2C_IC_DATA_CMD__RESTART_MASK: c_uint = 0x00000400L;
// CKSVII2C_IC_SS_SCL_HCNT
pub const CKSVII2C_IC_SS_SCL_HCNT__IC_SS_SCL_HCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_SS_SCL_HCNT__IC_SS_SCL_HCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C_IC_SS_SCL_LCNT
pub const CKSVII2C_IC_SS_SCL_LCNT__IC_SS_SCL_LCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_SS_SCL_LCNT__IC_SS_SCL_LCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C_IC_FS_SCL_HCNT
pub const CKSVII2C_IC_FS_SCL_HCNT__IC_FS_SCL_HCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_FS_SCL_HCNT__IC_FS_SCL_HCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C_IC_FS_SCL_LCNT
pub const CKSVII2C_IC_FS_SCL_LCNT__IC_FS_SCL_LCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_FS_SCL_LCNT__IC_FS_SCL_LCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C_IC_HS_SCL_HCNT
pub const CKSVII2C_IC_HS_SCL_HCNT__IC_HS_SCL_HCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_HS_SCL_HCNT__IC_HS_SCL_HCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C_IC_HS_SCL_LCNT
pub const CKSVII2C_IC_HS_SCL_LCNT__IC_HS_SCL_LCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_HS_SCL_LCNT__IC_HS_SCL_LCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C_IC_INTR_STAT
pub const CKSVII2C_IC_INTR_STAT__R_RX_UNDER__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_INTR_STAT__R_RX_OVER__SHIFT: c_uint = 0x1;
pub const CKSVII2C_IC_INTR_STAT__R_RX_FULL__SHIFT: c_uint = 0x2;
pub const CKSVII2C_IC_INTR_STAT__R_TX_OVER__SHIFT: c_uint = 0x3;
pub const CKSVII2C_IC_INTR_STAT__R_TX_EMPTY__SHIFT: c_uint = 0x4;
pub const CKSVII2C_IC_INTR_STAT__R_RD_REQ__SHIFT: c_uint = 0x5;
pub const CKSVII2C_IC_INTR_STAT__R_TX_ABRT__SHIFT: c_uint = 0x6;
pub const CKSVII2C_IC_INTR_STAT__R_RX_DONE__SHIFT: c_uint = 0x7;
pub const CKSVII2C_IC_INTR_STAT__R_ACTIVITY__SHIFT: c_uint = 0x8;
pub const CKSVII2C_IC_INTR_STAT__R_STOP_DET__SHIFT: c_uint = 0x9;
pub const CKSVII2C_IC_INTR_STAT__R_START_DET__SHIFT: c_uint = 0xa;
pub const CKSVII2C_IC_INTR_STAT__R_GEN_CALL__SHIFT: c_uint = 0xb;
pub const CKSVII2C_IC_INTR_STAT__R_RESTART_DET__SHIFT: c_uint = 0xc;
pub const CKSVII2C_IC_INTR_STAT__R_MST_ON_HOLD__SHIFT: c_uint = 0xd;
pub const CKSVII2C_IC_INTR_STAT__R_RX_UNDER_MASK: c_uint = 0x00000001L;
pub const CKSVII2C_IC_INTR_STAT__R_RX_OVER_MASK: c_uint = 0x00000002L;
pub const CKSVII2C_IC_INTR_STAT__R_RX_FULL_MASK: c_uint = 0x00000004L;
pub const CKSVII2C_IC_INTR_STAT__R_TX_OVER_MASK: c_uint = 0x00000008L;
pub const CKSVII2C_IC_INTR_STAT__R_TX_EMPTY_MASK: c_uint = 0x00000010L;
pub const CKSVII2C_IC_INTR_STAT__R_RD_REQ_MASK: c_uint = 0x00000020L;
pub const CKSVII2C_IC_INTR_STAT__R_TX_ABRT_MASK: c_uint = 0x00000040L;
pub const CKSVII2C_IC_INTR_STAT__R_RX_DONE_MASK: c_uint = 0x00000080L;
pub const CKSVII2C_IC_INTR_STAT__R_ACTIVITY_MASK: c_uint = 0x00000100L;
pub const CKSVII2C_IC_INTR_STAT__R_STOP_DET_MASK: c_uint = 0x00000200L;
pub const CKSVII2C_IC_INTR_STAT__R_START_DET_MASK: c_uint = 0x00000400L;
pub const CKSVII2C_IC_INTR_STAT__R_GEN_CALL_MASK: c_uint = 0x00000800L;
pub const CKSVII2C_IC_INTR_STAT__R_RESTART_DET_MASK: c_uint = 0x00001000L;
pub const CKSVII2C_IC_INTR_STAT__R_MST_ON_HOLD_MASK: c_uint = 0x00002000L;
// CKSVII2C_IC_INTR_MASK
pub const CKSVII2C_IC_INTR_MASK__M_RX_UNDER__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_INTR_MASK__M_RX_OVER__SHIFT: c_uint = 0x1;
pub const CKSVII2C_IC_INTR_MASK__M_RX_FULL__SHIFT: c_uint = 0x2;
pub const CKSVII2C_IC_INTR_MASK__M_TX_OVER__SHIFT: c_uint = 0x3;
pub const CKSVII2C_IC_INTR_MASK__M_TX_EMPTY__SHIFT: c_uint = 0x4;
pub const CKSVII2C_IC_INTR_MASK__M_RD_REQ__SHIFT: c_uint = 0x5;
pub const CKSVII2C_IC_INTR_MASK__M_TX_ABRT__SHIFT: c_uint = 0x6;
pub const CKSVII2C_IC_INTR_MASK__M_RX_DONE__SHIFT: c_uint = 0x7;
pub const CKSVII2C_IC_INTR_MASK__M_ACTIVITY__SHIFT: c_uint = 0x8;
pub const CKSVII2C_IC_INTR_MASK__M_STOP_DET__SHIFT: c_uint = 0x9;
pub const CKSVII2C_IC_INTR_MASK__M_START_DET__SHIFT: c_uint = 0xa;
pub const CKSVII2C_IC_INTR_MASK__M_GEN_CALL__SHIFT: c_uint = 0xb;
pub const CKSVII2C_IC_INTR_MASK__M_RESTART_DET__SHIFT: c_uint = 0xc;
pub const CKSVII2C_IC_INTR_MASK__M_MST_ON_HOLD__SHIFT: c_uint = 0xd;
pub const CKSVII2C_IC_INTR_MASK__M_RX_UNDER_MASK: c_uint = 0x00000001L;
pub const CKSVII2C_IC_INTR_MASK__M_RX_OVER_MASK: c_uint = 0x00000002L;
pub const CKSVII2C_IC_INTR_MASK__M_RX_FULL_MASK: c_uint = 0x00000004L;
pub const CKSVII2C_IC_INTR_MASK__M_TX_OVER_MASK: c_uint = 0x00000008L;
pub const CKSVII2C_IC_INTR_MASK__M_TX_EMPTY_MASK: c_uint = 0x00000010L;
pub const CKSVII2C_IC_INTR_MASK__M_RD_REQ_MASK: c_uint = 0x00000020L;
pub const CKSVII2C_IC_INTR_MASK__M_TX_ABRT_MASK: c_uint = 0x00000040L;
pub const CKSVII2C_IC_INTR_MASK__M_RX_DONE_MASK: c_uint = 0x00000080L;
pub const CKSVII2C_IC_INTR_MASK__M_ACTIVITY_MASK: c_uint = 0x00000100L;
pub const CKSVII2C_IC_INTR_MASK__M_STOP_DET_MASK: c_uint = 0x00000200L;
pub const CKSVII2C_IC_INTR_MASK__M_START_DET_MASK: c_uint = 0x00000400L;
pub const CKSVII2C_IC_INTR_MASK__M_GEN_CALL_MASK: c_uint = 0x00000800L;
pub const CKSVII2C_IC_INTR_MASK__M_RESTART_DET_MASK: c_uint = 0x00001000L;
pub const CKSVII2C_IC_INTR_MASK__M_MST_ON_HOLD_MASK: c_uint = 0x00002000L;
// CKSVII2C_IC_RAW_INTR_STAT
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RX_UNDER__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RX_OVER__SHIFT: c_uint = 0x1;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RX_FULL__SHIFT: c_uint = 0x2;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_TX_OVER__SHIFT: c_uint = 0x3;
pub const CKSVII2C_IC__RAW_INTR_STAT__R_TX_EMPTY__SHIFT: c_uint = 0x4;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RD_REQ__SHIFT: c_uint = 0x5;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_TX_ABRT__SHIFT: c_uint = 0x6;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RX_DONE__SHIFT: c_uint = 0x7;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_ACTIVITY__SHIFT: c_uint = 0x8;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_STOP_DET__SHIFT: c_uint = 0x9;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_START_DET__SHIFT: c_uint = 0xa;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_GEN_CALL__SHIFT: c_uint = 0xb;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RESTART_DET__SHIFT: c_uint = 0xc;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_MST_ON_HOLD__SHIFT: c_uint = 0xd;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RX_UNDER_MASK: c_uint = 0x00000001L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RX_OVER_MASK: c_uint = 0x00000002L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RX_FULL_MASK: c_uint = 0x00000004L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_TX_OVER_MASK: c_uint = 0x00000008L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_TX_EMPTY_MASK: c_uint = 0x00000010L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RD_REQ_MASK: c_uint = 0x00000020L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_TX_ABRT_MASK: c_uint = 0x00000040L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RX_DONE_MASK: c_uint = 0x00000080L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_ACTIVITY_MASK: c_uint = 0x00000100L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_STOP_DET_MASK: c_uint = 0x00000200L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_START_DET_MASK: c_uint = 0x00000400L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_GEN_CALL_MASK: c_uint = 0x00000800L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_RESTART_DET_MASK: c_uint = 0x00001000L;
pub const CKSVII2C_IC_RAW_INTR_STAT__R_MST_ON_HOLD_MASK: c_uint = 0x00002000L;
// CKSVII2C_IC_RX_TL
// CKSVII2C_IC_TX_TL
// CKSVII2C_IC_CLR_INTR
// CKSVII2C_IC_CLR_RX_UNDER
// CKSVII2C_IC_CLR_RX_OVER
// CKSVII2C_IC_CLR_TX_OVER
// CKSVII2C_IC_CLR_RD_REQ
// CKSVII2C_IC_CLR_TX_ABRT
// CKSVII2C_IC_CLR_RX_DONE
// CKSVII2C_IC_CLR_ACTIVITY
pub const CKSVII2C_IC_CLR_ACTIVITY__CLR_ACTIVITY__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_CLR_ACTIVITY__CLR_ACTIVITY_MASK: c_uint = 0x00000001L;
// CKSVII2C_IC_CLR_STOP_DET
// CKSVII2C_IC_CLR_START_DET
// CKSVII2C_IC_CLR_GEN_CALL
// CKSVII2C_IC_ENABLE
pub const CKSVII2C_IC_ENABLE__ENABLE__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_ENABLE__ABORT__SHIFT: c_uint = 0x1;
pub const CKSVII2C_IC_ENABLE__ENABLE_MASK: c_uint = 0x00000001L;
pub const CKSVII2C_IC_ENABLE__ABORT_MASK: c_uint = 0x00000002L;
// CKSVII2C_IC_STATUS
pub const CKSVII2C_IC_STATUS__ACTIVITY__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_STATUS__TFNF__SHIFT: c_uint = 0x1;
pub const CKSVII2C_IC_STATUS__TFE__SHIFT: c_uint = 0x2;
pub const CKSVII2C_IC_STATUS__RFNE__SHIFT: c_uint = 0x3;
pub const CKSVII2C_IC_STATUS__RFF__SHIFT: c_uint = 0x4;
pub const CKSVII2C_IC_STATUS__MST_ACTIVITY__SHIFT: c_uint = 0x5;
pub const CKSVII2C_IC_STATUS__SLV_ACTIVITY__SHIFT: c_uint = 0x6;
pub const CKSVII2C_IC_STATUS__ACTIVITY_MASK: c_uint = 0x00000001L;
pub const CKSVII2C_IC_STATUS__TFNF_MASK: c_uint = 0x00000002L;
pub const CKSVII2C_IC_STATUS__TFE_MASK: c_uint = 0x00000004L;
pub const CKSVII2C_IC_STATUS__RFNE_MASK: c_uint = 0x00000008L;
pub const CKSVII2C_IC_STATUS__RFF_MASK: c_uint = 0x00000010L;
pub const CKSVII2C_IC_STATUS__MST_ACTIVITY_MASK: c_uint = 0x00000020L;
pub const CKSVII2C_IC_STATUS__SLV_ACTIVITY_MASK: c_uint = 0x00000040L;
// CKSVII2C_IC_TXFLR
// CKSVII2C_IC_RXFLR
// CKSVII2C_IC_SDA_HOLD
pub const CKSVII2C_IC_SDA_HOLD__IC_SDA_HOLD__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_SDA_HOLD__IC_SDA_HOLD_MASK: c_uint = 0x00FFFFFFL;
// CKSVII2C_IC_TX_ABRT_SOURCE
pub const CKSVII2C_IC_TX_ABRT_SOURCE__ABRT_7B_ADDR_NOACK__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_TX_ABRT_SOURCE__ABRT_10ADDR1_NOACK__SHIFT: c_uint = 0x1;
pub const CKSVII2C_IC_TX_ABRT_SOURCE__ABRT_10ADDR2_NOACK__SHIFT: c_uint = 0x2;
pub const CKSVII2C_IC_TX_ABRT_SOURCE__ABRT_TXDATA_NOACK__SHIFT: c_uint = 0x3;
pub const CKSVII2C_IC_TX_ABRT_SOURCE__ABRT_7B_ADDR_NOACK_MASK: c_uint = 0x00000001L;
pub const CKSVII2C_IC_TX_ABRT_SOURCE__ABRT_10ADDR1_NOACK_MASK: c_uint = 0x00000002L;
pub const CKSVII2C_IC_TX_ABRT_SOURCE__ABRT_10ADDR2_NOACK_MASK: c_uint = 0x00000004L;
pub const CKSVII2C_IC_TX_ABRT_SOURCE__ABRT_TXDATA_NOACK_MASK: c_uint = 0x00000008L;
// CKSVII2C_IC_SLV_DATA_NACK_ONLY
// CKSVII2C_IC_DMA_CR
// CKSVII2C_IC_DMA_TDLR
// CKSVII2C_IC_DMA_RDLR
// CKSVII2C_IC_SDA_SETUP
pub const CKSVII2C_IC_SDA_SETUP__SDA_SETUP__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_SDA_SETUP__SDA_SETUP_MASK: c_uint = 0x000000FFL;
// CKSVII2C_IC_ACK_GENERAL_CALL
pub const CKSVII2C_IC_ACK_GENERAL_CALL__ACK_GENERAL_CALL__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_ACK_GENERAL_CALL__ACK_GENERAL_CALL_MASK: c_uint = 0x00000001L;
// CKSVII2C_IC_ENABLE_STATUS
pub const CKSVII2C_IC_ENABLE_STATUS__IC_EN__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_ENABLE_STATUS__SLV_RX_ABORTED__SHIFT: c_uint = 0x1;
pub const CKSVII2C_IC_ENABLE_STATUS__SLV_FIFO_FILLED_AND_FLUSHED__SHIFT: c_uint = 0x2;
pub const CKSVII2C_IC_ENABLE_STATUS__IC_EN_MASK: c_uint = 0x00000001L;
pub const CKSVII2C_IC_ENABLE_STATUS__SLV_RX_ABORTED_MASK: c_uint = 0x00000002L;
pub const CKSVII2C_IC_ENABLE_STATUS__SLV_FIFO_FILLED_AND_FLUSHED_MASK: c_uint = 0x00000004L;
// CKSVII2C_IC_FS_SPKLEN
pub const CKSVII2C_IC_FS_SPKLEN__FS_SPKLEN__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_FS_SPKLEN__FS_SPKLEN_MASK: c_uint = 0x000000FFL;
// CKSVII2C_IC_HS_SPKLEN
pub const CKSVII2C_IC_HS_SPKLEN__HS_SPKLEN__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_HS_SPKLEN__HS_SPKLEN_MASK: c_uint = 0x000000FFL;
// CKSVII2C_IC_CLR_RESTART_DET
// CKSVII2C_IC_COMP_PARAM_1
pub const CKSVII2C_IC_COMP_PARAM_1__COMP_PARAM_1__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_COMP_PARAM_1__COMP_PARAM_1_MASK: c_uint = 0xFFFFFFFFL;
// CKSVII2C_IC_COMP_VERSION
pub const CKSVII2C_IC_COMP_VERSION__COMP_VERSION__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_COMP_VERSION__COMP_VERSION_MASK: c_uint = 0xFFFFFFFFL;
// CKSVII2C_IC_COMP_TYPE
pub const CKSVII2C_IC_COMP_TYPE__COMP_TYPE__SHIFT: c_uint = 0x0;
pub const CKSVII2C_IC_COMP_TYPE__COMP_TYPE_MASK: c_uint = 0xFFFFFFFFL;
// CKSVII2C1_IC_CON
pub const CKSVII2C1_IC_CON__IC1_MASTER_MODE__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_CON__IC1_MAX_SPEED_MODE__SHIFT: c_uint = 0x1;
pub const CKSVII2C1_IC_CON__IC1_10BITADDR_SLAVE__SHIFT: c_uint = 0x3;
pub const CKSVII2C1_IC_CON__IC1_10BITADDR_MASTER__SHIFT: c_uint = 0x4;
pub const CKSVII2C1_IC_CON__IC1_RESTART_EN__SHIFT: c_uint = 0x5;
pub const CKSVII2C1_IC_CON__IC1_SLAVE_DISABLE__SHIFT: c_uint = 0x6;
pub const CKSVII2C1_IC_CON__STOP1_DET_IFADDRESSED__SHIFT: c_uint = 0x7;
pub const CKSVII2C1_IC_CON__TX1_EMPTY_CTRL__SHIFT: c_uint = 0x8;
pub const CKSVII2C1_IC_CON__RX1_FIFO_FULL_HLD_CTRL__SHIFT: c_uint = 0x9;
pub const CKSVII2C1_IC_CON__IC1_MASTER_MODE_MASK: c_uint = 0x00000001L;
pub const CKSVII2C1_IC_CON__IC1_MAX_SPEED_MODE_MASK: c_uint = 0x00000006L;
pub const CKSVII2C1_IC_CON__IC1_10BITADDR_SLAVE_MASK: c_uint = 0x00000008L;
pub const CKSVII2C1_IC_CON__IC1_10BITADDR_MASTER_MASK: c_uint = 0x00000010L;
pub const CKSVII2C1_IC_CON__IC1_RESTART_EN_MASK: c_uint = 0x00000020L;
pub const CKSVII2C1_IC_CON__IC1_SLAVE_DISABLE_MASK: c_uint = 0x00000040L;
pub const CKSVII2C1_IC_CON__STOP1_DET_IFADDRESSED_MASK: c_uint = 0x00000080L;
pub const CKSVII2C1_IC_CON__TX1_EMPTY_CTRL_MASK: c_uint = 0x00000100L;
pub const CKSVII2C1_IC_CON__RX1_FIFO_FULL_HLD_CTRL_MASK: c_uint = 0x00000200L;
// CKSVII2C1_IC_TAR
pub const CKSVII2C1_IC_TAR__IC1_TAR__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_TAR__GC1_OR_START__SHIFT: c_uint = 0xa;
pub const CKSVII2C1_IC_TAR__SPECIAL1__SHIFT: c_uint = 0xb;
pub const CKSVII2C1_IC_TAR__IC1_10BITADDR_MASTER__SHIFT: c_uint = 0xc;
pub const CKSVII2C1_IC_TAR__IC1_TAR_MASK: c_uint = 0x000003FFL;
pub const CKSVII2C1_IC_TAR__GC1_OR_START_MASK: c_uint = 0x00000400L;
pub const CKSVII2C1_IC_TAR__SPECIAL1_MASK: c_uint = 0x00000800L;
pub const CKSVII2C1_IC_TAR__IC1_10BITADDR_MASTER_MASK: c_uint = 0x00001000L;
// CKSVII2C1_IC_SAR
pub const CKSVII2C1_IC_SAR__IC1_SAR__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_SAR__IC1_SAR_MASK: c_uint = 0x000003FFL;
// CKSVII2C1_IC_HS_MADDR
pub const CKSVII2C1_IC_HS_MADDR__IC1_HS_MADDR__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_HS_MADDR__IC1_HS_MADDR_MASK: c_uint = 0x00000007L;
// CKSVII2C1_IC_DATA_CMD
pub const CKSVII2C1_IC_DATA_CMD__DAT1__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_DATA_CMD__CMD1__SHIFT: c_uint = 0x8;
pub const CKSVII2C1_IC_DATA_CMD__STOP1__SHIFT: c_uint = 0x9;
pub const CKSVII2C1_IC_DATA_CMD__RESTART1__SHIFT: c_uint = 0xa;
pub const CKSVII2C1_IC_DATA_CMD__DAT1_MASK: c_uint = 0x000000FFL;
pub const CKSVII2C1_IC_DATA_CMD__CMD1_MASK: c_uint = 0x00000100L;
pub const CKSVII2C1_IC_DATA_CMD__STOP1_MASK: c_uint = 0x00000200L;
pub const CKSVII2C1_IC_DATA_CMD__RESTART1_MASK: c_uint = 0x00000400L;
// CKSVII2C1_IC_SS_SCL_HCNT
pub const CKSVII2C1_IC_SS_SCL_HCNT__IC1_SS_SCL_HCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_SS_SCL_HCNT__IC1_SS_SCL_HCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C1_IC_SS_SCL_LCNT
pub const CKSVII2C1_IC_SS_SCL_LCNT__IC1_SS_SCL_LCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_SS_SCL_LCNT__IC1_SS_SCL_LCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C1_IC_FS_SCL_HCNT
pub const CKSVII2C1_IC_FS_SCL_HCNT__IC1_FS_SCL_HCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_FS_SCL_HCNT__IC1_FS_SCL_HCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C1_IC_FS_SCL_LCNT
pub const CKSVII2C1_IC_FS_SCL_LCNT__IC1_FS_SCL_LCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_FS_SCL_LCNT__IC1_FS_SCL_LCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C1_IC_HS_SCL_HCNT
pub const CKSVII2C1_IC_HS_SCL_HCNT__IC1_HS_SCL_HCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_HS_SCL_HCNT__IC1_HS_SCL_HCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C1_IC_HS_SCL_LCNT
pub const CKSVII2C1_IC_HS_SCL_LCNT__IC1_HS_SCL_LCNT__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_HS_SCL_LCNT__IC1_HS_SCL_LCNT_MASK: c_uint = 0x0000FFFFL;
// CKSVII2C1_IC_INTR_STAT
pub const CKSVII2C1_IC_INTR_STAT__R1_RX_UNDER__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_INTR_STAT__R1_RX_OVER__SHIFT: c_uint = 0x1;
pub const CKSVII2C1_IC_INTR_STAT__R1_RX_FULL__SHIFT: c_uint = 0x2;
pub const CKSVII2C1_IC_INTR_STAT__R1_TX_OVER__SHIFT: c_uint = 0x3;
pub const CKSVII2C1_IC_INTR_STAT__R1_TX_EMPTY__SHIFT: c_uint = 0x4;
pub const CKSVII2C1_IC_INTR_STAT__R1_RD_REQ__SHIFT: c_uint = 0x5;
pub const CKSVII2C1_IC_INTR_STAT__R1_TX_ABRT__SHIFT: c_uint = 0x6;
pub const CKSVII2C1_IC_INTR_STAT__R1_RX_DONE__SHIFT: c_uint = 0x7;
pub const CKSVII2C1_IC_INTR_STAT__R1_ACTIVITY__SHIFT: c_uint = 0x8;
pub const CKSVII2C1_IC_INTR_STAT__R1_STOP_DET__SHIFT: c_uint = 0x9;
pub const CKSVII2C1_IC_INTR_STAT__R1_START_DET__SHIFT: c_uint = 0xa;
pub const CKSVII2C1_IC_INTR_STAT__R1_GEN_CALL__SHIFT: c_uint = 0xb;
pub const CKSVII2C1_IC_INTR_STAT__R1_RESTART_DET__SHIFT: c_uint = 0xc;
pub const CKSVII2C1_IC_INTR_STAT__R1_MST_ON_HOLD__SHIFT: c_uint = 0xd;
pub const CKSVII2C1_IC_INTR_STAT__R1_RX_UNDER_MASK: c_uint = 0x00000001L;
pub const CKSVII2C1_IC_INTR_STAT__R1_RX_OVER_MASK: c_uint = 0x00000002L;
pub const CKSVII2C1_IC_INTR_STAT__R1_RX_FULL_MASK: c_uint = 0x00000004L;
pub const CKSVII2C1_IC_INTR_STAT__R1_TX_OVER_MASK: c_uint = 0x00000008L;
pub const CKSVII2C1_IC_INTR_STAT__R1_TX_EMPTY_MASK: c_uint = 0x00000010L;
pub const CKSVII2C1_IC_INTR_STAT__R1_RD_REQ_MASK: c_uint = 0x00000020L;
pub const CKSVII2C1_IC_INTR_STAT__R1_TX_ABRT_MASK: c_uint = 0x00000040L;
pub const CKSVII2C1_IC_INTR_STAT__R1_RX_DONE_MASK: c_uint = 0x00000080L;
pub const CKSVII2C1_IC_INTR_STAT__R1_ACTIVITY_MASK: c_uint = 0x00000100L;
pub const CKSVII2C1_IC_INTR_STAT__R1_STOP_DET_MASK: c_uint = 0x00000200L;
pub const CKSVII2C1_IC_INTR_STAT__R1_START_DET_MASK: c_uint = 0x00000400L;
pub const CKSVII2C1_IC_INTR_STAT__R1_GEN_CALL_MASK: c_uint = 0x00000800L;
pub const CKSVII2C1_IC_INTR_STAT__R1_RESTART_DET_MASK: c_uint = 0x00001000L;
pub const CKSVII2C1_IC_INTR_STAT__R1_MST_ON_HOLD_MASK: c_uint = 0x00002000L;
// CKSVII2C1_IC_INTR_MASK
pub const CKSVII2C1_IC_INTR_MASK__M1_RX_UNDER__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_INTR_MASK__M1_RX_OVER__SHIFT: c_uint = 0x1;
pub const CKSVII2C1_IC_INTR_MASK__M1_RX_FULL__SHIFT: c_uint = 0x2;
pub const CKSVII2C1_IC_INTR_MASK__M1_TX_OVER__SHIFT: c_uint = 0x3;
pub const CKSVII2C1_IC_INTR_MASK__M1_TX_EMPTY__SHIFT: c_uint = 0x4;
pub const CKSVII2C1_IC_INTR_MASK__M1_RD_REQ__SHIFT: c_uint = 0x5;
pub const CKSVII2C1_IC_INTR_MASK__M1_TX_ABRT__SHIFT: c_uint = 0x6;
pub const CKSVII2C1_IC_INTR_MASK__M1_RX_DONE__SHIFT: c_uint = 0x7;
pub const CKSVII2C1_IC_INTR_MASK__M1_ACTIVITY__SHIFT: c_uint = 0x8;
pub const CKSVII2C1_IC_INTR_MASK__M1_STOP_DET__SHIFT: c_uint = 0x9;
pub const CKSVII2C1_IC_INTR_MASK__M1_START_DET__SHIFT: c_uint = 0xa;
pub const CKSVII2C1_IC_INTR_MASK__M1_GEN_CALL__SHIFT: c_uint = 0xb;
pub const CKSVII2C1_IC_INTR_MASK__M1_RESTART_DET__SHIFT: c_uint = 0xc;
pub const CKSVII2C1_IC_INTR_MASK__M1_MST_ON_HOLD__SHIFT: c_uint = 0xd;
pub const CKSVII2C1_IC_INTR_MASK__M1_RX_UNDER_MASK: c_uint = 0x00000001L;
pub const CKSVII2C1_IC_INTR_MASK__M1_RX_OVER_MASK: c_uint = 0x00000002L;
pub const CKSVII2C1_IC_INTR_MASK__M1_RX_FULL_MASK: c_uint = 0x00000004L;
pub const CKSVII2C1_IC_INTR_MASK__M1_TX_OVER_MASK: c_uint = 0x00000008L;
pub const CKSVII2C1_IC_INTR_MASK__M1_TX_EMPTY_MASK: c_uint = 0x00000010L;
pub const CKSVII2C1_IC_INTR_MASK__M1_RD_REQ_MASK: c_uint = 0x00000020L;
pub const CKSVII2C1_IC_INTR_MASK__M1_TX_ABRT_MASK: c_uint = 0x00000040L;
pub const CKSVII2C1_IC_INTR_MASK__M1_RX_DONE_MASK: c_uint = 0x00000080L;
pub const CKSVII2C1_IC_INTR_MASK__M1_ACTIVITY_MASK: c_uint = 0x00000100L;
pub const CKSVII2C1_IC_INTR_MASK__M1_STOP_DET_MASK: c_uint = 0x00000200L;
pub const CKSVII2C1_IC_INTR_MASK__M1_START_DET_MASK: c_uint = 0x00000400L;
pub const CKSVII2C1_IC_INTR_MASK__M1_GEN_CALL_MASK: c_uint = 0x00000800L;
pub const CKSVII2C1_IC_INTR_MASK__M1_RESTART_DET_MASK: c_uint = 0x00001000L;
pub const CKSVII2C1_IC_INTR_MASK__M1_MST_ON_HOLD_MASK: c_uint = 0x00002000L;
// CKSVII2C1_IC_RAW_INTR_STAT
// CKSVII2C1_IC_RX_TL
// CKSVII2C1_IC_TX_TL
// CKSVII2C1_IC_CLR_INTR
// CKSVII2C1_IC_CLR_RX_UNDER
// CKSVII2C1_IC_CLR_RX_OVER
// CKSVII2C1_IC_CLR_TX_OVER
// CKSVII2C1_IC_CLR_RD_REQ
// CKSVII2C1_IC_CLR_TX_ABRT
// CKSVII2C1_IC_CLR_RX_DONE
// CKSVII2C1_IC_CLR_ACTIVITY
// CKSVII2C1_IC_CLR_STOP_DET
// CKSVII2C1_IC_CLR_START_DET
// CKSVII2C1_IC_CLR_GEN_CALL
// CKSVII2C1_IC_ENABLE
pub const CKSVII2C1_IC_ENABLE__ENABLE1__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_ENABLE__ABORT1__SHIFT: c_uint = 0x1;
pub const CKSVII2C1_IC_ENABLE__ENABLE1_MASK: c_uint = 0x00000001L;
pub const CKSVII2C1_IC_ENABLE__ABORT1_MASK: c_uint = 0x00000002L;
// CKSVII2C1_IC_STATUS
pub const CKSVII2C1_IC_STATUS__ACTIVITY1__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_STATUS__TFNF1__SHIFT: c_uint = 0x1;
pub const CKSVII2C1_IC_STATUS__TFE1__SHIFT: c_uint = 0x2;
pub const CKSVII2C1_IC_STATUS__RFNE1__SHIFT: c_uint = 0x3;
pub const CKSVII2C1_IC_STATUS__RFF1__SHIFT: c_uint = 0x4;
pub const CKSVII2C1_IC_STATUS__MST1_ACTIVITY__SHIFT: c_uint = 0x5;
pub const CKSVII2C1_IC_STATUS__SLV1_ACTIVITY__SHIFT: c_uint = 0x6;
pub const CKSVII2C1_IC_STATUS__ACTIVITY1_MASK: c_uint = 0x00000001L;
pub const CKSVII2C1_IC_STATUS__TFNF1_MASK: c_uint = 0x00000002L;
pub const CKSVII2C1_IC_STATUS__TFE1_MASK: c_uint = 0x00000004L;
pub const CKSVII2C1_IC_STATUS__RFNE1_MASK: c_uint = 0x00000008L;
pub const CKSVII2C1_IC_STATUS__RFF1_MASK: c_uint = 0x00000010L;
pub const CKSVII2C1_IC_STATUS__MST1_ACTIVITY_MASK: c_uint = 0x00000020L;
pub const CKSVII2C1_IC_STATUS__SLV1_ACTIVITY_MASK: c_uint = 0x00000040L;
// CKSVII2C1_IC_TXFLR
// CKSVII2C1_IC_RXFLR
// CKSVII2C1_IC_SDA_HOLD
pub const CKSVII2C1_IC_SDA_HOLD__IC1_SDA_HOLD__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_SDA_HOLD__IC1_SDA_HOLD_MASK: c_uint = 0x00FFFFFFL;
// CKSVII2C1_IC_TX_ABRT_SOURCE
// CKSVII2C1_IC_SLV_DATA_NACK_ONLY
// CKSVII2C1_IC_DMA_CR
// CKSVII2C1_IC_DMA_TDLR
// CKSVII2C1_IC_DMA_RDLR
// CKSVII2C1_IC_SDA_SETUP
pub const CKSVII2C1_IC_SDA_SETUP__SDA1_SETUP__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_SDA_SETUP__SDA1_SETUP_MASK: c_uint = 0x000000FFL;
// CKSVII2C1_IC_ACK_GENERAL_CALL
pub const CKSVII2C1_IC_ACK_GENERAL_CALL__ACK1_GENERAL_CALL__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_ACK_GENERAL_CALL__ACK1_GENERAL_CALL_MASK: c_uint = 0x00000001L;
// CKSVII2C1_IC_ENABLE_STATUS
pub const CKSVII2C1_IC_ENABLE_STATUS__IC1_EN__SHIFT: c_uint = 0x0;
pub const CKSVII2C1_IC_ENABLE_STATUS__SLV1_RX_ABORTED__SHIFT: c_uint = 0x1;
pub const CKSVII2C1_IC_ENABLE_STATUS__SLV1_FIFO_FILLED_AND_FLUSHED__SHIFT: c_uint = 0x2;
pub const CKSVII2C1_IC_ENABLE_STATUS__IC1_EN_MASK: c_uint = 0x00000001L;
pub const CKSVII2C1_IC_ENABLE_STATUS__SLV1_RX_ABORTED_MASK: c_uint = 0x00000002L;
pub const CKSVII2C1_IC_ENABLE_STATUS__SLV1_FIFO_FILLED_AND_FLUSHED_MASK: c_uint = 0x00000004L;
// SMUIO_MP_RESET_INTR
pub const SMUIO_MP_RESET_INTR__SMUIO_MP_RESET_INTR__SHIFT: c_uint = 0x0;
pub const SMUIO_MP_RESET_INTR__SMUIO_MP_RESET_INTR_MASK: c_uint = 0x00000001L;
// SMUIO_SOC_HALT
pub const SMUIO_SOC_HALT__WDT_FORCE_PWROK_EN__SHIFT: c_uint = 0x2;
pub const SMUIO_SOC_HALT__WDT_FORCE_RESETn_EN__SHIFT: c_uint = 0x3;
pub const SMUIO_SOC_HALT__WDT_FORCE_PWROK_EN_MASK: c_uint = 0x00000004L;
pub const SMUIO_SOC_HALT__WDT_FORCE_RESETn_EN_MASK: c_uint = 0x00000008L;
// SMUIO_PWRMGT
pub const SMUIO_PWRMGT__i2c_clk_gate_en__SHIFT: c_uint = 0x0;
pub const SMUIO_PWRMGT__i2c1_clk_gate_en__SHIFT: c_uint = 0x4;
pub const SMUIO_PWRMGT__i2c_clk_gate_en_MASK: c_uint = 0x00000001L;
pub const SMUIO_PWRMGT__i2c1_clk_gate_en_MASK: c_uint = 0x00000010L;
// ROM_CNTL
pub const ROM_CNTL__CLOCK_GATING_EN__SHIFT: c_uint = 0x0;
pub const ROM_CNTL__SPI_TIMING_RELAX__SHIFT: c_uint = 0x14;
pub const ROM_CNTL__SPI_TIMING_RELAX_OVERRIDE__SHIFT: c_uint = 0x15;
pub const ROM_CNTL__SPI_FAST_MODE__SHIFT: c_uint = 0x16;
pub const ROM_CNTL__SPI_FAST_MODE_OVERRIDE__SHIFT: c_uint = 0x17;
pub const ROM_CNTL__SCK_PRESCALE_REFCLK__SHIFT: c_uint = 0x18;
pub const ROM_CNTL__SCK_PRESCALE_REFCLK_OVERRIDE__SHIFT: c_uint = 0x1c;
pub const ROM_CNTL__CLOCK_GATING_EN_MASK: c_uint = 0x00000001L;
pub const ROM_CNTL__SPI_TIMING_RELAX_MASK: c_uint = 0x00100000L;
pub const ROM_CNTL__SPI_TIMING_RELAX_OVERRIDE_MASK: c_uint = 0x00200000L;
pub const ROM_CNTL__SPI_FAST_MODE_MASK: c_uint = 0x00400000L;
pub const ROM_CNTL__SPI_FAST_MODE_OVERRIDE_MASK: c_uint = 0x00800000L;
pub const ROM_CNTL__SCK_PRESCALE_REFCLK_MASK: c_uint = 0x0F000000L;
pub const ROM_CNTL__SCK_PRESCALE_REFCLK_OVERRIDE_MASK: c_uint = 0x10000000L;
// PAGE_MIRROR_CNTL
pub const PAGE_MIRROR_CNTL__PAGE_MIRROR_BASE_ADDR__SHIFT: c_uint = 0x0;
pub const PAGE_MIRROR_CNTL__PAGE_MIRROR_INVALIDATE__SHIFT: c_uint = 0x18;
pub const PAGE_MIRROR_CNTL__PAGE_MIRROR_ENABLE__SHIFT: c_uint = 0x19;
pub const PAGE_MIRROR_CNTL__PAGE_MIRROR_USAGE__SHIFT: c_uint = 0x1a;
pub const PAGE_MIRROR_CNTL__PAGE_MIRROR_BASE_ADDR_MASK: c_uint = 0x00FFFFFFL;
pub const PAGE_MIRROR_CNTL__PAGE_MIRROR_INVALIDATE_MASK: c_uint = 0x01000000L;
pub const PAGE_MIRROR_CNTL__PAGE_MIRROR_ENABLE_MASK: c_uint = 0x02000000L;
pub const PAGE_MIRROR_CNTL__PAGE_MIRROR_USAGE_MASK: c_uint = 0x0C000000L;
// ROM_STATUS
pub const ROM_STATUS__ROM_BUSY__SHIFT: c_uint = 0x0;
pub const ROM_STATUS__ROM_BUSY_MASK: c_uint = 0x00000001L;
// CGTT_ROM_CLK_CTRL0
pub const CGTT_ROM_CLK_CTRL0__ON_DELAY__SHIFT: c_uint = 0x0;
pub const CGTT_ROM_CLK_CTRL0__OFF_HYSTERESIS__SHIFT: c_uint = 0x4;
pub const CGTT_ROM_CLK_CTRL0__SOFT_OVERRIDE1__SHIFT: c_uint = 0x1e;
pub const CGTT_ROM_CLK_CTRL0__SOFT_OVERRIDE0__SHIFT: c_uint = 0x1f;
pub const CGTT_ROM_CLK_CTRL0__ON_DELAY_MASK: c_uint = 0x0000000FL;
pub const CGTT_ROM_CLK_CTRL0__OFF_HYSTERESIS_MASK: c_uint = 0x00000FF0L;
pub const CGTT_ROM_CLK_CTRL0__SOFT_OVERRIDE1_MASK: c_uint = 0x40000000L;
pub const CGTT_ROM_CLK_CTRL0__SOFT_OVERRIDE0_MASK: c_uint = 0x80000000L;
// ROM_INDEX
pub const ROM_INDEX__ROM_INDEX__SHIFT: c_uint = 0x0;
pub const ROM_INDEX__ROM_INDEX_MASK: c_uint = 0x00FFFFFFL;
// ROM_DATA
pub const ROM_DATA__ROM_DATA__SHIFT: c_uint = 0x0;
pub const ROM_DATA__ROM_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_START
pub const ROM_START__ROM_START__SHIFT: c_uint = 0x0;
pub const ROM_START__ROM_START_MASK: c_uint = 0x00FFFFFFL;
// ROM_SW_CNTL
pub const ROM_SW_CNTL__DATA_SIZE__SHIFT: c_uint = 0x0;
pub const ROM_SW_CNTL__COMMAND_SIZE__SHIFT: c_uint = 0x10;
pub const ROM_SW_CNTL__ROM_SW_RETURN_DATA_ENABLE__SHIFT: c_uint = 0x12;
pub const ROM_SW_CNTL__DATA_SIZE_MASK: c_uint = 0x0000FFFFL;
pub const ROM_SW_CNTL__COMMAND_SIZE_MASK: c_uint = 0x00030000L;
pub const ROM_SW_CNTL__ROM_SW_RETURN_DATA_ENABLE_MASK: c_uint = 0x00040000L;
// ROM_SW_STATUS
pub const ROM_SW_STATUS__ROM_SW_DONE__SHIFT: c_uint = 0x0;
pub const ROM_SW_STATUS__ROM_SW_DONE_MASK: c_uint = 0x00000001L;
// ROM_SW_COMMAND
pub const ROM_SW_COMMAND__ROM_SW_INSTRUCTION__SHIFT: c_uint = 0x0;
pub const ROM_SW_COMMAND__ROM_SW_ADDRESS__SHIFT: c_uint = 0x8;
pub const ROM_SW_COMMAND__ROM_SW_INSTRUCTION_MASK: c_uint = 0x000000FFL;
pub const ROM_SW_COMMAND__ROM_SW_ADDRESS_MASK: c_uint = 0xFFFFFF00L;
// ROM_SW_DATA_1
pub const ROM_SW_DATA_1__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_1__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_2
pub const ROM_SW_DATA_2__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_2__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_3
pub const ROM_SW_DATA_3__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_3__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_4
pub const ROM_SW_DATA_4__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_4__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_5
pub const ROM_SW_DATA_5__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_5__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_6
pub const ROM_SW_DATA_6__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_6__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_7
pub const ROM_SW_DATA_7__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_7__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_8
pub const ROM_SW_DATA_8__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_8__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_9
pub const ROM_SW_DATA_9__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_9__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_10
pub const ROM_SW_DATA_10__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_10__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_11
pub const ROM_SW_DATA_11__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_11__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_12
pub const ROM_SW_DATA_12__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_12__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_13
pub const ROM_SW_DATA_13__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_13__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_14
pub const ROM_SW_DATA_14__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_14__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_15
pub const ROM_SW_DATA_15__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_15__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_16
pub const ROM_SW_DATA_16__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_16__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_17
pub const ROM_SW_DATA_17__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_17__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_18
pub const ROM_SW_DATA_18__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_18__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_19
pub const ROM_SW_DATA_19__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_19__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_20
pub const ROM_SW_DATA_20__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_20__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_21
pub const ROM_SW_DATA_21__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_21__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_22
pub const ROM_SW_DATA_22__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_22__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_23
pub const ROM_SW_DATA_23__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_23__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_24
pub const ROM_SW_DATA_24__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_24__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_25
pub const ROM_SW_DATA_25__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_25__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_26
pub const ROM_SW_DATA_26__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_26__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_27
pub const ROM_SW_DATA_27__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_27__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_28
pub const ROM_SW_DATA_28__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_28__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_29
pub const ROM_SW_DATA_29__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_29__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_30
pub const ROM_SW_DATA_30__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_30__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_31
pub const ROM_SW_DATA_31__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_31__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_32
pub const ROM_SW_DATA_32__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_32__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_33
pub const ROM_SW_DATA_33__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_33__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_34
pub const ROM_SW_DATA_34__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_34__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_35
pub const ROM_SW_DATA_35__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_35__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_36
pub const ROM_SW_DATA_36__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_36__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_37
pub const ROM_SW_DATA_37__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_37__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_38
pub const ROM_SW_DATA_38__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_38__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_39
pub const ROM_SW_DATA_39__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_39__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_40
pub const ROM_SW_DATA_40__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_40__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_41
pub const ROM_SW_DATA_41__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_41__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_42
pub const ROM_SW_DATA_42__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_42__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_43
pub const ROM_SW_DATA_43__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_43__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_44
pub const ROM_SW_DATA_44__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_44__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_45
pub const ROM_SW_DATA_45__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_45__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_46
pub const ROM_SW_DATA_46__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_46__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_47
pub const ROM_SW_DATA_47__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_47__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_48
pub const ROM_SW_DATA_48__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_48__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_49
pub const ROM_SW_DATA_49__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_49__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_50
pub const ROM_SW_DATA_50__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_50__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_51
pub const ROM_SW_DATA_51__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_51__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_52
pub const ROM_SW_DATA_52__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_52__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_53
pub const ROM_SW_DATA_53__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_53__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_54
pub const ROM_SW_DATA_54__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_54__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_55
pub const ROM_SW_DATA_55__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_55__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_56
pub const ROM_SW_DATA_56__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_56__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_57
pub const ROM_SW_DATA_57__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_57__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_58
pub const ROM_SW_DATA_58__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_58__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_59
pub const ROM_SW_DATA_59__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_59__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_60
pub const ROM_SW_DATA_60__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_60__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_61
pub const ROM_SW_DATA_61__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_61__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_62
pub const ROM_SW_DATA_62__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_62__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_63
pub const ROM_SW_DATA_63__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_63__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// ROM_SW_DATA_64
pub const ROM_SW_DATA_64__ROM_SW_DATA__SHIFT: c_uint = 0x0;
pub const ROM_SW_DATA_64__ROM_SW_DATA_MASK: c_uint = 0xFFFFFFFFL;
// SMU_GPIOPAD_SW_INT_STAT
pub const SMU_GPIOPAD_SW_INT_STAT__SW_INT_STAT__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_SW_INT_STAT__SW_INT_STAT_MASK: c_uint = 0x00000001L;
// SMU_GPIOPAD_MASK
pub const SMU_GPIOPAD_MASK__GPIO_MASK__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_MASK__GPIO_MASK_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_A
pub const SMU_GPIOPAD_A__GPIO_A__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_A__GPIO_A_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_TXIMPSEL
pub const SMU_GPIOPAD_TXIMPSEL__GPIO_TXIMPSEL__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_TXIMPSEL__GPIO_TXIMPSEL_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_EN
pub const SMU_GPIOPAD_EN__GPIO_EN__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_EN__GPIO_EN_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_Y
pub const SMU_GPIOPAD_Y__GPIO_Y__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_Y__GPIO_Y_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_RXEN
pub const SMU_GPIOPAD_RXEN__GPIO_RXEN__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_RXEN__GPIO_RXEN_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_RCVR_SEL0
pub const SMU_GPIOPAD_RCVR_SEL0__GPIO_RCVR_SEL0__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_RCVR_SEL0__GPIO_RCVR_SEL0_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_RCVR_SEL1
pub const SMU_GPIOPAD_RCVR_SEL1__GPIO_RCVR_SEL1__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_RCVR_SEL1__GPIO_RCVR_SEL1_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_PU_EN
pub const SMU_GPIOPAD_PU_EN__GPIO_PU_EN__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_PU_EN__GPIO_PU_EN_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_PD_EN
pub const SMU_GPIOPAD_PD_EN__GPIO_PD_EN__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_PD_EN__GPIO_PD_EN_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_PINSTRAPS
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_0__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_1__SHIFT: c_uint = 0x1;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_2__SHIFT: c_uint = 0x2;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_3__SHIFT: c_uint = 0x3;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_4__SHIFT: c_uint = 0x4;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_5__SHIFT: c_uint = 0x5;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_6__SHIFT: c_uint = 0x6;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_7__SHIFT: c_uint = 0x7;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_8__SHIFT: c_uint = 0x8;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_9__SHIFT: c_uint = 0x9;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_10__SHIFT: c_uint = 0xa;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_11__SHIFT: c_uint = 0xb;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_12__SHIFT: c_uint = 0xc;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_13__SHIFT: c_uint = 0xd;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_14__SHIFT: c_uint = 0xe;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_15__SHIFT: c_uint = 0xf;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_16__SHIFT: c_uint = 0x10;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_17__SHIFT: c_uint = 0x11;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_18__SHIFT: c_uint = 0x12;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_19__SHIFT: c_uint = 0x13;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_20__SHIFT: c_uint = 0x14;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_21__SHIFT: c_uint = 0x15;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_22__SHIFT: c_uint = 0x16;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_23__SHIFT: c_uint = 0x17;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_24__SHIFT: c_uint = 0x18;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_25__SHIFT: c_uint = 0x19;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_26__SHIFT: c_uint = 0x1a;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_27__SHIFT: c_uint = 0x1b;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_28__SHIFT: c_uint = 0x1c;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_29__SHIFT: c_uint = 0x1d;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_30__SHIFT: c_uint = 0x1e;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_0_MASK: c_uint = 0x00000001L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_1_MASK: c_uint = 0x00000002L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_2_MASK: c_uint = 0x00000004L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_3_MASK: c_uint = 0x00000008L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_4_MASK: c_uint = 0x00000010L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_5_MASK: c_uint = 0x00000020L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_6_MASK: c_uint = 0x00000040L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_7_MASK: c_uint = 0x00000080L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_8_MASK: c_uint = 0x00000100L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_9_MASK: c_uint = 0x00000200L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_10_MASK: c_uint = 0x00000400L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_11_MASK: c_uint = 0x00000800L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_12_MASK: c_uint = 0x00001000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_13_MASK: c_uint = 0x00002000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_14_MASK: c_uint = 0x00004000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_15_MASK: c_uint = 0x00008000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_16_MASK: c_uint = 0x00010000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_17_MASK: c_uint = 0x00020000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_18_MASK: c_uint = 0x00040000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_19_MASK: c_uint = 0x00080000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_20_MASK: c_uint = 0x00100000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_21_MASK: c_uint = 0x00200000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_22_MASK: c_uint = 0x00400000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_23_MASK: c_uint = 0x00800000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_24_MASK: c_uint = 0x01000000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_25_MASK: c_uint = 0x02000000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_26_MASK: c_uint = 0x04000000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_27_MASK: c_uint = 0x08000000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_28_MASK: c_uint = 0x10000000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_29_MASK: c_uint = 0x20000000L;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_30_MASK: c_uint = 0x40000000L;
// DFT_PINSTRAPS
pub const DFT_PINSTRAPS__DFT_PINSTRAPS__SHIFT: c_uint = 0x0;
pub const DFT_PINSTRAPS__DFT_PINSTRAPS_MASK: c_uint = 0x000000FFL;
// SMU_GPIOPAD_INT_STAT_EN
pub const SMU_GPIOPAD_INT_STAT_EN__GPIO_INT_STAT_EN__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_INT_STAT_EN__SW_INITIATED_INT_STAT_EN__SHIFT: c_uint = 0x1f;
pub const SMU_GPIOPAD_INT_STAT_EN__GPIO_INT_STAT_EN_MASK: c_uint = 0x1FFFFFFFL;
pub const SMU_GPIOPAD_INT_STAT_EN__SW_INITIATED_INT_STAT_EN_MASK: c_uint = 0x80000000L;
// SMU_GPIOPAD_INT_STAT
pub const SMU_GPIOPAD_INT_STAT__GPIO_INT_STAT__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_INT_STAT__SW_INITIATED_INT_STAT__SHIFT: c_uint = 0x1f;
pub const SMU_GPIOPAD_INT_STAT__GPIO_INT_STAT_MASK: c_uint = 0x1FFFFFFFL;
pub const SMU_GPIOPAD_INT_STAT__SW_INITIATED_INT_STAT_MASK: c_uint = 0x80000000L;
// SMU_GPIOPAD_INT_STAT_AK
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_0__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_1__SHIFT: c_uint = 0x1;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_2__SHIFT: c_uint = 0x2;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_3__SHIFT: c_uint = 0x3;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_4__SHIFT: c_uint = 0x4;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_5__SHIFT: c_uint = 0x5;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_6__SHIFT: c_uint = 0x6;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_7__SHIFT: c_uint = 0x7;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_8__SHIFT: c_uint = 0x8;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_9__SHIFT: c_uint = 0x9;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_10__SHIFT: c_uint = 0xa;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_11__SHIFT: c_uint = 0xb;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_12__SHIFT: c_uint = 0xc;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_13__SHIFT: c_uint = 0xd;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_14__SHIFT: c_uint = 0xe;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_15__SHIFT: c_uint = 0xf;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_16__SHIFT: c_uint = 0x10;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_17__SHIFT: c_uint = 0x11;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_18__SHIFT: c_uint = 0x12;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_19__SHIFT: c_uint = 0x13;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_20__SHIFT: c_uint = 0x14;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_21__SHIFT: c_uint = 0x15;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_22__SHIFT: c_uint = 0x16;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_23__SHIFT: c_uint = 0x17;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_24__SHIFT: c_uint = 0x18;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_25__SHIFT: c_uint = 0x19;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_26__SHIFT: c_uint = 0x1a;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_27__SHIFT: c_uint = 0x1b;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_28__SHIFT: c_uint = 0x1c;
pub const SMU_GPIOPAD_INT_STAT_AK__SW_INITIATED_INT_STAT_AK__SHIFT: c_uint = 0x1f;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_0_MASK: c_uint = 0x00000001L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_1_MASK: c_uint = 0x00000002L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_2_MASK: c_uint = 0x00000004L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_3_MASK: c_uint = 0x00000008L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_4_MASK: c_uint = 0x00000010L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_5_MASK: c_uint = 0x00000020L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_6_MASK: c_uint = 0x00000040L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_7_MASK: c_uint = 0x00000080L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_8_MASK: c_uint = 0x00000100L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_9_MASK: c_uint = 0x00000200L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_10_MASK: c_uint = 0x00000400L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_11_MASK: c_uint = 0x00000800L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_12_MASK: c_uint = 0x00001000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_13_MASK: c_uint = 0x00002000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_14_MASK: c_uint = 0x00004000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_15_MASK: c_uint = 0x00008000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_16_MASK: c_uint = 0x00010000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_17_MASK: c_uint = 0x00020000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_18_MASK: c_uint = 0x00040000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_19_MASK: c_uint = 0x00080000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_20_MASK: c_uint = 0x00100000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_21_MASK: c_uint = 0x00200000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_22_MASK: c_uint = 0x00400000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_23_MASK: c_uint = 0x00800000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_24_MASK: c_uint = 0x01000000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_25_MASK: c_uint = 0x02000000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_26_MASK: c_uint = 0x04000000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_27_MASK: c_uint = 0x08000000L;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_28_MASK: c_uint = 0x10000000L;
pub const SMU_GPIOPAD_INT_STAT_AK__SW_INITIATED_INT_STAT_AK_MASK: c_uint = 0x80000000L;
// SMU_GPIOPAD_INT_EN
pub const SMU_GPIOPAD_INT_EN__GPIO_INT_EN__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_INT_EN__SW_INITIATED_INT_EN__SHIFT: c_uint = 0x1f;
pub const SMU_GPIOPAD_INT_EN__GPIO_INT_EN_MASK: c_uint = 0x1FFFFFFFL;
pub const SMU_GPIOPAD_INT_EN__SW_INITIATED_INT_EN_MASK: c_uint = 0x80000000L;
// SMU_GPIOPAD_INT_TYPE
pub const SMU_GPIOPAD_INT_TYPE__GPIO_INT_TYPE__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_INT_TYPE__SW_INITIATED_INT_TYPE__SHIFT: c_uint = 0x1f;
pub const SMU_GPIOPAD_INT_TYPE__GPIO_INT_TYPE_MASK: c_uint = 0x1FFFFFFFL;
pub const SMU_GPIOPAD_INT_TYPE__SW_INITIATED_INT_TYPE_MASK: c_uint = 0x80000000L;
// SMU_GPIOPAD_INT_POLARITY
pub const SMU_GPIOPAD_INT_POLARITY__GPIO_INT_POLARITY__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_INT_POLARITY__SW_INITIATED_INT_POLARITY__SHIFT: c_uint = 0x1f;
pub const SMU_GPIOPAD_INT_POLARITY__GPIO_INT_POLARITY_MASK: c_uint = 0x1FFFFFFFL;
pub const SMU_GPIOPAD_INT_POLARITY__SW_INITIATED_INT_POLARITY_MASK: c_uint = 0x80000000L;
// ROM_CC_BIF_PINSTRAP
pub const ROM_CC_BIF_PINSTRAP__BIOS_ROM_EN__SHIFT: c_uint = 0x0;
pub const ROM_CC_BIF_PINSTRAP__BIF_MEM_AP_SIZE__SHIFT: c_uint = 0x1;
pub const ROM_CC_BIF_PINSTRAP__ROM_CONFIG__SHIFT: c_uint = 0x4;
pub const ROM_CC_BIF_PINSTRAP__BIF_GEN3_DIS_A__SHIFT: c_uint = 0x7;
pub const ROM_CC_BIF_PINSTRAP__BIF_CLK_PM_EN__SHIFT: c_uint = 0x8;
pub const ROM_CC_BIF_PINSTRAP__BIF_VGA_DIS__SHIFT: c_uint = 0x9;
pub const ROM_CC_BIF_PINSTRAP__BIF_LC_TX_SWING__SHIFT: c_uint = 0xa;
pub const ROM_CC_BIF_PINSTRAP__BIOS_ROM_EN_MASK: c_uint = 0x00000001L;
pub const ROM_CC_BIF_PINSTRAP__BIF_MEM_AP_SIZE_MASK: c_uint = 0x0000000EL;
pub const ROM_CC_BIF_PINSTRAP__ROM_CONFIG_MASK: c_uint = 0x00000070L;
pub const ROM_CC_BIF_PINSTRAP__BIF_GEN3_DIS_A_MASK: c_uint = 0x00000080L;
pub const ROM_CC_BIF_PINSTRAP__BIF_CLK_PM_EN_MASK: c_uint = 0x00000100L;
pub const ROM_CC_BIF_PINSTRAP__BIF_VGA_DIS_MASK: c_uint = 0x00000200L;
pub const ROM_CC_BIF_PINSTRAP__BIF_LC_TX_SWING_MASK: c_uint = 0x00000400L;
// IO_SMUIO_PINSTRAP
pub const IO_SMUIO_PINSTRAP__AUD_PORT_CONN__SHIFT: c_uint = 0x0;
pub const IO_SMUIO_PINSTRAP__AUD__SHIFT: c_uint = 0x3;
pub const IO_SMUIO_PINSTRAP__BOARD_CONFIG__SHIFT: c_uint = 0x5;
pub const IO_SMUIO_PINSTRAP__SMBUS_ADDR__SHIFT: c_uint = 0x8;
pub const IO_SMUIO_PINSTRAP__AUD_PORT_CONN_MASK: c_uint = 0x00000007L;
pub const IO_SMUIO_PINSTRAP__AUD_MASK: c_uint = 0x00000018L;
pub const IO_SMUIO_PINSTRAP__BOARD_CONFIG_MASK: c_uint = 0x000000E0L;
pub const IO_SMUIO_PINSTRAP__SMBUS_ADDR_MASK: c_uint = 0x00000100L;
// SMUIO_PCC_CONTROL
pub const SMUIO_PCC_CONTROL__PCC_POLARITY__SHIFT: c_uint = 0x0;
pub const SMUIO_PCC_CONTROL__PCC_POLARITY_MASK: c_uint = 0x00000001L;
// SMUIO_PCC_GPIO_SELECT
pub const SMUIO_PCC_GPIO_SELECT__GPIO__SHIFT: c_uint = 0x0;
pub const SMUIO_PCC_GPIO_SELECT__GPIO_MASK: c_uint = 0xFFFFFFFFL;
// SMUIO_GPIO_INT0_SELECT
pub const SMUIO_GPIO_INT0_SELECT__GPIO_INT0_SELECT__SHIFT: c_uint = 0x0;
pub const SMUIO_GPIO_INT0_SELECT__GPIO_INT0_SELECT_MASK: c_uint = 0xFFFFFFFFL;
// SMUIO_GPIO_INT1_SELECT
pub const SMUIO_GPIO_INT1_SELECT__GPIO_INT1_SELECT__SHIFT: c_uint = 0x0;
pub const SMUIO_GPIO_INT1_SELECT__GPIO_INT1_SELECT_MASK: c_uint = 0xFFFFFFFFL;
// SMUIO_GPIO_INT2_SELECT
pub const SMUIO_GPIO_INT2_SELECT__GPIO_INT2_SELECT__SHIFT: c_uint = 0x0;
pub const SMUIO_GPIO_INT2_SELECT__GPIO_INT2_SELECT_MASK: c_uint = 0xFFFFFFFFL;
// SMUIO_GPIO_INT3_SELECT
pub const SMUIO_GPIO_INT3_SELECT__GPIO_INT3_SELECT__SHIFT: c_uint = 0x0;
pub const SMUIO_GPIO_INT3_SELECT__GPIO_INT3_SELECT_MASK: c_uint = 0xFFFFFFFFL;
// SMU_GPIOPAD_MP_INT0_STAT
pub const SMU_GPIOPAD_MP_INT0_STAT__GPIO_MP_INT0_STAT__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_MP_INT0_STAT__GPIO_MP_INT0_STAT_MASK: c_uint = 0x1FFFFFFFL;
// SMU_GPIOPAD_MP_INT1_STAT
pub const SMU_GPIOPAD_MP_INT1_STAT__GPIO_MP_INT1_STAT__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_MP_INT1_STAT__GPIO_MP_INT1_STAT_MASK: c_uint = 0x1FFFFFFFL;
// SMU_GPIOPAD_MP_INT2_STAT
pub const SMU_GPIOPAD_MP_INT2_STAT__GPIO_MP_INT2_STAT__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_MP_INT2_STAT__GPIO_MP_INT2_STAT_MASK: c_uint = 0x1FFFFFFFL;
// SMU_GPIOPAD_MP_INT3_STAT
pub const SMU_GPIOPAD_MP_INT3_STAT__GPIO_MP_INT3_STAT__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_MP_INT3_STAT__GPIO_MP_INT3_STAT_MASK: c_uint = 0x1FFFFFFFL;
// SMIO_INDEX
pub const SMIO_INDEX__SW_SMIO_INDEX__SHIFT: c_uint = 0x0;
pub const SMIO_INDEX__SW_SMIO_INDEX_MASK: c_uint = 0x00000001L;
// S0_VID_SMIO_CNTL
pub const S0_VID_SMIO_CNTL__S0_SMIO_VALUES__SHIFT: c_uint = 0x0;
pub const S0_VID_SMIO_CNTL__S0_SMIO_VALUES_MASK: c_uint = 0xFFFFFFFFL;
// S1_VID_SMIO_CNTL
pub const S1_VID_SMIO_CNTL__S1_SMIO_VALUES__SHIFT: c_uint = 0x0;
pub const S1_VID_SMIO_CNTL__S1_SMIO_VALUES_MASK: c_uint = 0xFFFFFFFFL;
// OPEN_DRAIN_SELECT
pub const OPEN_DRAIN_SELECT__OPEN_DRAIN_SELECT__SHIFT: c_uint = 0x0;
pub const OPEN_DRAIN_SELECT__RESERVED__SHIFT: c_uint = 0x1f;
pub const OPEN_DRAIN_SELECT__OPEN_DRAIN_SELECT_MASK: c_uint = 0x7FFFFFFFL;
pub const OPEN_DRAIN_SELECT__RESERVED_MASK: c_uint = 0x80000000L;
// SMIO_ENABLE
pub const SMIO_ENABLE__SMIO_ENABLE__SHIFT: c_uint = 0x0;
pub const SMIO_ENABLE__SMIO_ENABLE_MASK: c_uint = 0xFFFFFFFFL;
// SMU_GPIOPAD_S0
pub const SMU_GPIOPAD_S0__GPIO_S0__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_S0__GPIO_S0_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_S1
pub const SMU_GPIOPAD_S1__GPIO_S1__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_S1__GPIO_S1_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_SCL_EN
pub const SMU_GPIOPAD_SCL_EN__GPIO_SCL_EN__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_SCL_EN__GPIO_SCL_EN_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_SDA_EN
pub const SMU_GPIOPAD_SDA_EN__GPIO_SDA_EN__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_SDA_EN__GPIO_SDA_EN_MASK: c_uint = 0x7FFFFFFFL;
// SMU_GPIOPAD_SCHMEN
pub const SMU_GPIOPAD_SCHMEN__GPIO_SCHMEN__SHIFT: c_uint = 0x0;
pub const SMU_GPIOPAD_SCHMEN__GPIO_SCHMEN_MASK: c_uint = 0x7FFFFFFFL;
// addressBlock: smuio_smuio_pwr_SmuSmuioDec
// IP_DISCOVERY_VERSION
pub const IP_DISCOVERY_VERSION__IP_DISCOVERY_VERSION__SHIFT: c_uint = 0x0;
pub const IP_DISCOVERY_VERSION__IP_DISCOVERY_VERSION_MASK: c_uint = 0xFFFFFFFFL;
// SOC_GAP_PWROK
pub const SOC_GAP_PWROK__soc_gap_pwrok__SHIFT: c_uint = 0x0;
pub const SOC_GAP_PWROK__soc_gap_pwrok_MASK: c_uint = 0x00000001L;
// GFX_GAP_PWROK
pub const GFX_GAP_PWROK__gfx_gap_pwrok__SHIFT: c_uint = 0x0;
pub const GFX_GAP_PWROK__gfx_gap_pwrok_MASK: c_uint = 0x00000001L;
// PWROK_REFCLK_GAP_CYCLES
pub const PWROK_REFCLK_GAP_CYCLES__Pwrok_PreAssertion_clkgap_cycles__SHIFT: c_uint = 0x0;
pub const PWROK_REFCLK_GAP_CYCLES__Pwrok_PostAssertion_clkgap_cycles__SHIFT: c_uint = 0x8;
pub const PWROK_REFCLK_GAP_CYCLES__Pwrok_PreAssertion_clkgap_cycles_MASK: c_uint = 0x000000FFL;
pub const PWROK_REFCLK_GAP_CYCLES__Pwrok_PostAssertion_clkgap_cycles_MASK: c_uint = 0x0000FF00L;
// GOLDEN_TSC_INCREMENT_UPPER
pub const GOLDEN_TSC_INCREMENT_UPPER__GoldenTscIncrementUpper__SHIFT: c_uint = 0x0;
pub const GOLDEN_TSC_INCREMENT_UPPER__GoldenTscIncrementUpper_MASK: c_uint = 0x00FFFFFFL;
// GOLDEN_TSC_INCREMENT_LOWER
pub const GOLDEN_TSC_INCREMENT_LOWER__GoldenTscIncrementLower__SHIFT: c_uint = 0x0;
pub const GOLDEN_TSC_INCREMENT_LOWER__GoldenTscIncrementLower_MASK: c_uint = 0xFFFFFFFFL;
// GOLDEN_TSC_COUNT_UPPER
pub const GOLDEN_TSC_COUNT_UPPER__GoldenTscCountUpper__SHIFT: c_uint = 0x0;
pub const GOLDEN_TSC_COUNT_UPPER__GoldenTscCountUpper_MASK: c_uint = 0x00FFFFFFL;
// GOLDEN_TSC_COUNT_LOWER
pub const GOLDEN_TSC_COUNT_LOWER__GoldenTscCountLower__SHIFT: c_uint = 0x0;
pub const GOLDEN_TSC_COUNT_LOWER__GoldenTscCountLower_MASK: c_uint = 0xFFFFFFFFL;
// SOC_GOLDEN_TSC_SHADOW_UPPER
pub const SOC_GOLDEN_TSC_SHADOW_UPPER__SOCGoldenTscShadowUpper__SHIFT: c_uint = 0x0;
pub const SOC_GOLDEN_TSC_SHADOW_UPPER__SOCGoldenTscShadowUpper_MASK: c_uint = 0x00FFFFFFL;
// SOC_GOLDEN_TSC_SHADOW_LOWER
pub const SOC_GOLDEN_TSC_SHADOW_LOWER__SOCGoldenTscShadowLower__SHIFT: c_uint = 0x0;
pub const SOC_GOLDEN_TSC_SHADOW_LOWER__SOCGoldenTscShadowLower_MASK: c_uint = 0xFFFFFFFFL;
// GFX_GOLDEN_TSC_SHADOW_UPPER
pub const GFX_GOLDEN_TSC_SHADOW_UPPER__GFXGoldenTscShadowUpper__SHIFT: c_uint = 0x0;
pub const GFX_GOLDEN_TSC_SHADOW_UPPER__GFXGoldenTscShadowUpper_MASK: c_uint = 0x00FFFFFFL;
// GFX_GOLDEN_TSC_SHADOW_LOWER
pub const GFX_GOLDEN_TSC_SHADOW_LOWER__GFXGoldenTscShadowLower__SHIFT: c_uint = 0x0;
pub const GFX_GOLDEN_TSC_SHADOW_LOWER__GFXGoldenTscShadowLower_MASK: c_uint = 0xFFFFFFFFL;
// PWR_VIRT_RESET_REQ
pub const PWR_VIRT_RESET_REQ__VF_FLR__SHIFT: c_uint = 0x0;
pub const PWR_VIRT_RESET_REQ__PF_FLR__SHIFT: c_uint = 0x1f;
pub const PWR_VIRT_RESET_REQ__VF_FLR_MASK: c_uint = 0x7FFFFFFFL;
pub const PWR_VIRT_RESET_REQ__PF_FLR_MASK: c_uint = 0x80000000L;
// SCRATCH_REGISTER0
pub const SCRATCH_REGISTER0__ScratchPad0__SHIFT: c_uint = 0x0;
pub const SCRATCH_REGISTER0__ScratchPad0_MASK: c_uint = 0xFFFFFFFFL;
// SCRATCH_REGISTER1
pub const SCRATCH_REGISTER1__ScratchPad1__SHIFT: c_uint = 0x0;
pub const SCRATCH_REGISTER1__ScratchPad1_MASK: c_uint = 0xFFFFFFFFL;
// SCRATCH_REGISTER2
pub const SCRATCH_REGISTER2__ScratchPad2__SHIFT: c_uint = 0x0;
pub const SCRATCH_REGISTER2__ScratchPad2_MASK: c_uint = 0xFFFFFFFFL;
// SCRATCH_REGISTER3
pub const SCRATCH_REGISTER3__ScratchPad3__SHIFT: c_uint = 0x0;
pub const SCRATCH_REGISTER3__ScratchPad3_MASK: c_uint = 0xFFFFFFFFL;
// SCRATCH_REGISTER4
pub const SCRATCH_REGISTER4__ScratchPad4__SHIFT: c_uint = 0x0;
pub const SCRATCH_REGISTER4__ScratchPad4_MASK: c_uint = 0xFFFFFFFFL;
// SCRATCH_REGISTER5
pub const SCRATCH_REGISTER5__ScratchPad5__SHIFT: c_uint = 0x0;
pub const SCRATCH_REGISTER5__ScratchPad5_MASK: c_uint = 0xFFFFFFFFL;
// SCRATCH_REGISTER6
pub const SCRATCH_REGISTER6__ScratchPad6__SHIFT: c_uint = 0x0;
pub const SCRATCH_REGISTER6__ScratchPad6_MASK: c_uint = 0xFFFFFFFFL;
// SCRATCH_REGISTER7
pub const SCRATCH_REGISTER7__ScratchPad7__SHIFT: c_uint = 0x0;
pub const SCRATCH_REGISTER7__ScratchPad7_MASK: c_uint = 0xFFFFFFFFL;
// PWR_DISP_TIMER_CONTROL
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_COUNT__SHIFT: c_uint = 0x0;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_ENABLE__SHIFT: c_uint = 0x19;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_DISABLE__SHIFT: c_uint = 0x1a;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_MASK__SHIFT: c_uint = 0x1b;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_STAT_AK__SHIFT: c_uint = 0x1c;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_TYPE__SHIFT: c_uint = 0x1d;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_MODE__SHIFT: c_uint = 0x1e;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_COUNT_MASK: c_uint = 0x01FFFFFFL;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_ENABLE_MASK: c_uint = 0x02000000L;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_DISABLE_MASK: c_uint = 0x04000000L;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_MASK_MASK: c_uint = 0x08000000L;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_STAT_AK_MASK: c_uint = 0x10000000L;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_TYPE_MASK: c_uint = 0x20000000L;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_MODE_MASK: c_uint = 0x40000000L;
// PWR_DISP_TIMER2_CONTROL
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_COUNT__SHIFT: c_uint = 0x0;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_ENABLE__SHIFT: c_uint = 0x19;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_DISABLE__SHIFT: c_uint = 0x1a;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_MASK__SHIFT: c_uint = 0x1b;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_STAT_AK__SHIFT: c_uint = 0x1c;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_TYPE__SHIFT: c_uint = 0x1d;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_MODE__SHIFT: c_uint = 0x1e;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_COUNT_MASK: c_uint = 0x01FFFFFFL;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_ENABLE_MASK: c_uint = 0x02000000L;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_DISABLE_MASK: c_uint = 0x04000000L;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_MASK_MASK: c_uint = 0x08000000L;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_STAT_AK_MASK: c_uint = 0x10000000L;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_TYPE_MASK: c_uint = 0x20000000L;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_MODE_MASK: c_uint = 0x40000000L;
// PWR_DISP_TIMER_GLOBAL_CONTROL
pub const PWR_DISP_TIMER_GLOBAL_CONTROL__DISP_TIMER_PULSE_WIDTH__SHIFT: c_uint = 0x0;
pub const PWR_DISP_TIMER_GLOBAL_CONTROL__DISP_TIMER_PULSE_EN__SHIFT: c_uint = 0xa;
pub const PWR_DISP_TIMER_GLOBAL_CONTROL__DISP_TIMER_PULSE_WIDTH_MASK: c_uint = 0x000003FFL;
pub const PWR_DISP_TIMER_GLOBAL_CONTROL__DISP_TIMER_PULSE_EN_MASK: c_uint = 0x00000400L;
// PWR_IH_CONTROL
pub const PWR_IH_CONTROL__MAX_CREDIT__SHIFT: c_uint = 0x0;
pub const PWR_IH_CONTROL__DISP_TIMER_TRIGGER_MASK__SHIFT: c_uint = 0x5;
pub const PWR_IH_CONTROL__DISP_TIMER2_TRIGGER_MASK__SHIFT: c_uint = 0x6;
pub const PWR_IH_CONTROL__MAX_CREDIT_MASK: c_uint = 0x0000001FL;
pub const PWR_IH_CONTROL__DISP_TIMER_TRIGGER_MASK_MASK: c_uint = 0x00000020L;
pub const PWR_IH_CONTROL__DISP_TIMER2_TRIGGER_MASK_MASK: c_uint = 0x00000040L;
