//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/amd/include/asic_reg/vce/vce_4_0_sh_mask.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// Copyright (C) 2017  Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
// AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

// Macro flag: #define _vce_4_0_SH_MASK_HEADER
// addressBlock: vce0_vce_dec
// VCE_STATUS
pub const VCE_STATUS__JOB_BUSY__SHIFT: c_uint = 0x0;
pub const VCE_STATUS__VCPU_REPORT__SHIFT: c_uint = 0x1;
pub const VCE_STATUS__UENC_BUSY__SHIFT: c_uint = 0x8;
pub const VCE_STATUS__VCE_CONFIGURATION__SHIFT: c_uint = 0x16;
pub const VCE_STATUS__VCE_INSTANCE_ID__SHIFT: c_uint = 0x18;
pub const VCE_STATUS__JOB_BUSY_MASK: c_uint = 0x00000001L;
pub const VCE_STATUS__VCPU_REPORT_MASK: c_uint = 0x000000FEL;
pub const VCE_STATUS__UENC_BUSY_MASK: c_uint = 0x00000100L;
pub const VCE_STATUS__VCE_CONFIGURATION_MASK: c_uint = 0x00C00000L;
pub const VCE_STATUS__VCE_INSTANCE_ID_MASK: c_uint = 0x03000000L;
// VCE_VCPU_CNTL
pub const VCE_VCPU_CNTL__CLK_EN__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CNTL__ED_ENABLE__SHIFT: c_uint = 0x1;
pub const VCE_VCPU_CNTL__RBBM_SOFT_RESET__SHIFT: c_uint = 0x12;
pub const VCE_VCPU_CNTL__ONE_CACHE_SURFACE_EN__SHIFT: c_uint = 0x15;
pub const VCE_VCPU_CNTL__CLK_EN_MASK: c_uint = 0x00000001L;
pub const VCE_VCPU_CNTL__ED_ENABLE_MASK: c_uint = 0x00000002L;
pub const VCE_VCPU_CNTL__RBBM_SOFT_RESET_MASK: c_uint = 0x00040000L;
pub const VCE_VCPU_CNTL__ONE_CACHE_SURFACE_EN_MASK: c_uint = 0x00200000L;
// VCE_VCPU_CACHE_OFFSET0
pub const VCE_VCPU_CACHE_OFFSET0__OFFSET__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_OFFSET0__OFFSET_MASK: c_uint = 0x0FFFFFFFL;
// VCE_VCPU_CACHE_SIZE0
pub const VCE_VCPU_CACHE_SIZE0__SIZE__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_SIZE0__SIZE_MASK: c_uint = 0x00FFFFFFL;
// VCE_VCPU_CACHE_OFFSET1
pub const VCE_VCPU_CACHE_OFFSET1__OFFSET__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_OFFSET1__OFFSET_MASK: c_uint = 0x0FFFFFFFL;
// VCE_VCPU_CACHE_SIZE1
pub const VCE_VCPU_CACHE_SIZE1__SIZE__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_SIZE1__SIZE_MASK: c_uint = 0x00FFFFFFL;
// VCE_VCPU_CACHE_OFFSET2
pub const VCE_VCPU_CACHE_OFFSET2__OFFSET__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_OFFSET2__OFFSET_MASK: c_uint = 0x0FFFFFFFL;
// VCE_VCPU_CACHE_SIZE2
pub const VCE_VCPU_CACHE_SIZE2__SIZE__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_SIZE2__SIZE_MASK: c_uint = 0x00FFFFFFL;
// VCE_VCPU_CACHE_OFFSET3
pub const VCE_VCPU_CACHE_OFFSET3__OFFSET__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_OFFSET3__OFFSET_MASK: c_uint = 0x0FFFFFFFL;
// VCE_VCPU_CACHE_SIZE3
pub const VCE_VCPU_CACHE_SIZE3__SIZE__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_SIZE3__SIZE_MASK: c_uint = 0x00FFFFFFL;
// VCE_VCPU_CACHE_OFFSET4
pub const VCE_VCPU_CACHE_OFFSET4__OFFSET__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_OFFSET4__OFFSET_MASK: c_uint = 0x0FFFFFFFL;
// VCE_VCPU_CACHE_SIZE4
pub const VCE_VCPU_CACHE_SIZE4__SIZE__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_SIZE4__SIZE_MASK: c_uint = 0x00FFFFFFL;
// VCE_VCPU_CACHE_OFFSET5
pub const VCE_VCPU_CACHE_OFFSET5__OFFSET__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_OFFSET5__OFFSET_MASK: c_uint = 0x0FFFFFFFL;
// VCE_VCPU_CACHE_SIZE5
pub const VCE_VCPU_CACHE_SIZE5__SIZE__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_SIZE5__SIZE_MASK: c_uint = 0x00FFFFFFL;
// VCE_VCPU_CACHE_OFFSET6
pub const VCE_VCPU_CACHE_OFFSET6__OFFSET__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_OFFSET6__OFFSET_MASK: c_uint = 0x0FFFFFFFL;
// VCE_VCPU_CACHE_SIZE6
pub const VCE_VCPU_CACHE_SIZE6__SIZE__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_SIZE6__SIZE_MASK: c_uint = 0x00FFFFFFL;
// VCE_VCPU_CACHE_OFFSET7
pub const VCE_VCPU_CACHE_OFFSET7__OFFSET__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_OFFSET7__OFFSET_MASK: c_uint = 0x0FFFFFFFL;
// VCE_VCPU_CACHE_SIZE7
pub const VCE_VCPU_CACHE_SIZE7__SIZE__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_SIZE7__SIZE_MASK: c_uint = 0x00FFFFFFL;
// VCE_VCPU_CACHE_OFFSET8
pub const VCE_VCPU_CACHE_OFFSET8__OFFSET__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_OFFSET8__OFFSET_MASK: c_uint = 0x0FFFFFFFL;
// VCE_VCPU_CACHE_SIZE8
pub const VCE_VCPU_CACHE_SIZE8__SIZE__SHIFT: c_uint = 0x0;
pub const VCE_VCPU_CACHE_SIZE8__SIZE_MASK: c_uint = 0x00FFFFFFL;
// VCE_SOFT_RESET
pub const VCE_SOFT_RESET__ECPU_SOFT_RESET__SHIFT: c_uint = 0x0;
pub const VCE_SOFT_RESET__UENC_SOFT_RESET__SHIFT: c_uint = 0x1;
pub const VCE_SOFT_RESET__FME_SOFT_RESET__SHIFT: c_uint = 0x2;
pub const VCE_SOFT_RESET__MIF_SOFT_RESET__SHIFT: c_uint = 0x3;
pub const VCE_SOFT_RESET__DBF_SOFT_RESET__SHIFT: c_uint = 0x4;
pub const VCE_SOFT_RESET__ENT_SOFT_RESET__SHIFT: c_uint = 0x5;
pub const VCE_SOFT_RESET__TBE_SOFT_RESET__SHIFT: c_uint = 0x6;
pub const VCE_SOFT_RESET__LCM_SOFT_RESET__SHIFT: c_uint = 0x7;
pub const VCE_SOFT_RESET__CTL_SOFT_RESET__SHIFT: c_uint = 0x8;
pub const VCE_SOFT_RESET__IME_SOFT_RESET__SHIFT: c_uint = 0x9;
pub const VCE_SOFT_RESET__IH_SOFT_RESET__SHIFT: c_uint = 0xa;
pub const VCE_SOFT_RESET__SEM_SOFT_RESET__SHIFT: c_uint = 0xb;
pub const VCE_SOFT_RESET__DCAP_SOFT_RESET__SHIFT: c_uint = 0xc;
pub const VCE_SOFT_RESET__ACAP_SOFT_RESET__SHIFT: c_uint = 0xd;
pub const VCE_SOFT_RESET__TAP_SOFT_RESET__SHIFT: c_uint = 0xe;
pub const VCE_SOFT_RESET__LMI_SOFT_RESET__SHIFT: c_uint = 0xf;
pub const VCE_SOFT_RESET__LMI_UMC_SOFT_RESET__SHIFT: c_uint = 0x10;
pub const VCE_SOFT_RESET__AVMUX_SOFT_RESET__SHIFT: c_uint = 0x13;
pub const VCE_SOFT_RESET__VREG_SOFT_RESET__SHIFT: c_uint = 0x14;
pub const VCE_SOFT_RESET__DCAP_FSM_SOFT_RESET__SHIFT: c_uint = 0x15;
pub const VCE_SOFT_RESET__VEP_SOFT_RESET__SHIFT: c_uint = 0x16;
pub const VCE_SOFT_RESET__ECPU_SOFT_RESET_MASK: c_uint = 0x00000001L;
pub const VCE_SOFT_RESET__UENC_SOFT_RESET_MASK: c_uint = 0x00000002L;
pub const VCE_SOFT_RESET__FME_SOFT_RESET_MASK: c_uint = 0x00000004L;
pub const VCE_SOFT_RESET__MIF_SOFT_RESET_MASK: c_uint = 0x00000008L;
pub const VCE_SOFT_RESET__DBF_SOFT_RESET_MASK: c_uint = 0x00000010L;
pub const VCE_SOFT_RESET__ENT_SOFT_RESET_MASK: c_uint = 0x00000020L;
pub const VCE_SOFT_RESET__TBE_SOFT_RESET_MASK: c_uint = 0x00000040L;
pub const VCE_SOFT_RESET__LCM_SOFT_RESET_MASK: c_uint = 0x00000080L;
pub const VCE_SOFT_RESET__CTL_SOFT_RESET_MASK: c_uint = 0x00000100L;
pub const VCE_SOFT_RESET__IME_SOFT_RESET_MASK: c_uint = 0x00000200L;
pub const VCE_SOFT_RESET__IH_SOFT_RESET_MASK: c_uint = 0x00000400L;
pub const VCE_SOFT_RESET__SEM_SOFT_RESET_MASK: c_uint = 0x00000800L;
pub const VCE_SOFT_RESET__DCAP_SOFT_RESET_MASK: c_uint = 0x00001000L;
pub const VCE_SOFT_RESET__ACAP_SOFT_RESET_MASK: c_uint = 0x00002000L;
pub const VCE_SOFT_RESET__TAP_SOFT_RESET_MASK: c_uint = 0x00004000L;
pub const VCE_SOFT_RESET__LMI_SOFT_RESET_MASK: c_uint = 0x00008000L;
pub const VCE_SOFT_RESET__LMI_UMC_SOFT_RESET_MASK: c_uint = 0x00010000L;
pub const VCE_SOFT_RESET__AVMUX_SOFT_RESET_MASK: c_uint = 0x00080000L;
pub const VCE_SOFT_RESET__VREG_SOFT_RESET_MASK: c_uint = 0x00100000L;
pub const VCE_SOFT_RESET__DCAP_FSM_SOFT_RESET_MASK: c_uint = 0x00200000L;
pub const VCE_SOFT_RESET__VEP_SOFT_RESET_MASK: c_uint = 0x00400000L;
// VCE_RB_BASE_LO2
pub const VCE_RB_BASE_LO2__RB_BASE_LO__SHIFT: c_uint = 0x6;
pub const VCE_RB_BASE_LO2__RB_BASE_LO_MASK: c_uint = 0xFFFFFFC0L;
// VCE_RB_BASE_HI2
pub const VCE_RB_BASE_HI2__RB_BASE_HI__SHIFT: c_uint = 0x0;
pub const VCE_RB_BASE_HI2__RB_BASE_HI_MASK: c_uint = 0xFFFFFFFFL;
// VCE_RB_SIZE2
pub const VCE_RB_SIZE2__RB_SIZE__SHIFT: c_uint = 0x4;
pub const VCE_RB_SIZE2__RB_SIZE_MASK: c_uint = 0x007FFFF0L;
// VCE_RB_RPTR2
pub const VCE_RB_RPTR2__RB_RPTR__SHIFT: c_uint = 0x4;
pub const VCE_RB_RPTR2__RB_RPTR_MASK: c_uint = 0x007FFFF0L;
// VCE_RB_WPTR2
pub const VCE_RB_WPTR2__RB_WPTR__SHIFT: c_uint = 0x4;
pub const VCE_RB_WPTR2__RB_WPTR_MASK: c_uint = 0x007FFFF0L;
// VCE_RB_BASE_LO
pub const VCE_RB_BASE_LO__RB_BASE_LO__SHIFT: c_uint = 0x6;
pub const VCE_RB_BASE_LO__RB_BASE_LO_MASK: c_uint = 0xFFFFFFC0L;
// VCE_RB_BASE_HI
pub const VCE_RB_BASE_HI__RB_BASE_HI__SHIFT: c_uint = 0x0;
pub const VCE_RB_BASE_HI__RB_BASE_HI_MASK: c_uint = 0xFFFFFFFFL;
// VCE_RB_SIZE
pub const VCE_RB_SIZE__RB_SIZE__SHIFT: c_uint = 0x4;
pub const VCE_RB_SIZE__RB_SIZE_MASK: c_uint = 0x007FFFF0L;
// VCE_RB_RPTR
pub const VCE_RB_RPTR__RB_RPTR__SHIFT: c_uint = 0x4;
pub const VCE_RB_RPTR__RB_RPTR_MASK: c_uint = 0x007FFFF0L;
// VCE_RB_WPTR
pub const VCE_RB_WPTR__RB_WPTR__SHIFT: c_uint = 0x4;
pub const VCE_RB_WPTR__RB_WPTR_MASK: c_uint = 0x007FFFF0L;
// VCE_RB_ARB_CTRL
pub const VCE_RB_ARB_CTRL__RB_ARB_CTRL__SHIFT: c_uint = 0x0;
pub const VCE_RB_ARB_CTRL__VCE_CGTT_OVERRIDE__SHIFT: c_uint = 0x10;
pub const VCE_RB_ARB_CTRL__RB_ARB_CTRL_MASK: c_uint = 0x000001FFL;
pub const VCE_RB_ARB_CTRL__VCE_CGTT_OVERRIDE_MASK: c_uint = 0x00010000L;
// VCE_CLOCK_GATING_A
pub const VCE_CLOCK_GATING_A__CGC_CLK_ON_DELAY__SHIFT: c_uint = 0x0;
pub const VCE_CLOCK_GATING_A__CGC_CLK_OFF_DELAY__SHIFT: c_uint = 0x4;
pub const VCE_CLOCK_GATING_A__CGC_REG_AWAKE__SHIFT: c_uint = 0x11;
pub const VCE_CLOCK_GATING_A__CGC_CLK_ON_DELAY_MASK: c_uint = 0x0000000FL;
pub const VCE_CLOCK_GATING_A__CGC_CLK_OFF_DELAY_MASK: c_uint = 0x00000FF0L;
pub const VCE_CLOCK_GATING_A__CGC_REG_AWAKE_MASK: c_uint = 0x00020000L;
// VCE_CLOCK_GATING_B
pub const VCE_CLOCK_GATING_B__CGC_SYS_CLK_FORCE_ON__SHIFT: c_uint = 0x0;
pub const VCE_CLOCK_GATING_B__CGC_LMI_MC_CLK_FORCE_ON__SHIFT: c_uint = 0x1;
pub const VCE_CLOCK_GATING_B__CGC_LMI_UMC_CLK_FORCE_ON__SHIFT: c_uint = 0x2;
pub const VCE_CLOCK_GATING_B__CGC_UENC_CLK_FORCE_ON__SHIFT: c_uint = 0x3;
pub const VCE_CLOCK_GATING_B__CGC_VREG_CLK_FORCE_ON__SHIFT: c_uint = 0x4;
pub const VCE_CLOCK_GATING_B__CGC_ECPU_CLK_FORCE_ON__SHIFT: c_uint = 0x5;
pub const VCE_CLOCK_GATING_B__CGC_IH_CLK_FORCE_ON__SHIFT: c_uint = 0x6;
pub const VCE_CLOCK_GATING_B__CGC_SEM_CLK_FORCE_ON__SHIFT: c_uint = 0x7;
pub const VCE_CLOCK_GATING_B__CGC_CTLREG_CLK_FORCE_ON__SHIFT: c_uint = 0x8;
pub const VCE_CLOCK_GATING_B__CGC_MMSCH_CLK_FORCE_ON__SHIFT: c_uint = 0x9;
pub const VCE_CLOCK_GATING_B__CGC_SYS_CLK_FORCE_OFF__SHIFT: c_uint = 0x10;
pub const VCE_CLOCK_GATING_B__CGC_LMI_MC_CLK_FORCE_OFF__SHIFT: c_uint = 0x11;
pub const VCE_CLOCK_GATING_B__CGC_LMI_UMC_CLK_FORCE_OFF__SHIFT: c_uint = 0x12;
pub const VCE_CLOCK_GATING_B__CGC_UENC_CLK_FORCE_OFF__SHIFT: c_uint = 0x13;
pub const VCE_CLOCK_GATING_B__CGC_ECPU_CLK_FORCE_OFF__SHIFT: c_uint = 0x15;
pub const VCE_CLOCK_GATING_B__CGC_IH_CLK_FORCE_OFF__SHIFT: c_uint = 0x16;
pub const VCE_CLOCK_GATING_B__CGC_SEM_CLK_FORCE_OFF__SHIFT: c_uint = 0x17;
pub const VCE_CLOCK_GATING_B__CGC_MMSCH_CLK_FORCE_OFF__SHIFT: c_uint = 0x18;
pub const VCE_CLOCK_GATING_B__CGC_SYS_CLK_FORCE_ON_MASK: c_uint = 0x00000001L;
pub const VCE_CLOCK_GATING_B__CGC_LMI_MC_CLK_FORCE_ON_MASK: c_uint = 0x00000002L;
pub const VCE_CLOCK_GATING_B__CGC_LMI_UMC_CLK_FORCE_ON_MASK: c_uint = 0x00000004L;
pub const VCE_CLOCK_GATING_B__CGC_UENC_CLK_FORCE_ON_MASK: c_uint = 0x00000008L;
pub const VCE_CLOCK_GATING_B__CGC_VREG_CLK_FORCE_ON_MASK: c_uint = 0x00000010L;
pub const VCE_CLOCK_GATING_B__CGC_ECPU_CLK_FORCE_ON_MASK: c_uint = 0x00000020L;
pub const VCE_CLOCK_GATING_B__CGC_IH_CLK_FORCE_ON_MASK: c_uint = 0x00000040L;
pub const VCE_CLOCK_GATING_B__CGC_SEM_CLK_FORCE_ON_MASK: c_uint = 0x00000080L;
pub const VCE_CLOCK_GATING_B__CGC_CTLREG_CLK_FORCE_ON_MASK: c_uint = 0x00000100L;
pub const VCE_CLOCK_GATING_B__CGC_MMSCH_CLK_FORCE_ON_MASK: c_uint = 0x00000200L;
pub const VCE_CLOCK_GATING_B__CGC_SYS_CLK_FORCE_OFF_MASK: c_uint = 0x00010000L;
pub const VCE_CLOCK_GATING_B__CGC_LMI_MC_CLK_FORCE_OFF_MASK: c_uint = 0x00020000L;
pub const VCE_CLOCK_GATING_B__CGC_LMI_UMC_CLK_FORCE_OFF_MASK: c_uint = 0x00040000L;
pub const VCE_CLOCK_GATING_B__CGC_UENC_CLK_FORCE_OFF_MASK: c_uint = 0x00080000L;
pub const VCE_CLOCK_GATING_B__CGC_ECPU_CLK_FORCE_OFF_MASK: c_uint = 0x00200000L;
pub const VCE_CLOCK_GATING_B__CGC_IH_CLK_FORCE_OFF_MASK: c_uint = 0x00400000L;
pub const VCE_CLOCK_GATING_B__CGC_SEM_CLK_FORCE_OFF_MASK: c_uint = 0x00800000L;
pub const VCE_CLOCK_GATING_B__CGC_MMSCH_CLK_FORCE_OFF_MASK: c_uint = 0x01000000L;
// VCE_RB_BASE_LO3
pub const VCE_RB_BASE_LO3__RB_BASE_LO__SHIFT: c_uint = 0x6;
pub const VCE_RB_BASE_LO3__RB_BASE_LO_MASK: c_uint = 0xFFFFFFC0L;
// VCE_RB_BASE_HI3
pub const VCE_RB_BASE_HI3__RB_BASE_HI__SHIFT: c_uint = 0x0;
pub const VCE_RB_BASE_HI3__RB_BASE_HI_MASK: c_uint = 0xFFFFFFFFL;
// VCE_RB_SIZE3
pub const VCE_RB_SIZE3__RB_SIZE__SHIFT: c_uint = 0x4;
pub const VCE_RB_SIZE3__RB_SIZE_MASK: c_uint = 0x007FFFF0L;
// VCE_RB_RPTR3
pub const VCE_RB_RPTR3__RB_RPTR__SHIFT: c_uint = 0x4;
pub const VCE_RB_RPTR3__RB_RPTR_MASK: c_uint = 0x007FFFF0L;
// VCE_RB_WPTR3
pub const VCE_RB_WPTR3__RB_WPTR__SHIFT: c_uint = 0x4;
pub const VCE_RB_WPTR3__RB_WPTR_MASK: c_uint = 0x007FFFF0L;
// VCE_SYS_INT_EN
pub const VCE_SYS_INT_EN__VCE_SYS_INT_SEMA_WAIT_FAIL_TIMEOUT_EN__SHIFT: c_uint = 0x0;
pub const VCE_SYS_INT_EN__VCE_SYS_INT_TRAP_INTERRUPT_EN__SHIFT: c_uint = 0x3;
pub const VCE_SYS_INT_EN__VCE_SYS_INT_SEMA_WAIT_FAIL_TIMEOUT_EN_MASK: c_uint = 0x00000001L;
pub const VCE_SYS_INT_EN__VCE_SYS_INT_TRAP_INTERRUPT_EN_MASK: c_uint = 0x00000008L;
// VCE_SYS_INT_ACK
pub const VCE_SYS_INT_ACK__VCE_SYS_INT_SEMA_WAIT_FAIL_TIMEOUT_ACK__SHIFT: c_uint = 0x0;
pub const VCE_SYS_INT_ACK__VCE_SYS_INT_TRAP_INTERRUPT_ACK__SHIFT: c_uint = 0x3;
pub const VCE_SYS_INT_ACK__VCE_SYS_INT_SEMA_WAIT_FAIL_TIMEOUT_ACK_MASK: c_uint = 0x00000001L;
pub const VCE_SYS_INT_ACK__VCE_SYS_INT_TRAP_INTERRUPT_ACK_MASK: c_uint = 0x00000008L;
// VCE_SYS_INT_STATUS
pub const VCE_SYS_INT_STATUS__VCE_SYS_INT_SEMA_WAIT_FAIL_TIMEOUT_INT__SHIFT: c_uint = 0x0;
pub const VCE_SYS_INT_STATUS__VCE_SYS_INT_TRAP_INTERRUPT_INT__SHIFT: c_uint = 0x3;
pub const VCE_SYS_INT_STATUS__VCE_SYS_INT_SEMA_WAIT_FAIL_TIMEOUT_INT_MASK: c_uint = 0x00000001L;
pub const VCE_SYS_INT_STATUS__VCE_SYS_INT_TRAP_INTERRUPT_INT_MASK: c_uint = 0x00000008L;
// addressBlock: vce0_ctl_dec
// VCE_UENC_CLOCK_GATING
pub const VCE_UENC_CLOCK_GATING__CLOCK_ON_DELAY__SHIFT: c_uint = 0x0;
pub const VCE_UENC_CLOCK_GATING__CLOCK_OFF_DELAY__SHIFT: c_uint = 0x4;
pub const VCE_UENC_CLOCK_GATING__VEPCLK_FORCE_ON__SHIFT: c_uint = 0xc;
pub const VCE_UENC_CLOCK_GATING__IMECLK_FORCE_ON__SHIFT: c_uint = 0xd;
pub const VCE_UENC_CLOCK_GATING__FMECLK_FORCE_ON__SHIFT: c_uint = 0xe;
pub const VCE_UENC_CLOCK_GATING__TBECLK_FORCE_ON__SHIFT: c_uint = 0xf;
pub const VCE_UENC_CLOCK_GATING__DBFCLK_FORCE_ON__SHIFT: c_uint = 0x10;
pub const VCE_UENC_CLOCK_GATING__ENTCLK_FORCE_ON__SHIFT: c_uint = 0x11;
pub const VCE_UENC_CLOCK_GATING__LCMCLK_FORCE_ON__SHIFT: c_uint = 0x12;
pub const VCE_UENC_CLOCK_GATING__AVMCLK_FORCE_ON__SHIFT: c_uint = 0x13;
pub const VCE_UENC_CLOCK_GATING__DCAPCLK_FORCE_ON__SHIFT: c_uint = 0x14;
pub const VCE_UENC_CLOCK_GATING__ACAPCLK_FORCE_ON__SHIFT: c_uint = 0x15;
pub const VCE_UENC_CLOCK_GATING__ACAPCLK_FORCE_OFF__SHIFT: c_uint = 0x16;
pub const VCE_UENC_CLOCK_GATING__VEPCLK_FORCE_OFF__SHIFT: c_uint = 0x17;
pub const VCE_UENC_CLOCK_GATING__IMECLK_FORCE_OFF__SHIFT: c_uint = 0x18;
pub const VCE_UENC_CLOCK_GATING__FMECLK_FORCE_OFF__SHIFT: c_uint = 0x19;
pub const VCE_UENC_CLOCK_GATING__TBECLK_FORCE_OFF__SHIFT: c_uint = 0x1a;
pub const VCE_UENC_CLOCK_GATING__DBFCLK_FORCE_OFF__SHIFT: c_uint = 0x1b;
pub const VCE_UENC_CLOCK_GATING__ENTCLK_FORCE_OFF__SHIFT: c_uint = 0x1c;
pub const VCE_UENC_CLOCK_GATING__LCMCLK_FORCE_OFF__SHIFT: c_uint = 0x1d;
pub const VCE_UENC_CLOCK_GATING__AVMCLK_FORCE_OFF__SHIFT: c_uint = 0x1e;
pub const VCE_UENC_CLOCK_GATING__DCAPCLK_FORCE_OFF__SHIFT: c_uint = 0x1f;
pub const VCE_UENC_CLOCK_GATING__CLOCK_ON_DELAY_MASK: c_uint = 0x0000000FL;
pub const VCE_UENC_CLOCK_GATING__CLOCK_OFF_DELAY_MASK: c_uint = 0x00000FF0L;
pub const VCE_UENC_CLOCK_GATING__VEPCLK_FORCE_ON_MASK: c_uint = 0x00001000L;
pub const VCE_UENC_CLOCK_GATING__IMECLK_FORCE_ON_MASK: c_uint = 0x00002000L;
pub const VCE_UENC_CLOCK_GATING__FMECLK_FORCE_ON_MASK: c_uint = 0x00004000L;
pub const VCE_UENC_CLOCK_GATING__TBECLK_FORCE_ON_MASK: c_uint = 0x00008000L;
pub const VCE_UENC_CLOCK_GATING__DBFCLK_FORCE_ON_MASK: c_uint = 0x00010000L;
pub const VCE_UENC_CLOCK_GATING__ENTCLK_FORCE_ON_MASK: c_uint = 0x00020000L;
pub const VCE_UENC_CLOCK_GATING__LCMCLK_FORCE_ON_MASK: c_uint = 0x00040000L;
pub const VCE_UENC_CLOCK_GATING__AVMCLK_FORCE_ON_MASK: c_uint = 0x00080000L;
pub const VCE_UENC_CLOCK_GATING__DCAPCLK_FORCE_ON_MASK: c_uint = 0x00100000L;
pub const VCE_UENC_CLOCK_GATING__ACAPCLK_FORCE_ON_MASK: c_uint = 0x00200000L;
pub const VCE_UENC_CLOCK_GATING__ACAPCLK_FORCE_OFF_MASK: c_uint = 0x00400000L;
pub const VCE_UENC_CLOCK_GATING__VEPCLK_FORCE_OFF_MASK: c_uint = 0x00800000L;
pub const VCE_UENC_CLOCK_GATING__IMECLK_FORCE_OFF_MASK: c_uint = 0x01000000L;
pub const VCE_UENC_CLOCK_GATING__FMECLK_FORCE_OFF_MASK: c_uint = 0x02000000L;
pub const VCE_UENC_CLOCK_GATING__TBECLK_FORCE_OFF_MASK: c_uint = 0x04000000L;
pub const VCE_UENC_CLOCK_GATING__DBFCLK_FORCE_OFF_MASK: c_uint = 0x08000000L;
pub const VCE_UENC_CLOCK_GATING__ENTCLK_FORCE_OFF_MASK: c_uint = 0x10000000L;
pub const VCE_UENC_CLOCK_GATING__LCMCLK_FORCE_OFF_MASK: c_uint = 0x20000000L;
pub const VCE_UENC_CLOCK_GATING__AVMCLK_FORCE_OFF_MASK: c_uint = 0x40000000L;
pub const VCE_UENC_CLOCK_GATING__DCAPCLK_FORCE_OFF_MASK: c_uint = 0x80000000L;
// VCE_UENC_REG_CLOCK_GATING
pub const VCE_UENC_REG_CLOCK_GATING__MIFREGCLK_FORCE_ON__SHIFT: c_uint = 0x0;
pub const VCE_UENC_REG_CLOCK_GATING__IMEREGCLK_FORCE_ON__SHIFT: c_uint = 0x1;
pub const VCE_UENC_REG_CLOCK_GATING__FMEREGCLK_FORCE_ON__SHIFT: c_uint = 0x2;
pub const VCE_UENC_REG_CLOCK_GATING__TBEREGCLK_FORCE_ON__SHIFT: c_uint = 0x3;
pub const VCE_UENC_REG_CLOCK_GATING__DBFREGCLK_FORCE_ON__SHIFT: c_uint = 0x4;
pub const VCE_UENC_REG_CLOCK_GATING__ENTREGCLK_FORCE_ON__SHIFT: c_uint = 0x5;
pub const VCE_UENC_REG_CLOCK_GATING__LCMREGCLK_FORCE_ON__SHIFT: c_uint = 0x6;
pub const VCE_UENC_REG_CLOCK_GATING__RESERVED__SHIFT: c_uint = 0x7;
pub const VCE_UENC_REG_CLOCK_GATING__AVMREGCLK_FORCE_ON__SHIFT: c_uint = 0x8;
pub const VCE_UENC_REG_CLOCK_GATING__DCAPREGCLK_FORCE_ON__SHIFT: c_uint = 0x9;
pub const VCE_UENC_REG_CLOCK_GATING__VEPREGCLK_FORCE_ON__SHIFT: c_uint = 0xa;
pub const VCE_UENC_REG_CLOCK_GATING__MIFREGCLK_FORCE_ON_MASK: c_uint = 0x00000001L;
pub const VCE_UENC_REG_CLOCK_GATING__IMEREGCLK_FORCE_ON_MASK: c_uint = 0x00000002L;
pub const VCE_UENC_REG_CLOCK_GATING__FMEREGCLK_FORCE_ON_MASK: c_uint = 0x00000004L;
pub const VCE_UENC_REG_CLOCK_GATING__TBEREGCLK_FORCE_ON_MASK: c_uint = 0x00000008L;
pub const VCE_UENC_REG_CLOCK_GATING__DBFREGCLK_FORCE_ON_MASK: c_uint = 0x00000010L;
pub const VCE_UENC_REG_CLOCK_GATING__ENTREGCLK_FORCE_ON_MASK: c_uint = 0x00000020L;
pub const VCE_UENC_REG_CLOCK_GATING__LCMREGCLK_FORCE_ON_MASK: c_uint = 0x00000040L;
pub const VCE_UENC_REG_CLOCK_GATING__RESERVED_MASK: c_uint = 0x00000080L;
pub const VCE_UENC_REG_CLOCK_GATING__AVMREGCLK_FORCE_ON_MASK: c_uint = 0x00000100L;
pub const VCE_UENC_REG_CLOCK_GATING__DCAPREGCLK_FORCE_ON_MASK: c_uint = 0x00000200L;
pub const VCE_UENC_REG_CLOCK_GATING__VEPREGCLK_FORCE_ON_MASK: c_uint = 0x00000400L;
// VCE_UENC_CLOCK_GATING_2
pub const VCE_UENC_CLOCK_GATING_2__DBF2CLK_FORCE_ON__SHIFT: c_uint = 0x1;
pub const VCE_UENC_CLOCK_GATING_2__DBF2CLK_FORCE_OFF__SHIFT: c_uint = 0x10;
pub const VCE_UENC_CLOCK_GATING_2__DBF2CLK_FORCE_ON_MASK: c_uint = 0x00000002L;
pub const VCE_UENC_CLOCK_GATING_2__DBF2CLK_FORCE_OFF_MASK: c_uint = 0x00010000L;
// addressBlock: vce0_vce_sclk_dec
// VCE_LMI_VCPU_CACHE_40BIT_BAR
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR__BAR_MASK: c_uint = 0xFFFFFFFFL;
// VCE_LMI_CTRL2
pub const VCE_LMI_CTRL2__STALL_ARB__SHIFT: c_uint = 0x1;
pub const VCE_LMI_CTRL2__ASSERT_UMC_URGENT__SHIFT: c_uint = 0x2;
pub const VCE_LMI_CTRL2__MASK_UMC_URGENT__SHIFT: c_uint = 0x3;
pub const VCE_LMI_CTRL2__STALL_ARB_UMC__SHIFT: c_uint = 0x8;
pub const VCE_LMI_CTRL2__STALL_ARB_MASK: c_uint = 0x00000002L;
pub const VCE_LMI_CTRL2__ASSERT_UMC_URGENT_MASK: c_uint = 0x00000004L;
pub const VCE_LMI_CTRL2__MASK_UMC_URGENT_MASK: c_uint = 0x00000008L;
pub const VCE_LMI_CTRL2__STALL_ARB_UMC_MASK: c_uint = 0x00000100L;
// VCE_LMI_SWAP_CNTL3
pub const VCE_LMI_SWAP_CNTL3__RD_MC_CID_SWAP__SHIFT: c_uint = 0x0;
pub const VCE_LMI_SWAP_CNTL3__RD_MC_CID_TRAN__SHIFT: c_uint = 0x14;
pub const VCE_LMI_SWAP_CNTL3__RD_MC_CID_URG__SHIFT: c_uint = 0x1a;
pub const VCE_LMI_SWAP_CNTL3__RD_MC_CID_SWAP_MASK: c_uint = 0x00000003L;
pub const VCE_LMI_SWAP_CNTL3__RD_MC_CID_TRAN_MASK: c_uint = 0x00100000L;
pub const VCE_LMI_SWAP_CNTL3__RD_MC_CID_URG_MASK: c_uint = 0x04000000L;
// VCE_LMI_CTRL
pub const VCE_LMI_CTRL__ASSERT_MC_URGENT__SHIFT: c_uint = 0xb;
pub const VCE_LMI_CTRL__MASK_MC_URGENT__SHIFT: c_uint = 0xc;
pub const VCE_LMI_CTRL__DATA_COHERENCY_EN__SHIFT: c_uint = 0xd;
pub const VCE_LMI_CTRL__VCPU_DATA_COHERENCY_EN__SHIFT: c_uint = 0x15;
pub const VCE_LMI_CTRL__MIF_DATA_COHERENCY_EN__SHIFT: c_uint = 0x16;
pub const VCE_LMI_CTRL__VCPU_RD_CACHE_MISS_COUNT_EN__SHIFT: c_uint = 0x17;
pub const VCE_LMI_CTRL__VCPU_RD_CACHE_MISS_COUNT_RESET__SHIFT: c_uint = 0x18;
pub const VCE_LMI_CTRL__ASSERT_MC_URGENT_MASK: c_uint = 0x00000800L;
pub const VCE_LMI_CTRL__MASK_MC_URGENT_MASK: c_uint = 0x00001000L;
pub const VCE_LMI_CTRL__DATA_COHERENCY_EN_MASK: c_uint = 0x00002000L;
pub const VCE_LMI_CTRL__VCPU_DATA_COHERENCY_EN_MASK: c_uint = 0x00200000L;
pub const VCE_LMI_CTRL__MIF_DATA_COHERENCY_EN_MASK: c_uint = 0x00400000L;
pub const VCE_LMI_CTRL__VCPU_RD_CACHE_MISS_COUNT_EN_MASK: c_uint = 0x00800000L;
pub const VCE_LMI_CTRL__VCPU_RD_CACHE_MISS_COUNT_RESET_MASK: c_uint = 0x01000000L;
// VCE_LMI_SWAP_CNTL
pub const VCE_LMI_SWAP_CNTL__VCPU_W_MC_SWAP__SHIFT: c_uint = 0x0;
pub const VCE_LMI_SWAP_CNTL__WR_MC_CID_SWAP__SHIFT: c_uint = 0x2;
pub const VCE_LMI_SWAP_CNTL__WR_MC_CID_TRAN__SHIFT: c_uint = 0x14;
pub const VCE_LMI_SWAP_CNTL__WR_MC_CID_URG__SHIFT: c_uint = 0x1a;
pub const VCE_LMI_SWAP_CNTL__VCPU_W_MC_SWAP_MASK: c_uint = 0x00000003L;
pub const VCE_LMI_SWAP_CNTL__WR_MC_CID_SWAP_MASK: c_uint = 0x00003FFCL;
pub const VCE_LMI_SWAP_CNTL__WR_MC_CID_TRAN_MASK: c_uint = 0x03F00000L;
pub const VCE_LMI_SWAP_CNTL__WR_MC_CID_URG_MASK: c_uint = 0xFC000000L;
// VCE_LMI_SWAP_CNTL1
pub const VCE_LMI_SWAP_CNTL1__VCPU_R_MC_SWAP__SHIFT: c_uint = 0x0;
pub const VCE_LMI_SWAP_CNTL1__RD_MC_CID_SWAP__SHIFT: c_uint = 0x2;
pub const VCE_LMI_SWAP_CNTL1__RD_MC_CID_TRAN__SHIFT: c_uint = 0x14;
pub const VCE_LMI_SWAP_CNTL1__RD_MC_CID_URG__SHIFT: c_uint = 0x1a;
pub const VCE_LMI_SWAP_CNTL1__VCPU_R_MC_SWAP_MASK: c_uint = 0x00000003L;
pub const VCE_LMI_SWAP_CNTL1__RD_MC_CID_SWAP_MASK: c_uint = 0x00003FFCL;
pub const VCE_LMI_SWAP_CNTL1__RD_MC_CID_TRAN_MASK: c_uint = 0x03F00000L;
pub const VCE_LMI_SWAP_CNTL1__RD_MC_CID_URG_MASK: c_uint = 0xFC000000L;
// VCE_LMI_SWAP_CNTL2
pub const VCE_LMI_SWAP_CNTL2__WR_MC_CID_SWAP__SHIFT: c_uint = 0x0;
pub const VCE_LMI_SWAP_CNTL2__WR_MC_CID_TRAN__SHIFT: c_uint = 0x14;
pub const VCE_LMI_SWAP_CNTL2__WR_MC_CID_URG__SHIFT: c_uint = 0x1a;
pub const VCE_LMI_SWAP_CNTL2__WR_MC_CID_SWAP_MASK: c_uint = 0x000000FFL;
pub const VCE_LMI_SWAP_CNTL2__WR_MC_CID_TRAN_MASK: c_uint = 0x00F00000L;
pub const VCE_LMI_SWAP_CNTL2__WR_MC_CID_URG_MASK: c_uint = 0x3C000000L;
// VCE_LMI_CACHE_CTRL
pub const VCE_LMI_CACHE_CTRL__VCPU_EN__SHIFT: c_uint = 0x0;
pub const VCE_LMI_CACHE_CTRL__VCPU_FLUSH__SHIFT: c_uint = 0x1;
pub const VCE_LMI_CACHE_CTRL__VCPU_EN_MASK: c_uint = 0x00000001L;
pub const VCE_LMI_CACHE_CTRL__VCPU_FLUSH_MASK: c_uint = 0x00000002L;
// VCE_LMI_VCPU_CACHE_64BIT_BAR0
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR0__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR0__BAR_MASK: c_uint = 0x000000FFL;
// VCE_LMI_VCPU_CACHE_64BIT_BAR1
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR1__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR1__BAR_MASK: c_uint = 0x000000FFL;
// VCE_LMI_VCPU_CACHE_64BIT_BAR2
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR2__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR2__BAR_MASK: c_uint = 0x000000FFL;
// VCE_LMI_VCPU_CACHE_64BIT_BAR3
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR3__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR3__BAR_MASK: c_uint = 0x000000FFL;
// VCE_LMI_VCPU_CACHE_64BIT_BAR4
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR4__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR4__BAR_MASK: c_uint = 0x000000FFL;
// VCE_LMI_VCPU_CACHE_64BIT_BAR5
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR5__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR5__BAR_MASK: c_uint = 0x000000FFL;
// VCE_LMI_VCPU_CACHE_64BIT_BAR6
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR6__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR6__BAR_MASK: c_uint = 0x000000FFL;
// VCE_LMI_VCPU_CACHE_64BIT_BAR7
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR7__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_64BIT_BAR7__BAR_MASK: c_uint = 0x000000FFL;
// VCE_LMI_VCPU_CACHE_40BIT_BAR0
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR0__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR0__BAR_MASK: c_uint = 0xFFFFFFFFL;
// VCE_LMI_VCPU_CACHE_40BIT_BAR1
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR1__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR1__BAR_MASK: c_uint = 0xFFFFFFFFL;
// VCE_LMI_VCPU_CACHE_40BIT_BAR2
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR2__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR2__BAR_MASK: c_uint = 0xFFFFFFFFL;
// VCE_LMI_VCPU_CACHE_40BIT_BAR3
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR3__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR3__BAR_MASK: c_uint = 0xFFFFFFFFL;
// VCE_LMI_VCPU_CACHE_40BIT_BAR4
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR4__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR4__BAR_MASK: c_uint = 0xFFFFFFFFL;
// VCE_LMI_VCPU_CACHE_40BIT_BAR5
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR5__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR5__BAR_MASK: c_uint = 0xFFFFFFFFL;
// VCE_LMI_VCPU_CACHE_40BIT_BAR6
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR6__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR6__BAR_MASK: c_uint = 0xFFFFFFFFL;
// VCE_LMI_VCPU_CACHE_40BIT_BAR7
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR7__BAR__SHIFT: c_uint = 0x0;
pub const VCE_LMI_VCPU_CACHE_40BIT_BAR7__BAR_MASK: c_uint = 0xFFFFFFFFL;
// addressBlock: vce0_mmsch_dec
// VCE_MMSCH_VF_VMID
pub const VCE_MMSCH_VF_VMID__VF_CTX_VMID__SHIFT: c_uint = 0x0;
pub const VCE_MMSCH_VF_VMID__VF_GPCOM_VMID__SHIFT: c_uint = 0x4;
pub const VCE_MMSCH_VF_VMID__VF_CTX_VMID_MASK: c_uint = 0x0000000FL;
pub const VCE_MMSCH_VF_VMID__VF_GPCOM_VMID_MASK: c_uint = 0x000000F0L;
// VCE_MMSCH_VF_CTX_ADDR_LO
pub const VCE_MMSCH_VF_CTX_ADDR_LO__VF_CTX_ADDR_LO__SHIFT: c_uint = 0x6;
pub const VCE_MMSCH_VF_CTX_ADDR_LO__VF_CTX_ADDR_LO_MASK: c_uint = 0xFFFFFFC0L;
// VCE_MMSCH_VF_CTX_ADDR_HI
pub const VCE_MMSCH_VF_CTX_ADDR_HI__VF_CTX_ADDR_HI__SHIFT: c_uint = 0x0;
pub const VCE_MMSCH_VF_CTX_ADDR_HI__VF_CTX_ADDR_HI_MASK: c_uint = 0xFFFFFFFFL;
// VCE_MMSCH_VF_CTX_SIZE
pub const VCE_MMSCH_VF_CTX_SIZE__VF_CTX_SIZE__SHIFT: c_uint = 0x0;
pub const VCE_MMSCH_VF_CTX_SIZE__VF_CTX_SIZE_MASK: c_uint = 0xFFFFFFFFL;
// VCE_MMSCH_VF_GPCOM_ADDR_LO
pub const VCE_MMSCH_VF_GPCOM_ADDR_LO__VF_GPCOM_ADDR_LO__SHIFT: c_uint = 0x6;
pub const VCE_MMSCH_VF_GPCOM_ADDR_LO__VF_GPCOM_ADDR_LO_MASK: c_uint = 0xFFFFFFC0L;
// VCE_MMSCH_VF_GPCOM_ADDR_HI
pub const VCE_MMSCH_VF_GPCOM_ADDR_HI__VF_GPCOM_ADDR_HI__SHIFT: c_uint = 0x0;
pub const VCE_MMSCH_VF_GPCOM_ADDR_HI__VF_GPCOM_ADDR_HI_MASK: c_uint = 0xFFFFFFFFL;
// VCE_MMSCH_VF_GPCOM_SIZE
pub const VCE_MMSCH_VF_GPCOM_SIZE__VF_GPCOM_SIZE__SHIFT: c_uint = 0x0;
pub const VCE_MMSCH_VF_GPCOM_SIZE__VF_GPCOM_SIZE_MASK: c_uint = 0xFFFFFFFFL;
// VCE_MMSCH_VF_MAILBOX_HOST
pub const VCE_MMSCH_VF_MAILBOX_HOST__DATA__SHIFT: c_uint = 0x0;
pub const VCE_MMSCH_VF_MAILBOX_HOST__DATA_MASK: c_uint = 0xFFFFFFFFL;
// VCE_MMSCH_VF_MAILBOX_RESP
pub const VCE_MMSCH_VF_MAILBOX_RESP__RESP__SHIFT: c_uint = 0x0;
pub const VCE_MMSCH_VF_MAILBOX_RESP__RESP_MASK: c_uint = 0xFFFFFFFFL;
// addressBlock: vce0_vce_rb_pg_dec
// VCE_HW_VERSION
pub const VCE_HW_VERSION__VCE_VERSION__SHIFT: c_uint = 0x0;
pub const VCE_HW_VERSION__VCE_CONFIGURATION__SHIFT: c_uint = 0x8;
pub const VCE_HW_VERSION__VCE_INSTANCE_ID__SHIFT: c_uint = 0xa;
pub const VCE_HW_VERSION__VCE_VERSION_MASK: c_uint = 0x000000FFL;
pub const VCE_HW_VERSION__VCE_CONFIGURATION_MASK: c_uint = 0x00000300L;
pub const VCE_HW_VERSION__VCE_INSTANCE_ID_MASK: c_uint = 0x00000C00L;
