//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/etnaviv/cmdstream.xml.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// Macro flag: #define CMDSTREAM_XML
// Autogenerated file, DO NOT EDIT manually!
//
pub const FE_OPCODE_LOAD_STATE: c_uint = 0x00000001;
pub const FE_OPCODE_END: c_uint = 0x00000002;
pub const FE_OPCODE_NOP: c_uint = 0x00000003;
pub const FE_OPCODE_DRAW_2D: c_uint = 0x00000004;
pub const FE_OPCODE_DRAW_PRIMITIVES: c_uint = 0x00000005;
pub const FE_OPCODE_DRAW_INDEXED_PRIMITIVES: c_uint = 0x00000006;
pub const FE_OPCODE_WAIT: c_uint = 0x00000007;
pub const FE_OPCODE_LINK: c_uint = 0x00000008;
pub const FE_OPCODE_STALL: c_uint = 0x00000009;
pub const FE_OPCODE_CALL: c_uint = 0x0000000a;
pub const FE_OPCODE_RETURN: c_uint = 0x0000000b;
pub const FE_OPCODE_DRAW_INSTANCED: c_uint = 0x0000000c;
pub const FE_OPCODE_CHIP_SELECT: c_uint = 0x0000000d;
pub const FE_OPCODE_WAIT_FENCE: c_uint = 0x0000000f;
pub const FE_OPCODE_DRAW_INDIRECT: c_uint = 0x00000010;
pub const FE_OPCODE_SNAP_PAGES: c_uint = 0x00000013;
pub const PRIMITIVE_TYPE_POINTS: c_uint = 0x00000001;
pub const PRIMITIVE_TYPE_LINES: c_uint = 0x00000002;
pub const PRIMITIVE_TYPE_LINE_STRIP: c_uint = 0x00000003;
pub const PRIMITIVE_TYPE_TRIANGLES: c_uint = 0x00000004;
pub const PRIMITIVE_TYPE_TRIANGLE_STRIP: c_uint = 0x00000005;
pub const PRIMITIVE_TYPE_TRIANGLE_FAN: c_uint = 0x00000006;
pub const PRIMITIVE_TYPE_LINE_LOOP: c_uint = 0x00000007;
pub const PRIMITIVE_TYPE_QUADS: c_uint = 0x00000008;
pub const VIV_FE_LOAD_STATE: c_uint = 0x00000000;
pub const VIV_FE_LOAD_STATE_HEADER: c_uint = 0x00000000;
pub const VIV_FE_LOAD_STATE_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_LOAD_STATE_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_LOAD_STATE_HEADER_OP_LOAD_STATE: c_uint = 0x08000000;
pub const VIV_FE_LOAD_STATE_HEADER_FIXP: c_uint = 0x04000000;
pub const VIV_FE_LOAD_STATE_HEADER_COUNT__MASK: c_uint = 0x03ff0000;
pub const VIV_FE_LOAD_STATE_HEADER_COUNT__SHIFT: c_int = 16;

pub const VIV_FE_LOAD_STATE_HEADER_OFFSET__MASK: c_uint = 0x0000ffff;
pub const VIV_FE_LOAD_STATE_HEADER_OFFSET__SHIFT: c_int = 0;

pub const VIV_FE_LOAD_STATE_HEADER_OFFSET__SHR: c_int = 2;
pub const VIV_FE_END: c_uint = 0x00000000;
pub const VIV_FE_END_HEADER: c_uint = 0x00000000;
pub const VIV_FE_END_HEADER_EVENT_ID__MASK: c_uint = 0x0000001f;
pub const VIV_FE_END_HEADER_EVENT_ID__SHIFT: c_int = 0;

pub const VIV_FE_END_HEADER_EVENT_ENABLE: c_uint = 0x00000100;
pub const VIV_FE_END_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_END_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_END_HEADER_OP_END: c_uint = 0x10000000;
pub const VIV_FE_NOP: c_uint = 0x00000000;
pub const VIV_FE_NOP_HEADER: c_uint = 0x00000000;
pub const VIV_FE_NOP_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_NOP_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_NOP_HEADER_OP_NOP: c_uint = 0x18000000;
pub const VIV_FE_DRAW_2D: c_uint = 0x00000000;
pub const VIV_FE_DRAW_2D_HEADER: c_uint = 0x00000000;
pub const VIV_FE_DRAW_2D_HEADER_COUNT__MASK: c_uint = 0x0000ff00;
pub const VIV_FE_DRAW_2D_HEADER_COUNT__SHIFT: c_int = 8;

pub const VIV_FE_DRAW_2D_HEADER_DATA_COUNT__MASK: c_uint = 0x07ff0000;
pub const VIV_FE_DRAW_2D_HEADER_DATA_COUNT__SHIFT: c_int = 16;

pub const VIV_FE_DRAW_2D_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_DRAW_2D_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_DRAW_2D_HEADER_OP_DRAW_2D: c_uint = 0x20000000;
pub const VIV_FE_DRAW_2D_TOP_LEFT: c_uint = 0x00000008;
pub const VIV_FE_DRAW_2D_TOP_LEFT_X__MASK: c_uint = 0x0000ffff;
pub const VIV_FE_DRAW_2D_TOP_LEFT_X__SHIFT: c_int = 0;

pub const VIV_FE_DRAW_2D_TOP_LEFT_Y__MASK: c_uint = 0xffff0000;
pub const VIV_FE_DRAW_2D_TOP_LEFT_Y__SHIFT: c_int = 16;

pub const VIV_FE_DRAW_2D_BOTTOM_RIGHT: c_uint = 0x0000000c;
pub const VIV_FE_DRAW_2D_BOTTOM_RIGHT_X__MASK: c_uint = 0x0000ffff;
pub const VIV_FE_DRAW_2D_BOTTOM_RIGHT_X__SHIFT: c_int = 0;

pub const VIV_FE_DRAW_2D_BOTTOM_RIGHT_Y__MASK: c_uint = 0xffff0000;
pub const VIV_FE_DRAW_2D_BOTTOM_RIGHT_Y__SHIFT: c_int = 16;

pub const VIV_FE_DRAW_PRIMITIVES: c_uint = 0x00000000;
pub const VIV_FE_DRAW_PRIMITIVES_HEADER: c_uint = 0x00000000;
pub const VIV_FE_DRAW_PRIMITIVES_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_DRAW_PRIMITIVES_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_DRAW_PRIMITIVES_HEADER_OP_DRAW_PRIMITIVES: c_uint = 0x28000000;
pub const VIV_FE_DRAW_PRIMITIVES_COMMAND: c_uint = 0x00000004;
pub const VIV_FE_DRAW_PRIMITIVES_COMMAND_TYPE__MASK: c_uint = 0x000000ff;
pub const VIV_FE_DRAW_PRIMITIVES_COMMAND_TYPE__SHIFT: c_int = 0;

pub const VIV_FE_DRAW_PRIMITIVES_START: c_uint = 0x00000008;
pub const VIV_FE_DRAW_PRIMITIVES_COUNT: c_uint = 0x0000000c;
pub const VIV_FE_DRAW_INDEXED_PRIMITIVES: c_uint = 0x00000000;
pub const VIV_FE_DRAW_INDEXED_PRIMITIVES_HEADER: c_uint = 0x00000000;
pub const VIV_FE_DRAW_INDEXED_PRIMITIVES_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_DRAW_INDEXED_PRIMITIVES_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_DRAW_INDEXED_PRIMITIVES_HEADER_OP_DRAW_INDEXED_PRIMITIVES: c_uint = 0x30000000;
pub const VIV_FE_DRAW_INDEXED_PRIMITIVES_COMMAND: c_uint = 0x00000004;
pub const VIV_FE_DRAW_INDEXED_PRIMITIVES_COMMAND_TYPE__MASK: c_uint = 0x000000ff;
pub const VIV_FE_DRAW_INDEXED_PRIMITIVES_COMMAND_TYPE__SHIFT: c_int = 0;

pub const VIV_FE_DRAW_INDEXED_PRIMITIVES_START: c_uint = 0x00000008;
pub const VIV_FE_DRAW_INDEXED_PRIMITIVES_COUNT: c_uint = 0x0000000c;
pub const VIV_FE_DRAW_INDEXED_PRIMITIVES_OFFSET: c_uint = 0x00000010;
pub const VIV_FE_WAIT: c_uint = 0x00000000;
pub const VIV_FE_WAIT_HEADER: c_uint = 0x00000000;
pub const VIV_FE_WAIT_HEADER_DELAY__MASK: c_uint = 0x0000ffff;
pub const VIV_FE_WAIT_HEADER_DELAY__SHIFT: c_int = 0;

pub const VIV_FE_WAIT_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_WAIT_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_WAIT_HEADER_OP_WAIT: c_uint = 0x38000000;
pub const VIV_FE_LINK: c_uint = 0x00000000;
pub const VIV_FE_LINK_HEADER: c_uint = 0x00000000;
pub const VIV_FE_LINK_HEADER_PREFETCH__MASK: c_uint = 0x0000ffff;
pub const VIV_FE_LINK_HEADER_PREFETCH__SHIFT: c_int = 0;

pub const VIV_FE_LINK_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_LINK_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_LINK_HEADER_OP_LINK: c_uint = 0x40000000;
pub const VIV_FE_LINK_ADDRESS: c_uint = 0x00000004;
pub const VIV_FE_STALL: c_uint = 0x00000000;
pub const VIV_FE_STALL_HEADER: c_uint = 0x00000000;
pub const VIV_FE_STALL_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_STALL_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_STALL_HEADER_OP_STALL: c_uint = 0x48000000;
pub const VIV_FE_STALL_TOKEN: c_uint = 0x00000004;
pub const VIV_FE_STALL_TOKEN_FROM__MASK: c_uint = 0x0000001f;
pub const VIV_FE_STALL_TOKEN_FROM__SHIFT: c_int = 0;

pub const VIV_FE_STALL_TOKEN_TO__MASK: c_uint = 0x00001f00;
pub const VIV_FE_STALL_TOKEN_TO__SHIFT: c_int = 8;

pub const VIV_FE_STALL_TOKEN_UNK28__MASK: c_uint = 0x30000000;
pub const VIV_FE_STALL_TOKEN_UNK28__SHIFT: c_int = 28;

pub const VIV_FE_CALL: c_uint = 0x00000000;
pub const VIV_FE_CALL_HEADER: c_uint = 0x00000000;
pub const VIV_FE_CALL_HEADER_PREFETCH__MASK: c_uint = 0x0000ffff;
pub const VIV_FE_CALL_HEADER_PREFETCH__SHIFT: c_int = 0;

pub const VIV_FE_CALL_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_CALL_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_CALL_HEADER_OP_CALL: c_uint = 0x50000000;
pub const VIV_FE_CALL_ADDRESS: c_uint = 0x00000004;
pub const VIV_FE_CALL_RETURN_PREFETCH: c_uint = 0x00000008;
pub const VIV_FE_CALL_RETURN_ADDRESS: c_uint = 0x0000000c;
pub const VIV_FE_RETURN: c_uint = 0x00000000;
pub const VIV_FE_RETURN_HEADER: c_uint = 0x00000000;
pub const VIV_FE_RETURN_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_RETURN_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_RETURN_HEADER_OP_RETURN: c_uint = 0x58000000;
pub const VIV_FE_CHIP_SELECT: c_uint = 0x00000000;
pub const VIV_FE_CHIP_SELECT_HEADER: c_uint = 0x00000000;
pub const VIV_FE_CHIP_SELECT_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_CHIP_SELECT_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_CHIP_SELECT_HEADER_OP_CHIP_SELECT: c_uint = 0x68000000;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP15: c_uint = 0x00008000;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP14: c_uint = 0x00004000;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP13: c_uint = 0x00002000;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP12: c_uint = 0x00001000;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP11: c_uint = 0x00000800;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP10: c_uint = 0x00000400;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP9: c_uint = 0x00000200;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP8: c_uint = 0x00000100;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP7: c_uint = 0x00000080;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP6: c_uint = 0x00000040;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP5: c_uint = 0x00000020;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP4: c_uint = 0x00000010;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP3: c_uint = 0x00000008;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP2: c_uint = 0x00000004;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP1: c_uint = 0x00000002;
pub const VIV_FE_CHIP_SELECT_HEADER_ENABLE_CHIP0: c_uint = 0x00000001;
pub const VIV_FE_DRAW_INSTANCED: c_uint = 0x00000000;
pub const VIV_FE_DRAW_INSTANCED_HEADER: c_uint = 0x00000000;
pub const VIV_FE_DRAW_INSTANCED_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_DRAW_INSTANCED_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_DRAW_INSTANCED_HEADER_OP_DRAW_INSTANCED: c_uint = 0x60000000;
pub const VIV_FE_DRAW_INSTANCED_HEADER_INDEXED: c_uint = 0x00100000;
pub const VIV_FE_DRAW_INSTANCED_HEADER_TYPE__MASK: c_uint = 0x000f0000;
pub const VIV_FE_DRAW_INSTANCED_HEADER_TYPE__SHIFT: c_int = 16;

pub const VIV_FE_DRAW_INSTANCED_HEADER_INSTANCE_COUNT_LO__MASK: c_uint = 0x0000ffff;
pub const VIV_FE_DRAW_INSTANCED_HEADER_INSTANCE_COUNT_LO__SHIFT: c_int = 0;

pub const VIV_FE_DRAW_INSTANCED_COUNT: c_uint = 0x00000004;
pub const VIV_FE_DRAW_INSTANCED_COUNT_INSTANCE_COUNT_HI__MASK: c_uint = 0xff000000;
pub const VIV_FE_DRAW_INSTANCED_COUNT_INSTANCE_COUNT_HI__SHIFT: c_int = 24;

pub const VIV_FE_DRAW_INSTANCED_COUNT_VERTEX_COUNT__MASK: c_uint = 0x00ffffff;
pub const VIV_FE_DRAW_INSTANCED_COUNT_VERTEX_COUNT__SHIFT: c_int = 0;

pub const VIV_FE_DRAW_INSTANCED_START: c_uint = 0x00000008;
pub const VIV_FE_DRAW_INSTANCED_START_INDEX__MASK: c_uint = 0xffffffff;
pub const VIV_FE_DRAW_INSTANCED_START_INDEX__SHIFT: c_int = 0;

pub const VIV_FE_WAIT_FENCE: c_uint = 0x00000000;
pub const VIV_FE_WAIT_FENCE_HEADER: c_uint = 0x00000000;
pub const VIV_FE_WAIT_FENCE_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_WAIT_FENCE_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_WAIT_FENCE_HEADER_OP_WAIT_FENCE: c_uint = 0x78000000;
pub const VIV_FE_WAIT_FENCE_HEADER_UNK16__MASK: c_uint = 0x00030000;
pub const VIV_FE_WAIT_FENCE_HEADER_UNK16__SHIFT: c_int = 16;

pub const VIV_FE_WAIT_FENCE_HEADER_WAITCOUNT__MASK: c_uint = 0x0000ffff;
pub const VIV_FE_WAIT_FENCE_HEADER_WAITCOUNT__SHIFT: c_int = 0;

pub const VIV_FE_WAIT_FENCE_ADDRESS: c_uint = 0x00000004;
pub const VIV_FE_DRAW_INDIRECT: c_uint = 0x00000000;
pub const VIV_FE_DRAW_INDIRECT_HEADER: c_uint = 0x00000000;
pub const VIV_FE_DRAW_INDIRECT_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_DRAW_INDIRECT_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_DRAW_INDIRECT_HEADER_OP_DRAW_INDIRECT: c_uint = 0x80000000;
pub const VIV_FE_DRAW_INDIRECT_HEADER_INDEXED: c_uint = 0x00000100;
pub const VIV_FE_DRAW_INDIRECT_HEADER_TYPE__MASK: c_uint = 0x0000000f;
pub const VIV_FE_DRAW_INDIRECT_HEADER_TYPE__SHIFT: c_int = 0;

pub const VIV_FE_DRAW_INDIRECT_ADDRESS: c_uint = 0x00000004;
pub const VIV_FE_SNAP_PAGES: c_uint = 0x00000000;
pub const VIV_FE_SNAP_PAGES_HEADER: c_uint = 0x00000000;
pub const VIV_FE_SNAP_PAGES_HEADER_OP__MASK: c_uint = 0xf8000000;
pub const VIV_FE_SNAP_PAGES_HEADER_OP__SHIFT: c_int = 27;
pub const VIV_FE_SNAP_PAGES_HEADER_OP_SNAP_PAGES: c_uint = 0x98000000;
pub const VIV_FE_SNAP_PAGES_HEADER_UNK0__MASK: c_uint = 0x0000001f;
pub const VIV_FE_SNAP_PAGES_HEADER_UNK0__SHIFT: c_int = 0;

