//! Automatically rewritten from C Header to Rust Module
//! Source: include/dt-bindings/clock/qcom,mmcc-apq8084.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0-only
//
// Copyright (c) 2014, The Linux Foundation. All rights reserved.
//
pub const MMSS_AHB_CLK_SRC: c_int = 0;
pub const MMSS_AXI_CLK_SRC: c_int = 1;
pub const MMPLL0: c_int = 2;
pub const MMPLL0_VOTE: c_int = 3;
pub const MMPLL1: c_int = 4;
pub const MMPLL1_VOTE: c_int = 5;
pub const MMPLL2: c_int = 6;
pub const MMPLL3: c_int = 7;
pub const MMPLL4: c_int = 8;
pub const CSI0_CLK_SRC: c_int = 9;
pub const CSI1_CLK_SRC: c_int = 10;
pub const CSI2_CLK_SRC: c_int = 11;
pub const CSI3_CLK_SRC: c_int = 12;
pub const VCODEC0_CLK_SRC: c_int = 13;
pub const VFE0_CLK_SRC: c_int = 14;
pub const VFE1_CLK_SRC: c_int = 15;
pub const MDP_CLK_SRC: c_int = 16;
pub const PCLK0_CLK_SRC: c_int = 17;
pub const PCLK1_CLK_SRC: c_int = 18;
pub const OCMEMNOC_CLK_SRC: c_int = 19;
pub const GFX3D_CLK_SRC: c_int = 20;
pub const JPEG0_CLK_SRC: c_int = 21;
pub const JPEG1_CLK_SRC: c_int = 22;
pub const JPEG2_CLK_SRC: c_int = 23;
pub const EDPPIXEL_CLK_SRC: c_int = 24;
pub const EXTPCLK_CLK_SRC: c_int = 25;
pub const VP_CLK_SRC: c_int = 26;
pub const CCI_CLK_SRC: c_int = 27;
pub const CAMSS_GP0_CLK_SRC: c_int = 28;
pub const CAMSS_GP1_CLK_SRC: c_int = 29;
pub const MCLK0_CLK_SRC: c_int = 30;
pub const MCLK1_CLK_SRC: c_int = 31;
pub const MCLK2_CLK_SRC: c_int = 32;
pub const MCLK3_CLK_SRC: c_int = 33;
pub const CSI0PHYTIMER_CLK_SRC: c_int = 34;
pub const CSI1PHYTIMER_CLK_SRC: c_int = 35;
pub const CSI2PHYTIMER_CLK_SRC: c_int = 36;
pub const CPP_CLK_SRC: c_int = 37;
pub const BYTE0_CLK_SRC: c_int = 38;
pub const BYTE1_CLK_SRC: c_int = 39;
pub const EDPAUX_CLK_SRC: c_int = 40;
pub const EDPLINK_CLK_SRC: c_int = 41;
pub const ESC0_CLK_SRC: c_int = 42;
pub const ESC1_CLK_SRC: c_int = 43;
pub const HDMI_CLK_SRC: c_int = 44;
pub const VSYNC_CLK_SRC: c_int = 45;
pub const MMSS_RBCPR_CLK_SRC: c_int = 46;
pub const RBBMTIMER_CLK_SRC: c_int = 47;
pub const MAPLE_CLK_SRC: c_int = 48;
pub const VDP_CLK_SRC: c_int = 49;
pub const VPU_BUS_CLK_SRC: c_int = 50;
pub const MMSS_CXO_CLK: c_int = 51;
pub const MMSS_SLEEPCLK_CLK: c_int = 52;
pub const AVSYNC_AHB_CLK: c_int = 53;
pub const AVSYNC_EDPPIXEL_CLK: c_int = 54;
pub const AVSYNC_EXTPCLK_CLK: c_int = 55;
pub const AVSYNC_PCLK0_CLK: c_int = 56;
pub const AVSYNC_PCLK1_CLK: c_int = 57;
pub const AVSYNC_VP_CLK: c_int = 58;
pub const CAMSS_AHB_CLK: c_int = 59;
pub const CAMSS_CCI_CCI_AHB_CLK: c_int = 60;
pub const CAMSS_CCI_CCI_CLK: c_int = 61;
pub const CAMSS_CSI0_AHB_CLK: c_int = 62;
pub const CAMSS_CSI0_CLK: c_int = 63;
pub const CAMSS_CSI0PHY_CLK: c_int = 64;
pub const CAMSS_CSI0PIX_CLK: c_int = 65;
pub const CAMSS_CSI0RDI_CLK: c_int = 66;
pub const CAMSS_CSI1_AHB_CLK: c_int = 67;
pub const CAMSS_CSI1_CLK: c_int = 68;
pub const CAMSS_CSI1PHY_CLK: c_int = 69;
pub const CAMSS_CSI1PIX_CLK: c_int = 70;
pub const CAMSS_CSI1RDI_CLK: c_int = 71;
pub const CAMSS_CSI2_AHB_CLK: c_int = 72;
pub const CAMSS_CSI2_CLK: c_int = 73;
pub const CAMSS_CSI2PHY_CLK: c_int = 74;
pub const CAMSS_CSI2PIX_CLK: c_int = 75;
pub const CAMSS_CSI2RDI_CLK: c_int = 76;
pub const CAMSS_CSI3_AHB_CLK: c_int = 77;
pub const CAMSS_CSI3_CLK: c_int = 78;
pub const CAMSS_CSI3PHY_CLK: c_int = 79;
pub const CAMSS_CSI3PIX_CLK: c_int = 80;
pub const CAMSS_CSI3RDI_CLK: c_int = 81;
pub const CAMSS_CSI_VFE0_CLK: c_int = 82;
pub const CAMSS_CSI_VFE1_CLK: c_int = 83;
pub const CAMSS_GP0_CLK: c_int = 84;
pub const CAMSS_GP1_CLK: c_int = 85;
pub const CAMSS_ISPIF_AHB_CLK: c_int = 86;
pub const CAMSS_JPEG_JPEG0_CLK: c_int = 87;
pub const CAMSS_JPEG_JPEG1_CLK: c_int = 88;
pub const CAMSS_JPEG_JPEG2_CLK: c_int = 89;
pub const CAMSS_JPEG_JPEG_AHB_CLK: c_int = 90;
pub const CAMSS_JPEG_JPEG_AXI_CLK: c_int = 91;
pub const CAMSS_MCLK0_CLK: c_int = 92;
pub const CAMSS_MCLK1_CLK: c_int = 93;
pub const CAMSS_MCLK2_CLK: c_int = 94;
pub const CAMSS_MCLK3_CLK: c_int = 95;
pub const CAMSS_MICRO_AHB_CLK: c_int = 96;
pub const CAMSS_PHY0_CSI0PHYTIMER_CLK: c_int = 97;
pub const CAMSS_PHY1_CSI1PHYTIMER_CLK: c_int = 98;
pub const CAMSS_PHY2_CSI2PHYTIMER_CLK: c_int = 99;
pub const CAMSS_TOP_AHB_CLK: c_int = 100;
pub const CAMSS_VFE_CPP_AHB_CLK: c_int = 101;
pub const CAMSS_VFE_CPP_CLK: c_int = 102;
pub const CAMSS_VFE_VFE0_CLK: c_int = 103;
pub const CAMSS_VFE_VFE1_CLK: c_int = 104;
pub const CAMSS_VFE_VFE_AHB_CLK: c_int = 105;
pub const CAMSS_VFE_VFE_AXI_CLK: c_int = 106;
pub const MDSS_AHB_CLK: c_int = 107;
pub const MDSS_AXI_CLK: c_int = 108;
pub const MDSS_BYTE0_CLK: c_int = 109;
pub const MDSS_BYTE1_CLK: c_int = 110;
pub const MDSS_EDPAUX_CLK: c_int = 111;
pub const MDSS_EDPLINK_CLK: c_int = 112;
pub const MDSS_EDPPIXEL_CLK: c_int = 113;
pub const MDSS_ESC0_CLK: c_int = 114;
pub const MDSS_ESC1_CLK: c_int = 115;
pub const MDSS_EXTPCLK_CLK: c_int = 116;
pub const MDSS_HDMI_AHB_CLK: c_int = 117;
pub const MDSS_HDMI_CLK: c_int = 118;
pub const MDSS_MDP_CLK: c_int = 119;
pub const MDSS_MDP_LUT_CLK: c_int = 120;
pub const MDSS_PCLK0_CLK: c_int = 121;
pub const MDSS_PCLK1_CLK: c_int = 122;
pub const MDSS_VSYNC_CLK: c_int = 123;
pub const MMSS_RBCPR_AHB_CLK: c_int = 124;
pub const MMSS_RBCPR_CLK: c_int = 125;
pub const MMSS_SPDM_AHB_CLK: c_int = 126;
pub const MMSS_SPDM_AXI_CLK: c_int = 127;
pub const MMSS_SPDM_CSI0_CLK: c_int = 128;
pub const MMSS_SPDM_GFX3D_CLK: c_int = 129;
pub const MMSS_SPDM_JPEG0_CLK: c_int = 130;
pub const MMSS_SPDM_JPEG1_CLK: c_int = 131;
pub const MMSS_SPDM_JPEG2_CLK: c_int = 132;
pub const MMSS_SPDM_MDP_CLK: c_int = 133;
pub const MMSS_SPDM_PCLK0_CLK: c_int = 134;
pub const MMSS_SPDM_PCLK1_CLK: c_int = 135;
pub const MMSS_SPDM_VCODEC0_CLK: c_int = 136;
pub const MMSS_SPDM_VFE0_CLK: c_int = 137;
pub const MMSS_SPDM_VFE1_CLK: c_int = 138;
pub const MMSS_SPDM_RM_AXI_CLK: c_int = 139;
pub const MMSS_SPDM_RM_OCMEMNOC_CLK: c_int = 140;
pub const MMSS_MISC_AHB_CLK: c_int = 141;
pub const MMSS_MMSSNOC_AHB_CLK: c_int = 142;
pub const MMSS_MMSSNOC_BTO_AHB_CLK: c_int = 143;
pub const MMSS_MMSSNOC_AXI_CLK: c_int = 144;
pub const MMSS_S0_AXI_CLK: c_int = 145;
pub const OCMEMCX_AHB_CLK: c_int = 146;
pub const OCMEMCX_OCMEMNOC_CLK: c_int = 147;
pub const OXILI_OCMEMGX_CLK: c_int = 148;
pub const OXILI_GFX3D_CLK: c_int = 149;
pub const OXILI_RBBMTIMER_CLK: c_int = 150;
pub const OXILICX_AHB_CLK: c_int = 151;
pub const VENUS0_AHB_CLK: c_int = 152;
pub const VENUS0_AXI_CLK: c_int = 153;
pub const VENUS0_CORE0_VCODEC_CLK: c_int = 154;
pub const VENUS0_CORE1_VCODEC_CLK: c_int = 155;
pub const VENUS0_OCMEMNOC_CLK: c_int = 156;
pub const VENUS0_VCODEC0_CLK: c_int = 157;
pub const VPU_AHB_CLK: c_int = 158;
pub const VPU_AXI_CLK: c_int = 159;
pub const VPU_BUS_CLK: c_int = 160;
pub const VPU_CXO_CLK: c_int = 161;
pub const VPU_MAPLE_CLK: c_int = 162;
pub const VPU_SLEEP_CLK: c_int = 163;
pub const VPU_VDP_CLK: c_int = 164;
// GDSCs
pub const VENUS0_GDSC: c_int = 0;
pub const VENUS0_CORE0_GDSC: c_int = 1;
pub const VENUS0_CORE1_GDSC: c_int = 2;
pub const MDSS_GDSC: c_int = 3;
pub const CAMSS_JPEG_GDSC: c_int = 4;
pub const CAMSS_VFE_GDSC: c_int = 5;
pub const OXILI_GDSC: c_int = 6;
pub const OXILICX_GDSC: c_int = 7;
