//! Automatically rewritten from C Header to Rust Module
//! Source: include/dt-bindings/clock/qcom,gcc-qcs404.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright (c) 2018, The Linux Foundation. All rights reserved.
//
pub const GCC_APSS_AHB_CLK_SRC: c_int = 0;
pub const GCC_BLSP1_QUP0_I2C_APPS_CLK_SRC: c_int = 1;
pub const GCC_BLSP1_QUP0_SPI_APPS_CLK_SRC: c_int = 2;
pub const GCC_BLSP1_QUP1_I2C_APPS_CLK_SRC: c_int = 3;
pub const GCC_BLSP1_QUP1_SPI_APPS_CLK_SRC: c_int = 4;
pub const GCC_BLSP1_QUP2_I2C_APPS_CLK_SRC: c_int = 5;
pub const GCC_BLSP1_QUP2_SPI_APPS_CLK_SRC: c_int = 6;
pub const GCC_BLSP1_QUP3_I2C_APPS_CLK_SRC: c_int = 7;
pub const GCC_BLSP1_QUP3_SPI_APPS_CLK_SRC: c_int = 8;
pub const GCC_BLSP1_QUP4_I2C_APPS_CLK_SRC: c_int = 9;
pub const GCC_BLSP1_QUP4_SPI_APPS_CLK_SRC: c_int = 10;
pub const GCC_BLSP1_UART0_APPS_CLK_SRC: c_int = 11;
pub const GCC_BLSP1_UART1_APPS_CLK_SRC: c_int = 12;
pub const GCC_BLSP1_UART2_APPS_CLK_SRC: c_int = 13;
pub const GCC_BLSP1_UART3_APPS_CLK_SRC: c_int = 14;
pub const GCC_BLSP2_QUP0_I2C_APPS_CLK_SRC: c_int = 15;
pub const GCC_BLSP2_QUP0_SPI_APPS_CLK_SRC: c_int = 16;
pub const GCC_BLSP2_UART0_APPS_CLK_SRC: c_int = 17;
pub const GCC_BYTE0_CLK_SRC: c_int = 18;
pub const GCC_EMAC_CLK_SRC: c_int = 19;
pub const GCC_EMAC_PTP_CLK_SRC: c_int = 20;
pub const GCC_ESC0_CLK_SRC: c_int = 21;
pub const GCC_APSS_AHB_CLK: c_int = 22;
pub const GCC_APSS_AXI_CLK: c_int = 23;
pub const GCC_BIMC_APSS_AXI_CLK: c_int = 24;
pub const GCC_BIMC_GFX_CLK: c_int = 25;
pub const GCC_BIMC_MDSS_CLK: c_int = 26;
pub const GCC_BLSP1_AHB_CLK: c_int = 27;
pub const GCC_BLSP1_QUP0_I2C_APPS_CLK: c_int = 28;
pub const GCC_BLSP1_QUP0_SPI_APPS_CLK: c_int = 29;
pub const GCC_BLSP1_QUP1_I2C_APPS_CLK: c_int = 30;
pub const GCC_BLSP1_QUP1_SPI_APPS_CLK: c_int = 31;
pub const GCC_BLSP1_QUP2_I2C_APPS_CLK: c_int = 32;
pub const GCC_BLSP1_QUP2_SPI_APPS_CLK: c_int = 33;
pub const GCC_BLSP1_QUP3_I2C_APPS_CLK: c_int = 34;
pub const GCC_BLSP1_QUP3_SPI_APPS_CLK: c_int = 35;
pub const GCC_BLSP1_QUP4_I2C_APPS_CLK: c_int = 36;
pub const GCC_BLSP1_QUP4_SPI_APPS_CLK: c_int = 37;
pub const GCC_BLSP1_UART0_APPS_CLK: c_int = 38;
pub const GCC_BLSP1_UART1_APPS_CLK: c_int = 39;
pub const GCC_BLSP1_UART2_APPS_CLK: c_int = 40;
pub const GCC_BLSP1_UART3_APPS_CLK: c_int = 41;
pub const GCC_BLSP2_AHB_CLK: c_int = 42;
pub const GCC_BLSP2_QUP0_I2C_APPS_CLK: c_int = 43;
pub const GCC_BLSP2_QUP0_SPI_APPS_CLK: c_int = 44;
pub const GCC_BLSP2_UART0_APPS_CLK: c_int = 45;
pub const GCC_BOOT_ROM_AHB_CLK: c_int = 46;
pub const GCC_DCC_CLK: c_int = 47;
pub const GCC_GENI_IR_H_CLK: c_int = 48;
pub const GCC_ETH_AXI_CLK: c_int = 49;
pub const GCC_ETH_PTP_CLK: c_int = 50;
pub const GCC_ETH_RGMII_CLK: c_int = 51;
pub const GCC_ETH_SLAVE_AHB_CLK: c_int = 52;
pub const GCC_GENI_IR_S_CLK: c_int = 53;
pub const GCC_GP1_CLK: c_int = 54;
pub const GCC_GP2_CLK: c_int = 55;
pub const GCC_GP3_CLK: c_int = 56;
pub const GCC_MDSS_AHB_CLK: c_int = 57;
pub const GCC_MDSS_AXI_CLK: c_int = 58;
pub const GCC_MDSS_BYTE0_CLK: c_int = 59;
pub const GCC_MDSS_ESC0_CLK: c_int = 60;
pub const GCC_MDSS_HDMI_APP_CLK: c_int = 61;
pub const GCC_MDSS_HDMI_PCLK_CLK: c_int = 62;
pub const GCC_MDSS_MDP_CLK: c_int = 63;
pub const GCC_MDSS_PCLK0_CLK: c_int = 64;
pub const GCC_MDSS_VSYNC_CLK: c_int = 65;
pub const GCC_OXILI_AHB_CLK: c_int = 66;
pub const GCC_OXILI_GFX3D_CLK: c_int = 67;
pub const GCC_PCIE_0_AUX_CLK: c_int = 68;
pub const GCC_PCIE_0_CFG_AHB_CLK: c_int = 69;
pub const GCC_PCIE_0_MSTR_AXI_CLK: c_int = 70;
pub const GCC_PCIE_0_PIPE_CLK: c_int = 71;
pub const GCC_PCIE_0_SLV_AXI_CLK: c_int = 72;
pub const GCC_PCNOC_USB2_CLK: c_int = 73;
pub const GCC_PCNOC_USB3_CLK: c_int = 74;
pub const GCC_PDM2_CLK: c_int = 75;
pub const GCC_PDM_AHB_CLK: c_int = 76;
pub const GCC_VSYNC_CLK_SRC: c_int = 77;
pub const GCC_PRNG_AHB_CLK: c_int = 78;
pub const GCC_PWM0_XO512_CLK: c_int = 79;
pub const GCC_PWM1_XO512_CLK: c_int = 80;
pub const GCC_PWM2_XO512_CLK: c_int = 81;
pub const GCC_SDCC1_AHB_CLK: c_int = 82;
pub const GCC_SDCC1_APPS_CLK: c_int = 83;
pub const GCC_SDCC1_ICE_CORE_CLK: c_int = 84;
pub const GCC_SDCC2_AHB_CLK: c_int = 85;
pub const GCC_SDCC2_APPS_CLK: c_int = 86;
pub const GCC_SYS_NOC_USB3_CLK: c_int = 87;
pub const GCC_USB20_MOCK_UTMI_CLK: c_int = 88;
pub const GCC_USB2A_PHY_SLEEP_CLK: c_int = 89;
pub const GCC_USB30_MASTER_CLK: c_int = 90;
pub const GCC_USB30_MOCK_UTMI_CLK: c_int = 91;
pub const GCC_USB30_SLEEP_CLK: c_int = 92;
pub const GCC_USB3_PHY_AUX_CLK: c_int = 93;
pub const GCC_USB3_PHY_PIPE_CLK: c_int = 94;
pub const GCC_USB_HS_PHY_CFG_AHB_CLK: c_int = 95;
pub const GCC_USB_HS_SYSTEM_CLK: c_int = 96;
pub const GCC_GFX3D_CLK_SRC: c_int = 97;
pub const GCC_GP1_CLK_SRC: c_int = 98;
pub const GCC_GP2_CLK_SRC: c_int = 99;
pub const GCC_GP3_CLK_SRC: c_int = 100;
pub const GCC_GPLL0_OUT_MAIN: c_int = 101;
pub const GCC_GPLL1_OUT_MAIN: c_int = 102;
pub const GCC_GPLL3_OUT_MAIN: c_int = 103;
pub const GCC_GPLL4_OUT_MAIN: c_int = 104;
pub const GCC_HDMI_APP_CLK_SRC: c_int = 105;
pub const GCC_HDMI_PCLK_CLK_SRC: c_int = 106;
pub const GCC_MDP_CLK_SRC: c_int = 107;
pub const GCC_PCIE_0_AUX_CLK_SRC: c_int = 108;
pub const GCC_PCIE_0_PIPE_CLK_SRC: c_int = 109;
pub const GCC_PCLK0_CLK_SRC: c_int = 110;
pub const GCC_PDM2_CLK_SRC: c_int = 111;
pub const GCC_SDCC1_APPS_CLK_SRC: c_int = 112;
pub const GCC_SDCC1_ICE_CORE_CLK_SRC: c_int = 113;
pub const GCC_SDCC2_APPS_CLK_SRC: c_int = 114;
pub const GCC_USB20_MOCK_UTMI_CLK_SRC: c_int = 115;
pub const GCC_USB30_MASTER_CLK_SRC: c_int = 116;
pub const GCC_USB30_MOCK_UTMI_CLK_SRC: c_int = 117;
pub const GCC_USB3_PHY_AUX_CLK_SRC: c_int = 118;
pub const GCC_USB_HS_SYSTEM_CLK_SRC: c_int = 119;
pub const GCC_GPLL0_AO_CLK_SRC: c_int = 120;
pub const GCC_USB_HS_INACTIVITY_TIMERS_CLK: c_int = 122;
pub const GCC_GPLL0_AO_OUT_MAIN: c_int = 123;
pub const GCC_GPLL0_SLEEP_CLK_SRC: c_int = 124;
pub const GCC_GPLL6: c_int = 125;
pub const GCC_GPLL6_OUT_AUX: c_int = 126;
pub const GCC_MDSS_MDP_VOTE_CLK: c_int = 127;
pub const GCC_MDSS_ROTATOR_VOTE_CLK: c_int = 128;
pub const GCC_BIMC_GPU_CLK: c_int = 129;
pub const GCC_GTCU_AHB_CLK: c_int = 130;
pub const GCC_GFX_TCU_CLK: c_int = 131;
pub const GCC_GFX_TBU_CLK: c_int = 132;
pub const GCC_SMMU_CFG_CLK: c_int = 133;
pub const GCC_APSS_TCU_CLK: c_int = 134;
pub const GCC_CRYPTO_AHB_CLK: c_int = 135;
pub const GCC_CRYPTO_AXI_CLK: c_int = 136;
pub const GCC_CRYPTO_CLK: c_int = 137;
pub const GCC_MDP_TBU_CLK: c_int = 138;
pub const GCC_QDSS_DAP_CLK: c_int = 139;
pub const GCC_DCC_XO_CLK: c_int = 140;
pub const GCC_WCSS_Q6_AHB_CLK: c_int = 141;
pub const GCC_WCSS_Q6_AXIM_CLK: c_int = 142;
pub const GCC_CDSP_CFG_AHB_CLK: c_int = 143;
pub const GCC_BIMC_CDSP_CLK: c_int = 144;
pub const GCC_CDSP_TBU_CLK: c_int = 145;
pub const GCC_CDSP_BIMC_CLK_SRC: c_int = 146;
pub const GCC_GENI_IR_BCR: c_int = 0;
pub const GCC_USB_HS_BCR: c_int = 1;
pub const GCC_USB2_HS_PHY_ONLY_BCR: c_int = 2;
pub const GCC_QUSB2_PHY_BCR: c_int = 3;
pub const GCC_USB_HS_PHY_CFG_AHB_BCR: c_int = 4;
pub const GCC_USB2A_PHY_BCR: c_int = 5;
pub const GCC_USB3_PHY_BCR: c_int = 6;
pub const GCC_USB_30_BCR: c_int = 7;
pub const GCC_USB3PHY_PHY_BCR: c_int = 8;
pub const GCC_PCIE_0_BCR: c_int = 9;
pub const GCC_PCIE_0_PHY_BCR: c_int = 10;
pub const GCC_PCIE_0_LINK_DOWN_BCR: c_int = 11;
pub const GCC_PCIEPHY_0_PHY_BCR: c_int = 12;
pub const GCC_EMAC_BCR: c_int = 13;
pub const GCC_CDSP_RESTART: c_int = 14;
pub const GCC_PCIE_0_AXI_MASTER_STICKY_ARES: c_int = 15;
pub const GCC_PCIE_0_AHB_ARES: c_int = 16;
pub const GCC_PCIE_0_AXI_SLAVE_ARES: c_int = 17;
pub const GCC_PCIE_0_AXI_MASTER_ARES: c_int = 18;
pub const GCC_PCIE_0_CORE_STICKY_ARES: c_int = 19;
pub const GCC_PCIE_0_SLEEP_ARES: c_int = 20;
pub const GCC_PCIE_0_PIPE_ARES: c_int = 21;
pub const GCC_WDSP_RESTART: c_int = 22;
// Indexes for GDSCs
pub const MDSS_GDSC: c_int = 0;
pub const OXILI_GDSC: c_int = 1;
