//! Automatically rewritten from C Header to Rust Module
//! Source: fs/crypto/fscrypt_private.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// fscrypt_private.h
//
// Copyright (C) 2015, Google, Inc.
//
// Originally written by Michael Halcrow, Ildar Muslukhov, and Uday Savagaonkar.
// Heavily modified since then.
//

pub const FSCRYPT_FILE_NONCE_SIZE: c_int = 16;
//
// Minimum size of an fscrypt master key.  Note: a longer key will be required
// if ciphers with a 256-bit security strength are used.  This is just the
// absolute minimum, which applies when only 128-bit encryption is used.
//
pub const FSCRYPT_MIN_KEY_SIZE: c_int = 16;
// Maximum size of a raw fscrypt master key
pub const FSCRYPT_MAX_RAW_KEY_SIZE: c_int = 64;
// Maximum size of a hardware-wrapped fscrypt master key

// Maximum size of an fscrypt master key across both key types

//
// FSCRYPT_MAX_KEY_SIZE is defined in the UAPI header, but the addition of
// hardware-wrapped keys has made it misleading as it's only for raw keys.
// Don't use it in kernel code; use one of the above constants instead.
//

//
// This mask is passed as the third argument to the crypto_alloc_*() functions
// to prevent fscrypt from using the Crypto API drivers for non-inline crypto
// engines.  Those drivers have been problematic for fscrypt.  fscrypt users
// have reported hangs and even incorrect en/decryption with these drivers.
// Since going to the driver, off CPU, and back again is really slow, such
// drivers can be over 50 times slower than the CPU-based code for fscrypt's
// workload.  Even on platforms that lack AES instructions on the CPU, using the
// offloads has been shown to be slower, even staying with AES.  (Of course,
// Adiantum is faster still, and is the recommended option on such platforms...)
//
// Note that fscrypt also supports inline crypto engines.  Those don't use the
// Crypto API and work much better than the old-style (non-inline) engines.
//

pub const FSCRYPT_CONTEXT_V1: c_int = 1;
pub const FSCRYPT_CONTEXT_V2: c_int = 2;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fscrypt_context_v1 {
    pub /: *mut *mut u8 version; / FSCRYPT_CONTEXT_V1,
    pub contents_encryption_mode: u8,
    pub filenames_encryption_mode: u8,
    pub flags: u8,
    pub master_key_descriptor: [u8; FSCRYPT_KEY_DESCRIPTOR_SIZE],
    pub nonce: [u8; FSCRYPT_FILE_NONCE_SIZE],
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct fscrypt_context_v2 {
    pub /: *mut *mut u8 version; / FSCRYPT_CONTEXT_V2,
    pub contents_encryption_mode: u8,
    pub filenames_encryption_mode: u8,
    pub flags: u8,
    pub log2_data_unit_size: u8,
    pub __reserved: [u8; 3],
    pub master_key_identifier: [u8; FSCRYPT_KEY_IDENTIFIER_SIZE],
    pub nonce: [u8; FSCRYPT_FILE_NONCE_SIZE],
}

//
// fscrypt_context - the encryption context of an inode
//
// This is the on-disk equivalent of an fscrypt_policy, stored alongside each
// encrypted file usually in a hidden extended attribute.  It contains the
// fields from the fscrypt_policy, in order to identify the encryption algorithm
// and key with which the file is encrypted.  It also contains a nonce that was
// randomly generated by fscrypt itself; this is used as KDF input or as a tweak
// to cause different files to be encrypted differently.
//
#[repr(C)]
#[derive(Copy, Clone)]
pub union fscrypt_context {
    pub version: u8,
    pub v1: fscrypt_context_v1,
    pub v2: fscrypt_context_v2,
}

//
// Return the size expected for the given fscrypt_context based on its version
// number, or 0 if the context version is unrecognized.
//
extern "C" {
    pub fn sizeof(_arg: ctx->v1) -> return;
}
extern "C" {
    pub fn sizeof(_arg: ctx->v2) -> return;
}
// Check whether an fscrypt_context has a recognized version number and size
// Retrieve the context's nonce, assuming the context was already validated
#[repr(C)]
#[derive(Copy, Clone)]
pub union fscrypt_policy {
    pub version: u8,
    pub v1: fscrypt_policy_v1,
    pub v2: fscrypt_policy_v2,
}

//
// Return the size expected for the given fscrypt_policy based on its version
// number, or 0 if the policy version is unrecognized.
//
extern "C" {
    pub fn sizeof(_arg: policy->v1) -> return;
}
extern "C" {
    pub fn sizeof(_arg: policy->v2) -> return;
}
// Return the contents encryption mode of a valid encryption policy
// Return the filenames encryption mode of a valid encryption policy
// Return the flags (FSCRYPT_POLICY_FLAG*) of a valid encryption policy
extern "C" {
    pub fn fscrypt_policy_v2_du_bits(_arg: &policy->v2, _arg: inode) -> return;
}
//
// For encrypted symlinks, the ciphertext length is stored at the beginning
// of the string in little-endian format.
//
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fscrypt_symlink_data {
    pub len: __le16,
    pub encrypted_path: [c_char; ],
    pub __packed: },
//
// struct fscrypt_prepared_key - a key prepared for actual encryption/decryption
// @tfm: crypto API transform object
// @blk_key: key for blk-crypto
//
// Only one of the fields is non-NULL.
//
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fscrypt_prepared_key {
    pub tfm: *mut crypto_sync_skcipher,

    pub blk_key: *mut blk_crypto_key,

}

// An entry in the linked list ->mk_mode_keys
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fscrypt_mode_key {
    pub key: fscrypt_prepared_key,
    pub link: list_head,
    pub hkdf_context: u8,
    pub mode_num: u8,
    pub data_unit_bits: u8,
}

//
// fscrypt_inode_info - the "encryption key" for an inode
//
// When an encrypted file's key is made available, an instance of this struct is
// allocated and a pointer to it is stored in the file's in-memory inode.  Once
// created, it remains until the inode is evicted.
//
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fscrypt_inode_info {
// The key in a form prepared for actual encryption/decryption
    pub ci_enc_key: fscrypt_prepared_key,
// True if ci_enc_key should be freed when this struct is freed
    pub 1: u8 ci_owns_key :,
// True if ci_dirhash_key is initialized
    pub 1: u8 ci_dirhash_key_initialized :,
//
// log2 of the data unit size (granularity of contents encryption) of
// this file.  This is computable from ci_policy and ci_inode but is
// cached here for efficiency.  Only used for regular files.
//
    pub ci_data_unit_bits: u8,
// Hashed inode number.  Only set for IV_INO_LBLK_32
    pub ci_hashed_ino: u32,
//
// Encryption mode used for this inode.  It corresponds to either the
// contents or filenames encryption mode, depending on the inode type.
//
    pub ci_mode: *mut fscrypt_mode,
// Back-pointer to the inode
    pub ci_inode: *mut inode,
//
// The master key with which this inode was unlocked (decrypted).  This
// will be NULL if the master key was found in a process-subscribed
// keyring rather than in the filesystem-level keyring.
//
    pub ci_master_key: *mut fscrypt_master_key,
//
// Link in list of inodes that were unlocked with the master key.
// Only used when ->ci_master_key is set.
//
    pub ci_master_key_link: list_head,
//
// If non-NULL, then encryption is done using the master key directly
// and ci_enc_key will equal ci_direct_key->dk_key.
//
    pub ci_direct_key: *mut fscrypt_direct_key,
//
// This inode's hash key for filenames.  This is a 128-bit SipHash-2-4
// key.  This is only set for directories that use a keyed dirhash over
// the plaintext filenames -- currently just casefolded directories.
//
    pub ci_dirhash_key: siphash_key_t,
// The encryption policy used by this inode
    pub ci_policy: fscrypt_policy,
// This inode's nonce, copied from the fscrypt_context
    pub ci_nonce: [u8; FSCRYPT_FILE_NONCE_SIZE],
}

// crypto.c
extern "C" {
    pub fn fscrypt_initialize(sb: *mut super_block) -> c_int;
}

pub const FSCRYPT_MAX_IV_SIZE: c_int = 32;
#[repr(C)]
#[derive(Copy, Clone)]
pub union fscrypt_iv {
// zero-based index of data unit within the file
    pub index: __le64,
// per-file nonce; only set in DIRECT_KEY mode
    pub nonce: [u8; FSCRYPT_FILE_NONCE_SIZE],
}

//
// Return the number of bits used by the maximum file data unit index that is
// possible on the given filesystem, using the given log2 data unit size.
//
// fname.c
// hkdf.c
//
// The list of contexts in which fscrypt uses HKDF.  These values are used as
// the first byte of the HKDF application-specific info string to guarantee that
// info strings are never repeated between contexts.  This ensures that all HKDF
// outputs are unique and cryptographically isolated, i.e. knowledge of one
// output doesn't reveal another.
//

// block.c

//
// Check whether the crypto transform or blk-crypto key has been allocated in
// @prep_key, depending on which encryption implementation the file will use.
//

// keyring.c
//
// fscrypt_master_key_user - a user's claim to a master key
//
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fscrypt_master_key_user {
    pub link: list_head,
    pub uid: kuid_t,
//
// This 'struct key' contains no secret.  It exists solely to charge the
// appropriate user's key quota.
//
    pub quota_key: *mut key,
}

//
// fscrypt_master_key_secret - secret key material of an in-use master key
//
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fscrypt_master_key_secret {
//
// The KDF with which subkeys of this key can be derived.
//
// For v1 policy keys, this isn't applicable and won't be set.
// Otherwise, this KDF will be keyed by this master key if
// ->is_hw_wrapped=false, or by the "software secret" that hardware
// derived from this master key if ->is_hw_wrapped=true.
//
    pub hkdf: hmac_sha512_key,
//
// True if this key is a hardware-wrapped key; false if this key is a
// raw key (i.e. a "software key").  For v1 policy keys this will always
// be false, as v1 policy support is a legacy feature which doesn't
// support newer functionality such as hardware-wrapped keys.
//
    pub is_hw_wrapped: bool,
//
// Size of the key in bytes.  This remains set even if ->bytes was
// zeroized due to no longer being needed.  I.e. we still remember the
// size of the key even if we don't need to remember the key itself.
//
    pub size: u32,
//
// The bytes of the key, when still needed.  This can be either a raw
// key or a hardware-wrapped key, as indicated by ->is_hw_wrapped.  In
// the case of a raw, v2 policy key, there is no need to remember the
// actual key separately from ->hkdf so this field will be zeroized as
// soon as ->hkdf is initialized.
//
    pub bytes: [u8; FSCRYPT_MAX_ANY_KEY_SIZE],
    pub __randomize_layout: },
//
// fscrypt_master_key - an in-use master key
//
// This represents a master encryption key which has been added to the
// filesystem.  There are three high-level states that a key can be in:
//
// FSCRYPT_KEY_STATUS_PRESENT
// Key is fully usable; it can be used to unlock inodes that are encrypted
// with it (this includes being able to create new inodes).  ->mk_present
// indicates whether the key is in this state.  ->mk_secret exists, the key
// is in the keyring, and ->mk_active_refs > 0 due to ->mk_present.
//
// FSCRYPT_KEY_STATUS_INCOMPLETELY_REMOVED
// Removal of this key has been initiated, but some inodes that were
// unlocked with it are still in-use.  Like ABSENT, ->mk_secret is wiped,
// and the key can no longer be used to unlock inodes.  Unlike ABSENT, the
// key is still in the keyring; ->mk_decrypted_inodes is nonempty; and
// ->mk_active_refs > 0, being equal to the size of ->mk_decrypted_inodes.
//
// This state transitions to ABSENT if ->mk_decrypted_inodes becomes empty,
// or to PRESENT if FS_IOC_ADD_ENCRYPTION_KEY is called again for this key.
//
// FSCRYPT_KEY_STATUS_ABSENT
// Key is fully removed.  The key is no longer in the keyring,
// ->mk_decrypted_inodes is empty, ->mk_active_refs == 0, ->mk_secret is
// wiped, and the key can no longer be used to unlock inodes.
//
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fscrypt_master_key {
//
// Link in ->s_master_keys->key_hashtable.
// Only valid if ->mk_active_refs > 0.
//
    pub mk_node: hlist_node,
// Semaphore that protects ->mk_secret, ->mk_users, and ->mk_present
    pub mk_sem: rw_semaphore,
//
// Active and structural reference counts.  An active ref guarantees
// that the struct continues to exist, continues to be in the keyring
// ->s_master_keys, and that any non-file-scoped subkeys (e.g.
// ->mk_mode_keys) that have been prepared continue to exist.
// A structural ref only guarantees that the struct continues to exist.
//
// There is one active ref associated with ->mk_present being true, and
// one active ref for each inode in ->mk_decrypted_inodes.
//
// There is one structural ref associated with the active refcount being
// nonzero.  Finding a key in the keyring also takes a structural ref,
// which is then held temporarily while the key is operated on.
//
    pub mk_active_refs: refcount_t,
    pub mk_struct_refs: refcount_t,
    pub mk_rcu_head: rcu_head,
//
// The secret key material.  Wiped as soon as it is no longer needed;
// for details, see the fscrypt_master_key struct comment.
//
// Locking: protected by ->mk_sem.
//
    pub mk_secret: fscrypt_master_key_secret,
//
// For v1 policy keys: an arbitrary key descriptor which was assigned by
// userspace (->descriptor).
//
// For v2 policy keys: a cryptographic hash of this key (->identifier).
//
    pub mk_spec: fscrypt_key_specifier,
//
// List of user claims to this key (struct fscrypt_master_key_user).
// Normally each key will be added by just one user, but it's possible
// that multiple users share a key, and in that case we need to keep
// track of those users so that one user can't remove the key before the
// others want it removed too.
//
// Used only for v2 policy keys.  v1 policy keys can be added only by
// root, so user tracking doesn't apply to them.
//
// Locking: protected by ->mk_sem.
//
    pub mk_users: list_head,
//
// List of inodes that were unlocked using this key.  This allows the
// inodes to be evicted efficiently if the key is removed.
//
    pub mk_decrypted_inodes: list_head,
    pub mk_decrypted_inodes_lock: spinlock_t,
//
// A list of 'struct fscrypt_mode_key' for the (hkdf_context, mode_num,
// data_unit_bits, inlinecrypt) combinations that are in use for this
// master key, for hkdf_context in [HKDF_CONTEXT_DIRECT_KEY,
// HKDF_CONTEXT_IV_INO_LBLK_32_KEY, HKDF_CONTEXT_IV_INO_LBLK_64_KEY].
//
// This is a linked list and not a hash table because in practice
// there's just a single encryption policy per master key, using
// _at most_ 2 nodes in this list.  Per-file keys don't use this at all.
//
// This list is append-only until the master key is fully removed, at
// which time the list is cleared.  Before then,
// fscrypt_mode_key_setup_mutex synchronizes appends, and searches use
// the RCU read lock together with ->mk_sem held for read.
//
    pub mk_mode_keys: list_head,
// Hash key for inode numbers.  Initialized only when needed.
    pub mk_ino_hash_key: siphash_key_t,
    pub mk_ino_hash_key_initialized: bool,
//
// Whether this key is in the "present" state, i.e. fully usable.  For
// details, see the fscrypt_master_key struct comment.
//
// Locking: protected by ->mk_sem, but can be read locklessly using
// READ_ONCE().  Writers must use WRITE_ONCE() when concurrent readers
// are possible.
//
    pub mk_present: bool,
    pub __randomize_layout: },
    pub "descriptor": return,
    pub "identifier": return,
    pub "[unknown]": return,
    pub FSCRYPT_KEY_DESCRIPTOR_SIZE: return,
    pub FSCRYPT_KEY_IDENTIFIER_SIZE: return,
    pub 0: return,
    pub mk): *mut void fscrypt_put_master_key(struct fscrypt_master_key,
    pub mk): *mut fscrypt_master_key,
    pub mk_spec): *const fscrypt_key_specifier,
    pub key_identifier[FSCRYPT_KEY_IDENTIFIER_SIZE]): u8,
    pub key_spec): *mut fscrypt_key_specifier,
    pub identifier[FSCRYPT_KEY_IDENTIFIER_SIZE]): u8,
    pub fscrypt_init_keyring(void): void __init,
// keysetup.c
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fscrypt_mode {
    pub friendly_name: *const c_char,
    pub cipher_str: *const c_char,
    pub /: *mut *mut int keysize; / key size in bytes,
    pub /: *mut *mut int security_strength; / security strength in bytes,
    pub /: *mut *mut int ivsize; / IV size in bytes,
    pub logged_cryptoapi_impl: c_int,
    pub logged_blk_crypto_native: c_int,
    pub logged_blk_crypto_fallback: c_int,
    pub blk_crypto_mode: blk_crypto_mode_num,
}

extern "C" {
    pub fn fscrypt_get_encryption_info(inode: *mut inode, allow_unsupported: bool) -> c_int;
}
//
// fscrypt_require_key() - require an inode's encryption key
// @inode: the inode we need the key for
//
// If the inode is encrypted, set up its encryption key if not already done.
// Then require that the key be present and return -ENOKEY otherwise.
//
// No locks are needed, and the key will live as long as the struct inode --- so
// it won't go away from under you.
//
// Return: 0 on success, -ENOKEY if the key is missing, or another -errno code
// if a problem occurred while setting up the encryption key.
//
// keysetup_v1.c
extern "C" {
    pub fn fscrypt_put_direct_key(dk: *mut fscrypt_direct_key);
}
// policy.c
