//! Automatically rewritten from C Header to Rust Module
//! Source: include/linux/sunrpc/xdrgen/nfs4_1.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
// Generated by xdrgen. Manual edits will be lost.
// XDR specification file: ../../Documentation/sunrpc/xdr/nfs4_1.x
// XDR specification modification time: Tue Jun 30 11:57:21 2026

pub type int32_t = i32;
pub type uint32_t = u32;
pub type int64_t = i64;
pub type uint64_t = u64;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum nfsstat4 {
    NFS4_OK = 0,
    NFS4ERR_PERM = 1,
    NFS4ERR_NOENT = 2,
    NFS4ERR_IO = 5,
    NFS4ERR_NXIO = 6,
    NFS4ERR_ACCESS = 13,
    NFS4ERR_EXIST = 17,
    NFS4ERR_XDEV = 18,
    NFS4ERR_NOTDIR = 20,
    NFS4ERR_ISDIR = 21,
    NFS4ERR_INVAL = 22,
    NFS4ERR_FBIG = 27,
    NFS4ERR_NOSPC = 28,
    NFS4ERR_ROFS = 30,
    NFS4ERR_MLINK = 31,
    NFS4ERR_NAMETOOLONG = 63,
    NFS4ERR_NOTEMPTY = 66,
    NFS4ERR_DQUOT = 69,
    NFS4ERR_STALE = 70,
    NFS4ERR_BADHANDLE = 10001,
    NFS4ERR_BAD_COOKIE = 10003,
    NFS4ERR_NOTSUPP = 10004,
    NFS4ERR_TOOSMALL = 10005,
    NFS4ERR_SERVERFAULT = 10006,
    NFS4ERR_BADTYPE = 10007,
    NFS4ERR_DELAY = 10008,
    NFS4ERR_SAME = 10009,
    NFS4ERR_DENIED = 10010,
    NFS4ERR_EXPIRED = 10011,
    NFS4ERR_LOCKED = 10012,
    NFS4ERR_GRACE = 10013,
    NFS4ERR_FHEXPIRED = 10014,
    NFS4ERR_SHARE_DENIED = 10015,
    NFS4ERR_WRONGSEC = 10016,
    NFS4ERR_CLID_INUSE = 10017,
    NFS4ERR_RESOURCE = 10018,
    NFS4ERR_MOVED = 10019,
    NFS4ERR_NOFILEHANDLE = 10020,
    NFS4ERR_MINOR_VERS_MISMATCH = 10021,
    NFS4ERR_STALE_CLIENTID = 10022,
    NFS4ERR_STALE_STATEID = 10023,
    NFS4ERR_OLD_STATEID = 10024,
    NFS4ERR_BAD_STATEID = 10025,
    NFS4ERR_BAD_SEQID = 10026,
    NFS4ERR_NOT_SAME = 10027,
    NFS4ERR_LOCK_RANGE = 10028,
    NFS4ERR_SYMLINK = 10029,
    NFS4ERR_RESTOREFH = 10030,
    NFS4ERR_LEASE_MOVED = 10031,
    NFS4ERR_ATTRNOTSUPP = 10032,
    NFS4ERR_NO_GRACE = 10033,
    NFS4ERR_RECLAIM_BAD = 10034,
    NFS4ERR_RECLAIM_CONFLICT = 10035,
    NFS4ERR_BADXDR = 10036,
    NFS4ERR_LOCKS_HELD = 10037,
    NFS4ERR_OPENMODE = 10038,
    NFS4ERR_BADOWNER = 10039,
    NFS4ERR_BADCHAR = 10040,
    NFS4ERR_BADNAME = 10041,
    NFS4ERR_BAD_RANGE = 10042,
    NFS4ERR_LOCK_NOTSUPP = 10043,
    NFS4ERR_OP_ILLEGAL = 10044,
    NFS4ERR_DEADLOCK = 10045,
    NFS4ERR_FILE_OPEN = 10046,
    NFS4ERR_ADMIN_REVOKED = 10047,
    NFS4ERR_CB_PATH_DOWN = 10048,
    NFS4ERR_BADIOMODE = 10049,
    NFS4ERR_BADLAYOUT = 10050,
    NFS4ERR_BAD_SESSION_DIGEST = 10051,
    NFS4ERR_BADSESSION = 10052,
    NFS4ERR_BADSLOT = 10053,
    NFS4ERR_COMPLETE_ALREADY = 10054,
    NFS4ERR_CONN_NOT_BOUND_TO_SESSION = 10055,
    NFS4ERR_DELEG_ALREADY_WANTED = 10056,
    NFS4ERR_BACK_CHAN_BUSY = 10057,
    NFS4ERR_LAYOUTTRYLATER = 10058,
    NFS4ERR_LAYOUTUNAVAILABLE = 10059,
    NFS4ERR_NOMATCHING_LAYOUT = 10060,
    NFS4ERR_RECALLCONFLICT = 10061,
    NFS4ERR_UNKNOWN_LAYOUTTYPE = 10062,
    NFS4ERR_SEQ_MISORDERED = 10063,
    NFS4ERR_SEQUENCE_POS = 10064,
    NFS4ERR_REQ_TOO_BIG = 10065,
    NFS4ERR_REP_TOO_BIG = 10066,
    NFS4ERR_REP_TOO_BIG_TO_CACHE = 10067,
    NFS4ERR_RETRY_UNCACHED_REP = 10068,
    NFS4ERR_UNSAFE_COMPOUND = 10069,
    NFS4ERR_TOO_MANY_OPS = 10070,
    NFS4ERR_OP_NOT_IN_SESSION = 10071,
    NFS4ERR_HASH_ALG_UNSUPP = 10072,
    NFS4ERR_CLIENTID_BUSY = 10074,
    NFS4ERR_PNFS_IO_HOLE = 10075,
    NFS4ERR_SEQ_FALSE_RETRY = 10076,
    NFS4ERR_BAD_HIGH_SLOT = 10077,
    NFS4ERR_DEADSESSION = 10078,
    NFS4ERR_ENCR_ALG_UNSUPP = 10079,
    NFS4ERR_PNFS_NO_LAYOUT = 10080,
    NFS4ERR_NOT_ONLY_OP = 10081,
    NFS4ERR_WRONG_CRED = 10082,
    NFS4ERR_WRONG_TYPE = 10083,
    NFS4ERR_DIRDELEG_UNAVAIL = 10084,
    NFS4ERR_REJECT_DELEG = 10085,
    NFS4ERR_RETURNCONFLICT = 10086,
    NFS4ERR_DELEG_REVOKED = 10087,
    NFS4ERR_PARTNER_NOTSUPP = 10088,
    NFS4ERR_PARTNER_NO_AUTH = 10089,
    NFS4ERR_UNION_NOTSUPP = 10090,
    NFS4ERR_OFFLOAD_DENIED = 10091,
    NFS4ERR_WRONG_LFS = 10092,
    NFS4ERR_BADLABEL = 10093,
    NFS4ERR_OFFLOAD_NO_REQS = 10094,
    NFS4ERR_NOXATTR = 10095,
    NFS4ERR_XATTR2BIG = 10096,
}

pub type nfsstat4 = nfsstat4;
pub type attrlist4 = opaque;
pub type nfs_cookie4 = u64;
pub type nfs_fh4 = opaque;
pub type utf8string = opaque;
pub type utf8str_cis = utf8string;
pub type utf8str_cs = utf8string;
pub type utf8str_mixed = utf8string;
pub type component4 = utf8str_cs;
pub type linktext4 = utf8str_cs;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nfstime4 {
    pub seconds: i64,
    pub nseconds: u32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct fattr4 {
    pub attrmask: bitmap4,
    pub attr_vals: attrlist4,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct stateid4 {
    pub seqid: u32,
    pub other: [u8; 12],
}

pub type fattr4_offline = bool;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct open_arguments4 {
    pub oa_share_access: bitmap4,
    pub oa_share_deny: bitmap4,
    pub oa_share_access_want: bitmap4,
    pub oa_open_claim: bitmap4,
    pub oa_create_mode: bitmap4,
}

#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum open_args_share_access4 {
    OPEN_ARGS_SHARE_ACCESS_READ = 1,
    OPEN_ARGS_SHARE_ACCESS_WRITE = 2,
    OPEN_ARGS_SHARE_ACCESS_BOTH = 3,
}

pub type open_args_share_access4 = open_args_share_access4;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum open_args_share_deny4 {
    OPEN_ARGS_SHARE_DENY_NONE = 0,
    OPEN_ARGS_SHARE_DENY_READ = 1,
    OPEN_ARGS_SHARE_DENY_WRITE = 2,
    OPEN_ARGS_SHARE_DENY_BOTH = 3,
}

pub type open_args_share_deny4 = open_args_share_deny4;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum open_args_share_access_want4 {
    OPEN_ARGS_SHARE_ACCESS_WANT_ANY_DELEG = 3,
    OPEN_ARGS_SHARE_ACCESS_WANT_NO_DELEG = 4,
    OPEN_ARGS_SHARE_ACCESS_WANT_CANCEL = 5,
    OPEN_ARGS_SHARE_ACCESS_WANT_SIGNAL_DELEG_WHEN_RESRC_AVAIL = 17,
    OPEN_ARGS_SHARE_ACCESS_WANT_PUSH_DELEG_WHEN_UNCONTENDED = 18,
    OPEN_ARGS_SHARE_ACCESS_WANT_DELEG_TIMESTAMPS = 20,
    OPEN_ARGS_SHARE_ACCESS_WANT_OPEN_XOR_DELEGATION = 21,
}

pub type open_args_share_access_want4 = open_args_share_access_want4;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum open_args_open_claim4 {
    OPEN_ARGS_OPEN_CLAIM_NULL = 0,
    OPEN_ARGS_OPEN_CLAIM_PREVIOUS = 1,
    OPEN_ARGS_OPEN_CLAIM_DELEGATE_CUR = 2,
    OPEN_ARGS_OPEN_CLAIM_DELEGATE_PREV = 3,
    OPEN_ARGS_OPEN_CLAIM_FH = 4,
    OPEN_ARGS_OPEN_CLAIM_DELEG_CUR_FH = 5,
    OPEN_ARGS_OPEN_CLAIM_DELEG_PREV_FH = 6,
}

pub type open_args_open_claim4 = open_args_open_claim4;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum open_args_createmode4 {
    OPEN_ARGS_CREATEMODE_UNCHECKED4 = 0,
    OPEN_ARGS_CREATE_MODE_GUARDED = 1,
    OPEN_ARGS_CREATEMODE_EXCLUSIVE4 = 2,
    OPEN_ARGS_CREATE_MODE_EXCLUSIVE4_1 = 3,
}

pub type open_args_createmode4 = open_args_createmode4;
pub type fattr4_open_arguments = open_arguments4;
//
// Determine what OPEN supports.
//
pub type fattr4_time_deleg_access = nfstime4;
pub type fattr4_time_deleg_modify = nfstime4;
//
// New RECOMMENDED Attribute for
// delegation caching of times
//
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum open_delegation_type4 {
    OPEN_DELEGATE_NONE = 0,
    OPEN_DELEGATE_READ = 1,
    OPEN_DELEGATE_WRITE = 2,
    OPEN_DELEGATE_NONE_EXT = 3,
    OPEN_DELEGATE_READ_ATTRS_DELEG = 4,
    OPEN_DELEGATE_WRITE_ATTRS_DELEG = 5,
}

pub type open_delegation_type4 = open_delegation_type4;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum aclmodel4 {
    ACL_MODEL_NFS4 = 1,
    ACL_MODEL_POSIX_DRAFT = 2,
    ACL_MODEL_NONE = 3,
}

pub type aclmodel4 = aclmodel4;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum aclscope4 {
    ACL_SCOPE_FILE_OBJECT = 1,
    ACL_SCOPE_FILE_SYSTEM = 2,
    ACL_SCOPE_SERVER = 3,
}

pub type aclscope4 = aclscope4;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum posixacetag4 {
    POSIXACE4_TAG_USER_OBJ = 1,
    POSIXACE4_TAG_USER = 2,
    POSIXACE4_TAG_GROUP_OBJ = 3,
    POSIXACE4_TAG_GROUP = 4,
    POSIXACE4_TAG_MASK = 5,
    POSIXACE4_TAG_OTHER = 6,
}

pub type posixacetag4 = posixacetag4;
pub type posixaceperm4 = u32;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct posixace4 {
    pub tag: posixacetag4,
    pub perm: posixaceperm4,
    pub who: utf8str_mixed,
}

pub type fattr4_acl_trueform = aclmodel4;
pub type fattr4_acl_trueform_scope = aclscope4;
//
// New for POSIX ACL extension
//
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum notify_type4 {
    NOTIFY4_CHANGE_CHILD_ATTRS = 0,
    NOTIFY4_CHANGE_DIR_ATTRS = 1,
    NOTIFY4_REMOVE_ENTRY = 2,
    NOTIFY4_ADD_ENTRY = 3,
    NOTIFY4_RENAME_ENTRY = 4,
    NOTIFY4_CHANGE_COOKIE_VERIFIER = 5,
    NOTIFY4_GFLAG_EXTEND = 6,
    NOTIFY4_AUFLAG_VALID = 7,
    NOTIFY4_AUFLAG_USER = 8,
    NOTIFY4_AUFLAG_GROUP = 9,
    NOTIFY4_AUFLAG_OTHER = 10,
    NOTIFY4_CHANGE_AUTH = 11,
    NOTIFY4_CFLAG_ORDER = 12,
    NOTIFY4_AUFLAG_GANOW = 13,
    NOTIFY4_AUFLAG_GALATER = 14,
    NOTIFY4_CHANGE_GA = 15,
    NOTIFY4_CHANGE_AMASK = 16,
}

pub type notify_type4 = notify_type4;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct notify_entry4 {
    pub ne_file: component4,
    pub ne_attrs: fattr4,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct prev_entry4 {
    pub pe_prev_entry: notify_entry4,
    pub pe_prev_entry_cookie: nfs_cookie4,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct notify_remove4 {
    pub nrm_old_entry: notify_entry4,
    pub nrm_old_entry_cookie: nfs_cookie4,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct notify_add4 {
    pub count: u32,
    pub element: *mut notify_remove4,
    pub nad_old_entry: },
    pub nad_new_entry: notify_entry4,
    pub count: u32,
    pub element: *mut nfs_cookie4,
    pub nad_new_entry_cookie: },
    pub count: u32,
    pub element: *mut prev_entry4,
    pub nad_prev_entry: },
    pub nad_last_entry: bool,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct notify_attr4 {
    pub na_changed_entry: notify_entry4,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct notify_rename4 {
    pub nrn_old_entry: notify_remove4,
    pub nrn_new_entry: notify_add4,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct notify_verifier4 {
    pub nv_old_cookieverf: verifier4,
    pub nv_new_cookieverf: verifier4,
}

pub type notifylist4 = opaque;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct notify4 {
    pub notify_mask: bitmap4,
    pub notify_vals: notifylist4,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct CB_NOTIFY4args {
    pub cna_stateid: stateid4,
    pub cna_fh: nfs_fh4,
    pub count: u32,
    pub element: *mut notify4,
    pub cna_changes: },
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct CB_NOTIFY4res {
    pub cnr_status: nfsstat4,
}

