//! Automatically rewritten from C Header to Rust Module
//! Source: include/linux/sunrpc/xdrgen/nlm3.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
// Generated by xdrgen. Manual edits will be lost.
// XDR specification file: ../../Documentation/sunrpc/xdr/nlm3.x
// XDR specification modification time: Mon Jun 29 20:42:29 2026

pub type netobj = opaque;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum nlm_stats {
    LCK_GRANTED = 0,
    LCK_DENIED = 1,
    LCK_DENIED_NOLOCKS = 2,
    LCK_BLOCKED = 3,
    LCK_DENIED_GRACE_PERIOD = 4,
}

pub type nlm_stats = __be32;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_stat {
    pub stat: nlm_stats,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_res {
    pub cookie: netobj,
    pub stat: nlm_stat,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_holder {
    pub exclusive: bool,
    pub uppid: i32,
    pub oh: netobj,
    pub l_offset: u32,
    pub l_len: u32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_testrply {
    pub stat: nlm_stats,
    pub holder: nlm_holder,
    pub u: },
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_testres {
    pub cookie: netobj,
    pub test_stat: nlm_testrply,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_lock {
    pub caller_name: string,
    pub fh: netobj,
    pub oh: netobj,
    pub uppid: i32,
    pub l_offset: u32,
    pub l_len: u32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_lockargs {
    pub cookie: netobj,
    pub block: bool,
    pub exclusive: bool,
    pub alock: nlm_lock,
    pub reclaim: bool,
    pub state: i32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_cancargs {
    pub cookie: netobj,
    pub block: bool,
    pub exclusive: bool,
    pub alock: nlm_lock,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_testargs {
    pub cookie: netobj,
    pub exclusive: bool,
    pub alock: nlm_lock,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_unlockargs {
    pub cookie: netobj,
    pub alock: nlm_lock,
}

#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum fsh_mode {
    fsm_DN = 0,
    fsm_DR = 1,
    fsm_DW = 2,
    fsm_DRW = 3,
}

pub type fsh_mode = fsh_mode;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum fsh_access {
    fsa_NONE = 0,
    fsa_R = 1,
    fsa_W = 2,
    fsa_RW = 3,
}

pub type fsh_access = fsh_access;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_share {
    pub caller_name: string,
    pub fh: netobj,
    pub oh: netobj,
    pub mode: fsh_mode,
    pub access: fsh_access,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_shareargs {
    pub cookie: netobj,
    pub share: nlm_share,
    pub reclaim: bool,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_shareres {
    pub cookie: netobj,
    pub stat: nlm_stats,
    pub sequence: i32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_notify {
    pub name: string,
    pub state: i32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm_notifyargs {
    pub notify: nlm_notify,
    pub private: [u8; SM_PRIV_SIZE],
}

