//! Automatically rewritten from C Header to Rust Module
//! Source: include/linux/sunrpc/xdrgen/nlm4.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
// Generated by xdrgen. Manual edits will be lost.
// XDR specification file: ../../Documentation/sunrpc/xdr/nlm4.x
// XDR specification modification time: Mon Jun 29 20:42:29 2026

pub type netobj = opaque;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum fsh4_mode {
    fsm_DN = 0,
    fsm_DR = 1,
    fsm_DW = 2,
    fsm_DRW = 3,
}

pub type fsh4_mode = fsh4_mode;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum fsh4_access {
    fsa_NONE = 0,
    fsa_R = 1,
    fsa_W = 2,
    fsa_RW = 3,
}

pub type fsh4_access = fsh4_access;
pub type uint64 = u64;
pub type int64 = i64;
pub type uint32 = u32;
pub type int32 = i32;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum nlm4_stats {
    NLM4_GRANTED = 0,
    NLM4_DENIED = 1,
    NLM4_DENIED_NOLOCKS = 2,
    NLM4_BLOCKED = 3,
    NLM4_DENIED_GRACE_PERIOD = 4,
    NLM4_DEADLCK = 5,
    NLM4_ROFS = 6,
    NLM4_STALE_FH = 7,
    NLM4_FBIG = 8,
    NLM4_FAILED = 9,
}

pub type nlm4_stats = __be32;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_holder {
    pub exclusive: bool,
    pub svid: int32,
    pub oh: netobj,
    pub l_offset: uint64,
    pub l_len: uint64,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_testrply {
    pub stat: nlm4_stats,
    pub holder: nlm4_holder,
    pub u: },
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_stat {
    pub stat: nlm4_stats,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_res {
    pub cookie: netobj,
    pub stat: nlm4_stat,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_testres {
    pub cookie: netobj,
    pub stat: nlm4_testrply,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_lock {
    pub caller_name: string,
    pub fh: netobj,
    pub oh: netobj,
    pub svid: int32,
    pub l_offset: uint64,
    pub l_len: uint64,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_lockargs {
    pub cookie: netobj,
    pub block: bool,
    pub exclusive: bool,
    pub alock: nlm4_lock,
    pub reclaim: bool,
    pub state: int32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_cancargs {
    pub cookie: netobj,
    pub block: bool,
    pub exclusive: bool,
    pub alock: nlm4_lock,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_testargs {
    pub cookie: netobj,
    pub exclusive: bool,
    pub alock: nlm4_lock,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_unlockargs {
    pub cookie: netobj,
    pub alock: nlm4_lock,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_share {
    pub caller_name: string,
    pub fh: netobj,
    pub oh: netobj,
    pub mode: fsh4_mode,
    pub access: fsh4_access,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_shareargs {
    pub cookie: netobj,
    pub share: nlm4_share,
    pub reclaim: bool,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_shareres {
    pub cookie: netobj,
    pub stat: nlm4_stats,
    pub sequence: int32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_notify {
    pub name: string,
    pub state: int32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_notifyargs {
    pub notify: nlm4_notify,
    pub private: [u8; SM_PRIV_SIZE],
}

