//! Automatically rewritten from C Header to Rust Module
//! Source: fs/nfsd/nfs4xdr_gen.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
// Generated by xdrgen. Manual edits will be lost.
// XDR specification file: ../../Documentation/sunrpc/xdr/nfs4_1.x
// XDR specification modification time: Tue Jun 30 11:57:21 2026

extern "C" {
    pub fn xdrgen_decode_fattr4_open_arguments(xdr: *mut xdr_stream, ptr: *mut fattr4_open_arguments) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_fattr4_open_arguments(xdr: *mut xdr_stream, value: *const fattr4_open_arguments) -> bool;
}
extern "C" {
    pub fn xdrgen_decode_fattr4_time_deleg_access(xdr: *mut xdr_stream, ptr: *mut fattr4_time_deleg_access) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_fattr4_time_deleg_access(xdr: *mut xdr_stream, value: *const fattr4_time_deleg_access) -> bool;
}
extern "C" {
    pub fn xdrgen_decode_fattr4_time_deleg_modify(xdr: *mut xdr_stream, ptr: *mut fattr4_time_deleg_modify) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_fattr4_time_deleg_modify(xdr: *mut xdr_stream, value: *const fattr4_time_deleg_modify) -> bool;
}
extern "C" {
    pub fn xdrgen_decode_aclmodel4(xdr: *mut xdr_stream, ptr: *mut aclmodel4) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_aclmodel4(xdr: *mut xdr_stream, value: aclmodel4) -> bool;
}
extern "C" {
    pub fn xdrgen_decode_aclscope4(xdr: *mut xdr_stream, ptr: *mut aclscope4) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_aclscope4(xdr: *mut xdr_stream, value: aclscope4) -> bool;
}
extern "C" {
    pub fn xdrgen_decode_posixacetag4(xdr: *mut xdr_stream, ptr: *mut posixacetag4) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_posixacetag4(xdr: *mut xdr_stream, value: posixacetag4) -> bool;
}
extern "C" {
    pub fn xdrgen_decode_posixaceperm4(xdr: *mut xdr_stream, ptr: *mut posixaceperm4) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_posixaceperm4(xdr: *mut xdr_stream, value: posixaceperm4) -> bool;
}
extern "C" {
    pub fn xdrgen_decode_notify_remove4(xdr: *mut xdr_stream, ptr: *mut notify_remove4) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_notify_remove4(xdr: *mut xdr_stream, value: *const notify_remove4) -> bool;
}
extern "C" {
    pub fn xdrgen_decode_notify_add4(xdr: *mut xdr_stream, ptr: *mut notify_add4) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_notify_add4(xdr: *mut xdr_stream, value: *const notify_add4) -> bool;
}
extern "C" {
    pub fn xdrgen_decode_notify_attr4(xdr: *mut xdr_stream, ptr: *mut notify_attr4) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_notify_attr4(xdr: *mut xdr_stream, value: *const notify_attr4) -> bool;
}
extern "C" {
    pub fn xdrgen_decode_notify_rename4(xdr: *mut xdr_stream, ptr: *mut notify_rename4) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_notify_rename4(xdr: *mut xdr_stream, value: *const notify_rename4) -> bool;
}
extern "C" {
    pub fn xdrgen_decode_CB_NOTIFY4args(xdr: *mut xdr_stream, ptr: *mut CB_NOTIFY4args) -> bool;
}
extern "C" {
    pub fn xdrgen_encode_CB_NOTIFY4args(xdr: *mut xdr_stream, value: *const CB_NOTIFY4args) -> bool;
}
