//! Automatically rewritten from C Header to Rust Module
//! Source: include/scsi/fc/fc_fcoe.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0-only
//
// Copyright(c) 2007 Intel Corporation. All rights reserved.
//
// Maintained at www.Open-FCoE.org
//
// FCoE - Fibre Channel over Ethernet.
// See T11 FC-BB-5 Rev 2.00 (09-056v5.pdf)
//
// Default FC_FCOE_OUI / FC-MAP value.
//
pub const FC_FCOE_OUI: c_uint = 0x0efc00	/* upper 24 bits of FCOE MAC */;
//
// Fabric Login (FLOGI) MAC for non-FIP use.  Non-FIP use is deprecated.
//

//
// Ethernet Addresses based on FC S_ID and D_ID.
// Generated by FC_FCOE_OUI | S_ID/D_ID
//

//
// FCoE frame header - 14 bytes
// This follows the VLAN header, which includes the ethertype.
//
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fcoe_hdr {
    pub /: *mut *mut __u8 fcoe_ver; / version field - upper 4 bits,
    pub /: *mut *mut __u8 fcoe_resvd[12]; / reserved - send zero and ignore,
    pub /: *mut *mut __u8 fcoe_sof; / start of frame per RFC 3643,
}

//
// FCoE CRC & EOF - 8 bytes.
//
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fcoe_crc_eof {
    pub /: *mut *mut __le32 fcoe_crc32; / CRC for FC packet,
    pub /: *mut *mut __u8 fcoe_eof; / EOF from RFC 3643,
    pub /: *mut *mut __u8 fcoe_resvd[3]; / reserved - send zero and ignore,
    pub __attribute__((packed)): },
//
// Minimum FCoE + FC header length
// 14 bytes FCoE header + 24 byte FC header = 38 bytes
//
pub const FCOE_HEADER_LEN: c_int = 38;
//
// Minimum FCoE frame size
// 14 bytes FCoE header + 24 byte FC header + 8 byte FCoE trailer = 46 bytes
//
pub const FCOE_MIN_FRAME: c_int = 46;
//
// FCoE Link Error Status Block: T11 FC-BB-5 Rev2.0, Clause 7.10.
//
#[repr(C)]
#[derive(Copy, Clone)]
pub struct fcoe_fc_els_lesb {
    pub /: *mut *mut __be32 lesb_link_fail; / link failure count,
    pub /: *mut *mut __be32 lesb_vlink_fail; / virtual link failure count,
    pub /: *mut *mut __be32 lesb_miss_fka; / missing FIP keep-alive count,
    pub /: *mut *mut __be32 lesb_symb_err; / symbol error during carrier count,
    pub /: *mut *mut __be32 lesb_err_block; / errored block count,
    pub /: *mut *mut __be32 lesb_fcs_error; / frame check sequence error count,
}

//
// fc_fcoe_set_mac - Store OUI + DID into MAC address field.
// @mac: mac address to be set
// @did: fc dest id to use
//
