//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/amd/include/asic_reg/gc/gc_12_1_1_sh_mask.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// Copyright 2025 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

// Macro flag: #define _gc_12_1_1_SH_MASK_HEADER
// addressBlock: aigc_grbma_grbma_grbmadec
// GRBMA_GFX_INDEX
pub const GRBMA_GFX_INDEX__INSTANCE_INDEX__SHIFT: c_uint = 0x0;
pub const GRBMA_GFX_INDEX__SA_INDEX__SHIFT: c_uint = 0x8;
pub const GRBMA_GFX_INDEX__SE_INDEX__SHIFT: c_uint = 0x10;
pub const GRBMA_GFX_INDEX__SA_BROADCAST_WRITES__SHIFT: c_uint = 0x1d;
pub const GRBMA_GFX_INDEX__INSTANCE_BROADCAST_WRITES__SHIFT: c_uint = 0x1e;
pub const GRBMA_GFX_INDEX__SE_BROADCAST_WRITES__SHIFT: c_uint = 0x1f;
pub const GRBMA_GFX_INDEX__INSTANCE_INDEX_MASK: c_uint = 0x0000007FL;
pub const GRBMA_GFX_INDEX__SA_INDEX_MASK: c_uint = 0x00000300L;
pub const GRBMA_GFX_INDEX__SE_INDEX_MASK: c_uint = 0x000F0000L;
pub const GRBMA_GFX_INDEX__SA_BROADCAST_WRITES_MASK: c_uint = 0x20000000L;
pub const GRBMA_GFX_INDEX__INSTANCE_BROADCAST_WRITES_MASK: c_uint = 0x40000000L;
pub const GRBMA_GFX_INDEX__SE_BROADCAST_WRITES_MASK: c_uint = 0x80000000L;
// addressBlock: aigc_grbma_grbma_perfddec
// GRBMA_PERFCOUNTER0_LO
pub const GRBMA_PERFCOUNTER0_LO__PERFCOUNTER_LO__SHIFT: c_uint = 0x0;
pub const GRBMA_PERFCOUNTER0_LO__PERFCOUNTER_LO_MASK: c_uint = 0xFFFFFFFFL;
// GRBMA_PERFCOUNTER0_HI
pub const GRBMA_PERFCOUNTER0_HI__PERFCOUNTER_HI__SHIFT: c_uint = 0x0;
pub const GRBMA_PERFCOUNTER0_HI__PERFCOUNTER_HI_MASK: c_uint = 0xFFFFFFFFL;
// GRBMA_PERFCOUNTER1_LO
pub const GRBMA_PERFCOUNTER1_LO__PERFCOUNTER_LO__SHIFT: c_uint = 0x0;
pub const GRBMA_PERFCOUNTER1_LO__PERFCOUNTER_LO_MASK: c_uint = 0xFFFFFFFFL;
// GRBMA_PERFCOUNTER1_HI
pub const GRBMA_PERFCOUNTER1_HI__PERFCOUNTER_HI__SHIFT: c_uint = 0x0;
pub const GRBMA_PERFCOUNTER1_HI__PERFCOUNTER_HI_MASK: c_uint = 0xFFFFFFFFL;
// addressBlock: aigc_grbma_grbma_perfsdec
// GRBMA_PERFCOUNTER0_SELECT
pub const GRBMA_PERFCOUNTER0_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GRBMA_PERFCOUNTER0_SELECT__GL1CC_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x6;
pub const GRBMA_PERFCOUNTER0_SELECT__GL1XCC_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x7;
pub const GRBMA_PERFCOUNTER0_SELECT__PMR_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x8;
pub const GRBMA_PERFCOUNTER0_SELECT__SC_CLEAN_USER_DEFINED_MASK__SHIFT: c_uint = 0x9;
pub const GRBMA_PERFCOUNTER0_SELECT__WGS_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0xa;
pub const GRBMA_PERFCOUNTER0_SELECT__DB_CLEAN_USER_DEFINED_MASK__SHIFT: c_uint = 0xb;
pub const GRBMA_PERFCOUNTER0_SELECT__CB_CLEAN_USER_DEFINED_MASK__SHIFT: c_uint = 0xc;
pub const GRBMA_PERFCOUNTER0_SELECT__TA_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0xd;
pub const GRBMA_PERFCOUNTER0_SELECT__SX_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0xe;
pub const GRBMA_PERFCOUNTER0_SELECT__GL2C_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0xf;
pub const GRBMA_PERFCOUNTER0_SELECT__SPI_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x10;
pub const GRBMA_PERFCOUNTER0_SELECT__XCAC_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x11;
pub const GRBMA_PERFCOUNTER0_SELECT__PA_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x12;
pub const GRBMA_PERFCOUNTER0_SELECT__GL2A_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x13;
pub const GRBMA_PERFCOUNTER0_SELECT__DB_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x14;
pub const GRBMA_PERFCOUNTER0_SELECT__CB_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x15;
pub const GRBMA_PERFCOUNTER0_SELECT__EA_LINK_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x17;
pub const GRBMA_PERFCOUNTER0_SELECT__AIGC_CAC_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x18;
pub const GRBMA_PERFCOUNTER0_SELECT__BCI_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x19;
pub const GRBMA_PERFCOUNTER0_SELECT__RLC_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x1a;
pub const GRBMA_PERFCOUNTER0_SELECT__TCP_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x1b;
pub const GRBMA_PERFCOUNTER0_SELECT__GE_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x1c;
pub const GRBMA_PERFCOUNTER0_SELECT__UTCL1_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x1d;
pub const GRBMA_PERFCOUNTER0_SELECT__EA_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x1e;
pub const GRBMA_PERFCOUNTER0_SELECT__PERF_SEL_MASK: c_uint = 0x0000003FL;
pub const GRBMA_PERFCOUNTER0_SELECT__GL1CC_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00000040L;
pub const GRBMA_PERFCOUNTER0_SELECT__GL1XCC_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00000080L;
pub const GRBMA_PERFCOUNTER0_SELECT__PMR_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00000100L;
pub const GRBMA_PERFCOUNTER0_SELECT__SC_CLEAN_USER_DEFINED_MASK_MASK: c_uint = 0x00000200L;
pub const GRBMA_PERFCOUNTER0_SELECT__WGS_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00000400L;
pub const GRBMA_PERFCOUNTER0_SELECT__DB_CLEAN_USER_DEFINED_MASK_MASK: c_uint = 0x00000800L;
pub const GRBMA_PERFCOUNTER0_SELECT__CB_CLEAN_USER_DEFINED_MASK_MASK: c_uint = 0x00001000L;
pub const GRBMA_PERFCOUNTER0_SELECT__TA_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00002000L;
pub const GRBMA_PERFCOUNTER0_SELECT__SX_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00004000L;
pub const GRBMA_PERFCOUNTER0_SELECT__GL2C_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00008000L;
pub const GRBMA_PERFCOUNTER0_SELECT__SPI_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00010000L;
pub const GRBMA_PERFCOUNTER0_SELECT__XCAC_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00020000L;
pub const GRBMA_PERFCOUNTER0_SELECT__PA_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00040000L;
pub const GRBMA_PERFCOUNTER0_SELECT__GL2A_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00080000L;
pub const GRBMA_PERFCOUNTER0_SELECT__DB_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00100000L;
pub const GRBMA_PERFCOUNTER0_SELECT__CB_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00200000L;
pub const GRBMA_PERFCOUNTER0_SELECT__EA_LINK_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00800000L;
pub const GRBMA_PERFCOUNTER0_SELECT__AIGC_CAC_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x01000000L;
pub const GRBMA_PERFCOUNTER0_SELECT__BCI_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x02000000L;
pub const GRBMA_PERFCOUNTER0_SELECT__RLC_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x04000000L;
pub const GRBMA_PERFCOUNTER0_SELECT__TCP_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x08000000L;
pub const GRBMA_PERFCOUNTER0_SELECT__GE_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x10000000L;
pub const GRBMA_PERFCOUNTER0_SELECT__UTCL1_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x20000000L;
pub const GRBMA_PERFCOUNTER0_SELECT__EA_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x40000000L;
// GRBMA_PERFCOUNTER1_SELECT
pub const GRBMA_PERFCOUNTER1_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GRBMA_PERFCOUNTER1_SELECT__GL1CC_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x6;
pub const GRBMA_PERFCOUNTER1_SELECT__GL1XCC_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x7;
pub const GRBMA_PERFCOUNTER1_SELECT__PMR_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x8;
pub const GRBMA_PERFCOUNTER1_SELECT__SC_CLEAN_USER_DEFINED_MASK__SHIFT: c_uint = 0x9;
pub const GRBMA_PERFCOUNTER1_SELECT__WGS_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0xa;
pub const GRBMA_PERFCOUNTER1_SELECT__DB_CLEAN_USER_DEFINED_MASK__SHIFT: c_uint = 0xb;
pub const GRBMA_PERFCOUNTER1_SELECT__CB_CLEAN_USER_DEFINED_MASK__SHIFT: c_uint = 0xc;
pub const GRBMA_PERFCOUNTER1_SELECT__TA_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0xd;
pub const GRBMA_PERFCOUNTER1_SELECT__SX_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0xe;
pub const GRBMA_PERFCOUNTER1_SELECT__GL2C_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0xf;
pub const GRBMA_PERFCOUNTER1_SELECT__SPI_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x10;
pub const GRBMA_PERFCOUNTER1_SELECT__XCAC_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x11;
pub const GRBMA_PERFCOUNTER1_SELECT__PA_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x12;
pub const GRBMA_PERFCOUNTER1_SELECT__GL2A_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x13;
pub const GRBMA_PERFCOUNTER1_SELECT__DB_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x14;
pub const GRBMA_PERFCOUNTER1_SELECT__CB_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x15;
pub const GRBMA_PERFCOUNTER1_SELECT__EA_LINK_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x17;
pub const GRBMA_PERFCOUNTER1_SELECT__AIGC_CAC_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x18;
pub const GRBMA_PERFCOUNTER1_SELECT__BCI_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x19;
pub const GRBMA_PERFCOUNTER1_SELECT__RLC_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x1a;
pub const GRBMA_PERFCOUNTER1_SELECT__TCP_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x1b;
pub const GRBMA_PERFCOUNTER1_SELECT__GE_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x1c;
pub const GRBMA_PERFCOUNTER1_SELECT__UTCL1_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x1d;
pub const GRBMA_PERFCOUNTER1_SELECT__EA_BUSY_USER_DEFINED_MASK__SHIFT: c_uint = 0x1e;
pub const GRBMA_PERFCOUNTER1_SELECT__PERF_SEL_MASK: c_uint = 0x0000003FL;
pub const GRBMA_PERFCOUNTER1_SELECT__GL1CC_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00000040L;
pub const GRBMA_PERFCOUNTER1_SELECT__GL1XCC_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00000080L;
pub const GRBMA_PERFCOUNTER1_SELECT__PMR_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00000100L;
pub const GRBMA_PERFCOUNTER1_SELECT__SC_CLEAN_USER_DEFINED_MASK_MASK: c_uint = 0x00000200L;
pub const GRBMA_PERFCOUNTER1_SELECT__WGS_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00000400L;
pub const GRBMA_PERFCOUNTER1_SELECT__DB_CLEAN_USER_DEFINED_MASK_MASK: c_uint = 0x00000800L;
pub const GRBMA_PERFCOUNTER1_SELECT__CB_CLEAN_USER_DEFINED_MASK_MASK: c_uint = 0x00001000L;
pub const GRBMA_PERFCOUNTER1_SELECT__TA_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00002000L;
pub const GRBMA_PERFCOUNTER1_SELECT__SX_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00004000L;
pub const GRBMA_PERFCOUNTER1_SELECT__GL2C_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00008000L;
pub const GRBMA_PERFCOUNTER1_SELECT__SPI_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00010000L;
pub const GRBMA_PERFCOUNTER1_SELECT__XCAC_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00020000L;
pub const GRBMA_PERFCOUNTER1_SELECT__PA_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00040000L;
pub const GRBMA_PERFCOUNTER1_SELECT__GL2A_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00080000L;
pub const GRBMA_PERFCOUNTER1_SELECT__DB_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00100000L;
pub const GRBMA_PERFCOUNTER1_SELECT__CB_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00200000L;
pub const GRBMA_PERFCOUNTER1_SELECT__EA_LINK_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x00800000L;
pub const GRBMA_PERFCOUNTER1_SELECT__AIGC_CAC_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x01000000L;
pub const GRBMA_PERFCOUNTER1_SELECT__BCI_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x02000000L;
pub const GRBMA_PERFCOUNTER1_SELECT__RLC_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x04000000L;
pub const GRBMA_PERFCOUNTER1_SELECT__TCP_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x08000000L;
pub const GRBMA_PERFCOUNTER1_SELECT__GE_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x10000000L;
pub const GRBMA_PERFCOUNTER1_SELECT__UTCL1_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x20000000L;
pub const GRBMA_PERFCOUNTER1_SELECT__EA_BUSY_USER_DEFINED_MASK_MASK: c_uint = 0x40000000L;
// AID_PERFMON_CNTL
pub const AID_PERFMON_CNTL__PERFMON_STATE__SHIFT: c_uint = 0x0;
pub const AID_PERFMON_CNTL__SPM_PERFMON_STATE__SHIFT: c_uint = 0x4;
pub const AID_PERFMON_CNTL__PERFMON_ENABLE_MODE__SHIFT: c_uint = 0x8;
pub const AID_PERFMON_CNTL__PERFMON_SAMPLE_ENABLE__SHIFT: c_uint = 0xa;
pub const AID_PERFMON_CNTL__PERFMON_STATE_MASK: c_uint = 0x0000000FL;
pub const AID_PERFMON_CNTL__SPM_PERFMON_STATE_MASK: c_uint = 0x000000F0L;
pub const AID_PERFMON_CNTL__PERFMON_ENABLE_MODE_MASK: c_uint = 0x00000300L;
pub const AID_PERFMON_CNTL__PERFMON_SAMPLE_ENABLE_MASK: c_uint = 0x00000400L;
// addressBlock: aigc_gl2x_gfx_se_perfsdec
// GL2C_PERFCOUNTER0_SELECT
pub const GL2C_PERFCOUNTER0_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GL2C_PERFCOUNTER0_SELECT__PERF_SEL1__SHIFT: c_uint = 0xa;
pub const GL2C_PERFCOUNTER0_SELECT__CNTR_MODE__SHIFT: c_uint = 0x14;
pub const GL2C_PERFCOUNTER0_SELECT__PERF_MODE1__SHIFT: c_uint = 0x18;
pub const GL2C_PERFCOUNTER0_SELECT__PERF_MODE__SHIFT: c_uint = 0x1c;
pub const GL2C_PERFCOUNTER0_SELECT__PERF_SEL_MASK: c_uint = 0x000003FFL;
pub const GL2C_PERFCOUNTER0_SELECT__PERF_SEL1_MASK: c_uint = 0x000FFC00L;
pub const GL2C_PERFCOUNTER0_SELECT__CNTR_MODE_MASK: c_uint = 0x00F00000L;
pub const GL2C_PERFCOUNTER0_SELECT__PERF_MODE1_MASK: c_uint = 0x0F000000L;
pub const GL2C_PERFCOUNTER0_SELECT__PERF_MODE_MASK: c_uint = 0xF0000000L;
// GL2C_PERFCOUNTER0_SELECT1
pub const GL2C_PERFCOUNTER0_SELECT1__PERF_SEL2__SHIFT: c_uint = 0x0;
pub const GL2C_PERFCOUNTER0_SELECT1__PERF_SEL3__SHIFT: c_uint = 0xa;
pub const GL2C_PERFCOUNTER0_SELECT1__PERF_MODE3__SHIFT: c_uint = 0x18;
pub const GL2C_PERFCOUNTER0_SELECT1__PERF_MODE2__SHIFT: c_uint = 0x1c;
pub const GL2C_PERFCOUNTER0_SELECT1__PERF_SEL2_MASK: c_uint = 0x000003FFL;
pub const GL2C_PERFCOUNTER0_SELECT1__PERF_SEL3_MASK: c_uint = 0x000FFC00L;
pub const GL2C_PERFCOUNTER0_SELECT1__PERF_MODE3_MASK: c_uint = 0x0F000000L;
pub const GL2C_PERFCOUNTER0_SELECT1__PERF_MODE2_MASK: c_uint = 0xF0000000L;
// GL2C_PERFCOUNTER1_SELECT
pub const GL2C_PERFCOUNTER1_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GL2C_PERFCOUNTER1_SELECT__PERF_SEL1__SHIFT: c_uint = 0xa;
pub const GL2C_PERFCOUNTER1_SELECT__CNTR_MODE__SHIFT: c_uint = 0x14;
pub const GL2C_PERFCOUNTER1_SELECT__PERF_MODE1__SHIFT: c_uint = 0x18;
pub const GL2C_PERFCOUNTER1_SELECT__PERF_MODE__SHIFT: c_uint = 0x1c;
pub const GL2C_PERFCOUNTER1_SELECT__PERF_SEL_MASK: c_uint = 0x000003FFL;
pub const GL2C_PERFCOUNTER1_SELECT__PERF_SEL1_MASK: c_uint = 0x000FFC00L;
pub const GL2C_PERFCOUNTER1_SELECT__CNTR_MODE_MASK: c_uint = 0x00F00000L;
pub const GL2C_PERFCOUNTER1_SELECT__PERF_MODE1_MASK: c_uint = 0x0F000000L;
pub const GL2C_PERFCOUNTER1_SELECT__PERF_MODE_MASK: c_uint = 0xF0000000L;
// GL2C_PERFCOUNTER1_SELECT1
pub const GL2C_PERFCOUNTER1_SELECT1__PERF_SEL2__SHIFT: c_uint = 0x0;
pub const GL2C_PERFCOUNTER1_SELECT1__PERF_SEL3__SHIFT: c_uint = 0xa;
pub const GL2C_PERFCOUNTER1_SELECT1__PERF_MODE3__SHIFT: c_uint = 0x18;
pub const GL2C_PERFCOUNTER1_SELECT1__PERF_MODE2__SHIFT: c_uint = 0x1c;
pub const GL2C_PERFCOUNTER1_SELECT1__PERF_SEL2_MASK: c_uint = 0x000003FFL;
pub const GL2C_PERFCOUNTER1_SELECT1__PERF_SEL3_MASK: c_uint = 0x000FFC00L;
pub const GL2C_PERFCOUNTER1_SELECT1__PERF_MODE3_MASK: c_uint = 0x0F000000L;
pub const GL2C_PERFCOUNTER1_SELECT1__PERF_MODE2_MASK: c_uint = 0xF0000000L;
// GL2C_PERFCOUNTER2_SELECT
pub const GL2C_PERFCOUNTER2_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GL2C_PERFCOUNTER2_SELECT__PERF_SEL1__SHIFT: c_uint = 0xa;
pub const GL2C_PERFCOUNTER2_SELECT__CNTR_MODE__SHIFT: c_uint = 0x14;
pub const GL2C_PERFCOUNTER2_SELECT__PERF_MODE1__SHIFT: c_uint = 0x18;
pub const GL2C_PERFCOUNTER2_SELECT__PERF_MODE__SHIFT: c_uint = 0x1c;
pub const GL2C_PERFCOUNTER2_SELECT__PERF_SEL_MASK: c_uint = 0x000003FFL;
pub const GL2C_PERFCOUNTER2_SELECT__PERF_SEL1_MASK: c_uint = 0x000FFC00L;
pub const GL2C_PERFCOUNTER2_SELECT__CNTR_MODE_MASK: c_uint = 0x00F00000L;
pub const GL2C_PERFCOUNTER2_SELECT__PERF_MODE1_MASK: c_uint = 0x0F000000L;
pub const GL2C_PERFCOUNTER2_SELECT__PERF_MODE_MASK: c_uint = 0xF0000000L;
// GL2C_PERFCOUNTER2_SELECT1
pub const GL2C_PERFCOUNTER2_SELECT1__PERF_SEL2__SHIFT: c_uint = 0x0;
pub const GL2C_PERFCOUNTER2_SELECT1__PERF_SEL3__SHIFT: c_uint = 0xa;
pub const GL2C_PERFCOUNTER2_SELECT1__PERF_MODE3__SHIFT: c_uint = 0x18;
pub const GL2C_PERFCOUNTER2_SELECT1__PERF_MODE2__SHIFT: c_uint = 0x1c;
pub const GL2C_PERFCOUNTER2_SELECT1__PERF_SEL2_MASK: c_uint = 0x000003FFL;
pub const GL2C_PERFCOUNTER2_SELECT1__PERF_SEL3_MASK: c_uint = 0x000FFC00L;
pub const GL2C_PERFCOUNTER2_SELECT1__PERF_MODE3_MASK: c_uint = 0x0F000000L;
pub const GL2C_PERFCOUNTER2_SELECT1__PERF_MODE2_MASK: c_uint = 0xF0000000L;
// GL2C_PERFCOUNTER3_SELECT
pub const GL2C_PERFCOUNTER3_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GL2C_PERFCOUNTER3_SELECT__PERF_SEL1__SHIFT: c_uint = 0xa;
pub const GL2C_PERFCOUNTER3_SELECT__CNTR_MODE__SHIFT: c_uint = 0x14;
pub const GL2C_PERFCOUNTER3_SELECT__PERF_MODE1__SHIFT: c_uint = 0x18;
pub const GL2C_PERFCOUNTER3_SELECT__PERF_MODE__SHIFT: c_uint = 0x1c;
pub const GL2C_PERFCOUNTER3_SELECT__PERF_SEL_MASK: c_uint = 0x000003FFL;
pub const GL2C_PERFCOUNTER3_SELECT__PERF_SEL1_MASK: c_uint = 0x000FFC00L;
pub const GL2C_PERFCOUNTER3_SELECT__CNTR_MODE_MASK: c_uint = 0x00F00000L;
pub const GL2C_PERFCOUNTER3_SELECT__PERF_MODE1_MASK: c_uint = 0x0F000000L;
pub const GL2C_PERFCOUNTER3_SELECT__PERF_MODE_MASK: c_uint = 0xF0000000L;
// GL2C_PERFCOUNTER3_SELECT1
pub const GL2C_PERFCOUNTER3_SELECT1__PERF_SEL2__SHIFT: c_uint = 0x0;
pub const GL2C_PERFCOUNTER3_SELECT1__PERF_SEL3__SHIFT: c_uint = 0xa;
pub const GL2C_PERFCOUNTER3_SELECT1__PERF_MODE3__SHIFT: c_uint = 0x18;
pub const GL2C_PERFCOUNTER3_SELECT1__PERF_MODE2__SHIFT: c_uint = 0x1c;
pub const GL2C_PERFCOUNTER3_SELECT1__PERF_SEL2_MASK: c_uint = 0x000003FFL;
pub const GL2C_PERFCOUNTER3_SELECT1__PERF_SEL3_MASK: c_uint = 0x000FFC00L;
pub const GL2C_PERFCOUNTER3_SELECT1__PERF_MODE3_MASK: c_uint = 0x0F000000L;
pub const GL2C_PERFCOUNTER3_SELECT1__PERF_MODE2_MASK: c_uint = 0xF0000000L;
// GL2A_PERFCOUNTER0_SELECT
pub const GL2A_PERFCOUNTER0_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GL2A_PERFCOUNTER0_SELECT__PERF_SEL1__SHIFT: c_uint = 0xa;
pub const GL2A_PERFCOUNTER0_SELECT__CNTR_MODE__SHIFT: c_uint = 0x14;
pub const GL2A_PERFCOUNTER0_SELECT__PERF_MODE1__SHIFT: c_uint = 0x18;
pub const GL2A_PERFCOUNTER0_SELECT__PERF_MODE__SHIFT: c_uint = 0x1c;
pub const GL2A_PERFCOUNTER0_SELECT__PERF_SEL_MASK: c_uint = 0x000003FFL;
pub const GL2A_PERFCOUNTER0_SELECT__PERF_SEL1_MASK: c_uint = 0x000FFC00L;
pub const GL2A_PERFCOUNTER0_SELECT__CNTR_MODE_MASK: c_uint = 0x00F00000L;
pub const GL2A_PERFCOUNTER0_SELECT__PERF_MODE1_MASK: c_uint = 0x0F000000L;
pub const GL2A_PERFCOUNTER0_SELECT__PERF_MODE_MASK: c_uint = 0xF0000000L;
// GL2A_PERFCOUNTER0_SELECT1
pub const GL2A_PERFCOUNTER0_SELECT1__PERF_SEL2__SHIFT: c_uint = 0x0;
pub const GL2A_PERFCOUNTER0_SELECT1__PERF_SEL3__SHIFT: c_uint = 0xa;
pub const GL2A_PERFCOUNTER0_SELECT1__PERF_MODE3__SHIFT: c_uint = 0x18;
pub const GL2A_PERFCOUNTER0_SELECT1__PERF_MODE2__SHIFT: c_uint = 0x1c;
pub const GL2A_PERFCOUNTER0_SELECT1__PERF_SEL2_MASK: c_uint = 0x000003FFL;
pub const GL2A_PERFCOUNTER0_SELECT1__PERF_SEL3_MASK: c_uint = 0x000FFC00L;
pub const GL2A_PERFCOUNTER0_SELECT1__PERF_MODE3_MASK: c_uint = 0x0F000000L;
pub const GL2A_PERFCOUNTER0_SELECT1__PERF_MODE2_MASK: c_uint = 0xF0000000L;
// GL2A_PERFCOUNTER1_SELECT
pub const GL2A_PERFCOUNTER1_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GL2A_PERFCOUNTER1_SELECT__PERF_SEL1__SHIFT: c_uint = 0xa;
pub const GL2A_PERFCOUNTER1_SELECT__CNTR_MODE__SHIFT: c_uint = 0x14;
pub const GL2A_PERFCOUNTER1_SELECT__PERF_MODE1__SHIFT: c_uint = 0x18;
pub const GL2A_PERFCOUNTER1_SELECT__PERF_MODE__SHIFT: c_uint = 0x1c;
pub const GL2A_PERFCOUNTER1_SELECT__PERF_SEL_MASK: c_uint = 0x000003FFL;
pub const GL2A_PERFCOUNTER1_SELECT__PERF_SEL1_MASK: c_uint = 0x000FFC00L;
pub const GL2A_PERFCOUNTER1_SELECT__CNTR_MODE_MASK: c_uint = 0x00F00000L;
pub const GL2A_PERFCOUNTER1_SELECT__PERF_MODE1_MASK: c_uint = 0x0F000000L;
pub const GL2A_PERFCOUNTER1_SELECT__PERF_MODE_MASK: c_uint = 0xF0000000L;
// GL2A_PERFCOUNTER1_SELECT1
pub const GL2A_PERFCOUNTER1_SELECT1__PERF_SEL2__SHIFT: c_uint = 0x0;
pub const GL2A_PERFCOUNTER1_SELECT1__PERF_SEL3__SHIFT: c_uint = 0xa;
pub const GL2A_PERFCOUNTER1_SELECT1__PERF_MODE3__SHIFT: c_uint = 0x18;
pub const GL2A_PERFCOUNTER1_SELECT1__PERF_MODE2__SHIFT: c_uint = 0x1c;
pub const GL2A_PERFCOUNTER1_SELECT1__PERF_SEL2_MASK: c_uint = 0x000003FFL;
pub const GL2A_PERFCOUNTER1_SELECT1__PERF_SEL3_MASK: c_uint = 0x000FFC00L;
pub const GL2A_PERFCOUNTER1_SELECT1__PERF_MODE3_MASK: c_uint = 0x0F000000L;
pub const GL2A_PERFCOUNTER1_SELECT1__PERF_MODE2_MASK: c_uint = 0xF0000000L;
// GL2A_PERFCOUNTER2_SELECT
pub const GL2A_PERFCOUNTER2_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GL2A_PERFCOUNTER2_SELECT__PERF_SEL1__SHIFT: c_uint = 0xa;
pub const GL2A_PERFCOUNTER2_SELECT__CNTR_MODE__SHIFT: c_uint = 0x14;
pub const GL2A_PERFCOUNTER2_SELECT__PERF_MODE1__SHIFT: c_uint = 0x18;
pub const GL2A_PERFCOUNTER2_SELECT__PERF_MODE__SHIFT: c_uint = 0x1c;
pub const GL2A_PERFCOUNTER2_SELECT__PERF_SEL_MASK: c_uint = 0x000003FFL;
pub const GL2A_PERFCOUNTER2_SELECT__PERF_SEL1_MASK: c_uint = 0x000FFC00L;
pub const GL2A_PERFCOUNTER2_SELECT__CNTR_MODE_MASK: c_uint = 0x00F00000L;
pub const GL2A_PERFCOUNTER2_SELECT__PERF_MODE1_MASK: c_uint = 0x0F000000L;
pub const GL2A_PERFCOUNTER2_SELECT__PERF_MODE_MASK: c_uint = 0xF0000000L;
// GL2A_PERFCOUNTER2_SELECT1
pub const GL2A_PERFCOUNTER2_SELECT1__PERF_SEL2__SHIFT: c_uint = 0x0;
pub const GL2A_PERFCOUNTER2_SELECT1__PERF_SEL3__SHIFT: c_uint = 0xa;
pub const GL2A_PERFCOUNTER2_SELECT1__PERF_MODE3__SHIFT: c_uint = 0x18;
pub const GL2A_PERFCOUNTER2_SELECT1__PERF_MODE2__SHIFT: c_uint = 0x1c;
pub const GL2A_PERFCOUNTER2_SELECT1__PERF_SEL2_MASK: c_uint = 0x000003FFL;
pub const GL2A_PERFCOUNTER2_SELECT1__PERF_SEL3_MASK: c_uint = 0x000FFC00L;
pub const GL2A_PERFCOUNTER2_SELECT1__PERF_MODE3_MASK: c_uint = 0x0F000000L;
pub const GL2A_PERFCOUNTER2_SELECT1__PERF_MODE2_MASK: c_uint = 0xF0000000L;
// GL2A_PERFCOUNTER3_SELECT
pub const GL2A_PERFCOUNTER3_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GL2A_PERFCOUNTER3_SELECT__PERF_SEL1__SHIFT: c_uint = 0xa;
pub const GL2A_PERFCOUNTER3_SELECT__CNTR_MODE__SHIFT: c_uint = 0x14;
pub const GL2A_PERFCOUNTER3_SELECT__PERF_MODE1__SHIFT: c_uint = 0x18;
pub const GL2A_PERFCOUNTER3_SELECT__PERF_MODE__SHIFT: c_uint = 0x1c;
pub const GL2A_PERFCOUNTER3_SELECT__PERF_SEL_MASK: c_uint = 0x000003FFL;
pub const GL2A_PERFCOUNTER3_SELECT__PERF_SEL1_MASK: c_uint = 0x000FFC00L;
pub const GL2A_PERFCOUNTER3_SELECT__CNTR_MODE_MASK: c_uint = 0x00F00000L;
pub const GL2A_PERFCOUNTER3_SELECT__PERF_MODE1_MASK: c_uint = 0x0F000000L;
pub const GL2A_PERFCOUNTER3_SELECT__PERF_MODE_MASK: c_uint = 0xF0000000L;
// GL2A_PERFCOUNTER3_SELECT1
pub const GL2A_PERFCOUNTER3_SELECT1__PERF_SEL2__SHIFT: c_uint = 0x0;
pub const GL2A_PERFCOUNTER3_SELECT1__PERF_SEL3__SHIFT: c_uint = 0xa;
pub const GL2A_PERFCOUNTER3_SELECT1__PERF_MODE3__SHIFT: c_uint = 0x18;
pub const GL2A_PERFCOUNTER3_SELECT1__PERF_MODE2__SHIFT: c_uint = 0x1c;
pub const GL2A_PERFCOUNTER3_SELECT1__PERF_SEL2_MASK: c_uint = 0x000003FFL;
pub const GL2A_PERFCOUNTER3_SELECT1__PERF_SEL3_MASK: c_uint = 0x000FFC00L;
pub const GL2A_PERFCOUNTER3_SELECT1__PERF_MODE3_MASK: c_uint = 0x0F000000L;
pub const GL2A_PERFCOUNTER3_SELECT1__PERF_MODE2_MASK: c_uint = 0xF0000000L;
// addressBlock: aigc_gfx_gcea_se_gfx_se_perfsdec
// GC_EA_SE_PERFCOUNTER0_SELECT
pub const GC_EA_SE_PERFCOUNTER0_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GC_EA_SE_PERFCOUNTER0_SELECT__PERF_SEL1__SHIFT: c_uint = 0xa;
pub const GC_EA_SE_PERFCOUNTER0_SELECT__CNTR_MODE__SHIFT: c_uint = 0x14;
pub const GC_EA_SE_PERFCOUNTER0_SELECT__PERF_MODE1__SHIFT: c_uint = 0x18;
pub const GC_EA_SE_PERFCOUNTER0_SELECT__PERF_MODE__SHIFT: c_uint = 0x1c;
pub const GC_EA_SE_PERFCOUNTER0_SELECT__PERF_SEL_MASK: c_uint = 0x000003FFL;
pub const GC_EA_SE_PERFCOUNTER0_SELECT__PERF_SEL1_MASK: c_uint = 0x000FFC00L;
pub const GC_EA_SE_PERFCOUNTER0_SELECT__CNTR_MODE_MASK: c_uint = 0x00F00000L;
pub const GC_EA_SE_PERFCOUNTER0_SELECT__PERF_MODE1_MASK: c_uint = 0x0F000000L;
pub const GC_EA_SE_PERFCOUNTER0_SELECT__PERF_MODE_MASK: c_uint = 0xF0000000L;
// GC_EA_SE_PERFCOUNTER0_SELECT1
pub const GC_EA_SE_PERFCOUNTER0_SELECT1__PERF_SEL2__SHIFT: c_uint = 0x0;
pub const GC_EA_SE_PERFCOUNTER0_SELECT1__PERF_SEL3__SHIFT: c_uint = 0xa;
pub const GC_EA_SE_PERFCOUNTER0_SELECT1__PERF_MODE3__SHIFT: c_uint = 0x18;
pub const GC_EA_SE_PERFCOUNTER0_SELECT1__PERF_MODE2__SHIFT: c_uint = 0x1c;
pub const GC_EA_SE_PERFCOUNTER0_SELECT1__PERF_SEL2_MASK: c_uint = 0x000003FFL;
pub const GC_EA_SE_PERFCOUNTER0_SELECT1__PERF_SEL3_MASK: c_uint = 0x000FFC00L;
pub const GC_EA_SE_PERFCOUNTER0_SELECT1__PERF_MODE3_MASK: c_uint = 0x0F000000L;
pub const GC_EA_SE_PERFCOUNTER0_SELECT1__PERF_MODE2_MASK: c_uint = 0xF0000000L;
// GC_EA_SE_PERFCOUNTER1_SELECT
pub const GC_EA_SE_PERFCOUNTER1_SELECT__PERF_SEL__SHIFT: c_uint = 0x0;
pub const GC_EA_SE_PERFCOUNTER1_SELECT__COUNTER_MODE__SHIFT: c_uint = 0x1c;
pub const GC_EA_SE_PERFCOUNTER1_SELECT__PERF_SEL_MASK: c_uint = 0x000003FFL;
pub const GC_EA_SE_PERFCOUNTER1_SELECT__COUNTER_MODE_MASK: c_uint = 0xF0000000L;
// addressBlock: aigc_gfx_gcea_se_gfx_se_perfddec
// GC_EA_SE_PERFCOUNTER0_LO
pub const GC_EA_SE_PERFCOUNTER0_LO__PERFCOUNTER_LO__SHIFT: c_uint = 0x0;
pub const GC_EA_SE_PERFCOUNTER0_LO__PERFCOUNTER_LO_MASK: c_uint = 0xFFFFFFFFL;
// GC_EA_SE_PERFCOUNTER0_HI
pub const GC_EA_SE_PERFCOUNTER0_HI__PERFCOUNTER_HI__SHIFT: c_uint = 0x0;
pub const GC_EA_SE_PERFCOUNTER0_HI__PERFCOUNTER_HI_MASK: c_uint = 0xFFFFFFFFL;
// GC_EA_SE_PERFCOUNTER1_LO
pub const GC_EA_SE_PERFCOUNTER1_LO__PERFCOUNTER_LO__SHIFT: c_uint = 0x0;
pub const GC_EA_SE_PERFCOUNTER1_LO__PERFCOUNTER_LO_MASK: c_uint = 0xFFFFFFFFL;
// GC_EA_SE_PERFCOUNTER1_HI
pub const GC_EA_SE_PERFCOUNTER1_HI__PERFCOUNTER_HI__SHIFT: c_uint = 0x0;
pub const GC_EA_SE_PERFCOUNTER1_HI__PERFCOUNTER_HI_MASK: c_uint = 0xFFFFFFFFL;
