//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/amd/include/asic_reg/gc/gc_9_4_1_sh_mask.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// Copyright (C) 2020  Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
// AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

// Macro flag: #define _gc_9_4_1_SH_MASK_HEADER
// addressBlock: gc_cppdec2
// CPF_EDC_TAG_CNT
pub const CPF_EDC_TAG_CNT__DED_COUNT__SHIFT: c_uint = 0x0;
pub const CPF_EDC_TAG_CNT__SEC_COUNT__SHIFT: c_uint = 0x2;
pub const CPF_EDC_TAG_CNT__DED_COUNT_MASK: c_uint = 0x00000003L;
pub const CPF_EDC_TAG_CNT__SEC_COUNT_MASK: c_uint = 0x0000000CL;
// CPF_EDC_ROQ_CNT
pub const CPF_EDC_ROQ_CNT__DED_COUNT_ME1__SHIFT: c_uint = 0x0;
pub const CPF_EDC_ROQ_CNT__SEC_COUNT_ME1__SHIFT: c_uint = 0x2;
pub const CPF_EDC_ROQ_CNT__DED_COUNT_ME2__SHIFT: c_uint = 0x4;
pub const CPF_EDC_ROQ_CNT__SEC_COUNT_ME2__SHIFT: c_uint = 0x6;
pub const CPF_EDC_ROQ_CNT__DED_COUNT_ME1_MASK: c_uint = 0x00000003L;
pub const CPF_EDC_ROQ_CNT__SEC_COUNT_ME1_MASK: c_uint = 0x0000000CL;
pub const CPF_EDC_ROQ_CNT__DED_COUNT_ME2_MASK: c_uint = 0x00000030L;
pub const CPF_EDC_ROQ_CNT__SEC_COUNT_ME2_MASK: c_uint = 0x000000C0L;
// CPG_EDC_TAG_CNT
pub const CPG_EDC_TAG_CNT__DED_COUNT__SHIFT: c_uint = 0x0;
pub const CPG_EDC_TAG_CNT__SEC_COUNT__SHIFT: c_uint = 0x2;
pub const CPG_EDC_TAG_CNT__DED_COUNT_MASK: c_uint = 0x00000003L;
pub const CPG_EDC_TAG_CNT__SEC_COUNT_MASK: c_uint = 0x0000000CL;
// CPG_EDC_DMA_CNT
pub const CPG_EDC_DMA_CNT__ROQ_DED_COUNT__SHIFT: c_uint = 0x0;
pub const CPG_EDC_DMA_CNT__ROQ_SEC_COUNT__SHIFT: c_uint = 0x2;
pub const CPG_EDC_DMA_CNT__TAG_DED_COUNT__SHIFT: c_uint = 0x4;
pub const CPG_EDC_DMA_CNT__TAG_SEC_COUNT__SHIFT: c_uint = 0x6;
pub const CPG_EDC_DMA_CNT__ROQ_DED_COUNT_MASK: c_uint = 0x00000003L;
pub const CPG_EDC_DMA_CNT__ROQ_SEC_COUNT_MASK: c_uint = 0x0000000CL;
pub const CPG_EDC_DMA_CNT__TAG_DED_COUNT_MASK: c_uint = 0x00000030L;
pub const CPG_EDC_DMA_CNT__TAG_SEC_COUNT_MASK: c_uint = 0x000000C0L;
// CPC_EDC_SCRATCH_CNT
pub const CPC_EDC_SCRATCH_CNT__DED_COUNT__SHIFT: c_uint = 0x0;
pub const CPC_EDC_SCRATCH_CNT__SEC_COUNT__SHIFT: c_uint = 0x2;
pub const CPC_EDC_SCRATCH_CNT__DED_COUNT_MASK: c_uint = 0x00000003L;
pub const CPC_EDC_SCRATCH_CNT__SEC_COUNT_MASK: c_uint = 0x0000000CL;
// CPC_EDC_UCODE_CNT
pub const CPC_EDC_UCODE_CNT__DED_COUNT__SHIFT: c_uint = 0x0;
pub const CPC_EDC_UCODE_CNT__SEC_COUNT__SHIFT: c_uint = 0x2;
pub const CPC_EDC_UCODE_CNT__DED_COUNT_MASK: c_uint = 0x00000003L;
pub const CPC_EDC_UCODE_CNT__SEC_COUNT_MASK: c_uint = 0x0000000CL;
// DC_EDC_STATE_CNT
pub const DC_EDC_STATE_CNT__DED_COUNT_ME1__SHIFT: c_uint = 0x0;
pub const DC_EDC_STATE_CNT__SEC_COUNT_ME1__SHIFT: c_uint = 0x2;
pub const DC_EDC_STATE_CNT__DED_COUNT_ME1_MASK: c_uint = 0x00000003L;
pub const DC_EDC_STATE_CNT__SEC_COUNT_ME1_MASK: c_uint = 0x0000000CL;
// DC_EDC_CSINVOC_CNT
pub const DC_EDC_CSINVOC_CNT__DED_COUNT_ME1__SHIFT: c_uint = 0x0;
pub const DC_EDC_CSINVOC_CNT__SEC_COUNT_ME1__SHIFT: c_uint = 0x2;
pub const DC_EDC_CSINVOC_CNT__DED_COUNT1_ME1__SHIFT: c_uint = 0x4;
pub const DC_EDC_CSINVOC_CNT__SEC_COUNT1_ME1__SHIFT: c_uint = 0x6;
pub const DC_EDC_CSINVOC_CNT__DED_COUNT_ME1_MASK: c_uint = 0x00000003L;
pub const DC_EDC_CSINVOC_CNT__SEC_COUNT_ME1_MASK: c_uint = 0x0000000CL;
pub const DC_EDC_CSINVOC_CNT__DED_COUNT1_ME1_MASK: c_uint = 0x00000030L;
pub const DC_EDC_CSINVOC_CNT__SEC_COUNT1_ME1_MASK: c_uint = 0x000000C0L;
// DC_EDC_RESTORE_CNT
pub const DC_EDC_RESTORE_CNT__DED_COUNT_ME1__SHIFT: c_uint = 0x0;
pub const DC_EDC_RESTORE_CNT__SEC_COUNT_ME1__SHIFT: c_uint = 0x2;
pub const DC_EDC_RESTORE_CNT__DED_COUNT1_ME1__SHIFT: c_uint = 0x4;
pub const DC_EDC_RESTORE_CNT__SEC_COUNT1_ME1__SHIFT: c_uint = 0x6;
pub const DC_EDC_RESTORE_CNT__DED_COUNT_ME1_MASK: c_uint = 0x00000003L;
pub const DC_EDC_RESTORE_CNT__SEC_COUNT_ME1_MASK: c_uint = 0x0000000CL;
pub const DC_EDC_RESTORE_CNT__DED_COUNT1_ME1_MASK: c_uint = 0x00000030L;
pub const DC_EDC_RESTORE_CNT__SEC_COUNT1_ME1_MASK: c_uint = 0x000000C0L;
// addressBlock: gc_gdsdec
// GDS_EDC_CNT
pub const GDS_EDC_CNT__GDS_MEM_DED__SHIFT: c_uint = 0x0;
pub const GDS_EDC_CNT__GDS_MEM_SEC__SHIFT: c_uint = 0x4;
pub const GDS_EDC_CNT__UNUSED__SHIFT: c_uint = 0x6;
pub const GDS_EDC_CNT__GDS_MEM_DED_MASK: c_uint = 0x00000003L;
pub const GDS_EDC_CNT__GDS_MEM_SEC_MASK: c_uint = 0x00000030L;
pub const GDS_EDC_CNT__UNUSED_MASK: c_uint = 0xFFFFFFC0L;
// GDS_EDC_GRBM_CNT
pub const GDS_EDC_GRBM_CNT__DED__SHIFT: c_uint = 0x0;
pub const GDS_EDC_GRBM_CNT__SEC__SHIFT: c_uint = 0x2;
pub const GDS_EDC_GRBM_CNT__UNUSED__SHIFT: c_uint = 0x4;
pub const GDS_EDC_GRBM_CNT__DED_MASK: c_uint = 0x00000003L;
pub const GDS_EDC_GRBM_CNT__SEC_MASK: c_uint = 0x0000000CL;
pub const GDS_EDC_GRBM_CNT__UNUSED_MASK: c_uint = 0xFFFFFFF0L;
// GDS_EDC_OA_DED
pub const GDS_EDC_OA_DED__ME0_GFXHP3D_PIX_DED__SHIFT: c_uint = 0x0;
pub const GDS_EDC_OA_DED__ME0_GFXHP3D_VTX_DED__SHIFT: c_uint = 0x1;
pub const GDS_EDC_OA_DED__ME0_CS_DED__SHIFT: c_uint = 0x2;
pub const GDS_EDC_OA_DED__ME0_GFXHP3D_GS_DED__SHIFT: c_uint = 0x3;
pub const GDS_EDC_OA_DED__ME1_PIPE0_DED__SHIFT: c_uint = 0x4;
pub const GDS_EDC_OA_DED__ME1_PIPE1_DED__SHIFT: c_uint = 0x5;
pub const GDS_EDC_OA_DED__ME1_PIPE2_DED__SHIFT: c_uint = 0x6;
pub const GDS_EDC_OA_DED__ME1_PIPE3_DED__SHIFT: c_uint = 0x7;
pub const GDS_EDC_OA_DED__ME2_PIPE0_DED__SHIFT: c_uint = 0x8;
pub const GDS_EDC_OA_DED__ME2_PIPE1_DED__SHIFT: c_uint = 0x9;
pub const GDS_EDC_OA_DED__ME2_PIPE2_DED__SHIFT: c_uint = 0xa;
pub const GDS_EDC_OA_DED__ME2_PIPE3_DED__SHIFT: c_uint = 0xb;
pub const GDS_EDC_OA_DED__UNUSED1__SHIFT: c_uint = 0xc;
pub const GDS_EDC_OA_DED__ME0_GFXHP3D_PIX_DED_MASK: c_uint = 0x00000001L;
pub const GDS_EDC_OA_DED__ME0_GFXHP3D_VTX_DED_MASK: c_uint = 0x00000002L;
pub const GDS_EDC_OA_DED__ME0_CS_DED_MASK: c_uint = 0x00000004L;
pub const GDS_EDC_OA_DED__ME0_GFXHP3D_GS_DED_MASK: c_uint = 0x00000008L;
pub const GDS_EDC_OA_DED__ME1_PIPE0_DED_MASK: c_uint = 0x00000010L;
pub const GDS_EDC_OA_DED__ME1_PIPE1_DED_MASK: c_uint = 0x00000020L;
pub const GDS_EDC_OA_DED__ME1_PIPE2_DED_MASK: c_uint = 0x00000040L;
pub const GDS_EDC_OA_DED__ME1_PIPE3_DED_MASK: c_uint = 0x00000080L;
pub const GDS_EDC_OA_DED__ME2_PIPE0_DED_MASK: c_uint = 0x00000100L;
pub const GDS_EDC_OA_DED__ME2_PIPE1_DED_MASK: c_uint = 0x00000200L;
pub const GDS_EDC_OA_DED__ME2_PIPE2_DED_MASK: c_uint = 0x00000400L;
pub const GDS_EDC_OA_DED__ME2_PIPE3_DED_MASK: c_uint = 0x00000800L;
pub const GDS_EDC_OA_DED__UNUSED1_MASK: c_uint = 0xFFFFF000L;
// GDS_EDC_OA_PHY_CNT
pub const GDS_EDC_OA_PHY_CNT__ME0_CS_PIPE_MEM_SEC__SHIFT: c_uint = 0x0;
pub const GDS_EDC_OA_PHY_CNT__ME0_CS_PIPE_MEM_DED__SHIFT: c_uint = 0x2;
pub const GDS_EDC_OA_PHY_CNT__PHY_CMD_RAM_MEM_SEC__SHIFT: c_uint = 0x4;
pub const GDS_EDC_OA_PHY_CNT__PHY_CMD_RAM_MEM_DED__SHIFT: c_uint = 0x6;
pub const GDS_EDC_OA_PHY_CNT__PHY_DATA_RAM_MEM_SEC__SHIFT: c_uint = 0x8;
pub const GDS_EDC_OA_PHY_CNT__PHY_DATA_RAM_MEM_DED__SHIFT: c_uint = 0xa;
pub const GDS_EDC_OA_PHY_CNT__UNUSED1__SHIFT: c_uint = 0xc;
pub const GDS_EDC_OA_PHY_CNT__ME0_CS_PIPE_MEM_SEC_MASK: c_uint = 0x00000003L;
pub const GDS_EDC_OA_PHY_CNT__ME0_CS_PIPE_MEM_DED_MASK: c_uint = 0x0000000CL;
pub const GDS_EDC_OA_PHY_CNT__PHY_CMD_RAM_MEM_SEC_MASK: c_uint = 0x00000030L;
pub const GDS_EDC_OA_PHY_CNT__PHY_CMD_RAM_MEM_DED_MASK: c_uint = 0x000000C0L;
pub const GDS_EDC_OA_PHY_CNT__PHY_DATA_RAM_MEM_SEC_MASK: c_uint = 0x00000300L;
pub const GDS_EDC_OA_PHY_CNT__PHY_DATA_RAM_MEM_DED_MASK: c_uint = 0x00000C00L;
pub const GDS_EDC_OA_PHY_CNT__UNUSED1_MASK: c_uint = 0xFFFFF000L;
// GDS_EDC_OA_PIPE_CNT
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE0_PIPE_MEM_SEC__SHIFT: c_uint = 0x0;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE0_PIPE_MEM_DED__SHIFT: c_uint = 0x2;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE1_PIPE_MEM_SEC__SHIFT: c_uint = 0x4;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE1_PIPE_MEM_DED__SHIFT: c_uint = 0x6;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE2_PIPE_MEM_SEC__SHIFT: c_uint = 0x8;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE2_PIPE_MEM_DED__SHIFT: c_uint = 0xa;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE3_PIPE_MEM_SEC__SHIFT: c_uint = 0xc;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE3_PIPE_MEM_DED__SHIFT: c_uint = 0xe;
pub const GDS_EDC_OA_PIPE_CNT__UNUSED__SHIFT: c_uint = 0x10;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE0_PIPE_MEM_SEC_MASK: c_uint = 0x00000003L;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE0_PIPE_MEM_DED_MASK: c_uint = 0x0000000CL;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE1_PIPE_MEM_SEC_MASK: c_uint = 0x00000030L;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE1_PIPE_MEM_DED_MASK: c_uint = 0x000000C0L;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE2_PIPE_MEM_SEC_MASK: c_uint = 0x00000300L;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE2_PIPE_MEM_DED_MASK: c_uint = 0x00000C00L;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE3_PIPE_MEM_SEC_MASK: c_uint = 0x00003000L;
pub const GDS_EDC_OA_PIPE_CNT__ME1_PIPE3_PIPE_MEM_DED_MASK: c_uint = 0x0000C000L;
pub const GDS_EDC_OA_PIPE_CNT__UNUSED_MASK: c_uint = 0xFFFF0000L;
// addressBlock: gc_shsdec
// SPI_EDC_CNT
pub const SPI_EDC_CNT__SPI_SR_MEM_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const SPI_EDC_CNT__SPI_SR_MEM_DED_COUNT__SHIFT: c_uint = 0x2;
pub const SPI_EDC_CNT__SPI_GDS_EXPREQ_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const SPI_EDC_CNT__SPI_GDS_EXPREQ_DED_COUNT__SHIFT: c_uint = 0x6;
pub const SPI_EDC_CNT__SPI_WB_GRANT_30_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const SPI_EDC_CNT__SPI_WB_GRANT_30_DED_COUNT__SHIFT: c_uint = 0xa;
pub const SPI_EDC_CNT__SPI_WB_GRANT_61_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const SPI_EDC_CNT__SPI_WB_GRANT_61_DED_COUNT__SHIFT: c_uint = 0xe;
pub const SPI_EDC_CNT__SPI_LIFE_CNT_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const SPI_EDC_CNT__SPI_LIFE_CNT_DED_COUNT__SHIFT: c_uint = 0x12;
pub const SPI_EDC_CNT__SPI_SR_MEM_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const SPI_EDC_CNT__SPI_SR_MEM_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const SPI_EDC_CNT__SPI_GDS_EXPREQ_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const SPI_EDC_CNT__SPI_GDS_EXPREQ_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const SPI_EDC_CNT__SPI_WB_GRANT_30_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const SPI_EDC_CNT__SPI_WB_GRANT_30_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const SPI_EDC_CNT__SPI_WB_GRANT_61_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const SPI_EDC_CNT__SPI_WB_GRANT_61_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const SPI_EDC_CNT__SPI_LIFE_CNT_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const SPI_EDC_CNT__SPI_LIFE_CNT_DED_COUNT_MASK: c_uint = 0x000C0000L;
// addressBlock: gc_sqdec
// SQC_EDC_CNT2
pub const SQC_EDC_CNT2__INST_BANKA_TAG_RAM_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const SQC_EDC_CNT2__INST_BANKA_TAG_RAM_DED_COUNT__SHIFT: c_uint = 0x2;
pub const SQC_EDC_CNT2__INST_BANKA_BANK_RAM_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const SQC_EDC_CNT2__INST_BANKA_BANK_RAM_DED_COUNT__SHIFT: c_uint = 0x6;
pub const SQC_EDC_CNT2__DATA_BANKA_TAG_RAM_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const SQC_EDC_CNT2__DATA_BANKA_TAG_RAM_DED_COUNT__SHIFT: c_uint = 0xa;
pub const SQC_EDC_CNT2__DATA_BANKA_BANK_RAM_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const SQC_EDC_CNT2__DATA_BANKA_BANK_RAM_DED_COUNT__SHIFT: c_uint = 0xe;
pub const SQC_EDC_CNT2__INST_UTCL1_LFIFO_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const SQC_EDC_CNT2__INST_UTCL1_LFIFO_DED_COUNT__SHIFT: c_uint = 0x12;
pub const SQC_EDC_CNT2__INST_BANKA_TAG_RAM_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const SQC_EDC_CNT2__INST_BANKA_TAG_RAM_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const SQC_EDC_CNT2__INST_BANKA_BANK_RAM_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const SQC_EDC_CNT2__INST_BANKA_BANK_RAM_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const SQC_EDC_CNT2__DATA_BANKA_TAG_RAM_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const SQC_EDC_CNT2__DATA_BANKA_TAG_RAM_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const SQC_EDC_CNT2__DATA_BANKA_BANK_RAM_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const SQC_EDC_CNT2__DATA_BANKA_BANK_RAM_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const SQC_EDC_CNT2__INST_UTCL1_LFIFO_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const SQC_EDC_CNT2__INST_UTCL1_LFIFO_DED_COUNT_MASK: c_uint = 0x000C0000L;
// SQC_EDC_CNT3
pub const SQC_EDC_CNT3__INST_BANKB_TAG_RAM_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const SQC_EDC_CNT3__INST_BANKB_TAG_RAM_DED_COUNT__SHIFT: c_uint = 0x2;
pub const SQC_EDC_CNT3__INST_BANKB_BANK_RAM_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const SQC_EDC_CNT3__INST_BANKB_BANK_RAM_DED_COUNT__SHIFT: c_uint = 0x6;
pub const SQC_EDC_CNT3__DATA_BANKB_TAG_RAM_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const SQC_EDC_CNT3__DATA_BANKB_TAG_RAM_DED_COUNT__SHIFT: c_uint = 0xa;
pub const SQC_EDC_CNT3__DATA_BANKB_BANK_RAM_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const SQC_EDC_CNT3__DATA_BANKB_BANK_RAM_DED_COUNT__SHIFT: c_uint = 0xe;
pub const SQC_EDC_CNT3__INST_BANKB_TAG_RAM_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const SQC_EDC_CNT3__INST_BANKB_TAG_RAM_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const SQC_EDC_CNT3__INST_BANKB_BANK_RAM_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const SQC_EDC_CNT3__INST_BANKB_BANK_RAM_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const SQC_EDC_CNT3__DATA_BANKB_TAG_RAM_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const SQC_EDC_CNT3__DATA_BANKB_TAG_RAM_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const SQC_EDC_CNT3__DATA_BANKB_BANK_RAM_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const SQC_EDC_CNT3__DATA_BANKB_BANK_RAM_DED_COUNT_MASK: c_uint = 0x0000C000L;
// SQC_EDC_PARITY_CNT3
pub const SQC_EDC_PARITY_CNT3__INST_BANKA_UTCL1_MISS_FIFO_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const SQC_EDC_PARITY_CNT3__INST_BANKA_UTCL1_MISS_FIFO_DED_COUNT__SHIFT: c_uint = 0x2;
pub const SQC_EDC_PARITY_CNT3__INST_BANKA_MISS_FIFO_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const SQC_EDC_PARITY_CNT3__INST_BANKA_MISS_FIFO_DED_COUNT__SHIFT: c_uint = 0x6;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKA_HIT_FIFO_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKA_HIT_FIFO_DED_COUNT__SHIFT: c_uint = 0xa;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKA_MISS_FIFO_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKA_MISS_FIFO_DED_COUNT__SHIFT: c_uint = 0xe;
pub const SQC_EDC_PARITY_CNT3__INST_BANKB_UTCL1_MISS_FIFO_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const SQC_EDC_PARITY_CNT3__INST_BANKB_UTCL1_MISS_FIFO_DED_COUNT__SHIFT: c_uint = 0x12;
pub const SQC_EDC_PARITY_CNT3__INST_BANKB_MISS_FIFO_SEC_COUNT__SHIFT: c_uint = 0x14;
pub const SQC_EDC_PARITY_CNT3__INST_BANKB_MISS_FIFO_DED_COUNT__SHIFT: c_uint = 0x16;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKB_HIT_FIFO_SEC_COUNT__SHIFT: c_uint = 0x18;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKB_HIT_FIFO_DED_COUNT__SHIFT: c_uint = 0x1a;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKB_MISS_FIFO_SEC_COUNT__SHIFT: c_uint = 0x1c;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKB_MISS_FIFO_DED_COUNT__SHIFT: c_uint = 0x1e;
pub const SQC_EDC_PARITY_CNT3__INST_BANKA_UTCL1_MISS_FIFO_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const SQC_EDC_PARITY_CNT3__INST_BANKA_UTCL1_MISS_FIFO_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const SQC_EDC_PARITY_CNT3__INST_BANKA_MISS_FIFO_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const SQC_EDC_PARITY_CNT3__INST_BANKA_MISS_FIFO_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKA_HIT_FIFO_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKA_HIT_FIFO_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKA_MISS_FIFO_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKA_MISS_FIFO_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const SQC_EDC_PARITY_CNT3__INST_BANKB_UTCL1_MISS_FIFO_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const SQC_EDC_PARITY_CNT3__INST_BANKB_UTCL1_MISS_FIFO_DED_COUNT_MASK: c_uint = 0x000C0000L;
pub const SQC_EDC_PARITY_CNT3__INST_BANKB_MISS_FIFO_SEC_COUNT_MASK: c_uint = 0x00300000L;
pub const SQC_EDC_PARITY_CNT3__INST_BANKB_MISS_FIFO_DED_COUNT_MASK: c_uint = 0x00C00000L;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKB_HIT_FIFO_SEC_COUNT_MASK: c_uint = 0x03000000L;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKB_HIT_FIFO_DED_COUNT_MASK: c_uint = 0x0C000000L;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKB_MISS_FIFO_SEC_COUNT_MASK: c_uint = 0x30000000L;
pub const SQC_EDC_PARITY_CNT3__DATA_BANKB_MISS_FIFO_DED_COUNT_MASK: c_uint = 0xC0000000L;
// SQC_EDC_CNT
pub const SQC_EDC_CNT__DATA_CU0_WRITE_DATA_BUF_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const SQC_EDC_CNT__DATA_CU0_WRITE_DATA_BUF_DED_COUNT__SHIFT: c_uint = 0x2;
pub const SQC_EDC_CNT__DATA_CU0_UTCL1_LFIFO_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const SQC_EDC_CNT__DATA_CU0_UTCL1_LFIFO_DED_COUNT__SHIFT: c_uint = 0x6;
pub const SQC_EDC_CNT__DATA_CU1_WRITE_DATA_BUF_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const SQC_EDC_CNT__DATA_CU1_WRITE_DATA_BUF_DED_COUNT__SHIFT: c_uint = 0xa;
pub const SQC_EDC_CNT__DATA_CU1_UTCL1_LFIFO_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const SQC_EDC_CNT__DATA_CU1_UTCL1_LFIFO_DED_COUNT__SHIFT: c_uint = 0xe;
pub const SQC_EDC_CNT__DATA_CU2_WRITE_DATA_BUF_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const SQC_EDC_CNT__DATA_CU2_WRITE_DATA_BUF_DED_COUNT__SHIFT: c_uint = 0x12;
pub const SQC_EDC_CNT__DATA_CU2_UTCL1_LFIFO_SEC_COUNT__SHIFT: c_uint = 0x14;
pub const SQC_EDC_CNT__DATA_CU2_UTCL1_LFIFO_DED_COUNT__SHIFT: c_uint = 0x16;
pub const SQC_EDC_CNT__DATA_CU3_WRITE_DATA_BUF_SEC_COUNT__SHIFT: c_uint = 0x18;
pub const SQC_EDC_CNT__DATA_CU3_WRITE_DATA_BUF_DED_COUNT__SHIFT: c_uint = 0x1a;
pub const SQC_EDC_CNT__DATA_CU3_UTCL1_LFIFO_SEC_COUNT__SHIFT: c_uint = 0x1c;
pub const SQC_EDC_CNT__DATA_CU3_UTCL1_LFIFO_DED_COUNT__SHIFT: c_uint = 0x1e;
pub const SQC_EDC_CNT__DATA_CU0_WRITE_DATA_BUF_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const SQC_EDC_CNT__DATA_CU0_WRITE_DATA_BUF_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const SQC_EDC_CNT__DATA_CU0_UTCL1_LFIFO_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const SQC_EDC_CNT__DATA_CU0_UTCL1_LFIFO_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const SQC_EDC_CNT__DATA_CU1_WRITE_DATA_BUF_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const SQC_EDC_CNT__DATA_CU1_WRITE_DATA_BUF_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const SQC_EDC_CNT__DATA_CU1_UTCL1_LFIFO_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const SQC_EDC_CNT__DATA_CU1_UTCL1_LFIFO_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const SQC_EDC_CNT__DATA_CU2_WRITE_DATA_BUF_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const SQC_EDC_CNT__DATA_CU2_WRITE_DATA_BUF_DED_COUNT_MASK: c_uint = 0x000C0000L;
pub const SQC_EDC_CNT__DATA_CU2_UTCL1_LFIFO_SEC_COUNT_MASK: c_uint = 0x00300000L;
pub const SQC_EDC_CNT__DATA_CU2_UTCL1_LFIFO_DED_COUNT_MASK: c_uint = 0x00C00000L;
pub const SQC_EDC_CNT__DATA_CU3_WRITE_DATA_BUF_SEC_COUNT_MASK: c_uint = 0x03000000L;
pub const SQC_EDC_CNT__DATA_CU3_WRITE_DATA_BUF_DED_COUNT_MASK: c_uint = 0x0C000000L;
pub const SQC_EDC_CNT__DATA_CU3_UTCL1_LFIFO_SEC_COUNT_MASK: c_uint = 0x30000000L;
pub const SQC_EDC_CNT__DATA_CU3_UTCL1_LFIFO_DED_COUNT_MASK: c_uint = 0xC0000000L;
// SQ_EDC_SEC_CNT
pub const SQ_EDC_SEC_CNT__LDS_SEC__SHIFT: c_uint = 0x0;
pub const SQ_EDC_SEC_CNT__SGPR_SEC__SHIFT: c_uint = 0x8;
pub const SQ_EDC_SEC_CNT__VGPR_SEC__SHIFT: c_uint = 0x10;
pub const SQ_EDC_SEC_CNT__LDS_SEC_MASK: c_uint = 0x000000FFL;
pub const SQ_EDC_SEC_CNT__SGPR_SEC_MASK: c_uint = 0x0000FF00L;
pub const SQ_EDC_SEC_CNT__VGPR_SEC_MASK: c_uint = 0x00FF0000L;
// SQ_EDC_DED_CNT
pub const SQ_EDC_DED_CNT__LDS_DED__SHIFT: c_uint = 0x0;
pub const SQ_EDC_DED_CNT__SGPR_DED__SHIFT: c_uint = 0x8;
pub const SQ_EDC_DED_CNT__VGPR_DED__SHIFT: c_uint = 0x10;
pub const SQ_EDC_DED_CNT__LDS_DED_MASK: c_uint = 0x000000FFL;
pub const SQ_EDC_DED_CNT__SGPR_DED_MASK: c_uint = 0x0000FF00L;
pub const SQ_EDC_DED_CNT__VGPR_DED_MASK: c_uint = 0x00FF0000L;
// SQ_EDC_INFO
pub const SQ_EDC_INFO__WAVE_ID__SHIFT: c_uint = 0x0;
pub const SQ_EDC_INFO__SIMD_ID__SHIFT: c_uint = 0x4;
pub const SQ_EDC_INFO__SOURCE__SHIFT: c_uint = 0x6;
pub const SQ_EDC_INFO__VM_ID__SHIFT: c_uint = 0x9;
pub const SQ_EDC_INFO__WAVE_ID_MASK: c_uint = 0x0000000FL;
pub const SQ_EDC_INFO__SIMD_ID_MASK: c_uint = 0x00000030L;
pub const SQ_EDC_INFO__SOURCE_MASK: c_uint = 0x000001C0L;
pub const SQ_EDC_INFO__VM_ID_MASK: c_uint = 0x00001E00L;
// SQ_EDC_CNT
pub const SQ_EDC_CNT__LDS_D_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const SQ_EDC_CNT__LDS_D_DED_COUNT__SHIFT: c_uint = 0x2;
pub const SQ_EDC_CNT__LDS_I_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const SQ_EDC_CNT__LDS_I_DED_COUNT__SHIFT: c_uint = 0x6;
pub const SQ_EDC_CNT__SGPR_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const SQ_EDC_CNT__SGPR_DED_COUNT__SHIFT: c_uint = 0xa;
pub const SQ_EDC_CNT__VGPR0_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const SQ_EDC_CNT__VGPR0_DED_COUNT__SHIFT: c_uint = 0xe;
pub const SQ_EDC_CNT__VGPR1_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const SQ_EDC_CNT__VGPR1_DED_COUNT__SHIFT: c_uint = 0x12;
pub const SQ_EDC_CNT__VGPR2_SEC_COUNT__SHIFT: c_uint = 0x14;
pub const SQ_EDC_CNT__VGPR2_DED_COUNT__SHIFT: c_uint = 0x16;
pub const SQ_EDC_CNT__VGPR3_SEC_COUNT__SHIFT: c_uint = 0x18;
pub const SQ_EDC_CNT__VGPR3_DED_COUNT__SHIFT: c_uint = 0x1a;
pub const SQ_EDC_CNT__LDS_D_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const SQ_EDC_CNT__LDS_D_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const SQ_EDC_CNT__LDS_I_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const SQ_EDC_CNT__LDS_I_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const SQ_EDC_CNT__SGPR_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const SQ_EDC_CNT__SGPR_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const SQ_EDC_CNT__VGPR0_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const SQ_EDC_CNT__VGPR0_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const SQ_EDC_CNT__VGPR1_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const SQ_EDC_CNT__VGPR1_DED_COUNT_MASK: c_uint = 0x000C0000L;
pub const SQ_EDC_CNT__VGPR2_SEC_COUNT_MASK: c_uint = 0x00300000L;
pub const SQ_EDC_CNT__VGPR2_DED_COUNT_MASK: c_uint = 0x00C00000L;
pub const SQ_EDC_CNT__VGPR3_SEC_COUNT_MASK: c_uint = 0x03000000L;
pub const SQ_EDC_CNT__VGPR3_DED_COUNT_MASK: c_uint = 0x0C000000L;
// addressBlock: gc_tpdec
// TA_EDC_CNT
pub const TA_EDC_CNT__TA_FS_DFIFO_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const TA_EDC_CNT__TA_FS_DFIFO_DED_COUNT__SHIFT: c_uint = 0x2;
pub const TA_EDC_CNT__TA_FS_AFIFO_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const TA_EDC_CNT__TA_FS_AFIFO_DED_COUNT__SHIFT: c_uint = 0x6;
pub const TA_EDC_CNT__TA_FL_LFIFO_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const TA_EDC_CNT__TA_FL_LFIFO_DED_COUNT__SHIFT: c_uint = 0xa;
pub const TA_EDC_CNT__TA_FX_LFIFO_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const TA_EDC_CNT__TA_FX_LFIFO_DED_COUNT__SHIFT: c_uint = 0xe;
pub const TA_EDC_CNT__TA_FS_CFIFO_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const TA_EDC_CNT__TA_FS_CFIFO_DED_COUNT__SHIFT: c_uint = 0x12;
pub const TA_EDC_CNT__TA_FS_DFIFO_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const TA_EDC_CNT__TA_FS_DFIFO_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const TA_EDC_CNT__TA_FS_AFIFO_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const TA_EDC_CNT__TA_FS_AFIFO_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const TA_EDC_CNT__TA_FL_LFIFO_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const TA_EDC_CNT__TA_FL_LFIFO_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const TA_EDC_CNT__TA_FX_LFIFO_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const TA_EDC_CNT__TA_FX_LFIFO_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const TA_EDC_CNT__TA_FS_CFIFO_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const TA_EDC_CNT__TA_FS_CFIFO_DED_COUNT_MASK: c_uint = 0x000C0000L;
// addressBlock: gc_tcdec
// TCP_EDC_CNT
pub const TCP_EDC_CNT__SEC_COUNT__SHIFT: c_uint = 0x0;
pub const TCP_EDC_CNT__LFIFO_SED_COUNT__SHIFT: c_uint = 0x8;
pub const TCP_EDC_CNT__DED_COUNT__SHIFT: c_uint = 0x10;
pub const TCP_EDC_CNT__SEC_COUNT_MASK: c_uint = 0x000000FFL;
pub const TCP_EDC_CNT__LFIFO_SED_COUNT_MASK: c_uint = 0x0000FF00L;
pub const TCP_EDC_CNT__DED_COUNT_MASK: c_uint = 0x00FF0000L;
// TCP_EDC_CNT_NEW
pub const TCP_EDC_CNT_NEW__CACHE_RAM_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const TCP_EDC_CNT_NEW__CACHE_RAM_DED_COUNT__SHIFT: c_uint = 0x2;
pub const TCP_EDC_CNT_NEW__LFIFO_RAM_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const TCP_EDC_CNT_NEW__LFIFO_RAM_DED_COUNT__SHIFT: c_uint = 0x6;
pub const TCP_EDC_CNT_NEW__CMD_FIFO_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const TCP_EDC_CNT_NEW__CMD_FIFO_DED_COUNT__SHIFT: c_uint = 0xa;
pub const TCP_EDC_CNT_NEW__VM_FIFO_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const TCP_EDC_CNT_NEW__VM_FIFO_DED_COUNT__SHIFT: c_uint = 0xe;
pub const TCP_EDC_CNT_NEW__DB_RAM_SED_COUNT__SHIFT: c_uint = 0x10;
pub const TCP_EDC_CNT_NEW__UTCL1_LFIFO0_SEC_COUNT__SHIFT: c_uint = 0x12;
pub const TCP_EDC_CNT_NEW__UTCL1_LFIFO0_DED_COUNT__SHIFT: c_uint = 0x14;
pub const TCP_EDC_CNT_NEW__UTCL1_LFIFO1_SEC_COUNT__SHIFT: c_uint = 0x16;
pub const TCP_EDC_CNT_NEW__UTCL1_LFIFO1_DED_COUNT__SHIFT: c_uint = 0x18;
pub const TCP_EDC_CNT_NEW__CACHE_RAM_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const TCP_EDC_CNT_NEW__CACHE_RAM_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const TCP_EDC_CNT_NEW__LFIFO_RAM_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const TCP_EDC_CNT_NEW__LFIFO_RAM_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const TCP_EDC_CNT_NEW__CMD_FIFO_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const TCP_EDC_CNT_NEW__CMD_FIFO_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const TCP_EDC_CNT_NEW__VM_FIFO_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const TCP_EDC_CNT_NEW__VM_FIFO_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const TCP_EDC_CNT_NEW__DB_RAM_SED_COUNT_MASK: c_uint = 0x00030000L;
pub const TCP_EDC_CNT_NEW__UTCL1_LFIFO0_SEC_COUNT_MASK: c_uint = 0x000C0000L;
pub const TCP_EDC_CNT_NEW__UTCL1_LFIFO0_DED_COUNT_MASK: c_uint = 0x00300000L;
pub const TCP_EDC_CNT_NEW__UTCL1_LFIFO1_SEC_COUNT_MASK: c_uint = 0x00C00000L;
pub const TCP_EDC_CNT_NEW__UTCL1_LFIFO1_DED_COUNT_MASK: c_uint = 0x03000000L;
// TCP_ATC_EDC_GATCL1_CNT
pub const TCP_ATC_EDC_GATCL1_CNT__DATA_SEC__SHIFT: c_uint = 0x0;
pub const TCP_ATC_EDC_GATCL1_CNT__DATA_SEC_MASK: c_uint = 0x000000FFL;
// TCI_EDC_CNT
pub const TCI_EDC_CNT__WRITE_RAM_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const TCI_EDC_CNT__WRITE_RAM_DED_COUNT__SHIFT: c_uint = 0x2;
pub const TCI_EDC_CNT__WRITE_RAM_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const TCI_EDC_CNT__WRITE_RAM_DED_COUNT_MASK: c_uint = 0x0000000CL;
// TCA_EDC_CNT
pub const TCA_EDC_CNT__HOLE_FIFO_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const TCA_EDC_CNT__HOLE_FIFO_DED_COUNT__SHIFT: c_uint = 0x2;
pub const TCA_EDC_CNT__REQ_FIFO_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const TCA_EDC_CNT__REQ_FIFO_DED_COUNT__SHIFT: c_uint = 0x6;
pub const TCA_EDC_CNT__HOLE_FIFO_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const TCA_EDC_CNT__HOLE_FIFO_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const TCA_EDC_CNT__REQ_FIFO_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const TCA_EDC_CNT__REQ_FIFO_DED_COUNT_MASK: c_uint = 0x000000C0L;
// TCC_EDC_CNT
pub const TCC_EDC_CNT__CACHE_DATA_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const TCC_EDC_CNT__CACHE_DATA_DED_COUNT__SHIFT: c_uint = 0x2;
pub const TCC_EDC_CNT__CACHE_DIRTY_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const TCC_EDC_CNT__CACHE_DIRTY_DED_COUNT__SHIFT: c_uint = 0x6;
pub const TCC_EDC_CNT__HIGH_RATE_TAG_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const TCC_EDC_CNT__HIGH_RATE_TAG_DED_COUNT__SHIFT: c_uint = 0xa;
pub const TCC_EDC_CNT__LOW_RATE_TAG_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const TCC_EDC_CNT__LOW_RATE_TAG_DED_COUNT__SHIFT: c_uint = 0xe;
pub const TCC_EDC_CNT__SRC_FIFO_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const TCC_EDC_CNT__SRC_FIFO_DED_COUNT__SHIFT: c_uint = 0x12;
pub const TCC_EDC_CNT__LATENCY_FIFO_SEC_COUNT__SHIFT: c_uint = 0x14;
pub const TCC_EDC_CNT__LATENCY_FIFO_DED_COUNT__SHIFT: c_uint = 0x16;
pub const TCC_EDC_CNT__LATENCY_FIFO_NEXT_RAM_SEC_COUNT__SHIFT: c_uint = 0x18;
pub const TCC_EDC_CNT__LATENCY_FIFO_NEXT_RAM_DED_COUNT__SHIFT: c_uint = 0x1a;
pub const TCC_EDC_CNT__CACHE_DATA_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const TCC_EDC_CNT__CACHE_DATA_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const TCC_EDC_CNT__CACHE_DIRTY_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const TCC_EDC_CNT__CACHE_DIRTY_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const TCC_EDC_CNT__HIGH_RATE_TAG_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const TCC_EDC_CNT__HIGH_RATE_TAG_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const TCC_EDC_CNT__LOW_RATE_TAG_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const TCC_EDC_CNT__LOW_RATE_TAG_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const TCC_EDC_CNT__SRC_FIFO_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const TCC_EDC_CNT__SRC_FIFO_DED_COUNT_MASK: c_uint = 0x000C0000L;
pub const TCC_EDC_CNT__LATENCY_FIFO_SEC_COUNT_MASK: c_uint = 0x00300000L;
pub const TCC_EDC_CNT__LATENCY_FIFO_DED_COUNT_MASK: c_uint = 0x00C00000L;
pub const TCC_EDC_CNT__LATENCY_FIFO_NEXT_RAM_SEC_COUNT_MASK: c_uint = 0x03000000L;
pub const TCC_EDC_CNT__LATENCY_FIFO_NEXT_RAM_DED_COUNT_MASK: c_uint = 0x0C000000L;
// TCC_EDC_CNT2
pub const TCC_EDC_CNT2__CACHE_TAG_PROBE_FIFO_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const TCC_EDC_CNT2__CACHE_TAG_PROBE_FIFO_DED_COUNT__SHIFT: c_uint = 0x2;
pub const TCC_EDC_CNT2__UC_ATOMIC_FIFO_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const TCC_EDC_CNT2__UC_ATOMIC_FIFO_DED_COUNT__SHIFT: c_uint = 0x6;
pub const TCC_EDC_CNT2__WRITE_CACHE_READ_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const TCC_EDC_CNT2__WRITE_CACHE_READ_DED_COUNT__SHIFT: c_uint = 0xa;
pub const TCC_EDC_CNT2__RETURN_CONTROL_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const TCC_EDC_CNT2__RETURN_CONTROL_DED_COUNT__SHIFT: c_uint = 0xe;
pub const TCC_EDC_CNT2__IN_USE_TRANSFER_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const TCC_EDC_CNT2__IN_USE_TRANSFER_DED_COUNT__SHIFT: c_uint = 0x12;
pub const TCC_EDC_CNT2__IN_USE_DEC_SEC_COUNT__SHIFT: c_uint = 0x14;
pub const TCC_EDC_CNT2__IN_USE_DEC_DED_COUNT__SHIFT: c_uint = 0x16;
pub const TCC_EDC_CNT2__WRITE_RETURN_SEC_COUNT__SHIFT: c_uint = 0x18;
pub const TCC_EDC_CNT2__WRITE_RETURN_DED_COUNT__SHIFT: c_uint = 0x1a;
pub const TCC_EDC_CNT2__RETURN_DATA_SEC_COUNT__SHIFT: c_uint = 0x1c;
pub const TCC_EDC_CNT2__RETURN_DATA_DED_COUNT__SHIFT: c_uint = 0x1e;
pub const TCC_EDC_CNT2__CACHE_TAG_PROBE_FIFO_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const TCC_EDC_CNT2__CACHE_TAG_PROBE_FIFO_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const TCC_EDC_CNT2__UC_ATOMIC_FIFO_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const TCC_EDC_CNT2__UC_ATOMIC_FIFO_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const TCC_EDC_CNT2__WRITE_CACHE_READ_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const TCC_EDC_CNT2__WRITE_CACHE_READ_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const TCC_EDC_CNT2__RETURN_CONTROL_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const TCC_EDC_CNT2__RETURN_CONTROL_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const TCC_EDC_CNT2__IN_USE_TRANSFER_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const TCC_EDC_CNT2__IN_USE_TRANSFER_DED_COUNT_MASK: c_uint = 0x000C0000L;
pub const TCC_EDC_CNT2__IN_USE_DEC_SEC_COUNT_MASK: c_uint = 0x00300000L;
pub const TCC_EDC_CNT2__IN_USE_DEC_DED_COUNT_MASK: c_uint = 0x00C00000L;
pub const TCC_EDC_CNT2__WRITE_RETURN_SEC_COUNT_MASK: c_uint = 0x03000000L;
pub const TCC_EDC_CNT2__WRITE_RETURN_DED_COUNT_MASK: c_uint = 0x0C000000L;
pub const TCC_EDC_CNT2__RETURN_DATA_SEC_COUNT_MASK: c_uint = 0x30000000L;
pub const TCC_EDC_CNT2__RETURN_DATA_DED_COUNT_MASK: c_uint = 0xC0000000L;
// addressBlock: gc_tpdec
// TD_EDC_CNT
pub const TD_EDC_CNT__SS_FIFO_LO_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const TD_EDC_CNT__SS_FIFO_LO_DED_COUNT__SHIFT: c_uint = 0x2;
pub const TD_EDC_CNT__SS_FIFO_HI_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const TD_EDC_CNT__SS_FIFO_HI_DED_COUNT__SHIFT: c_uint = 0x6;
pub const TD_EDC_CNT__CS_FIFO_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const TD_EDC_CNT__CS_FIFO_DED_COUNT__SHIFT: c_uint = 0xa;
pub const TD_EDC_CNT__SS_FIFO_LO_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const TD_EDC_CNT__SS_FIFO_LO_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const TD_EDC_CNT__SS_FIFO_HI_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const TD_EDC_CNT__SS_FIFO_HI_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const TD_EDC_CNT__CS_FIFO_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const TD_EDC_CNT__CS_FIFO_DED_COUNT_MASK: c_uint = 0x00000C00L;
// TA_EDC_CNT
pub const TA_EDC_CNT__TA_FS_DFIFO_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const TA_EDC_CNT__TA_FS_DFIFO_DED_COUNT__SHIFT: c_uint = 0x2;
pub const TA_EDC_CNT__TA_FS_AFIFO_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const TA_EDC_CNT__TA_FS_AFIFO_DED_COUNT__SHIFT: c_uint = 0x6;
pub const TA_EDC_CNT__TA_FL_LFIFO_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const TA_EDC_CNT__TA_FL_LFIFO_DED_COUNT__SHIFT: c_uint = 0xa;
pub const TA_EDC_CNT__TA_FX_LFIFO_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const TA_EDC_CNT__TA_FX_LFIFO_DED_COUNT__SHIFT: c_uint = 0xe;
pub const TA_EDC_CNT__TA_FS_CFIFO_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const TA_EDC_CNT__TA_FS_CFIFO_DED_COUNT__SHIFT: c_uint = 0x12;
pub const TA_EDC_CNT__TA_FS_DFIFO_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const TA_EDC_CNT__TA_FS_DFIFO_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const TA_EDC_CNT__TA_FS_AFIFO_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const TA_EDC_CNT__TA_FS_AFIFO_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const TA_EDC_CNT__TA_FL_LFIFO_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const TA_EDC_CNT__TA_FL_LFIFO_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const TA_EDC_CNT__TA_FX_LFIFO_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const TA_EDC_CNT__TA_FX_LFIFO_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const TA_EDC_CNT__TA_FS_CFIFO_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const TA_EDC_CNT__TA_FS_CFIFO_DED_COUNT_MASK: c_uint = 0x000C0000L;
// addressBlock: gc_ea_gceadec2
// GCEA_EDC_CNT
pub const GCEA_EDC_CNT__DRAMRD_CMDMEM_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const GCEA_EDC_CNT__DRAMRD_CMDMEM_DED_COUNT__SHIFT: c_uint = 0x2;
pub const GCEA_EDC_CNT__DRAMWR_CMDMEM_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const GCEA_EDC_CNT__DRAMWR_CMDMEM_DED_COUNT__SHIFT: c_uint = 0x6;
pub const GCEA_EDC_CNT__DRAMWR_DATAMEM_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const GCEA_EDC_CNT__DRAMWR_DATAMEM_DED_COUNT__SHIFT: c_uint = 0xa;
pub const GCEA_EDC_CNT__RRET_TAGMEM_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const GCEA_EDC_CNT__RRET_TAGMEM_DED_COUNT__SHIFT: c_uint = 0xe;
pub const GCEA_EDC_CNT__WRET_TAGMEM_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const GCEA_EDC_CNT__WRET_TAGMEM_DED_COUNT__SHIFT: c_uint = 0x12;
pub const GCEA_EDC_CNT__DRAMRD_PAGEMEM_SED_COUNT__SHIFT: c_uint = 0x14;
pub const GCEA_EDC_CNT__DRAMWR_PAGEMEM_SED_COUNT__SHIFT: c_uint = 0x16;
pub const GCEA_EDC_CNT__IORD_CMDMEM_SED_COUNT__SHIFT: c_uint = 0x18;
pub const GCEA_EDC_CNT__IOWR_CMDMEM_SED_COUNT__SHIFT: c_uint = 0x1a;
pub const GCEA_EDC_CNT__IOWR_DATAMEM_SED_COUNT__SHIFT: c_uint = 0x1c;
pub const GCEA_EDC_CNT__MAM_AFMEM_SEC_COUNT__SHIFT: c_uint = 0x1e;
pub const GCEA_EDC_CNT__DRAMRD_CMDMEM_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const GCEA_EDC_CNT__DRAMRD_CMDMEM_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const GCEA_EDC_CNT__DRAMWR_CMDMEM_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const GCEA_EDC_CNT__DRAMWR_CMDMEM_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const GCEA_EDC_CNT__DRAMWR_DATAMEM_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const GCEA_EDC_CNT__DRAMWR_DATAMEM_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const GCEA_EDC_CNT__RRET_TAGMEM_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const GCEA_EDC_CNT__RRET_TAGMEM_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const GCEA_EDC_CNT__WRET_TAGMEM_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const GCEA_EDC_CNT__WRET_TAGMEM_DED_COUNT_MASK: c_uint = 0x000C0000L;
pub const GCEA_EDC_CNT__DRAMRD_PAGEMEM_SED_COUNT_MASK: c_uint = 0x00300000L;
pub const GCEA_EDC_CNT__DRAMWR_PAGEMEM_SED_COUNT_MASK: c_uint = 0x00C00000L;
pub const GCEA_EDC_CNT__IORD_CMDMEM_SED_COUNT_MASK: c_uint = 0x03000000L;
pub const GCEA_EDC_CNT__IOWR_CMDMEM_SED_COUNT_MASK: c_uint = 0x0C000000L;
pub const GCEA_EDC_CNT__IOWR_DATAMEM_SED_COUNT_MASK: c_uint = 0x30000000L;
pub const GCEA_EDC_CNT__MAM_AFMEM_SEC_COUNT_MASK: c_uint = 0xC0000000L;
// GCEA_EDC_CNT2
pub const GCEA_EDC_CNT2__GMIRD_CMDMEM_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const GCEA_EDC_CNT2__GMIRD_CMDMEM_DED_COUNT__SHIFT: c_uint = 0x2;
pub const GCEA_EDC_CNT2__GMIWR_CMDMEM_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const GCEA_EDC_CNT2__GMIWR_CMDMEM_DED_COUNT__SHIFT: c_uint = 0x6;
pub const GCEA_EDC_CNT2__GMIWR_DATAMEM_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const GCEA_EDC_CNT2__GMIWR_DATAMEM_DED_COUNT__SHIFT: c_uint = 0xa;
pub const GCEA_EDC_CNT2__GMIRD_PAGEMEM_SED_COUNT__SHIFT: c_uint = 0xc;
pub const GCEA_EDC_CNT2__GMIWR_PAGEMEM_SED_COUNT__SHIFT: c_uint = 0xe;
pub const GCEA_EDC_CNT2__MAM_D0MEM_SED_COUNT__SHIFT: c_uint = 0x10;
pub const GCEA_EDC_CNT2__MAM_D1MEM_SED_COUNT__SHIFT: c_uint = 0x12;
pub const GCEA_EDC_CNT2__MAM_D2MEM_SED_COUNT__SHIFT: c_uint = 0x14;
pub const GCEA_EDC_CNT2__MAM_D3MEM_SED_COUNT__SHIFT: c_uint = 0x16;
pub const GCEA_EDC_CNT2__MAM_D0MEM_DED_COUNT__SHIFT: c_uint = 0x18;
pub const GCEA_EDC_CNT2__MAM_D1MEM_DED_COUNT__SHIFT: c_uint = 0x1a;
pub const GCEA_EDC_CNT2__MAM_D2MEM_DED_COUNT__SHIFT: c_uint = 0x1c;
pub const GCEA_EDC_CNT2__MAM_D3MEM_DED_COUNT__SHIFT: c_uint = 0x1e;
pub const GCEA_EDC_CNT2__GMIRD_CMDMEM_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const GCEA_EDC_CNT2__GMIRD_CMDMEM_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const GCEA_EDC_CNT2__GMIWR_CMDMEM_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const GCEA_EDC_CNT2__GMIWR_CMDMEM_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const GCEA_EDC_CNT2__GMIWR_DATAMEM_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const GCEA_EDC_CNT2__GMIWR_DATAMEM_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const GCEA_EDC_CNT2__GMIRD_PAGEMEM_SED_COUNT_MASK: c_uint = 0x00003000L;
pub const GCEA_EDC_CNT2__GMIWR_PAGEMEM_SED_COUNT_MASK: c_uint = 0x0000C000L;
pub const GCEA_EDC_CNT2__MAM_D0MEM_SED_COUNT_MASK: c_uint = 0x00030000L;
pub const GCEA_EDC_CNT2__MAM_D1MEM_SED_COUNT_MASK: c_uint = 0x000C0000L;
pub const GCEA_EDC_CNT2__MAM_D2MEM_SED_COUNT_MASK: c_uint = 0x00300000L;
pub const GCEA_EDC_CNT2__MAM_D3MEM_SED_COUNT_MASK: c_uint = 0x00C00000L;
pub const GCEA_EDC_CNT2__MAM_D0MEM_DED_COUNT_MASK: c_uint = 0x03000000L;
pub const GCEA_EDC_CNT2__MAM_D1MEM_DED_COUNT_MASK: c_uint = 0x0C000000L;
pub const GCEA_EDC_CNT2__MAM_D2MEM_DED_COUNT_MASK: c_uint = 0x30000000L;
pub const GCEA_EDC_CNT2__MAM_D3MEM_DED_COUNT_MASK: c_uint = 0xC0000000L;
// GCEA_EDC_CNT3
pub const GCEA_EDC_CNT3__DRAMRD_PAGEMEM_DED_COUNT__SHIFT: c_uint = 0x0;
pub const GCEA_EDC_CNT3__DRAMWR_PAGEMEM_DED_COUNT__SHIFT: c_uint = 0x2;
pub const GCEA_EDC_CNT3__IORD_CMDMEM_DED_COUNT__SHIFT: c_uint = 0x4;
pub const GCEA_EDC_CNT3__IOWR_CMDMEM_DED_COUNT__SHIFT: c_uint = 0x6;
pub const GCEA_EDC_CNT3__IOWR_DATAMEM_DED_COUNT__SHIFT: c_uint = 0x8;
pub const GCEA_EDC_CNT3__GMIRD_PAGEMEM_DED_COUNT__SHIFT: c_uint = 0xa;
pub const GCEA_EDC_CNT3__GMIWR_PAGEMEM_DED_COUNT__SHIFT: c_uint = 0xc;
pub const GCEA_EDC_CNT3__MAM_AFMEM_DED_COUNT__SHIFT: c_uint = 0xe;
pub const GCEA_EDC_CNT3__MAM_A0MEM_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const GCEA_EDC_CNT3__MAM_A0MEM_DED_COUNT__SHIFT: c_uint = 0x12;
pub const GCEA_EDC_CNT3__MAM_A1MEM_SEC_COUNT__SHIFT: c_uint = 0x14;
pub const GCEA_EDC_CNT3__MAM_A1MEM_DED_COUNT__SHIFT: c_uint = 0x16;
pub const GCEA_EDC_CNT3__MAM_A2MEM_SEC_COUNT__SHIFT: c_uint = 0x18;
pub const GCEA_EDC_CNT3__MAM_A2MEM_DED_COUNT__SHIFT: c_uint = 0x1a;
pub const GCEA_EDC_CNT3__MAM_A3MEM_SEC_COUNT__SHIFT: c_uint = 0x1c;
pub const GCEA_EDC_CNT3__MAM_A3MEM_DED_COUNT__SHIFT: c_uint = 0x1e;
pub const GCEA_EDC_CNT3__DRAMRD_PAGEMEM_DED_COUNT_MASK: c_uint = 0x00000003L;
pub const GCEA_EDC_CNT3__DRAMWR_PAGEMEM_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const GCEA_EDC_CNT3__IORD_CMDMEM_DED_COUNT_MASK: c_uint = 0x00000030L;
pub const GCEA_EDC_CNT3__IOWR_CMDMEM_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const GCEA_EDC_CNT3__IOWR_DATAMEM_DED_COUNT_MASK: c_uint = 0x00000300L;
pub const GCEA_EDC_CNT3__GMIRD_PAGEMEM_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const GCEA_EDC_CNT3__GMIWR_PAGEMEM_DED_COUNT_MASK: c_uint = 0x00003000L;
pub const GCEA_EDC_CNT3__MAM_AFMEM_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const GCEA_EDC_CNT3__MAM_A0MEM_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const GCEA_EDC_CNT3__MAM_A0MEM_DED_COUNT_MASK: c_uint = 0x000C0000L;
pub const GCEA_EDC_CNT3__MAM_A1MEM_SEC_COUNT_MASK: c_uint = 0x00300000L;
pub const GCEA_EDC_CNT3__MAM_A1MEM_DED_COUNT_MASK: c_uint = 0x00C00000L;
pub const GCEA_EDC_CNT3__MAM_A2MEM_SEC_COUNT_MASK: c_uint = 0x03000000L;
pub const GCEA_EDC_CNT3__MAM_A2MEM_DED_COUNT_MASK: c_uint = 0x0C000000L;
pub const GCEA_EDC_CNT3__MAM_A3MEM_SEC_COUNT_MASK: c_uint = 0x30000000L;
pub const GCEA_EDC_CNT3__MAM_A3MEM_DED_COUNT_MASK: c_uint = 0xC0000000L;
// GCEA_ERR_STATUS
pub const GCEA_ERR_STATUS__SDP_RDRSP_STATUS__SHIFT: c_uint = 0x0;
pub const GCEA_ERR_STATUS__SDP_WRRSP_STATUS__SHIFT: c_uint = 0x4;
pub const GCEA_ERR_STATUS__SDP_RDRSP_DATASTATUS__SHIFT: c_uint = 0x8;
pub const GCEA_ERR_STATUS__SDP_RDRSP_DATAPARITY_ERROR__SHIFT: c_uint = 0xa;
pub const GCEA_ERR_STATUS__CLEAR_ERROR_STATUS__SHIFT: c_uint = 0xb;
pub const GCEA_ERR_STATUS__BUSY_ON_ERROR__SHIFT: c_uint = 0xc;
pub const GCEA_ERR_STATUS__FUE_FLAG__SHIFT: c_uint = 0xd;
pub const GCEA_ERR_STATUS__SDP_RDRSP_STATUS_MASK: c_uint = 0x0000000FL;
pub const GCEA_ERR_STATUS__SDP_WRRSP_STATUS_MASK: c_uint = 0x000000F0L;
pub const GCEA_ERR_STATUS__SDP_RDRSP_DATASTATUS_MASK: c_uint = 0x00000300L;
pub const GCEA_ERR_STATUS__SDP_RDRSP_DATAPARITY_ERROR_MASK: c_uint = 0x00000400L;
pub const GCEA_ERR_STATUS__CLEAR_ERROR_STATUS_MASK: c_uint = 0x00000800L;
pub const GCEA_ERR_STATUS__BUSY_ON_ERROR_MASK: c_uint = 0x00001000L;
pub const GCEA_ERR_STATUS__FUE_FLAG_MASK: c_uint = 0x00002000L;
// addressBlock: gc_gfxudec
// GRBM_GFX_INDEX
pub const GRBM_GFX_INDEX__INSTANCE_INDEX__SHIFT: c_uint = 0x0;
pub const GRBM_GFX_INDEX__SH_INDEX__SHIFT: c_uint = 0x8;
pub const GRBM_GFX_INDEX__SE_INDEX__SHIFT: c_uint = 0x10;
pub const GRBM_GFX_INDEX__SH_BROADCAST_WRITES__SHIFT: c_uint = 0x1d;
pub const GRBM_GFX_INDEX__INSTANCE_BROADCAST_WRITES__SHIFT: c_uint = 0x1e;
pub const GRBM_GFX_INDEX__SE_BROADCAST_WRITES__SHIFT: c_uint = 0x1f;
pub const GRBM_GFX_INDEX__INSTANCE_INDEX_MASK: c_uint = 0x000000FFL;
pub const GRBM_GFX_INDEX__SH_INDEX_MASK: c_uint = 0x0000FF00L;
pub const GRBM_GFX_INDEX__SE_INDEX_MASK: c_uint = 0x00FF0000L;
pub const GRBM_GFX_INDEX__SH_BROADCAST_WRITES_MASK: c_uint = 0x20000000L;
pub const GRBM_GFX_INDEX__INSTANCE_BROADCAST_WRITES_MASK: c_uint = 0x40000000L;
pub const GRBM_GFX_INDEX__SE_BROADCAST_WRITES_MASK: c_uint = 0x80000000L;
// addressBlock: gc_utcl2_atcl2dec
// ATC_L2_CNTL
// ATC_L2_CACHE_4K_DSM_INDEX
pub const ATC_L2_CACHE_4K_DSM_INDEX__INDEX__SHIFT: c_uint = 0x0;
pub const ATC_L2_CACHE_4K_DSM_INDEX__INDEX_MASK: c_uint = 0x000000FFL;
// ATC_L2_CACHE_2M_DSM_INDEX
pub const ATC_L2_CACHE_2M_DSM_INDEX__INDEX__SHIFT: c_uint = 0x0;
pub const ATC_L2_CACHE_2M_DSM_INDEX__INDEX_MASK: c_uint = 0x000000FFL;
// ATC_L2_CACHE_4K_DSM_CNTL
pub const ATC_L2_CACHE_4K_DSM_CNTL__SEC_COUNT__SHIFT: c_uint = 0xd;
pub const ATC_L2_CACHE_4K_DSM_CNTL__DED_COUNT__SHIFT: c_uint = 0xf;
pub const ATC_L2_CACHE_4K_DSM_CNTL__SEC_COUNT_MASK: c_uint = 0x00006000L;
pub const ATC_L2_CACHE_4K_DSM_CNTL__DED_COUNT_MASK: c_uint = 0x00018000L;
// ATC_L2_CACHE_2M_DSM_CNTL
pub const ATC_L2_CACHE_2M_DSM_CNTL__SEC_COUNT__SHIFT: c_uint = 0xd;
pub const ATC_L2_CACHE_2M_DSM_CNTL__DED_COUNT__SHIFT: c_uint = 0xf;
pub const ATC_L2_CACHE_2M_DSM_CNTL__SEC_COUNT_MASK: c_uint = 0x00006000L;
pub const ATC_L2_CACHE_2M_DSM_CNTL__DED_COUNT_MASK: c_uint = 0x00018000L;
// addressBlock: gc_utcl2_vml2pfdec
// VML2_MEM_ECC_INDEX
pub const VML2_MEM_ECC_INDEX__INDEX__SHIFT: c_uint = 0x0;
pub const VML2_MEM_ECC_INDEX__INDEX_MASK: c_uint = 0x000000FFL;
// VML2_WALKER_MEM_ECC_INDEX
pub const VML2_WALKER_MEM_ECC_INDEX__INDEX__SHIFT: c_uint = 0x0;
pub const VML2_WALKER_MEM_ECC_INDEX__INDEX_MASK: c_uint = 0x000000FFL;
// UTCL2_MEM_ECC_INDEX
pub const UTCL2_MEM_ECC_INDEX__INDEX__SHIFT: c_uint = 0x0;
pub const UTCL2_MEM_ECC_INDEX__INDEX_MASK: c_uint = 0x000000FFL;
// VML2_MEM_ECC_CNTL
pub const VML2_MEM_ECC_CNTL__SEC_COUNT__SHIFT: c_uint = 0xc;
pub const VML2_MEM_ECC_CNTL__DED_COUNT__SHIFT: c_uint = 0xe;
pub const VML2_MEM_ECC_CNTL__SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const VML2_MEM_ECC_CNTL__DED_COUNT_MASK: c_uint = 0x0000C000L;
// VML2_WALKER_MEM_ECC_CNTL
pub const VML2_WALKER_MEM_ECC_CNTL__SEC_COUNT__SHIFT: c_uint = 0xc;
pub const VML2_WALKER_MEM_ECC_CNTL__DED_COUNT__SHIFT: c_uint = 0xe;
pub const VML2_WALKER_MEM_ECC_CNTL__SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const VML2_WALKER_MEM_ECC_CNTL__DED_COUNT_MASK: c_uint = 0x0000C000L;
// UTCL2_MEM_ECC_CNTL
pub const UTCL2_MEM_ECC_CNTL__SEC_COUNT__SHIFT: c_uint = 0xc;
pub const UTCL2_MEM_ECC_CNTL__DED_COUNT__SHIFT: c_uint = 0xe;
pub const UTCL2_MEM_ECC_CNTL__SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const UTCL2_MEM_ECC_CNTL__DED_COUNT_MASK: c_uint = 0x0000C000L;
// addressBlock: gc_rlcpdec
// RLC_EDC_CNT
pub const RLC_EDC_CNT__RLCG_INSTR_RAM_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const RLC_EDC_CNT__RLCG_INSTR_RAM_DED_COUNT__SHIFT: c_uint = 0x2;
pub const RLC_EDC_CNT__RLCG_SCRATCH_RAM_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const RLC_EDC_CNT__RLCG_SCRATCH_RAM_DED_COUNT__SHIFT: c_uint = 0x6;
pub const RLC_EDC_CNT__RLCV_INSTR_RAM_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const RLC_EDC_CNT__RLCV_INSTR_RAM_DED_COUNT__SHIFT: c_uint = 0xa;
pub const RLC_EDC_CNT__RLCV_SCRATCH_RAM_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const RLC_EDC_CNT__RLCV_SCRATCH_RAM_DED_COUNT__SHIFT: c_uint = 0xe;
pub const RLC_EDC_CNT__RLC_TCTAG_RAM_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const RLC_EDC_CNT__RLC_TCTAG_RAM_DED_COUNT__SHIFT: c_uint = 0x12;
pub const RLC_EDC_CNT__RLC_SPM_SCRATCH_RAM_SEC_COUNT__SHIFT: c_uint = 0x14;
pub const RLC_EDC_CNT__RLC_SPM_SCRATCH_RAM_DED_COUNT__SHIFT: c_uint = 0x16;
pub const RLC_EDC_CNT__RLC_SRM_DATA_RAM_SEC_COUNT__SHIFT: c_uint = 0x18;
pub const RLC_EDC_CNT__RLC_SRM_DATA_RAM_DED_COUNT__SHIFT: c_uint = 0x1a;
pub const RLC_EDC_CNT__RLC_SRM_ADDR_RAM_SEC_COUNT__SHIFT: c_uint = 0x1c;
pub const RLC_EDC_CNT__RLC_SRM_ADDR_RAM_DED_COUNT__SHIFT: c_uint = 0x1e;
pub const RLC_EDC_CNT__RLCG_INSTR_RAM_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const RLC_EDC_CNT__RLCG_INSTR_RAM_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const RLC_EDC_CNT__RLCG_SCRATCH_RAM_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const RLC_EDC_CNT__RLCG_SCRATCH_RAM_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const RLC_EDC_CNT__RLCV_INSTR_RAM_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const RLC_EDC_CNT__RLCV_INSTR_RAM_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const RLC_EDC_CNT__RLCV_SCRATCH_RAM_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const RLC_EDC_CNT__RLCV_SCRATCH_RAM_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const RLC_EDC_CNT__RLC_TCTAG_RAM_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const RLC_EDC_CNT__RLC_TCTAG_RAM_DED_COUNT_MASK: c_uint = 0x000C0000L;
pub const RLC_EDC_CNT__RLC_SPM_SCRATCH_RAM_SEC_COUNT_MASK: c_uint = 0x00300000L;
pub const RLC_EDC_CNT__RLC_SPM_SCRATCH_RAM_DED_COUNT_MASK: c_uint = 0x00C00000L;
pub const RLC_EDC_CNT__RLC_SRM_DATA_RAM_SEC_COUNT_MASK: c_uint = 0x03000000L;
pub const RLC_EDC_CNT__RLC_SRM_DATA_RAM_DED_COUNT_MASK: c_uint = 0x0C000000L;
pub const RLC_EDC_CNT__RLC_SRM_ADDR_RAM_SEC_COUNT_MASK: c_uint = 0x30000000L;
pub const RLC_EDC_CNT__RLC_SRM_ADDR_RAM_DED_COUNT_MASK: c_uint = 0xC0000000L;
// RLC_EDC_CNT2
pub const RLC_EDC_CNT2__RLC_SPM_SE0_SCRATCH_RAM_SEC_COUNT__SHIFT: c_uint = 0x0;
pub const RLC_EDC_CNT2__RLC_SPM_SE0_SCRATCH_RAM_DED_COUNT__SHIFT: c_uint = 0x2;
pub const RLC_EDC_CNT2__RLC_SPM_SE1_SCRATCH_RAM_SEC_COUNT__SHIFT: c_uint = 0x4;
pub const RLC_EDC_CNT2__RLC_SPM_SE1_SCRATCH_RAM_DED_COUNT__SHIFT: c_uint = 0x6;
pub const RLC_EDC_CNT2__RLC_SPM_SE2_SCRATCH_RAM_SEC_COUNT__SHIFT: c_uint = 0x8;
pub const RLC_EDC_CNT2__RLC_SPM_SE2_SCRATCH_RAM_DED_COUNT__SHIFT: c_uint = 0xa;
pub const RLC_EDC_CNT2__RLC_SPM_SE3_SCRATCH_RAM_SEC_COUNT__SHIFT: c_uint = 0xc;
pub const RLC_EDC_CNT2__RLC_SPM_SE3_SCRATCH_RAM_DED_COUNT__SHIFT: c_uint = 0xe;
pub const RLC_EDC_CNT2__RLC_SPM_SE4_SCRATCH_RAM_SEC_COUNT__SHIFT: c_uint = 0x10;
pub const RLC_EDC_CNT2__RLC_SPM_SE4_SCRATCH_RAM_DED_COUNT__SHIFT: c_uint = 0x12;
pub const RLC_EDC_CNT2__RLC_SPM_SE5_SCRATCH_RAM_SEC_COUNT__SHIFT: c_uint = 0x14;
pub const RLC_EDC_CNT2__RLC_SPM_SE5_SCRATCH_RAM_DED_COUNT__SHIFT: c_uint = 0x16;
pub const RLC_EDC_CNT2__RLC_SPM_SE6_SCRATCH_RAM_SEC_COUNT__SHIFT: c_uint = 0x18;
pub const RLC_EDC_CNT2__RLC_SPM_SE6_SCRATCH_RAM_DED_COUNT__SHIFT: c_uint = 0x1a;
pub const RLC_EDC_CNT2__RLC_SPM_SE7_SCRATCH_RAM_SEC_COUNT__SHIFT: c_uint = 0x1c;
pub const RLC_EDC_CNT2__RLC_SPM_SE7_SCRATCH_RAM_DED_COUNT__SHIFT: c_uint = 0x1e;
pub const RLC_EDC_CNT2__RLC_SPM_SE0_SCRATCH_RAM_SEC_COUNT_MASK: c_uint = 0x00000003L;
pub const RLC_EDC_CNT2__RLC_SPM_SE0_SCRATCH_RAM_DED_COUNT_MASK: c_uint = 0x0000000CL;
pub const RLC_EDC_CNT2__RLC_SPM_SE1_SCRATCH_RAM_SEC_COUNT_MASK: c_uint = 0x00000030L;
pub const RLC_EDC_CNT2__RLC_SPM_SE1_SCRATCH_RAM_DED_COUNT_MASK: c_uint = 0x000000C0L;
pub const RLC_EDC_CNT2__RLC_SPM_SE2_SCRATCH_RAM_SEC_COUNT_MASK: c_uint = 0x00000300L;
pub const RLC_EDC_CNT2__RLC_SPM_SE2_SCRATCH_RAM_DED_COUNT_MASK: c_uint = 0x00000C00L;
pub const RLC_EDC_CNT2__RLC_SPM_SE3_SCRATCH_RAM_SEC_COUNT_MASK: c_uint = 0x00003000L;
pub const RLC_EDC_CNT2__RLC_SPM_SE3_SCRATCH_RAM_DED_COUNT_MASK: c_uint = 0x0000C000L;
pub const RLC_EDC_CNT2__RLC_SPM_SE4_SCRATCH_RAM_SEC_COUNT_MASK: c_uint = 0x00030000L;
pub const RLC_EDC_CNT2__RLC_SPM_SE4_SCRATCH_RAM_DED_COUNT_MASK: c_uint = 0x000C0000L;
pub const RLC_EDC_CNT2__RLC_SPM_SE5_SCRATCH_RAM_SEC_COUNT_MASK: c_uint = 0x00300000L;
pub const RLC_EDC_CNT2__RLC_SPM_SE5_SCRATCH_RAM_DED_COUNT_MASK: c_uint = 0x00C00000L;
pub const RLC_EDC_CNT2__RLC_SPM_SE6_SCRATCH_RAM_SEC_COUNT_MASK: c_uint = 0x03000000L;
pub const RLC_EDC_CNT2__RLC_SPM_SE6_SCRATCH_RAM_DED_COUNT_MASK: c_uint = 0x0C000000L;
pub const RLC_EDC_CNT2__RLC_SPM_SE7_SCRATCH_RAM_SEC_COUNT_MASK: c_uint = 0x30000000L;
pub const RLC_EDC_CNT2__RLC_SPM_SE7_SCRATCH_RAM_DED_COUNT_MASK: c_uint = 0xC0000000L;
