//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/amd/display/dc/inc/dcn_calcs.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// Copyright 2017 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// Authors: AMD
//
// Bandwidth and Watermark calculations interface.
// (Refer to "DCEx_mode_support.xlsm" from Perforce.)
//

//
// DCN data structures.
//
pub const number_of_planes: c_int = 6;
pub const number_of_planes_minus_one: c_int = 5;
pub const number_of_states: c_int = 4;
pub const number_of_states_plus_one: c_int = 5;
pub const ddr4_dram_width: c_int = 64;
pub const ddr4_dram_factor_single_Channel: c_int = 16;
#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum dcn_bw_defs {
    dcn_bw_v_min0p65,
    dcn_bw_v_mid0p72,
    dcn_bw_v_nom0p8,
    dcn_bw_v_max0p9,
    dcn_bw_v_max0p91,
    dcn_bw_no_support = 5,
    dcn_bw_yes,
    dcn_bw_hor,
    dcn_bw_vert,
    dcn_bw_override,
    dcn_bw_rgb_sub_64,
    dcn_bw_rgb_sub_32,
    dcn_bw_rgb_sub_16,
    dcn_bw_no,
    dcn_bw_sw_linear,
    dcn_bw_sw_4_kb_d,
    dcn_bw_sw_4_kb_d_x,
    dcn_bw_sw_64_kb_d,
    dcn_bw_sw_64_kb_d_t,
    dcn_bw_sw_64_kb_d_x,
    dcn_bw_sw_var_d,
    dcn_bw_sw_var_d_x,
    dcn_bw_yuv420_sub_8,
    dcn_bw_sw_4_kb_s,
    dcn_bw_sw_4_kb_s_x,
    dcn_bw_sw_64_kb_s,
    dcn_bw_sw_64_kb_s_t,
    dcn_bw_sw_64_kb_s_x,
    dcn_bw_writeback,
    dcn_bw_444,
    dcn_bw_dp,
    dcn_bw_420,
    dcn_bw_hdmi,
    dcn_bw_sw_var_s,
    dcn_bw_sw_var_s_x,
    dcn_bw_yuv420_sub_10,
    dcn_bw_supported_in_v_active,
    dcn_bw_supported_in_v_blank,
    dcn_bw_not_supported,
    dcn_bw_na,
    dcn_bw_encoder_8bpc,
    dcn_bw_encoder_10bpc,
    dcn_bw_encoder_12bpc,
    dcn_bw_encoder_16bpc,
}

// bounding box parameters
// mode parameters
// system configuration
// display configuration
#[repr(C)]
#[derive(Copy, Clone)]
pub struct dcn_bw_internal_vars {
    pub 1]: float voltage[number_of_states_plus_one +,
    pub 1]: float max_dispclk[number_of_states_plus_one +,
    pub 1]: float max_dppclk[number_of_states_plus_one +,
    pub 1]: float dcfclk_per_state[number_of_states_plus_one +,
    pub 1]: float phyclk_per_state[number_of_states_plus_one +,
    pub 1]: float fabric_and_dram_bandwidth_per_state[number_of_states_plus_one +,
    pub sr_exit_time: float,
    pub sr_enter_plus_exit_time: float,
    pub dram_clock_change_latency: float,
    pub urgent_latency: float,
    pub write_back_latency: float,
    pub percent_of_ideal_drambw_received_after_urg_latency: float,
    pub dcfclkv_max0p9: float,
    pub dcfclkv_nom0p8: float,
    pub dcfclkv_mid0p72: float,
    pub dcfclkv_min0p65: float,
    pub max_dispclk_vmax0p9: float,
    pub max_dppclk_vmax0p9: float,
    pub max_dispclk_vnom0p8: float,
    pub max_dppclk_vnom0p8: float,
    pub max_dispclk_vmid0p72: float,
    pub max_dppclk_vmid0p72: float,
    pub max_dispclk_vmin0p65: float,
    pub max_dppclk_vmin0p65: float,
    pub socclk: float,
    pub fabric_and_dram_bandwidth_vmax0p9: float,
    pub fabric_and_dram_bandwidth_vnom0p8: float,
    pub fabric_and_dram_bandwidth_vmid0p72: float,
    pub fabric_and_dram_bandwidth_vmin0p65: float,
    pub round_trip_ping_latency_cycles: float,
    pub urgent_out_of_order_return_per_channel: float,
    pub number_of_channels: float,
    pub vmm_page_size: float,
    pub return_bus_width: float,
    pub rob_buffer_size_in_kbyte: float,
    pub det_buffer_size_in_kbyte: float,
    pub dpp_output_buffer_pixels: float,
    pub opp_output_buffer_lines: float,
    pub pixel_chunk_size_in_kbyte: float,
    pub pte_chunk_size: float,
    pub meta_chunk_size: float,
    pub writeback_chunk_size: float,
    pub odm_capability: dcn_bw_defs,
    pub dsc_capability: dcn_bw_defs,
    pub line_buffer_size: float,
    pub is_line_buffer_bpp_fixed: dcn_bw_defs,
    pub line_buffer_fixed_bpp: float,
    pub max_line_buffer_lines: float,
    pub writeback_luma_buffer_size: float,
    pub writeback_chroma_buffer_size: float,
    pub max_num_dpp: float,
    pub max_num_writeback: float,
    pub max_dchub_topscl_throughput: float,
    pub max_pscl_tolb_throughput: float,
    pub max_lb_tovscl_throughput: float,
    pub max_vscl_tohscl_throughput: float,
    pub max_hscl_ratio: float,
    pub max_vscl_ratio: float,
    pub max_hscl_taps: float,
    pub max_vscl_taps: float,
    pub under_scan_factor: float,
    pub phyclkv_max0p9: float,
    pub phyclkv_nom0p8: float,
    pub phyclkv_mid0p72: float,
    pub phyclkv_min0p65: float,
    pub pte_buffer_size_in_requests: float,
    pub dispclk_ramping_margin: float,
    pub downspreading: float,
    pub max_inter_dcn_tile_repeaters: float,
    pub can_vstartup_lines_exceed_vsync_plus_back_porch_lines_minus_one: dcn_bw_defs,
    pub bug_forcing_luma_and_chroma_request_to_same_size_fixed: dcn_bw_defs,
    pub mode: c_int,
    pub 1]: float viewport_width[number_of_planes_minus_one +,
    pub 1]: float htotal[number_of_planes_minus_one +,
    pub 1]: float vtotal[number_of_planes_minus_one +,
    pub 1]: float v_sync_plus_back_porch[number_of_planes_minus_one +,
    pub 1]: float vactive[number_of_planes_minus_one +,
    pub /*MHz*/: *mut float pixel_clock[number_of_planes_minus_one + 1];,
    pub 1]: float viewport_height[number_of_planes_minus_one +,
    pub 1]: dcn_bw_defs dcc_enable[number_of_planes_minus_one +,
    pub 1]: float dcc_rate[number_of_planes_minus_one +,
    pub 1]: dcn_bw_defs source_scan[number_of_planes_minus_one +,
    pub 1]: float lb_bit_per_pixel[number_of_planes_minus_one +,
    pub 1]: dcn_bw_defs source_pixel_format[number_of_planes_minus_one +,
    pub 1]: dcn_bw_defs source_surface_mode[number_of_planes_minus_one +,
    pub 1]: dcn_bw_defs output_format[number_of_planes_minus_one +,
    pub 1]: dcn_bw_defs output_deep_color[number_of_planes_minus_one +,
    pub 1]: dcn_bw_defs output[number_of_planes_minus_one +,
    pub 1]: float scaler_rec_out_width[number_of_planes_minus_one +,
    pub 1]: float scaler_recout_height[number_of_planes_minus_one +,
    pub 1]: float underscan_output[number_of_planes_minus_one +,
    pub 1]: float interlace_output[number_of_planes_minus_one +,
    pub 1]: float override_hta_ps[number_of_planes_minus_one +,
    pub 1]: float override_vta_ps[number_of_planes_minus_one +,
    pub 1]: float override_hta_pschroma[number_of_planes_minus_one +,
    pub 1]: float override_vta_pschroma[number_of_planes_minus_one +,
    pub 1]: float urgent_latency_support_us[number_of_planes_minus_one +,
    pub 1]: float h_ratio[number_of_planes_minus_one +,
    pub 1]: float v_ratio[number_of_planes_minus_one +,
    pub 1]: float htaps[number_of_planes_minus_one +,
    pub 1]: float vtaps[number_of_planes_minus_one +,
    pub 1]: float hta_pschroma[number_of_planes_minus_one +,
    pub 1]: float vta_pschroma[number_of_planes_minus_one +,
    pub pte_enable: dcn_bw_defs,
    pub synchronized_vblank: dcn_bw_defs,
    pub ta_pscalculation: dcn_bw_defs,
    pub voltage_override_level: c_int,
    pub number_of_active_planes: c_int,
    pub voltage_level: c_int,
    pub immediate_flip_supported: dcn_bw_defs,
    pub dcfclk: float,
    pub max_phyclk: float,
    pub fabric_and_dram_bandwidth: float,
    pub 1]: float dpp_per_plane_per_ratio[1 + 1][number_of_planes_minus_one +,
    pub 1]: dcn_bw_defs dispclk_dppclk_support_per_ratio[1 +,
    pub 1]: float required_dispclk_per_ratio[1 +,
    pub 1]: dcn_bw_defs error_message[1 +,
    pub dispclk_dppclk_ratio: c_int,
    pub 1]: float dpp_per_plane[number_of_planes_minus_one +,
    pub 1]: float det_buffer_size_y[number_of_planes_minus_one +,
    pub 1]: float det_buffer_size_c[number_of_planes_minus_one +,
    pub 1]: float swath_height_y[number_of_planes_minus_one +,
    pub 1]: float swath_height_c[number_of_planes_minus_one +,
    pub final_error_message: dcn_bw_defs,
    pub frequency: float,
    pub header_line: float,
    pub header: float,
    pub voltage_override: dcn_bw_defs,
    pub allow_different_hratio_vratio: dcn_bw_defs,
    pub acceptable_quality_hta_ps: float,
    pub acceptable_quality_vta_ps: float,
    pub 1]: float no_of_dpp[number_of_states_plus_one + 1][1 + 1][number_of_planes_minus_one +,
    pub 1]: float swath_width_yper_state[number_of_states_plus_one + 1][1 + 1][number_of_planes_minus_one +,
    pub 1]: float swath_height_yper_state[number_of_states_plus_one + 1][1 + 1][number_of_planes_minus_one +,
    pub 1]: float swath_height_cper_state[number_of_states_plus_one + 1][1 + 1][number_of_planes_minus_one +,
    pub 1]: float urgent_latency_support_us_per_state[number_of_states_plus_one + 1][1 + 1][number_of_planes_minus_one +,
    pub 1]: float v_ratio_pre_ywith_immediate_flip[number_of_states_plus_one + 1][1 + 1][number_of_planes_minus_one +,
    pub 1]: float v_ratio_pre_cwith_immediate_flip[number_of_states_plus_one + 1][1 + 1][number_of_planes_minus_one +,
    pub 1]: float required_prefetch_pixel_data_bw_with_immediate_flip[number_of_states_plus_one + 1][1 + 1][number_of_planes_minus_one +,
    pub 1]: float v_ratio_pre_ywithout_immediate_flip[number_of_states_plus_one + 1][1 + 1][number_of_planes_minus_one +,
    pub 1]: float v_ratio_pre_cwithout_immediate_flip[number_of_states_plus_one + 1][1 + 1][number_of_planes_minus_one +,
    pub 1]: float required_prefetch_pixel_data_bw_without_immediate_flip[number_of_states_plus_one + 1][1 + 1][number_of_planes_minus_one +,
    pub 1]: dcn_bw_defs prefetch_supported_with_immediate_flip[number_of_states_plus_one + 1][1 +,
    pub 1]: dcn_bw_defs prefetch_supported_without_immediate_flip[number_of_states_plus_one + 1][1 +,
    pub 1]: dcn_bw_defs v_ratio_in_prefetch_supported_with_immediate_flip[number_of_states_plus_one + 1][1 +,
    pub 1]: dcn_bw_defs v_ratio_in_prefetch_supported_without_immediate_flip[number_of_states_plus_one + 1][1 +,
    pub 1]: float required_dispclk[number_of_states_plus_one + 1][1 +,
    pub 1]: dcn_bw_defs dispclk_dppclk_support[number_of_states_plus_one + 1][1 +,
    pub 1]: dcn_bw_defs total_available_pipes_support[number_of_states_plus_one + 1][1 +,
    pub 1]: float total_number_of_active_dpp[number_of_states_plus_one + 1][1 +,
    pub 1]: float total_number_of_dcc_active_dpp[number_of_states_plus_one + 1][1 +,
    pub 1]: dcn_bw_defs urgent_latency_support[number_of_states_plus_one + 1][1 +,
    pub 1]: dcn_bw_defs mode_support_with_immediate_flip[number_of_states_plus_one + 1][1 +,
    pub 1]: dcn_bw_defs mode_support_without_immediate_flip[number_of_states_plus_one + 1][1 +,
    pub 1]: float return_bw_per_state[number_of_states_plus_one +,
    pub 1]: dcn_bw_defs dio_support[number_of_states_plus_one +,
    pub 1]: float urgent_round_trip_and_out_of_order_latency_per_state[number_of_states_plus_one +,
    pub 1]: dcn_bw_defs rob_support[number_of_states_plus_one +,
    pub 1]: dcn_bw_defs bandwidth_support[number_of_states_plus_one +,
    pub 1]: float prefetch_bw[number_of_planes_minus_one +,
    pub 1]: float meta_pte_bytes_per_frame[number_of_planes_minus_one +,
    pub 1]: float meta_row_bytes[number_of_planes_minus_one +,
    pub 1]: float dpte_bytes_per_row[number_of_planes_minus_one +,
    pub 1]: float prefetch_lines_y[number_of_planes_minus_one +,
    pub 1]: float prefetch_lines_c[number_of_planes_minus_one +,
    pub 1]: float max_num_sw_y[number_of_planes_minus_one +,
    pub 1]: float max_num_sw_c[number_of_planes_minus_one +,
    pub 1]: float line_times_for_prefetch[number_of_planes_minus_one +,
    pub 1]: float lines_for_meta_pte_with_immediate_flip[number_of_planes_minus_one +,
    pub 1]: float lines_for_meta_pte_without_immediate_flip[number_of_planes_minus_one +,
    pub 1]: float lines_for_meta_and_dpte_row_with_immediate_flip[number_of_planes_minus_one +,
    pub 1]: float lines_for_meta_and_dpte_row_without_immediate_flip[number_of_planes_minus_one +,
    pub 1]: float min_dppclk_using_single_dpp[number_of_planes_minus_one +,
    pub 1]: float swath_width_ysingle_dpp[number_of_planes_minus_one +,
    pub 1]: float byte_per_pixel_in_dety[number_of_planes_minus_one +,
    pub 1]: float byte_per_pixel_in_detc[number_of_planes_minus_one +,
    pub 1]: float number_of_dpp_required_for_det_and_lb_size[number_of_planes_minus_one +,
    pub 1]: float required_phyclk[number_of_planes_minus_one +,
    pub 1]: float read256_block_height_y[number_of_planes_minus_one +,
    pub 1]: float read256_block_width_y[number_of_planes_minus_one +,
    pub 1]: float read256_block_height_c[number_of_planes_minus_one +,
    pub 1]: float read256_block_width_c[number_of_planes_minus_one +,
    pub 1]: float max_swath_height_y[number_of_planes_minus_one +,
    pub 1]: float max_swath_height_c[number_of_planes_minus_one +,
    pub 1]: float min_swath_height_y[number_of_planes_minus_one +,
    pub 1]: float min_swath_height_c[number_of_planes_minus_one +,
    pub 1]: float read_bandwidth[number_of_planes_minus_one +,
    pub 1]: float write_bandwidth[number_of_planes_minus_one +,
    pub 1]: float pscl_factor[number_of_planes_minus_one +,
    pub 1]: float pscl_factor_chroma[number_of_planes_minus_one +,
    pub scale_ratio_support: dcn_bw_defs,
    pub source_format_pixel_and_scan_support: dcn_bw_defs,
    pub total_read_bandwidth_consumed_gbyte_per_second: float,
    pub total_write_bandwidth_consumed_gbyte_per_second: float,
    pub total_bandwidth_consumed_gbyte_per_second: float,
    pub dcc_enabled_in_any_plane: dcn_bw_defs,
    pub return_bw_todcn_per_state: float,
    pub critical_point: float,
    pub writeback_latency_support: dcn_bw_defs,
    pub required_output_bw: float,
    pub total_number_of_active_writeback: float,
    pub total_available_writeback_support: dcn_bw_defs,
    pub maximum_swath_width: float,
    pub number_of_dpp_required_for_det_size: float,
    pub number_of_dpp_required_for_lb_size: float,
    pub min_dispclk_using_single_dpp: float,
    pub min_dispclk_using_dual_dpp: float,
    pub viewport_size_support: dcn_bw_defs,
    pub swath_width_granularity_y: float,
    pub rounded_up_max_swath_size_bytes_y: float,
    pub swath_width_granularity_c: float,
    pub rounded_up_max_swath_size_bytes_c: float,
    pub lines_in_det_luma: float,
    pub lines_in_det_chroma: float,
    pub effective_lb_latency_hiding_source_lines_luma: float,
    pub effective_lb_latency_hiding_source_lines_chroma: float,
    pub effective_detlb_lines_luma: float,
    pub effective_detlb_lines_chroma: float,
    pub projected_dcfclk_deep_sleep: float,
    pub meta_req_height_y: float,
    pub meta_req_width_y: float,
    pub meta_surface_width_y: float,
    pub meta_surface_height_y: float,
    pub meta_pte_bytes_per_frame_y: float,
    pub meta_row_bytes_y: float,
    pub macro_tile_block_size_bytes_y: float,
    pub macro_tile_block_height_y: float,
    pub data_pte_req_height_y: float,
    pub data_pte_req_width_y: float,
    pub dpte_bytes_per_row_y: float,
    pub meta_req_height_c: float,
    pub meta_req_width_c: float,
    pub meta_surface_width_c: float,
    pub meta_surface_height_c: float,
    pub meta_pte_bytes_per_frame_c: float,
    pub meta_row_bytes_c: float,
    pub macro_tile_block_size_bytes_c: float,
    pub macro_tile_block_height_c: float,
    pub macro_tile_block_width_c: float,
    pub data_pte_req_height_c: float,
    pub data_pte_req_width_c: float,
    pub dpte_bytes_per_row_c: float,
    pub v_init_y: float,
    pub max_partial_sw_y: float,
    pub v_init_c: float,
    pub max_partial_sw_c: float,
    pub dst_x_after_scaler: float,
    pub dst_y_after_scaler: float,
    pub time_calc: float,
    pub 1][2]: float v_update_offset[number_of_planes_minus_one +,
    pub total_repeater_delay: float,
    pub 1][2]: float v_update_width[number_of_planes_minus_one +,
    pub 1][2]: float v_ready_offset[number_of_planes_minus_one +,
    pub time_setup: float,
    pub extra_latency: float,
    pub maximum_vstartup: float,
    pub bw_available_for_immediate_flip: float,
    pub 1]: float total_immediate_flip_bytes[number_of_planes_minus_one +,
    pub time_for_meta_pte_with_immediate_flip: float,
    pub time_for_meta_pte_without_immediate_flip: float,
    pub time_for_meta_and_dpte_row_with_immediate_flip: float,
    pub time_for_meta_and_dpte_row_without_immediate_flip: float,
    pub line_times_to_request_prefetch_pixel_data_with_immediate_flip: float,
    pub line_times_to_request_prefetch_pixel_data_without_immediate_flip: float,
    pub maximum_read_bandwidth_with_prefetch_with_immediate_flip: float,
    pub maximum_read_bandwidth_with_prefetch_without_immediate_flip: float,
    pub voltage_level_with_immediate_flip: float,
    pub voltage_level_without_immediate_flip: float,
    pub 1]: float total_number_of_active_dpp_per_ratio[1 +,
    pub byte_per_pix_dety: float,
    pub byte_per_pix_detc: float,
    pub read256_bytes_block_height_y: float,
    pub read256_bytes_block_width_y: float,
    pub read256_bytes_block_height_c: float,
    pub read256_bytes_block_width_c: float,
    pub maximum_swath_height_y: float,
    pub maximum_swath_height_c: float,
    pub minimum_swath_height_y: float,
    pub minimum_swath_height_c: float,
    pub swath_width: float,
    pub 1]: float prefetch_bandwidth[number_of_planes_minus_one +,
    pub 1]: float v_init_pre_fill_y[number_of_planes_minus_one +,
    pub 1]: float v_init_pre_fill_c[number_of_planes_minus_one +,
    pub 1]: float max_num_swath_y[number_of_planes_minus_one +,
    pub 1]: float max_num_swath_c[number_of_planes_minus_one +,
    pub 1]: float prefill_y[number_of_planes_minus_one +,
    pub 1]: float prefill_c[number_of_planes_minus_one +,
    pub 1]: float v_startup[number_of_planes_minus_one +,
    pub 1]: dcn_bw_defs allow_dram_clock_change_during_vblank[number_of_planes_minus_one +,
    pub 1]: float allow_dram_self_refresh_during_vblank[number_of_planes_minus_one +,
    pub 1]: float v_ratio_prefetch_y[number_of_planes_minus_one +,
    pub 1]: float v_ratio_prefetch_c[number_of_planes_minus_one +,
    pub 1]: float destination_lines_for_prefetch[number_of_planes_minus_one +,
    pub 1]: float destination_lines_to_request_vm_inv_blank[number_of_planes_minus_one +,
    pub 1]: float destination_lines_to_request_row_in_vblank[number_of_planes_minus_one +,
    pub 1]: float min_ttuv_blank[number_of_planes_minus_one +,
    pub 1]: float byte_per_pixel_dety[number_of_planes_minus_one +,
    pub 1]: float byte_per_pixel_detc[number_of_planes_minus_one +,
    pub 1]: float swath_width_y[number_of_planes_minus_one +,
    pub 1]: float lines_in_dety[number_of_planes_minus_one +,
    pub 1]: float lines_in_dety_rounded_down_to_swath[number_of_planes_minus_one +,
    pub 1]: float lines_in_detc[number_of_planes_minus_one +,
    pub 1]: float lines_in_detc_rounded_down_to_swath[number_of_planes_minus_one +,
    pub 1]: float full_det_buffering_time_y[number_of_planes_minus_one +,
    pub 1]: float full_det_buffering_time_c[number_of_planes_minus_one +,
    pub 1]: float active_dram_clock_change_latency_margin[number_of_planes_minus_one +,
    pub 1]: float v_blank_dram_clock_change_latency_margin[number_of_planes_minus_one +,
    pub 1]: float dcfclk_deep_sleep_per_plane[number_of_planes_minus_one +,
    pub 1]: float read_bandwidth_plane_luma[number_of_planes_minus_one +,
    pub 1]: float read_bandwidth_plane_chroma[number_of_planes_minus_one +,
    pub 1]: float display_pipe_line_delivery_time_luma[number_of_planes_minus_one +,
    pub 1]: float display_pipe_line_delivery_time_chroma[number_of_planes_minus_one +,
    pub 1]: float display_pipe_line_delivery_time_luma_prefetch[number_of_planes_minus_one +,
    pub 1]: float display_pipe_line_delivery_time_chroma_prefetch[number_of_planes_minus_one +,
    pub 1]: float pixel_pte_bytes_per_row[number_of_planes_minus_one +,
    pub 1]: float meta_pte_bytes_frame[number_of_planes_minus_one +,
    pub 1]: float meta_row_byte[number_of_planes_minus_one +,
    pub 1]: float prefetch_source_lines_y[number_of_planes_minus_one +,
    pub 1]: float prefetch_source_lines_c[number_of_planes_minus_one +,
    pub 1]: float pscl_throughput[number_of_planes_minus_one +,
    pub 1]: float pscl_throughput_chroma[number_of_planes_minus_one +,
    pub 1]: float output_bpphdmi[number_of_planes_minus_one +,
    pub 1]: float output_bppdp4_lane_hbr[number_of_planes_minus_one +,
    pub 1]: float output_bppdp4_lane_hbr2[number_of_planes_minus_one +,
    pub 1]: float output_bppdp4_lane_hbr3[number_of_planes_minus_one +,
    pub 1]: float max_vstartup_lines[number_of_planes_minus_one +,
    pub dispclk_with_ramping: float,
    pub dispclk_without_ramping: float,
    pub dppclk_using_single_dpp_luma: float,
    pub dppclk_using_single_dpp: float,
    pub dppclk_using_single_dpp_chroma: float,
    pub odm_capable: dcn_bw_defs,
    pub dispclk: float,
    pub dppclk: float,
    pub return_bandwidth_to_dcn: float,
    pub dcc_enabled_any_plane: dcn_bw_defs,
    pub return_bw: float,
    pub critical_compression: float,
    pub total_data_read_bandwidth: float,
    pub total_active_dpp: float,
    pub total_dcc_active_dpp: float,
    pub urgent_round_trip_and_out_of_order_latency: float,
    pub last_pixel_of_line_extra_watermark: float,
    pub data_fabric_line_delivery_time_luma: float,
    pub data_fabric_line_delivery_time_chroma: float,
    pub urgent_extra_latency: float,
    pub urgent_watermark: float,
    pub ptemeta_urgent_watermark: float,
    pub dram_clock_change_watermark: float,
    pub total_active_writeback: float,
    pub writeback_dram_clock_change_watermark: float,
    pub min_full_det_buffering_time: float,
    pub frame_time_for_min_full_det_buffering_time: float,
    pub average_read_bandwidth_gbyte_per_second: float,
    pub part_of_burst_that_fits_in_rob: float,
    pub stutter_burst_time: float,
    pub stutter_efficiency_not_including_vblank: float,
    pub smallest_vblank: float,
    pub v_blank_time: float,
    pub stutter_efficiency: float,
    pub dcf_clk_deep_sleep: float,
    pub stutter_exit_watermark: float,
    pub stutter_enter_plus_exit_watermark: float,
    pub effective_det_plus_lb_lines_luma: float,
    pub urgent_latency_support_us_luma: float,
    pub effective_det_plus_lb_lines_chroma: float,
    pub urgent_latency_support_us_chroma: float,
    pub min_urgent_latency_support_us: float,
    pub non_urgent_latency_tolerance: float,
    pub block_height256_bytes_y: float,
    pub block_height256_bytes_c: float,
    pub meta_request_width_y: float,
    pub meta_surf_width_y: float,
    pub meta_surf_height_y: float,
    pub meta_pte_bytes_frame_y: float,
    pub meta_row_byte_y: float,
    pub macro_tile_size_byte_y: float,
    pub macro_tile_height_y: float,
    pub pixel_pte_req_height_y: float,
    pub pixel_pte_req_width_y: float,
    pub pixel_pte_bytes_per_row_y: float,
    pub meta_request_width_c: float,
    pub meta_surf_width_c: float,
    pub meta_surf_height_c: float,
    pub meta_pte_bytes_frame_c: float,
    pub meta_row_byte_c: float,
    pub macro_tile_size_bytes_c: float,
    pub macro_tile_height_c: float,
    pub pixel_pte_req_height_c: float,
    pub pixel_pte_req_width_c: float,
    pub pixel_pte_bytes_per_row_c: float,
    pub max_partial_swath_y: float,
    pub max_partial_swath_c: float,
    pub t_calc: float,
    pub next_prefetch_mode: float,
    pub v_startup_lines: float,
    pub planes_with_room_to_increase_vstartup_prefetch_bw_less_than_active_bw: dcn_bw_defs,
    pub planes_with_room_to_increase_vstartup_vratio_prefetch_more_than4: dcn_bw_defs,
    pub planes_with_room_to_increase_vstartup_destination_line_times_for_prefetch_less_than2: dcn_bw_defs,
    pub v_ratio_prefetch_more_than4: dcn_bw_defs,
    pub destination_line_times_for_prefetch_less_than2: dcn_bw_defs,
    pub prefetch_mode: float,
    pub dstx_after_scaler: float,
    pub dsty_after_scaler: float,
    pub 1]: float v_update_offset_pix[number_of_planes_minus_one +,
    pub total_repeater_delay_time: float,
    pub 1]: float v_update_width_pix[number_of_planes_minus_one +,
    pub 1]: float v_ready_offset_pix[number_of_planes_minus_one +,
    pub t_setup: float,
    pub t_wait: float,
    pub bandwidth_available_for_immediate_flip: float,
    pub tot_immediate_flip_bytes: float,
    pub max_rd_bandwidth: float,
    pub time_for_fetching_meta_pte: float,
    pub time_for_fetching_row_in_vblank: float,
    pub lines_to_request_prefetch_pixel_data: float,
    pub required_prefetch_pix_data_bw: float,
    pub prefetch_mode_supported: dcn_bw_defs,
    pub active_dp_ps: float,
    pub lb_latency_hiding_source_lines_y: float,
    pub lb_latency_hiding_source_lines_c: float,
    pub effective_lb_latency_hiding_y: float,
    pub effective_lb_latency_hiding_c: float,
    pub dpp_output_buffer_lines_y: float,
    pub dpp_output_buffer_lines_c: float,
    pub dppopp_buffering_y: float,
    pub max_det_buffering_time_y: float,
    pub active_dram_clock_change_latency_margin_y: float,
    pub dppopp_buffering_c: float,
    pub max_det_buffering_time_c: float,
    pub active_dram_clock_change_latency_margin_c: float,
    pub writeback_dram_clock_change_latency_margin: float,
    pub min_active_dram_clock_change_margin: float,
    pub v_blank_of_min_active_dram_clock_change_margin: float,
    pub second_min_active_dram_clock_change_margin: float,
    pub min_vblank_dram_clock_change_margin: float,
    pub dram_clock_change_margin: float,
    pub dram_clock_change_support: float,
    pub wr_bandwidth: float,
    pub max_used_bw: float,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct dcn_soc_bounding_box {
    pub /*us*/: *mut float sr_exit_time;,
    pub /*us*/: *mut float sr_enter_plus_exit_time;,
    pub /*us*/: *mut float urgent_latency;,
    pub /*us*/: *mut float write_back_latency;,
    pub /*%*/: *mut float percent_of_ideal_drambw_received_after_urg_latency;,
    pub /*bytes*/: *mut int max_request_size;,
    pub /*MHz*/: *mut float dcfclkv_max0p9;,
    pub /*MHz*/: *mut float dcfclkv_nom0p8;,
    pub /*MHz*/: *mut float dcfclkv_mid0p72;,
    pub /*MHz*/: *mut float dcfclkv_min0p65;,
    pub /*MHz*/: *mut float max_dispclk_vmax0p9;,
    pub /*MHz*/: *mut float max_dispclk_vmid0p72;,
    pub /*MHz*/: *mut float max_dispclk_vnom0p8;,
    pub /*MHz*/: *mut float max_dispclk_vmin0p65;,
    pub /*MHz*/: *mut float max_dppclk_vmax0p9;,
    pub /*MHz*/: *mut float max_dppclk_vnom0p8;,
    pub /*MHz*/: *mut float max_dppclk_vmid0p72;,
    pub /*MHz*/: *mut float max_dppclk_vmin0p65;,
    pub /*MHz*/: *mut float socclk;,
    pub /*GB/s*/: *mut float fabric_and_dram_bandwidth_vmax0p9;,
    pub /*GB/s*/: *mut float fabric_and_dram_bandwidth_vnom0p8;,
    pub /*GB/s*/: *mut float fabric_and_dram_bandwidth_vmid0p72;,
    pub /*GB/s*/: *mut float fabric_and_dram_bandwidth_vmin0p65;,
    pub /*MHz*/: *mut float phyclkv_max0p9;,
    pub /*MHz*/: *mut float phyclkv_nom0p8;,
    pub /*MHz*/: *mut float phyclkv_mid0p72;,
    pub /*MHz*/: *mut float phyclkv_min0p65;,
    pub /*%*/: *mut float downspreading;,
    pub Cycles*/: *mut *mut int round_trip_ping_latency_cycles; /DCFCLK,
    pub /*bytes*/: *mut int urgent_out_of_order_return_per_channel;,
    pub number_of_channels: c_int,
    pub /*bytes*/: *mut int vmm_page_size;,
    pub /*us*/: *mut float dram_clock_change_latency;,
    pub /*bytes*/: *mut int return_bus_width;,
    pub /*%*/: *mut float percent_disp_bw_limit;,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct dcn_ip_params {
    pub rob_buffer_size_in_kbyte: float,
    pub det_buffer_size_in_kbyte: float,
    pub dpp_output_buffer_pixels: float,
    pub opp_output_buffer_lines: float,
    pub pixel_chunk_size_in_kbyte: float,
    pub pte_enable: dcn_bw_defs,
    pub /*kbytes*/: *mut int pte_chunk_size;,
    pub /*kbytes*/: *mut int meta_chunk_size;,
    pub /*kbytes*/: *mut int writeback_chunk_size;,
    pub odm_capability: dcn_bw_defs,
    pub dsc_capability: dcn_bw_defs,
    pub /*bit*/: *mut int line_buffer_size;,
    pub max_line_buffer_lines: c_int,
    pub is_line_buffer_bpp_fixed: dcn_bw_defs,
    pub line_buffer_fixed_bpp: c_int,
    pub /*kbytes*/: *mut int writeback_luma_buffer_size;,
    pub /*kbytes*/: *mut int writeback_chroma_buffer_size;,
    pub max_num_dpp: c_int,
    pub max_num_writeback: c_int,
    pub /*pixels/dppclk*/: *mut int max_dchub_topscl_throughput;,
    pub /*pixels/dppclk*/: *mut int max_pscl_tolb_throughput;,
    pub /*pixels/dppclk*/: *mut int max_lb_tovscl_throughput;,
    pub /*pixels/dppclk*/: *mut int max_vscl_tohscl_throughput;,
    pub max_hscl_ratio: float,
    pub max_vscl_ratio: float,
    pub max_hscl_taps: c_int,
    pub max_vscl_taps: c_int,
    pub pte_buffer_size_in_requests: c_int,
    pub /*%*/: *mut float dispclk_ramping_margin;,
    pub under_scan_factor: float,
    pub max_inter_dcn_tile_repeaters: c_int,
    pub can_vstartup_lines_exceed_vsync_plus_back_porch_lines_minus_one: dcn_bw_defs,
    pub bug_forcing_luma_and_chroma_request_to_same_size_fixed: dcn_bw_defs,
    pub dcfclk_cstate_latency: c_int,
}

extern "C" {
    pub fn dcn_bw_sync_calcs_and_dml(dc: *mut dc);
}
extern "C" {
    pub fn swizzle_mode_to_macro_tile_size(sw_mode: swizzle_mode_values) -> source_macro_tile_size;
}
