//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/amd/include/asic_reg/uvd/uvd_7_0_sh_mask.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// Copyright (C) 2017  Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
// AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

// Macro flag: #define _uvd_7_0_SH_MASK_HEADER
// addressBlock: uvd0_uvd_pg_dec
// UVD_POWER_STATUS
pub const UVD_POWER_STATUS__UVD_POWER_STATUS__SHIFT: c_uint = 0x0;
pub const UVD_POWER_STATUS__UVD_PG_MODE__SHIFT: c_uint = 0x2;
pub const UVD_POWER_STATUS__UVD_STATUS_CHECK_TIMEOUT__SHIFT: c_uint = 0x3;
pub const UVD_POWER_STATUS__PWR_ON_CHECK_TIMEOUT__SHIFT: c_uint = 0x4;
pub const UVD_POWER_STATUS__PWR_OFF_CHECK_TIMEOUT__SHIFT: c_uint = 0x5;
pub const UVD_POWER_STATUS__UVD_PGFSM_TIMEOUT_MODE__SHIFT: c_uint = 0x6;
pub const UVD_POWER_STATUS__UVD_PG_EN__SHIFT: c_uint = 0x8;
pub const UVD_POWER_STATUS__PAUSE_DPG_REQ__SHIFT: c_uint = 0x9;
pub const UVD_POWER_STATUS__PAUSE_DPG_ACK__SHIFT: c_uint = 0xa;
pub const UVD_POWER_STATUS__UVD_POWER_STATUS_MASK: c_uint = 0x00000003L;
pub const UVD_POWER_STATUS__UVD_PG_MODE_MASK: c_uint = 0x00000004L;
pub const UVD_POWER_STATUS__UVD_STATUS_CHECK_TIMEOUT_MASK: c_uint = 0x00000008L;
pub const UVD_POWER_STATUS__PWR_ON_CHECK_TIMEOUT_MASK: c_uint = 0x00000010L;
pub const UVD_POWER_STATUS__PWR_OFF_CHECK_TIMEOUT_MASK: c_uint = 0x00000020L;
pub const UVD_POWER_STATUS__UVD_PGFSM_TIMEOUT_MODE_MASK: c_uint = 0x000000C0L;
pub const UVD_POWER_STATUS__UVD_PG_EN_MASK: c_uint = 0x00000100L;
pub const UVD_POWER_STATUS__PAUSE_DPG_REQ_MASK: c_uint = 0x00000200L;
pub const UVD_POWER_STATUS__PAUSE_DPG_ACK_MASK: c_uint = 0x00000400L;
// UVD_DPG_RBC_RB_CNTL
pub const UVD_DPG_RBC_RB_CNTL__RB_BUFSZ__SHIFT: c_uint = 0x0;
pub const UVD_DPG_RBC_RB_CNTL__RB_BLKSZ__SHIFT: c_uint = 0x8;
pub const UVD_DPG_RBC_RB_CNTL__RB_NO_FETCH__SHIFT: c_uint = 0x10;
pub const UVD_DPG_RBC_RB_CNTL__RB_WPTR_POLL_EN__SHIFT: c_uint = 0x14;
pub const UVD_DPG_RBC_RB_CNTL__RB_NO_UPDATE__SHIFT: c_uint = 0x18;
pub const UVD_DPG_RBC_RB_CNTL__RB_RPTR_WR_EN__SHIFT: c_uint = 0x1c;
pub const UVD_DPG_RBC_RB_CNTL__RB_BUFSZ_MASK: c_uint = 0x0000001FL;
pub const UVD_DPG_RBC_RB_CNTL__RB_BLKSZ_MASK: c_uint = 0x00001F00L;
pub const UVD_DPG_RBC_RB_CNTL__RB_NO_FETCH_MASK: c_uint = 0x00010000L;
pub const UVD_DPG_RBC_RB_CNTL__RB_WPTR_POLL_EN_MASK: c_uint = 0x00100000L;
pub const UVD_DPG_RBC_RB_CNTL__RB_NO_UPDATE_MASK: c_uint = 0x01000000L;
pub const UVD_DPG_RBC_RB_CNTL__RB_RPTR_WR_EN_MASK: c_uint = 0x10000000L;
// UVD_DPG_RBC_RB_BASE_LOW
pub const UVD_DPG_RBC_RB_BASE_LOW__RB_BASE_LOW__SHIFT: c_uint = 0x0;
pub const UVD_DPG_RBC_RB_BASE_LOW__RB_BASE_LOW_MASK: c_uint = 0xFFFFFFFFL;
// UVD_DPG_RBC_RB_BASE_HIGH
pub const UVD_DPG_RBC_RB_BASE_HIGH__RB_BASE_HIGH__SHIFT: c_uint = 0x0;
pub const UVD_DPG_RBC_RB_BASE_HIGH__RB_BASE_HIGH_MASK: c_uint = 0xFFFFFFFFL;
// UVD_DPG_RBC_RB_WPTR_CNTL
pub const UVD_DPG_RBC_RB_WPTR_CNTL__RB_PRE_WRITE_TIMER__SHIFT: c_uint = 0x0;
pub const UVD_DPG_RBC_RB_WPTR_CNTL__RB_PRE_WRITE_TIMER_MASK: c_uint = 0x00007FFFL;
// UVD_DPG_RBC_RB_RPTR
pub const UVD_DPG_RBC_RB_RPTR__RB_RPTR__SHIFT: c_uint = 0x4;
pub const UVD_DPG_RBC_RB_RPTR__RB_RPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_DPG_RBC_RB_WPTR
pub const UVD_DPG_RBC_RB_WPTR__RB_WPTR__SHIFT: c_uint = 0x4;
pub const UVD_DPG_RBC_RB_WPTR__RB_WPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_DPG_LMI_VCPU_CACHE_64BIT_BAR_LOW
pub const UVD_DPG_LMI_VCPU_CACHE_64BIT_BAR_LOW__BITS_31_0__SHIFT: c_uint = 0x0;
pub const UVD_DPG_LMI_VCPU_CACHE_64BIT_BAR_LOW__BITS_31_0_MASK: c_uint = 0xFFFFFFFFL;
// UVD_DPG_LMI_VCPU_CACHE_64BIT_BAR_HIGH
pub const UVD_DPG_LMI_VCPU_CACHE_64BIT_BAR_HIGH__BITS_63_32__SHIFT: c_uint = 0x0;
pub const UVD_DPG_LMI_VCPU_CACHE_64BIT_BAR_HIGH__BITS_63_32_MASK: c_uint = 0xFFFFFFFFL;
// UVD_DPG_VCPU_CACHE_OFFSET0
pub const UVD_DPG_VCPU_CACHE_OFFSET0__CACHE_OFFSET0__SHIFT: c_uint = 0x0;
pub const UVD_DPG_VCPU_CACHE_OFFSET0__CACHE_OFFSET0_MASK: c_uint = 0x01FFFFFFL;
// addressBlock: uvd0_uvdnpdec
// UVD_JPEG_ADDR_CONFIG
pub const UVD_JPEG_ADDR_CONFIG__NUM_PIPES__SHIFT: c_uint = 0x0;
pub const UVD_JPEG_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE__SHIFT: c_uint = 0x3;
pub const UVD_JPEG_ADDR_CONFIG__MAX_COMPRESSED_FRAGS__SHIFT: c_uint = 0x6;
pub const UVD_JPEG_ADDR_CONFIG__BANK_INTERLEAVE_SIZE__SHIFT: c_uint = 0x8;
pub const UVD_JPEG_ADDR_CONFIG__NUM_BANKS__SHIFT: c_uint = 0xc;
pub const UVD_JPEG_ADDR_CONFIG__SHADER_ENGINE_TILE_SIZE__SHIFT: c_uint = 0x10;
pub const UVD_JPEG_ADDR_CONFIG__NUM_SHADER_ENGINES__SHIFT: c_uint = 0x13;
pub const UVD_JPEG_ADDR_CONFIG__NUM_GPUS__SHIFT: c_uint = 0x15;
pub const UVD_JPEG_ADDR_CONFIG__MULTI_GPU_TILE_SIZE__SHIFT: c_uint = 0x18;
pub const UVD_JPEG_ADDR_CONFIG__NUM_RB_PER_SE__SHIFT: c_uint = 0x1a;
pub const UVD_JPEG_ADDR_CONFIG__ROW_SIZE__SHIFT: c_uint = 0x1c;
pub const UVD_JPEG_ADDR_CONFIG__NUM_LOWER_PIPES__SHIFT: c_uint = 0x1e;
pub const UVD_JPEG_ADDR_CONFIG__SE_ENABLE__SHIFT: c_uint = 0x1f;
pub const UVD_JPEG_ADDR_CONFIG__NUM_PIPES_MASK: c_uint = 0x00000007L;
pub const UVD_JPEG_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE_MASK: c_uint = 0x00000038L;
pub const UVD_JPEG_ADDR_CONFIG__MAX_COMPRESSED_FRAGS_MASK: c_uint = 0x000000C0L;
pub const UVD_JPEG_ADDR_CONFIG__BANK_INTERLEAVE_SIZE_MASK: c_uint = 0x00000700L;
pub const UVD_JPEG_ADDR_CONFIG__NUM_BANKS_MASK: c_uint = 0x00007000L;
pub const UVD_JPEG_ADDR_CONFIG__SHADER_ENGINE_TILE_SIZE_MASK: c_uint = 0x00070000L;
pub const UVD_JPEG_ADDR_CONFIG__NUM_SHADER_ENGINES_MASK: c_uint = 0x00180000L;
pub const UVD_JPEG_ADDR_CONFIG__NUM_GPUS_MASK: c_uint = 0x00E00000L;
pub const UVD_JPEG_ADDR_CONFIG__MULTI_GPU_TILE_SIZE_MASK: c_uint = 0x03000000L;
pub const UVD_JPEG_ADDR_CONFIG__NUM_RB_PER_SE_MASK: c_uint = 0x0C000000L;
pub const UVD_JPEG_ADDR_CONFIG__ROW_SIZE_MASK: c_uint = 0x30000000L;
pub const UVD_JPEG_ADDR_CONFIG__NUM_LOWER_PIPES_MASK: c_uint = 0x40000000L;
pub const UVD_JPEG_ADDR_CONFIG__SE_ENABLE_MASK: c_uint = 0x80000000L;
// UVD_GPCOM_VCPU_CMD
pub const UVD_GPCOM_VCPU_CMD__CMD_SEND__SHIFT: c_uint = 0x0;
pub const UVD_GPCOM_VCPU_CMD__CMD__SHIFT: c_uint = 0x1;
pub const UVD_GPCOM_VCPU_CMD__CMD_SOURCE__SHIFT: c_uint = 0x1f;
pub const UVD_GPCOM_VCPU_CMD__CMD_SEND_MASK: c_uint = 0x00000001L;
pub const UVD_GPCOM_VCPU_CMD__CMD_MASK: c_uint = 0x7FFFFFFEL;
pub const UVD_GPCOM_VCPU_CMD__CMD_SOURCE_MASK: c_uint = 0x80000000L;
// UVD_GPCOM_VCPU_DATA0
pub const UVD_GPCOM_VCPU_DATA0__DATA0__SHIFT: c_uint = 0x0;
pub const UVD_GPCOM_VCPU_DATA0__DATA0_MASK: c_uint = 0xFFFFFFFFL;
// UVD_GPCOM_VCPU_DATA1
pub const UVD_GPCOM_VCPU_DATA1__DATA1__SHIFT: c_uint = 0x0;
pub const UVD_GPCOM_VCPU_DATA1__DATA1_MASK: c_uint = 0xFFFFFFFFL;
// UVD_UDEC_ADDR_CONFIG
pub const UVD_UDEC_ADDR_CONFIG__NUM_PIPES__SHIFT: c_uint = 0x0;
pub const UVD_UDEC_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE__SHIFT: c_uint = 0x3;
pub const UVD_UDEC_ADDR_CONFIG__MAX_COMPRESSED_FRAGS__SHIFT: c_uint = 0x6;
pub const UVD_UDEC_ADDR_CONFIG__BANK_INTERLEAVE_SIZE__SHIFT: c_uint = 0x8;
pub const UVD_UDEC_ADDR_CONFIG__NUM_BANKS__SHIFT: c_uint = 0xc;
pub const UVD_UDEC_ADDR_CONFIG__SHADER_ENGINE_TILE_SIZE__SHIFT: c_uint = 0x10;
pub const UVD_UDEC_ADDR_CONFIG__NUM_SHADER_ENGINES__SHIFT: c_uint = 0x13;
pub const UVD_UDEC_ADDR_CONFIG__NUM_GPUS__SHIFT: c_uint = 0x15;
pub const UVD_UDEC_ADDR_CONFIG__MULTI_GPU_TILE_SIZE__SHIFT: c_uint = 0x18;
pub const UVD_UDEC_ADDR_CONFIG__NUM_RB_PER_SE__SHIFT: c_uint = 0x1a;
pub const UVD_UDEC_ADDR_CONFIG__ROW_SIZE__SHIFT: c_uint = 0x1c;
pub const UVD_UDEC_ADDR_CONFIG__NUM_LOWER_PIPES__SHIFT: c_uint = 0x1e;
pub const UVD_UDEC_ADDR_CONFIG__SE_ENABLE__SHIFT: c_uint = 0x1f;
pub const UVD_UDEC_ADDR_CONFIG__NUM_PIPES_MASK: c_uint = 0x00000007L;
pub const UVD_UDEC_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE_MASK: c_uint = 0x00000038L;
pub const UVD_UDEC_ADDR_CONFIG__MAX_COMPRESSED_FRAGS_MASK: c_uint = 0x000000C0L;
pub const UVD_UDEC_ADDR_CONFIG__BANK_INTERLEAVE_SIZE_MASK: c_uint = 0x00000700L;
pub const UVD_UDEC_ADDR_CONFIG__NUM_BANKS_MASK: c_uint = 0x00007000L;
pub const UVD_UDEC_ADDR_CONFIG__SHADER_ENGINE_TILE_SIZE_MASK: c_uint = 0x00070000L;
pub const UVD_UDEC_ADDR_CONFIG__NUM_SHADER_ENGINES_MASK: c_uint = 0x00180000L;
pub const UVD_UDEC_ADDR_CONFIG__NUM_GPUS_MASK: c_uint = 0x00E00000L;
pub const UVD_UDEC_ADDR_CONFIG__MULTI_GPU_TILE_SIZE_MASK: c_uint = 0x03000000L;
pub const UVD_UDEC_ADDR_CONFIG__NUM_RB_PER_SE_MASK: c_uint = 0x0C000000L;
pub const UVD_UDEC_ADDR_CONFIG__ROW_SIZE_MASK: c_uint = 0x30000000L;
pub const UVD_UDEC_ADDR_CONFIG__NUM_LOWER_PIPES_MASK: c_uint = 0x40000000L;
pub const UVD_UDEC_ADDR_CONFIG__SE_ENABLE_MASK: c_uint = 0x80000000L;
// UVD_UDEC_DB_ADDR_CONFIG
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_PIPES__SHIFT: c_uint = 0x0;
pub const UVD_UDEC_DB_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE__SHIFT: c_uint = 0x3;
pub const UVD_UDEC_DB_ADDR_CONFIG__MAX_COMPRESSED_FRAGS__SHIFT: c_uint = 0x6;
pub const UVD_UDEC_DB_ADDR_CONFIG__BANK_INTERLEAVE_SIZE__SHIFT: c_uint = 0x8;
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_BANKS__SHIFT: c_uint = 0xc;
pub const UVD_UDEC_DB_ADDR_CONFIG__SHADER_ENGINE_TILE_SIZE__SHIFT: c_uint = 0x10;
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_SHADER_ENGINES__SHIFT: c_uint = 0x13;
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_GPUS__SHIFT: c_uint = 0x15;
pub const UVD_UDEC_DB_ADDR_CONFIG__MULTI_GPU_TILE_SIZE__SHIFT: c_uint = 0x18;
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_RB_PER_SE__SHIFT: c_uint = 0x1a;
pub const UVD_UDEC_DB_ADDR_CONFIG__ROW_SIZE__SHIFT: c_uint = 0x1c;
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_LOWER_PIPES__SHIFT: c_uint = 0x1e;
pub const UVD_UDEC_DB_ADDR_CONFIG__SE_ENABLE__SHIFT: c_uint = 0x1f;
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_PIPES_MASK: c_uint = 0x00000007L;
pub const UVD_UDEC_DB_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE_MASK: c_uint = 0x00000038L;
pub const UVD_UDEC_DB_ADDR_CONFIG__MAX_COMPRESSED_FRAGS_MASK: c_uint = 0x000000C0L;
pub const UVD_UDEC_DB_ADDR_CONFIG__BANK_INTERLEAVE_SIZE_MASK: c_uint = 0x00000700L;
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_BANKS_MASK: c_uint = 0x00007000L;
pub const UVD_UDEC_DB_ADDR_CONFIG__SHADER_ENGINE_TILE_SIZE_MASK: c_uint = 0x00070000L;
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_SHADER_ENGINES_MASK: c_uint = 0x00180000L;
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_GPUS_MASK: c_uint = 0x00E00000L;
pub const UVD_UDEC_DB_ADDR_CONFIG__MULTI_GPU_TILE_SIZE_MASK: c_uint = 0x03000000L;
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_RB_PER_SE_MASK: c_uint = 0x0C000000L;
pub const UVD_UDEC_DB_ADDR_CONFIG__ROW_SIZE_MASK: c_uint = 0x30000000L;
pub const UVD_UDEC_DB_ADDR_CONFIG__NUM_LOWER_PIPES_MASK: c_uint = 0x40000000L;
pub const UVD_UDEC_DB_ADDR_CONFIG__SE_ENABLE_MASK: c_uint = 0x80000000L;
// UVD_UDEC_DBW_ADDR_CONFIG
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_PIPES__SHIFT: c_uint = 0x0;
pub const UVD_UDEC_DBW_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE__SHIFT: c_uint = 0x3;
pub const UVD_UDEC_DBW_ADDR_CONFIG__MAX_COMPRESSED_FRAGS__SHIFT: c_uint = 0x6;
pub const UVD_UDEC_DBW_ADDR_CONFIG__BANK_INTERLEAVE_SIZE__SHIFT: c_uint = 0x8;
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_BANKS__SHIFT: c_uint = 0xc;
pub const UVD_UDEC_DBW_ADDR_CONFIG__SHADER_ENGINE_TILE_SIZE__SHIFT: c_uint = 0x10;
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_SHADER_ENGINES__SHIFT: c_uint = 0x13;
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_GPUS__SHIFT: c_uint = 0x15;
pub const UVD_UDEC_DBW_ADDR_CONFIG__MULTI_GPU_TILE_SIZE__SHIFT: c_uint = 0x18;
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_RB_PER_SE__SHIFT: c_uint = 0x1a;
pub const UVD_UDEC_DBW_ADDR_CONFIG__ROW_SIZE__SHIFT: c_uint = 0x1c;
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_LOWER_PIPES__SHIFT: c_uint = 0x1e;
pub const UVD_UDEC_DBW_ADDR_CONFIG__SE_ENABLE__SHIFT: c_uint = 0x1f;
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_PIPES_MASK: c_uint = 0x00000007L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE_MASK: c_uint = 0x00000038L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__MAX_COMPRESSED_FRAGS_MASK: c_uint = 0x000000C0L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__BANK_INTERLEAVE_SIZE_MASK: c_uint = 0x00000700L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_BANKS_MASK: c_uint = 0x00007000L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__SHADER_ENGINE_TILE_SIZE_MASK: c_uint = 0x00070000L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_SHADER_ENGINES_MASK: c_uint = 0x00180000L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_GPUS_MASK: c_uint = 0x00E00000L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__MULTI_GPU_TILE_SIZE_MASK: c_uint = 0x03000000L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_RB_PER_SE_MASK: c_uint = 0x0C000000L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__ROW_SIZE_MASK: c_uint = 0x30000000L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__NUM_LOWER_PIPES_MASK: c_uint = 0x40000000L;
pub const UVD_UDEC_DBW_ADDR_CONFIG__SE_ENABLE_MASK: c_uint = 0x80000000L;
// UVD_SUVD_CGC_GATE
pub const UVD_SUVD_CGC_GATE__SRE__SHIFT: c_uint = 0x0;
pub const UVD_SUVD_CGC_GATE__SIT__SHIFT: c_uint = 0x1;
pub const UVD_SUVD_CGC_GATE__SMP__SHIFT: c_uint = 0x2;
pub const UVD_SUVD_CGC_GATE__SCM__SHIFT: c_uint = 0x3;
pub const UVD_SUVD_CGC_GATE__SDB__SHIFT: c_uint = 0x4;
pub const UVD_SUVD_CGC_GATE__SRE_H264__SHIFT: c_uint = 0x5;
pub const UVD_SUVD_CGC_GATE__SRE_HEVC__SHIFT: c_uint = 0x6;
pub const UVD_SUVD_CGC_GATE__SIT_H264__SHIFT: c_uint = 0x7;
pub const UVD_SUVD_CGC_GATE__SIT_HEVC__SHIFT: c_uint = 0x8;
pub const UVD_SUVD_CGC_GATE__SCM_H264__SHIFT: c_uint = 0x9;
pub const UVD_SUVD_CGC_GATE__SCM_HEVC__SHIFT: c_uint = 0xa;
pub const UVD_SUVD_CGC_GATE__SDB_H264__SHIFT: c_uint = 0xb;
pub const UVD_SUVD_CGC_GATE__SDB_HEVC__SHIFT: c_uint = 0xc;
pub const UVD_SUVD_CGC_GATE__SCLR__SHIFT: c_uint = 0xd;
pub const UVD_SUVD_CGC_GATE__UVD_SC__SHIFT: c_uint = 0xe;
pub const UVD_SUVD_CGC_GATE__ENT__SHIFT: c_uint = 0xf;
pub const UVD_SUVD_CGC_GATE__IME__SHIFT: c_uint = 0x10;
pub const UVD_SUVD_CGC_GATE__SIT_HEVC_DEC__SHIFT: c_uint = 0x11;
pub const UVD_SUVD_CGC_GATE__SIT_HEVC_ENC__SHIFT: c_uint = 0x12;
pub const UVD_SUVD_CGC_GATE__SRE_MASK: c_uint = 0x00000001L;
pub const UVD_SUVD_CGC_GATE__SIT_MASK: c_uint = 0x00000002L;
pub const UVD_SUVD_CGC_GATE__SMP_MASK: c_uint = 0x00000004L;
pub const UVD_SUVD_CGC_GATE__SCM_MASK: c_uint = 0x00000008L;
pub const UVD_SUVD_CGC_GATE__SDB_MASK: c_uint = 0x00000010L;
pub const UVD_SUVD_CGC_GATE__SRE_H264_MASK: c_uint = 0x00000020L;
pub const UVD_SUVD_CGC_GATE__SRE_HEVC_MASK: c_uint = 0x00000040L;
pub const UVD_SUVD_CGC_GATE__SIT_H264_MASK: c_uint = 0x00000080L;
pub const UVD_SUVD_CGC_GATE__SIT_HEVC_MASK: c_uint = 0x00000100L;
pub const UVD_SUVD_CGC_GATE__SCM_H264_MASK: c_uint = 0x00000200L;
pub const UVD_SUVD_CGC_GATE__SCM_HEVC_MASK: c_uint = 0x00000400L;
pub const UVD_SUVD_CGC_GATE__SDB_H264_MASK: c_uint = 0x00000800L;
pub const UVD_SUVD_CGC_GATE__SDB_HEVC_MASK: c_uint = 0x00001000L;
pub const UVD_SUVD_CGC_GATE__SCLR_MASK: c_uint = 0x00002000L;
pub const UVD_SUVD_CGC_GATE__UVD_SC_MASK: c_uint = 0x00004000L;
pub const UVD_SUVD_CGC_GATE__ENT_MASK: c_uint = 0x00008000L;
pub const UVD_SUVD_CGC_GATE__IME_MASK: c_uint = 0x00010000L;
pub const UVD_SUVD_CGC_GATE__SIT_HEVC_DEC_MASK: c_uint = 0x00020000L;
pub const UVD_SUVD_CGC_GATE__SIT_HEVC_ENC_MASK: c_uint = 0x00040000L;
// UVD_SUVD_CGC_CTRL
pub const UVD_SUVD_CGC_CTRL__SRE_MODE__SHIFT: c_uint = 0x0;
pub const UVD_SUVD_CGC_CTRL__SIT_MODE__SHIFT: c_uint = 0x1;
pub const UVD_SUVD_CGC_CTRL__SMP_MODE__SHIFT: c_uint = 0x2;
pub const UVD_SUVD_CGC_CTRL__SCM_MODE__SHIFT: c_uint = 0x3;
pub const UVD_SUVD_CGC_CTRL__SDB_MODE__SHIFT: c_uint = 0x4;
pub const UVD_SUVD_CGC_CTRL__SCLR_MODE__SHIFT: c_uint = 0x5;
pub const UVD_SUVD_CGC_CTRL__UVD_SC_MODE__SHIFT: c_uint = 0x6;
pub const UVD_SUVD_CGC_CTRL__ENT_MODE__SHIFT: c_uint = 0x7;
pub const UVD_SUVD_CGC_CTRL__IME_MODE__SHIFT: c_uint = 0x8;
pub const UVD_SUVD_CGC_CTRL__SRE_MODE_MASK: c_uint = 0x00000001L;
pub const UVD_SUVD_CGC_CTRL__SIT_MODE_MASK: c_uint = 0x00000002L;
pub const UVD_SUVD_CGC_CTRL__SMP_MODE_MASK: c_uint = 0x00000004L;
pub const UVD_SUVD_CGC_CTRL__SCM_MODE_MASK: c_uint = 0x00000008L;
pub const UVD_SUVD_CGC_CTRL__SDB_MODE_MASK: c_uint = 0x00000010L;
pub const UVD_SUVD_CGC_CTRL__SCLR_MODE_MASK: c_uint = 0x00000020L;
pub const UVD_SUVD_CGC_CTRL__UVD_SC_MODE_MASK: c_uint = 0x00000040L;
pub const UVD_SUVD_CGC_CTRL__ENT_MODE_MASK: c_uint = 0x00000080L;
pub const UVD_SUVD_CGC_CTRL__IME_MODE_MASK: c_uint = 0x00000100L;
// UVD_LMI_VCPU_CACHE1_64BIT_BAR_LOW
pub const UVD_LMI_VCPU_CACHE1_64BIT_BAR_LOW__BITS_31_0__SHIFT: c_uint = 0x0;
pub const UVD_LMI_VCPU_CACHE1_64BIT_BAR_LOW__BITS_31_0_MASK: c_uint = 0xFFFFFFFFL;
// UVD_LMI_VCPU_CACHE1_64BIT_BAR_HIGH
pub const UVD_LMI_VCPU_CACHE1_64BIT_BAR_HIGH__BITS_63_32__SHIFT: c_uint = 0x0;
pub const UVD_LMI_VCPU_CACHE1_64BIT_BAR_HIGH__BITS_63_32_MASK: c_uint = 0xFFFFFFFFL;
// UVD_LMI_VCPU_CACHE2_64BIT_BAR_LOW
pub const UVD_LMI_VCPU_CACHE2_64BIT_BAR_LOW__BITS_31_0__SHIFT: c_uint = 0x0;
pub const UVD_LMI_VCPU_CACHE2_64BIT_BAR_LOW__BITS_31_0_MASK: c_uint = 0xFFFFFFFFL;
// UVD_LMI_VCPU_CACHE2_64BIT_BAR_HIGH
pub const UVD_LMI_VCPU_CACHE2_64BIT_BAR_HIGH__BITS_63_32__SHIFT: c_uint = 0x0;
pub const UVD_LMI_VCPU_CACHE2_64BIT_BAR_HIGH__BITS_63_32_MASK: c_uint = 0xFFFFFFFFL;
// UVD_POWER_STATUS_U
pub const UVD_POWER_STATUS_U__UVD_POWER_STATUS__SHIFT: c_uint = 0x0;
pub const UVD_POWER_STATUS_U__UVD_POWER_STATUS_MASK: c_uint = 0x00000003L;
// UVD_NO_OP
pub const UVD_NO_OP__NO_OP__SHIFT: c_uint = 0x0;
pub const UVD_NO_OP__NO_OP_MASK: c_uint = 0xFFFFFFFFL;
// UVD_GP_SCRATCH8
pub const UVD_GP_SCRATCH8__DATA__SHIFT: c_uint = 0x0;
pub const UVD_GP_SCRATCH8__DATA_MASK: c_uint = 0xFFFFFFFFL;
// UVD_RB_BASE_LO2
pub const UVD_RB_BASE_LO2__RB_BASE_LO__SHIFT: c_uint = 0x6;
pub const UVD_RB_BASE_LO2__RB_BASE_LO_MASK: c_uint = 0xFFFFFFC0L;
// UVD_RB_BASE_HI2
pub const UVD_RB_BASE_HI2__RB_BASE_HI__SHIFT: c_uint = 0x0;
pub const UVD_RB_BASE_HI2__RB_BASE_HI_MASK: c_uint = 0xFFFFFFFFL;
// UVD_RB_SIZE2
pub const UVD_RB_SIZE2__RB_SIZE__SHIFT: c_uint = 0x4;
pub const UVD_RB_SIZE2__RB_SIZE_MASK: c_uint = 0x007FFFF0L;
// UVD_RB_RPTR2
pub const UVD_RB_RPTR2__RB_RPTR__SHIFT: c_uint = 0x4;
pub const UVD_RB_RPTR2__RB_RPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_RB_WPTR2
pub const UVD_RB_WPTR2__RB_WPTR__SHIFT: c_uint = 0x4;
pub const UVD_RB_WPTR2__RB_WPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_RB_BASE_LO
pub const UVD_RB_BASE_LO__RB_BASE_LO__SHIFT: c_uint = 0x6;
pub const UVD_RB_BASE_LO__RB_BASE_LO_MASK: c_uint = 0xFFFFFFC0L;
// UVD_RB_BASE_HI
pub const UVD_RB_BASE_HI__RB_BASE_HI__SHIFT: c_uint = 0x0;
pub const UVD_RB_BASE_HI__RB_BASE_HI_MASK: c_uint = 0xFFFFFFFFL;
// UVD_RB_SIZE
pub const UVD_RB_SIZE__RB_SIZE__SHIFT: c_uint = 0x4;
pub const UVD_RB_SIZE__RB_SIZE_MASK: c_uint = 0x007FFFF0L;
// UVD_RB_RPTR
pub const UVD_RB_RPTR__RB_RPTR__SHIFT: c_uint = 0x4;
pub const UVD_RB_RPTR__RB_RPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_RB_WPTR
pub const UVD_RB_WPTR__RB_WPTR__SHIFT: c_uint = 0x4;
pub const UVD_RB_WPTR__RB_WPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_JRBC_RB_RPTR
pub const UVD_JRBC_RB_RPTR__RB_RPTR__SHIFT: c_uint = 0x4;
pub const UVD_JRBC_RB_RPTR__RB_RPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_LMI_VCPU_CACHE_64BIT_BAR_HIGH
pub const UVD_LMI_VCPU_CACHE_64BIT_BAR_HIGH__BITS_63_32__SHIFT: c_uint = 0x0;
pub const UVD_LMI_VCPU_CACHE_64BIT_BAR_HIGH__BITS_63_32_MASK: c_uint = 0xFFFFFFFFL;
// UVD_LMI_VCPU_CACHE_64BIT_BAR_LOW
pub const UVD_LMI_VCPU_CACHE_64BIT_BAR_LOW__BITS_31_0__SHIFT: c_uint = 0x0;
pub const UVD_LMI_VCPU_CACHE_64BIT_BAR_LOW__BITS_31_0_MASK: c_uint = 0xFFFFFFFFL;
// UVD_LMI_RBC_IB_64BIT_BAR_HIGH
pub const UVD_LMI_RBC_IB_64BIT_BAR_HIGH__BITS_63_32__SHIFT: c_uint = 0x0;
pub const UVD_LMI_RBC_IB_64BIT_BAR_HIGH__BITS_63_32_MASK: c_uint = 0xFFFFFFFFL;
// UVD_LMI_RBC_IB_64BIT_BAR_LOW
pub const UVD_LMI_RBC_IB_64BIT_BAR_LOW__BITS_31_0__SHIFT: c_uint = 0x0;
pub const UVD_LMI_RBC_IB_64BIT_BAR_LOW__BITS_31_0_MASK: c_uint = 0xFFFFFFFFL;
// UVD_LMI_RBC_RB_64BIT_BAR_HIGH
pub const UVD_LMI_RBC_RB_64BIT_BAR_HIGH__BITS_63_32__SHIFT: c_uint = 0x0;
pub const UVD_LMI_RBC_RB_64BIT_BAR_HIGH__BITS_63_32_MASK: c_uint = 0xFFFFFFFFL;
// UVD_LMI_RBC_RB_64BIT_BAR_LOW
pub const UVD_LMI_RBC_RB_64BIT_BAR_LOW__BITS_31_0__SHIFT: c_uint = 0x0;
pub const UVD_LMI_RBC_RB_64BIT_BAR_LOW__BITS_31_0_MASK: c_uint = 0xFFFFFFFFL;
// addressBlock: uvd0_uvddec
// UVD_SEMA_CNTL
pub const UVD_SEMA_CNTL__SEMAPHORE_EN__SHIFT: c_uint = 0x0;
pub const UVD_SEMA_CNTL__ADVANCED_MODE_DIS__SHIFT: c_uint = 0x1;
pub const UVD_SEMA_CNTL__SEMAPHORE_EN_MASK: c_uint = 0x00000001L;
pub const UVD_SEMA_CNTL__ADVANCED_MODE_DIS_MASK: c_uint = 0x00000002L;
// UVD_LMI_JRBC_RB_64BIT_BAR_LOW
pub const UVD_LMI_JRBC_RB_64BIT_BAR_LOW__BITS_31_0__SHIFT: c_uint = 0x0;
pub const UVD_LMI_JRBC_RB_64BIT_BAR_LOW__BITS_31_0_MASK: c_uint = 0xFFFFFFFFL;
// UVD_JRBC_RB_WPTR
pub const UVD_JRBC_RB_WPTR__RB_WPTR__SHIFT: c_uint = 0x4;
pub const UVD_JRBC_RB_WPTR__RB_WPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_RB_RPTR3
pub const UVD_RB_RPTR3__RB_RPTR__SHIFT: c_uint = 0x4;
pub const UVD_RB_RPTR3__RB_RPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_RB_WPTR3
pub const UVD_RB_WPTR3__RB_WPTR__SHIFT: c_uint = 0x4;
pub const UVD_RB_WPTR3__RB_WPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_RB_BASE_LO3
pub const UVD_RB_BASE_LO3__RB_BASE_LO__SHIFT: c_uint = 0x6;
pub const UVD_RB_BASE_LO3__RB_BASE_LO_MASK: c_uint = 0xFFFFFFC0L;
// UVD_RB_BASE_HI3
pub const UVD_RB_BASE_HI3__RB_BASE_HI__SHIFT: c_uint = 0x0;
pub const UVD_RB_BASE_HI3__RB_BASE_HI_MASK: c_uint = 0xFFFFFFFFL;
// UVD_RB_SIZE3
pub const UVD_RB_SIZE3__RB_SIZE__SHIFT: c_uint = 0x4;
pub const UVD_RB_SIZE3__RB_SIZE_MASK: c_uint = 0x007FFFF0L;
// JPEG_CGC_GATE
pub const JPEG_CGC_GATE__JPEG__SHIFT: c_uint = 0x14;
pub const JPEG_CGC_GATE__JPEG2__SHIFT: c_uint = 0x15;
pub const JPEG_CGC_GATE__JPEG_MASK: c_uint = 0x00100000L;
pub const JPEG_CGC_GATE__JPEG2_MASK: c_uint = 0x00200000L;
// UVD_CTX_INDEX
pub const UVD_CTX_INDEX__INDEX__SHIFT: c_uint = 0x0;
pub const UVD_CTX_INDEX__INDEX_MASK: c_uint = 0x000001FFL;
// UVD_CTX_DATA
pub const UVD_CTX_DATA__DATA__SHIFT: c_uint = 0x0;
pub const UVD_CTX_DATA__DATA_MASK: c_uint = 0xFFFFFFFFL;
// UVD_CGC_GATE
pub const UVD_CGC_GATE__SYS__SHIFT: c_uint = 0x0;
pub const UVD_CGC_GATE__UDEC__SHIFT: c_uint = 0x1;
pub const UVD_CGC_GATE__MPEG2__SHIFT: c_uint = 0x2;
pub const UVD_CGC_GATE__REGS__SHIFT: c_uint = 0x3;
pub const UVD_CGC_GATE__RBC__SHIFT: c_uint = 0x4;
pub const UVD_CGC_GATE__LMI_MC__SHIFT: c_uint = 0x5;
pub const UVD_CGC_GATE__LMI_UMC__SHIFT: c_uint = 0x6;
pub const UVD_CGC_GATE__IDCT__SHIFT: c_uint = 0x7;
pub const UVD_CGC_GATE__MPRD__SHIFT: c_uint = 0x8;
pub const UVD_CGC_GATE__MPC__SHIFT: c_uint = 0x9;
pub const UVD_CGC_GATE__LBSI__SHIFT: c_uint = 0xa;
pub const UVD_CGC_GATE__LRBBM__SHIFT: c_uint = 0xb;
pub const UVD_CGC_GATE__UDEC_RE__SHIFT: c_uint = 0xc;
pub const UVD_CGC_GATE__UDEC_CM__SHIFT: c_uint = 0xd;
pub const UVD_CGC_GATE__UDEC_IT__SHIFT: c_uint = 0xe;
pub const UVD_CGC_GATE__UDEC_DB__SHIFT: c_uint = 0xf;
pub const UVD_CGC_GATE__UDEC_MP__SHIFT: c_uint = 0x10;
pub const UVD_CGC_GATE__WCB__SHIFT: c_uint = 0x11;
pub const UVD_CGC_GATE__VCPU__SHIFT: c_uint = 0x12;
pub const UVD_CGC_GATE__SCPU__SHIFT: c_uint = 0x13;
pub const UVD_CGC_GATE__SYS_MASK: c_uint = 0x00000001L;
pub const UVD_CGC_GATE__UDEC_MASK: c_uint = 0x00000002L;
pub const UVD_CGC_GATE__MPEG2_MASK: c_uint = 0x00000004L;
pub const UVD_CGC_GATE__REGS_MASK: c_uint = 0x00000008L;
pub const UVD_CGC_GATE__RBC_MASK: c_uint = 0x00000010L;
pub const UVD_CGC_GATE__LMI_MC_MASK: c_uint = 0x00000020L;
pub const UVD_CGC_GATE__LMI_UMC_MASK: c_uint = 0x00000040L;
pub const UVD_CGC_GATE__IDCT_MASK: c_uint = 0x00000080L;
pub const UVD_CGC_GATE__MPRD_MASK: c_uint = 0x00000100L;
pub const UVD_CGC_GATE__MPC_MASK: c_uint = 0x00000200L;
pub const UVD_CGC_GATE__LBSI_MASK: c_uint = 0x00000400L;
pub const UVD_CGC_GATE__LRBBM_MASK: c_uint = 0x00000800L;
pub const UVD_CGC_GATE__UDEC_RE_MASK: c_uint = 0x00001000L;
pub const UVD_CGC_GATE__UDEC_CM_MASK: c_uint = 0x00002000L;
pub const UVD_CGC_GATE__UDEC_IT_MASK: c_uint = 0x00004000L;
pub const UVD_CGC_GATE__UDEC_DB_MASK: c_uint = 0x00008000L;
pub const UVD_CGC_GATE__UDEC_MP_MASK: c_uint = 0x00010000L;
pub const UVD_CGC_GATE__WCB_MASK: c_uint = 0x00020000L;
pub const UVD_CGC_GATE__VCPU_MASK: c_uint = 0x00040000L;
pub const UVD_CGC_GATE__SCPU_MASK: c_uint = 0x00080000L;
// UVD_CGC_CTRL
pub const UVD_CGC_CTRL__DYN_CLOCK_MODE__SHIFT: c_uint = 0x0;
pub const UVD_CGC_CTRL__CLK_GATE_DLY_TIMER__SHIFT: c_uint = 0x2;
pub const UVD_CGC_CTRL__CLK_OFF_DELAY__SHIFT: c_uint = 0x6;
pub const UVD_CGC_CTRL__UDEC_RE_MODE__SHIFT: c_uint = 0xb;
pub const UVD_CGC_CTRL__UDEC_CM_MODE__SHIFT: c_uint = 0xc;
pub const UVD_CGC_CTRL__UDEC_IT_MODE__SHIFT: c_uint = 0xd;
pub const UVD_CGC_CTRL__UDEC_DB_MODE__SHIFT: c_uint = 0xe;
pub const UVD_CGC_CTRL__UDEC_MP_MODE__SHIFT: c_uint = 0xf;
pub const UVD_CGC_CTRL__SYS_MODE__SHIFT: c_uint = 0x10;
pub const UVD_CGC_CTRL__UDEC_MODE__SHIFT: c_uint = 0x11;
pub const UVD_CGC_CTRL__MPEG2_MODE__SHIFT: c_uint = 0x12;
pub const UVD_CGC_CTRL__REGS_MODE__SHIFT: c_uint = 0x13;
pub const UVD_CGC_CTRL__RBC_MODE__SHIFT: c_uint = 0x14;
pub const UVD_CGC_CTRL__LMI_MC_MODE__SHIFT: c_uint = 0x15;
pub const UVD_CGC_CTRL__LMI_UMC_MODE__SHIFT: c_uint = 0x16;
pub const UVD_CGC_CTRL__IDCT_MODE__SHIFT: c_uint = 0x17;
pub const UVD_CGC_CTRL__MPRD_MODE__SHIFT: c_uint = 0x18;
pub const UVD_CGC_CTRL__MPC_MODE__SHIFT: c_uint = 0x19;
pub const UVD_CGC_CTRL__LBSI_MODE__SHIFT: c_uint = 0x1a;
pub const UVD_CGC_CTRL__LRBBM_MODE__SHIFT: c_uint = 0x1b;
pub const UVD_CGC_CTRL__WCB_MODE__SHIFT: c_uint = 0x1c;
pub const UVD_CGC_CTRL__VCPU_MODE__SHIFT: c_uint = 0x1d;
pub const UVD_CGC_CTRL__SCPU_MODE__SHIFT: c_uint = 0x1e;
pub const UVD_CGC_CTRL__DYN_CLOCK_MODE_MASK: c_uint = 0x00000001L;
pub const UVD_CGC_CTRL__CLK_GATE_DLY_TIMER_MASK: c_uint = 0x0000003CL;
pub const UVD_CGC_CTRL__CLK_OFF_DELAY_MASK: c_uint = 0x000007C0L;
pub const UVD_CGC_CTRL__UDEC_RE_MODE_MASK: c_uint = 0x00000800L;
pub const UVD_CGC_CTRL__UDEC_CM_MODE_MASK: c_uint = 0x00001000L;
pub const UVD_CGC_CTRL__UDEC_IT_MODE_MASK: c_uint = 0x00002000L;
pub const UVD_CGC_CTRL__UDEC_DB_MODE_MASK: c_uint = 0x00004000L;
pub const UVD_CGC_CTRL__UDEC_MP_MODE_MASK: c_uint = 0x00008000L;
pub const UVD_CGC_CTRL__SYS_MODE_MASK: c_uint = 0x00010000L;
pub const UVD_CGC_CTRL__UDEC_MODE_MASK: c_uint = 0x00020000L;
pub const UVD_CGC_CTRL__MPEG2_MODE_MASK: c_uint = 0x00040000L;
pub const UVD_CGC_CTRL__REGS_MODE_MASK: c_uint = 0x00080000L;
pub const UVD_CGC_CTRL__RBC_MODE_MASK: c_uint = 0x00100000L;
pub const UVD_CGC_CTRL__LMI_MC_MODE_MASK: c_uint = 0x00200000L;
pub const UVD_CGC_CTRL__LMI_UMC_MODE_MASK: c_uint = 0x00400000L;
pub const UVD_CGC_CTRL__IDCT_MODE_MASK: c_uint = 0x00800000L;
pub const UVD_CGC_CTRL__MPRD_MODE_MASK: c_uint = 0x01000000L;
pub const UVD_CGC_CTRL__MPC_MODE_MASK: c_uint = 0x02000000L;
pub const UVD_CGC_CTRL__LBSI_MODE_MASK: c_uint = 0x04000000L;
pub const UVD_CGC_CTRL__LRBBM_MODE_MASK: c_uint = 0x08000000L;
pub const UVD_CGC_CTRL__WCB_MODE_MASK: c_uint = 0x10000000L;
pub const UVD_CGC_CTRL__VCPU_MODE_MASK: c_uint = 0x20000000L;
pub const UVD_CGC_CTRL__SCPU_MODE_MASK: c_uint = 0x40000000L;
// UVD_GP_SCRATCH4
pub const UVD_GP_SCRATCH4__DATA__SHIFT: c_uint = 0x0;
pub const UVD_GP_SCRATCH4__DATA_MASK: c_uint = 0xFFFFFFFFL;
// UVD_LMI_CTRL2
pub const UVD_LMI_CTRL2__SPH_DIS__SHIFT: c_uint = 0x0;
pub const UVD_LMI_CTRL2__STALL_ARB__SHIFT: c_uint = 0x1;
pub const UVD_LMI_CTRL2__ASSERT_UMC_URGENT__SHIFT: c_uint = 0x2;
pub const UVD_LMI_CTRL2__MASK_UMC_URGENT__SHIFT: c_uint = 0x3;
pub const UVD_LMI_CTRL2__DRCITF_BUBBLE_FIX_DIS__SHIFT: c_uint = 0x7;
pub const UVD_LMI_CTRL2__STALL_ARB_UMC__SHIFT: c_uint = 0x8;
pub const UVD_LMI_CTRL2__MC_READ_ID_SEL__SHIFT: c_uint = 0x9;
pub const UVD_LMI_CTRL2__MC_WRITE_ID_SEL__SHIFT: c_uint = 0xb;
pub const UVD_LMI_CTRL2__SPH_DIS_MASK: c_uint = 0x00000001L;
pub const UVD_LMI_CTRL2__STALL_ARB_MASK: c_uint = 0x00000002L;
pub const UVD_LMI_CTRL2__ASSERT_UMC_URGENT_MASK: c_uint = 0x00000004L;
pub const UVD_LMI_CTRL2__MASK_UMC_URGENT_MASK: c_uint = 0x00000008L;
pub const UVD_LMI_CTRL2__DRCITF_BUBBLE_FIX_DIS_MASK: c_uint = 0x00000080L;
pub const UVD_LMI_CTRL2__STALL_ARB_UMC_MASK: c_uint = 0x00000100L;
pub const UVD_LMI_CTRL2__MC_READ_ID_SEL_MASK: c_uint = 0x00000600L;
pub const UVD_LMI_CTRL2__MC_WRITE_ID_SEL_MASK: c_uint = 0x00001800L;
// UVD_MASTINT_EN
pub const UVD_MASTINT_EN__OVERRUN_RST__SHIFT: c_uint = 0x0;
pub const UVD_MASTINT_EN__VCPU_EN__SHIFT: c_uint = 0x1;
pub const UVD_MASTINT_EN__SYS_EN__SHIFT: c_uint = 0x2;
pub const UVD_MASTINT_EN__INT_OVERRUN__SHIFT: c_uint = 0x4;
pub const UVD_MASTINT_EN__OVERRUN_RST_MASK: c_uint = 0x00000001L;
pub const UVD_MASTINT_EN__VCPU_EN_MASK: c_uint = 0x00000002L;
pub const UVD_MASTINT_EN__SYS_EN_MASK: c_uint = 0x00000004L;
pub const UVD_MASTINT_EN__INT_OVERRUN_MASK: c_uint = 0x007FFFF0L;
// JPEG_CGC_CTRL
pub const JPEG_CGC_CTRL__DYN_CLOCK_MODE__SHIFT: c_uint = 0x0;
pub const JPEG_CGC_CTRL__JPEG2_MODE__SHIFT: c_uint = 0x1;
pub const JPEG_CGC_CTRL__CLK_GATE_DLY_TIMER__SHIFT: c_uint = 0x2;
pub const JPEG_CGC_CTRL__CLK_OFF_DELAY__SHIFT: c_uint = 0x6;
pub const JPEG_CGC_CTRL__JPEG_MODE__SHIFT: c_uint = 0x1f;
pub const JPEG_CGC_CTRL__DYN_CLOCK_MODE_MASK: c_uint = 0x00000001L;
pub const JPEG_CGC_CTRL__JPEG2_MODE_MASK: c_uint = 0x00000002L;
pub const JPEG_CGC_CTRL__CLK_GATE_DLY_TIMER_MASK: c_uint = 0x0000003CL;
pub const JPEG_CGC_CTRL__CLK_OFF_DELAY_MASK: c_uint = 0x000007C0L;
pub const JPEG_CGC_CTRL__JPEG_MODE_MASK: c_uint = 0x80000000L;
// UVD_LMI_CTRL
pub const UVD_LMI_CTRL__WRITE_CLEAN_TIMER__SHIFT: c_uint = 0x0;
pub const UVD_LMI_CTRL__WRITE_CLEAN_TIMER_EN__SHIFT: c_uint = 0x8;
pub const UVD_LMI_CTRL__REQ_MODE__SHIFT: c_uint = 0x9;
pub const UVD_LMI_CTRL__ASSERT_MC_URGENT__SHIFT: c_uint = 0xb;
pub const UVD_LMI_CTRL__MASK_MC_URGENT__SHIFT: c_uint = 0xc;
pub const UVD_LMI_CTRL__DATA_COHERENCY_EN__SHIFT: c_uint = 0xd;
pub const UVD_LMI_CTRL__CRC_RESET__SHIFT: c_uint = 0xe;
pub const UVD_LMI_CTRL__CRC_SEL__SHIFT: c_uint = 0xf;
pub const UVD_LMI_CTRL__VCPU_DATA_COHERENCY_EN__SHIFT: c_uint = 0x15;
pub const UVD_LMI_CTRL__CM_DATA_COHERENCY_EN__SHIFT: c_uint = 0x16;
pub const UVD_LMI_CTRL__DB_DB_DATA_COHERENCY_EN__SHIFT: c_uint = 0x17;
pub const UVD_LMI_CTRL__DB_IT_DATA_COHERENCY_EN__SHIFT: c_uint = 0x18;
pub const UVD_LMI_CTRL__IT_IT_DATA_COHERENCY_EN__SHIFT: c_uint = 0x19;
pub const UVD_LMI_CTRL__RFU__SHIFT: c_uint = 0x1b;
pub const UVD_LMI_CTRL__WRITE_CLEAN_TIMER_MASK: c_uint = 0x000000FFL;
pub const UVD_LMI_CTRL__WRITE_CLEAN_TIMER_EN_MASK: c_uint = 0x00000100L;
pub const UVD_LMI_CTRL__REQ_MODE_MASK: c_uint = 0x00000200L;
pub const UVD_LMI_CTRL__ASSERT_MC_URGENT_MASK: c_uint = 0x00000800L;
pub const UVD_LMI_CTRL__MASK_MC_URGENT_MASK: c_uint = 0x00001000L;
pub const UVD_LMI_CTRL__DATA_COHERENCY_EN_MASK: c_uint = 0x00002000L;
pub const UVD_LMI_CTRL__CRC_RESET_MASK: c_uint = 0x00004000L;
pub const UVD_LMI_CTRL__CRC_SEL_MASK: c_uint = 0x000F8000L;
pub const UVD_LMI_CTRL__VCPU_DATA_COHERENCY_EN_MASK: c_uint = 0x00200000L;
pub const UVD_LMI_CTRL__CM_DATA_COHERENCY_EN_MASK: c_uint = 0x00400000L;
pub const UVD_LMI_CTRL__DB_DB_DATA_COHERENCY_EN_MASK: c_uint = 0x00800000L;
pub const UVD_LMI_CTRL__DB_IT_DATA_COHERENCY_EN_MASK: c_uint = 0x01000000L;
pub const UVD_LMI_CTRL__IT_IT_DATA_COHERENCY_EN_MASK: c_uint = 0x02000000L;
pub const UVD_LMI_CTRL__RFU_MASK: c_uint = 0xF8000000L;
// UVD_LMI_SWAP_CNTL
pub const UVD_LMI_SWAP_CNTL__RB_MC_SWAP__SHIFT: c_uint = 0x0;
pub const UVD_LMI_SWAP_CNTL__IB_MC_SWAP__SHIFT: c_uint = 0x2;
pub const UVD_LMI_SWAP_CNTL__RB_RPTR_MC_SWAP__SHIFT: c_uint = 0x4;
pub const UVD_LMI_SWAP_CNTL__VCPU_R_MC_SWAP__SHIFT: c_uint = 0x6;
pub const UVD_LMI_SWAP_CNTL__VCPU_W_MC_SWAP__SHIFT: c_uint = 0x8;
pub const UVD_LMI_SWAP_CNTL__CM_MC_SWAP__SHIFT: c_uint = 0xa;
pub const UVD_LMI_SWAP_CNTL__IT_MC_SWAP__SHIFT: c_uint = 0xc;
pub const UVD_LMI_SWAP_CNTL__DB_R_MC_SWAP__SHIFT: c_uint = 0xe;
pub const UVD_LMI_SWAP_CNTL__DB_W_MC_SWAP__SHIFT: c_uint = 0x10;
pub const UVD_LMI_SWAP_CNTL__CSM_MC_SWAP__SHIFT: c_uint = 0x12;
pub const UVD_LMI_SWAP_CNTL__MP_REF16_MC_SWAP__SHIFT: c_uint = 0x16;
pub const UVD_LMI_SWAP_CNTL__DBW_MC_SWAP__SHIFT: c_uint = 0x18;
pub const UVD_LMI_SWAP_CNTL__RB_WR_MC_SWAP__SHIFT: c_uint = 0x1a;
pub const UVD_LMI_SWAP_CNTL__RE_MC_SWAP__SHIFT: c_uint = 0x1c;
pub const UVD_LMI_SWAP_CNTL__MP_MC_SWAP__SHIFT: c_uint = 0x1e;
pub const UVD_LMI_SWAP_CNTL__RB_MC_SWAP_MASK: c_uint = 0x00000003L;
pub const UVD_LMI_SWAP_CNTL__IB_MC_SWAP_MASK: c_uint = 0x0000000CL;
pub const UVD_LMI_SWAP_CNTL__RB_RPTR_MC_SWAP_MASK: c_uint = 0x00000030L;
pub const UVD_LMI_SWAP_CNTL__VCPU_R_MC_SWAP_MASK: c_uint = 0x000000C0L;
pub const UVD_LMI_SWAP_CNTL__VCPU_W_MC_SWAP_MASK: c_uint = 0x00000300L;
pub const UVD_LMI_SWAP_CNTL__CM_MC_SWAP_MASK: c_uint = 0x00000C00L;
pub const UVD_LMI_SWAP_CNTL__IT_MC_SWAP_MASK: c_uint = 0x00003000L;
pub const UVD_LMI_SWAP_CNTL__DB_R_MC_SWAP_MASK: c_uint = 0x0000C000L;
pub const UVD_LMI_SWAP_CNTL__DB_W_MC_SWAP_MASK: c_uint = 0x00030000L;
pub const UVD_LMI_SWAP_CNTL__CSM_MC_SWAP_MASK: c_uint = 0x000C0000L;
pub const UVD_LMI_SWAP_CNTL__MP_REF16_MC_SWAP_MASK: c_uint = 0x00C00000L;
pub const UVD_LMI_SWAP_CNTL__DBW_MC_SWAP_MASK: c_uint = 0x03000000L;
pub const UVD_LMI_SWAP_CNTL__RB_WR_MC_SWAP_MASK: c_uint = 0x0C000000L;
pub const UVD_LMI_SWAP_CNTL__RE_MC_SWAP_MASK: c_uint = 0x30000000L;
pub const UVD_LMI_SWAP_CNTL__MP_MC_SWAP_MASK: c_uint = 0xC0000000L;
// UVD_MP_SWAP_CNTL
pub const UVD_MP_SWAP_CNTL__MP_REF0_MC_SWAP__SHIFT: c_uint = 0x0;
pub const UVD_MP_SWAP_CNTL__MP_REF1_MC_SWAP__SHIFT: c_uint = 0x2;
pub const UVD_MP_SWAP_CNTL__MP_REF2_MC_SWAP__SHIFT: c_uint = 0x4;
pub const UVD_MP_SWAP_CNTL__MP_REF3_MC_SWAP__SHIFT: c_uint = 0x6;
pub const UVD_MP_SWAP_CNTL__MP_REF4_MC_SWAP__SHIFT: c_uint = 0x8;
pub const UVD_MP_SWAP_CNTL__MP_REF5_MC_SWAP__SHIFT: c_uint = 0xa;
pub const UVD_MP_SWAP_CNTL__MP_REF6_MC_SWAP__SHIFT: c_uint = 0xc;
pub const UVD_MP_SWAP_CNTL__MP_REF7_MC_SWAP__SHIFT: c_uint = 0xe;
pub const UVD_MP_SWAP_CNTL__MP_REF8_MC_SWAP__SHIFT: c_uint = 0x10;
pub const UVD_MP_SWAP_CNTL__MP_REF9_MC_SWAP__SHIFT: c_uint = 0x12;
pub const UVD_MP_SWAP_CNTL__MP_REF10_MC_SWAP__SHIFT: c_uint = 0x14;
pub const UVD_MP_SWAP_CNTL__MP_REF11_MC_SWAP__SHIFT: c_uint = 0x16;
pub const UVD_MP_SWAP_CNTL__MP_REF12_MC_SWAP__SHIFT: c_uint = 0x18;
pub const UVD_MP_SWAP_CNTL__MP_REF13_MC_SWAP__SHIFT: c_uint = 0x1a;
pub const UVD_MP_SWAP_CNTL__MP_REF14_MC_SWAP__SHIFT: c_uint = 0x1c;
pub const UVD_MP_SWAP_CNTL__MP_REF15_MC_SWAP__SHIFT: c_uint = 0x1e;
pub const UVD_MP_SWAP_CNTL__MP_REF0_MC_SWAP_MASK: c_uint = 0x00000003L;
pub const UVD_MP_SWAP_CNTL__MP_REF1_MC_SWAP_MASK: c_uint = 0x0000000CL;
pub const UVD_MP_SWAP_CNTL__MP_REF2_MC_SWAP_MASK: c_uint = 0x00000030L;
pub const UVD_MP_SWAP_CNTL__MP_REF3_MC_SWAP_MASK: c_uint = 0x000000C0L;
pub const UVD_MP_SWAP_CNTL__MP_REF4_MC_SWAP_MASK: c_uint = 0x00000300L;
pub const UVD_MP_SWAP_CNTL__MP_REF5_MC_SWAP_MASK: c_uint = 0x00000C00L;
pub const UVD_MP_SWAP_CNTL__MP_REF6_MC_SWAP_MASK: c_uint = 0x00003000L;
pub const UVD_MP_SWAP_CNTL__MP_REF7_MC_SWAP_MASK: c_uint = 0x0000C000L;
pub const UVD_MP_SWAP_CNTL__MP_REF8_MC_SWAP_MASK: c_uint = 0x00030000L;
pub const UVD_MP_SWAP_CNTL__MP_REF9_MC_SWAP_MASK: c_uint = 0x000C0000L;
pub const UVD_MP_SWAP_CNTL__MP_REF10_MC_SWAP_MASK: c_uint = 0x00300000L;
pub const UVD_MP_SWAP_CNTL__MP_REF11_MC_SWAP_MASK: c_uint = 0x00C00000L;
pub const UVD_MP_SWAP_CNTL__MP_REF12_MC_SWAP_MASK: c_uint = 0x03000000L;
pub const UVD_MP_SWAP_CNTL__MP_REF13_MC_SWAP_MASK: c_uint = 0x0C000000L;
pub const UVD_MP_SWAP_CNTL__MP_REF14_MC_SWAP_MASK: c_uint = 0x30000000L;
pub const UVD_MP_SWAP_CNTL__MP_REF15_MC_SWAP_MASK: c_uint = 0xC0000000L;
// UVD_MPC_SET_MUXA0
pub const UVD_MPC_SET_MUXA0__VARA_0__SHIFT: c_uint = 0x0;
pub const UVD_MPC_SET_MUXA0__VARA_1__SHIFT: c_uint = 0x6;
pub const UVD_MPC_SET_MUXA0__VARA_2__SHIFT: c_uint = 0xc;
pub const UVD_MPC_SET_MUXA0__VARA_3__SHIFT: c_uint = 0x12;
pub const UVD_MPC_SET_MUXA0__VARA_4__SHIFT: c_uint = 0x18;
pub const UVD_MPC_SET_MUXA0__VARA_0_MASK: c_uint = 0x0000003FL;
pub const UVD_MPC_SET_MUXA0__VARA_1_MASK: c_uint = 0x00000FC0L;
pub const UVD_MPC_SET_MUXA0__VARA_2_MASK: c_uint = 0x0003F000L;
pub const UVD_MPC_SET_MUXA0__VARA_3_MASK: c_uint = 0x00FC0000L;
pub const UVD_MPC_SET_MUXA0__VARA_4_MASK: c_uint = 0x3F000000L;
// UVD_MPC_SET_MUXA1
pub const UVD_MPC_SET_MUXA1__VARA_5__SHIFT: c_uint = 0x0;
pub const UVD_MPC_SET_MUXA1__VARA_6__SHIFT: c_uint = 0x6;
pub const UVD_MPC_SET_MUXA1__VARA_7__SHIFT: c_uint = 0xc;
pub const UVD_MPC_SET_MUXA1__VARA_5_MASK: c_uint = 0x0000003FL;
pub const UVD_MPC_SET_MUXA1__VARA_6_MASK: c_uint = 0x00000FC0L;
pub const UVD_MPC_SET_MUXA1__VARA_7_MASK: c_uint = 0x0003F000L;
// UVD_MPC_SET_MUXB0
pub const UVD_MPC_SET_MUXB0__VARB_0__SHIFT: c_uint = 0x0;
pub const UVD_MPC_SET_MUXB0__VARB_1__SHIFT: c_uint = 0x6;
pub const UVD_MPC_SET_MUXB0__VARB_2__SHIFT: c_uint = 0xc;
pub const UVD_MPC_SET_MUXB0__VARB_3__SHIFT: c_uint = 0x12;
pub const UVD_MPC_SET_MUXB0__VARB_4__SHIFT: c_uint = 0x18;
pub const UVD_MPC_SET_MUXB0__VARB_0_MASK: c_uint = 0x0000003FL;
pub const UVD_MPC_SET_MUXB0__VARB_1_MASK: c_uint = 0x00000FC0L;
pub const UVD_MPC_SET_MUXB0__VARB_2_MASK: c_uint = 0x0003F000L;
pub const UVD_MPC_SET_MUXB0__VARB_3_MASK: c_uint = 0x00FC0000L;
pub const UVD_MPC_SET_MUXB0__VARB_4_MASK: c_uint = 0x3F000000L;
// UVD_MPC_SET_MUXB1
pub const UVD_MPC_SET_MUXB1__VARB_5__SHIFT: c_uint = 0x0;
pub const UVD_MPC_SET_MUXB1__VARB_6__SHIFT: c_uint = 0x6;
pub const UVD_MPC_SET_MUXB1__VARB_7__SHIFT: c_uint = 0xc;
pub const UVD_MPC_SET_MUXB1__VARB_5_MASK: c_uint = 0x0000003FL;
pub const UVD_MPC_SET_MUXB1__VARB_6_MASK: c_uint = 0x00000FC0L;
pub const UVD_MPC_SET_MUXB1__VARB_7_MASK: c_uint = 0x0003F000L;
// UVD_MPC_SET_MUX
pub const UVD_MPC_SET_MUX__SET_0__SHIFT: c_uint = 0x0;
pub const UVD_MPC_SET_MUX__SET_1__SHIFT: c_uint = 0x3;
pub const UVD_MPC_SET_MUX__SET_2__SHIFT: c_uint = 0x6;
pub const UVD_MPC_SET_MUX__SET_0_MASK: c_uint = 0x00000007L;
pub const UVD_MPC_SET_MUX__SET_1_MASK: c_uint = 0x00000038L;
pub const UVD_MPC_SET_MUX__SET_2_MASK: c_uint = 0x000001C0L;
// UVD_MPC_SET_ALU
pub const UVD_MPC_SET_ALU__FUNCT__SHIFT: c_uint = 0x0;
pub const UVD_MPC_SET_ALU__OPERAND__SHIFT: c_uint = 0x4;
pub const UVD_MPC_SET_ALU__FUNCT_MASK: c_uint = 0x00000007L;
pub const UVD_MPC_SET_ALU__OPERAND_MASK: c_uint = 0x00000FF0L;
// UVD_VCPU_CACHE_OFFSET0
pub const UVD_VCPU_CACHE_OFFSET0__CACHE_OFFSET0__SHIFT: c_uint = 0x0;
pub const UVD_VCPU_CACHE_OFFSET0__CACHE_OFFSET0_MASK: c_uint = 0x01FFFFFFL;
// UVD_VCPU_CACHE_SIZE0
pub const UVD_VCPU_CACHE_SIZE0__CACHE_SIZE0__SHIFT: c_uint = 0x0;
pub const UVD_VCPU_CACHE_SIZE0__CACHE_SIZE0_MASK: c_uint = 0x001FFFFFL;
// UVD_VCPU_CACHE_OFFSET1
pub const UVD_VCPU_CACHE_OFFSET1__CACHE_OFFSET1__SHIFT: c_uint = 0x0;
pub const UVD_VCPU_CACHE_OFFSET1__CACHE_OFFSET1_MASK: c_uint = 0x01FFFFFFL;
// UVD_VCPU_CACHE_SIZE1
pub const UVD_VCPU_CACHE_SIZE1__CACHE_SIZE1__SHIFT: c_uint = 0x0;
pub const UVD_VCPU_CACHE_SIZE1__CACHE_SIZE1_MASK: c_uint = 0x001FFFFFL;
// UVD_VCPU_CACHE_OFFSET2
pub const UVD_VCPU_CACHE_OFFSET2__CACHE_OFFSET2__SHIFT: c_uint = 0x0;
pub const UVD_VCPU_CACHE_OFFSET2__CACHE_OFFSET2_MASK: c_uint = 0x01FFFFFFL;
// UVD_VCPU_CACHE_SIZE2
pub const UVD_VCPU_CACHE_SIZE2__CACHE_SIZE2__SHIFT: c_uint = 0x0;
pub const UVD_VCPU_CACHE_SIZE2__CACHE_SIZE2_MASK: c_uint = 0x001FFFFFL;
// UVD_VCPU_CNTL
pub const UVD_VCPU_CNTL__CLK_EN__SHIFT: c_uint = 0x9;
pub const UVD_VCPU_CNTL__CLK_EN_MASK: c_uint = 0x00000200L;
// UVD_SOFT_RESET
pub const UVD_SOFT_RESET__RBC_SOFT_RESET__SHIFT: c_uint = 0x0;
pub const UVD_SOFT_RESET__LBSI_SOFT_RESET__SHIFT: c_uint = 0x1;
pub const UVD_SOFT_RESET__LMI_SOFT_RESET__SHIFT: c_uint = 0x2;
pub const UVD_SOFT_RESET__VCPU_SOFT_RESET__SHIFT: c_uint = 0x3;
pub const UVD_SOFT_RESET__UDEC_SOFT_RESET__SHIFT: c_uint = 0x4;
pub const UVD_SOFT_RESET__CSM_SOFT_RESET__SHIFT: c_uint = 0x5;
pub const UVD_SOFT_RESET__CXW_SOFT_RESET__SHIFT: c_uint = 0x6;
pub const UVD_SOFT_RESET__TAP_SOFT_RESET__SHIFT: c_uint = 0x7;
pub const UVD_SOFT_RESET__MPC_SOFT_RESET__SHIFT: c_uint = 0x8;
pub const UVD_SOFT_RESET__IH_SOFT_RESET__SHIFT: c_uint = 0xa;
pub const UVD_SOFT_RESET__LMI_UMC_SOFT_RESET__SHIFT: c_uint = 0xd;
pub const UVD_SOFT_RESET__SPH_SOFT_RESET__SHIFT: c_uint = 0xe;
pub const UVD_SOFT_RESET__MIF_SOFT_RESET__SHIFT: c_uint = 0xf;
pub const UVD_SOFT_RESET__LCM_SOFT_RESET__SHIFT: c_uint = 0x10;
pub const UVD_SOFT_RESET__SUVD_SOFT_RESET__SHIFT: c_uint = 0x11;
pub const UVD_SOFT_RESET__LBSI_VCLK_RESET_STATUS__SHIFT: c_uint = 0x12;
pub const UVD_SOFT_RESET__VCPU_VCLK_RESET_STATUS__SHIFT: c_uint = 0x13;
pub const UVD_SOFT_RESET__UDEC_VCLK_RESET_STATUS__SHIFT: c_uint = 0x14;
pub const UVD_SOFT_RESET__UDEC_DCLK_RESET_STATUS__SHIFT: c_uint = 0x15;
pub const UVD_SOFT_RESET__MPC_DCLK_RESET_STATUS__SHIFT: c_uint = 0x16;
pub const UVD_SOFT_RESET__MIF_DCLK_RESET_STATUS__SHIFT: c_uint = 0x1a;
pub const UVD_SOFT_RESET__LCM_DCLK_RESET_STATUS__SHIFT: c_uint = 0x1b;
pub const UVD_SOFT_RESET__SUVD_VCLK_RESET_STATUS__SHIFT: c_uint = 0x1c;
pub const UVD_SOFT_RESET__SUVD_DCLK_RESET_STATUS__SHIFT: c_uint = 0x1d;
pub const UVD_SOFT_RESET__RE_DCLK_RESET_STATUS__SHIFT: c_uint = 0x1e;
pub const UVD_SOFT_RESET__SRE_DCLK_RESET_STATUS__SHIFT: c_uint = 0x1f;
pub const UVD_SOFT_RESET__RBC_SOFT_RESET_MASK: c_uint = 0x00000001L;
pub const UVD_SOFT_RESET__LBSI_SOFT_RESET_MASK: c_uint = 0x00000002L;
pub const UVD_SOFT_RESET__LMI_SOFT_RESET_MASK: c_uint = 0x00000004L;
pub const UVD_SOFT_RESET__VCPU_SOFT_RESET_MASK: c_uint = 0x00000008L;
pub const UVD_SOFT_RESET__UDEC_SOFT_RESET_MASK: c_uint = 0x00000010L;
pub const UVD_SOFT_RESET__CSM_SOFT_RESET_MASK: c_uint = 0x00000020L;
pub const UVD_SOFT_RESET__CXW_SOFT_RESET_MASK: c_uint = 0x00000040L;
pub const UVD_SOFT_RESET__TAP_SOFT_RESET_MASK: c_uint = 0x00000080L;
pub const UVD_SOFT_RESET__MPC_SOFT_RESET_MASK: c_uint = 0x00000100L;
pub const UVD_SOFT_RESET__IH_SOFT_RESET_MASK: c_uint = 0x00000400L;
pub const UVD_SOFT_RESET__LMI_UMC_SOFT_RESET_MASK: c_uint = 0x00002000L;
pub const UVD_SOFT_RESET__SPH_SOFT_RESET_MASK: c_uint = 0x00004000L;
pub const UVD_SOFT_RESET__MIF_SOFT_RESET_MASK: c_uint = 0x00008000L;
pub const UVD_SOFT_RESET__LCM_SOFT_RESET_MASK: c_uint = 0x00010000L;
pub const UVD_SOFT_RESET__SUVD_SOFT_RESET_MASK: c_uint = 0x00020000L;
pub const UVD_SOFT_RESET__LBSI_VCLK_RESET_STATUS_MASK: c_uint = 0x00040000L;
pub const UVD_SOFT_RESET__VCPU_VCLK_RESET_STATUS_MASK: c_uint = 0x00080000L;
pub const UVD_SOFT_RESET__UDEC_VCLK_RESET_STATUS_MASK: c_uint = 0x00100000L;
pub const UVD_SOFT_RESET__UDEC_DCLK_RESET_STATUS_MASK: c_uint = 0x00200000L;
pub const UVD_SOFT_RESET__MPC_DCLK_RESET_STATUS_MASK: c_uint = 0x00400000L;
pub const UVD_SOFT_RESET__MIF_DCLK_RESET_STATUS_MASK: c_uint = 0x04000000L;
pub const UVD_SOFT_RESET__LCM_DCLK_RESET_STATUS_MASK: c_uint = 0x08000000L;
pub const UVD_SOFT_RESET__SUVD_VCLK_RESET_STATUS_MASK: c_uint = 0x10000000L;
pub const UVD_SOFT_RESET__SUVD_DCLK_RESET_STATUS_MASK: c_uint = 0x20000000L;
pub const UVD_SOFT_RESET__RE_DCLK_RESET_STATUS_MASK: c_uint = 0x40000000L;
pub const UVD_SOFT_RESET__SRE_DCLK_RESET_STATUS_MASK: c_uint = 0x80000000L;
// UVD_LMI_RBC_IB_VMID
pub const UVD_LMI_RBC_IB_VMID__IB_VMID__SHIFT: c_uint = 0x0;
pub const UVD_LMI_RBC_IB_VMID__IB_VMID_MASK: c_uint = 0x0000000FL;
// UVD_RBC_IB_SIZE
pub const UVD_RBC_IB_SIZE__IB_SIZE__SHIFT: c_uint = 0x4;
pub const UVD_RBC_IB_SIZE__IB_SIZE_MASK: c_uint = 0x007FFFF0L;
// UVD_RBC_RB_RPTR
pub const UVD_RBC_RB_RPTR__RB_RPTR__SHIFT: c_uint = 0x4;
pub const UVD_RBC_RB_RPTR__RB_RPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_RBC_RB_WPTR
pub const UVD_RBC_RB_WPTR__RB_WPTR__SHIFT: c_uint = 0x4;
pub const UVD_RBC_RB_WPTR__RB_WPTR_MASK: c_uint = 0x007FFFF0L;
// UVD_RBC_RB_WPTR_CNTL
pub const UVD_RBC_RB_WPTR_CNTL__RB_PRE_WRITE_TIMER__SHIFT: c_uint = 0x0;
pub const UVD_RBC_RB_WPTR_CNTL__RB_PRE_WRITE_TIMER_MASK: c_uint = 0x00007FFFL;
// UVD_RBC_RB_CNTL
pub const UVD_RBC_RB_CNTL__RB_BUFSZ__SHIFT: c_uint = 0x0;
pub const UVD_RBC_RB_CNTL__RB_BLKSZ__SHIFT: c_uint = 0x8;
pub const UVD_RBC_RB_CNTL__RB_NO_FETCH__SHIFT: c_uint = 0x10;
pub const UVD_RBC_RB_CNTL__RB_WPTR_POLL_EN__SHIFT: c_uint = 0x14;
pub const UVD_RBC_RB_CNTL__RB_NO_UPDATE__SHIFT: c_uint = 0x18;
pub const UVD_RBC_RB_CNTL__RB_RPTR_WR_EN__SHIFT: c_uint = 0x1c;
pub const UVD_RBC_RB_CNTL__RB_BUFSZ_MASK: c_uint = 0x0000001FL;
pub const UVD_RBC_RB_CNTL__RB_BLKSZ_MASK: c_uint = 0x00001F00L;
pub const UVD_RBC_RB_CNTL__RB_NO_FETCH_MASK: c_uint = 0x00010000L;
pub const UVD_RBC_RB_CNTL__RB_WPTR_POLL_EN_MASK: c_uint = 0x00100000L;
pub const UVD_RBC_RB_CNTL__RB_NO_UPDATE_MASK: c_uint = 0x01000000L;
pub const UVD_RBC_RB_CNTL__RB_RPTR_WR_EN_MASK: c_uint = 0x10000000L;
// UVD_RBC_RB_RPTR_ADDR
pub const UVD_RBC_RB_RPTR_ADDR__RB_RPTR_ADDR__SHIFT: c_uint = 0x0;
pub const UVD_RBC_RB_RPTR_ADDR__RB_RPTR_ADDR_MASK: c_uint = 0xFFFFFFFFL;
// UVD_STATUS
pub const UVD_STATUS__RBC_BUSY__SHIFT: c_uint = 0x0;
pub const UVD_STATUS__VCPU_REPORT__SHIFT: c_uint = 0x1;
pub const UVD_STATUS__AVP_BUSY__SHIFT: c_uint = 0x8;
pub const UVD_STATUS__IDCT_BUSY__SHIFT: c_uint = 0x9;
pub const UVD_STATUS__IDCT_CTL_ACK__SHIFT: c_uint = 0xb;
pub const UVD_STATUS__UVD_CTL_ACK__SHIFT: c_uint = 0xc;
pub const UVD_STATUS__AVP_BLOCK_ACK__SHIFT: c_uint = 0xd;
pub const UVD_STATUS__IDCT_BLOCK_ACK__SHIFT: c_uint = 0xe;
pub const UVD_STATUS__UVD_BLOCK_ACK__SHIFT: c_uint = 0xf;
pub const UVD_STATUS__RBC_ACCESS_GPCOM__SHIFT: c_uint = 0x10;
pub const UVD_STATUS__SYS_GPCOM_REQ__SHIFT: c_uint = 0x1f;
pub const UVD_STATUS__RBC_BUSY_MASK: c_uint = 0x00000001L;
pub const UVD_STATUS__VCPU_REPORT_MASK: c_uint = 0x000000FEL;
pub const UVD_STATUS__AVP_BUSY_MASK: c_uint = 0x00000100L;
pub const UVD_STATUS__IDCT_BUSY_MASK: c_uint = 0x00000200L;
pub const UVD_STATUS__IDCT_CTL_ACK_MASK: c_uint = 0x00000800L;
pub const UVD_STATUS__UVD_CTL_ACK_MASK: c_uint = 0x00001000L;
pub const UVD_STATUS__AVP_BLOCK_ACK_MASK: c_uint = 0x00002000L;
pub const UVD_STATUS__IDCT_BLOCK_ACK_MASK: c_uint = 0x00004000L;
pub const UVD_STATUS__UVD_BLOCK_ACK_MASK: c_uint = 0x00008000L;
pub const UVD_STATUS__RBC_ACCESS_GPCOM_MASK: c_uint = 0x00010000L;
pub const UVD_STATUS__SYS_GPCOM_REQ_MASK: c_uint = 0x80000000L;
// UVD_SEMA_TIMEOUT_STATUS
pub const UVD_SEMA_TIMEOUT_STATUS__SEMAPHORE_WAIT_INCOMPLETE_TIMEOUT_STAT__SHIFT: c_uint = 0x0;
pub const UVD_SEMA_TIMEOUT_STATUS__SEMAPHORE_WAIT_FAULT_TIMEOUT_STAT__SHIFT: c_uint = 0x1;
pub const UVD_SEMA_TIMEOUT_STATUS__SEMAPHORE_SIGNAL_INCOMPLETE_TIMEOUT_STAT__SHIFT: c_uint = 0x2;
pub const UVD_SEMA_TIMEOUT_STATUS__SEMAPHORE_TIMEOUT_CLEAR__SHIFT: c_uint = 0x3;
pub const UVD_SEMA_TIMEOUT_STATUS__SEMAPHORE_WAIT_INCOMPLETE_TIMEOUT_STAT_MASK: c_uint = 0x00000001L;
pub const UVD_SEMA_TIMEOUT_STATUS__SEMAPHORE_WAIT_FAULT_TIMEOUT_STAT_MASK: c_uint = 0x00000002L;
pub const UVD_SEMA_TIMEOUT_STATUS__SEMAPHORE_SIGNAL_INCOMPLETE_TIMEOUT_STAT_MASK: c_uint = 0x00000004L;
pub const UVD_SEMA_TIMEOUT_STATUS__SEMAPHORE_TIMEOUT_CLEAR_MASK: c_uint = 0x00000008L;
// UVD_SEMA_WAIT_INCOMPLETE_TIMEOUT_CNTL
pub const UVD_SEMA_WAIT_INCOMPLETE_TIMEOUT_CNTL__WAIT_INCOMPLETE_EN__SHIFT: c_uint = 0x0;
pub const UVD_SEMA_WAIT_INCOMPLETE_TIMEOUT_CNTL__WAIT_INCOMPLETE_COUNT__SHIFT: c_uint = 0x1;
pub const UVD_SEMA_WAIT_INCOMPLETE_TIMEOUT_CNTL__RESEND_TIMER__SHIFT: c_uint = 0x18;
pub const UVD_SEMA_WAIT_INCOMPLETE_TIMEOUT_CNTL__WAIT_INCOMPLETE_EN_MASK: c_uint = 0x00000001L;
pub const UVD_SEMA_WAIT_INCOMPLETE_TIMEOUT_CNTL__WAIT_INCOMPLETE_COUNT_MASK: c_uint = 0x001FFFFEL;
pub const UVD_SEMA_WAIT_INCOMPLETE_TIMEOUT_CNTL__RESEND_TIMER_MASK: c_uint = 0x07000000L;
// UVD_SEMA_WAIT_FAULT_TIMEOUT_CNTL
pub const UVD_SEMA_WAIT_FAULT_TIMEOUT_CNTL__WAIT_FAULT_EN__SHIFT: c_uint = 0x0;
pub const UVD_SEMA_WAIT_FAULT_TIMEOUT_CNTL__WAIT_FAULT_COUNT__SHIFT: c_uint = 0x1;
pub const UVD_SEMA_WAIT_FAULT_TIMEOUT_CNTL__RESEND_TIMER__SHIFT: c_uint = 0x18;
pub const UVD_SEMA_WAIT_FAULT_TIMEOUT_CNTL__WAIT_FAULT_EN_MASK: c_uint = 0x00000001L;
pub const UVD_SEMA_WAIT_FAULT_TIMEOUT_CNTL__WAIT_FAULT_COUNT_MASK: c_uint = 0x001FFFFEL;
pub const UVD_SEMA_WAIT_FAULT_TIMEOUT_CNTL__RESEND_TIMER_MASK: c_uint = 0x07000000L;
// UVD_SEMA_SIGNAL_INCOMPLETE_TIMEOUT_CNTL
pub const UVD_SEMA_SIGNAL_INCOMPLETE_TIMEOUT_CNTL__SIGNAL_INCOMPLETE_EN__SHIFT: c_uint = 0x0;
pub const UVD_SEMA_SIGNAL_INCOMPLETE_TIMEOUT_CNTL__SIGNAL_INCOMPLETE_COUNT__SHIFT: c_uint = 0x1;
pub const UVD_SEMA_SIGNAL_INCOMPLETE_TIMEOUT_CNTL__RESEND_TIMER__SHIFT: c_uint = 0x18;
pub const UVD_SEMA_SIGNAL_INCOMPLETE_TIMEOUT_CNTL__SIGNAL_INCOMPLETE_EN_MASK: c_uint = 0x00000001L;
pub const UVD_SEMA_SIGNAL_INCOMPLETE_TIMEOUT_CNTL__SIGNAL_INCOMPLETE_COUNT_MASK: c_uint = 0x001FFFFEL;
pub const UVD_SEMA_SIGNAL_INCOMPLETE_TIMEOUT_CNTL__RESEND_TIMER_MASK: c_uint = 0x07000000L;
// UVD_CONTEXT_ID
pub const UVD_CONTEXT_ID__CONTEXT_ID__SHIFT: c_uint = 0x0;
pub const UVD_CONTEXT_ID__CONTEXT_ID_MASK: c_uint = 0xFFFFFFFFL;
// UVD_CONTEXT_ID2
pub const UVD_CONTEXT_ID2__CONTEXT_ID2__SHIFT: c_uint = 0x0;
pub const UVD_CONTEXT_ID2__CONTEXT_ID2_MASK: c_uint = 0xFFFFFFFFL;
// UVD_FW_STATUS
pub const UVD_FW_STATUS__BUSY__SHIFT: c_uint = 0x0;
pub const UVD_FW_STATUS__ACTIVE__SHIFT: c_uint = 0x1;
pub const UVD_FW_STATUS__SEND_EFUSE_REQ__SHIFT: c_uint = 0x2;
pub const UVD_FW_STATUS__DONE__SHIFT: c_uint = 0x8;
pub const UVD_FW_STATUS__PASS__SHIFT: c_uint = 0x10;
pub const UVD_FW_STATUS__FAIL__SHIFT: c_uint = 0x11;
pub const UVD_FW_STATUS__INVALID_LEN__SHIFT: c_uint = 0x12;
pub const UVD_FW_STATUS__INVALID_0_PADDING__SHIFT: c_uint = 0x13;
pub const UVD_FW_STATUS__INVALID_NONCE__SHIFT: c_uint = 0x14;
pub const UVD_FW_STATUS__BUSY_MASK: c_uint = 0x00000001L;
pub const UVD_FW_STATUS__ACTIVE_MASK: c_uint = 0x00000002L;
pub const UVD_FW_STATUS__SEND_EFUSE_REQ_MASK: c_uint = 0x00000004L;
pub const UVD_FW_STATUS__DONE_MASK: c_uint = 0x00000100L;
pub const UVD_FW_STATUS__PASS_MASK: c_uint = 0x00010000L;
pub const UVD_FW_STATUS__FAIL_MASK: c_uint = 0x00020000L;
pub const UVD_FW_STATUS__INVALID_LEN_MASK: c_uint = 0x00040000L;
pub const UVD_FW_STATUS__INVALID_0_PADDING_MASK: c_uint = 0x00080000L;
pub const UVD_FW_STATUS__INVALID_NONCE_MASK: c_uint = 0x00100000L;
