//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/gaudi2/asic_reg/arc_farm_kdma_ctx_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2020 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// ARC_FARM_KDMA_CTX
// (Prototype: DMA_CORE_CTX)
//
// ARC_FARM_KDMA_CTX_RATE_LIM_TKN
pub const ARC_FARM_KDMA_CTX_RATE_LIM_TKN_RD_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_RATE_LIM_TKN_RD_MASK: c_uint = 0xFF;
pub const ARC_FARM_KDMA_CTX_RATE_LIM_TKN_WR_SHIFT: c_int = 16;
pub const ARC_FARM_KDMA_CTX_RATE_LIM_TKN_WR_MASK: c_uint = 0xFF0000;
// ARC_FARM_KDMA_CTX_PWRLP
pub const ARC_FARM_KDMA_CTX_PWRLP_DATA_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_PWRLP_DATA_MASK: c_uint = 0xFF;
pub const ARC_FARM_KDMA_CTX_PWRLP_EN_SHIFT: c_int = 8;
pub const ARC_FARM_KDMA_CTX_PWRLP_EN_MASK: c_uint = 0x100;
// ARC_FARM_KDMA_CTX_TE_NUMROWS
pub const ARC_FARM_KDMA_CTX_TE_NUMROWS_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_TE_NUMROWS_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_IDX
pub const ARC_FARM_KDMA_CTX_IDX_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_IDX_VAL_MASK: c_uint = 0xFFFF;
// ARC_FARM_KDMA_CTX_IDX_INC
pub const ARC_FARM_KDMA_CTX_IDX_INC_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_IDX_INC_VAL_MASK: c_uint = 0xFF;
// ARC_FARM_KDMA_CTX_CTRL
pub const ARC_FARM_KDMA_CTX_CTRL_TRANSPOSE_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_CTRL_TRANSPOSE_MASK: c_uint = 0x1;
pub const ARC_FARM_KDMA_CTX_CTRL_DTYPE_SHIFT: c_int = 4;
pub const ARC_FARM_KDMA_CTX_CTRL_DTYPE_MASK: c_uint = 0x30;
pub const ARC_FARM_KDMA_CTX_CTRL_COMPRESS_SHIFT: c_int = 8;
pub const ARC_FARM_KDMA_CTX_CTRL_COMPRESS_MASK: c_uint = 0x100;
pub const ARC_FARM_KDMA_CTX_CTRL_DECOMPRESS_SHIFT: c_int = 9;
pub const ARC_FARM_KDMA_CTX_CTRL_DECOMPRESS_MASK: c_uint = 0x200;
pub const ARC_FARM_KDMA_CTX_CTRL_RD_UNCACHEABLE_SHIFT: c_int = 12;
pub const ARC_FARM_KDMA_CTX_CTRL_RD_UNCACHEABLE_MASK: c_uint = 0x1000;
// ARC_FARM_KDMA_CTX_SRC_TSIZE_0
pub const ARC_FARM_KDMA_CTX_SRC_TSIZE_0_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_TSIZE_0_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_TSIZE_1
pub const ARC_FARM_KDMA_CTX_SRC_TSIZE_1_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_TSIZE_1_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_STRIDE_1
pub const ARC_FARM_KDMA_CTX_SRC_STRIDE_1_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_STRIDE_1_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_TSIZE_2
pub const ARC_FARM_KDMA_CTX_SRC_TSIZE_2_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_TSIZE_2_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_STRIDE_2
pub const ARC_FARM_KDMA_CTX_SRC_STRIDE_2_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_STRIDE_2_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_TSIZE_3
pub const ARC_FARM_KDMA_CTX_SRC_TSIZE_3_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_TSIZE_3_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_STRIDE_3
pub const ARC_FARM_KDMA_CTX_SRC_STRIDE_3_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_STRIDE_3_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_TSIZE_4
pub const ARC_FARM_KDMA_CTX_SRC_TSIZE_4_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_TSIZE_4_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_STRIDE_4
pub const ARC_FARM_KDMA_CTX_SRC_STRIDE_4_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_STRIDE_4_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_TSIZE_1
pub const ARC_FARM_KDMA_CTX_DST_TSIZE_1_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_TSIZE_1_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_STRIDE_1
pub const ARC_FARM_KDMA_CTX_DST_STRIDE_1_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_STRIDE_1_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_TSIZE_2
pub const ARC_FARM_KDMA_CTX_DST_TSIZE_2_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_TSIZE_2_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_STRIDE_2
pub const ARC_FARM_KDMA_CTX_DST_STRIDE_2_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_STRIDE_2_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_TSIZE_3
pub const ARC_FARM_KDMA_CTX_DST_TSIZE_3_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_TSIZE_3_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_STRIDE_3
pub const ARC_FARM_KDMA_CTX_DST_STRIDE_3_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_STRIDE_3_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_TSIZE_4
pub const ARC_FARM_KDMA_CTX_DST_TSIZE_4_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_TSIZE_4_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_STRIDE_4
pub const ARC_FARM_KDMA_CTX_DST_STRIDE_4_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_STRIDE_4_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_WR_COMP_ADDR_HI
pub const ARC_FARM_KDMA_CTX_WR_COMP_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_WR_COMP_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_WR_COMP_ADDR_LO
pub const ARC_FARM_KDMA_CTX_WR_COMP_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_WR_COMP_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_WR_COMP_WDATA
pub const ARC_FARM_KDMA_CTX_WR_COMP_WDATA_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_WR_COMP_WDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_OFFSET_LO
pub const ARC_FARM_KDMA_CTX_SRC_OFFSET_LO_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_OFFSET_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_OFFSET_HI
pub const ARC_FARM_KDMA_CTX_SRC_OFFSET_HI_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_OFFSET_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_OFFSET_LO
pub const ARC_FARM_KDMA_CTX_DST_OFFSET_LO_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_OFFSET_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_OFFSET_HI
pub const ARC_FARM_KDMA_CTX_DST_OFFSET_HI_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_OFFSET_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_BASE_LO
pub const ARC_FARM_KDMA_CTX_SRC_BASE_LO_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_SRC_BASE_HI
pub const ARC_FARM_KDMA_CTX_SRC_BASE_HI_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_SRC_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_BASE_LO
pub const ARC_FARM_KDMA_CTX_DST_BASE_LO_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_BASE_HI
pub const ARC_FARM_KDMA_CTX_DST_BASE_HI_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_DST_TSIZE_0
pub const ARC_FARM_KDMA_CTX_DST_TSIZE_0_VAL_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_DST_TSIZE_0_VAL_MASK: c_uint = 0xFFFFFFFF;
// ARC_FARM_KDMA_CTX_COMMIT
pub const ARC_FARM_KDMA_CTX_COMMIT_WR_COMP_EN_SHIFT: c_int = 0;
pub const ARC_FARM_KDMA_CTX_COMMIT_WR_COMP_EN_MASK: c_uint = 0x1;
pub const ARC_FARM_KDMA_CTX_COMMIT_ENDIAN_SWAP_SHIFT: c_int = 1;
pub const ARC_FARM_KDMA_CTX_COMMIT_ENDIAN_SWAP_MASK: c_uint = 0x6;
pub const ARC_FARM_KDMA_CTX_COMMIT_MEM_SET_SHIFT: c_int = 4;
pub const ARC_FARM_KDMA_CTX_COMMIT_MEM_SET_MASK: c_uint = 0x10;
pub const ARC_FARM_KDMA_CTX_COMMIT_BF16_SHIFT: c_int = 6;
pub const ARC_FARM_KDMA_CTX_COMMIT_BF16_MASK: c_uint = 0x40;
pub const ARC_FARM_KDMA_CTX_COMMIT_FP16_SHIFT: c_int = 7;
pub const ARC_FARM_KDMA_CTX_COMMIT_FP16_MASK: c_uint = 0x80;
pub const ARC_FARM_KDMA_CTX_COMMIT_CTX_ID_INC_SHIFT: c_int = 8;
pub const ARC_FARM_KDMA_CTX_COMMIT_CTX_ID_INC_MASK: c_uint = 0x100;
pub const ARC_FARM_KDMA_CTX_COMMIT_ADD_OFFSET_0_SHIFT: c_int = 9;
pub const ARC_FARM_KDMA_CTX_COMMIT_ADD_OFFSET_0_MASK: c_uint = 0x200;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_SIZE0_FROM_DST_SIZE0_SHIFT: c_int = 10;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_SIZE0_FROM_DST_SIZE0_MASK: c_uint = 0x400;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_OFST_FROM_DST_OFST_SHIFT: c_int = 11;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_OFST_FROM_DST_OFST_MASK: c_uint = 0x800;
pub const ARC_FARM_KDMA_CTX_COMMIT_DISABLE_DIM1_SHIFT: c_int = 12;
pub const ARC_FARM_KDMA_CTX_COMMIT_DISABLE_DIM1_MASK: c_uint = 0x1000;
pub const ARC_FARM_KDMA_CTX_COMMIT_DISABLE_DIM2_SHIFT: c_int = 13;
pub const ARC_FARM_KDMA_CTX_COMMIT_DISABLE_DIM2_MASK: c_uint = 0x2000;
pub const ARC_FARM_KDMA_CTX_COMMIT_DISABLE_DIM3_SHIFT: c_int = 14;
pub const ARC_FARM_KDMA_CTX_COMMIT_DISABLE_DIM3_MASK: c_uint = 0x4000;
pub const ARC_FARM_KDMA_CTX_COMMIT_DISABLE_DIM4_SHIFT: c_int = 15;
pub const ARC_FARM_KDMA_CTX_COMMIT_DISABLE_DIM4_MASK: c_uint = 0x8000;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_SIZE1_FROM_DST_SIZE1_SHIFT: c_int = 16;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_SIZE1_FROM_DST_SIZE1_MASK: c_uint = 0x10000;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_SIZE2_FROM_DST_SIZE2_SHIFT: c_int = 17;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_SIZE2_FROM_DST_SIZE2_MASK: c_uint = 0x20000;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_SIZE3_FROM_DST_SIZE3_SHIFT: c_int = 18;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_SIZE3_FROM_DST_SIZE3_MASK: c_uint = 0x40000;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_SIZE4_FROM_DST_SIZE4_SHIFT: c_int = 19;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_SIZE4_FROM_DST_SIZE4_MASK: c_uint = 0x80000;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_STRD1_FROM_DST_STRD1_SHIFT: c_int = 20;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_STRD1_FROM_DST_STRD1_MASK: c_uint = 0x100000;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_STRD2_FROM_DST_STRD2_SHIFT: c_int = 21;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_STRD2_FROM_DST_STRD2_MASK: c_uint = 0x200000;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_STRD3_FROM_DST_STRD3_SHIFT: c_int = 22;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_STRD3_FROM_DST_STRD3_MASK: c_uint = 0x400000;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_STRD4_FROM_DST_STRD4_SHIFT: c_int = 23;
pub const ARC_FARM_KDMA_CTX_COMMIT_SRC_STRD4_FROM_DST_STRD4_MASK: c_uint = 0x800000;
pub const ARC_FARM_KDMA_CTX_COMMIT_LIN_SHIFT: c_int = 31;
pub const ARC_FARM_KDMA_CTX_COMMIT_LIN_MASK: c_uint = 0x80000000;
