//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/gaudi2/asic_reg/dcore0_edma0_qm_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2020 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// DCORE0_EDMA0_QM
// (Prototype: QMAN)
//
// DCORE0_EDMA0_QM_GLBL_CFG0
pub const DCORE0_EDMA0_QM_GLBL_CFG0_PQF_EN_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_CFG0_PQF_EN_MASK: c_uint = 0xF;
pub const DCORE0_EDMA0_QM_GLBL_CFG0_CQF_EN_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_GLBL_CFG0_CQF_EN_MASK: c_uint = 0x1F0;
pub const DCORE0_EDMA0_QM_GLBL_CFG0_CP_EN_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_GLBL_CFG0_CP_EN_MASK: c_uint = 0x3E00;
pub const DCORE0_EDMA0_QM_GLBL_CFG0_ARC_CQF_EN_SHIFT: c_int = 14;
pub const DCORE0_EDMA0_QM_GLBL_CFG0_ARC_CQF_EN_MASK: c_uint = 0x4000;
// DCORE0_EDMA0_QM_GLBL_CFG1
pub const DCORE0_EDMA0_QM_GLBL_CFG1_PQF_STOP_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_CFG1_PQF_STOP_MASK: c_uint = 0xF;
pub const DCORE0_EDMA0_QM_GLBL_CFG1_CQF_STOP_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_GLBL_CFG1_CQF_STOP_MASK: c_uint = 0x1F0;
pub const DCORE0_EDMA0_QM_GLBL_CFG1_CP_STOP_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_GLBL_CFG1_CP_STOP_MASK: c_uint = 0x3E00;
pub const DCORE0_EDMA0_QM_GLBL_CFG1_PQF_FLUSH_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_GLBL_CFG1_PQF_FLUSH_MASK: c_uint = 0xF0000;
pub const DCORE0_EDMA0_QM_GLBL_CFG1_CQF_FLUSH_SHIFT: c_int = 20;
pub const DCORE0_EDMA0_QM_GLBL_CFG1_CQF_FLUSH_MASK: c_uint = 0x1F00000;
pub const DCORE0_EDMA0_QM_GLBL_CFG1_CP_FLUSH_SHIFT: c_int = 25;
pub const DCORE0_EDMA0_QM_GLBL_CFG1_CP_FLUSH_MASK: c_uint = 0x3E000000;
// DCORE0_EDMA0_QM_GLBL_CFG2
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_CQF_STOP_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_CQF_STOP_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_CQF_FLUSH_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_CQF_FLUSH_MASK: c_uint = 0x2;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_AWUSER_OVRD_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_AWUSER_OVRD_MASK: c_uint = 0x10;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_ARUSER_OVRD_SHIFT: c_int = 5;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_ARUSER_OVRD_MASK: c_uint = 0x20;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_AWUSER_OVRD_SHIFT: c_int = 6;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_AWUSER_OVRD_MASK: c_uint = 0x40;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_ARUSER_OVRD_SHIFT: c_int = 7;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_ARUSER_OVRD_MASK: c_uint = 0x80;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_AWPROT_OVRD_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_AWPROT_OVRD_MASK: c_uint = 0x100;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_ARPROT_OVRD_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_ARPROT_OVRD_MASK: c_uint = 0x200;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_AWPROT_OVRD_SHIFT: c_int = 10;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_AWPROT_OVRD_MASK: c_uint = 0x400;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_ARPROT_OVRD_SHIFT: c_int = 11;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_ARPROT_OVRD_MASK: c_uint = 0x800;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_AWCACHE_OVRD_SHIFT: c_int = 12;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_AWCACHE_OVRD_MASK: c_uint = 0x1000;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_ARCACHE_OVRD_SHIFT: c_int = 13;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_HBW_ARCACHE_OVRD_MASK: c_uint = 0x2000;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_AWCACHE_OVRD_SHIFT: c_int = 14;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_AWCACHE_OVRD_MASK: c_uint = 0x4000;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_ARCACHE_OVRD_SHIFT: c_int = 15;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_ARCACHE_OVRD_MASK: c_uint = 0x8000;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_BUSER_OVRD_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_GLBL_CFG2_ARC_LBW_BUSER_OVRD_MASK: c_uint = 0x10000;
// DCORE0_EDMA0_QM_GLBL_ERR_CFG
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_PQF_ERR_MSG_EN_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_PQF_ERR_MSG_EN_MASK: c_uint = 0xF;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_CQF_ERR_MSG_EN_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_CQF_ERR_MSG_EN_MASK: c_uint = 0x1F0;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_CP_ERR_MSG_EN_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_CP_ERR_MSG_EN_MASK: c_uint = 0x3E00;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_PQF_STOP_ON_ERR_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_PQF_STOP_ON_ERR_MASK: c_uint = 0xF0000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_CQF_STOP_ON_ERR_SHIFT: c_int = 20;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_CQF_STOP_ON_ERR_MASK: c_uint = 0x1F00000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_CP_STOP_ON_ERR_SHIFT: c_int = 25;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_CP_STOP_ON_ERR_MASK: c_uint = 0x3E000000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_ARB_STOP_ON_ERR_SHIFT: c_int = 31;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG_ARB_STOP_ON_ERR_MASK: c_uint = 0x80000000;
// DCORE0_EDMA0_QM_GLBL_ERR_CFG1
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG1_CQF_ERR_MSG_EN_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG1_CQF_ERR_MSG_EN_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG1_CQF_STOP_ON_ERR_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG1_CQF_STOP_ON_ERR_MASK: c_uint = 0x2;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG1_ARC_STOP_ON_ERR_SHIFT: c_int = 2;
pub const DCORE0_EDMA0_QM_GLBL_ERR_CFG1_ARC_STOP_ON_ERR_MASK: c_uint = 0x4;
// DCORE0_EDMA0_QM_GLBL_ERR_ARC_HALT_EN
pub const DCORE0_EDMA0_QM_GLBL_ERR_ARC_HALT_EN_ERR_IND_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_ERR_ARC_HALT_EN_ERR_IND_MASK: c_uint = 0xFFFFFF;
// DCORE0_EDMA0_QM_GLBL_AXCACHE
pub const DCORE0_EDMA0_QM_GLBL_AXCACHE_HBW_AR_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_AXCACHE_HBW_AR_MASK: c_uint = 0xF;
pub const DCORE0_EDMA0_QM_GLBL_AXCACHE_HBW_AW_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_GLBL_AXCACHE_HBW_AW_MASK: c_uint = 0xF0000;
pub const DCORE0_EDMA0_QM_GLBL_AXCACHE_LBW_AW_SHIFT: c_int = 20;
pub const DCORE0_EDMA0_QM_GLBL_AXCACHE_LBW_AW_MASK: c_uint = 0xF00000;
pub const DCORE0_EDMA0_QM_GLBL_AXCACHE_LBW_AR_SHIFT: c_int = 24;
pub const DCORE0_EDMA0_QM_GLBL_AXCACHE_LBW_AR_MASK: c_uint = 0xF000000;
// DCORE0_EDMA0_QM_GLBL_STS0
pub const DCORE0_EDMA0_QM_GLBL_STS0_PQF_IDLE_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_STS0_PQF_IDLE_MASK: c_uint = 0xF;
pub const DCORE0_EDMA0_QM_GLBL_STS0_CQF_IDLE_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_GLBL_STS0_CQF_IDLE_MASK: c_uint = 0x1F0;
pub const DCORE0_EDMA0_QM_GLBL_STS0_CP_IDLE_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_GLBL_STS0_CP_IDLE_MASK: c_uint = 0x3E00;
pub const DCORE0_EDMA0_QM_GLBL_STS0_PQF_IS_STOP_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_GLBL_STS0_PQF_IS_STOP_MASK: c_uint = 0xF0000;
pub const DCORE0_EDMA0_QM_GLBL_STS0_CQF_IS_STOP_SHIFT: c_int = 20;
pub const DCORE0_EDMA0_QM_GLBL_STS0_CQF_IS_STOP_MASK: c_uint = 0x1F00000;
pub const DCORE0_EDMA0_QM_GLBL_STS0_CP_IS_STOP_SHIFT: c_int = 25;
pub const DCORE0_EDMA0_QM_GLBL_STS0_CP_IS_STOP_MASK: c_uint = 0x3E000000;
pub const DCORE0_EDMA0_QM_GLBL_STS0_ARB_IS_STOP_SHIFT: c_int = 31;
pub const DCORE0_EDMA0_QM_GLBL_STS0_ARB_IS_STOP_MASK: c_uint = 0x80000000;
// DCORE0_EDMA0_QM_GLBL_STS1
pub const DCORE0_EDMA0_QM_GLBL_STS1_ARC_CQF_IDLE_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_STS1_ARC_CQF_IDLE_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_GLBL_STS1_ARC_CQF_IS_STOP_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_GLBL_STS1_ARC_CQF_IS_STOP_MASK: c_uint = 0x2;
// DCORE0_EDMA0_QM_GLBL_ERR_STS
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_PQF_RD_ERR_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_PQF_RD_ERR_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CQF_RD_ERR_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CQF_RD_ERR_MASK: c_uint = 0x2;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_RD_ERR_SHIFT: c_int = 2;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_RD_ERR_MASK: c_uint = 0x4;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_UNDEF_CMD_ERR_SHIFT: c_int = 3;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_UNDEF_CMD_ERR_MASK: c_uint = 0x8;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_STOP_OP_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_STOP_OP_MASK: c_uint = 0x10;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_MSG_WR_ERR_SHIFT: c_int = 5;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_MSG_WR_ERR_MASK: c_uint = 0x20;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_WREG_ERR_SHIFT: c_int = 6;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_WREG_ERR_MASK: c_uint = 0x40;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE0_OVF_ERR_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE0_OVF_ERR_MASK: c_uint = 0x100;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE1_OVF_ERR_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE1_OVF_ERR_MASK: c_uint = 0x200;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE2_OVF_ERR_SHIFT: c_int = 10;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE2_OVF_ERR_MASK: c_uint = 0x400;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE3_OVF_ERR_SHIFT: c_int = 11;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE3_OVF_ERR_MASK: c_uint = 0x800;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE0_UDF_ERR_SHIFT: c_int = 12;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE0_UDF_ERR_MASK: c_uint = 0x1000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE1_UDF_ERR_SHIFT: c_int = 13;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE1_UDF_ERR_MASK: c_uint = 0x2000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE2_UDF_ERR_SHIFT: c_int = 14;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE2_UDF_ERR_MASK: c_uint = 0x4000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE3_UDF_ERR_SHIFT: c_int = 15;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CP_FENCE3_UDF_ERR_MASK: c_uint = 0x8000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CPDMA_UP_OVF_ERR_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_CPDMA_UP_OVF_ERR_MASK: c_uint = 0x10000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_PQC_L2H_ERR_SHIFT: c_int = 17;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_PQC_L2H_ERR_MASK: c_uint = 0x20000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_RSVD_18_24_SHIFT: c_int = 18;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_RSVD_18_24_MASK: c_uint = 0x1FC0000;
// DCORE0_EDMA0_QM_GLBL_ERR_STS_4
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_RSVD0_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_RSVD0_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CQF_RD_ERR_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CQF_RD_ERR_MASK: c_uint = 0x2;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_RD_ERR_SHIFT: c_int = 2;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_RD_ERR_MASK: c_uint = 0x4;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_UNDEF_CMD_ERR_SHIFT: c_int = 3;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_UNDEF_CMD_ERR_MASK: c_uint = 0x8;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_STOP_OP_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_STOP_OP_MASK: c_uint = 0x10;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_MSG_WR_ERR_SHIFT: c_int = 5;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_MSG_WR_ERR_MASK: c_uint = 0x20;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_WREG_ERR_SHIFT: c_int = 6;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_WREG_ERR_MASK: c_uint = 0x40;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE0_OVF_ERR_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE0_OVF_ERR_MASK: c_uint = 0x100;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE1_OVF_ERR_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE1_OVF_ERR_MASK: c_uint = 0x200;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE2_OVF_ERR_SHIFT: c_int = 10;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE2_OVF_ERR_MASK: c_uint = 0x400;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE3_OVF_ERR_SHIFT: c_int = 11;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE3_OVF_ERR_MASK: c_uint = 0x800;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE0_UDF_ERR_SHIFT: c_int = 12;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE0_UDF_ERR_MASK: c_uint = 0x1000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE1_UDF_ERR_SHIFT: c_int = 13;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE1_UDF_ERR_MASK: c_uint = 0x2000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE2_UDF_ERR_SHIFT: c_int = 14;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE2_UDF_ERR_MASK: c_uint = 0x4000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE3_UDF_ERR_SHIFT: c_int = 15;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_FENCE3_UDF_ERR_MASK: c_uint = 0x8000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CPDMA_UP_OVF_ERR_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CPDMA_UP_OVF_ERR_MASK: c_uint = 0x10000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_RSVD17_SHIFT: c_int = 17;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_RSVD17_MASK: c_uint = 0x20000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CQ_WR_IFIFO_CI_ERR_SHIFT: c_int = 18;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CQ_WR_IFIFO_CI_ERR_MASK: c_uint = 0x40000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CQ_WR_CTL_CI_ERR_SHIFT: c_int = 19;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CQ_WR_CTL_CI_ERR_MASK: c_uint = 0x80000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_ARC_CQF_RD_ERR_SHIFT: c_int = 20;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_ARC_CQF_RD_ERR_MASK: c_uint = 0x100000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_ARC_CQ_WR_IFIFO_CI_ERR_SHIFT: c_int = 21;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_ARC_CQ_WR_IFIFO_CI_ERR_MASK: c_uint = 0x200000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_ARC_CQ_WR_CTL_CI_ERR_SHIFT: c_int = 22;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_ARC_CQ_WR_CTL_CI_ERR_MASK: c_uint = 0x400000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_ARC_AXI_ERR_SHIFT: c_int = 23;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_ARC_AXI_ERR_MASK: c_uint = 0x800000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_SWITCH_WDT_ERR_SHIFT: c_int = 24;
pub const DCORE0_EDMA0_QM_GLBL_ERR_STS_4_CP_SWITCH_WDT_ERR_MASK: c_uint = 0x1000000;
// DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_PQF_RD_ERR_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_PQF_RD_ERR_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CQF_RD_ERR_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CQF_RD_ERR_MASK: c_uint = 0x2;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_RD_ERR_SHIFT: c_int = 2;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_RD_ERR_MASK: c_uint = 0x4;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_UNDEF_CMD_ERR_SHIFT: c_int = 3;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_UNDEF_CMD_ERR_MASK: c_uint = 0x8;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_STOP_OP_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_STOP_OP_MASK: c_uint = 0x10;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_MSG_WR_ERR_SHIFT: c_int = 5;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_MSG_WR_ERR_MASK: c_uint = 0x20;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_WREG_ERR_SHIFT: c_int = 6;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_WREG_ERR_MASK: c_uint = 0x40;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE0_OVF_ERR_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE0_OVF_ERR_MASK: c_uint = 0x100;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE1_OVF_ERR_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE1_OVF_ERR_MASK: c_uint = 0x200;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE2_OVF_ERR_SHIFT: c_int = 10;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE2_OVF_ERR_MASK: c_uint = 0x400;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE3_OVF_ERR_SHIFT: c_int = 11;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE3_OVF_ERR_MASK: c_uint = 0x800;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE0_UDF_ERR_SHIFT: c_int = 12;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE0_UDF_ERR_MASK: c_uint = 0x1000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE1_UDF_ERR_SHIFT: c_int = 13;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE1_UDF_ERR_MASK: c_uint = 0x2000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE2_UDF_ERR_SHIFT: c_int = 14;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE2_UDF_ERR_MASK: c_uint = 0x4000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE3_UDF_ERR_SHIFT: c_int = 15;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CP_FENCE3_UDF_ERR_MASK: c_uint = 0x8000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CPDMA_UP_OVF_ERR_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_CPDMA_UP_OVF_ERR_MASK: c_uint = 0x10000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_PQC_L2H_ERR_SHIFT: c_int = 17;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_PQC_L2H_ERR_MASK: c_uint = 0x20000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_RSVD_18_24_SHIFT: c_int = 18;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_RSVD_18_24_MASK: c_uint = 0x1FC0000;
// DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_RSVD0_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_RSVD0_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CQF_RD_ERR_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CQF_RD_ERR_MASK: c_uint = 0x2;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_RD_ERR_SHIFT: c_int = 2;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_RD_ERR_MASK: c_uint = 0x4;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_UNDEF_CMD_ERR_SHIFT: c_int = 3;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_UNDEF_CMD_ERR_MASK: c_uint = 0x8;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_STOP_OP_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_STOP_OP_MASK: c_uint = 0x10;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_MSG_WR_ERR_SHIFT: c_int = 5;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_MSG_WR_ERR_MASK: c_uint = 0x20;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_WREG_ERR_SHIFT: c_int = 6;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_WREG_ERR_MASK: c_uint = 0x40;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE0_OVF_ERR_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE0_OVF_ERR_MASK: c_uint = 0x100;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE1_OVF_ERR_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE1_OVF_ERR_MASK: c_uint = 0x200;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE2_OVF_ERR_SHIFT: c_int = 10;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE2_OVF_ERR_MASK: c_uint = 0x400;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE3_OVF_ERR_SHIFT: c_int = 11;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE3_OVF_ERR_MASK: c_uint = 0x800;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE0_UDF_ERR_SHIFT: c_int = 12;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE0_UDF_ERR_MASK: c_uint = 0x1000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE1_UDF_ERR_SHIFT: c_int = 13;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE1_UDF_ERR_MASK: c_uint = 0x2000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE2_UDF_ERR_SHIFT: c_int = 14;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE2_UDF_ERR_MASK: c_uint = 0x4000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE3_UDF_ERR_SHIFT: c_int = 15;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_FENCE3_UDF_ERR_MASK: c_uint = 0x8000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CPDMA_UP_OVF_ERR_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CPDMA_UP_OVF_ERR_MASK: c_uint = 0x10000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_RSVD17_SHIFT: c_int = 17;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_RSVD17_MASK: c_uint = 0x20000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CQ_WR_IFIFO_CI_ERR_SHIFT: c_int = 18;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CQ_WR_IFIFO_CI_ERR_MASK: c_uint = 0x40000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CQ_WR_CTL_CI_ERR_SHIFT: c_int = 19;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CQ_WR_CTL_CI_ERR_MASK: c_uint = 0x80000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_ARC_CQF_RD_ERR_SHIFT: c_int = 20;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_ARC_CQF_RD_ERR_MASK: c_uint = 0x100000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_ARC_CQ_WR_IFIFO_CI_ERR_SHIFT: c_int = 21;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_ARC_CQ_WR_IFIFO_CI_ERR_MASK: c_uint = 0x200000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_ARC_CQ_WR_CTL_CI_ERR_SHIFT: c_int = 22;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_ARC_CQ_WR_CTL_CI_ERR_MASK: c_uint = 0x400000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_ARC_AXI_ERR_SHIFT: c_int = 23;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_ARC_AXI_ERR_MASK: c_uint = 0x800000;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_SWITCH_WDT_ERR_SHIFT: c_int = 24;
pub const DCORE0_EDMA0_QM_GLBL_ERR_MSG_EN_4_CP_SWITCH_WDT_ERR_MASK: c_uint = 0x1000000;
// DCORE0_EDMA0_QM_GLBL_PROT
pub const DCORE0_EDMA0_QM_GLBL_PROT_PQF_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_PROT_PQF_MASK: c_uint = 0xF;
pub const DCORE0_EDMA0_QM_GLBL_PROT_CQF_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_GLBL_PROT_CQF_MASK: c_uint = 0x1F0;
pub const DCORE0_EDMA0_QM_GLBL_PROT_CP_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_GLBL_PROT_CP_MASK: c_uint = 0x3E00;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ERR_SHIFT: c_int = 14;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ERR_MASK: c_uint = 0x4000;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ARB_SHIFT: c_int = 15;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ARB_MASK: c_uint = 0x8000;
pub const DCORE0_EDMA0_QM_GLBL_PROT_PQC_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_GLBL_PROT_PQC_MASK: c_uint = 0x10000;
pub const DCORE0_EDMA0_QM_GLBL_PROT_CQ_IFIFO_MSG_SHIFT: c_int = 17;
pub const DCORE0_EDMA0_QM_GLBL_PROT_CQ_IFIFO_MSG_MASK: c_uint = 0x20000;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ARC_CQ_IFIFO_MSG_SHIFT: c_int = 18;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ARC_CQ_IFIFO_MSG_MASK: c_uint = 0x40000;
pub const DCORE0_EDMA0_QM_GLBL_PROT_CQ_CTL_MSG_SHIFT: c_int = 19;
pub const DCORE0_EDMA0_QM_GLBL_PROT_CQ_CTL_MSG_MASK: c_uint = 0x80000;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ARC_CQ_CTL_MSG_SHIFT: c_int = 20;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ARC_CQ_CTL_MSG_MASK: c_uint = 0x100000;
pub const DCORE0_EDMA0_QM_GLBL_PROT_CP_WR_ARC_SHIFT: c_int = 21;
pub const DCORE0_EDMA0_QM_GLBL_PROT_CP_WR_ARC_MASK: c_uint = 0x200000;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ARC_CQF_SHIFT: c_int = 22;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ARC_CQF_MASK: c_uint = 0x400000;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ARC_CORE_SHIFT: c_int = 23;
pub const DCORE0_EDMA0_QM_GLBL_PROT_ARC_CORE_MASK: c_uint = 0x800000;
// DCORE0_EDMA0_QM_PQ_BASE_LO
pub const DCORE0_EDMA0_QM_PQ_BASE_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQ_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQ_BASE_HI
pub const DCORE0_EDMA0_QM_PQ_BASE_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQ_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQ_SIZE
pub const DCORE0_EDMA0_QM_PQ_SIZE_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQ_SIZE_VAL_MASK: c_uint = 0x1F;
// DCORE0_EDMA0_QM_PQ_PI
pub const DCORE0_EDMA0_QM_PQ_PI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQ_PI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQ_CI
pub const DCORE0_EDMA0_QM_PQ_CI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQ_CI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQ_CFG0
pub const DCORE0_EDMA0_QM_PQ_CFG0_FORCE_STALL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQ_CFG0_FORCE_STALL_MASK: c_uint = 0x1;
// DCORE0_EDMA0_QM_PQ_CFG1
pub const DCORE0_EDMA0_QM_PQ_CFG1_CREDIT_LIM_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQ_CFG1_CREDIT_LIM_MASK: c_uint = 0xFF;
pub const DCORE0_EDMA0_QM_PQ_CFG1_MAX_INFLIGHT_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_PQ_CFG1_MAX_INFLIGHT_MASK: c_uint = 0xFF0000;
// DCORE0_EDMA0_QM_PQ_STS0
pub const DCORE0_EDMA0_QM_PQ_STS0_CREDIT_CNT_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQ_STS0_CREDIT_CNT_MASK: c_uint = 0xFF;
pub const DCORE0_EDMA0_QM_PQ_STS0_FREE_CNT_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_PQ_STS0_FREE_CNT_MASK: c_uint = 0xFF00;
pub const DCORE0_EDMA0_QM_PQ_STS0_INFLIGHT_CNT_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_PQ_STS0_INFLIGHT_CNT_MASK: c_uint = 0xFF0000;
// DCORE0_EDMA0_QM_PQ_STS1
pub const DCORE0_EDMA0_QM_PQ_STS1_BUF_EMPTY_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQ_STS1_BUF_EMPTY_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_PQ_STS1_BUSY_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_PQ_STS1_BUSY_MASK: c_uint = 0x2;
// DCORE0_EDMA0_QM_CQ_CFG0
pub const DCORE0_EDMA0_QM_CQ_CFG0_IF_B2B_EN_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_CFG0_IF_B2B_EN_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_CQ_CFG0_IF_MSG_EN_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_CQ_CFG0_IF_MSG_EN_MASK: c_uint = 0x2;
pub const DCORE0_EDMA0_QM_CQ_CFG0_CTL_MSG_EN_SHIFT: c_int = 2;
pub const DCORE0_EDMA0_QM_CQ_CFG0_CTL_MSG_EN_MASK: c_uint = 0x4;
// DCORE0_EDMA0_QM_CQ_STS0
pub const DCORE0_EDMA0_QM_CQ_STS0_CREDIT_CNT_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_STS0_CREDIT_CNT_MASK: c_uint = 0xFF;
pub const DCORE0_EDMA0_QM_CQ_STS0_FREE_CNT_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_CQ_STS0_FREE_CNT_MASK: c_uint = 0xFF00;
pub const DCORE0_EDMA0_QM_CQ_STS0_INFLIGHT_CNT_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_CQ_STS0_INFLIGHT_CNT_MASK: c_uint = 0xFF0000;
// DCORE0_EDMA0_QM_CQ_CFG1
pub const DCORE0_EDMA0_QM_CQ_CFG1_CREDIT_LIM_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_CFG1_CREDIT_LIM_MASK: c_uint = 0xFF;
pub const DCORE0_EDMA0_QM_CQ_CFG1_MAX_INFLIGHT_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_CQ_CFG1_MAX_INFLIGHT_MASK: c_uint = 0xFF0000;
// DCORE0_EDMA0_QM_CQ_STS1
pub const DCORE0_EDMA0_QM_CQ_STS1_BUF_EMPTY_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_STS1_BUF_EMPTY_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_CQ_STS1_BUSY_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_CQ_STS1_BUSY_MASK: c_uint = 0x2;
// DCORE0_EDMA0_QM_CQ_PTR_LO_0
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_0_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_0_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_PTR_HI_0
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_0_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_0_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_TSIZE_0
pub const DCORE0_EDMA0_QM_CQ_TSIZE_0_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_TSIZE_0_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_CTL_0
pub const DCORE0_EDMA0_QM_CQ_CTL_0_UP_SHIFT: c_int = 28;
pub const DCORE0_EDMA0_QM_CQ_CTL_0_UP_MASK: c_uint = 0xF0000000;
// DCORE0_EDMA0_QM_CQ_PTR_LO_1
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_1_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_1_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_PTR_HI_1
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_1_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_1_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_TSIZE_1
pub const DCORE0_EDMA0_QM_CQ_TSIZE_1_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_TSIZE_1_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_CTL_1
pub const DCORE0_EDMA0_QM_CQ_CTL_1_UP_SHIFT: c_int = 28;
pub const DCORE0_EDMA0_QM_CQ_CTL_1_UP_MASK: c_uint = 0xF0000000;
// DCORE0_EDMA0_QM_CQ_PTR_LO_2
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_2_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_2_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_PTR_HI_2
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_2_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_2_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_TSIZE_2
pub const DCORE0_EDMA0_QM_CQ_TSIZE_2_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_TSIZE_2_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_CTL_2
pub const DCORE0_EDMA0_QM_CQ_CTL_2_UP_SHIFT: c_int = 28;
pub const DCORE0_EDMA0_QM_CQ_CTL_2_UP_MASK: c_uint = 0xF0000000;
// DCORE0_EDMA0_QM_CQ_PTR_LO_3
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_3_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_3_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_PTR_HI_3
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_3_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_3_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_TSIZE_3
pub const DCORE0_EDMA0_QM_CQ_TSIZE_3_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_TSIZE_3_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_CTL_3
pub const DCORE0_EDMA0_QM_CQ_CTL_3_UP_SHIFT: c_int = 28;
pub const DCORE0_EDMA0_QM_CQ_CTL_3_UP_MASK: c_uint = 0xF0000000;
// DCORE0_EDMA0_QM_CQ_PTR_LO_4
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_4_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_4_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_PTR_HI_4
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_4_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_4_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_TSIZE_4
pub const DCORE0_EDMA0_QM_CQ_TSIZE_4_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_TSIZE_4_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_CTL_4
pub const DCORE0_EDMA0_QM_CQ_CTL_4_UP_SHIFT: c_int = 28;
pub const DCORE0_EDMA0_QM_CQ_CTL_4_UP_MASK: c_uint = 0xF0000000;
// DCORE0_EDMA0_QM_CQ_TSIZE_STS
pub const DCORE0_EDMA0_QM_CQ_TSIZE_STS_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_TSIZE_STS_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_PTR_LO_STS
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_STS_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_LO_STS_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_PTR_HI_STS
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_STS_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_PTR_HI_STS_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_IFIFO_STS
pub const DCORE0_EDMA0_QM_CQ_IFIFO_STS_CNT_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_IFIFO_STS_CNT_MASK: c_uint = 0x7;
pub const DCORE0_EDMA0_QM_CQ_IFIFO_STS_RDY_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_CQ_IFIFO_STS_RDY_MASK: c_uint = 0x10;
pub const DCORE0_EDMA0_QM_CQ_IFIFO_STS_CTL_STALL_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_CQ_IFIFO_STS_CTL_STALL_MASK: c_uint = 0x100;
// DCORE0_EDMA0_QM_CP_MSG_BASE0_ADDR_LO
pub const DCORE0_EDMA0_QM_CP_MSG_BASE0_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_MSG_BASE0_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_MSG_BASE0_ADDR_HI
pub const DCORE0_EDMA0_QM_CP_MSG_BASE0_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_MSG_BASE0_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_MSG_BASE1_ADDR_LO
pub const DCORE0_EDMA0_QM_CP_MSG_BASE1_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_MSG_BASE1_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_MSG_BASE1_ADDR_HI
pub const DCORE0_EDMA0_QM_CP_MSG_BASE1_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_MSG_BASE1_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_MSG_BASE2_ADDR_LO
pub const DCORE0_EDMA0_QM_CP_MSG_BASE2_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_MSG_BASE2_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_MSG_BASE2_ADDR_HI
pub const DCORE0_EDMA0_QM_CP_MSG_BASE2_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_MSG_BASE2_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_MSG_BASE3_ADDR_LO
pub const DCORE0_EDMA0_QM_CP_MSG_BASE3_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_MSG_BASE3_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_MSG_BASE3_ADDR_HI
pub const DCORE0_EDMA0_QM_CP_MSG_BASE3_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_MSG_BASE3_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_FENCE0_RDATA
pub const DCORE0_EDMA0_QM_CP_FENCE0_RDATA_INC_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_FENCE0_RDATA_INC_VAL_MASK: c_uint = 0xF;
// DCORE0_EDMA0_QM_CP_FENCE1_RDATA
pub const DCORE0_EDMA0_QM_CP_FENCE1_RDATA_INC_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_FENCE1_RDATA_INC_VAL_MASK: c_uint = 0xF;
// DCORE0_EDMA0_QM_CP_FENCE2_RDATA
pub const DCORE0_EDMA0_QM_CP_FENCE2_RDATA_INC_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_FENCE2_RDATA_INC_VAL_MASK: c_uint = 0xF;
// DCORE0_EDMA0_QM_CP_FENCE3_RDATA
pub const DCORE0_EDMA0_QM_CP_FENCE3_RDATA_INC_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_FENCE3_RDATA_INC_VAL_MASK: c_uint = 0xF;
// DCORE0_EDMA0_QM_CP_FENCE0_CNT
pub const DCORE0_EDMA0_QM_CP_FENCE0_CNT_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_FENCE0_CNT_VAL_MASK: c_uint = 0x3FFF;
// DCORE0_EDMA0_QM_CP_FENCE1_CNT
pub const DCORE0_EDMA0_QM_CP_FENCE1_CNT_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_FENCE1_CNT_VAL_MASK: c_uint = 0x3FFF;
// DCORE0_EDMA0_QM_CP_FENCE2_CNT
pub const DCORE0_EDMA0_QM_CP_FENCE2_CNT_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_FENCE2_CNT_VAL_MASK: c_uint = 0x3FFF;
// DCORE0_EDMA0_QM_CP_FENCE3_CNT
pub const DCORE0_EDMA0_QM_CP_FENCE3_CNT_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_FENCE3_CNT_VAL_MASK: c_uint = 0x3FFF;
// DCORE0_EDMA0_QM_CP_BARRIER_CFG
pub const DCORE0_EDMA0_QM_CP_BARRIER_CFG_EBGUARD_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_BARRIER_CFG_EBGUARD_MASK: c_uint = 0xFFF;
pub const DCORE0_EDMA0_QM_CP_BARRIER_CFG_RBGUARD_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_CP_BARRIER_CFG_RBGUARD_MASK: c_uint = 0xF0000;
// DCORE0_EDMA0_QM_CP_LDMA_SRC_BASE_LO_OFFSET
pub const DCORE0_EDMA0_QM_CP_LDMA_SRC_BASE_LO_OFFSET_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_LDMA_SRC_BASE_LO_OFFSET_VAL_MASK: c_uint = 0xFFFF;
// DCORE0_EDMA0_QM_CP_LDMA_DST_BASE_LO_OFFSET
pub const DCORE0_EDMA0_QM_CP_LDMA_DST_BASE_LO_OFFSET_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_LDMA_DST_BASE_LO_OFFSET_VAL_MASK: c_uint = 0xFFFF;
// DCORE0_EDMA0_QM_CP_LDMA_TSIZE_OFFSET
pub const DCORE0_EDMA0_QM_CP_LDMA_TSIZE_OFFSET_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_LDMA_TSIZE_OFFSET_VAL_MASK: c_uint = 0xFFFF;
// DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_0
pub const DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_0_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_0_VAL_MASK: c_uint = 0xFFFF;
// DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_1
pub const DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_1_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_1_VAL_MASK: c_uint = 0xFFFF;
// DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_2
pub const DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_2_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_2_VAL_MASK: c_uint = 0xFFFF;
// DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_3
pub const DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_3_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_3_VAL_MASK: c_uint = 0xFFFF;
// DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_4
pub const DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_4_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_CQ_PTR_LO_OFFSET_4_VAL_MASK: c_uint = 0xFFFF;
// DCORE0_EDMA0_QM_CP_STS
pub const DCORE0_EDMA0_QM_CP_STS_MSG_INFLIGHT_CNT_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_STS_MSG_INFLIGHT_CNT_MASK: c_uint = 0xFF;
pub const DCORE0_EDMA0_QM_CP_STS_ERDY_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_CP_STS_ERDY_MASK: c_uint = 0x100;
pub const DCORE0_EDMA0_QM_CP_STS_SWITCH_EN_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_CP_STS_SWITCH_EN_MASK: c_uint = 0x200;
pub const DCORE0_EDMA0_QM_CP_STS_MRDY_SHIFT: c_int = 10;
pub const DCORE0_EDMA0_QM_CP_STS_MRDY_MASK: c_uint = 0x400;
pub const DCORE0_EDMA0_QM_CP_STS_SW_STOP_SHIFT: c_int = 11;
pub const DCORE0_EDMA0_QM_CP_STS_SW_STOP_MASK: c_uint = 0x800;
pub const DCORE0_EDMA0_QM_CP_STS_FENCE_ID_SHIFT: c_int = 12;
pub const DCORE0_EDMA0_QM_CP_STS_FENCE_ID_MASK: c_uint = 0x3000;
pub const DCORE0_EDMA0_QM_CP_STS_FENCE_IN_PROGRESS_SHIFT: c_int = 14;
pub const DCORE0_EDMA0_QM_CP_STS_FENCE_IN_PROGRESS_MASK: c_uint = 0x4000;
pub const DCORE0_EDMA0_QM_CP_STS_FENCE_TARGET_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_CP_STS_FENCE_TARGET_MASK: c_uint = 0x3FFF0000;
pub const DCORE0_EDMA0_QM_CP_STS_CUR_CQ_SHIFT: c_int = 30;
pub const DCORE0_EDMA0_QM_CP_STS_CUR_CQ_MASK: c_uint = 0x40000000;
// DCORE0_EDMA0_QM_CP_CURRENT_INST_LO
pub const DCORE0_EDMA0_QM_CP_CURRENT_INST_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_CURRENT_INST_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_CURRENT_INST_HI
pub const DCORE0_EDMA0_QM_CP_CURRENT_INST_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_CURRENT_INST_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_PRED
pub const DCORE0_EDMA0_QM_CP_PRED_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_PRED_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_PRED_UPEN
pub const DCORE0_EDMA0_QM_CP_PRED_UPEN_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_PRED_UPEN_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_DBG_0
pub const DCORE0_EDMA0_QM_CP_DBG_0_CS_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_DBG_0_CS_MASK: c_uint = 0x1F;
pub const DCORE0_EDMA0_QM_CP_DBG_0_EB_CNT_NOT_ZERO_SHIFT: c_int = 5;
pub const DCORE0_EDMA0_QM_CP_DBG_0_EB_CNT_NOT_ZERO_MASK: c_uint = 0x20;
pub const DCORE0_EDMA0_QM_CP_DBG_0_BULK_CNT_NOT_ZERO_SHIFT: c_int = 6;
pub const DCORE0_EDMA0_QM_CP_DBG_0_BULK_CNT_NOT_ZERO_MASK: c_uint = 0x40;
pub const DCORE0_EDMA0_QM_CP_DBG_0_MREB_STALL_SHIFT: c_int = 7;
pub const DCORE0_EDMA0_QM_CP_DBG_0_MREB_STALL_MASK: c_uint = 0x80;
pub const DCORE0_EDMA0_QM_CP_DBG_0_STALL_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_CP_DBG_0_STALL_MASK: c_uint = 0x100;
// DCORE0_EDMA0_QM_CP_CPDMA_UP_CRED
pub const DCORE0_EDMA0_QM_CP_CPDMA_UP_CRED_TH_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_CPDMA_UP_CRED_TH_MASK: c_uint = 0x3;
pub const DCORE0_EDMA0_QM_CP_CPDMA_UP_CRED_VAL_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_CP_CPDMA_UP_CRED_VAL_MASK: c_uint = 0x300;
// DCORE0_EDMA0_QM_CP_IN_DATA_LO
pub const DCORE0_EDMA0_QM_CP_IN_DATA_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_IN_DATA_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_IN_DATA_HI
pub const DCORE0_EDMA0_QM_CP_IN_DATA_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_IN_DATA_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQC_HBW_BASE_LO
pub const DCORE0_EDMA0_QM_PQC_HBW_BASE_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQC_HBW_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQC_HBW_BASE_HI
pub const DCORE0_EDMA0_QM_PQC_HBW_BASE_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQC_HBW_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQC_SIZE
pub const DCORE0_EDMA0_QM_PQC_SIZE_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQC_SIZE_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQC_PI
pub const DCORE0_EDMA0_QM_PQC_PI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQC_PI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQC_LBW_WDATA
pub const DCORE0_EDMA0_QM_PQC_LBW_WDATA_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQC_LBW_WDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQC_LBW_BASE_LO
pub const DCORE0_EDMA0_QM_PQC_LBW_BASE_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQC_LBW_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQC_LBW_BASE_HI
pub const DCORE0_EDMA0_QM_PQC_LBW_BASE_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQC_LBW_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PQC_CFG
pub const DCORE0_EDMA0_QM_PQC_CFG_EN_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQC_CFG_EN_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_PQC_CFG_DIRECT_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_PQC_CFG_DIRECT_MASK: c_uint = 0x10;
// DCORE0_EDMA0_QM_PQC_SECURE_PUSH_IND
pub const DCORE0_EDMA0_QM_PQC_SECURE_PUSH_IND_CP_NUM_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQC_SECURE_PUSH_IND_CP_NUM_MASK: c_uint = 0x3;
// DCORE0_EDMA0_QM_ARB_MASK
pub const DCORE0_EDMA0_QM_ARB_MASK_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_MASK_VAL_MASK: c_uint = 0xF;
// DCORE0_EDMA0_QM_ARB_CFG_0
pub const DCORE0_EDMA0_QM_ARB_CFG_0_PRIO_TYPE_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_CFG_0_PRIO_TYPE_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_ARB_CFG_0_IS_MASTER_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_ARB_CFG_0_IS_MASTER_MASK: c_uint = 0x10;
pub const DCORE0_EDMA0_QM_ARB_CFG_0_EN_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_ARB_CFG_0_EN_MASK: c_uint = 0x100;
pub const DCORE0_EDMA0_QM_ARB_CFG_0_MST_MSG_NOSTALL_SHIFT: c_int = 9;
pub const DCORE0_EDMA0_QM_ARB_CFG_0_MST_MSG_NOSTALL_MASK: c_uint = 0x200;
// DCORE0_EDMA0_QM_ARB_CHOICE_Q_PUSH
pub const DCORE0_EDMA0_QM_ARB_CHOICE_Q_PUSH_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_CHOICE_Q_PUSH_VAL_MASK: c_uint = 0x3;
// DCORE0_EDMA0_QM_ARB_WRR_WEIGHT
pub const DCORE0_EDMA0_QM_ARB_WRR_WEIGHT_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_WRR_WEIGHT_VAL_MASK: c_uint = 0xFF;
// DCORE0_EDMA0_QM_ARB_CFG_1
pub const DCORE0_EDMA0_QM_ARB_CFG_1_CLR_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_CFG_1_CLR_MASK: c_uint = 0x1;
// DCORE0_EDMA0_QM_ARB_MST_AVAIL_CRED
pub const DCORE0_EDMA0_QM_ARB_MST_AVAIL_CRED_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_MST_AVAIL_CRED_VAL_MASK: c_uint = 0x7F;
// DCORE0_EDMA0_QM_ARB_MST_CRED_INC
pub const DCORE0_EDMA0_QM_ARB_MST_CRED_INC_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_MST_CRED_INC_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARB_MST_CHOICE_PUSH_OFST
pub const DCORE0_EDMA0_QM_ARB_MST_CHOICE_PUSH_OFST_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_MST_CHOICE_PUSH_OFST_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARB_SLV_MASTER_INC_CRED_OFST
pub const DCORE0_EDMA0_QM_ARB_SLV_MASTER_INC_CRED_OFST_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_SLV_MASTER_INC_CRED_OFST_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARB_MST_SLAVE_EN
pub const DCORE0_EDMA0_QM_ARB_MST_SLAVE_EN_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_MST_SLAVE_EN_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARB_MST_SLAVE_EN_1
pub const DCORE0_EDMA0_QM_ARB_MST_SLAVE_EN_1_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_MST_SLAVE_EN_1_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARB_SLV_CHOICE_WDT
pub const DCORE0_EDMA0_QM_ARB_SLV_CHOICE_WDT_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_SLV_CHOICE_WDT_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARB_SLV_ID
pub const DCORE0_EDMA0_QM_ARB_SLV_ID_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_SLV_ID_VAL_MASK: c_uint = 0x7F;
// DCORE0_EDMA0_QM_ARB_MST_QUIET_PER
pub const DCORE0_EDMA0_QM_ARB_MST_QUIET_PER_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_MST_QUIET_PER_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARB_MSG_MAX_INFLIGHT
pub const DCORE0_EDMA0_QM_ARB_MSG_MAX_INFLIGHT_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_MSG_MAX_INFLIGHT_VAL_MASK: c_uint = 0x3F;
// DCORE0_EDMA0_QM_ARB_BASE_LO
pub const DCORE0_EDMA0_QM_ARB_BASE_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARB_BASE_HI
pub const DCORE0_EDMA0_QM_ARB_BASE_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARB_STATE_STS
pub const DCORE0_EDMA0_QM_ARB_STATE_STS_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_STATE_STS_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARB_CHOICE_FULLNESS_STS
pub const DCORE0_EDMA0_QM_ARB_CHOICE_FULLNESS_STS_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_CHOICE_FULLNESS_STS_VAL_MASK: c_uint = 0x7F;
// DCORE0_EDMA0_QM_ARB_MSG_STS
pub const DCORE0_EDMA0_QM_ARB_MSG_STS_FULL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_MSG_STS_FULL_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_ARB_MSG_STS_NO_INFLIGHT_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_ARB_MSG_STS_NO_INFLIGHT_MASK: c_uint = 0x2;
// DCORE0_EDMA0_QM_ARB_SLV_CHOICE_Q_HEAD
pub const DCORE0_EDMA0_QM_ARB_SLV_CHOICE_Q_HEAD_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_SLV_CHOICE_Q_HEAD_VAL_MASK: c_uint = 0x3;
// DCORE0_EDMA0_QM_ARB_ERR_CAUSE
pub const DCORE0_EDMA0_QM_ARB_ERR_CAUSE_CHOICE_OVF_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_ERR_CAUSE_CHOICE_OVF_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_ARB_ERR_CAUSE_CHOICE_WDT_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_ARB_ERR_CAUSE_CHOICE_WDT_MASK: c_uint = 0x2;
pub const DCORE0_EDMA0_QM_ARB_ERR_CAUSE_AXI_LBW_ERR_SHIFT: c_int = 2;
pub const DCORE0_EDMA0_QM_ARB_ERR_CAUSE_AXI_LBW_ERR_MASK: c_uint = 0x4;
// DCORE0_EDMA0_QM_ARB_ERR_MSG_EN
pub const DCORE0_EDMA0_QM_ARB_ERR_MSG_EN_CHOICE_OVF_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_ERR_MSG_EN_CHOICE_OVF_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_ARB_ERR_MSG_EN_CHOICE_WDT_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_ARB_ERR_MSG_EN_CHOICE_WDT_MASK: c_uint = 0x2;
pub const DCORE0_EDMA0_QM_ARB_ERR_MSG_EN_AXI_LBW_ERR_SHIFT: c_int = 2;
pub const DCORE0_EDMA0_QM_ARB_ERR_MSG_EN_AXI_LBW_ERR_MASK: c_uint = 0x4;
// DCORE0_EDMA0_QM_ARB_ERR_STS_DRP
pub const DCORE0_EDMA0_QM_ARB_ERR_STS_DRP_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_ERR_STS_DRP_VAL_MASK: c_uint = 0x3;
// DCORE0_EDMA0_QM_ARB_MST_CRED_STS
pub const DCORE0_EDMA0_QM_ARB_MST_CRED_STS_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_MST_CRED_STS_VAL_MASK: c_uint = 0x7F;
pub const DCORE0_EDMA0_QM_ARB_MST_CRED_STS_IDX_SHIFT: c_int = 24;
pub const DCORE0_EDMA0_QM_ARB_MST_CRED_STS_IDX_MASK: c_uint = 0x1F000000;
// DCORE0_EDMA0_QM_ARB_MST_CRED_STS_1
pub const DCORE0_EDMA0_QM_ARB_MST_CRED_STS_1_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARB_MST_CRED_STS_1_VAL_MASK: c_uint = 0x7F;
pub const DCORE0_EDMA0_QM_ARB_MST_CRED_STS_1_IDX_SHIFT: c_int = 24;
pub const DCORE0_EDMA0_QM_ARB_MST_CRED_STS_1_IDX_MASK: c_uint = 0x1F000000;
// DCORE0_EDMA0_QM_CSMR_STRICT_PRIO_CFG
pub const DCORE0_EDMA0_QM_CSMR_STRICT_PRIO_CFG_ARB_TYPE_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CSMR_STRICT_PRIO_CFG_ARB_TYPE_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_CSMR_STRICT_PRIO_CFG_PER_ENTRY_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_CSMR_STRICT_PRIO_CFG_PER_ENTRY_MASK: c_uint = 0x10;
// DCORE0_EDMA0_QM_ARC_CQ_CFG0
pub const DCORE0_EDMA0_QM_ARC_CQ_CFG0_IF_B2B_EN_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_CFG0_IF_B2B_EN_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_ARC_CQ_CFG0_IF_MSG_EN_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_ARC_CQ_CFG0_IF_MSG_EN_MASK: c_uint = 0x2;
pub const DCORE0_EDMA0_QM_ARC_CQ_CFG0_CTL_MSG_EN_SHIFT: c_int = 2;
pub const DCORE0_EDMA0_QM_ARC_CQ_CFG0_CTL_MSG_EN_MASK: c_uint = 0x4;
// DCORE0_EDMA0_QM_ARC_CQ_CFG1
pub const DCORE0_EDMA0_QM_ARC_CQ_CFG1_CREDIT_LIM_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_CFG1_CREDIT_LIM_MASK: c_uint = 0xFF;
pub const DCORE0_EDMA0_QM_ARC_CQ_CFG1_MAX_INFLIGHT_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_ARC_CQ_CFG1_MAX_INFLIGHT_MASK: c_uint = 0xFF0000;
// DCORE0_EDMA0_QM_ARC_CQ_PTR_LO
pub const DCORE0_EDMA0_QM_ARC_CQ_PTR_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_PTR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_CQ_PTR_HI
pub const DCORE0_EDMA0_QM_ARC_CQ_PTR_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_PTR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_CQ_TSIZE
pub const DCORE0_EDMA0_QM_ARC_CQ_TSIZE_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_TSIZE_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_CQ_CTL
pub const DCORE0_EDMA0_QM_ARC_CQ_CTL_UP_SHIFT: c_int = 28;
pub const DCORE0_EDMA0_QM_ARC_CQ_CTL_UP_MASK: c_uint = 0xF0000000;
// DCORE0_EDMA0_QM_ARC_CQ_IFIFO_STS
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_STS_CNT_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_STS_CNT_MASK: c_uint = 0x7;
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_STS_RDY_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_STS_RDY_MASK: c_uint = 0x10;
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_STS_CTL_STALL_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_STS_CTL_STALL_MASK: c_uint = 0x100;
// DCORE0_EDMA0_QM_ARC_CQ_STS0
pub const DCORE0_EDMA0_QM_ARC_CQ_STS0_CREDIT_CNT_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_STS0_CREDIT_CNT_MASK: c_uint = 0xFF;
pub const DCORE0_EDMA0_QM_ARC_CQ_STS0_FREE_CNT_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_ARC_CQ_STS0_FREE_CNT_MASK: c_uint = 0xFF00;
pub const DCORE0_EDMA0_QM_ARC_CQ_STS0_INFLIGHT_CNT_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_ARC_CQ_STS0_INFLIGHT_CNT_MASK: c_uint = 0xFF0000;
// DCORE0_EDMA0_QM_ARC_CQ_STS1
pub const DCORE0_EDMA0_QM_ARC_CQ_STS1_BUF_EMPTY_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_STS1_BUF_EMPTY_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_ARC_CQ_STS1_BUSY_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_ARC_CQ_STS1_BUSY_MASK: c_uint = 0x2;
// DCORE0_EDMA0_QM_ARC_CQ_TSIZE_STS
pub const DCORE0_EDMA0_QM_ARC_CQ_TSIZE_STS_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_TSIZE_STS_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_CQ_PTR_LO_STS
pub const DCORE0_EDMA0_QM_ARC_CQ_PTR_LO_STS_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_PTR_LO_STS_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_CQ_PTR_HI_STS
pub const DCORE0_EDMA0_QM_ARC_CQ_PTR_HI_STS_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_PTR_HI_STS_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_WR_ARC_ADDR_HI
pub const DCORE0_EDMA0_QM_CP_WR_ARC_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_WR_ARC_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_WR_ARC_ADDR_LO
pub const DCORE0_EDMA0_QM_CP_WR_ARC_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_WR_ARC_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_CQ_IFIFO_MSG_BASE_HI
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_MSG_BASE_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_MSG_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_CQ_IFIFO_MSG_BASE_LO
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_MSG_BASE_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_MSG_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_CQ_CTL_MSG_BASE_HI
pub const DCORE0_EDMA0_QM_ARC_CQ_CTL_MSG_BASE_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_CTL_MSG_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_CQ_CTL_MSG_BASE_LO
pub const DCORE0_EDMA0_QM_ARC_CQ_CTL_MSG_BASE_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_CTL_MSG_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_IFIFO_MSG_BASE_HI
pub const DCORE0_EDMA0_QM_CQ_IFIFO_MSG_BASE_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_IFIFO_MSG_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_IFIFO_MSG_BASE_LO
pub const DCORE0_EDMA0_QM_CQ_IFIFO_MSG_BASE_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_IFIFO_MSG_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_CTL_MSG_BASE_HI
pub const DCORE0_EDMA0_QM_CQ_CTL_MSG_BASE_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_CTL_MSG_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_CTL_MSG_BASE_LO
pub const DCORE0_EDMA0_QM_CQ_CTL_MSG_BASE_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_CTL_MSG_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ADDR_OVRD
pub const DCORE0_EDMA0_QM_ADDR_OVRD_IDX_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ADDR_OVRD_IDX_MASK: c_uint = 0xFF;
// DCORE0_EDMA0_QM_CQ_IFIFO_CI
pub const DCORE0_EDMA0_QM_CQ_IFIFO_CI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_IFIFO_CI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_CQ_IFIFO_CI
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_CI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_IFIFO_CI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CQ_CTL_CI
pub const DCORE0_EDMA0_QM_CQ_CTL_CI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CQ_CTL_CI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_CQ_CTL_CI
pub const DCORE0_EDMA0_QM_ARC_CQ_CTL_CI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_CQ_CTL_CI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_CFG
pub const DCORE0_EDMA0_QM_CP_CFG_SWITCH_EN_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_CFG_SWITCH_EN_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_CP_CFG_SWITCH_WD_EN_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_CP_CFG_SWITCH_WD_EN_MASK: c_uint = 0x2;
// DCORE0_EDMA0_QM_CP_EXT_SWITCH
pub const DCORE0_EDMA0_QM_CP_EXT_SWITCH_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_EXT_SWITCH_VAL_MASK: c_uint = 0x1;
// DCORE0_EDMA0_QM_CP_SWITCH_WD_SET
pub const DCORE0_EDMA0_QM_CP_SWITCH_WD_SET_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_SWITCH_WD_SET_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_CP_SWITCH_WD
pub const DCORE0_EDMA0_QM_CP_SWITCH_WD_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_CP_SWITCH_WD_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_LB_ADDR_BASE_LO
pub const DCORE0_EDMA0_QM_ARC_LB_ADDR_BASE_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_LB_ADDR_BASE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_LB_ADDR_BASE_HI
pub const DCORE0_EDMA0_QM_ARC_LB_ADDR_BASE_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_LB_ADDR_BASE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ENGINE_BASE_ADDR_HI
pub const DCORE0_EDMA0_QM_ENGINE_BASE_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ENGINE_BASE_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ENGINE_BASE_ADDR_LO
pub const DCORE0_EDMA0_QM_ENGINE_BASE_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ENGINE_BASE_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ENGINE_ADDR_RANGE_SIZE
pub const DCORE0_EDMA0_QM_ENGINE_ADDR_RANGE_SIZE_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ENGINE_ADDR_RANGE_SIZE_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_QM_ARC_AUX_BASE_ADDR_HI
pub const DCORE0_EDMA0_QM_QM_ARC_AUX_BASE_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_QM_ARC_AUX_BASE_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_QM_ARC_AUX_BASE_ADDR_LO
pub const DCORE0_EDMA0_QM_QM_ARC_AUX_BASE_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_QM_ARC_AUX_BASE_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_QM_BASE_ADDR_HI
pub const DCORE0_EDMA0_QM_QM_BASE_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_QM_BASE_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_QM_BASE_ADDR_LO
pub const DCORE0_EDMA0_QM_QM_BASE_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_QM_BASE_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_ARC_PQC_SECURE_PUSH_IND
pub const DCORE0_EDMA0_QM_ARC_PQC_SECURE_PUSH_IND_CP_NUM_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_ARC_PQC_SECURE_PUSH_IND_CP_NUM_MASK: c_uint = 0x3;
// DCORE0_EDMA0_QM_PQC_STS_0
pub const DCORE0_EDMA0_QM_PQC_STS_0_COMP_DATA_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQC_STS_0_COMP_DATA_MASK: c_uint = 0xFFFF;
pub const DCORE0_EDMA0_QM_PQC_STS_0_COMP_OFST_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_PQC_STS_0_COMP_OFST_MASK: c_uint = 0xFFFF0000;
// DCORE0_EDMA0_QM_PQC_STS_1
pub const DCORE0_EDMA0_QM_PQC_STS_1_COMP_FIFO_CNTR_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PQC_STS_1_COMP_FIFO_CNTR_MASK: c_uint = 0xF;
pub const DCORE0_EDMA0_QM_PQC_STS_1_COMP_FIFO_EMPTY_SHIFT: c_int = 4;
pub const DCORE0_EDMA0_QM_PQC_STS_1_COMP_FIFO_EMPTY_MASK: c_uint = 0x10;
pub const DCORE0_EDMA0_QM_PQC_STS_1_COMP_FIFO_FULL_SHIFT: c_int = 5;
pub const DCORE0_EDMA0_QM_PQC_STS_1_COMP_FIFO_FULL_MASK: c_uint = 0x20;
// DCORE0_EDMA0_QM_SEI_STATUS
pub const DCORE0_EDMA0_QM_SEI_STATUS_QM_INT_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_SEI_STATUS_QM_INT_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_SEI_STATUS_ARC_INT_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_SEI_STATUS_ARC_INT_MASK: c_uint = 0x2;
// DCORE0_EDMA0_QM_SEI_MASK
pub const DCORE0_EDMA0_QM_SEI_MASK_QM_INT_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_SEI_MASK_QM_INT_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_SEI_MASK_ARC_INT_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_SEI_MASK_ARC_INT_MASK: c_uint = 0x2;
// DCORE0_EDMA0_QM_GLBL_ERR_ADDR_LO
pub const DCORE0_EDMA0_QM_GLBL_ERR_ADDR_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_ERR_ADDR_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_GLBL_ERR_ADDR_HI
pub const DCORE0_EDMA0_QM_GLBL_ERR_ADDR_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_ERR_ADDR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_GLBL_ERR_WDATA
pub const DCORE0_EDMA0_QM_GLBL_ERR_WDATA_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_GLBL_ERR_WDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_L2H_MASK_LO
pub const DCORE0_EDMA0_QM_L2H_MASK_LO_VAL_SHIFT: c_int = 20;
pub const DCORE0_EDMA0_QM_L2H_MASK_LO_VAL_MASK: c_uint = 0xFFF00000;
// DCORE0_EDMA0_QM_L2H_MASK_HI
pub const DCORE0_EDMA0_QM_L2H_MASK_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_L2H_MASK_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_L2H_CMPR_LO
pub const DCORE0_EDMA0_QM_L2H_CMPR_LO_VAL_SHIFT: c_int = 20;
pub const DCORE0_EDMA0_QM_L2H_CMPR_LO_VAL_MASK: c_uint = 0xFFF00000;
// DCORE0_EDMA0_QM_L2H_CMPR_HI
pub const DCORE0_EDMA0_QM_L2H_CMPR_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_L2H_CMPR_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_LOCAL_RANGE_BASE
pub const DCORE0_EDMA0_QM_LOCAL_RANGE_BASE_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_LOCAL_RANGE_BASE_VAL_MASK: c_uint = 0xFFFF;
// DCORE0_EDMA0_QM_LOCAL_RANGE_SIZE
pub const DCORE0_EDMA0_QM_LOCAL_RANGE_SIZE_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_LOCAL_RANGE_SIZE_VAL_MASK: c_uint = 0xFFFF;
// DCORE0_EDMA0_QM_HBW_RD_RATE_LIM_CFG_1
pub const DCORE0_EDMA0_QM_HBW_RD_RATE_LIM_CFG_1_TOUT_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_HBW_RD_RATE_LIM_CFG_1_TOUT_MASK: c_uint = 0xFF;
pub const DCORE0_EDMA0_QM_HBW_RD_RATE_LIM_CFG_1_EN_SHIFT: c_int = 31;
pub const DCORE0_EDMA0_QM_HBW_RD_RATE_LIM_CFG_1_EN_MASK: c_uint = 0x80000000;
// DCORE0_EDMA0_QM_LBW_WR_RATE_LIM_CFG_0
pub const DCORE0_EDMA0_QM_LBW_WR_RATE_LIM_CFG_0_RST_TOKEN_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_LBW_WR_RATE_LIM_CFG_0_RST_TOKEN_MASK: c_uint = 0xFF;
pub const DCORE0_EDMA0_QM_LBW_WR_RATE_LIM_CFG_0_SAT_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_LBW_WR_RATE_LIM_CFG_0_SAT_MASK: c_uint = 0xFF0000;
// DCORE0_EDMA0_QM_LBW_WR_RATE_LIM_CFG_1
pub const DCORE0_EDMA0_QM_LBW_WR_RATE_LIM_CFG_1_TOUT_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_LBW_WR_RATE_LIM_CFG_1_TOUT_MASK: c_uint = 0xFF;
pub const DCORE0_EDMA0_QM_LBW_WR_RATE_LIM_CFG_1_EN_SHIFT: c_int = 31;
pub const DCORE0_EDMA0_QM_LBW_WR_RATE_LIM_CFG_1_EN_MASK: c_uint = 0x80000000;
// DCORE0_EDMA0_QM_HBW_RD_RATE_LIM_CFG_0
pub const DCORE0_EDMA0_QM_HBW_RD_RATE_LIM_CFG_0_RST_TOKEN_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_HBW_RD_RATE_LIM_CFG_0_RST_TOKEN_MASK: c_uint = 0xFF;
pub const DCORE0_EDMA0_QM_HBW_RD_RATE_LIM_CFG_0_SAT_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_HBW_RD_RATE_LIM_CFG_0_SAT_MASK: c_uint = 0xFF0000;
// DCORE0_EDMA0_QM_IND_GW_APB_CFG
pub const DCORE0_EDMA0_QM_IND_GW_APB_CFG_ADDR_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_IND_GW_APB_CFG_ADDR_MASK: c_uint = 0x7FFFFFFF;
pub const DCORE0_EDMA0_QM_IND_GW_APB_CFG_CMD_SHIFT: c_int = 31;
pub const DCORE0_EDMA0_QM_IND_GW_APB_CFG_CMD_MASK: c_uint = 0x80000000;
// DCORE0_EDMA0_QM_IND_GW_APB_WDATA
pub const DCORE0_EDMA0_QM_IND_GW_APB_WDATA_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_IND_GW_APB_WDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_IND_GW_APB_RDATA
pub const DCORE0_EDMA0_QM_IND_GW_APB_RDATA_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_IND_GW_APB_RDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_IND_GW_APB_STATUS
pub const DCORE0_EDMA0_QM_IND_GW_APB_STATUS_RDY_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_IND_GW_APB_STATUS_RDY_MASK: c_uint = 0x1;
pub const DCORE0_EDMA0_QM_IND_GW_APB_STATUS_ERR_SHIFT: c_int = 1;
pub const DCORE0_EDMA0_QM_IND_GW_APB_STATUS_ERR_MASK: c_uint = 0x2;
// DCORE0_EDMA0_QM_PERF_CNT_FREE_LO
pub const DCORE0_EDMA0_QM_PERF_CNT_FREE_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PERF_CNT_FREE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PERF_CNT_FREE_HI
pub const DCORE0_EDMA0_QM_PERF_CNT_FREE_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PERF_CNT_FREE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PERF_CNT_IDLE_LO
pub const DCORE0_EDMA0_QM_PERF_CNT_IDLE_LO_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PERF_CNT_IDLE_LO_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PERF_CNT_IDLE_HI
pub const DCORE0_EDMA0_QM_PERF_CNT_IDLE_HI_VAL_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PERF_CNT_IDLE_HI_VAL_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_EDMA0_QM_PERF_CNT_CFG
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_PQ_MASK_SHIFT: c_int = 0;
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_PQ_MASK_MASK: c_uint = 0xF;
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_CQ_MASK_SHIFT: c_int = 8;
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_CQ_MASK_MASK: c_uint = 0x1F00;
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_CP_MASK_SHIFT: c_int = 16;
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_CP_MASK_MASK: c_uint = 0x1F0000;
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_AGENT_MASK_SHIFT: c_int = 24;
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_AGENT_MASK_MASK: c_uint = 0x1000000;
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_EN_FREE_SHIFT: c_int = 30;
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_EN_FREE_MASK: c_uint = 0x40000000;
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_EN_IDLE_SHIFT: c_int = 31;
pub const DCORE0_EDMA0_QM_PERF_CNT_CFG_EN_IDLE_MASK: c_uint = 0x80000000;
