//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/gaudi2/asic_reg/dcore0_hmmu0_mmu_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2020 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// DCORE0_HMMU0_MMU
// (Prototype: MMU)
//
// DCORE0_HMMU0_MMU_MMU_ENABLE
pub const DCORE0_HMMU0_MMU_MMU_ENABLE_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MMU_ENABLE_R_MASK: c_uint = 0x1;
// DCORE0_HMMU0_MMU_FORCE_ORDERING
pub const DCORE0_HMMU0_MMU_FORCE_ORDERING_WEAK_ORDERING_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_FORCE_ORDERING_WEAK_ORDERING_MASK: c_uint = 0x1;
pub const DCORE0_HMMU0_MMU_FORCE_ORDERING_STRONG_ORDERING_SHIFT: c_int = 1;
pub const DCORE0_HMMU0_MMU_FORCE_ORDERING_STRONG_ORDERING_MASK: c_uint = 0x2;
// DCORE0_HMMU0_MMU_FEATURE_ENABLE
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_VA_ORDERING_EN_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_VA_ORDERING_EN_MASK: c_uint = 0x1;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_CLEAN_LINK_LIST_SHIFT: c_int = 1;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_CLEAN_LINK_LIST_MASK: c_uint = 0x2;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_HOP_OFFSET_EN_SHIFT: c_int = 2;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_HOP_OFFSET_EN_MASK: c_uint = 0x4;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_OBI_ORDERING_EN_SHIFT: c_int = 3;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_OBI_ORDERING_EN_MASK: c_uint = 0x8;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_STRONG_ORDERING_READ_EN_SHIFT: c_int = 4;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_STRONG_ORDERING_READ_EN_MASK: c_uint = 0x10;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_TRACE_ENABLE_SHIFT: c_int = 5;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_TRACE_ENABLE_MASK: c_uint = 0x20;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_TRACE_EV_MMU_OR_STLB_SHIFT: c_int = 6;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_TRACE_EV_MMU_OR_STLB_MASK: c_uint = 0x40;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_TRACE_CLKH_EQUAL_CLKL_SHIFT: c_int = 7;
pub const DCORE0_HMMU0_MMU_FEATURE_ENABLE_TRACE_CLKH_EQUAL_CLKL_MASK: c_uint = 0x80;
// DCORE0_HMMU0_MMU_VA_ORDERING_MASK_38_7
pub const DCORE0_HMMU0_MMU_VA_ORDERING_MASK_38_7_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_VA_ORDERING_MASK_38_7_R_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_VA_ORDERING_MASK_64_39
pub const DCORE0_HMMU0_MMU_VA_ORDERING_MASK_64_39_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_VA_ORDERING_MASK_64_39_R_MASK: c_uint = 0x3FFFFFF;
// DCORE0_HMMU0_MMU_LOG2_DDR_SIZE
pub const DCORE0_HMMU0_MMU_LOG2_DDR_SIZE_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_LOG2_DDR_SIZE_R_MASK: c_uint = 0xFF;
// DCORE0_HMMU0_MMU_SCRAMBLER
pub const DCORE0_HMMU0_MMU_SCRAMBLER_ADDR_BIT_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_SCRAMBLER_ADDR_BIT_MASK: c_uint = 0x3F;
pub const DCORE0_HMMU0_MMU_SCRAMBLER_SINGLE_DDR_EN_SHIFT: c_int = 6;
pub const DCORE0_HMMU0_MMU_SCRAMBLER_SINGLE_DDR_EN_MASK: c_uint = 0x40;
pub const DCORE0_HMMU0_MMU_SCRAMBLER_SINGLE_DDR_ID_SHIFT: c_int = 7;
pub const DCORE0_HMMU0_MMU_SCRAMBLER_SINGLE_DDR_ID_MASK: c_uint = 0x80;
pub const DCORE0_HMMU0_MMU_SCRAMBLER_DDR_CH_LSB_BIT_LOCATION_SHIFT: c_int = 8;
pub const DCORE0_HMMU0_MMU_SCRAMBLER_DDR_CH_LSB_BIT_LOCATION_MASK: c_uint = 0x7F00;
// DCORE0_HMMU0_MMU_MEM_INIT_BUSY
pub const DCORE0_HMMU0_MMU_MEM_INIT_BUSY_DATA_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MEM_INIT_BUSY_DATA_MASK: c_uint = 0x3;
pub const DCORE0_HMMU0_MMU_MEM_INIT_BUSY_OBI0_SHIFT: c_int = 2;
pub const DCORE0_HMMU0_MMU_MEM_INIT_BUSY_OBI0_MASK: c_uint = 0x4;
pub const DCORE0_HMMU0_MMU_MEM_INIT_BUSY_OBI1_SHIFT: c_int = 3;
pub const DCORE0_HMMU0_MMU_MEM_INIT_BUSY_OBI1_MASK: c_uint = 0x8;
// DCORE0_HMMU0_MMU_SPI_SEI_MASK
pub const DCORE0_HMMU0_MMU_SPI_SEI_MASK_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_SPI_SEI_MASK_R_MASK: c_uint = 0x7FFFF;
// DCORE0_HMMU0_MMU_SPI_SEI_CAUSE
pub const DCORE0_HMMU0_MMU_SPI_SEI_CAUSE_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_SPI_SEI_CAUSE_R_MASK: c_uint = 0x7FFFF;
// DCORE0_HMMU0_MMU_PAGE_ERROR_CAPTURE
pub const DCORE0_HMMU0_MMU_PAGE_ERROR_CAPTURE_VA_63_32_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_PAGE_ERROR_CAPTURE_VA_63_32_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_PAGE_ERROR_CAPTURE_VA
pub const DCORE0_HMMU0_MMU_PAGE_ERROR_CAPTURE_VA_VA_31_0_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_PAGE_ERROR_CAPTURE_VA_VA_31_0_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_ACCESS_ERROR_CAPTURE
pub const DCORE0_HMMU0_MMU_ACCESS_ERROR_CAPTURE_VA_63_32_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_ACCESS_ERROR_CAPTURE_VA_63_32_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_ACCESS_ERROR_CAPTURE_VA
pub const DCORE0_HMMU0_MMU_ACCESS_ERROR_CAPTURE_VA_VA_31_0_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_ACCESS_ERROR_CAPTURE_VA_VA_31_0_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_ACCESS_PAGE_ERROR_VALID
pub const DCORE0_HMMU0_MMU_ACCESS_PAGE_ERROR_VALID_PAGE_ERR_VALID_ENTRY_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_ACCESS_PAGE_ERROR_VALID_PAGE_ERR_VALID_ENTRY_MASK: c_uint = 0x1;
pub const DCORE0_HMMU0_MMU_ACCESS_PAGE_ERROR_VALID_ACCESS_ERR_VALID_ENTRY_SHIFT: c_int = 1;
pub const DCORE0_HMMU0_MMU_ACCESS_PAGE_ERROR_VALID_ACCESS_ERR_VALID_ENTRY_MASK: c_uint = 0x2;
// DCORE0_HMMU0_MMU_INTERRUPT_CLR
pub const DCORE0_HMMU0_MMU_INTERRUPT_CLR_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_INTERRUPT_CLR_R_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_INTERRUPT_MASK
pub const DCORE0_HMMU0_MMU_INTERRUPT_MASK_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_INTERRUPT_MASK_R_MASK: c_uint = 0xFF;
// DCORE0_HMMU0_MMU_DBG_MEM_WRAP_RM
pub const DCORE0_HMMU0_MMU_DBG_MEM_WRAP_RM_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_DBG_MEM_WRAP_RM_R_MASK: c_uint = 0x3FFFFFFF;
// DCORE0_HMMU0_MMU_SPI_CAUSE_CLR
pub const DCORE0_HMMU0_MMU_SPI_CAUSE_CLR_CLR_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_SPI_CAUSE_CLR_CLR_MASK: c_uint = 0x1;
// DCORE0_HMMU0_MMU_PIPE_CREDIT
pub const DCORE0_HMMU0_MMU_PIPE_CREDIT_READ_CREDIT_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_PIPE_CREDIT_READ_CREDIT_MASK: c_uint = 0xF;
pub const DCORE0_HMMU0_MMU_PIPE_CREDIT_READ_FORCE_FULL_SHIFT: c_int = 7;
pub const DCORE0_HMMU0_MMU_PIPE_CREDIT_READ_FORCE_FULL_MASK: c_uint = 0x80;
pub const DCORE0_HMMU0_MMU_PIPE_CREDIT_WRITE_CREDIT_SHIFT: c_int = 8;
pub const DCORE0_HMMU0_MMU_PIPE_CREDIT_WRITE_CREDIT_MASK: c_uint = 0xF00;
pub const DCORE0_HMMU0_MMU_PIPE_CREDIT_WRITE_FORCE_FULL_SHIFT: c_int = 15;
pub const DCORE0_HMMU0_MMU_PIPE_CREDIT_WRITE_FORCE_FULL_MASK: c_uint = 0x8000;
// DCORE0_HMMU0_MMU_MMU_BYPASS
pub const DCORE0_HMMU0_MMU_MMU_BYPASS_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MMU_BYPASS_R_MASK: c_uint = 0x1;
// DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_HOP5_PAGE_SIZE_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_HOP5_PAGE_SIZE_MASK: c_uint = 0xF;
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_HOP4_PAGE_SIZE_SHIFT: c_int = 4;
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_HOP4_PAGE_SIZE_MASK: c_uint = 0xF0;
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_HOP3_PAGE_SIZE_SHIFT: c_int = 8;
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_HOP3_PAGE_SIZE_MASK: c_uint = 0xF00;
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_HOP2_PAGE_SIZE_SHIFT: c_int = 12;
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_HOP2_PAGE_SIZE_MASK: c_uint = 0xF000;
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_HOP1_PAGE_SIZE_SHIFT: c_int = 16;
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_HOP1_PAGE_SIZE_MASK: c_uint = 0xF0000;
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_CFG_8_BITS_HOP_MODE_EN_SHIFT: c_int = 20;
pub const DCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE_CFG_8_BITS_HOP_MODE_EN_MASK: c_uint = 0x100000;
// DCORE0_HMMU0_MMU_CORE_SEP_CACHE_RNG
pub const DCORE0_HMMU0_MMU_CORE_SEP_CACHE_RNG_CORE_SET_MASK_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_CORE_SEP_CACHE_RNG_CORE_SET_MASK_MASK: c_uint = 0x1FF;
pub const DCORE0_HMMU0_MMU_CORE_SEP_CACHE_RNG_CORE_SET_MIN_SHIFT: c_int = 10;
pub const DCORE0_HMMU0_MMU_CORE_SEP_CACHE_RNG_CORE_SET_MIN_MASK: c_uint = 0x7FC00;
pub const DCORE0_HMMU0_MMU_CORE_SEP_CACHE_RNG_CORE_SET_MAX_SHIFT: c_int = 20;
pub const DCORE0_HMMU0_MMU_CORE_SEP_CACHE_RNG_CORE_SET_MAX_MASK: c_uint = 0x1FF00000;
// DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_WRITE_CRED_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_WRITE_CRED_MASK: c_uint = 0x1FF;
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_READ_CRED_SHIFT: c_int = 9;
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_READ_CRED_MASK: c_uint = 0x3FE00;
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_TOTAL_SHIFT: c_int = 18;
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_TOTAL_MASK: c_uint = 0x7FC0000;
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_FORCE_FULL_WRITE_SHIFT: c_int = 27;
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_FORCE_FULL_WRITE_MASK: c_uint = 0x8000000;
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_FORCE_FULL_READ_SHIFT: c_int = 28;
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_FORCE_FULL_READ_MASK: c_uint = 0x10000000;
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_FORCE_FULL_TOTAL_SHIFT: c_int = 29;
pub const DCORE0_HMMU0_MMU_CORE_SEP_SLICE_CRDT_FORCE_FULL_TOTAL_MASK: c_uint = 0x20000000;
// DCORE0_HMMU0_MMU_TOTAL_SLICE_CREDIT
pub const DCORE0_HMMU0_MMU_TOTAL_SLICE_CREDIT_TOTAL_SHIFT: c_int = 18;
pub const DCORE0_HMMU0_MMU_TOTAL_SLICE_CREDIT_TOTAL_MASK: c_uint = 0x7FC0000;
pub const DCORE0_HMMU0_MMU_TOTAL_SLICE_CREDIT_FORCE_FULL_TOTAL_SHIFT: c_int = 29;
pub const DCORE0_HMMU0_MMU_TOTAL_SLICE_CREDIT_FORCE_FULL_TOTAL_MASK: c_uint = 0x20000000;
// DCORE0_HMMU0_MMU_PAGE_FAULT_ID_LSB
pub const DCORE0_HMMU0_MMU_PAGE_FAULT_ID_LSB_PAGE_FAULT_ID_31_0_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_PAGE_FAULT_ID_LSB_PAGE_FAULT_ID_31_0_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_PAGE_FAULT_ID_MSB
pub const DCORE0_HMMU0_MMU_PAGE_FAULT_ID_MSB_PAGE_FAULT_ID_42_32_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_PAGE_FAULT_ID_MSB_PAGE_FAULT_ID_42_32_MASK: c_uint = 0x7FF;
// DCORE0_HMMU0_MMU_PAGE_ACCESS_ID_LSB
pub const DCORE0_HMMU0_MMU_PAGE_ACCESS_ID_LSB_PAGE_ACCESS_ID_31_0_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_PAGE_ACCESS_ID_LSB_PAGE_ACCESS_ID_31_0_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_PAGE_ACCESS_ID_MSB
pub const DCORE0_HMMU0_MMU_PAGE_ACCESS_ID_MSB_PAGE_ACCESS_ID_42_32_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_PAGE_ACCESS_ID_MSB_PAGE_ACCESS_ID_42_32_MASK: c_uint = 0x7FF;
// DCORE0_HMMU0_MMU_DDR_RANGE_REG_ENABLE
pub const DCORE0_HMMU0_MMU_DDR_RANGE_REG_ENABLE_ENABLE_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_DDR_RANGE_REG_ENABLE_ENABLE_MASK: c_uint = 0x1;
// DCORE0_HMMU0_MMU_MMU_RR_SEC_MIN_63_32
pub const DCORE0_HMMU0_MMU_MMU_RR_SEC_MIN_63_32_SEC_MIN_63_32_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MMU_RR_SEC_MIN_63_32_SEC_MIN_63_32_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_MMU_RR_SEC_MIN_31_0
pub const DCORE0_HMMU0_MMU_MMU_RR_SEC_MIN_31_0_SEC_MIN_31_0_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MMU_RR_SEC_MIN_31_0_SEC_MIN_31_0_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_MMU_RR_SEC_MAX_63_32
pub const DCORE0_HMMU0_MMU_MMU_RR_SEC_MAX_63_32_SEC_MAX_63_32_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MMU_RR_SEC_MAX_63_32_SEC_MAX_63_32_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_MMU_RR_SEC_MAX_31_0
pub const DCORE0_HMMU0_MMU_MMU_RR_SEC_MAX_31_0_SEC_MAX_31_0_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MMU_RR_SEC_MAX_31_0_SEC_MAX_31_0_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_MMU_RR_PRIV_MIN_63_32
pub const DCORE0_HMMU0_MMU_MMU_RR_PRIV_MIN_63_32_PRIV_MIN_63_32_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MMU_RR_PRIV_MIN_63_32_PRIV_MIN_63_32_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_MMU_RR_PRIV_MIN_31_0
pub const DCORE0_HMMU0_MMU_MMU_RR_PRIV_MIN_31_0_PRIV_MIN_31_0_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MMU_RR_PRIV_MIN_31_0_PRIV_MIN_31_0_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_MMU_RR_PRIV_MAX_63_32
pub const DCORE0_HMMU0_MMU_MMU_RR_PRIV_MAX_63_32_PRIV_MAX_63_32_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MMU_RR_PRIV_MAX_63_32_PRIV_MAX_63_32_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_MMU_RR_PRIV_MAX_31_0
pub const DCORE0_HMMU0_MMU_MMU_RR_PRIV_MAX_31_0_PRIV_MAX_31_0_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MMU_RR_PRIV_MAX_31_0_PRIV_MAX_31_0_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_ILLEGAL_ADDR_WRITE_63_32
pub const DCORE0_HMMU0_MMU_ILLEGAL_ADDR_WRITE_63_32_ILLEGAL_ADDR_63_32_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_ILLEGAL_ADDR_WRITE_63_32_ILLEGAL_ADDR_63_32_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_ILLEGAL_ADDR_WRITE_31_0
pub const DCORE0_HMMU0_MMU_ILLEGAL_ADDR_WRITE_31_0_ILLEGAL_ADDR_31_0_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_ILLEGAL_ADDR_WRITE_31_0_ILLEGAL_ADDR_31_0_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_ILLEGAL_ADDR_READ_63_32
pub const DCORE0_HMMU0_MMU_ILLEGAL_ADDR_READ_63_32_ILLEGAL_ADDR_63_32_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_ILLEGAL_ADDR_READ_63_32_ILLEGAL_ADDR_63_32_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_ILLEGAL_ADDR_READ_31_0
pub const DCORE0_HMMU0_MMU_ILLEGAL_ADDR_READ_31_0_ILLEGAL_ADDR_31_0_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_ILLEGAL_ADDR_READ_31_0_ILLEGAL_ADDR_31_0_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_RAZWI_WRITE_VLD
pub const DCORE0_HMMU0_MMU_RAZWI_WRITE_VLD_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_RAZWI_WRITE_VLD_R_MASK: c_uint = 0x1;
// DCORE0_HMMU0_MMU_RAZWI_WRITE_ID_31_0
pub const DCORE0_HMMU0_MMU_RAZWI_WRITE_ID_31_0_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_RAZWI_WRITE_ID_31_0_R_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_RAZWI_WRITE_ID_42_32
pub const DCORE0_HMMU0_MMU_RAZWI_WRITE_ID_42_32_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_RAZWI_WRITE_ID_42_32_R_MASK: c_uint = 0x7FF;
// DCORE0_HMMU0_MMU_RAZWI_READ_VLD
pub const DCORE0_HMMU0_MMU_RAZWI_READ_VLD_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_RAZWI_READ_VLD_R_MASK: c_uint = 0x1;
// DCORE0_HMMU0_MMU_RAZWI_READ_ID_31_0
pub const DCORE0_HMMU0_MMU_RAZWI_READ_ID_31_0_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_RAZWI_READ_ID_31_0_R_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_RAZWI_READ_ID_42_32
pub const DCORE0_HMMU0_MMU_RAZWI_READ_ID_42_32_R_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_RAZWI_READ_ID_42_32_R_MASK: c_uint = 0x7FF;
// DCORE0_HMMU0_MMU_MMU_SRC_NUM
pub const DCORE0_HMMU0_MMU_MMU_SRC_NUM_OVERRIDE_SRC_NUM_EN_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_MMU_SRC_NUM_OVERRIDE_SRC_NUM_EN_MASK: c_uint = 0x1;
pub const DCORE0_HMMU0_MMU_MMU_SRC_NUM_SRC_NUM_SHIFT: c_int = 1;
pub const DCORE0_HMMU0_MMU_MMU_SRC_NUM_SRC_NUM_MASK: c_uint = 0x1E;
// DCORE0_HMMU0_MMU_RAZWI_ADDR_LSB
pub const DCORE0_HMMU0_MMU_RAZWI_ADDR_LSB_ADDR_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_RAZWI_ADDR_LSB_ADDR_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_HMMU0_MMU_RAZWI_ADDR_MSB
pub const DCORE0_HMMU0_MMU_RAZWI_ADDR_MSB_ADDR_SHIFT: c_int = 0;
pub const DCORE0_HMMU0_MMU_RAZWI_ADDR_MSB_ADDR_MASK: c_uint = 0xFFFFFFFF;
