//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/gaudi2/asic_reg/dcore0_mme_ctrl_lo_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2020 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// DCORE0_MME_CTRL_LO
// (Prototype: MME_CTRL_LO)
//
// DCORE0_MME_CTRL_LO_ARCH_STATUS
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_AGU_IN_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_AGU_IN_MASK: c_uint = 0x1F;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_EU_SHIFT: c_int = 5;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_EU_MASK: c_uint = 0x20;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_AP_SHIFT: c_int = 6;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_AP_MASK: c_uint = 0x40;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_AGU_COUT_SHIFT: c_int = 7;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_AGU_COUT_MASK: c_uint = 0x180;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_IN_EMPTY_SHIFT: c_int = 9;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_IN_EMPTY_MASK: c_uint = 0x3E00;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_AGU_COUT_SM_IDLE_SHIFT: c_int = 14;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_AGU_COUT_SM_IDLE_MASK: c_uint = 0xC000;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_WBC_AXI_IDLE_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_WBC_AXI_IDLE_MASK: c_uint = 0x30000;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_IN_AXI_IDLE_SHIFT: c_int = 18;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_SB_IN_AXI_IDLE_MASK: c_uint = 0x7C0000;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_ACCUM_FREE_SHIFT: c_int = 23;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_ACCUM_FREE_MASK: c_uint = 0x3800000;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_QM_IDLE_SHIFT: c_int = 30;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_QM_IDLE_MASK: c_uint = 0x40000000;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_QM_RDY_SHIFT: c_int = 31;
pub const DCORE0_MME_CTRL_LO_ARCH_STATUS_QM_RDY_MASK: c_uint = 0x80000000;
// DCORE0_MME_CTRL_LO_CMD
pub const DCORE0_MME_CTRL_LO_CMD_AGU_IN_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_CMD_AGU_IN_MASK: c_uint = 0x1F;
pub const DCORE0_MME_CTRL_LO_CMD_EU_SHIFT: c_int = 5;
pub const DCORE0_MME_CTRL_LO_CMD_EU_MASK: c_uint = 0x20;
pub const DCORE0_MME_CTRL_LO_CMD_AP_SHIFT: c_int = 6;
pub const DCORE0_MME_CTRL_LO_CMD_AP_MASK: c_uint = 0x40;
pub const DCORE0_MME_CTRL_LO_CMD_AGU_COUT_SHIFT: c_int = 7;
pub const DCORE0_MME_CTRL_LO_CMD_AGU_COUT_MASK: c_uint = 0x180;
pub const DCORE0_MME_CTRL_LO_CMD_COPY_AND_INC_SHIFT: c_int = 9;
pub const DCORE0_MME_CTRL_LO_CMD_COPY_AND_INC_MASK: c_uint = 0x200;
pub const DCORE0_MME_CTRL_LO_CMD_DESC_SEL_SHIFT: c_int = 10;
pub const DCORE0_MME_CTRL_LO_CMD_DESC_SEL_MASK: c_uint = 0xC00;
pub const DCORE0_MME_CTRL_LO_CMD_MASK_IDLE_IND_SHIFT: c_int = 12;
pub const DCORE0_MME_CTRL_LO_CMD_MASK_IDLE_IND_MASK: c_uint = 0x1000;
pub const DCORE0_MME_CTRL_LO_CMD_AGU_OUT1_FROM_AGU0_DW0_SHIFT: c_int = 13;
pub const DCORE0_MME_CTRL_LO_CMD_AGU_OUT1_FROM_AGU0_DW0_MASK: c_uint = 0x2000;
pub const DCORE0_MME_CTRL_LO_CMD_AGU_OUT1_FROM_AGU0_DW1_4_SHIFT: c_int = 14;
pub const DCORE0_MME_CTRL_LO_CMD_AGU_OUT1_FROM_AGU0_DW1_4_MASK: c_uint = 0x4000;
pub const DCORE0_MME_CTRL_LO_CMD_NULL_DESC_SHIFT: c_int = 15;
pub const DCORE0_MME_CTRL_LO_CMD_NULL_DESC_MASK: c_uint = 0x8000;
// DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SIGNAL_MASK0_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SIGNAL_MASK0_MASK: c_uint = 0x3F;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SIGNAL_EN0_SHIFT: c_int = 6;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SIGNAL_EN0_MASK: c_uint = 0x40;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SIGNAL_MASK1_SHIFT: c_int = 8;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SIGNAL_MASK1_MASK: c_uint = 0x3F00;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SIGNAL_EN1_SHIFT: c_int = 14;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SIGNAL_EN1_MASK: c_uint = 0x4000;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_MASTER_WAIT_SLAVE_FENCE_SHIFT: c_int = 15;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_MASTER_WAIT_SLAVE_FENCE_MASK: c_uint = 0x8000;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE_SEND_FENCE2MASTER_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE_SEND_FENCE2MASTER_MASK: c_uint = 0x10000;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE_SIGNAL_EN_SHIFT: c_int = 17;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE_SIGNAL_EN_MASK: c_uint = 0x20000;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE0_USE_SLV_ADR_SHIFT: c_int = 18;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE0_USE_SLV_ADR_MASK: c_uint = 0x40000;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE1_USE_SLV_ADR_SHIFT: c_int = 19;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE1_USE_SLV_ADR_MASK: c_uint = 0x80000;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE0_USE_MSTR_ADR_PLUS4_SHIFT: c_int = 20;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE0_USE_MSTR_ADR_PLUS4_MASK: c_uint = 0x100000;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE1_USE_MSTR_ADR_PLUS4_SHIFT: c_int = 21;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_DW0_SLAVE1_USE_MSTR_ADR_PLUS4_MASK: c_uint = 0x200000;
// DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_ADDR0
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_ADDR0_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_ADDR0_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL0
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL0_SO_VALUE_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL0_SO_VALUE_MASK: c_uint = 0x7FFF;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL0_SO_RESERVED_SHIFT: c_int = 15;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL0_SO_RESERVED_MASK: c_uint = 0x3FFF8000;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL0_SO_PERF_EN_SHIFT: c_int = 30;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL0_SO_PERF_EN_MASK: c_uint = 0x40000000;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL0_SO_OP_SHIFT: c_int = 31;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL0_SO_OP_MASK: c_uint = 0x80000000;
// DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_ADDR1
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_ADDR1_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_ADDR1_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL1
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL1_SO_VALUE_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL1_SO_VALUE_MASK: c_uint = 0x7FFF;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL1_SO_RESERVED_SHIFT: c_int = 15;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL1_SO_RESERVED_MASK: c_uint = 0x3FFF8000;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL1_SO_PERF_EN_SHIFT: c_int = 30;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL1_SO_PERF_EN_MASK: c_uint = 0x40000000;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL1_SO_OP_SHIFT: c_int = 31;
pub const DCORE0_MME_CTRL_LO_ARCH_SYNC_OBJ_VAL1_SO_OP_MASK: c_uint = 0x80000000;
// DCORE0_MME_CTRL_LO_ARCH_A_SS
pub const DCORE0_MME_CTRL_LO_ARCH_A_SS_MINUS_1_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_ARCH_A_SS_MINUS_1_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_ARCH_B_SS
pub const DCORE0_MME_CTRL_LO_ARCH_B_SS_MINUS_1_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_ARCH_B_SS_MINUS_1_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_ARCH_COUT_SS
pub const DCORE0_MME_CTRL_LO_ARCH_COUT_SS_MINUS_1_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_ARCH_COUT_SS_MINUS_1_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_QM_STALL
pub const DCORE0_MME_CTRL_LO_QM_STALL_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_QM_STALL_V_MASK: c_uint = 0x1;
// DCORE0_MME_CTRL_LO_LOG_SHADOW_LO
pub const DCORE0_MME_CTRL_LO_LOG_SHADOW_LO_MASK_0_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_LOG_SHADOW_LO_MASK_0_MASK: c_uint = 0x1FF;
pub const DCORE0_MME_CTRL_LO_LOG_SHADOW_LO_MASK_1_SHIFT: c_int = 9;
pub const DCORE0_MME_CTRL_LO_LOG_SHADOW_LO_MASK_1_MASK: c_uint = 0x3FE00;
// DCORE0_MME_CTRL_LO_LOG_SHADOW_HI
pub const DCORE0_MME_CTRL_LO_LOG_SHADOW_HI_MASK_2_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_LOG_SHADOW_HI_MASK_2_MASK: c_uint = 0x1FF;
pub const DCORE0_MME_CTRL_LO_LOG_SHADOW_HI_MASK_3_SHIFT: c_int = 9;
pub const DCORE0_MME_CTRL_LO_LOG_SHADOW_HI_MASK_3_MASK: c_uint = 0x3FE00;
// DCORE0_MME_CTRL_LO_SYNC_OBJECT_FIFO_TH
pub const DCORE0_MME_CTRL_LO_SYNC_OBJECT_FIFO_TH_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_SYNC_OBJECT_FIFO_TH_V_MASK: c_uint = 0x1F;
// DCORE0_MME_CTRL_LO_REDUN
pub const DCORE0_MME_CTRL_LO_REDUN_FMA_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_REDUN_FMA_MASK: c_uint = 0x3F;
// DCORE0_MME_CTRL_LO_EUS_LOCAL_FIFO_TH
pub const DCORE0_MME_CTRL_LO_EUS_LOCAL_FIFO_TH_FIFO0_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EUS_LOCAL_FIFO_TH_FIFO0_MASK: c_uint = 0x1F;
pub const DCORE0_MME_CTRL_LO_EUS_LOCAL_FIFO_TH_FIFO1_SHIFT: c_int = 5;
pub const DCORE0_MME_CTRL_LO_EUS_LOCAL_FIFO_TH_FIFO1_MASK: c_uint = 0x3E0;
pub const DCORE0_MME_CTRL_LO_EUS_LOCAL_FIFO_TH_FIFO2_SHIFT: c_int = 10;
pub const DCORE0_MME_CTRL_LO_EUS_LOCAL_FIFO_TH_FIFO2_MASK: c_uint = 0x7C00;
// DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW0
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_MASK: c_uint = 0xFF;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE0_SHIFT: c_int = 8;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE0_MASK: c_uint = 0x1F00;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE1_SHIFT: c_int = 13;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE1_MASK: c_uint = 0x3E000;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE2_SHIFT: c_int = 18;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE2_MASK: c_uint = 0x7C0000;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE3_SHIFT: c_int = 23;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW0_FP_PE3_MASK: c_uint = 0xF800000;
// DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW1
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW1_FP_PE4_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW1_FP_PE4_MASK: c_uint = 0x1F;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW1_FP_PE_HI_SHIFT: c_int = 5;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_DLY_DW1_FP_PE_HI_MASK: c_uint = 0x3E0;
// DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F16
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F16_DLY_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F16_DLY_MASK: c_uint = 0xFFF;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F16_EN_SHIFT: c_int = 31;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F16_EN_MASK: c_uint = 0x80000000;
// DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F8
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F8_DLY_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F8_DLY_MASK: c_uint = 0xFFF;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F8_EN_SHIFT: c_int = 31;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_F8_EN_MASK: c_uint = 0x80000000;
// DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32_DLY_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32_DLY_MASK: c_uint = 0xFFF;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32_EN_SHIFT: c_int = 31;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32_EN_MASK: c_uint = 0x80000000;
// DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32I
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32I_DLY_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32I_DLY_MASK: c_uint = 0xFFF;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32I_EN_SHIFT: c_int = 31;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_FP32I_EN_MASK: c_uint = 0x80000000;
// DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_TF32
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_TF32_DLY_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_TF32_DLY_MASK: c_uint = 0xFFF;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_TF32_EN_SHIFT: c_int = 31;
pub const DCORE0_MME_CTRL_LO_EUS_ROLLUP_CD_PROT_TF32_EN_MASK: c_uint = 0x80000000;
// DCORE0_MME_CTRL_LO_PCU_RL_DESC0
pub const DCORE0_MME_CTRL_LO_PCU_RL_DESC0_RL_RST_TOKEN_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_RL_DESC0_RL_RST_TOKEN_MASK: c_uint = 0xFFFF;
pub const DCORE0_MME_CTRL_LO_PCU_RL_DESC0_RL_TIMEOUT_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_PCU_RL_DESC0_RL_TIMEOUT_MASK: c_uint = 0xFF0000;
pub const DCORE0_MME_CTRL_LO_PCU_RL_DESC0_RL_DUMMY2REAL_PERIOD_SHIFT: c_int = 24;
pub const DCORE0_MME_CTRL_LO_PCU_RL_DESC0_RL_DUMMY2REAL_PERIOD_MASK: c_uint = 0xFF000000;
// DCORE0_MME_CTRL_LO_PCU_RL_TOKEN_UPDATE
pub const DCORE0_MME_CTRL_LO_PCU_RL_TOKEN_UPDATE_INC_VAL_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_RL_TOKEN_UPDATE_INC_VAL_MASK: c_uint = 0xFFFF;
pub const DCORE0_MME_CTRL_LO_PCU_RL_TOKEN_UPDATE_DEC_VAL_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_PCU_RL_TOKEN_UPDATE_DEC_VAL_MASK: c_uint = 0xFFFF0000;
// DCORE0_MME_CTRL_LO_PCU_RL_TH
pub const DCORE0_MME_CTRL_LO_PCU_RL_TH_POOL_TH_DEC_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_RL_TH_POOL_TH_DEC_MASK: c_uint = 0xFFFF;
pub const DCORE0_MME_CTRL_LO_PCU_RL_TH_DUMMY_REAL_DIFF_TH_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_PCU_RL_TH_DUMMY_REAL_DIFF_TH_MASK: c_uint = 0xFFFF0000;
// DCORE0_MME_CTRL_LO_PCU_RL_MIN
pub const DCORE0_MME_CTRL_LO_PCU_RL_MIN_AVG_MIN_TO_FORCE_DUMMY_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_RL_MIN_AVG_MIN_TO_FORCE_DUMMY_MASK: c_uint = 0xFFFF;
pub const DCORE0_MME_CTRL_LO_PCU_RL_MIN_TOKEN_MIN_VAL_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_PCU_RL_MIN_TOKEN_MIN_VAL_MASK: c_uint = 0xFFFF0000;
// DCORE0_MME_CTRL_LO_PCU_RL_CTRL_EN
pub const DCORE0_MME_CTRL_LO_PCU_RL_CTRL_EN_PCU_DISABLE_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_RL_CTRL_EN_PCU_DISABLE_MASK: c_uint = 0x1;
pub const DCORE0_MME_CTRL_LO_PCU_RL_CTRL_EN_MIN_VAL_PROT_EN_SHIFT: c_int = 1;
pub const DCORE0_MME_CTRL_LO_PCU_RL_CTRL_EN_MIN_VAL_PROT_EN_MASK: c_uint = 0x2;
// DCORE0_MME_CTRL_LO_PCU_RL_HISTORY_LOG_SIZE
pub const DCORE0_MME_CTRL_LO_PCU_RL_HISTORY_LOG_SIZE_ALL_MACS_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_RL_HISTORY_LOG_SIZE_ALL_MACS_MASK: c_uint = 0x7;
pub const DCORE0_MME_CTRL_LO_PCU_RL_HISTORY_LOG_SIZE_REAL_MACS_SHIFT: c_int = 3;
pub const DCORE0_MME_CTRL_LO_PCU_RL_HISTORY_LOG_SIZE_REAL_MACS_MASK: c_uint = 0x18;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_A_BF16
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_BF16_ODD_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_BF16_ODD_MASK: c_uint = 0xFFFF;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_BF16_EVEN_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_BF16_EVEN_MASK: c_uint = 0xFFFF0000;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_B_BF16
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_BF16_ODD_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_BF16_ODD_MASK: c_uint = 0xFFFF;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_BF16_EVEN_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_BF16_EVEN_MASK: c_uint = 0xFFFF0000;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_A_FP16
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_FP16_ODD_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_FP16_ODD_MASK: c_uint = 0xFFFF;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_FP16_EVEN_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_FP16_EVEN_MASK: c_uint = 0xFFFF0000;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_B_FP16
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_FP16_ODD_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_FP16_ODD_MASK: c_uint = 0xFFFF;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_FP16_EVEN_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_FP16_EVEN_MASK: c_uint = 0xFFFF0000;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_F8
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_F8_A_VAL_ODD_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_F8_A_VAL_ODD_MASK: c_uint = 0xFF;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_F8_A_VAL_EVEN_SHIFT: c_int = 8;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_F8_A_VAL_EVEN_MASK: c_uint = 0xFF00;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_F8_B_VAL_ODD_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_F8_B_VAL_ODD_MASK: c_uint = 0xFF0000;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_F8_B_VAL_EVEN_SHIFT: c_int = 24;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_F8_B_VAL_EVEN_MASK: c_uint = 0xFF000000;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_A_FP32_ODD
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_FP32_ODD_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_FP32_ODD_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_A_FP32_EVEN
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_FP32_EVEN_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_FP32_EVEN_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_B_FP32_ODD
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_FP32_ODD_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_FP32_ODD_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_B_FP32_EVEN
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_FP32_EVEN_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_FP32_EVEN_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_A_TF32_ODD
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_TF32_ODD_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_TF32_ODD_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_A_TF32_EVEN
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_TF32_EVEN_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_A_TF32_EVEN_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_B_TF32_ODD
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_TF32_ODD_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_TF32_ODD_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_PCU_DUMMY_B_TF32_EVEN
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_TF32_EVEN_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DUMMY_B_TF32_EVEN_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_PROT
pub const DCORE0_MME_CTRL_LO_PROT_VALUE_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PROT_VALUE_MASK: c_uint = 0x7;
// DCORE0_MME_CTRL_LO_EU
pub const DCORE0_MME_CTRL_LO_EU_POWER_SAVE_DISABLE_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EU_POWER_SAVE_DISABLE_MASK: c_uint = 0x1;
pub const DCORE0_MME_CTRL_LO_EU_FP_PYR_CLOSE_CGATE_EN_SHIFT: c_int = 1;
pub const DCORE0_MME_CTRL_LO_EU_FP_PYR_CLOSE_CGATE_EN_MASK: c_uint = 0x2;
pub const DCORE0_MME_CTRL_LO_EU_FP_CLS_CLOSE_CGATE_EN_SHIFT: c_int = 2;
pub const DCORE0_MME_CTRL_LO_EU_FP_CLS_CLOSE_CGATE_EN_MASK: c_uint = 0x4;
pub const DCORE0_MME_CTRL_LO_EU_FP_CLOSE_CGATE_DLY_SHIFT: c_int = 8;
pub const DCORE0_MME_CTRL_LO_EU_FP_CLOSE_CGATE_DLY_MASK: c_uint = 0xFFF00;
pub const DCORE0_MME_CTRL_LO_EU_FP_CLOSE_CGATE_ON_DESC_SHIFT: c_int = 20;
pub const DCORE0_MME_CTRL_LO_EU_FP_CLOSE_CGATE_ON_DESC_MASK: c_uint = 0x100000;
pub const DCORE0_MME_CTRL_LO_EU_FP_ROLLUP_CDC_STALL_DIS_SHIFT: c_int = 21;
pub const DCORE0_MME_CTRL_LO_EU_FP_ROLLUP_CDC_STALL_DIS_MASK: c_uint = 0x200000;
// DCORE0_MME_CTRL_LO_SBTE
pub const DCORE0_MME_CTRL_LO_SBTE_CLOSE_CGATE_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_SBTE_CLOSE_CGATE_MASK: c_uint = 0x1F;
// DCORE0_MME_CTRL_LO_AGU_SM_INFLIGHT_CNTR
pub const DCORE0_MME_CTRL_LO_AGU_SM_INFLIGHT_CNTR_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_AGU_SM_INFLIGHT_CNTR_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_AGU_SM_TOTAL_CNTR
pub const DCORE0_MME_CTRL_LO_AGU_SM_TOTAL_CNTR_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_AGU_SM_TOTAL_CNTR_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_PCU_RL_SAT_SEC
pub const DCORE0_MME_CTRL_LO_PCU_RL_SAT_SEC_VAL_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_RL_SAT_SEC_VAL_MASK: c_uint = 0xFFFFF;
pub const DCORE0_MME_CTRL_LO_PCU_RL_SAT_SEC_SEL_SHIFT: c_int = 31;
pub const DCORE0_MME_CTRL_LO_PCU_RL_SAT_SEC_SEL_MASK: c_uint = 0x80000000;
// DCORE0_MME_CTRL_LO_FMA_FUNC_REDUN_CLK_EN32
pub const DCORE0_MME_CTRL_LO_FMA_FUNC_REDUN_CLK_EN32_V_NMB__SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_FMA_FUNC_REDUN_CLK_EN32_V_NMB__MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_FMA_FUNC_REDUN_CLK_EN33
pub const DCORE0_MME_CTRL_LO_FMA_FUNC_REDUN_CLK_EN33_V_NMB__SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_FMA_FUNC_REDUN_CLK_EN33_V_NMB__MASK: c_uint = 0x1;
// DCORE0_MME_CTRL_LO_EU_ISOLATION_DIS
pub const DCORE0_MME_CTRL_LO_EU_ISOLATION_DIS_FMA_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EU_ISOLATION_DIS_FMA_MASK: c_uint = 0x1;
// DCORE0_MME_CTRL_LO_QM_SLV_CLK_EN
pub const DCORE0_MME_CTRL_LO_QM_SLV_CLK_EN_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_QM_SLV_CLK_EN_V_MASK: c_uint = 0x1;
// DCORE0_MME_CTRL_LO_HBW_CLK_ENABLER_DIS
pub const DCORE0_MME_CTRL_LO_HBW_CLK_ENABLER_DIS_AXI_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_HBW_CLK_ENABLER_DIS_AXI_MASK: c_uint = 0x1;
pub const DCORE0_MME_CTRL_LO_HBW_CLK_ENABLER_DIS_APB_SHIFT: c_int = 1;
pub const DCORE0_MME_CTRL_LO_HBW_CLK_ENABLER_DIS_APB_MASK: c_uint = 0x2;
// DCORE0_MME_CTRL_LO_AGU
pub const DCORE0_MME_CTRL_LO_AGU_COUT_H_FROM_SPATIAL_LOOP_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_AGU_COUT_H_FROM_SPATIAL_LOOP_MASK: c_uint = 0x1;
// DCORE0_MME_CTRL_LO_QM
pub const DCORE0_MME_CTRL_LO_QM_STOP_ON_SBTE_ERR_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_QM_STOP_ON_SBTE_ERR_MASK: c_uint = 0x1;
pub const DCORE0_MME_CTRL_LO_QM_EXT_ADDR_ERR_EN_SHIFT: c_int = 1;
pub const DCORE0_MME_CTRL_LO_QM_EXT_ADDR_ERR_EN_MASK: c_uint = 0x2;
// DCORE0_MME_CTRL_LO_EARLY_RELEASE_STATUS
pub const DCORE0_MME_CTRL_LO_EARLY_RELEASE_STATUS_AGU_COUT0_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EARLY_RELEASE_STATUS_AGU_COUT0_MASK: c_uint = 0xF;
pub const DCORE0_MME_CTRL_LO_EARLY_RELEASE_STATUS_AGU_COUT1_SHIFT: c_int = 4;
pub const DCORE0_MME_CTRL_LO_EARLY_RELEASE_STATUS_AGU_COUT1_MASK: c_uint = 0xF0;
pub const DCORE0_MME_CTRL_LO_EARLY_RELEASE_STATUS_AP_BRAIN_SHIFT: c_int = 8;
pub const DCORE0_MME_CTRL_LO_EARLY_RELEASE_STATUS_AP_BRAIN_MASK: c_uint = 0xF00;
pub const DCORE0_MME_CTRL_LO_EARLY_RELEASE_STATUS_EU_BRAIN_SHIFT: c_int = 12;
pub const DCORE0_MME_CTRL_LO_EARLY_RELEASE_STATUS_EU_BRAIN_MASK: c_uint = 0xF000;
// DCORE0_MME_CTRL_LO_INTR_CAUSE
pub const DCORE0_MME_CTRL_LO_INTR_CAUSE_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_INTR_CAUSE_V_MASK: c_uint = 0xFFFF;
// DCORE0_MME_CTRL_LO_INTR_MASK
pub const DCORE0_MME_CTRL_LO_INTR_MASK_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_INTR_MASK_V_MASK: c_uint = 0x3FFFFF;
// DCORE0_MME_CTRL_LO_INTR_CLEAR
pub const DCORE0_MME_CTRL_LO_INTR_CLEAR_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_INTR_CLEAR_V_MASK: c_uint = 0xFFFF;
// DCORE0_MME_CTRL_LO_REDUN_PSOC_SEL_SEC
pub const DCORE0_MME_CTRL_LO_REDUN_PSOC_SEL_SEC_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_REDUN_PSOC_SEL_SEC_V_MASK: c_uint = 0x1;
// DCORE0_MME_CTRL_LO_BIST
pub const DCORE0_MME_CTRL_LO_BIST_FUNC_MODE_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_BIST_FUNC_MODE_MASK: c_uint = 0x1;
pub const DCORE0_MME_CTRL_LO_BIST_APB_SW_MODE_SHIFT: c_int = 1;
pub const DCORE0_MME_CTRL_LO_BIST_APB_SW_MODE_MASK: c_uint = 0x2;
// DCORE0_MME_CTRL_LO_EU_RL_ENABLE
pub const DCORE0_MME_CTRL_LO_EU_RL_ENABLE_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EU_RL_ENABLE_V_MASK: c_uint = 0x1;
// DCORE0_MME_CTRL_LO_EU_RL_TOKEN_SEL
pub const DCORE0_MME_CTRL_LO_EU_RL_TOKEN_SEL_STAT_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EU_RL_TOKEN_SEL_STAT_MASK: c_uint = 0x1;
// DCORE0_MME_CTRL_LO_EU_RL_CFG
pub const DCORE0_MME_CTRL_LO_EU_RL_CFG_RST_TOKEN_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_EU_RL_CFG_RST_TOKEN_MASK: c_uint = 0xFF;
pub const DCORE0_MME_CTRL_LO_EU_RL_CFG_TIMEOUT_SHIFT: c_int = 8;
pub const DCORE0_MME_CTRL_LO_EU_RL_CFG_TIMEOUT_MASK: c_uint = 0xFF00;
pub const DCORE0_MME_CTRL_LO_EU_RL_CFG_SATURATION_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_EU_RL_CFG_SATURATION_MASK: c_uint = 0xFF0000;
pub const DCORE0_MME_CTRL_LO_EU_RL_CFG_DATA_SIZE_SHIFT: c_int = 24;
pub const DCORE0_MME_CTRL_LO_EU_RL_CFG_DATA_SIZE_MASK: c_uint = 0xFF000000;
// DCORE0_MME_CTRL_LO_PCU_DBG_DW0
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW0_FSM_STATE_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW0_FSM_STATE_MASK: c_uint = 0x1;
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW0_REAL_POOL_TOKENS_SHIFT: c_int = 8;
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW0_REAL_POOL_TOKENS_MASK: c_uint = 0xFFFFF00;
// DCORE0_MME_CTRL_LO_PCU_DBG_DW1
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW1_ALL_POOL_TOKENS_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW1_ALL_POOL_TOKENS_MASK: c_uint = 0xFFFFF;
// DCORE0_MME_CTRL_LO_PCU_DBG_DW2
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW2_BUBBLE_CYC_CNTR_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW2_BUBBLE_CYC_CNTR_MASK: c_uint = 0xFFFF;
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW2_DUMMY_CYC_CNTR_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW2_DUMMY_CYC_CNTR_MASK: c_uint = 0xFFFF0000;
// DCORE0_MME_CTRL_LO_PCU_DBG_DW3
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW3_REAL_MACS_HISTORY_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW3_REAL_MACS_HISTORY_MASK: c_uint = 0xFFFF;
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW3_ALL_MACS_HISTORY_SHIFT: c_int = 16;
pub const DCORE0_MME_CTRL_LO_PCU_DBG_DW3_ALL_MACS_HISTORY_MASK: c_uint = 0xFFFF0000;
// DCORE0_MME_CTRL_LO_PCU_DBG_WKL_ID
pub const DCORE0_MME_CTRL_LO_PCU_DBG_WKL_ID_B_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_PCU_DBG_WKL_ID_B_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_MME_CTRL_LO_ETF_MEM_WRAP_RM
pub const DCORE0_MME_CTRL_LO_ETF_MEM_WRAP_RM_V_SHIFT: c_int = 0;
pub const DCORE0_MME_CTRL_LO_ETF_MEM_WRAP_RM_V_MASK: c_uint = 0x3FFFFFFF;
