//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/gaudi2/asic_reg/dcore0_tpc0_cfg_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2020 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// DCORE0_TPC0_CFG
// (Prototype: TPC)
//
// DCORE0_TPC0_CFG_TPC_COUNT
pub const DCORE0_TPC0_CFG_TPC_COUNT_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TPC_COUNT_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_TPC_ID
pub const DCORE0_TPC0_CFG_TPC_ID_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TPC_ID_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_STALL_ON_ERR
pub const DCORE0_TPC0_CFG_STALL_ON_ERR_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_STALL_ON_ERR_V_MASK: c_uint = 0x1;
// DCORE0_TPC0_CFG_CLK_EN
pub const DCORE0_TPC0_CFG_CLK_EN_LBW_CFG_DIS_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_CLK_EN_LBW_CFG_DIS_MASK: c_uint = 0x1;
pub const DCORE0_TPC0_CFG_CLK_EN_DBG_CFG_DIS_SHIFT: c_int = 4;
pub const DCORE0_TPC0_CFG_CLK_EN_DBG_CFG_DIS_MASK: c_uint = 0x10;
// DCORE0_TPC0_CFG_IQ_RL_EN
pub const DCORE0_TPC0_CFG_IQ_RL_EN_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_IQ_RL_EN_V_MASK: c_uint = 0x1;
// DCORE0_TPC0_CFG_IQ_RL_SAT
pub const DCORE0_TPC0_CFG_IQ_RL_SAT_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_IQ_RL_SAT_V_MASK: c_uint = 0xFF;
// DCORE0_TPC0_CFG_IQ_RL_RST_TOKEN
pub const DCORE0_TPC0_CFG_IQ_RL_RST_TOKEN_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_IQ_RL_RST_TOKEN_V_MASK: c_uint = 0xFF;
// DCORE0_TPC0_CFG_IQ_RL_TIMEOUT
pub const DCORE0_TPC0_CFG_IQ_RL_TIMEOUT_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_IQ_RL_TIMEOUT_V_MASK: c_uint = 0xFF;
// DCORE0_TPC0_CFG_TSB_CFG_MTRR_2
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_2_PHY_BASE_ADD_LO_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_2_PHY_BASE_ADD_LO_MASK: c_uint = 0xFFFFFF;
// DCORE0_TPC0_CFG_IQ_LBW_CLK_EN
pub const DCORE0_TPC0_CFG_IQ_LBW_CLK_EN_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_IQ_LBW_CLK_EN_V_MASK: c_uint = 0x1;
// DCORE0_TPC0_CFG_TPC_LOCK_VALUE
pub const DCORE0_TPC0_CFG_TPC_LOCK_VALUE_VALUE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TPC_LOCK_VALUE_VALUE_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_TPC_LOCK
pub const DCORE0_TPC0_CFG_TPC_LOCK_LOCK_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TPC_LOCK_LOCK_MASK: c_uint = 0x1;
// DCORE0_TPC0_CFG_CGU_SB
pub const DCORE0_TPC0_CFG_CGU_SB_TSB_DISABLE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_CGU_SB_TSB_DISABLE_MASK: c_uint = 0x1;
// DCORE0_TPC0_CFG_CGU_CNT
pub const DCORE0_TPC0_CFG_CGU_CNT_DCACHE_DISABLE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_CGU_CNT_DCACHE_DISABLE_MASK: c_uint = 0x1;
pub const DCORE0_TPC0_CFG_CGU_CNT_WQ_DISABLE_SHIFT: c_int = 1;
pub const DCORE0_TPC0_CFG_CGU_CNT_WQ_DISABLE_MASK: c_uint = 0x2;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_ADDSUB_0_DISABLE_SHIFT: c_int = 2;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_ADDSUB_0_DISABLE_MASK: c_uint = 0x4;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_ADDSUB_1_DISABLE_SHIFT: c_int = 3;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_ADDSUB_1_DISABLE_MASK: c_uint = 0x8;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_ADDSUB_2_DISABLE_SHIFT: c_int = 4;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_ADDSUB_2_DISABLE_MASK: c_uint = 0x10;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_ADDSUB_3_DISABLE_SHIFT: c_int = 5;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_ADDSUB_3_DISABLE_MASK: c_uint = 0x20;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_ADDSUB_4_DISABLE_SHIFT: c_int = 6;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_ADDSUB_4_DISABLE_MASK: c_uint = 0x40;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_CMP_0_DISABLE_SHIFT: c_int = 7;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_CMP_0_DISABLE_MASK: c_uint = 0x80;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_CMP_1_DISABLE_SHIFT: c_int = 8;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_CMP_1_DISABLE_MASK: c_uint = 0x100;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_CMP_2_DISABLE_SHIFT: c_int = 9;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_CMP_2_DISABLE_MASK: c_uint = 0x200;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_CMP_3_DISABLE_SHIFT: c_int = 10;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_CMP_3_DISABLE_MASK: c_uint = 0x400;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_CMP_4_DISABLE_SHIFT: c_int = 11;
pub const DCORE0_TPC0_CFG_CGU_CNT_SPU_AGU_CMP_4_DISABLE_MASK: c_uint = 0x800;
pub const DCORE0_TPC0_CFG_CGU_CNT_MSAC_DISABLE_SHIFT: c_int = 12;
pub const DCORE0_TPC0_CFG_CGU_CNT_MSAC_DISABLE_MASK: c_uint = 0x1000;
pub const DCORE0_TPC0_CFG_CGU_CNT_CONV_DISABLE_SHIFT: c_int = 13;
pub const DCORE0_TPC0_CFG_CGU_CNT_CONV_DISABLE_MASK: c_uint = 0x2000;
pub const DCORE0_TPC0_CFG_CGU_CNT_NEARBYINT_DISABLE_SHIFT: c_int = 14;
pub const DCORE0_TPC0_CFG_CGU_CNT_NEARBYINT_DISABLE_MASK: c_uint = 0x4000;
pub const DCORE0_TPC0_CFG_CGU_CNT_CMP_DISABLE_SHIFT: c_int = 15;
pub const DCORE0_TPC0_CFG_CGU_CNT_CMP_DISABLE_MASK: c_uint = 0x8000;
pub const DCORE0_TPC0_CFG_CGU_CNT_FP_MAC_DISABLE_SHIFT: c_int = 16;
pub const DCORE0_TPC0_CFG_CGU_CNT_FP_MAC_DISABLE_MASK: c_uint = 0x10000;
pub const DCORE0_TPC0_CFG_CGU_CNT_SOPS_SRC_A_D2_DISABLE_SHIFT: c_int = 17;
pub const DCORE0_TPC0_CFG_CGU_CNT_SOPS_SRC_A_D2_DISABLE_MASK: c_uint = 0x20000;
pub const DCORE0_TPC0_CFG_CGU_CNT_SOPS_SRC_B_D2_DISABLE_SHIFT: c_int = 18;
pub const DCORE0_TPC0_CFG_CGU_CNT_SOPS_SRC_B_D2_DISABLE_MASK: c_uint = 0x40000;
pub const DCORE0_TPC0_CFG_CGU_CNT_SOPS_SRC_E_D2_DISABLE_SHIFT: c_int = 19;
pub const DCORE0_TPC0_CFG_CGU_CNT_SOPS_SRC_E_D2_DISABLE_MASK: c_uint = 0x80000;
pub const DCORE0_TPC0_CFG_CGU_CNT_SOPS_FMA_SRC_C_E1_DISABLE_SHIFT: c_int = 20;
pub const DCORE0_TPC0_CFG_CGU_CNT_SOPS_FMA_SRC_C_E1_DISABLE_MASK: c_uint = 0x100000;
pub const DCORE0_TPC0_CFG_CGU_CNT_LD_SOPS_SRC_A_D2_DISABLE_SHIFT: c_int = 21;
pub const DCORE0_TPC0_CFG_CGU_CNT_LD_SOPS_SRC_A_D2_DISABLE_MASK: c_uint = 0x200000;
pub const DCORE0_TPC0_CFG_CGU_CNT_ST_SOPS_SRC_A_D2_DISABLE_SHIFT: c_int = 22;
pub const DCORE0_TPC0_CFG_CGU_CNT_ST_SOPS_SRC_A_D2_DISABLE_MASK: c_uint = 0x400000;
pub const DCORE0_TPC0_CFG_CGU_CNT_FP_ADDSUB_DISABLE_SHIFT: c_int = 23;
pub const DCORE0_TPC0_CFG_CGU_CNT_FP_ADDSUB_DISABLE_MASK: c_uint = 0x800000;
// DCORE0_TPC0_CFG_CGU_CPE
pub const DCORE0_TPC0_CFG_CGU_CPE_NEARBYINT_DISABLE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_CGU_CPE_NEARBYINT_DISABLE_MASK: c_uint = 0x1;
pub const DCORE0_TPC0_CFG_CGU_CPE_SOPS_SRC_A_DISABLE_SHIFT: c_int = 1;
pub const DCORE0_TPC0_CFG_CGU_CPE_SOPS_SRC_A_DISABLE_MASK: c_uint = 0x2;
pub const DCORE0_TPC0_CFG_CGU_CPE_SOPS_SRC_B_DISABLE_SHIFT: c_int = 2;
pub const DCORE0_TPC0_CFG_CGU_CPE_SOPS_SRC_B_DISABLE_MASK: c_uint = 0x4;
pub const DCORE0_TPC0_CFG_CGU_CPE_SOPS_SRC_E_DISABLE_SHIFT: c_int = 3;
pub const DCORE0_TPC0_CFG_CGU_CPE_SOPS_SRC_E_DISABLE_MASK: c_uint = 0x8;
pub const DCORE0_TPC0_CFG_CGU_CPE_SOPS_SRC_D_DISABLE_SHIFT: c_int = 4;
pub const DCORE0_TPC0_CFG_CGU_CPE_SOPS_SRC_D_DISABLE_MASK: c_uint = 0x10;
pub const DCORE0_TPC0_CFG_CGU_CPE_SOPS_SRC_C_DISABLE_SHIFT: c_int = 5;
pub const DCORE0_TPC0_CFG_CGU_CPE_SOPS_SRC_C_DISABLE_MASK: c_uint = 0x20;
pub const DCORE0_TPC0_CFG_CGU_CPE_LD_SOPS_SRC_A_DISABLE_SHIFT: c_int = 6;
pub const DCORE0_TPC0_CFG_CGU_CPE_LD_SOPS_SRC_A_DISABLE_MASK: c_uint = 0x40;
pub const DCORE0_TPC0_CFG_CGU_CPE_MSAC_DISABLE_SHIFT: c_int = 7;
pub const DCORE0_TPC0_CFG_CGU_CPE_MSAC_DISABLE_MASK: c_uint = 0x80;
pub const DCORE0_TPC0_CFG_CGU_CPE_ADDSUB_DISABLE_SHIFT: c_int = 8;
pub const DCORE0_TPC0_CFG_CGU_CPE_ADDSUB_DISABLE_MASK: c_uint = 0x100;
pub const DCORE0_TPC0_CFG_CGU_CPE_SHIFT_DISABLE_SHIFT: c_int = 9;
pub const DCORE0_TPC0_CFG_CGU_CPE_SHIFT_DISABLE_MASK: c_uint = 0x200;
pub const DCORE0_TPC0_CFG_CGU_CPE_GLE_DISABLE_SHIFT: c_int = 10;
pub const DCORE0_TPC0_CFG_CGU_CPE_GLE_DISABLE_MASK: c_uint = 0x400;
pub const DCORE0_TPC0_CFG_CGU_CPE_CMP_DISABLE_SHIFT: c_int = 11;
pub const DCORE0_TPC0_CFG_CGU_CPE_CMP_DISABLE_MASK: c_uint = 0x800;
pub const DCORE0_TPC0_CFG_CGU_CPE_CONV_DISABLE_SHIFT: c_int = 12;
pub const DCORE0_TPC0_CFG_CGU_CPE_CONV_DISABLE_MASK: c_uint = 0x1000;
pub const DCORE0_TPC0_CFG_CGU_CPE_SB_DISABLE_SHIFT: c_int = 13;
pub const DCORE0_TPC0_CFG_CGU_CPE_SB_DISABLE_MASK: c_uint = 0x2000;
pub const DCORE0_TPC0_CFG_CGU_CPE_TBUF_DISABLE_SHIFT: c_int = 14;
pub const DCORE0_TPC0_CFG_CGU_CPE_TBUF_DISABLE_MASK: c_uint = 0x4000;
pub const DCORE0_TPC0_CFG_CGU_CPE_ST_G_DISABLE_SHIFT: c_int = 15;
pub const DCORE0_TPC0_CFG_CGU_CPE_ST_G_DISABLE_MASK: c_uint = 0x8000;
pub const DCORE0_TPC0_CFG_CGU_CPE_FP_MAC_0_DISABLE_SHIFT: c_int = 16;
pub const DCORE0_TPC0_CFG_CGU_CPE_FP_MAC_0_DISABLE_MASK: c_uint = 0x10000;
pub const DCORE0_TPC0_CFG_CGU_CPE_FP_MAC_1_DISABLE_SHIFT: c_int = 17;
pub const DCORE0_TPC0_CFG_CGU_CPE_FP_MAC_1_DISABLE_MASK: c_uint = 0x20000;
pub const DCORE0_TPC0_CFG_CGU_CPE_FP_ADDSUB_DISABLE_SHIFT: c_int = 18;
pub const DCORE0_TPC0_CFG_CGU_CPE_FP_ADDSUB_DISABLE_MASK: c_uint = 0x40000;
pub const DCORE0_TPC0_CFG_CGU_CPE_ST_SOPS_SRC_C_DISABLE_SHIFT: c_int = 19;
pub const DCORE0_TPC0_CFG_CGU_CPE_ST_SOPS_SRC_C_DISABLE_MASK: c_uint = 0x80000;
// DCORE0_TPC0_CFG_FP16_FTZ_IN
pub const DCORE0_TPC0_CFG_FP16_FTZ_IN_MODE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_FP16_FTZ_IN_MODE_MASK: c_uint = 0x1;
// DCORE0_TPC0_CFG_DCACHE_CFG
pub const DCORE0_TPC0_CFG_DCACHE_CFG_G_PREF_DIS_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_DCACHE_CFG_G_PREF_DIS_MASK: c_uint = 0x1;
pub const DCORE0_TPC0_CFG_DCACHE_CFG_G_PREF_VLD_CLR_SHIFT: c_int = 1;
pub const DCORE0_TPC0_CFG_DCACHE_CFG_G_PREF_VLD_CLR_MASK: c_uint = 0x2;
pub const DCORE0_TPC0_CFG_DCACHE_CFG_HALT_FLUSH_SHIFT: c_int = 2;
pub const DCORE0_TPC0_CFG_DCACHE_CFG_HALT_FLUSH_MASK: c_uint = 0x4;
pub const DCORE0_TPC0_CFG_DCACHE_CFG_DEALIGN_DIS_SHIFT: c_int = 3;
pub const DCORE0_TPC0_CFG_DCACHE_CFG_DEALIGN_DIS_MASK: c_uint = 0x8;
// DCORE0_TPC0_CFG_E2E_CRDT_TOP
pub const DCORE0_TPC0_CFG_E2E_CRDT_TOP_FORCE_EN_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_E2E_CRDT_TOP_FORCE_EN_MASK: c_uint = 0x1;
pub const DCORE0_TPC0_CFG_E2E_CRDT_TOP_Y_X_FORCE_SHIFT: c_int = 4;
pub const DCORE0_TPC0_CFG_E2E_CRDT_TOP_Y_X_FORCE_MASK: c_uint = 0x1FF0;
// DCORE0_TPC0_CFG_TPC_DCACHE_L0CD
pub const DCORE0_TPC0_CFG_TPC_DCACHE_L0CD_VAL_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TPC_DCACHE_L0CD_VAL_MASK: c_uint = 0x1;
// DCORE0_TPC0_CFG_TPC_SB_L0CD
pub const DCORE0_TPC0_CFG_TPC_SB_L0CD_VAL_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TPC_SB_L0CD_VAL_MASK: c_uint = 0x1;
// DCORE0_TPC0_CFG_CONV_ROUND_CSR
pub const DCORE0_TPC0_CFG_CONV_ROUND_CSR_MODE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_CONV_ROUND_CSR_MODE_MASK: c_uint = 0x7;
// DCORE0_TPC0_CFG_TSB_OCCUPANCY
pub const DCORE0_TPC0_CFG_TSB_OCCUPANCY_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TSB_OCCUPANCY_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_ARB_QNT_HBW_WEIGHT
pub const DCORE0_TPC0_CFG_ARB_QNT_HBW_WEIGHT_AR_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_ARB_QNT_HBW_WEIGHT_AR_MASK: c_uint = 0xFFF;
pub const DCORE0_TPC0_CFG_ARB_QNT_HBW_WEIGHT_AW_SHIFT: c_int = 12;
pub const DCORE0_TPC0_CFG_ARB_QNT_HBW_WEIGHT_AW_MASK: c_uint = 0xFF000;
// DCORE0_TPC0_CFG_ARB_QNT_LBW_WEIGHT
pub const DCORE0_TPC0_CFG_ARB_QNT_LBW_WEIGHT_AW_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_ARB_QNT_LBW_WEIGHT_AW_MASK: c_uint = 0xFF;
pub const DCORE0_TPC0_CFG_ARB_QNT_LBW_WEIGHT_AR_SHIFT: c_int = 8;
pub const DCORE0_TPC0_CFG_ARB_QNT_LBW_WEIGHT_AR_MASK: c_uint = 0xFF00;
// DCORE0_TPC0_CFG_ARB_CNT_HBW_WEIGHT
pub const DCORE0_TPC0_CFG_ARB_CNT_HBW_WEIGHT_AR_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_ARB_CNT_HBW_WEIGHT_AR_MASK: c_uint = 0xFFF;
pub const DCORE0_TPC0_CFG_ARB_CNT_HBW_WEIGHT_AW_SHIFT: c_int = 12;
pub const DCORE0_TPC0_CFG_ARB_CNT_HBW_WEIGHT_AW_MASK: c_uint = 0xFFF000;
// DCORE0_TPC0_CFG_ARB_CNT_LBW_WEIGHT
pub const DCORE0_TPC0_CFG_ARB_CNT_LBW_WEIGHT_AR_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_ARB_CNT_LBW_WEIGHT_AR_MASK: c_uint = 0xFF;
pub const DCORE0_TPC0_CFG_ARB_CNT_LBW_WEIGHT_AW_SHIFT: c_int = 8;
pub const DCORE0_TPC0_CFG_ARB_CNT_LBW_WEIGHT_AW_MASK: c_uint = 0xFFF00;
// DCORE0_TPC0_CFG_LUT_FUNC32_BASE2_ADDR_LO
pub const DCORE0_TPC0_CFG_LUT_FUNC32_BASE2_ADDR_LO_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC32_BASE2_ADDR_LO_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC32_BASE2_ADDR_HI
pub const DCORE0_TPC0_CFG_LUT_FUNC32_BASE2_ADDR_HI_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC32_BASE2_ADDR_HI_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC64_BASE2_ADDR_LO
pub const DCORE0_TPC0_CFG_LUT_FUNC64_BASE2_ADDR_LO_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC64_BASE2_ADDR_LO_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC64_BASE2_ADDR_HI
pub const DCORE0_TPC0_CFG_LUT_FUNC64_BASE2_ADDR_HI_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC64_BASE2_ADDR_HI_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC128_BASE2_ADDR_LO
pub const DCORE0_TPC0_CFG_LUT_FUNC128_BASE2_ADDR_LO_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC128_BASE2_ADDR_LO_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC128_BASE2_ADDR_HI
pub const DCORE0_TPC0_CFG_LUT_FUNC128_BASE2_ADDR_HI_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC128_BASE2_ADDR_HI_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC256_BASE2_ADDR_LO
pub const DCORE0_TPC0_CFG_LUT_FUNC256_BASE2_ADDR_LO_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC256_BASE2_ADDR_LO_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC256_BASE2_ADDR_HI
pub const DCORE0_TPC0_CFG_LUT_FUNC256_BASE2_ADDR_HI_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC256_BASE2_ADDR_HI_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_SPE_LFSR_POLYNOM
pub const DCORE0_TPC0_CFG_SPE_LFSR_POLYNOM_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_SPE_LFSR_POLYNOM_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_TSB_CFG_MTRR_GLBL
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_GLBL_EN_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_GLBL_EN_MASK: c_uint = 0x1;
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_GLBL_DEFAULT_MEMORY_TYPE_SHIFT: c_int = 4;
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_GLBL_DEFAULT_MEMORY_TYPE_MASK: c_uint = 0x10;
// DCORE0_TPC0_CFG_TSB_CFG_MTRR
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_VALID_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_VALID_MASK: c_uint = 0x1;
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_MEMORY_TYPE_SHIFT: c_int = 4;
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_MEMORY_TYPE_MASK: c_uint = 0x10;
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_PHY_BASE_ADD_SHIFT: c_int = 8;
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_PHY_BASE_ADD_MASK: c_uint = 0xFFFF00;
// DCORE0_TPC0_CFG_TSB_CFG_MTRR_MASK_LO
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_MASK_LO_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_MASK_LO_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_TSB_CFG_MTRR_MASK_HI
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_MASK_HI_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TSB_CFG_MTRR_MASK_HI_V_MASK: c_uint = 0xFF;
// DCORE0_TPC0_CFG_FP8_143_BIAS
pub const DCORE0_TPC0_CFG_FP8_143_BIAS_BIAS_143_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_FP8_143_BIAS_BIAS_143_MASK: c_uint = 0xF;
// DCORE0_TPC0_CFG_ROUND_CSR
pub const DCORE0_TPC0_CFG_ROUND_CSR_MODE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_ROUND_CSR_MODE_MASK: c_uint = 0x7;
// DCORE0_TPC0_CFG_HB_PROT
pub const DCORE0_TPC0_CFG_HB_PROT_AWPROT_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_HB_PROT_AWPROT_MASK: c_uint = 0x7;
pub const DCORE0_TPC0_CFG_HB_PROT_ARPROT_SHIFT: c_int = 3;
pub const DCORE0_TPC0_CFG_HB_PROT_ARPROT_MASK: c_uint = 0x38;
// DCORE0_TPC0_CFG_LB_PROT
pub const DCORE0_TPC0_CFG_LB_PROT_AWPROT_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LB_PROT_AWPROT_MASK: c_uint = 0x7;
pub const DCORE0_TPC0_CFG_LB_PROT_ARPROT_SHIFT: c_int = 3;
pub const DCORE0_TPC0_CFG_LB_PROT_ARPROT_MASK: c_uint = 0x38;
// DCORE0_TPC0_CFG_SEMAPHORE
pub const DCORE0_TPC0_CFG_SEMAPHORE_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_SEMAPHORE_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_VFLAGS
pub const DCORE0_TPC0_CFG_VFLAGS_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_VFLAGS_V_MASK: c_uint = 0x7F;
// DCORE0_TPC0_CFG_SFLAGS
pub const DCORE0_TPC0_CFG_SFLAGS_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_SFLAGS_V_MASK: c_uint = 0x7F;
// DCORE0_TPC0_CFG_LFSR_POLYNOM
pub const DCORE0_TPC0_CFG_LFSR_POLYNOM_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LFSR_POLYNOM_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_STATUS
pub const DCORE0_TPC0_CFG_STATUS_SCALAR_PIPE_EMPTY_SHIFT: c_int = 1;
pub const DCORE0_TPC0_CFG_STATUS_SCALAR_PIPE_EMPTY_MASK: c_uint = 0x2;
pub const DCORE0_TPC0_CFG_STATUS_VECTOR_PIPE_EMPTY_SHIFT: c_int = 2;
pub const DCORE0_TPC0_CFG_STATUS_VECTOR_PIPE_EMPTY_MASK: c_uint = 0x4;
pub const DCORE0_TPC0_CFG_STATUS_IQ_EMPTY_SHIFT: c_int = 3;
pub const DCORE0_TPC0_CFG_STATUS_IQ_EMPTY_MASK: c_uint = 0x8;
pub const DCORE0_TPC0_CFG_STATUS_SB_EMPTY_SHIFT: c_int = 5;
pub const DCORE0_TPC0_CFG_STATUS_SB_EMPTY_MASK: c_uint = 0x20;
pub const DCORE0_TPC0_CFG_STATUS_QM_IDLE_SHIFT: c_int = 6;
pub const DCORE0_TPC0_CFG_STATUS_QM_IDLE_MASK: c_uint = 0x40;
pub const DCORE0_TPC0_CFG_STATUS_QM_RDY_SHIFT: c_int = 7;
pub const DCORE0_TPC0_CFG_STATUS_QM_RDY_MASK: c_uint = 0x80;
// DCORE0_TPC0_CFG_CFG_BASE_ADDRESS_HIGH
pub const DCORE0_TPC0_CFG_CFG_BASE_ADDRESS_HIGH_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_CFG_BASE_ADDRESS_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_CFG_SUBTRACT_VALUE
pub const DCORE0_TPC0_CFG_CFG_SUBTRACT_VALUE_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_CFG_SUBTRACT_VALUE_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_SM_BASE_ADDRESS_HIGH
pub const DCORE0_TPC0_CFG_SM_BASE_ADDRESS_HIGH_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_SM_BASE_ADDRESS_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_TPC_CMD
pub const DCORE0_TPC0_CFG_TPC_CMD_ICACHE_INVALIDATE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TPC_CMD_ICACHE_INVALIDATE_MASK: c_uint = 0x1;
pub const DCORE0_TPC0_CFG_TPC_CMD_DCACHE_INVALIDATE_SHIFT: c_int = 1;
pub const DCORE0_TPC0_CFG_TPC_CMD_DCACHE_INVALIDATE_MASK: c_uint = 0x2;
pub const DCORE0_TPC0_CFG_TPC_CMD_LCACHE_INVALIDATE_SHIFT: c_int = 2;
pub const DCORE0_TPC0_CFG_TPC_CMD_LCACHE_INVALIDATE_MASK: c_uint = 0x4;
pub const DCORE0_TPC0_CFG_TPC_CMD_TCACHE_INVALIDATE_SHIFT: c_int = 3;
pub const DCORE0_TPC0_CFG_TPC_CMD_TCACHE_INVALIDATE_MASK: c_uint = 0x8;
pub const DCORE0_TPC0_CFG_TPC_CMD_ICACHE_PREFETCH_64KB_SHIFT: c_int = 4;
pub const DCORE0_TPC0_CFG_TPC_CMD_ICACHE_PREFETCH_64KB_MASK: c_uint = 0x10;
pub const DCORE0_TPC0_CFG_TPC_CMD_ICACHE_PREFETCH_32KB_SHIFT: c_int = 5;
pub const DCORE0_TPC0_CFG_TPC_CMD_ICACHE_PREFETCH_32KB_MASK: c_uint = 0x20;
pub const DCORE0_TPC0_CFG_TPC_CMD_QMAN_STOP_SHIFT: c_int = 6;
pub const DCORE0_TPC0_CFG_TPC_CMD_QMAN_STOP_MASK: c_uint = 0x40;
// DCORE0_TPC0_CFG_TPC_EXECUTE
pub const DCORE0_TPC0_CFG_TPC_EXECUTE_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TPC_EXECUTE_V_MASK: c_uint = 0x1;
// DCORE0_TPC0_CFG_TPC_STALL
pub const DCORE0_TPC0_CFG_TPC_STALL_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TPC_STALL_V_MASK: c_uint = 0x1;
// DCORE0_TPC0_CFG_ICACHE_BASE_ADDERESS_LOW
pub const DCORE0_TPC0_CFG_ICACHE_BASE_ADDERESS_LOW_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_ICACHE_BASE_ADDERESS_LOW_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_ICACHE_BASE_ADDERESS_HIGH
pub const DCORE0_TPC0_CFG_ICACHE_BASE_ADDERESS_HIGH_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_ICACHE_BASE_ADDERESS_HIGH_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_RD_RATE_LIMIT
pub const DCORE0_TPC0_CFG_RD_RATE_LIMIT_ENABLE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_RD_RATE_LIMIT_ENABLE_MASK: c_uint = 0x1;
pub const DCORE0_TPC0_CFG_RD_RATE_LIMIT_SATURATION_SHIFT: c_int = 1;
pub const DCORE0_TPC0_CFG_RD_RATE_LIMIT_SATURATION_MASK: c_uint = 0x1FE;
pub const DCORE0_TPC0_CFG_RD_RATE_LIMIT_TIMEOUT_SHIFT: c_int = 9;
pub const DCORE0_TPC0_CFG_RD_RATE_LIMIT_TIMEOUT_MASK: c_uint = 0x1FE00;
// DCORE0_TPC0_CFG_WR_RATE_LIMIT
pub const DCORE0_TPC0_CFG_WR_RATE_LIMIT_ENABLE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_WR_RATE_LIMIT_ENABLE_MASK: c_uint = 0x1;
pub const DCORE0_TPC0_CFG_WR_RATE_LIMIT_SATURATION_SHIFT: c_int = 1;
pub const DCORE0_TPC0_CFG_WR_RATE_LIMIT_SATURATION_MASK: c_uint = 0x1FE;
pub const DCORE0_TPC0_CFG_WR_RATE_LIMIT_TIMEOUT_SHIFT: c_int = 9;
pub const DCORE0_TPC0_CFG_WR_RATE_LIMIT_TIMEOUT_MASK: c_uint = 0x1FE00;
// DCORE0_TPC0_CFG_MSS_CONFIG
pub const DCORE0_TPC0_CFG_MSS_CONFIG_AWCACHE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_MSS_CONFIG_AWCACHE_MASK: c_uint = 0xF;
pub const DCORE0_TPC0_CFG_MSS_CONFIG_ARCACHE_SHIFT: c_int = 4;
pub const DCORE0_TPC0_CFG_MSS_CONFIG_ARCACHE_MASK: c_uint = 0xF0;
pub const DCORE0_TPC0_CFG_MSS_CONFIG_ICACHE_FETCH_LINE_NUM_SHIFT: c_int = 8;
pub const DCORE0_TPC0_CFG_MSS_CONFIG_ICACHE_FETCH_LINE_NUM_MASK: c_uint = 0x300;
pub const DCORE0_TPC0_CFG_MSS_CONFIG_EXPOSED_PIPE_DIS_SHIFT: c_int = 10;
pub const DCORE0_TPC0_CFG_MSS_CONFIG_EXPOSED_PIPE_DIS_MASK: c_uint = 0x400;
pub const DCORE0_TPC0_CFG_MSS_CONFIG_DCACHE_PREFETCH_DIS_SHIFT: c_int = 11;
pub const DCORE0_TPC0_CFG_MSS_CONFIG_DCACHE_PREFETCH_DIS_MASK: c_uint = 0x800;
// DCORE0_TPC0_CFG_TPC_INTR_CAUSE
pub const DCORE0_TPC0_CFG_TPC_INTR_CAUSE_CAUSE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TPC_INTR_CAUSE_CAUSE_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_TPC_INTR_MASK
pub const DCORE0_TPC0_CFG_TPC_INTR_MASK_MASK_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TPC_INTR_MASK_MASK_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_WQ_CREDITS
pub const DCORE0_TPC0_CFG_WQ_CREDITS_ST_G_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_WQ_CREDITS_ST_G_MASK: c_uint = 0xF;
pub const DCORE0_TPC0_CFG_WQ_CREDITS_KERNEL_FIFO_SHIFT: c_int = 4;
pub const DCORE0_TPC0_CFG_WQ_CREDITS_KERNEL_FIFO_MASK: c_uint = 0x70;
// DCORE0_TPC0_CFG_OPCODE_EXEC
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_SPU_OP_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_SPU_OP_MASK: c_uint = 0x7F;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_SPU_EN_SHIFT: c_int = 7;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_SPU_EN_MASK: c_uint = 0x80;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_VPU_OP_SHIFT: c_int = 8;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_VPU_OP_MASK: c_uint = 0x7F00;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_VPU_EN_SHIFT: c_int = 15;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_VPU_EN_MASK: c_uint = 0x8000;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_LD_OP_SHIFT: c_int = 16;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_LD_OP_MASK: c_uint = 0x7F0000;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_LD_EN_SHIFT: c_int = 23;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_LD_EN_MASK: c_uint = 0x800000;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_ST_OP_SHIFT: c_int = 24;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_ST_OP_MASK: c_uint = 0x7F000000;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_ST_EN_SHIFT: c_int = 31;
pub const DCORE0_TPC0_CFG_OPCODE_EXEC_ST_EN_MASK: c_uint = 0x80000000;
// DCORE0_TPC0_CFG_LUT_FUNC32_BASE_ADDR_LO
pub const DCORE0_TPC0_CFG_LUT_FUNC32_BASE_ADDR_LO_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC32_BASE_ADDR_LO_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC32_BASE_ADDR_HI
pub const DCORE0_TPC0_CFG_LUT_FUNC32_BASE_ADDR_HI_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC32_BASE_ADDR_HI_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC64_BASE_ADDR_LO
pub const DCORE0_TPC0_CFG_LUT_FUNC64_BASE_ADDR_LO_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC64_BASE_ADDR_LO_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC64_BASE_ADDR_HI
pub const DCORE0_TPC0_CFG_LUT_FUNC64_BASE_ADDR_HI_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC64_BASE_ADDR_HI_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC128_BASE_ADDR_LO
pub const DCORE0_TPC0_CFG_LUT_FUNC128_BASE_ADDR_LO_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC128_BASE_ADDR_LO_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC128_BASE_ADDR_HI
pub const DCORE0_TPC0_CFG_LUT_FUNC128_BASE_ADDR_HI_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC128_BASE_ADDR_HI_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC256_BASE_ADDR_LO
pub const DCORE0_TPC0_CFG_LUT_FUNC256_BASE_ADDR_LO_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC256_BASE_ADDR_LO_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_LUT_FUNC256_BASE_ADDR_HI
pub const DCORE0_TPC0_CFG_LUT_FUNC256_BASE_ADDR_HI_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_LUT_FUNC256_BASE_ADDR_HI_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_TSB_CFG_MAX_SIZE
pub const DCORE0_TPC0_CFG_TSB_CFG_MAX_SIZE_DATA_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TSB_CFG_MAX_SIZE_DATA_MASK: c_uint = 0xFFFF;
pub const DCORE0_TPC0_CFG_TSB_CFG_MAX_SIZE_MD_SHIFT: c_int = 16;
pub const DCORE0_TPC0_CFG_TSB_CFG_MAX_SIZE_MD_MASK: c_uint = 0xFFFF0000;
// DCORE0_TPC0_CFG_TSB_CFG
pub const DCORE0_TPC0_CFG_TSB_CFG_CACHE_DISABLE_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TSB_CFG_CACHE_DISABLE_MASK: c_uint = 0x1;
pub const DCORE0_TPC0_CFG_TSB_CFG_MAX_OS_SHIFT: c_int = 1;
pub const DCORE0_TPC0_CFG_TSB_CFG_MAX_OS_MASK: c_uint = 0x1FFFE;
pub const DCORE0_TPC0_CFG_TSB_CFG_ENABLE_CGATE_SHIFT: c_int = 17;
pub const DCORE0_TPC0_CFG_TSB_CFG_ENABLE_CGATE_MASK: c_uint = 0x20000;
// DCORE0_TPC0_CFG_TSB_INFLIGHT_CNTR
pub const DCORE0_TPC0_CFG_TSB_INFLIGHT_CNTR_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_TSB_INFLIGHT_CNTR_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_WQ_INFLIGHT_CNTR
pub const DCORE0_TPC0_CFG_WQ_INFLIGHT_CNTR_HBW_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_WQ_INFLIGHT_CNTR_HBW_MASK: c_uint = 0xFFFF;
pub const DCORE0_TPC0_CFG_WQ_INFLIGHT_CNTR_LBW_SHIFT: c_int = 16;
pub const DCORE0_TPC0_CFG_WQ_INFLIGHT_CNTR_LBW_MASK: c_uint = 0x1FF0000;
// DCORE0_TPC0_CFG_WQ_LBW_TOTAL_CNTR
pub const DCORE0_TPC0_CFG_WQ_LBW_TOTAL_CNTR_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_WQ_LBW_TOTAL_CNTR_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_WQ_HBW_TOTAL_CNTR
pub const DCORE0_TPC0_CFG_WQ_HBW_TOTAL_CNTR_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_WQ_HBW_TOTAL_CNTR_V_MASK: c_uint = 0xFFFFFFFF;
// DCORE0_TPC0_CFG_IRQ_OCCOUPY_CNTR
pub const DCORE0_TPC0_CFG_IRQ_OCCOUPY_CNTR_V_SHIFT: c_int = 0;
pub const DCORE0_TPC0_CFG_IRQ_OCCOUPY_CNTR_V_MASK: c_uint = 0xFFFFFFFF;
