//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/gaudi2/asic_reg/pcie_dec0_cmd_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2020 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// PCIE_DEC0_CMD
// (Prototype: VSI_CMD)
//
// PCIE_DEC0_CMD_SWREG0
pub const PCIE_DEC0_CMD_SWREG0_SW_HW_VERSION_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG0_SW_HW_VERSION_MASK: c_uint = 0xFFFF;
pub const PCIE_DEC0_CMD_SWREG0_SW_HW_ID_SHIFT: c_int = 16;
pub const PCIE_DEC0_CMD_SWREG0_SW_HW_ID_MASK: c_uint = 0xFFFF0000;
// PCIE_DEC0_CMD_SWREG1
pub const PCIE_DEC0_CMD_SWREG1_SW_HW_BUILDDATE_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG1_SW_HW_BUILDDATE_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG2
pub const PCIE_DEC0_CMD_SWREG2_SW_EXT_NORM_INTR_SRC_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG2_SW_EXT_NORM_INTR_SRC_MASK: c_uint = 0xFFFF;
pub const PCIE_DEC0_CMD_SWREG2_SW_EXT_ABN_INTR_SRC_SHIFT: c_int = 16;
pub const PCIE_DEC0_CMD_SWREG2_SW_EXT_ABN_INTR_SRC_MASK: c_uint = 0xFFFF0000;
// PCIE_DEC0_CMD_SWREG3
pub const PCIE_DEC0_CMD_SWREG3_SW_EXE_CMDBUF_COUNT_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG3_SW_EXE_CMDBUF_COUNT_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG4
pub const PCIE_DEC0_CMD_SWREG4_SW_CMD_EXE_LSB_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG4_SW_CMD_EXE_LSB_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG5
pub const PCIE_DEC0_CMD_SWREG5_SW_CMD_EXE_MSB_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG5_SW_CMD_EXE_MSB_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG6
pub const PCIE_DEC0_CMD_SWREG6_SW_AXI_TOTALARLEN_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG6_SW_AXI_TOTALARLEN_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG7
pub const PCIE_DEC0_CMD_SWREG7_SW_AXI_TOTALR_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG7_SW_AXI_TOTALR_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG8
pub const PCIE_DEC0_CMD_SWREG8_SW_AXI_TOTALAR_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG8_SW_AXI_TOTALAR_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG9
pub const PCIE_DEC0_CMD_SWREG9_SW_AXI_TOTALRLAST_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG9_SW_AXI_TOTALRLAST_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG10
pub const PCIE_DEC0_CMD_SWREG10_SW_AXI_TOTALAWLEN_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG10_SW_AXI_TOTALAWLEN_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG11
pub const PCIE_DEC0_CMD_SWREG11_SW_AXI_TOTALW_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG11_SW_AXI_TOTALW_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG12
pub const PCIE_DEC0_CMD_SWREG12_SW_AXI_TOTALAW_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG12_SW_AXI_TOTALAW_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG13
pub const PCIE_DEC0_CMD_SWREG13_SW_AXI_TOTALWLAST_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG13_SW_AXI_TOTALWLAST_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG14
pub const PCIE_DEC0_CMD_SWREG14_SW_AXI_TOTALB_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG14_SW_AXI_TOTALB_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG15
pub const PCIE_DEC0_CMD_SWREG15_SW_WORK_STATE_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG15_SW_WORK_STATE_MASK: c_uint = 0x7;
pub const PCIE_DEC0_CMD_SWREG15_RSV_SHIFT: c_int = 3;
pub const PCIE_DEC0_CMD_SWREG15_RSV_MASK: c_uint = 0x3FFFF8;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_BREADY_SHIFT: c_int = 22;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_BREADY_MASK: c_uint = 0x400000;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_BVALID_SHIFT: c_int = 23;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_BVALID_MASK: c_uint = 0x800000;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_WREADY_SHIFT: c_int = 24;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_WREADY_MASK: c_uint = 0x1000000;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_WVALID_SHIFT: c_int = 25;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_WVALID_MASK: c_uint = 0x2000000;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_AWREADY_SHIFT: c_int = 26;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_AWREADY_MASK: c_uint = 0x4000000;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_AWVALID_SHIFT: c_int = 27;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_AWVALID_MASK: c_uint = 0x8000000;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_RREADY_SHIFT: c_int = 28;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_RREADY_MASK: c_uint = 0x10000000;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_RVALID_SHIFT: c_int = 29;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_RVALID_MASK: c_uint = 0x20000000;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_ARREADY_SHIFT: c_int = 30;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_ARREADY_MASK: c_uint = 0x40000000;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_ARVALID_SHIFT: c_int = 31;
pub const PCIE_DEC0_CMD_SWREG15_SW_AXI_ARVALID_MASK: c_uint = 0x80000000;
// PCIE_DEC0_CMD_SWREG16
pub const PCIE_DEC0_CMD_SWREG16_SW_START_TRIGGER_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG16_SW_START_TRIGGER_MASK: c_uint = 0x1;
pub const PCIE_DEC0_CMD_SWREG16_SW_RESET_ALL_SHIFT: c_int = 1;
pub const PCIE_DEC0_CMD_SWREG16_SW_RESET_ALL_MASK: c_uint = 0x2;
pub const PCIE_DEC0_CMD_SWREG16_SW_RESET_CORE_SHIFT: c_int = 2;
pub const PCIE_DEC0_CMD_SWREG16_SW_RESET_CORE_MASK: c_uint = 0x4;
pub const PCIE_DEC0_CMD_SWREG16_SW_ABORT_MODE_SHIFT: c_int = 3;
pub const PCIE_DEC0_CMD_SWREG16_SW_ABORT_MODE_MASK: c_uint = 0x8;
pub const PCIE_DEC0_CMD_SWREG16_SW_CORE_CLK_GATE_DISABLE_SHIFT: c_int = 4;
pub const PCIE_DEC0_CMD_SWREG16_SW_CORE_CLK_GATE_DISABLE_MASK: c_uint = 0x10;
pub const PCIE_DEC0_CMD_SWREG16_SW_MASTER_OUT_CLK_GATE_DISABLE_SHIFT: c_int = 5;
pub const PCIE_DEC0_CMD_SWREG16_SW_MASTER_OUT_CLK_GATE_DISABLE_MASK: c_uint = 0x20;
pub const PCIE_DEC0_CMD_SWREG16_SW_AXI_CLK_GATE_DISABLE_SHIFT: c_int = 6;
pub const PCIE_DEC0_CMD_SWREG16_SW_AXI_CLK_GATE_DISABLE_MASK: c_uint = 0x40;
pub const PCIE_DEC0_CMD_SWREG16_RSV_SHIFT: c_int = 7;
pub const PCIE_DEC0_CMD_SWREG16_RSV_MASK: c_uint = 0xFFFFFF80;
// PCIE_DEC0_CMD_SWREG17
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_ENDCMD_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_ENDCMD_MASK: c_uint = 0x1;
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_BUSERR_SHIFT: c_int = 1;
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_BUSERR_MASK: c_uint = 0x2;
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_TIMEOUT_SHIFT: c_int = 2;
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_TIMEOUT_MASK: c_uint = 0x4;
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_CMDERR_SHIFT: c_int = 3;
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_CMDERR_MASK: c_uint = 0x8;
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_ABORT_SHIFT: c_int = 4;
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_ABORT_MASK: c_uint = 0x10;
pub const PCIE_DEC0_CMD_SWREG17_RSV_1_SHIFT: c_int = 5;
pub const PCIE_DEC0_CMD_SWREG17_RSV_1_MASK: c_uint = 0x20;
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_JMP_SHIFT: c_int = 6;
pub const PCIE_DEC0_CMD_SWREG17_SW_IRQ_JMP_MASK: c_uint = 0x40;
pub const PCIE_DEC0_CMD_SWREG17_RSV_SHIFT: c_int = 7;
pub const PCIE_DEC0_CMD_SWREG17_RSV_MASK: c_uint = 0xFFFFFF80;
// PCIE_DEC0_CMD_SWREG18
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_ENDCMD_EN_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_ENDCMD_EN_MASK: c_uint = 0x1;
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_BUSERR_EN_SHIFT: c_int = 1;
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_BUSERR_EN_MASK: c_uint = 0x2;
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_TIMEOUT_EN_SHIFT: c_int = 2;
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_TIMEOUT_EN_MASK: c_uint = 0x4;
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_CMDERR_EN_SHIFT: c_int = 3;
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_CMDERR_EN_MASK: c_uint = 0x8;
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_ABORT_EN_SHIFT: c_int = 4;
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_ABORT_EN_MASK: c_uint = 0x10;
pub const PCIE_DEC0_CMD_SWREG18_RSV_1_SHIFT: c_int = 5;
pub const PCIE_DEC0_CMD_SWREG18_RSV_1_MASK: c_uint = 0x20;
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_JMP_EN_SHIFT: c_int = 6;
pub const PCIE_DEC0_CMD_SWREG18_SW_IRQ_JMP_EN_MASK: c_uint = 0x40;
pub const PCIE_DEC0_CMD_SWREG18_RSV_SHIFT: c_int = 7;
pub const PCIE_DEC0_CMD_SWREG18_RSV_MASK: c_uint = 0xFFFFFF80;
// PCIE_DEC0_CMD_SWREG19
pub const PCIE_DEC0_CMD_SWREG19_SW_TIMEOUT_CYCLES_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG19_SW_TIMEOUT_CYCLES_MASK: c_uint = 0x7FFFFFFF;
pub const PCIE_DEC0_CMD_SWREG19_SW_TIMEOUT_ENABLE_SHIFT: c_int = 31;
pub const PCIE_DEC0_CMD_SWREG19_SW_TIMEOUT_ENABLE_MASK: c_uint = 0x80000000;
// PCIE_DEC0_CMD_SWREG20
pub const PCIE_DEC0_CMD_SWREG20_SW_CMDBUF_EXE_ADDR_LSB_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG20_SW_CMDBUF_EXE_ADDR_LSB_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG21
pub const PCIE_DEC0_CMD_SWREG21_SW_CMDBUF_EXE_ADDR_MSB_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG21_SW_CMDBUF_EXE_ADDR_MSB_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG22
pub const PCIE_DEC0_CMD_SWREG22_SW_CMDBUF_EXE_LENGTH_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG22_SW_CMDBUF_EXE_LENGTH_MASK: c_uint = 0xFFFF;
pub const PCIE_DEC0_CMD_SWREG22_RSV_SHIFT: c_int = 16;
pub const PCIE_DEC0_CMD_SWREG22_RSV_MASK: c_uint = 0xFFFF0000;
// PCIE_DEC0_CMD_SWREG23
pub const PCIE_DEC0_CMD_SWREG23_SW_AXI_ID_WR_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG23_SW_AXI_ID_WR_MASK: c_uint = 0xFF;
pub const PCIE_DEC0_CMD_SWREG23_SW_AXI_ID_RD_SHIFT: c_int = 8;
pub const PCIE_DEC0_CMD_SWREG23_SW_AXI_ID_RD_MASK: c_uint = 0xFF00;
pub const PCIE_DEC0_CMD_SWREG23_SW_MAX_BURST_LEN_SHIFT: c_int = 16;
pub const PCIE_DEC0_CMD_SWREG23_SW_MAX_BURST_LEN_MASK: c_uint = 0xFF0000;
pub const PCIE_DEC0_CMD_SWREG23_RSV_SHIFT: c_int = 24;
pub const PCIE_DEC0_CMD_SWREG23_RSV_MASK: c_uint = 0xF000000;
pub const PCIE_DEC0_CMD_SWREG23_SW_CMD_SWAP_SHIFT: c_int = 28;
pub const PCIE_DEC0_CMD_SWREG23_SW_CMD_SWAP_MASK: c_uint = 0xF0000000;
// PCIE_DEC0_CMD_SWREG24
pub const PCIE_DEC0_CMD_SWREG24_SW_RDY_CMDBUF_COUNT_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG24_SW_RDY_CMDBUF_COUNT_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG25
pub const PCIE_DEC0_CMD_SWREG25_SW_EXT_NORM_INTR_GATE_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG25_SW_EXT_NORM_INTR_GATE_MASK: c_uint = 0xFFFF;
pub const PCIE_DEC0_CMD_SWREG25_SW_EXT_ABN_INTR_GATE_SHIFT: c_int = 16;
pub const PCIE_DEC0_CMD_SWREG25_SW_EXT_ABN_INTR_GATE_MASK: c_uint = 0xFFFF0000;
// PCIE_DEC0_CMD_SWREG26
pub const PCIE_DEC0_CMD_SWREG26_SW_CMDBUF_EXE_ID_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG26_SW_CMDBUF_EXE_ID_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG64
pub const PCIE_DEC0_CMD_SWREG64_SW_DUMMY0_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG64_SW_DUMMY0_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG65
pub const PCIE_DEC0_CMD_SWREG65_SW_DUMMY1_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG65_SW_DUMMY1_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG66
pub const PCIE_DEC0_CMD_SWREG66_SW_DUMMY2_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG66_SW_DUMMY2_MASK: c_uint = 0xFFFFFFFF;
// PCIE_DEC0_CMD_SWREG67
pub const PCIE_DEC0_CMD_SWREG67_SW_DUMMY3_SHIFT: c_int = 0;
pub const PCIE_DEC0_CMD_SWREG67_SW_DUMMY3_MASK: c_uint = 0xFFFFFFFF;
