//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/gaudi2/asic_reg/pcie_vdec0_brdg_ctrl_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2020 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// PCIE_VDEC0_BRDG_CTRL
// (Prototype: VDEC_BRDG_CTRL)
//
// PCIE_VDEC0_BRDG_CTRL_CGM_DISABLE
pub const PCIE_VDEC0_BRDG_CTRL_CGM_DISABLE_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_CGM_DISABLE_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_IDLE_MASK
pub const PCIE_VDEC0_BRDG_CTRL_IDLE_MASK_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_IDLE_MASK_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_APB_CGM_CNT
pub const PCIE_VDEC0_BRDG_CTRL_APB_CGM_CNT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_APB_CGM_CNT_VAL_MASK: c_uint = 0xFFFF;
// PCIE_VDEC0_BRDG_CTRL_APB_ARB_WDOG_CNT
pub const PCIE_VDEC0_BRDG_CTRL_APB_ARB_WDOG_CNT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_APB_ARB_WDOG_CNT_VAL_MASK: c_uint = 0xFFFF;
// PCIE_VDEC0_BRDG_CTRL_GRACEFUL
pub const PCIE_VDEC0_BRDG_CTRL_GRACEFUL_STOP_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_GRACEFUL_STOP_MASK: c_uint = 0x1;
pub const PCIE_VDEC0_BRDG_CTRL_GRACEFUL_PEND_SHIFT: c_int = 4;
pub const PCIE_VDEC0_BRDG_CTRL_GRACEFUL_PEND_MASK: c_uint = 0x10;
// PCIE_VDEC0_BRDG_CTRL_IDLE_CGM_CNT
pub const PCIE_VDEC0_BRDG_CTRL_IDLE_CGM_CNT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_IDLE_CGM_CNT_VAL_MASK: c_uint = 0xFFFF;
// PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_HBW_SEI_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_HBW_SEI_MASK: c_uint = 0x1;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_HBW_SEI_SHIFT: c_int = 1;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_HBW_SEI_MASK: c_uint = 0x2;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_HBW_SEI_SHIFT: c_int = 2;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_HBW_SEI_MASK: c_uint = 0x4;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_HBW_SEI_SHIFT: c_int = 3;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_HBW_SEI_MASK: c_uint = 0x8;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_LBW_SEI_SHIFT: c_int = 4;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_VCD_LBW_SEI_MASK: c_uint = 0x10;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_LBW_SEI_SHIFT: c_int = 5;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_L2C_LBW_SEI_MASK: c_uint = 0x20;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_LBW_SEI_SHIFT: c_int = 6;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_NRM_LBW_SEI_MASK: c_uint = 0x40;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_LBW_SEI_SHIFT: c_int = 7;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MSIX_ABNRM_LBW_SEI_MASK: c_uint = 0x80;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_APB_VCD_LBW_SEI_SHIFT: c_int = 8;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_APB_VCD_LBW_SEI_MASK: c_uint = 0x100;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_APB_L2C_LBW_SEI_SHIFT: c_int = 9;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_APB_L2C_LBW_SEI_MASK: c_uint = 0x200;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_APB_NRM_LBW_SEI_SHIFT: c_int = 10;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_APB_NRM_LBW_SEI_MASK: c_uint = 0x400;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_APB_ABNRM_LBW_SEI_SHIFT: c_int = 11;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_APB_ABNRM_LBW_SEI_MASK: c_uint = 0x800;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_DEC_SEI_SHIFT: c_int = 12;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_DEC_SEI_MASK: c_uint = 0x1000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_DEC_APB_SEI_SHIFT: c_int = 13;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_DEC_APB_SEI_MASK: c_uint = 0x2000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_TRC_APB_SEI_SHIFT: c_int = 14;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_TRC_APB_SEI_MASK: c_uint = 0x4000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_LBW_MSTR_IF_SEI_SHIFT: c_int = 15;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_LBW_MSTR_IF_SEI_MASK: c_uint = 0x8000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_AXI_SPLIT_BRESP_ERR_SEI_SHIFT: c_int = 16;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_AXI_SPLIT_BRESP_ERR_SEI_MASK: c_uint = 0x10000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_HBW_AXI_WR_VIOL_SEI_SHIFT: c_int = 17;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_HBW_AXI_WR_VIOL_SEI_MASK: c_uint = 0x20000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_HBW_AXI_RD_VIOL_SEI_SHIFT: c_int = 18;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_HBW_AXI_RD_VIOL_SEI_MASK: c_uint = 0x40000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_LBW_AXI_WR_VIOL_SEI_SHIFT: c_int = 19;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_LBW_AXI_WR_VIOL_SEI_MASK: c_uint = 0x80000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_LBW_AXI_RD_VIOL_SEI_SHIFT: c_int = 20;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_LBW_AXI_RD_VIOL_SEI_MASK: c_uint = 0x100000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_VCD_SPI_SHIFT: c_int = 21;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_VCD_SPI_MASK: c_uint = 0x200000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_L2C_SPI_SHIFT: c_int = 22;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_L2C_SPI_MASK: c_uint = 0x400000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_NRM_SPI_SHIFT: c_int = 23;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_NRM_SPI_MASK: c_uint = 0x800000;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_ABNRM_SPI_SHIFT: c_int = 24;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_ABNRM_SPI_MASK: c_uint = 0x1000000;
// PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWLEN_GT_31_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWLEN_GT_31_MASK: c_uint = 0x1;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWLOCK_VIOL_SHIFT: c_int = 1;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWLOCK_VIOL_MASK: c_uint = 0x2;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWBURST_VIOL_SHIFT: c_int = 2;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWBURST_VIOL_MASK: c_uint = 0x4;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWADDR_SIZE_ALIGN_VIOL_SHIFT: c_int = 3;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWADDR_SIZE_ALIGN_VIOL_MASK: c_uint = 0x8;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWSIZE_VIOL_SHIFT: c_int = 4;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_AWSIZE_VIOL_MASK: c_uint = 0x10;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARLEN_GT_31_SHIFT: c_int = 5;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARLEN_GT_31_MASK: c_uint = 0x20;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARLOCK_VIOL_SHIFT: c_int = 6;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARLOCK_VIOL_MASK: c_uint = 0x40;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARBURST_VIOL_SHIFT: c_int = 7;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARBURST_VIOL_MASK: c_uint = 0x80;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARADDR_SIZE_ALIGN_VIOL_SHIFT: c_int = 8;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARADDR_SIZE_ALIGN_VIOL_MASK: c_uint = 0x100;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARSIZE_VIOL_SHIFT: c_int = 9;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_CAUSE_ARSIZE_VIOL_MASK: c_uint = 0x200;
// PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_READ_ACCESS_VIOL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_READ_ACCESS_VIOL_MASK: c_uint = 0x1;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWLOCK_VIOL_SHIFT: c_int = 1;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWLOCK_VIOL_MASK: c_uint = 0x2;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWADDR_ALIGN_VIOL_SHIFT: c_int = 2;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWADDR_ALIGN_VIOL_MASK: c_uint = 0x4;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWSIZE_VIOL_SHIFT: c_int = 3;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWSIZE_VIOL_MASK: c_uint = 0x8;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWLEN_VIOL_SHIFT: c_int = 4;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_AWLEN_VIOL_MASK: c_uint = 0x10;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_WSTRB_VIOL_SHIFT: c_int = 5;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_CAUSE_WSTRB_VIOL_MASK: c_uint = 0x20;
// PCIE_VDEC0_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM
pub const PCIE_VDEC0_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_HBW_AW_VIOL_CLR_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_HBW_AW_VIOL_CLR_MASK: c_uint = 0x1;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_HBW_AR_VIOL_CLR_SHIFT: c_int = 1;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_HBW_AR_VIOL_CLR_MASK: c_uint = 0x2;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_LBW_AW_VIOL_CLR_SHIFT: c_int = 2;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_VIOL_CLR_STICKY_TERM_LBW_AW_VIOL_CLR_MASK: c_uint = 0x4;
// PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MASK
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_CAUSE_INTR_MASK_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_MASK
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_MASK_MASK_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_AXI_VIOL_MASK_MASK_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_MASK
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_MASK_MASK_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_AXI_VIOL_MASK_MASK_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_VCD_GIC_INTR_MASK
pub const PCIE_VDEC0_BRDG_CTRL_VCD_GIC_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_GIC_INTR_MASK_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_L2C_GIC_INTR_MASK
pub const PCIE_VDEC0_BRDG_CTRL_L2C_GIC_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_GIC_INTR_MASK_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_NRM_GIC_INTR_MASK
pub const PCIE_VDEC0_BRDG_CTRL_NRM_GIC_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_GIC_INTR_MASK_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_GIC_INTR_MASK
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_GIC_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_GIC_INTR_MASK_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_DEC_HBW_AWPROT
pub const PCIE_VDEC0_BRDG_CTRL_DEC_HBW_AWPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_HBW_AWPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_DEC_HBW_ARPROT
pub const PCIE_VDEC0_BRDG_CTRL_DEC_HBW_ARPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_HBW_ARPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_DEC_LBW_AWPROT
pub const PCIE_VDEC0_BRDG_CTRL_DEC_LBW_AWPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_LBW_AWPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_DEC_LBW_ARPROT
pub const PCIE_VDEC0_BRDG_CTRL_DEC_LBW_ARPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_LBW_ARPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_DEC_LBW_SLV_AWPROT
pub const PCIE_VDEC0_BRDG_CTRL_DEC_LBW_SLV_AWPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_LBW_SLV_AWPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_DEC_LBW_SLV_ARPROT
pub const PCIE_VDEC0_BRDG_CTRL_DEC_LBW_SLV_ARPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_LBW_SLV_ARPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE
pub const PCIE_VDEC0_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_HBW_LEGAL_AWSIZE_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_HBW_LEGAL_AWSIZE_MASK: c_uint = 0x7;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_HBW_LEGAL_ARSIZE_SHIFT: c_int = 3;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_HBW_LEGAL_ARSIZE_MASK: c_uint = 0x38;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_LBW_LEGAL_AWSIZE_SHIFT: c_int = 6;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_AXI_LEGAL_AXSIZE_LBW_LEGAL_AWSIZE_MASK: c_uint = 0x1C0;
// PCIE_VDEC0_BRDG_CTRL_ARC_MSG_MASK
pub const PCIE_VDEC0_BRDG_CTRL_ARC_MSG_MASK_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ARC_MSG_MASK_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_ARC_START_LBW_WDATA
pub const PCIE_VDEC0_BRDG_CTRL_ARC_START_LBW_WDATA_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ARC_START_LBW_WDATA_VAL_MASK: c_uint = 0xFF;
// PCIE_VDEC0_BRDG_CTRL_ARC_FINISH_LBW_WDATA
pub const PCIE_VDEC0_BRDG_CTRL_ARC_FINISH_LBW_WDATA_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ARC_FINISH_LBW_WDATA_VAL_MASK: c_uint = 0xFF;
// PCIE_VDEC0_BRDG_CTRL_HWEVENT_TRACE_SEL
pub const PCIE_VDEC0_BRDG_CTRL_HWEVENT_TRACE_SEL_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_HWEVENT_TRACE_SEL_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_HWEVENT_TRACE_ADDR
pub const PCIE_VDEC0_BRDG_CTRL_HWEVENT_TRACE_ADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_HWEVENT_TRACE_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_CNT_L
pub const PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_CNT_L_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_CNT_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_CNT_H
pub const PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_CNT_H_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_CNT_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_L
pub const PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_L_IND_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_L_IND_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_H
pub const PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_H_IND_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_FREE_RUN_SET_VALUE_H_IND_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_CNT_L
pub const PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_CNT_L_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_CNT_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_CNT_H
pub const PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_CNT_H_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_CNT_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_SET_VALUE_L
pub const PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_SET_VALUE_L_IND_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_SET_VALUE_L_IND_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_SET_VALUE_H
pub const PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_SET_VALUE_H_IND_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_BUSY_SET_VALUE_H_IND_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_STAT_CNTR_EN
pub const PCIE_VDEC0_BRDG_CTRL_STAT_CNTR_EN_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_STAT_CNTR_EN_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_VCD_INTR_MASK
pub const PCIE_VDEC0_BRDG_CTRL_VCD_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_INTR_MASK_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_FLOW_MASK
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_FLOW_MASK_APB_WR_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_FLOW_MASK_APB_WR_MASK: c_uint = 0x1;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_FLOW_MASK_APB_RD_SHIFT: c_int = 1;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_FLOW_MASK_APB_RD_MASK: c_uint = 0x2;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_FLOW_MASK_LBW_SHIFT: c_int = 2;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_FLOW_MASK_LBW_MASK: c_uint = 0x4;
// PCIE_VDEC0_BRDG_CTRL_VCD_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_VCD_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_STAT_VCD_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_STAT_VCD_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_STAT_VCD_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_STAT_VCD_MSIX_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_STAT_VCD_MSIX_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_STAT_VCD_MSIX_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_VCD_SWREG1_ADDR
pub const PCIE_VDEC0_BRDG_CTRL_VCD_SWREG1_ADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_SWREG1_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_VCD_APB_WR_ADDR
pub const PCIE_VDEC0_BRDG_CTRL_VCD_APB_WR_ADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_APB_WR_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_VCD_APB_WR_DATA
pub const PCIE_VDEC0_BRDG_CTRL_VCD_APB_WR_DATA_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_APB_WR_DATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT
pub const PCIE_VDEC0_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_CPLQ_HBW_AWPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_L
pub const PCIE_VDEC0_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_L_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_H
pub const PCIE_VDEC0_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_H_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_CPLQ_HBW_AWADDR_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_LBW_AWPROT
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_LBW_AWPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_LBW_AWPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_LBW_AWADDR
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_LBW_AWADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_LBW_AWADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_LBW_WDATA
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_LBW_WDATA_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_VCD_MSIX_LBW_WDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_L2C_INTR_MASK
pub const PCIE_VDEC0_BRDG_CTRL_L2C_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_INTR_MASK_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_FLOW_MASK
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_FLOW_MASK_APB_WR_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_FLOW_MASK_APB_WR_MASK: c_uint = 0x1;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_FLOW_MASK_APB_RD_SHIFT: c_int = 1;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_FLOW_MASK_APB_RD_MASK: c_uint = 0x2;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_FLOW_MASK_LBW_SHIFT: c_int = 2;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_FLOW_MASK_LBW_MASK: c_uint = 0x4;
// PCIE_VDEC0_BRDG_CTRL_L2C_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_L2C_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_STAT_L2C_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_STAT_L2C_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_STAT_L2C_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_STAT_L2C_MSIX_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_STAT_L2C_MSIX_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_STAT_L2C_MSIX_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_L2C_SWREG1_ADDR
pub const PCIE_VDEC0_BRDG_CTRL_L2C_SWREG1_ADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_SWREG1_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_L2C_APB_WR_ADDR
pub const PCIE_VDEC0_BRDG_CTRL_L2C_APB_WR_ADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_APB_WR_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_L2C_APB_WR_DATA
pub const PCIE_VDEC0_BRDG_CTRL_L2C_APB_WR_DATA_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_APB_WR_DATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT
pub const PCIE_VDEC0_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_CPLQ_HBW_AWPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_L
pub const PCIE_VDEC0_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_L_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_H
pub const PCIE_VDEC0_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_H_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_CPLQ_HBW_AWADDR_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_LBW_AWPROT
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_LBW_AWPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_LBW_AWPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_LBW_AWADDR
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_LBW_AWADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_LBW_AWADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_LBW_WDATA
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_LBW_WDATA_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_L2C_MSIX_LBW_WDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_NRM_INTR_MASK
pub const PCIE_VDEC0_BRDG_CTRL_NRM_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_INTR_MASK_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_FLOW_MASK
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_FLOW_MASK_APB_WR_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_FLOW_MASK_APB_WR_MASK: c_uint = 0x1;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_FLOW_MASK_APB_RD_SHIFT: c_int = 1;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_FLOW_MASK_APB_RD_MASK: c_uint = 0x2;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_FLOW_MASK_LBW_SHIFT: c_int = 2;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_FLOW_MASK_LBW_MASK: c_uint = 0x4;
// PCIE_VDEC0_BRDG_CTRL_NRM_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_NRM_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_STAT_NRM_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_STAT_NRM_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_STAT_NRM_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_STAT_NRM_MSIX_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_STAT_NRM_MSIX_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_STAT_NRM_MSIX_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_NRM_SWREG1_ADDR
pub const PCIE_VDEC0_BRDG_CTRL_NRM_SWREG1_ADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_SWREG1_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_NRM_APB_WR_ADDR
pub const PCIE_VDEC0_BRDG_CTRL_NRM_APB_WR_ADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_APB_WR_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_NRM_APB_WR_DATA
pub const PCIE_VDEC0_BRDG_CTRL_NRM_APB_WR_DATA_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_APB_WR_DATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT
pub const PCIE_VDEC0_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_CPLQ_HBW_AWPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_L
pub const PCIE_VDEC0_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_L_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_H
pub const PCIE_VDEC0_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_H_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_CPLQ_HBW_AWADDR_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_LBW_AWPROT
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_LBW_AWPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_LBW_AWPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_LBW_AWADDR
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_LBW_AWADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_LBW_AWADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_LBW_WDATA
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_LBW_WDATA_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_NRM_MSIX_LBW_WDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_INTR_MASK
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_INTR_MASK_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_APB_WR_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_APB_WR_MASK: c_uint = 0x1;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_APB_RD_SHIFT: c_int = 1;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_APB_RD_MASK: c_uint = 0x2;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_LBW_SHIFT: c_int = 2;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_FLOW_MASK_LBW_MASK: c_uint = 0x4;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_STAT_ABNRM_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_STAT_ABNRM_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_STAT_ABNRM_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_STAT_ABNRM_MSIX_WAIT_CNTR
pub const PCIE_VDEC0_BRDG_CTRL_STAT_ABNRM_MSIX_WAIT_CNTR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_STAT_ABNRM_MSIX_WAIT_CNTR_VAL_MASK: c_uint = 0xFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_SWREG1_ADDR
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_SWREG1_ADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_SWREG1_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_APB_WR_ADDR
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_APB_WR_ADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_APB_WR_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_APB_WR_DATA
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_APB_WR_DATA_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_APB_WR_DATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_CPLQ_HBW_AWPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_L
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_L_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_H
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_H_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_CPLQ_HBW_AWADDR_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_LBW_AWPROT_VAL_MASK: c_uint = 0x7;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_LBW_AWADDR
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_LBW_AWADDR_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_LBW_AWADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_LBW_WDATA
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_LBW_WDATA_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_ABNRM_MSIX_LBW_WDATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_BRESP_ERR_ID
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_BRESP_ERR_ID_ID_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_BRESP_ERR_ID_ID_MASK: c_uint = 0xFF;
// PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_CFG
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_CFG_FORCE_RESP_OK_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_CFG_FORCE_RESP_OK_MASK: c_uint = 0x1;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_CFG_FORCE_WR_BUF_SHIFT: c_int = 1;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_CFG_FORCE_WR_BUF_MASK: c_uint = 0x2;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_CFG_NUM_RD_OS_SHIFT: c_int = 8;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_CFG_NUM_RD_OS_MASK: c_uint = 0xFF00;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_CFG_NUM_WR_OS_SHIFT: c_int = 16;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_CFG_NUM_WR_OS_MASK: c_uint = 0xFF0000;
// PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_NO_WR_INFLIGHT
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_NO_WR_INFLIGHT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_AXI_SPLIT_NO_WR_INFLIGHT_VAL_MASK: c_uint = 0x1;
// PCIE_VDEC0_BRDG_CTRL_HWEVENT_MASK
pub const PCIE_VDEC0_BRDG_CTRL_HWEVENT_MASK_MASK_SHIFT: c_int = 1;
pub const PCIE_VDEC0_BRDG_CTRL_HWEVENT_MASK_MASK_MASK: c_uint = 0x2;
// PCIE_VDEC0_BRDG_CTRL_HWEVENT_CNTXT
pub const PCIE_VDEC0_BRDG_CTRL_HWEVENT_CNTXT_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_HWEVENT_CNTXT_VAL_MASK: c_uint = 0xFFFF;
// PCIE_VDEC0_BRDG_CTRL_LBW_SLV_TERM_ERR_RESP
pub const PCIE_VDEC0_BRDG_CTRL_LBW_SLV_TERM_ERR_RESP_ERR_RESP_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_SLV_TERM_ERR_RESP_ERR_RESP_MASK: c_uint = 0x3;
// PCIE_VDEC0_BRDG_CTRL_LBW_MSTR_TERM_ERR_RESP
pub const PCIE_VDEC0_BRDG_CTRL_LBW_MSTR_TERM_ERR_RESP_ERR_RESP_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_LBW_MSTR_TERM_ERR_RESP_ERR_RESP_MASK: c_uint = 0x3;
// PCIE_VDEC0_BRDG_CTRL_DEC_HBW_MSTR_ERR_RESP
pub const PCIE_VDEC0_BRDG_CTRL_DEC_HBW_MSTR_ERR_RESP_WR_ERR_RESP_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_HBW_MSTR_ERR_RESP_WR_ERR_RESP_MASK: c_uint = 0x3;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_HBW_MSTR_ERR_RESP_RD_ERR_RESP_SHIFT: c_int = 2;
pub const PCIE_VDEC0_BRDG_CTRL_DEC_HBW_MSTR_ERR_RESP_RD_ERR_RESP_MASK: c_uint = 0xC;
// PCIE_VDEC0_BRDG_CTRL_HBW_VIOL_TERM_STATUS
pub const PCIE_VDEC0_BRDG_CTRL_HBW_VIOL_TERM_STATUS_AW_STA_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_VIOL_TERM_STATUS_AW_STA_MASK: c_uint = 0x1;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_VIOL_TERM_STATUS_AR_STA_SHIFT: c_int = 1;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_VIOL_TERM_STATUS_AR_STA_MASK: c_uint = 0x2;
// PCIE_VDEC0_BRDG_CTRL_HBW_LAST_AWADDR_TERM_L
pub const PCIE_VDEC0_BRDG_CTRL_HBW_LAST_AWADDR_TERM_L_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_LAST_AWADDR_TERM_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_HBW_LAST_AWADDR_TERM_H
pub const PCIE_VDEC0_BRDG_CTRL_HBW_LAST_AWADDR_TERM_H_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_LAST_AWADDR_TERM_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_HBW_LAST_ARADDR_TERM_L
pub const PCIE_VDEC0_BRDG_CTRL_HBW_LAST_ARADDR_TERM_L_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_LAST_ARADDR_TERM_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PCIE_VDEC0_BRDG_CTRL_HBW_LAST_ARADDR_TERM_H
pub const PCIE_VDEC0_BRDG_CTRL_HBW_LAST_ARADDR_TERM_H_VAL_SHIFT: c_int = 0;
pub const PCIE_VDEC0_BRDG_CTRL_HBW_LAST_ARADDR_TERM_H_VAL_MASK: c_uint = 0xFFFFFFFF;
