//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/gaudi2/asic_reg/pmmu_hbw_stlb_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2020 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// PMMU_HBW_STLB
// (Prototype: STLB)
//
// PMMU_HBW_STLB_BUSY
pub const PMMU_HBW_STLB_BUSY_BUSY_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_BUSY_BUSY_MASK: c_uint = 0xFFFFFFFF;
// PMMU_HBW_STLB_ASID
pub const PMMU_HBW_STLB_ASID_ASID_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_ASID_MASK: c_uint = 0x3FF;
// PMMU_HBW_STLB_HOP0_PA43_12
pub const PMMU_HBW_STLB_HOP0_PA43_12_HOP0_PA43_12_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_HOP0_PA43_12_HOP0_PA43_12_MASK: c_uint = 0xFFFFFFFF;
// PMMU_HBW_STLB_HOP0_PA63_44
pub const PMMU_HBW_STLB_HOP0_PA63_44_HOP0_PA63_44_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_HOP0_PA63_44_HOP0_PA63_44_MASK: c_uint = 0xFFFFF;
// PMMU_HBW_STLB_CACHE_INV
pub const PMMU_HBW_STLB_CACHE_INV_PRODUCER_INDEX_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_CACHE_INV_PRODUCER_INDEX_MASK: c_uint = 0xFF;
pub const PMMU_HBW_STLB_CACHE_INV_INDEX_MASK_SHIFT: c_int = 8;
pub const PMMU_HBW_STLB_CACHE_INV_INDEX_MASK_MASK: c_uint = 0xFF00;
// PMMU_HBW_STLB_CACHE_INV_BASE_39_8
pub const PMMU_HBW_STLB_CACHE_INV_BASE_39_8_PA_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_CACHE_INV_BASE_39_8_PA_MASK: c_uint = 0xFFFFFFFF;
// PMMU_HBW_STLB_CACHE_INV_BASE_63_40
pub const PMMU_HBW_STLB_CACHE_INV_BASE_63_40_PA_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_CACHE_INV_BASE_63_40_PA_MASK: c_uint = 0xFFFFFF;
// PMMU_HBW_STLB_STLB_FEATURE_EN
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_STLB_CTRL_MULTI_PAGE_SIZE_EN_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_STLB_CTRL_MULTI_PAGE_SIZE_EN_MASK: c_uint = 0x1;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_MULTI_PAGE_SIZE_EN_SHIFT: c_int = 1;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_MULTI_PAGE_SIZE_EN_MASK: c_uint = 0x2;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_LOOKUP_EN_SHIFT: c_int = 2;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_LOOKUP_EN_MASK: c_uint = 0x4;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_BYPASS_SHIFT: c_int = 3;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_BYPASS_MASK: c_uint = 0x8;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_BANK_STOP_SHIFT: c_int = 4;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_BANK_STOP_MASK: c_uint = 0x10;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_TRACE_EN_SHIFT: c_int = 5;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_TRACE_EN_MASK: c_uint = 0x20;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_FOLLOWER_EN_SHIFT: c_int = 6;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_FOLLOWER_EN_MASK: c_uint = 0x40;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_CACHING_EN_SHIFT: c_int = 7;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_CACHING_EN_MASK: c_uint = 0x1F80;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_FOLLOWING_NUM_LIMIT_SHIFT: c_int = 13;
pub const PMMU_HBW_STLB_STLB_FEATURE_EN_FOLLOWING_NUM_LIMIT_MASK: c_uint = 0xE000;
// PMMU_HBW_STLB_STLB_AXI_CACHE
pub const PMMU_HBW_STLB_STLB_AXI_CACHE_STLB_CTRL_ARCACHE_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_STLB_AXI_CACHE_STLB_CTRL_ARCACHE_MASK: c_uint = 0xF;
pub const PMMU_HBW_STLB_STLB_AXI_CACHE_STLB_CTRL_AWCACHE_SHIFT: c_int = 4;
pub const PMMU_HBW_STLB_STLB_AXI_CACHE_STLB_CTRL_AWCACHE_MASK: c_uint = 0xF0;
pub const PMMU_HBW_STLB_STLB_AXI_CACHE_INV_ARCACHE_SHIFT: c_int = 8;
pub const PMMU_HBW_STLB_STLB_AXI_CACHE_INV_ARCACHE_MASK: c_uint = 0xF00;
// PMMU_HBW_STLB_HOP_CONFIGURATION
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_FIRST_HOP_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_FIRST_HOP_MASK: c_uint = 0x7;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_FIRST_LOOKUP_HOP_SMALL_P_SHIFT: c_int = 4;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_FIRST_LOOKUP_HOP_SMALL_P_MASK: c_uint = 0x70;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_FIRST_LOOKUP_HOP_LARGE_P_SHIFT: c_int = 8;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_FIRST_LOOKUP_HOP_LARGE_P_MASK: c_uint = 0x700;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_LAST_HOP_SHIFT: c_int = 12;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_LAST_HOP_MASK: c_uint = 0x7000;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_FOLLOWER_HOP_SHIFT: c_int = 16;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_FOLLOWER_HOP_MASK: c_uint = 0x70000;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_ONLY_LARGE_PAGE_SHIFT: c_int = 20;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_ONLY_LARGE_PAGE_MASK: c_uint = 0x100000;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_LARGE_PAGE_INDICATION_BIT_SHIFT: c_int = 21;
pub const PMMU_HBW_STLB_HOP_CONFIGURATION_LARGE_PAGE_INDICATION_BIT_MASK: c_uint = 0x7E00000;
// PMMU_HBW_STLB_LINK_LIST_LOOKUP_MASK_63_32
pub const PMMU_HBW_STLB_LINK_LIST_LOOKUP_MASK_63_32_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_LINK_LIST_LOOKUP_MASK_63_32_R_MASK: c_uint = 0xFFFFFFFF;
// PMMU_HBW_STLB_LINK_LIST_LOOKUP_MASK_31_0
pub const PMMU_HBW_STLB_LINK_LIST_LOOKUP_MASK_31_0_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_LINK_LIST_LOOKUP_MASK_31_0_R_MASK: c_uint = 0xFFFFFFFF;
// PMMU_HBW_STLB_INV_ALL_START
pub const PMMU_HBW_STLB_INV_ALL_START_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_INV_ALL_START_R_MASK: c_uint = 0x1;
// PMMU_HBW_STLB_INV_ALL_SET
pub const PMMU_HBW_STLB_INV_ALL_SET_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_INV_ALL_SET_R_MASK: c_uint = 0xFF;
// PMMU_HBW_STLB_INV_PS
pub const PMMU_HBW_STLB_INV_PS_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_INV_PS_R_MASK: c_uint = 0x3;
// PMMU_HBW_STLB_INV_CONSUMER_INDEX
pub const PMMU_HBW_STLB_INV_CONSUMER_INDEX_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_INV_CONSUMER_INDEX_R_MASK: c_uint = 0xFF;
// PMMU_HBW_STLB_INV_HIT_COUNT
pub const PMMU_HBW_STLB_INV_HIT_COUNT_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_INV_HIT_COUNT_R_MASK: c_uint = 0x7FF;
// PMMU_HBW_STLB_INV_SET
pub const PMMU_HBW_STLB_INV_SET_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_INV_SET_R_MASK: c_uint = 0xFF;
// PMMU_HBW_STLB_SRAM_INIT
pub const PMMU_HBW_STLB_SRAM_INIT_BUSY_TAG_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_SRAM_INIT_BUSY_TAG_MASK: c_uint = 0x3;
pub const PMMU_HBW_STLB_SRAM_INIT_BUSY_SLICE_SHIFT: c_int = 2;
pub const PMMU_HBW_STLB_SRAM_INIT_BUSY_SLICE_MASK: c_uint = 0xC;
pub const PMMU_HBW_STLB_SRAM_INIT_BUSY_DATA_SHIFT: c_int = 4;
pub const PMMU_HBW_STLB_SRAM_INIT_BUSY_DATA_MASK: c_uint = 0x10;
// PMMU_HBW_STLB_MEM_CACHE_INVALIDATION
// PMMU_HBW_STLB_MEM_CACHE_INV_STATUS
pub const PMMU_HBW_STLB_MEM_CACHE_INV_STATUS_INVALIDATE_DONE_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_MEM_CACHE_INV_STATUS_INVALIDATE_DONE_MASK: c_uint = 0x1;
pub const PMMU_HBW_STLB_MEM_CACHE_INV_STATUS_CACHE_IDLE_SHIFT: c_int = 1;
pub const PMMU_HBW_STLB_MEM_CACHE_INV_STATUS_CACHE_IDLE_MASK: c_uint = 0x2;
// PMMU_HBW_STLB_MEM_CACHE_BASE_38_7
pub const PMMU_HBW_STLB_MEM_CACHE_BASE_38_7_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_MEM_CACHE_BASE_38_7_R_MASK: c_uint = 0xFFFFFFFF;
// PMMU_HBW_STLB_MEM_CACHE_BASE_63_39
pub const PMMU_HBW_STLB_MEM_CACHE_BASE_63_39_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_MEM_CACHE_BASE_63_39_R_MASK: c_uint = 0x1FFFFFF;
// PMMU_HBW_STLB_MEM_CACHE_CONFIG
pub const PMMU_HBW_STLB_MEM_CACHE_CONFIG_CACHE_HOP_EN_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_MEM_CACHE_CONFIG_CACHE_HOP_EN_MASK: c_uint = 0x3F;
pub const PMMU_HBW_STLB_MEM_CACHE_CONFIG_CACHE_HOP_PREFETCH_EN_SHIFT: c_int = 6;
pub const PMMU_HBW_STLB_MEM_CACHE_CONFIG_CACHE_HOP_PREFETCH_EN_MASK: c_uint = 0xFC0;
pub const PMMU_HBW_STLB_MEM_CACHE_CONFIG_BYPASS_EN_SHIFT: c_int = 12;
pub const PMMU_HBW_STLB_MEM_CACHE_CONFIG_BYPASS_EN_MASK: c_uint = 0x1000;
pub const PMMU_HBW_STLB_MEM_CACHE_CONFIG_RELEASE_INVALIDATE_SHIFT: c_int = 13;
pub const PMMU_HBW_STLB_MEM_CACHE_CONFIG_RELEASE_INVALIDATE_MASK: c_uint = 0x2000;
// PMMU_HBW_STLB_SET_THRESHOLD_HOP5
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP5_MIN_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP5_MIN_MASK: c_uint = 0x1FF;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP5_MAX_SHIFT: c_int = 9;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP5_MAX_MASK: c_uint = 0x3FE00;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP5_MASK_SHIFT: c_int = 18;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP5_MASK_MASK: c_uint = 0x7FC0000;
// PMMU_HBW_STLB_SET_THRESHOLD_HOP4
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP4_MIN_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP4_MIN_MASK: c_uint = 0x1FF;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP4_MAX_SHIFT: c_int = 9;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP4_MAX_MASK: c_uint = 0x3FE00;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP4_MASK_SHIFT: c_int = 18;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP4_MASK_MASK: c_uint = 0x7FC0000;
// PMMU_HBW_STLB_SET_THRESHOLD_HOP3
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP3_MIN_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP3_MIN_MASK: c_uint = 0x1FF;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP3_MAX_SHIFT: c_int = 9;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP3_MAX_MASK: c_uint = 0x3FE00;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP3_MASK_SHIFT: c_int = 18;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP3_MASK_MASK: c_uint = 0x7FC0000;
// PMMU_HBW_STLB_SET_THRESHOLD_HOP2
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP2_MIN_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP2_MIN_MASK: c_uint = 0x1FF;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP2_MAX_SHIFT: c_int = 9;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP2_MAX_MASK: c_uint = 0x3FE00;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP2_MASK_SHIFT: c_int = 18;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP2_MASK_MASK: c_uint = 0x7FC0000;
// PMMU_HBW_STLB_SET_THRESHOLD_HOP1
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP1_MIN_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP1_MIN_MASK: c_uint = 0x1FF;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP1_MAX_SHIFT: c_int = 9;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP1_MAX_MASK: c_uint = 0x3FE00;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP1_MASK_SHIFT: c_int = 18;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP1_MASK_MASK: c_uint = 0x7FC0000;
// PMMU_HBW_STLB_SET_THRESHOLD_HOP0
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP0_MIN_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP0_MIN_MASK: c_uint = 0x1FF;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP0_MAX_SHIFT: c_int = 9;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP0_MAX_MASK: c_uint = 0x3FE00;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP0_MASK_SHIFT: c_int = 18;
pub const PMMU_HBW_STLB_SET_THRESHOLD_HOP0_MASK_MASK: c_uint = 0x7FC0000;
// PMMU_HBW_STLB_MULTI_HIT_INTERRUPT_CLR
// PMMU_HBW_STLB_MULTI_HIT_INTERRUPT_MASK
pub const PMMU_HBW_STLB_MULTI_HIT_INTERRUPT_MASK_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_MULTI_HIT_INTERRUPT_MASK_R_MASK: c_uint = 0x1;
// PMMU_HBW_STLB_MEM_L0_CACHE_CFG
pub const PMMU_HBW_STLB_MEM_L0_CACHE_CFG_PLRU_EVICTION_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_MEM_L0_CACHE_CFG_PLRU_EVICTION_MASK: c_uint = 0x1;
pub const PMMU_HBW_STLB_MEM_L0_CACHE_CFG_CACHE_STOP_SHIFT: c_int = 1;
pub const PMMU_HBW_STLB_MEM_L0_CACHE_CFG_CACHE_STOP_MASK: c_uint = 0x2;
pub const PMMU_HBW_STLB_MEM_L0_CACHE_CFG_INV_WRITEBACK_SHIFT: c_int = 2;
pub const PMMU_HBW_STLB_MEM_L0_CACHE_CFG_INV_WRITEBACK_MASK: c_uint = 0x4;
// PMMU_HBW_STLB_MEM_READ_ARPROT
pub const PMMU_HBW_STLB_MEM_READ_ARPROT_R_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_MEM_READ_ARPROT_R_MASK: c_uint = 0x7;
// PMMU_HBW_STLB_RANGE_CACHE_INVALIDATION
pub const PMMU_HBW_STLB_RANGE_CACHE_INVALIDATION_RANGE_INVALIDATION_ENABLE_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_RANGE_CACHE_INVALIDATION_RANGE_INVALIDATION_ENABLE_MASK: c_uint = 0x1;
pub const PMMU_HBW_STLB_RANGE_CACHE_INVALIDATION_INVALIDATION_ASID_EN_SHIFT: c_int = 1;
pub const PMMU_HBW_STLB_RANGE_CACHE_INVALIDATION_INVALIDATION_ASID_EN_MASK: c_uint = 0x2;
pub const PMMU_HBW_STLB_RANGE_CACHE_INVALIDATION_INVALIDATION_ASID_SHIFT: c_int = 2;
pub const PMMU_HBW_STLB_RANGE_CACHE_INVALIDATION_INVALIDATION_ASID_MASK: c_uint = 0xFFC;
// PMMU_HBW_STLB_RANGE_INV_START_LSB
pub const PMMU_HBW_STLB_RANGE_INV_START_LSB_INV_START_LSB_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_RANGE_INV_START_LSB_INV_START_LSB_MASK: c_uint = 0xFFFFFFFF;
// PMMU_HBW_STLB_RANGE_INV_START_MSB
pub const PMMU_HBW_STLB_RANGE_INV_START_MSB_INV_START_MSB_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_RANGE_INV_START_MSB_INV_START_MSB_MASK: c_uint = 0xFFFFF;
// PMMU_HBW_STLB_RANGE_INV_END_LSB
pub const PMMU_HBW_STLB_RANGE_INV_END_LSB_INV_END_LSB_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_RANGE_INV_END_LSB_INV_END_LSB_MASK: c_uint = 0xFFFFFFFF;
// PMMU_HBW_STLB_RANGE_INV_END_MSB
pub const PMMU_HBW_STLB_RANGE_INV_END_MSB_INV_END_MSB_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_RANGE_INV_END_MSB_INV_END_MSB_MASK: c_uint = 0xFFFFF;
// PMMU_HBW_STLB_ASID_SCRAMBLER_CTRL
pub const PMMU_HBW_STLB_ASID_SCRAMBLER_CTRL_SCRAMBLER_SCRAM_EN_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCRAMBLER_CTRL_SCRAMBLER_SCRAM_EN_MASK: c_uint = 0x1;
// PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_0
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_0_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_0_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_1
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_1_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_1_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_2
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_2_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_2_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_3
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_3_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_3_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_4
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_4_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_4_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_5
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_5_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_5_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_6
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_6_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_6_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_7
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_7_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_7_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_8
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_8_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_8_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_9
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_9_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MATRIX_H3_9_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_10
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_10_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_10_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_11
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_11_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_11_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_12
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_12_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_12_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_13
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_13_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_13_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_14
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_14_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_14_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_15
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_15_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_15_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_16
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_16_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_16_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_17
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_17_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_17_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
// PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_18
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_18_ASID_POLY_MATRIX_H3_SHIFT: c_int = 0;
pub const PMMU_HBW_STLB_ASID_SCR_POLY_MAT_H3_18_ASID_POLY_MATRIX_H3_MASK: c_uint = 0x1FF;
