//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/accel/habanalabs/include/gaudi2/asic_reg/psoc_global_conf_masks.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2016-2020 HabanaLabs, Ltd.
// All Rights Reserved.
//
// This is an auto-generated file
// DO NOT EDIT BELOW
//
// PSOC_GLOBAL_CONF
// (Prototype: GLOBAL_CONF)
//
// PSOC_GLOBAL_CONF_NON_RST_FLOPS
pub const PSOC_GLOBAL_CONF_NON_RST_FLOPS_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_NON_RST_FLOPS_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_PCI_FW_FSM
pub const PSOC_GLOBAL_CONF_PCI_FW_FSM_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PCI_FW_FSM_EN_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_IND_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_MNL_RST_IND_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_MNL_RST_IND_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_WD_RST_IND_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_WD_RST_IND_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_SW_RST_IND_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_SW_RST_IND_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_SOFT_RST_IND_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_SOFT_RST_IND_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_PRST_RST_IND_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_PRST_RST_IND_MASK: c_uint = 0x100;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_FLR_RST_IND_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_FLR_RST_IND_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_FW_RST_IND_SHIFT: c_int = 10;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_FW_RST_IND_MASK: c_uint = 0x400;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_ECC_DERR_RST_IND_SHIFT: c_int = 11;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_RE_START_ECC_DERR_RST_IND_MASK: c_uint = 0x800;
// PSOC_GLOBAL_CONF_BTM_FSM
pub const PSOC_GLOBAL_CONF_BTM_FSM_STATE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BTM_FSM_STATE_MASK: c_uint = 0x1F;
// PSOC_GLOBAL_CONF_BTL_ROM_DELAY
pub const PSOC_GLOBAL_CONF_BTL_ROM_DELAY_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BTL_ROM_DELAY_VAL_MASK: c_uint = 0xFFFF;
// PSOC_GLOBAL_CONF_SW_BTM_FSM
pub const PSOC_GLOBAL_CONF_SW_BTM_FSM_CTRL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SW_BTM_FSM_CTRL_MASK: c_uint = 0x1F;
// PSOC_GLOBAL_CONF_SW_BOOT_SEQ_FSM
pub const PSOC_GLOBAL_CONF_SW_BOOT_SEQ_FSM_CTRL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SW_BOOT_SEQ_FSM_CTRL_MASK: c_uint = 0x1F;
// PSOC_GLOBAL_CONF_BOOT_SEQ_TIMEOUT
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_TIMEOUT_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_TIMEOUT_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_QSPI_SPI
pub const PSOC_GLOBAL_CONF_QSPI_SPI_SEL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_QSPI_SPI_SEL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_SPI_MEM_EN
pub const PSOC_GLOBAL_CONF_SPI_MEM_EN_IND_SPI_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_MEM_EN_IND_SPI_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_SPI_MEM_EN_IND_QSPI_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_SPI_MEM_EN_IND_QSPI_MASK: c_uint = 0x2;
// PSOC_GLOBAL_CONF_PRSTN
pub const PSOC_GLOBAL_CONF_PRSTN_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PRSTN_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PCIE_EN
pub const PSOC_GLOBAL_CONF_PCIE_EN_MASK_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PCIE_EN_MASK_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PCIE_PRSTN_INTR
pub const PSOC_GLOBAL_CONF_PCIE_PRSTN_INTR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PCIE_PRSTN_INTR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_SPI_IMG_STS
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_SPI_PRI_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_SPI_PRI_MASK: c_uint = 0x3;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_SPI_SEC_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_SPI_SEC_MASK: c_uint = 0xC;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRSTN_PRI_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRSTN_PRI_MASK: c_uint = 0x30;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRSTN_SEC_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRSTN_SEC_MASK: c_uint = 0xC0;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PCIE_PRI_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PCIE_PRI_MASK: c_uint = 0x300;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PCIE_SEC_SHIFT: c_int = 10;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PCIE_SEC_MASK: c_uint = 0xC00;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRE_SPI_PRI_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRE_SPI_PRI_MASK: c_uint = 0x3000;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRE_PRSTN_PRI_SHIFT: c_int = 14;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRE_PRSTN_PRI_MASK: c_uint = 0xC000;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRE_SPI_SEC_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRE_SPI_SEC_MASK: c_uint = 0x30000;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRE_PRSTN_SEC_SHIFT: c_int = 18;
pub const PSOC_GLOBAL_CONF_SPI_IMG_STS_PRE_PRSTN_SEC_MASK: c_uint = 0xC0000;
// PSOC_GLOBAL_CONF_BOOT_SEQ_FSM
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_IDLE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_IDLE_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_BOOT_INIT_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_BOOT_INIT_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRI_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRI_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_SEC_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_SEC_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRSTN_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PRSTN_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PCIE_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_SPI_PCIE_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_ROM_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_ROM_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_PCLK_READY_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_PCLK_READY_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_LTSSM_EN_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_FSM_LTSSM_EN_MASK: c_uint = 0x100;
// PSOC_GLOBAL_CONF_BOOT_SEQ_EXT_LD
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_EXT_LD_DONE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_EXT_LD_DONE_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_QSPI_SPI_BOOTSEQ_RST
pub const PSOC_GLOBAL_CONF_QSPI_SPI_BOOTSEQ_RST_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_QSPI_SPI_BOOTSEQ_RST_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PHY_STABLE
pub const PSOC_GLOBAL_CONF_PHY_STABLE_PRSTN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PHY_STABLE_PRSTN_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PRSTN_OVR
pub const PSOC_GLOBAL_CONF_PRSTN_OVR_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PRSTN_OVR_EN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_PRSTN_OVR_VAL_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_PRSTN_OVR_VAL_MASK: c_uint = 0x10;
// PSOC_GLOBAL_CONF_ETR_FLUSH
pub const PSOC_GLOBAL_CONF_ETR_FLUSH_MASK_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ETR_FLUSH_MASK_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ANY_RST
pub const PSOC_GLOBAL_CONF_ANY_RST_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ANY_RST_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_COLD_RST_FLOPS
pub const PSOC_GLOBAL_CONF_COLD_RST_FLOPS_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_COLD_RST_FLOPS_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_DIS_RAZWI_ERR
pub const PSOC_GLOBAL_CONF_DIS_RAZWI_ERR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_DIS_RAZWI_ERR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PCIE_PHY_RST_N
pub const PSOC_GLOBAL_CONF_PCIE_PHY_RST_N_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PCIE_PHY_RST_N_IND_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_PCIE_PHY_RST_N_CLK_DIS_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_PCIE_PHY_RST_N_CLK_DIS_MASK: c_uint = 0x10000;
// PSOC_GLOBAL_CONF_RAZWI_INTERRUPT
pub const PSOC_GLOBAL_CONF_RAZWI_INTERRUPT_INTR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_RAZWI_INTERRUPT_INTR_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_RAZWI_MASK_INFO
pub const PSOC_GLOBAL_CONF_RAZWI_MASK_INFO_MASK_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_RAZWI_MASK_INFO_MASK_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_RAZWI_MASK_INFO_WAS_AR_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_RAZWI_MASK_INFO_WAS_AR_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_RAZWI_MASK_INFO_WAS_AW_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_RAZWI_MASK_INFO_WAS_AW_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_RAZWI_MASK_INFO_AXUSER_L_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_RAZWI_MASK_INFO_AXUSER_L_MASK: c_uint = 0x3FF0;
pub const PSOC_GLOBAL_CONF_RAZWI_MASK_INFO_AXUSER_H_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_RAZWI_MASK_INFO_AXUSER_H_MASK: c_uint = 0xFFFF0000;
// PSOC_GLOBAL_CONF_BTL_PROT
pub const PSOC_GLOBAL_CONF_BTL_PROT_AR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BTL_PROT_AR_MASK: c_uint = 0x7;
pub const PSOC_GLOBAL_CONF_BTL_PROT_AW_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_BTL_PROT_AW_MASK: c_uint = 0x70;
// PSOC_GLOBAL_CONF_BTL_ADDR_EXT
pub const PSOC_GLOBAL_CONF_BTL_ADDR_EXT_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BTL_ADDR_EXT_VAL_MASK: c_uint = 0xFFFFF;
// PSOC_GLOBAL_CONF_BOOT_SEQ_TO
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_TO_MASK_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOT_SEQ_TO_MASK_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_RESET_DELAYS
pub const PSOC_GLOBAL_CONF_RESET_DELAYS_PRE_RESET_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_RESET_DELAYS_PRE_RESET_MASK: c_uint = 0xFFFF;
pub const PSOC_GLOBAL_CONF_RESET_DELAYS_GRAD_RESET_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_RESET_DELAYS_GRAD_RESET_MASK: c_uint = 0xFFFF0000;
// PSOC_GLOBAL_CONF_SCRATCHPAD
pub const PSOC_GLOBAL_CONF_SCRATCHPAD_REG_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SCRATCHPAD_REG_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SEMAPHORE
pub const PSOC_GLOBAL_CONF_SEMAPHORE_REG_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SEMAPHORE_REG_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_CPU_BOOT_STATUS
pub const PSOC_GLOBAL_CONF_CPU_BOOT_STATUS_CNTR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_CPU_BOOT_STATUS_CNTR_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_KMD_MSG_TO_CPU
pub const PSOC_GLOBAL_CONF_KMD_MSG_TO_CPU_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_KMD_MSG_TO_CPU_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SPL_SOURCE
pub const PSOC_GLOBAL_CONF_SPL_SOURCE_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPL_SOURCE_VAL_MASK: c_uint = 0x7;
// PSOC_GLOBAL_CONF_I2C_MSTR1_DBG
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_S_GEN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_S_GEN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_P_GEN_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_P_GEN_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_DATA_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_DATA_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_RD_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_RD_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_WR_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_WR_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_HS_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_HS_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_MASTER_ACT_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_MASTER_ACT_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_SLAVE_ACT_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_SLAVE_ACT_MASK: c_uint = 0x100;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_10BIT_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_ADDR_10BIT_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_MST_CSTATE_SHIFT: c_int = 10;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_MST_CSTATE_MASK: c_uint = 0x7C00;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_SLV_CSTATE_SHIFT: c_int = 15;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_SLV_CSTATE_MASK: c_uint = 0x78000;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_IC_EN_SHIFT: c_int = 19;
pub const PSOC_GLOBAL_CONF_I2C_MSTR1_DBG_IC_EN_MASK: c_uint = 0x80000;
// PSOC_GLOBAL_CONF_I2C_SLV
pub const PSOC_GLOBAL_CONF_I2C_SLV_CPU_CTRL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_I2C_SLV_CPU_CTRL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_I2C_SLV_INTR_MASK
pub const PSOC_GLOBAL_CONF_I2C_SLV_INTR_MASK_INTR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_I2C_SLV_INTR_MASK_INTR_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_TRACE_ADDR
pub const PSOC_GLOBAL_CONF_TRACE_ADDR_MSB_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TRACE_ADDR_MSB_MASK: c_uint = 0xFFFFFF;
// PSOC_GLOBAL_CONF_SMB_ALERT_CTRL
pub const PSOC_GLOBAL_CONF_SMB_ALERT_CTRL_I2C_M0_ALERT_MASK_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SMB_ALERT_CTRL_I2C_M0_ALERT_MASK_MASK: c_uint = 0xFF;
pub const PSOC_GLOBAL_CONF_SMB_ALERT_CTRL_I2C_M1_ALERT_MASK_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_SMB_ALERT_CTRL_I2C_M1_ALERT_MASK_MASK: c_uint = 0xFF00;
pub const PSOC_GLOBAL_CONF_SMB_ALERT_CTRL_I2C_SLV_ALERT_MASK_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_SMB_ALERT_CTRL_I2C_SLV_ALERT_MASK_MASK: c_uint = 0xFF0000;
// PSOC_GLOBAL_CONF_SMB_ALERT_INTR_CAUSE
pub const PSOC_GLOBAL_CONF_SMB_ALERT_INTR_CAUSE_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SMB_ALERT_INTR_CAUSE_VAL_MASK: c_uint = 0xFF;
// PSOC_GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CLEAR
pub const PSOC_GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CLEAR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CLEAR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CTRL
pub const PSOC_GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CTRL_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CTRL_IND_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CTRL_MASK_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_PCIE_PSOC_DERR_INTR_CTRL_MASK_MASK: c_uint = 0x10;
// PSOC_GLOBAL_CONF_TRACE_AXPROT
pub const PSOC_GLOBAL_CONF_TRACE_AXPROT_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TRACE_AXPROT_VAL_MASK: c_uint = 0x7;
// PSOC_GLOBAL_CONF_TRACE_AWUSER
pub const PSOC_GLOBAL_CONF_TRACE_AWUSER_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TRACE_AWUSER_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_TRACE_ARUSER
pub const PSOC_GLOBAL_CONF_TRACE_ARUSER_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TRACE_ARUSER_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_BTL_STS
pub const PSOC_GLOBAL_CONF_BTL_STS_DONE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BTL_STS_DONE_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_BTL_STS_FAIL_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_BTL_STS_FAIL_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_BTL_STS_FAIL_CODE_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_BTL_STS_FAIL_CODE_MASK: c_uint = 0xF00;
// PSOC_GLOBAL_CONF_TIMEOUT_INTR
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_0_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_0_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_1_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_1_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_2_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_2_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_3_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_3_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_4_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_4_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_TIMER_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_TIMER_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_UART_0_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_UART_0_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_UART_1_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_UART_1_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_5_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_5_MASK: c_uint = 0x100;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_6_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_TIMEOUT_INTR_GPIO_6_MASK: c_uint = 0x200;
// PSOC_GLOBAL_CONF_COMB_TIMEOUT_INTR
pub const PSOC_GLOBAL_CONF_COMB_TIMEOUT_INTR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_COMB_TIMEOUT_INTR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PERIPH_INTR
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_TX_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_TX_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_RX_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_RX_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_TXOVR_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_TXOVR_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_RXOVR_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_0_RXOVR_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_TX_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_TX_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_RX_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_RX_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_TXOVR_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_TXOVR_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_RXOVR_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_UART_1_RXOVR_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_EMMC_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_EMMC_MASK: c_uint = 0x1000;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_EMMC_WAKEUP_SHIFT: c_int = 13;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_EMMC_WAKEUP_MASK: c_uint = 0x2000;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_MII_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_PERIPH_INTR_MII_MASK: c_uint = 0x10000;
// PSOC_GLOBAL_CONF_COMB_PERIPH_INTR
pub const PSOC_GLOBAL_CONF_COMB_PERIPH_INTR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_COMB_PERIPH_INTR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_AXI_ERR_INTR
pub const PSOC_GLOBAL_CONF_AXI_ERR_INTR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_ERR_INTR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ARC_WD_INTR
pub const PSOC_GLOBAL_CONF_ARC_WD_INTR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ARC_WD_INTR_IND_MASK: c_uint = 0x3;
// PSOC_GLOBAL_CONF_ARC_WD_INTR_MASK
pub const PSOC_GLOBAL_CONF_ARC_WD_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ARC_WD_INTR_MASK_VAL_MASK: c_uint = 0x3;
// PSOC_GLOBAL_CONF_DBG_APB_CTRL
pub const PSOC_GLOBAL_CONF_DBG_APB_CTRL_SEL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_DBG_APB_CTRL_SEL_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_DBG_APB_CTRL_VAL_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_DBG_APB_CTRL_VAL_MASK: c_uint = 0x2;
// PSOC_GLOBAL_CONF_SPI_DMA_BAUDR
pub const PSOC_GLOBAL_CONF_SPI_DMA_BAUDR_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_DMA_BAUDR_VAL_MASK: c_uint = 0xFFFF;
// PSOC_GLOBAL_CONF_SPI_DMA_AWPROT
pub const PSOC_GLOBAL_CONF_SPI_DMA_AWPROT_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_DMA_AWPROT_VAL_MASK: c_uint = 0x7;
// PSOC_GLOBAL_CONF_SPI_DMA_AWUSER
pub const PSOC_GLOBAL_CONF_SPI_DMA_AWUSER_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_DMA_AWUSER_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SPI_DMA_CTRL
pub const PSOC_GLOBAL_CONF_SPI_DMA_CTRL_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_DMA_CTRL_EN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_SPI_DMA_CTRL_DST_SRAM_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_SPI_DMA_CTRL_DST_SRAM_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_SPI_DMA_CTRL_MEM_SIZE_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_SPI_DMA_CTRL_MEM_SIZE_MASK: c_uint = 0x3FFF0;
pub const PSOC_GLOBAL_CONF_SPI_DMA_CTRL_ADDR_SHIFT: c_int = 18;
pub const PSOC_GLOBAL_CONF_SPI_DMA_CTRL_ADDR_MASK: c_uint = 0xFFFC0000;
// PSOC_GLOBAL_CONF_SPI_DMA_STATUS
pub const PSOC_GLOBAL_CONF_SPI_DMA_STATUS_DONE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_DMA_STATUS_DONE_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_SPI_DMA_STATUS_ERROR_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_SPI_DMA_STATUS_ERROR_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_SPI_DMA_STATUS_COPIED_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_SPI_DMA_STATUS_COPIED_MASK: c_uint = 0x3FFF0;
// PSOC_GLOBAL_CONF_SPI_DMA_DST_ADDR_L
pub const PSOC_GLOBAL_CONF_SPI_DMA_DST_ADDR_L_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_DMA_DST_ADDR_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SPI_DMA_DST_ADDR_H
pub const PSOC_GLOBAL_CONF_SPI_DMA_DST_ADDR_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_DMA_DST_ADDR_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL
pub const PSOC_GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WEN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WEN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_BYTE_SWAP_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_BYTE_SWAP_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WRITE_CMD_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WRITE_CMD_MASK: c_uint = 0xFF00;
pub const PSOC_GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WREN_CMD_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WREN_CMD_MASK: c_uint = 0xFF0000;
pub const PSOC_GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WRDI_CMD_SHIFT: c_int = 24;
pub const PSOC_GLOBAL_CONF_SPI_DIRECT_WR_RD_CTRL_WRDI_CMD_MASK: c_uint = 0xFF000000;
// PSOC_GLOBAL_CONF_SPI_WR_WO_CTRL
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_CTRL_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_CTRL_EN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_CTRL_RESP_ERR_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_CTRL_RESP_ERR_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_CTRL_SE_RANGE_SEL_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_CTRL_SE_RANGE_SEL_MASK: c_uint = 0xFF0;
// PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_L
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_L_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_H
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_RST_VAL_H_VAL_MASK: c_uint = 0xFF;
// PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_L
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_L_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_H
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_TIMER_VAL_H_VAL_MASK: c_uint = 0xFF;
// PSOC_GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_L
pub const PSOC_GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_L_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_H
pub const PSOC_GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_QSPI_WR_WO_TIMER_VAL_H_VAL_MASK: c_uint = 0xFF;
// PSOC_GLOBAL_CONF_SPI_WR_WO_SE_STATUS
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_SE_STATUS_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_SE_STATUS_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_QSPI_WR_WO_SE_STATUS
pub const PSOC_GLOBAL_CONF_QSPI_WR_WO_SE_STATUS_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_QSPI_WR_WO_SE_STATUS_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SPI_WR_WO_ERR_ADDR
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_ERR_ADDR_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_ERR_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_QSPI_WR_WO_ERR_ADDR
pub const PSOC_GLOBAL_CONF_QSPI_WR_WO_ERR_ADDR_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_QSPI_WR_WO_ERR_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_MASK
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_MASK_QSPI_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_MASK_QSPI_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_MASK_SPI_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_MASK_SPI_MASK: c_uint = 0x2;
// PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_CAUSE
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_CAUSE_QSPI_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_CAUSE_QSPI_IND_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_CAUSE_SPI_IND_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_CAUSE_SPI_IND_MASK: c_uint = 0x2;
// PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_CLEAR
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_CLEAR_QSPI_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_CLEAR_QSPI_VAL_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_CLEAR_SPI_VAL_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_SPI_WR_WO_INTR_CLEAR_SPI_VAL_MASK: c_uint = 0x2;
// PSOC_GLOBAL_CONF_MSTR_IF
pub const PSOC_GLOBAL_CONF_MSTR_IF_GRACEFULL_CLEAR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MSTR_IF_GRACEFULL_CLEAR_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_MSTR_IF_FORCE_BP_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_MSTR_IF_FORCE_BP_MASK: c_uint = 0x2;
// PSOC_GLOBAL_CONF_TARGETID
pub const PSOC_GLOBAL_CONF_TARGETID_TDESIGNER_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_TARGETID_TDESIGNER_MASK: c_uint = 0xFFE;
pub const PSOC_GLOBAL_CONF_TARGETID_TPARTNO_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_TARGETID_TPARTNO_MASK: c_uint = 0xFFF0000;
pub const PSOC_GLOBAL_CONF_TARGETID_TREVISION_SHIFT: c_int = 28;
pub const PSOC_GLOBAL_CONF_TARGETID_TREVISION_MASK: c_uint = 0xF0000000;
// PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL_NUM_OS_RD_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL_NUM_OS_RD_MASK: c_uint = 0xFF;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL_NUM_OS_WR_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL_NUM_OS_WR_MASK: c_uint = 0xFF00;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL_FORCE_WR_BUF_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL_FORCE_WR_BUF_MASK: c_uint = 0x10000;
// PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_AWCACHE_OVRD_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_AWCACHE_OVRD_EN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_AWCACHE_OVRD_VAL_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_AWCACHE_OVRD_VAL_MASK: c_uint = 0xF0;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_ARCACHE_OVRD_EN_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_ARCACHE_OVRD_EN_MASK: c_uint = 0x100;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_ARCACHE_OVRD_VAL_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_ARCACHE_OVRD_VAL_MASK: c_uint = 0xF000;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_NO_WR_INFLIGHT_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_ARC_LBU_AXI_SPLIT_CTRL2_NO_WR_INFLIGHT_MASK: c_uint = 0x10000;
// PSOC_GLOBAL_CONF_EMMC_INT_VOL_STABLE
pub const PSOC_GLOBAL_CONF_EMMC_INT_VOL_STABLE_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_EMMC_INT_VOL_STABLE_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_RSVD_0_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_RSVD_0_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_MEM_REPAIR_CFG_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_MEM_REPAIR_CFG_MASK: c_uint = 0xC;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_CPOL_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_CPOL_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_CPHA_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_CPHA_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_BTL_EN_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_BTL_EN_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_BTL_ROM_EN_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_BTL_ROM_EN_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_DUMP_SEL_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_DUMP_SEL_MASK: c_uint = 0x3FFF00;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_RSVD_1_SHIFT: c_int = 22;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_RSVD_1_MASK: c_uint = 0x400000;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_DUMP_DIS_SHIFT: c_int = 23;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_DUMP_DIS_MASK: c_uint = 0x800000;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_I2C_SHIFT: c_int = 24;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_I2C_MASK: c_uint = 0x1F000000;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_SPI_QSPI_SHIFT: c_int = 29;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_SPI_QSPI_MASK: c_uint = 0x20000000;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_CPU_PLL_CFG_SHIFT: c_int = 30;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_L_CPU_PLL_CFG_MASK: c_uint = 0xC0000000;
// PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_H
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_H_SECURITY_BYPASS_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_H_SECURITY_BYPASS_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_H_SRIS_MODE_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_H_SRIS_MODE_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_H_I2C_SLV_ADDR_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_H_I2C_SLV_ADDR_MASK: c_uint = 0x7C;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_H_RERERVED_STRAP_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_BOOT_STRAP_PINS_H_RERERVED_STRAP_MASK: c_uint = 0x380;
// PSOC_GLOBAL_CONF_LEGACY_BOOT_STRAPS
pub const PSOC_GLOBAL_CONF_LEGACY_BOOT_STRAPS_PCIE_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_LEGACY_BOOT_STRAPS_PCIE_EN_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_MEM_REPAIR_DIV
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_DIV_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_DIV_EN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_DIV_VAL_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_DIV_VAL_MASK: c_uint = 0xFF00;
// PSOC_GLOBAL_CONF_MEM_REPAIR_CTRL
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_CTRL_SET_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_CTRL_SET_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_MEM_REPAIR_STS
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_STS_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_STS_IND_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_STS_FAIL_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_MEM_REPAIR_STS_FAIL_MASK: c_uint = 0x10;
// PSOC_GLOBAL_CONF_OUTSTANT_TRANS
pub const PSOC_GLOBAL_CONF_OUTSTANT_TRANS_RD_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_OUTSTANT_TRANS_RD_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_OUTSTANT_TRANS_WR_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_OUTSTANT_TRANS_WR_MASK: c_uint = 0x2;
// PSOC_GLOBAL_CONF_MASK_REQ
pub const PSOC_GLOBAL_CONF_MASK_REQ_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MASK_REQ_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_BSAC_CTRL
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_ENABLE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_ENABLE_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_HOLD_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_HOLD_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_DONE_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_DONE_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_STARTED_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_STARTED_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_APBERROR_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_APBERROR_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_FRF_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_FRF_MASK: c_uint = 0x300;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_TMOD_SHIFT: c_int = 10;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_TMOD_MASK: c_uint = 0xC00;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_SPI_FRF_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_BSAC_CTRL_SPI_FRF_MASK: c_uint = 0x3000;
// PSOC_GLOBAL_CONF_BSAC_ADDR
pub const PSOC_GLOBAL_CONF_BSAC_ADDR_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BSAC_ADDR_VAL_MASK: c_uint = 0xFFFFFFF;
// PSOC_GLOBAL_CONF_BSAC_DATA
pub const PSOC_GLOBAL_CONF_BSAC_DATA_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BSAC_DATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_BSAC_POLLING_CTRL
pub const PSOC_GLOBAL_CONF_BSAC_POLLING_CTRL_ADDR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BSAC_POLLING_CTRL_ADDR_MASK: c_uint = 0xFFFFFFF;
pub const PSOC_GLOBAL_CONF_BSAC_POLLING_CTRL_ENABLE_SHIFT: c_int = 28;
pub const PSOC_GLOBAL_CONF_BSAC_POLLING_CTRL_ENABLE_MASK: c_uint = 0x10000000;
pub const PSOC_GLOBAL_CONF_BSAC_POLLING_CTRL_DONE_SHIFT: c_int = 29;
pub const PSOC_GLOBAL_CONF_BSAC_POLLING_CTRL_DONE_MASK: c_uint = 0x20000000;
// PSOC_GLOBAL_CONF_BSAC_POLLING_DATA
pub const PSOC_GLOBAL_CONF_BSAC_POLLING_DATA_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BSAC_POLLING_DATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_BSAC_POLLING_MASK
pub const PSOC_GLOBAL_CONF_BSAC_POLLING_MASK_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BSAC_POLLING_MASK_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_BTL_IMG
pub const PSOC_GLOBAL_CONF_BTL_IMG_SPI_IMAGE_FLIP_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BTL_IMG_SPI_IMAGE_FLIP_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_BTL_IMG_PRST_IMAGE_FLIP_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_BTL_IMG_PRST_IMAGE_FLIP_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_BTL_IMG_PCIE_IMAGE_FLIP_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_BTL_IMG_PCIE_IMAGE_FLIP_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_BTL_IMG_SW_RST_RUN_PCIE_IMAGE_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_BTL_IMG_SW_RST_RUN_PCIE_IMAGE_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_BTL_IMG_SOFT_RST_RUN_PCIE_IMAGE_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_BTL_IMG_SOFT_RST_RUN_PCIE_IMAGE_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_BTL_IMG_WD_RST_RUN_PCIE_IMAGE_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_BTL_IMG_WD_RST_RUN_PCIE_IMAGE_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_BTL_IMG_MNL_RST_RUN_PCIE_IMAGE_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_BTL_IMG_MNL_RST_RUN_PCIE_IMAGE_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_BTL_IMG_PRST_RUN_PCIE_IMAGE_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_BTL_IMG_PRST_RUN_PCIE_IMAGE_MASK: c_uint = 0x100;
pub const PSOC_GLOBAL_CONF_BTL_IMG_FLR_RST_RUN_PCIE_IMAGE_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_BTL_IMG_FLR_RST_RUN_PCIE_IMAGE_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_BTL_IMG_FW_RST_RUN_PCIE_IMAGE_SHIFT: c_int = 10;
pub const PSOC_GLOBAL_CONF_BTL_IMG_FW_RST_RUN_PCIE_IMAGE_MASK: c_uint = 0x400;
// PSOC_GLOBAL_CONF_PRSTN_MASK
pub const PSOC_GLOBAL_CONF_PRSTN_MASK_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PRSTN_MASK_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_WD_MASK
pub const PSOC_GLOBAL_CONF_WD_MASK_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_WD_MASK_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_RST_SRC
pub const PSOC_GLOBAL_CONF_RST_SRC_COLD_RST_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_RST_SRC_COLD_RST_IND_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_RST_SRC_MNL_RST_IND_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_RST_SRC_MNL_RST_IND_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_RST_SRC_PRSTN_RST_IND_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_RST_SRC_PRSTN_RST_IND_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_RST_SRC_SOFT_RST_IND_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_RST_SRC_SOFT_RST_IND_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_RST_SRC_WD_RST_IND_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_RST_SRC_WD_RST_IND_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_RST_SRC_FW_RST_IND_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_RST_SRC_FW_RST_IND_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_RST_SRC_SW_RST_IND_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_RST_SRC_SW_RST_IND_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_RST_SRC_FLR_RST_IND_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_RST_SRC_FLR_RST_IND_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_RST_SRC_ECC_DERR_RST_IND_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_RST_SRC_ECC_DERR_RST_IND_MASK: c_uint = 0x100;
// PSOC_GLOBAL_CONF_BOOT_STATE
pub const PSOC_GLOBAL_CONF_BOOT_STATE_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOT_STATE_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_RST_FROM_PCIE_CTRL
pub const PSOC_GLOBAL_CONF_RST_FROM_PCIE_CTRL_SOFT_RST_MASK_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_RST_FROM_PCIE_CTRL_SOFT_RST_MASK_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_RST_FROM_PCIE_CTRL_SW_RST_MASK_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_RST_FROM_PCIE_CTRL_SW_RST_MASK_MASK: c_uint = 0x10;
// PSOC_GLOBAL_CONF_PAD_1V8_CFG
pub const PSOC_GLOBAL_CONF_PAD_1V8_CFG_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PAD_1V8_CFG_VAL_MASK: c_uint = 0x7F;
// PSOC_GLOBAL_CONF_PAD_3V3_CFG
pub const PSOC_GLOBAL_CONF_PAD_3V3_CFG_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PAD_3V3_CFG_VAL_MASK: c_uint = 0x7F;
// PSOC_GLOBAL_CONF_BNK3V3_MS
pub const PSOC_GLOBAL_CONF_BNK3V3_MS_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BNK3V3_MS_VAL_MASK: c_uint = 0x3;
// PSOC_GLOBAL_CONF_TPC_ISO
pub const PSOC_GLOBAL_CONF_TPC_ISO_ISO_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TPC_ISO_ISO_EN_MASK: c_uint = 0x1FFFFFF;
// PSOC_GLOBAL_CONF_VDEC_ISO
pub const PSOC_GLOBAL_CONF_VDEC_ISO_ISO_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_VDEC_ISO_ISO_EN_MASK: c_uint = 0x3FF;
// PSOC_GLOBAL_CONF_NIC_ISO
pub const PSOC_GLOBAL_CONF_NIC_ISO_ISO_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_NIC_ISO_ISO_EN_MASK: c_uint = 0xFFF;
// PSOC_GLOBAL_CONF_MME_ISO
pub const PSOC_GLOBAL_CONF_MME_ISO_MME0_EU_RO_ISO_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MME_ISO_MME0_EU_RO_ISO_MASK: c_uint = 0x3F;
pub const PSOC_GLOBAL_CONF_MME_ISO_MME1_EU_RO_ISO_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_MME_ISO_MME1_EU_RO_ISO_MASK: c_uint = 0xFC0;
pub const PSOC_GLOBAL_CONF_MME_ISO_MME2_EU_RO_ISO_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_MME_ISO_MME2_EU_RO_ISO_MASK: c_uint = 0x3F000;
pub const PSOC_GLOBAL_CONF_MME_ISO_MME3_EU_RO_ISO_SHIFT: c_int = 18;
pub const PSOC_GLOBAL_CONF_MME_ISO_MME3_EU_RO_ISO_MASK: c_uint = 0xFC0000;
// PSOC_GLOBAL_CONF_EDMA_ISO
pub const PSOC_GLOBAL_CONF_EDMA_ISO_ISO_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_EDMA_ISO_ISO_EN_MASK: c_uint = 0xFF;
// PSOC_GLOBAL_CONF_HBM_ISO
pub const PSOC_GLOBAL_CONF_HBM_ISO_HBM_TO_XBAR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_HBM_ISO_HBM_TO_XBAR_MASK: c_uint = 0xFFF;
pub const PSOC_GLOBAL_CONF_HBM_ISO_HBM_TO_HCH_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_HBM_ISO_HBM_TO_HCH_MASK: c_uint = 0x3F0000;
// PSOC_GLOBAL_CONF_XBAR_EDGE_ISO
pub const PSOC_GLOBAL_CONF_XBAR_EDGE_ISO_ISO_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_XBAR_EDGE_ISO_ISO_EN_MASK: c_uint = 0xF;
// PSOC_GLOBAL_CONF_HIF_HMMU_ISO
pub const PSOC_GLOBAL_CONF_HIF_HMMU_ISO_ISO_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_HIF_HMMU_ISO_ISO_EN_MASK: c_uint = 0xFFFF;
// PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_STATUS
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_STATUS_FAILED_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_STATUS_FAILED_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_LSB_ADDR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_LSB_ADDR_MASK: c_uint = 0xFFF;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_PPROT_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_PPROT_MASK: c_uint = 0x7000;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_PWRITE_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_PWRITE_MASK: c_uint = 0x10000;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_FENCE_SHIFT: c_int = 17;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_FENCE_MASK: c_uint = 0x20000;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_DROP_SHIFT: c_int = 18;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_DROP_MASK: c_uint = 0x40000;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_DST_ID_SHIFT: c_int = 20;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_PUSH_DST_ID_MASK: c_uint = 0x3F00000;
// PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_WR
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_WR_PWDATA_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_REQ_WR_PWDATA_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_ASIF_MSTR_RES_STATUS
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_RES_STATUS_RES_READY_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_RES_STATUS_RES_READY_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_RES_STATUS_PSLVERR_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_RES_STATUS_PSLVERR_MASK: c_uint = 0x10;
// PSOC_GLOBAL_CONF_ASIF_MSTR_RES_POP
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_RES_POP_PRDATA_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_RES_POP_PRDATA_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_REQ_BUFF_FULL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_REQ_BUFF_FULL_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_RES_BUFF_FULL_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_RES_BUFF_FULL_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_REQ_ILLEGAL_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_REQ_ILLEGAL_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_RES_DATA_OVRN_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_RES_DATA_OVRN_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_RES_QUAL_OVRN_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_RES_QUAL_OVRN_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_POP_RES_WHILE_EMPTY_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_POP_RES_WHILE_EMPTY_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_PUSH_REQ_WHILE_FULL_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_PUSH_REQ_WHILE_FULL_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_RX_TIMEOUT_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_RX_TIMEOUT_MASK: c_uint = 0x100;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_TX_TIMEOUT_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_TX_TIMEOUT_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_ADDR_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_ADDR_MASK: c_uint = 0xFFF000;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_DST_ID_SHIFT: c_int = 24;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_DST_ID_MASK: c_uint = 0x3F000000;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_DROP_SHIFT: c_int = 31;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_ERROR_PSLVERR_DROP_MASK: c_uint = 0x80000000;
// PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_REQ_BUFF_FULL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_REQ_BUFF_FULL_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_BUFF_FULL_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_BUFF_FULL_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_REQ_ILLEGAL_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_REQ_ILLEGAL_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_DATA_OVRN_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_DATA_OVRN_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_PSLVERR_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_PSLVERR_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_QUAL_OVRN_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_QUAL_OVRN_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_POP_RES_WHILE_EMPTY_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_POP_RES_WHILE_EMPTY_MASK: c_uint = 0x40;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_PUSH_REQ_WHILE_FULL_SHIFT: c_int = 7;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_PUSH_REQ_WHILE_FULL_MASK: c_uint = 0x80;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RX_TIMEOUT_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RX_TIMEOUT_MASK: c_uint = 0x100;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_TX_TIMEOUT_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_TX_TIMEOUT_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_VALID_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_INTR_MASK_MASK_RES_VALID_MASK: c_uint = 0x10000;
// PSOC_GLOBAL_CONF_ASIF_MSTR_STATUS
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_STATUS_REQ_LL_USED_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_STATUS_REQ_LL_USED_MASK: c_uint = 0x3F;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_STATUS_RES_LL_USED_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_STATUS_RES_LL_USED_MASK: c_uint = 0x1F00;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_STATUS_OTF_FIFO_USED_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_ASIF_MSTR_STATUS_OTF_FIFO_USED_MASK: c_uint = 0x3F0000;
// PSOC_GLOBAL_CONF_ASIF_CORE_CFG
pub const PSOC_GLOBAL_CONF_ASIF_CORE_CFG_RISE_DELAY_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_CFG_RISE_DELAY_MASK: c_uint = 0x1F;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_CFG_FALL_DELAY_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_CFG_FALL_DELAY_MASK: c_uint = 0x1F00;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_CFG_DETECT_DELAY_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_CFG_DETECT_DELAY_MASK: c_uint = 0xF0000;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_CFG_FLUSH_DESIGN_SHIFT: c_int = 31;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_CFG_FLUSH_DESIGN_MASK: c_uint = 0x80000000;
// PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_DATA_OVRN_CNT_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_DATA_OVRN_CNT_MASK: c_uint = 0xF;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_QUAL_OVRN_CNT_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_QUAL_OVRN_CNT_MASK: c_uint = 0xF0;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_DETECT_CYCLES_CNT_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_DETECT_CYCLES_CNT_MASK: c_uint = 0xF00;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_CNT_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_CNT_MASK: c_uint = 0xF000;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_TX_CNT_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_TX_CNT_MASK: c_uint = 0xF0000;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_FSM_SHIFT: c_int = 20;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_RX_FSM_MASK: c_uint = 0xF00000;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_TX_FSM_SHIFT: c_int = 24;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_TX_FSM_MASK: c_uint = 0xF000000;
// PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_GLB_CLEAR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_GLB_CLEAR_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_DATA_OVRN_CLR_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_DATA_OVRN_CLR_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_QUAL_OVRN_CLR_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_QUAL_OVRN_CLR_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_CLR_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_RX_CLR_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_TX_CLR_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_DBG_CNT_CLR_TX_CLR_MASK: c_uint = 0x10;
// PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_EN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_EN_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_EN_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_RES_SHIFT: c_int = 2;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_RES_MASK: c_uint = 0x4;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_RES_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_RES_MASK: c_uint = 0x8;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_VALUE_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_RX_TIMEOUT_VALUE_MASK: c_uint = 0x3FF00;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_VALUE_SHIFT: c_int = 20;
pub const PSOC_GLOBAL_CONF_ASIF_CORE_TIMEOUT_CFG_TX_TIMEOUT_VALUE_MASK: c_uint = 0x3FF00000;
// PSOC_GLOBAL_CONF_ASIF_FUNC_INTR_CAUSE
pub const PSOC_GLOBAL_CONF_ASIF_FUNC_INTR_CAUSE_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_FUNC_INTR_CAUSE_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ASIF_FUNC_INTR_CLEAR
pub const PSOC_GLOBAL_CONF_ASIF_FUNC_INTR_CLEAR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_FUNC_INTR_CLEAR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ASIF_FUNC_INTR_MASK
pub const PSOC_GLOBAL_CONF_ASIF_FUNC_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_FUNC_INTR_MASK_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ASIF_ERR_INTR_CAUSE
pub const PSOC_GLOBAL_CONF_ASIF_ERR_INTR_CAUSE_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_ERR_INTR_CAUSE_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ASIF_ERR_INTR_CLEAR
pub const PSOC_GLOBAL_CONF_ASIF_ERR_INTR_CLEAR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_ERR_INTR_CLEAR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ASIF_ERR_INTR_MASK
pub const PSOC_GLOBAL_CONF_ASIF_ERR_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ASIF_ERR_INTR_MASK_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PAD_DEFAULT
pub const PSOC_GLOBAL_CONF_PAD_DEFAULT_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PAD_DEFAULT_VAL_MASK: c_uint = 0xF;
// PSOC_GLOBAL_CONF_PAD_SEL
pub const PSOC_GLOBAL_CONF_PAD_SEL_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PAD_SEL_VAL_MASK: c_uint = 0x3;
// PSOC_GLOBAL_CONF_SMI_ACCESS_EN
pub const PSOC_GLOBAL_CONF_SMI_ACCESS_EN_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SMI_ACCESS_EN_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_SCRAM_EXTMEM_EN
pub const PSOC_GLOBAL_CONF_SCRAM_EXTMEM_EN_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SCRAM_EXTMEM_EN_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_SCRAM_PERM_SEL
pub const PSOC_GLOBAL_CONF_SCRAM_PERM_SEL_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SCRAM_PERM_SEL_VAL_MASK: c_uint = 0xF;
// PSOC_GLOBAL_CONF_SCRAM_POLY_H3
pub const PSOC_GLOBAL_CONF_SCRAM_POLY_H3_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SCRAM_POLY_H3_VAL_MASK: c_uint = 0x1FFFFFFF;
// PSOC_GLOBAL_CONF_CORE_MODE
pub const PSOC_GLOBAL_CONF_CORE_MODE_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_CORE_MODE_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_EXTMEM_ID_LOC
pub const PSOC_GLOBAL_CONF_EXTMEM_ID_LOC_USER_SHRD_IND_LOC_SHIFT: c_int = 24;
pub const PSOC_GLOBAL_CONF_EXTMEM_ID_LOC_USER_SHRD_IND_LOC_MASK: c_uint = 0x3F000000;
// PSOC_GLOBAL_CONF_LBW_USER_CTRL
pub const PSOC_GLOBAL_CONF_LBW_USER_CTRL_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_LBW_USER_CTRL_EN_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ADC_STM_ID
pub const PSOC_GLOBAL_CONF_ADC_STM_ID_STM_MSTR_ID_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_STM_ID_STM_MSTR_ID_MASK: c_uint = 0x3F;
// PSOC_GLOBAL_CONF_ADC
pub const PSOC_GLOBAL_CONF_ADC_INTR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_INTR_MASK: c_uint = 0xF;
// PSOC_GLOBAL_CONF_ADC_INT_MASK
pub const PSOC_GLOBAL_CONF_ADC_INT_MASK_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_INT_MASK_VAL_MASK: c_uint = 0xF;
// PSOC_GLOBAL_CONF_ADC_CLK_FREQ
pub const PSOC_GLOBAL_CONF_ADC_CLK_FREQ_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_CLK_FREQ_VAL_MASK: c_uint = 0xFF;
// PSOC_GLOBAL_CONF_ADC_DELAY_FROM_START
pub const PSOC_GLOBAL_CONF_ADC_DELAY_FROM_START_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_DELAY_FROM_START_VAL_MASK: c_uint = 0xFF;
// PSOC_GLOBAL_CONF_ADC_SAMPLES
pub const PSOC_GLOBAL_CONF_ADC_SAMPLES_DATA_SAMPLES_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_SAMPLES_DATA_SAMPLES_MASK: c_uint = 0x1F;
pub const PSOC_GLOBAL_CONF_ADC_SAMPLES_CLK_SAMPLES_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_ADC_SAMPLES_CLK_SAMPLES_MASK: c_uint = 0x1F00;
// PSOC_GLOBAL_CONF_ADC_TPH_CS
pub const PSOC_GLOBAL_CONF_ADC_TPH_CS_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_TPH_CS_VAL_MASK: c_uint = 0xFF;
// PSOC_GLOBAL_CONF_ADC_LSB_NMSB
pub const PSOC_GLOBAL_CONF_ADC_LSB_NMSB_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_LSB_NMSB_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ADC_ONE_NCONTIUES
pub const PSOC_GLOBAL_CONF_ADC_ONE_NCONTIUES_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_ONE_NCONTIUES_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ADC_BLOCK_ENABLE
pub const PSOC_GLOBAL_CONF_ADC_BLOCK_ENABLE_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_BLOCK_ENABLE_VAL_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_ADC_BLOCK_ENABLE_CH_SEL_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_ADC_BLOCK_ENABLE_CH_SEL_MASK: c_uint = 0x30;
// PSOC_GLOBAL_CONF_ADC_TDV_CSDO
pub const PSOC_GLOBAL_CONF_ADC_TDV_CSDO_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_TDV_CSDO_VAL_MASK: c_uint = 0xFF;
// PSOC_GLOBAL_CONF_ADC_PID_SEL
pub const PSOC_GLOBAL_CONF_ADC_PID_SEL_ADC_SEL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_PID_SEL_ADC_SEL_MASK: c_uint = 0x3;
pub const PSOC_GLOBAL_CONF_ADC_PID_SEL_CHANNEL_SEL_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_ADC_PID_SEL_CHANNEL_SEL_MASK: c_uint = 0x30;
// PSOC_GLOBAL_CONF_ADC_TSU_CSCK
pub const PSOC_GLOBAL_CONF_ADC_TSU_CSCK_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_TSU_CSCK_VAL_MASK: c_uint = 0xFF;
// PSOC_GLOBAL_CONF_ADC_CH_SEL
pub const PSOC_GLOBAL_CONF_ADC_CH_SEL_SEL_DELAY_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_CH_SEL_SEL_DELAY_MASK: c_uint = 0xFF;
pub const PSOC_GLOBAL_CONF_ADC_CH_SEL_SEL_MAX_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_ADC_CH_SEL_SEL_MAX_MASK: c_uint = 0x300;
// PSOC_GLOBAL_CONF_ADC_WRITE_ADDR
pub const PSOC_GLOBAL_CONF_ADC_WRITE_ADDR_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_WRITE_ADDR_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_ADC_CFG_DATA
pub const PSOC_GLOBAL_CONF_ADC_CFG_DATA_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_CFG_DATA_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_AUX_WR_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_AUX_WR_EN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_WR_EN_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_WR_EN_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_GRNT_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_GRNT_MASK: c_uint = 0x1000;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_DATA_SHIFT: c_int = 13;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_DATA_MASK: c_uint = 0x2000;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_TS_SHIFT: c_int = 14;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_TS_MASK: c_uint = 0x4000;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_MARKED_SHIFT: c_int = 15;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_IS_MARKED_MASK: c_uint = 0x8000;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_CAUSE_TRIG_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_ADC_AUX_STM_CTRL_STM_EV_CAUSE_TRIG_MASK: c_uint = 0x10000;
// PSOC_GLOBAL_CONF_TERMINATE_READ_CTRL
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_CTRL_RRESP_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_CTRL_RRESP_VAL_MASK: c_uint = 0x3;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_CTRL_WIN_EN_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_CTRL_WIN_EN_MASK: c_uint = 0xF0;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD0_L
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD0_L_VAL_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD0_L_VAL_MASK: c_uint = 0xFFFFF000;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD0_H
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD0_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD0_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD0_L
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD0_L_VAL_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD0_L_VAL_MASK: c_uint = 0xFFFFF000;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD0_H
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD0_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD0_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD1_L
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD1_L_VAL_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD1_L_VAL_MASK: c_uint = 0xFFFFF000;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD1_H
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD1_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD1_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD1_L
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD1_L_VAL_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD1_L_VAL_MASK: c_uint = 0xFFFFF000;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD1_H
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD1_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD1_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD2_L
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD2_L_VAL_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD2_L_VAL_MASK: c_uint = 0xFFFFF000;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD2_H
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD2_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD2_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD2_L
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD2_L_VAL_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD2_L_VAL_MASK: c_uint = 0xFFFFF000;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD2_H
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD2_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD2_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD3_L
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD3_L_VAL_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD3_L_VAL_MASK: c_uint = 0xFFFFF000;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD3_H
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD3_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MIN_AD3_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD3_L
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD3_L_VAL_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD3_L_VAL_MASK: c_uint = 0xFFFFF000;
// PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD3_H
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD3_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_TERMINATE_READ_MAX_AD3_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_SCRATCHPAD_INIT_CTRL
pub const PSOC_GLOBAL_CONF_SCRATCHPAD_INIT_CTRL_START_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_SCRATCHPAD_INIT_CTRL_START_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_SCRATCHPAD_INIT_CTRL_DONE_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_SCRATCHPAD_INIT_CTRL_DONE_MASK: c_uint = 0x10;
// PSOC_GLOBAL_CONF_RST_OUT_CTRL
pub const PSOC_GLOBAL_CONF_RST_OUT_CTRL_CLR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_RST_OUT_CTRL_CLR_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_MEM_CPY_CTRL
pub const PSOC_GLOBAL_CONF_MEM_CPY_CTRL_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_CTRL_EN_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_MEM_CPY_STATUS
pub const PSOC_GLOBAL_CONF_MEM_CPY_STATUS_DONE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_STATUS_DONE_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_MEM_CPY_START_ADDR_H
pub const PSOC_GLOBAL_CONF_MEM_CPY_START_ADDR_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_START_ADDR_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_MEM_CPY_START_ADDR_L
pub const PSOC_GLOBAL_CONF_MEM_CPY_START_ADDR_L_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_START_ADDR_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_MEM_CPY_DEST_ADDR_H
pub const PSOC_GLOBAL_CONF_MEM_CPY_DEST_ADDR_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_DEST_ADDR_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_MEM_CPY_DEST_ADDR_L
pub const PSOC_GLOBAL_CONF_MEM_CPY_DEST_ADDR_L_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_DEST_ADDR_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_MEM_CPY_CTRL2
pub const PSOC_GLOBAL_CONF_MEM_CPY_CTRL2_MEM_SIZE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_CTRL2_MEM_SIZE_MASK: c_uint = 0xFFFF;
pub const PSOC_GLOBAL_CONF_MEM_CPY_CTRL2_WR_OS_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_MEM_CPY_CTRL2_WR_OS_MASK: c_uint = 0x3F0000;
pub const PSOC_GLOBAL_CONF_MEM_CPY_CTRL2_RD_OS_SHIFT: c_int = 24;
pub const PSOC_GLOBAL_CONF_MEM_CPY_CTRL2_RD_OS_MASK: c_uint = 0x3F000000;
pub const PSOC_GLOBAL_CONF_MEM_CPY_CTRL2_USE_CONST_SHIFT: c_int = 31;
pub const PSOC_GLOBAL_CONF_MEM_CPY_CTRL2_USE_CONST_MASK: c_uint = 0x80000000;
// PSOC_GLOBAL_CONF_MEM_CPY_CONST
pub const PSOC_GLOBAL_CONF_MEM_CPY_CONST_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_CONST_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_MEM_CPY_CURR_ADDR_H
pub const PSOC_GLOBAL_CONF_MEM_CPY_CURR_ADDR_H_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_CURR_ADDR_H_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_MEM_CPY_CURR_ADDR_L
pub const PSOC_GLOBAL_CONF_MEM_CPY_CURR_ADDR_L_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_CURR_ADDR_L_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_AXI_SPLIT_CFG
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_CFG_FORCE_RESP_OK_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_CFG_FORCE_RESP_OK_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_CFG_FORCE_WR_BUF_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_CFG_FORCE_WR_BUF_MASK: c_uint = 0x2;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_CFG_NUM_RD_OS_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_CFG_NUM_RD_OS_MASK: c_uint = 0xFF00;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_CFG_NUM_WR_OS_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_CFG_NUM_WR_OS_MASK: c_uint = 0xFF0000;
// PSOC_GLOBAL_CONF_AXI_SPLIT_PROT_CFG1
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_PROT_CFG1_OVRD_RD_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_PROT_CFG1_OVRD_RD_EN_MASK: c_uint = 0x7;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_PROT_CFG1_OVRD_RD_VAL_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_PROT_CFG1_OVRD_RD_VAL_MASK: c_uint = 0x700;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_PROT_CFG1_OVRD_WR_EN_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_PROT_CFG1_OVRD_WR_EN_MASK: c_uint = 0x70000;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_PROT_CFG1_OVRD_WR_VAL_SHIFT: c_int = 24;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_PROT_CFG1_OVRD_WR_VAL_MASK: c_uint = 0x7000000;
// PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG0
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG0_OVRD_RD_EN_31_0_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG0_OVRD_RD_EN_31_0_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG1
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG1_OVRD_RD_31_0_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG1_OVRD_RD_31_0_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG2
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG2_OVRD_WR_EN_31_0_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG2_OVRD_WR_EN_31_0_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG3
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG3_OVRD_WR_31_0_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG3_OVRD_WR_31_0_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG4
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG4_OVRD_RD_EN_39_32_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG4_OVRD_RD_EN_39_32_MASK: c_uint = 0xFF;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG4_OVRD_RD_39_32_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG4_OVRD_RD_39_32_MASK: c_uint = 0xFF00;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG4_OVRD_WR_EN_39_32_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG4_OVRD_WR_EN_39_32_MASK: c_uint = 0xFF0000;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG4_OVRD_WR_39_32_SHIFT: c_int = 24;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_USER_CFG4_OVRD_WR_39_32_MASK: c_uint = 0xFF000000;
// PSOC_GLOBAL_CONF_LBW_ARUSER_OVRD
pub const PSOC_GLOBAL_CONF_LBW_ARUSER_OVRD_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_LBW_ARUSER_OVRD_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_LBW_ARUSER_OVRD_EN
pub const PSOC_GLOBAL_CONF_LBW_ARUSER_OVRD_EN_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_LBW_ARUSER_OVRD_EN_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_LBW_AWUSER_OVRD
pub const PSOC_GLOBAL_CONF_LBW_AWUSER_OVRD_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_LBW_AWUSER_OVRD_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_LBW_AWUSER_OVRD_EN
pub const PSOC_GLOBAL_CONF_LBW_AWUSER_OVRD_EN_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_LBW_AWUSER_OVRD_EN_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_MAIN_AXI_SPLIT_CFG2
pub const PSOC_GLOBAL_CONF_MAIN_AXI_SPLIT_CFG2_INTR_CAUSE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MAIN_AXI_SPLIT_CFG2_INTR_CAUSE_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_MAIN_AXI_SPLIT_CFG2_INTR_MASK_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_MAIN_AXI_SPLIT_CFG2_INTR_MASK_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_MAIN_AXI_SPLIT_CFG2_NO_WR_INFLIGHT_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_MAIN_AXI_SPLIT_CFG2_NO_WR_INFLIGHT_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_MAIN_AXI_SPLIT_CFG2_SEI_INTR_ID_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_MAIN_AXI_SPLIT_CFG2_SEI_INTR_ID_MASK: c_uint = 0x7FFFFF00;
// PSOC_GLOBAL_CONF_BOOTROM_AXI_SPLIT_CFG2
pub const PSOC_GLOBAL_CONF_BOOTROM_AXI_SPLIT_CFG2_INTR_CAUSE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BOOTROM_AXI_SPLIT_CFG2_INTR_CAUSE_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_BOOTROM_AXI_SPLIT_CFG2_INTR_MASK_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_BOOTROM_AXI_SPLIT_CFG2_INTR_MASK_MASK: c_uint = 0x10;
pub const PSOC_GLOBAL_CONF_BOOTROM_AXI_SPLIT_CFG2_NO_WR_INFLIGHT_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_BOOTROM_AXI_SPLIT_CFG2_NO_WR_INFLIGHT_MASK: c_uint = 0x20;
pub const PSOC_GLOBAL_CONF_BOOTROM_AXI_SPLIT_CFG2_SEI_INTR_ID_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_BOOTROM_AXI_SPLIT_CFG2_SEI_INTR_ID_MASK: c_uint = 0xFFFFF00;
// PSOC_GLOBAL_CONF_AXI_SPLIT_INTR_CLEAR
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_INTR_CLEAR_MAIN_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_INTR_CLEAR_MAIN_IND_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_INTR_CLEAR_BOOTROM_IND_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_AXI_SPLIT_INTR_CLEAR_BOOTROM_IND_MASK: c_uint = 0x2;
// PSOC_GLOBAL_CONF_MEM_CPY_PROT
pub const PSOC_GLOBAL_CONF_MEM_CPY_PROT_AR_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_PROT_AR_MASK: c_uint = 0x7;
pub const PSOC_GLOBAL_CONF_MEM_CPY_PROT_AW_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_MEM_CPY_PROT_AW_MASK: c_uint = 0x70;
// PSOC_GLOBAL_CONF_ISOLATE_INPUTS
pub const PSOC_GLOBAL_CONF_ISOLATE_INPUTS_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ISOLATE_INPUTS_EN_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_MESH_TO_BOOTROM_CTRL
pub const PSOC_GLOBAL_CONF_MESH_TO_BOOTROM_CTRL_BLOCK_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MESH_TO_BOOTROM_CTRL_BLOCK_EN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_MESH_TO_BOOTROM_CTRL_BLOCK_BRESP_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_MESH_TO_BOOTROM_CTRL_BLOCK_BRESP_MASK: c_uint = 0x6;
pub const PSOC_GLOBAL_CONF_MESH_TO_BOOTROM_CTRL_BLOCK_RRESP_SHIFT: c_int = 5;
pub const PSOC_GLOBAL_CONF_MESH_TO_BOOTROM_CTRL_BLOCK_RRESP_MASK: c_uint = 0x60;
// PSOC_GLOBAL_CONF_ARC_JT_SEL
pub const PSOC_GLOBAL_CONF_ARC_JT_SEL_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ARC_JT_SEL_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_PLL_DUMP_CRTL
pub const PSOC_GLOBAL_CONF_PLL_DUMP_CRTL_PLL_SEL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_PLL_DUMP_CRTL_PLL_SEL_MASK: c_uint = 0x3F;
pub const PSOC_GLOBAL_CONF_PLL_DUMP_CRTL_BIT_SEL_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_PLL_DUMP_CRTL_BIT_SEL_MASK: c_uint = 0xF00;
// PSOC_GLOBAL_CONF_MEM_CPY_AXUSER
pub const PSOC_GLOBAL_CONF_MEM_CPY_AXUSER_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_MEM_CPY_AXUSER_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_BTL_AXUSER
pub const PSOC_GLOBAL_CONF_BTL_AXUSER_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BTL_AXUSER_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL0
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL0_ADDR_EXTMEM_PC_LOC0_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL0_ADDR_EXTMEM_PC_LOC0_MASK: c_uint = 0x3F;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL0_ADDR_EXTMEM_PC_LOC1_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL0_ADDR_EXTMEM_PC_LOC1_MASK: c_uint = 0xFC0;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL0_ADDR_EXTMEM_PC_LOC2_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL0_ADDR_EXTMEM_PC_LOC2_MASK: c_uint = 0x3F000;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL0_ADDR_EXTMEM_PC_LOC3_SHIFT: c_int = 18;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL0_ADDR_EXTMEM_PC_LOC3_MASK: c_uint = 0xFC0000;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL0_ADDR_EXTMEM_HBM_LOC0_SHIFT: c_int = 24;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL0_ADDR_EXTMEM_HBM_LOC0_MASK: c_uint = 0x3F000000;
// PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_ADDR_EXTMEM_HBM_LOC1_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_ADDR_EXTMEM_HBM_LOC1_MASK: c_uint = 0x3F;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_ADDR_EXTMEM_HBM_LOC2_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_ADDR_EXTMEM_HBM_LOC2_MASK: c_uint = 0xFC0;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_NON_LIN_PC_EN_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_NON_LIN_PC_EN_MASK: c_uint = 0x1000;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_NON_LIN_HBM_CNT_EN_SHIFT: c_int = 13;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_NON_LIN_HBM_CNT_EN_MASK: c_uint = 0x2000;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_NON_LIN_HBM_ALL_ADDR_EN_SHIFT: c_int = 14;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_NON_LIN_HBM_ALL_ADDR_EN_MASK: c_uint = 0x4000;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_NON_LIN_HBM_ALL_ADDR_MASK_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_NON_LIN_HBM_ALL_ADDR_MASK_MASK: c_uint = 0xFF0000;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_HBM_NUM_SHIFT: c_int = 24;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL1_HBM_NUM_MASK: c_uint = 0x7000000;
// PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL2
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL2_SCRAM_NONLIN_HBM_CNT_MASK_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL2_SCRAM_NONLIN_HBM_CNT_MASK_MASK: c_uint = 0xFFFF;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL2_SCRAM_NONLIN_EXTM_PC_MASK_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL2_SCRAM_NONLIN_EXTM_PC_MASK_MASK: c_uint = 0xFFFF0000;
// PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP0_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP0_MASK: c_uint = 0x7;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP1_SHIFT: c_int = 3;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP1_MASK: c_uint = 0x38;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP2_SHIFT: c_int = 6;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP2_MASK: c_uint = 0x1C0;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP3_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP3_MASK: c_uint = 0xE00;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP4_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP4_MASK: c_uint = 0x7000;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP5_SHIFT: c_int = 15;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_NL_SRC_CTRL3_HBM_MAP5_MASK: c_uint = 0x38000;
// PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_EN_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_EN_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_AXI_RESP_SHIFT: c_int = 4;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_AXI_RESP_MASK: c_uint = 0x30;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_DRAIN_HBW_SHIFT: c_int = 8;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_DRAIN_HBW_MASK: c_uint = 0x100;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_DRAIN_LBW_SHIFT: c_int = 9;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_DRAIN_LBW_MASK: c_uint = 0x200;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_INTR_MASK_HBW_SHIFT: c_int = 12;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_INTR_MASK_HBW_MASK: c_uint = 0x1000;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_INTR_MASK_LBW_SHIFT: c_int = 13;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_CTRL_INTR_MASK_LBW_MASK: c_uint = 0x2000;
// PSOC_GLOBAL_CONF_AXI_DRAIN_TIMEOUT
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_TIMEOUT_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_TIMEOUT_VAL_MASK: c_uint = 0xFFFFFFFF;
// PSOC_GLOBAL_CONF_AXI_DRAIN_INTR
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_INTR_HBW_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_INTR_HBW_IND_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_INTR_LBW_IND_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_AXI_DRAIN_INTR_LBW_IND_MASK: c_uint = 0x2;
// PSOC_GLOBAL_CONF_BTL_STOP_SPI_CLK
pub const PSOC_GLOBAL_CONF_BTL_STOP_SPI_CLK_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_BTL_STOP_SPI_CLK_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ECO_INTR_CAUSE
pub const PSOC_GLOBAL_CONF_ECO_INTR_CAUSE_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ECO_INTR_CAUSE_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ECO_INTR_CLEAR
pub const PSOC_GLOBAL_CONF_ECO_INTR_CLEAR_IND_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ECO_INTR_CLEAR_IND_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_ECO_INTR_MASK
pub const PSOC_GLOBAL_CONF_ECO_INTR_MASK_VAL_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_ECO_INTR_MASK_VAL_MASK: c_uint = 0x1;
// PSOC_GLOBAL_CONF_DFT_APB_CONTROL
pub const PSOC_GLOBAL_CONF_DFT_APB_CONTROL_SPIF_MODE_SHIFT: c_int = 0;
pub const PSOC_GLOBAL_CONF_DFT_APB_CONTROL_SPIF_MODE_MASK: c_uint = 0x1;
pub const PSOC_GLOBAL_CONF_DFT_APB_CONTROL_RESERVED_OUT_SHIFT: c_int = 1;
pub const PSOC_GLOBAL_CONF_DFT_APB_CONTROL_RESERVED_OUT_MASK: c_uint = 0xFFFE;
pub const PSOC_GLOBAL_CONF_DFT_APB_CONTROL_RESERVED_IN_SHIFT: c_int = 16;
pub const PSOC_GLOBAL_CONF_DFT_APB_CONTROL_RESERVED_IN_MASK: c_uint = 0xFFFF0000;
