//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/media/i2c/ccs/ccs-regs.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause
// Copyright (C) 2019--2020 Intel Corporation
//
// Generated by Documentation/driver-api/media/drivers/ccs/mk-ccs-regs;
// do not modify.
//

pub const CCS_MIPI_CCS_VERSION_V1_0: c_uint = 0x10;
pub const CCS_MIPI_CCS_VERSION_V1_1: c_uint = 0x11;

pub const CCS_MIPI_CCS_VERSION_MAJOR_MASK: c_uint = 0xf0;

pub const CCS_MIPI_CCS_VERSION_MINOR_MASK: c_uint = 0xf;

pub const CCS_MODULE_DATE_PHASE_MASK: c_uint = 0x7;

pub const CCS_FRAME_FORMAT_MODEL_SUBTYPE_ROWS_MASK: c_uint = 0xf;

pub const CCS_FRAME_FORMAT_MODEL_SUBTYPE_COLUMNS_MASK: c_uint = 0xf0;

pub const CCS_FRAME_FORMAT_DESCRIPTOR_PIXELS_MASK: c_uint = 0xfff;

pub const CCS_FRAME_FORMAT_DESCRIPTOR_PCODE_MASK: c_uint = 0xf000;

pub const CCS_FRAME_FORMAT_DESCRIPTOR_4_PIXELS_MASK: c_uint = 0xffff;

pub const CCS_FRAME_FORMAT_DESCRIPTOR_4_PCODE_MASK: c_uint = 0xf0000000;

pub const CCS_DATA_FORMAT_MODEL_SUBTYPE_ROWS_MASK: c_uint = 0xf;

pub const CCS_DATA_FORMAT_MODEL_SUBTYPE_COLUMNS_MASK: c_uint = 0xf0;

pub const CCS_DATA_FORMAT_DESCRIPTOR_COMPRESSED_MASK: c_uint = 0xff;

pub const CCS_DATA_FORMAT_DESCRIPTOR_UNCOMPRESSED_MASK: c_uint = 0xff00;

pub const CCS_HDR_RESOLUTION_REDUCTION_ROW_MASK: c_uint = 0xf;

pub const CCS_HDR_RESOLUTION_REDUCTION_COLUMN_MASK: c_uint = 0xf0;

pub const CCS_PLL_MODE_MASK: c_uint = 0x1;

pub const CCS_TGR_PREAMBLE_LENGTH_BEGIN_PREAMBLE_LENGTH_MASK: c_uint = 0x3f;

pub const CCS_TGR_POST_LENGTH_POST_LENGTH_MASK: c_uint = 0x1f;

pub const CCS_TGR_PREAMBLE_PROG_SEQUENCE_SYMBOL_N_1_MASK: c_uint = 0x38;

pub const CCS_TGR_PREAMBLE_PROG_SEQUENCE_SYMBOL_N_MASK: c_uint = 0x7;

pub const CCS_SCRAMBLING_CTRL_MASK: c_uint = 0xc;

pub const CCS_HDR_RESOLUTION_SUB_TYPE_ROW_MASK: c_uint = 0xf;

pub const CCS_HDR_RESOLUTION_SUB_TYPE_COLUMN_MASK: c_uint = 0xf0;

pub const CCS_PN9_MISC_CAPABILITY_NUM_PIXELS_MASK: c_uint = 0x7;

pub const CCS_ALPS_CAPABILITY_CPHY_ALP_NOT_SUPPORTED: c_uint = 0xc;
pub const CCS_ALPS_CAPABILITY_CPHY_ALP_SUPPORTED: c_uint = 0xd;
pub const CCS_ALPS_CAPABILITY_CPHY_CONTROLLABLE_ALP: c_uint = 0xe;

pub const CCS_SCRAMBLING_CAPABILITY_MAX_SEEDS_PER_LANE_C_MASK: c_uint = 0x6;

pub const CCS_SCRAMBLING_CAPABILITY_NUM_SEED_REGS_MASK: c_uint = 0x38;

pub const CCS_CPHY_SF_TWAKEUP_MASK: c_uint = 0xf;

pub const CCS_CPHY_SF_TINIT_MASK: c_uint = 0xf0;

pub const CCS_DPHY_LIMITS_1_THS_PREPARE_MASK: c_uint = 0xf;

pub const CCS_DPHY_LIMITS_1_THS_ZERO_MASK: c_uint = 0xf0;

pub const CCS_DPHY_LIMITS_2_THS_TRAIL_MASK: c_uint = 0xf;

pub const CCS_DPHY_LIMITS_2_TCLK_TRAIL_MIN_MASK: c_uint = 0xf0;

pub const CCS_DPHY_LIMITS_3_TCLK_PREPARE_MASK: c_uint = 0xf;

pub const CCS_DPHY_LIMITS_3_TCLK_ZERO_MASK: c_uint = 0xf0;

pub const CCS_DPHY_LIMITS_4_TCLK_POST_MASK: c_uint = 0xf;

pub const CCS_DPHY_LIMITS_4_TLPX_MASK: c_uint = 0xf0;

pub const CCS_DPHY_LIMITS_5_THS_EXIT_MASK: c_uint = 0xf;

pub const CCS_DPHY_LIMITS_5_TWAKEUP_MASK: c_uint = 0xf0;

pub const CCS_DPHY_LIMITS_6_TINIT_MASK: c_uint = 0xf;

pub const CCS_CPHY_LIMITS_1_T3_PREPARE_MAX_MASK: c_uint = 0xf;

pub const CCS_CPHY_LIMITS_1_T3_LPX_MAX_MASK: c_uint = 0xf0;

pub const CCS_CPHY_LIMITS_2_THS_EXIT_MAX_MASK: c_uint = 0xf;

pub const CCS_CPHY_LIMITS_2_TWAKEUP_MAX_MASK: c_uint = 0xf0;

pub const CCS_CPHY_LIMITS_3_TINIT_MAX_MASK: c_uint = 0xf;

pub const CCS_BINNING_SUB_TYPE_ROW_MASK: c_uint = 0xf;

pub const CCS_BINNING_SUB_TYPE_COLUMN_MASK: c_uint = 0xf0;

