//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/media/i2c/ccs/ccs-limits.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause
// Copyright (C) 2019--2020 Intel Corporation
//
// Generated by Documentation/driver-api/media/drivers/ccs/mk-ccs-regs;
// do not modify.
//

#[repr(C)]
#[derive(Copy, Clone)]
pub struct ccs_limit {
    pub reg: u32,
    pub size: u16,
    pub flags: u16,
    pub name: *const c_char,
}

pub const CCS_L_FRAME_FORMAT_MODEL_TYPE: c_int = 0;
pub const CCS_L_FRAME_FORMAT_MODEL_SUBTYPE: c_int = 1;
pub const CCS_L_FRAME_FORMAT_DESCRIPTOR: c_int = 2;

pub const CCS_L_FRAME_FORMAT_DESCRIPTOR_4: c_int = 3;

pub const CCS_L_ANALOG_GAIN_CAPABILITY: c_int = 4;
pub const CCS_L_ANALOG_GAIN_CODE_MIN: c_int = 5;
pub const CCS_L_ANALOG_GAIN_CODE_MAX: c_int = 6;
pub const CCS_L_ANALOG_GAIN_CODE_STEP: c_int = 7;
pub const CCS_L_ANALOG_GAIN_TYPE: c_int = 8;
pub const CCS_L_ANALOG_GAIN_M0: c_int = 9;
pub const CCS_L_ANALOG_GAIN_C0: c_int = 10;
pub const CCS_L_ANALOG_GAIN_M1: c_int = 11;
pub const CCS_L_ANALOG_GAIN_C1: c_int = 12;
pub const CCS_L_ANALOG_LINEAR_GAIN_MIN: c_int = 13;
pub const CCS_L_ANALOG_LINEAR_GAIN_MAX: c_int = 14;
pub const CCS_L_ANALOG_LINEAR_GAIN_STEP_SIZE: c_int = 15;
pub const CCS_L_ANALOG_EXPONENTIAL_GAIN_MIN: c_int = 16;
pub const CCS_L_ANALOG_EXPONENTIAL_GAIN_MAX: c_int = 17;
pub const CCS_L_ANALOG_EXPONENTIAL_GAIN_STEP_SIZE: c_int = 18;
pub const CCS_L_DATA_FORMAT_MODEL_TYPE: c_int = 19;
pub const CCS_L_DATA_FORMAT_MODEL_SUBTYPE: c_int = 20;
pub const CCS_L_DATA_FORMAT_DESCRIPTOR: c_int = 21;

pub const CCS_L_INTEGRATION_TIME_CAPABILITY: c_int = 22;
pub const CCS_L_COARSE_INTEGRATION_TIME_MIN: c_int = 23;
pub const CCS_L_COARSE_INTEGRATION_TIME_MAX_MARGIN: c_int = 24;
pub const CCS_L_FINE_INTEGRATION_TIME_MIN: c_int = 25;
pub const CCS_L_FINE_INTEGRATION_TIME_MAX_MARGIN: c_int = 26;
pub const CCS_L_DIGITAL_GAIN_CAPABILITY: c_int = 27;
pub const CCS_L_DIGITAL_GAIN_MIN: c_int = 28;
pub const CCS_L_DIGITAL_GAIN_MAX: c_int = 29;
pub const CCS_L_DIGITAL_GAIN_STEP_SIZE: c_int = 30;
pub const CCS_L_PEDESTAL_CAPABILITY: c_int = 31;
pub const CCS_L_ADC_CAPABILITY: c_int = 32;
pub const CCS_L_ADC_BIT_DEPTH_CAPABILITY: c_int = 33;
pub const CCS_L_MIN_EXT_CLK_FREQ_MHZ: c_int = 34;
pub const CCS_L_MAX_EXT_CLK_FREQ_MHZ: c_int = 35;
pub const CCS_L_MIN_PRE_PLL_CLK_DIV: c_int = 36;
pub const CCS_L_MAX_PRE_PLL_CLK_DIV: c_int = 37;
pub const CCS_L_MIN_PLL_IP_CLK_FREQ_MHZ: c_int = 38;
pub const CCS_L_MAX_PLL_IP_CLK_FREQ_MHZ: c_int = 39;
pub const CCS_L_MIN_PLL_MULTIPLIER: c_int = 40;
pub const CCS_L_MAX_PLL_MULTIPLIER: c_int = 41;
pub const CCS_L_MIN_PLL_OP_CLK_FREQ_MHZ: c_int = 42;
pub const CCS_L_MAX_PLL_OP_CLK_FREQ_MHZ: c_int = 43;
pub const CCS_L_MIN_VT_SYS_CLK_DIV: c_int = 44;
pub const CCS_L_MAX_VT_SYS_CLK_DIV: c_int = 45;
pub const CCS_L_MIN_VT_SYS_CLK_FREQ_MHZ: c_int = 46;
pub const CCS_L_MAX_VT_SYS_CLK_FREQ_MHZ: c_int = 47;
pub const CCS_L_MIN_VT_PIX_CLK_FREQ_MHZ: c_int = 48;
pub const CCS_L_MAX_VT_PIX_CLK_FREQ_MHZ: c_int = 49;
pub const CCS_L_MIN_VT_PIX_CLK_DIV: c_int = 50;
pub const CCS_L_MAX_VT_PIX_CLK_DIV: c_int = 51;
pub const CCS_L_CLOCK_CALCULATION: c_int = 52;
pub const CCS_L_NUM_OF_VT_LANES: c_int = 53;
pub const CCS_L_NUM_OF_OP_LANES: c_int = 54;
pub const CCS_L_OP_BITS_PER_LANE: c_int = 55;
pub const CCS_L_MIN_FRAME_LENGTH_LINES: c_int = 56;
pub const CCS_L_MAX_FRAME_LENGTH_LINES: c_int = 57;
pub const CCS_L_MIN_LINE_LENGTH_PCK: c_int = 58;
pub const CCS_L_MAX_LINE_LENGTH_PCK: c_int = 59;
pub const CCS_L_MIN_LINE_BLANKING_PCK: c_int = 60;
pub const CCS_L_MIN_FRAME_BLANKING_LINES: c_int = 61;
pub const CCS_L_MIN_LINE_LENGTH_PCK_STEP_SIZE: c_int = 62;
pub const CCS_L_TIMING_MODE_CAPABILITY: c_int = 63;
pub const CCS_L_FRAME_MARGIN_MAX_VALUE: c_int = 64;
pub const CCS_L_FRAME_MARGIN_MIN_VALUE: c_int = 65;
pub const CCS_L_GAIN_DELAY_TYPE: c_int = 66;
pub const CCS_L_MIN_OP_SYS_CLK_DIV: c_int = 67;
pub const CCS_L_MAX_OP_SYS_CLK_DIV: c_int = 68;
pub const CCS_L_MIN_OP_SYS_CLK_FREQ_MHZ: c_int = 69;
pub const CCS_L_MAX_OP_SYS_CLK_FREQ_MHZ: c_int = 70;
pub const CCS_L_MIN_OP_PIX_CLK_DIV: c_int = 71;
pub const CCS_L_MAX_OP_PIX_CLK_DIV: c_int = 72;
pub const CCS_L_MIN_OP_PIX_CLK_FREQ_MHZ: c_int = 73;
pub const CCS_L_MAX_OP_PIX_CLK_FREQ_MHZ: c_int = 74;
pub const CCS_L_X_ADDR_MIN: c_int = 75;
pub const CCS_L_Y_ADDR_MIN: c_int = 76;
pub const CCS_L_X_ADDR_MAX: c_int = 77;
pub const CCS_L_Y_ADDR_MAX: c_int = 78;
pub const CCS_L_MIN_X_OUTPUT_SIZE: c_int = 79;
pub const CCS_L_MIN_Y_OUTPUT_SIZE: c_int = 80;
pub const CCS_L_MAX_X_OUTPUT_SIZE: c_int = 81;
pub const CCS_L_MAX_Y_OUTPUT_SIZE: c_int = 82;
pub const CCS_L_X_ADDR_START_DIV_CONSTANT: c_int = 83;
pub const CCS_L_Y_ADDR_START_DIV_CONSTANT: c_int = 84;
pub const CCS_L_X_ADDR_END_DIV_CONSTANT: c_int = 85;
pub const CCS_L_Y_ADDR_END_DIV_CONSTANT: c_int = 86;
pub const CCS_L_X_SIZE_DIV: c_int = 87;
pub const CCS_L_Y_SIZE_DIV: c_int = 88;
pub const CCS_L_X_OUTPUT_DIV: c_int = 89;
pub const CCS_L_Y_OUTPUT_DIV: c_int = 90;
pub const CCS_L_NON_FLEXIBLE_RESOLUTION_SUPPORT: c_int = 91;
pub const CCS_L_MIN_OP_PRE_PLL_CLK_DIV: c_int = 92;
pub const CCS_L_MAX_OP_PRE_PLL_CLK_DIV: c_int = 93;
pub const CCS_L_MIN_OP_PLL_IP_CLK_FREQ_MHZ: c_int = 94;
pub const CCS_L_MAX_OP_PLL_IP_CLK_FREQ_MHZ: c_int = 95;
pub const CCS_L_MIN_OP_PLL_MULTIPLIER: c_int = 96;
pub const CCS_L_MAX_OP_PLL_MULTIPLIER: c_int = 97;
pub const CCS_L_MIN_OP_PLL_OP_CLK_FREQ_MHZ: c_int = 98;
pub const CCS_L_MAX_OP_PLL_OP_CLK_FREQ_MHZ: c_int = 99;
pub const CCS_L_CLOCK_TREE_PLL_CAPABILITY: c_int = 100;
pub const CCS_L_CLOCK_CAPA_TYPE_CAPABILITY: c_int = 101;
pub const CCS_L_MIN_EVEN_INC: c_int = 102;
pub const CCS_L_MIN_ODD_INC: c_int = 103;
pub const CCS_L_MAX_EVEN_INC: c_int = 104;
pub const CCS_L_MAX_ODD_INC: c_int = 105;
pub const CCS_L_AUX_SUBSAMP_CAPABILITY: c_int = 106;
pub const CCS_L_AUX_SUBSAMP_MONO_CAPABILITY: c_int = 107;
pub const CCS_L_MONOCHROME_CAPABILITY: c_int = 108;
pub const CCS_L_PIXEL_READOUT_CAPABILITY: c_int = 109;
pub const CCS_L_MIN_EVEN_INC_MONO: c_int = 110;
pub const CCS_L_MAX_EVEN_INC_MONO: c_int = 111;
pub const CCS_L_MIN_ODD_INC_MONO: c_int = 112;
pub const CCS_L_MAX_ODD_INC_MONO: c_int = 113;
pub const CCS_L_MIN_EVEN_INC_BC2: c_int = 114;
pub const CCS_L_MAX_EVEN_INC_BC2: c_int = 115;
pub const CCS_L_MIN_ODD_INC_BC2: c_int = 116;
pub const CCS_L_MAX_ODD_INC_BC2: c_int = 117;
pub const CCS_L_MIN_EVEN_INC_MONO_BC2: c_int = 118;
pub const CCS_L_MAX_EVEN_INC_MONO_BC2: c_int = 119;
pub const CCS_L_MIN_ODD_INC_MONO_BC2: c_int = 120;
pub const CCS_L_MAX_ODD_INC_MONO_BC2: c_int = 121;
pub const CCS_L_SCALING_CAPABILITY: c_int = 122;
pub const CCS_L_SCALER_M_MIN: c_int = 123;
pub const CCS_L_SCALER_M_MAX: c_int = 124;
pub const CCS_L_SCALER_N_MIN: c_int = 125;
pub const CCS_L_SCALER_N_MAX: c_int = 126;
pub const CCS_L_DIGITAL_CROP_CAPABILITY: c_int = 127;
pub const CCS_L_HDR_CAPABILITY_1: c_int = 128;
pub const CCS_L_MIN_HDR_BIT_DEPTH: c_int = 129;
pub const CCS_L_HDR_RESOLUTION_SUB_TYPES: c_int = 130;
pub const CCS_L_HDR_RESOLUTION_SUB_TYPE: c_int = 131;

pub const CCS_L_HDR_CAPABILITY_2: c_int = 132;
pub const CCS_L_MAX_HDR_BIT_DEPTH: c_int = 133;
pub const CCS_L_USL_SUPPORT_CAPABILITY: c_int = 134;
pub const CCS_L_USL_CLOCK_MODE_D_CAPABILITY: c_int = 135;
pub const CCS_L_MIN_OP_SYS_CLK_DIV_REV: c_int = 136;
pub const CCS_L_MAX_OP_SYS_CLK_DIV_REV: c_int = 137;
pub const CCS_L_MIN_OP_PIX_CLK_DIV_REV: c_int = 138;
pub const CCS_L_MAX_OP_PIX_CLK_DIV_REV: c_int = 139;
pub const CCS_L_MIN_OP_SYS_CLK_FREQ_REV_MHZ: c_int = 140;
pub const CCS_L_MAX_OP_SYS_CLK_FREQ_REV_MHZ: c_int = 141;
pub const CCS_L_MIN_OP_PIX_CLK_FREQ_REV_MHZ: c_int = 142;
pub const CCS_L_MAX_OP_PIX_CLK_FREQ_REV_MHZ: c_int = 143;
pub const CCS_L_MAX_BITRATE_REV_D_MODE_MBPS: c_int = 144;
pub const CCS_L_MAX_SYMRATE_REV_C_MODE_MSPS: c_int = 145;
pub const CCS_L_COMPRESSION_CAPABILITY: c_int = 146;
pub const CCS_L_TEST_MODE_CAPABILITY: c_int = 147;
pub const CCS_L_PN9_DATA_FORMAT1: c_int = 148;
pub const CCS_L_PN9_DATA_FORMAT2: c_int = 149;
pub const CCS_L_PN9_DATA_FORMAT3: c_int = 150;
pub const CCS_L_PN9_DATA_FORMAT4: c_int = 151;
pub const CCS_L_PN9_MISC_CAPABILITY: c_int = 152;
pub const CCS_L_TEST_PATTERN_CAPABILITY: c_int = 153;
pub const CCS_L_PATTERN_SIZE_DIV_M1: c_int = 154;
pub const CCS_L_FIFO_SUPPORT_CAPABILITY: c_int = 155;
pub const CCS_L_PHY_CTRL_CAPABILITY: c_int = 156;
pub const CCS_L_CSI_DPHY_LANE_MODE_CAPABILITY: c_int = 157;
pub const CCS_L_CSI_SIGNALING_MODE_CAPABILITY: c_int = 158;
pub const CCS_L_FAST_STANDBY_CAPABILITY: c_int = 159;
pub const CCS_L_CSI_ADDRESS_CONTROL_CAPABILITY: c_int = 160;
pub const CCS_L_DATA_TYPE_CAPABILITY: c_int = 161;
pub const CCS_L_CSI_CPHY_LANE_MODE_CAPABILITY: c_int = 162;
pub const CCS_L_EMB_DATA_CAPABILITY: c_int = 163;
pub const CCS_L_MAX_PER_LANE_BITRATE_LANE_D_MODE_MBPS: c_int = 164;

pub const CCS_L_TEMP_SENSOR_CAPABILITY: c_int = 165;
pub const CCS_L_MAX_PER_LANE_BITRATE_LANE_C_MODE_MBPS: c_int = 166;

pub const CCS_L_DPHY_EQUALIZATION_CAPABILITY: c_int = 167;
pub const CCS_L_CPHY_EQUALIZATION_CAPABILITY: c_int = 168;
pub const CCS_L_DPHY_PREAMBLE_CAPABILITY: c_int = 169;
pub const CCS_L_DPHY_SSC_CAPABILITY: c_int = 170;
pub const CCS_L_CPHY_CALIBRATION_CAPABILITY: c_int = 171;
pub const CCS_L_DPHY_CALIBRATION_CAPABILITY: c_int = 172;
pub const CCS_L_PHY_CTRL_CAPABILITY_2: c_int = 173;
pub const CCS_L_LRTE_CPHY_CAPABILITY: c_int = 174;
pub const CCS_L_LRTE_DPHY_CAPABILITY: c_int = 175;
pub const CCS_L_ALPS_CAPABILITY_DPHY: c_int = 176;
pub const CCS_L_ALPS_CAPABILITY_CPHY: c_int = 177;
pub const CCS_L_SCRAMBLING_CAPABILITY: c_int = 178;
pub const CCS_L_DPHY_MANUAL_CONSTANT: c_int = 179;
pub const CCS_L_CPHY_MANUAL_CONSTANT: c_int = 180;
pub const CCS_L_CSI2_INTERFACE_CAPABILITY_MISC: c_int = 181;
pub const CCS_L_PHY_CTRL_CAPABILITY_3: c_int = 182;
pub const CCS_L_DPHY_SF: c_int = 183;
pub const CCS_L_CPHY_SF: c_int = 184;
pub const CCS_L_DPHY_LIMITS_1: c_int = 185;
pub const CCS_L_DPHY_LIMITS_2: c_int = 186;
pub const CCS_L_DPHY_LIMITS_3: c_int = 187;
pub const CCS_L_DPHY_LIMITS_4: c_int = 188;
pub const CCS_L_DPHY_LIMITS_5: c_int = 189;
pub const CCS_L_DPHY_LIMITS_6: c_int = 190;
pub const CCS_L_CPHY_LIMITS_1: c_int = 191;
pub const CCS_L_CPHY_LIMITS_2: c_int = 192;
pub const CCS_L_CPHY_LIMITS_3: c_int = 193;
pub const CCS_L_MIN_FRAME_LENGTH_LINES_BIN: c_int = 194;
pub const CCS_L_MAX_FRAME_LENGTH_LINES_BIN: c_int = 195;
pub const CCS_L_MIN_LINE_LENGTH_PCK_BIN: c_int = 196;
pub const CCS_L_MAX_LINE_LENGTH_PCK_BIN: c_int = 197;
pub const CCS_L_MIN_LINE_BLANKING_PCK_BIN: c_int = 198;
pub const CCS_L_FINE_INTEGRATION_TIME_MIN_BIN: c_int = 199;
pub const CCS_L_FINE_INTEGRATION_TIME_MAX_MARGIN_BIN: c_int = 200;
pub const CCS_L_BINNING_CAPABILITY: c_int = 201;
pub const CCS_L_BINNING_WEIGHTING_CAPABILITY: c_int = 202;
pub const CCS_L_BINNING_SUB_TYPES: c_int = 203;
pub const CCS_L_BINNING_SUB_TYPE: c_int = 204;

pub const CCS_L_BINNING_WEIGHTING_MONO_CAPABILITY: c_int = 205;
pub const CCS_L_BINNING_SUB_TYPES_MONO: c_int = 206;
pub const CCS_L_BINNING_SUB_TYPE_MONO: c_int = 207;

pub const CCS_L_DATA_TRANSFER_IF_CAPABILITY: c_int = 208;
pub const CCS_L_SHADING_CORRECTION_CAPABILITY: c_int = 209;
pub const CCS_L_GREEN_IMBALANCE_CAPABILITY: c_int = 210;
pub const CCS_L_MODULE_SPECIFIC_CORRECTION_CAPABILITY: c_int = 211;
pub const CCS_L_DEFECT_CORRECTION_CAPABILITY: c_int = 212;
pub const CCS_L_DEFECT_CORRECTION_CAPABILITY_2: c_int = 213;
pub const CCS_L_NF_CAPABILITY: c_int = 214;
pub const CCS_L_OB_READOUT_CAPABILITY: c_int = 215;
pub const CCS_L_COLOR_FEEDBACK_CAPABILITY: c_int = 216;
pub const CCS_L_CFA_PATTERN_CAPABILITY: c_int = 217;
pub const CCS_L_CFA_PATTERN_CONVERSION_CAPABILITY: c_int = 218;
pub const CCS_L_FLASH_MODE_CAPABILITY: c_int = 219;
pub const CCS_L_SA_STROBE_MODE_CAPABILITY: c_int = 220;
pub const CCS_L_RESET_MAX_DELAY: c_int = 221;
pub const CCS_L_RESET_MIN_TIME: c_int = 222;
pub const CCS_L_PDAF_CAPABILITY_1: c_int = 223;
pub const CCS_L_PDAF_CAPABILITY_2: c_int = 224;
pub const CCS_L_BRACKETING_LUT_CAPABILITY_1: c_int = 225;
pub const CCS_L_BRACKETING_LUT_CAPABILITY_2: c_int = 226;
pub const CCS_L_BRACKETING_LUT_SIZE: c_int = 227;
pub const CCS_L_LAST: c_int = 228;
