//! Automatically rewritten from C Header to Rust Module
//! Source: tools/sched_ext/include/scx/enums_abi.autogen.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// WARNING: This file is autogenerated from gen_enum_defs.py [1].
//
// scx enumerator values from the vmlinux.h this tree is built against.
// Used as the substitution source when the running kernel's BTF lacks
// BTF_KIND_ENUM64 encoding and 64-bit enum values are truncated.
//
// [1] https://github.com/sched-ext/scx/blob/main/scripts/gen_enum_defs.py
//
#[repr(C)]
#[derive(Copy, Clone)]
pub struct __scx_enum_abi_val {
    pub type: *const c_char,
    pub name: *const c_char,
    pub val: u64,
}
