//! Automatically rewritten from C Header to Rust Module
//! Source: fs/lockd/nlm4xdr_gen.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0
// Generated by xdrgen. Manual edits will be lost.
// XDR specification file: ../../Documentation/sunrpc/xdr/nlm4.x
// XDR specification modification time: Mon Jun 29 20:42:29 2026

extern "C" {
    pub fn nlm4_svc_decode_nlm4_testargs(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
extern "C" {
    pub fn nlm4_svc_decode_nlm4_lockargs(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
extern "C" {
    pub fn nlm4_svc_decode_nlm4_cancargs(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
extern "C" {
    pub fn nlm4_svc_decode_nlm4_unlockargs(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
extern "C" {
    pub fn nlm4_svc_decode_nlm4_testres(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
extern "C" {
    pub fn nlm4_svc_decode_nlm4_res(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
extern "C" {
    pub fn nlm4_svc_decode_nlm4_notifyargs(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
extern "C" {
    pub fn nlm4_svc_decode_nlm4_shareargs(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
extern "C" {
    pub fn nlm4_svc_decode_nlm4_notify(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
extern "C" {
    pub fn nlm4_svc_encode_nlm4_testres(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
extern "C" {
    pub fn nlm4_svc_encode_nlm4_res(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
extern "C" {
    pub fn nlm4_svc_encode_nlm4_shareres(rqstp: *mut svc_rqst, xdr: *mut xdr_stream) -> bool;
}
