//! Automatically rewritten from C Header to Rust Module
//! Source: drivers/gpu/drm/amd/include/soc21_enum.h
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


//
// Copyright 2021 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

// Macro flag: #define _soc21_ENUM_HEADER

//
// Chip Enums
//
// DSM_DATA_SEL enum
//
// DSM_ENABLE_ERROR_INJECT enum
//
// DSM_SELECT_INJECT_DELAY enum
//
// DSM_SINGLE_WRITE enum
//
// ENUM_NUM_SIMD_PER_CU enum
//
// GATCL1RequestType enum
//
// GL0V_CACHE_POLICIES enum
//
// GL1_CACHE_POLICIES enum
//
// GL1_CACHE_STORE_POLICIES enum
//
// GL2_CACHE_POLICIES enum
//
// Hdp_SurfaceEndian enum
//
// MTYPE enum
//
// PERFMON_COUNTER_MODE enum
//
// PERFMON_SPM_MODE enum
//
// RMI_CID enum
//
// ReadPolicy enum
//
// SDMA_PERFMON_SEL enum
//
// SDMA_PERF_SEL enum
//
// TCC_CACHE_POLICIES enum
//
// TCC_MTYPE enum
//
// UTCL0FaultType enum
//
// UTCL0RequestType enum
//
// UTCL1FaultType enum
//
// UTCL1RequestType enum
//
// VMEMCMD_RETURN_ORDER enum
//
// WritePolicy enum
//
// CNVC_CFG Enums
//
// CNVC_BYPASS enum
//
// CNVC_COEF_FORMAT_ENUM enum
//
// CNVC_ENABLE enum
//
// CNVC_PENDING enum
//
// COLOR_KEYER_MODE enum
//
// DENORM_TRUNCATE enum
//
// FORMAT_CROSSBAR enum
//
// PIX_EXPAND_MODE enum
//
// PRE_CSC_MODE_ENUM enum
//
// PRE_DEGAM_MODE enum
//
// PRE_DEGAM_SELECT enum
//
// SURFACE_PIXEL_FORMAT enum
//
// XNORM enum
//
// CNVC_CUR Enums
//
// CUR_ENABLE enum
//
// CUR_EXPAND_MODE enum
//
// CUR_INV_CLAMP enum
//
// CUR_MODE enum
//
// CUR_PENDING enum
//
// CUR_ROM_EN enum
//
// DSCL Enums
//
// COEF_RAM_SELECT_RD enum
//
// DSCL_MODE_SEL enum
//
// LB_ALPHA_EN enum
//
// LB_INTERLEAVE_EN enum
//
// LB_MEMORY_CONFIG enum
//
// OBUF_BYPASS_SEL enum
//
// OBUF_IS_HALF_RECOUT_WIDTH_SEL enum
//
// OBUF_USE_FULL_BUFFER_SEL enum
//
// SCL_2TAP_HARDCODE enum
//
// SCL_ALPHA_COEF enum
//
// SCL_AUTOCAL_MODE enum
//
// SCL_BOUNDARY enum
//
// SCL_CHROMA_COEF enum
//
// SCL_COEF_FILTER_TYPE_SEL enum
//
// SCL_COEF_RAM_SEL enum
//
// SCL_SHARP_EN enum
//
// CM Enums
//
// CMC_3DLUT_30BIT_ENUM enum
//
// CMC_3DLUT_RAM_SEL enum
//
// CMC_3DLUT_SIZE_ENUM enum
//
// CMC_LUT_2_CONFIG_ENUM enum
//
// CMC_LUT_2_MODE_ENUM enum
//
// CMC_LUT_NUM_SEG enum
//
// CMC_LUT_RAM_SEL enum
//
// CM_BYPASS enum
//
// CM_COEF_FORMAT_ENUM enum
//
// CM_DATA_SIGNED enum
//
// CM_EN enum
//
// CM_GAMMA_LUT_MODE_ENUM enum
//
// CM_GAMMA_LUT_PWL_DISABLE_ENUM enum
//
// CM_GAMMA_LUT_SEL_ENUM enum
//
// CM_GAMUT_REMAP_MODE_ENUM enum
//
// CM_LUT_2_CONFIG_ENUM enum
//
// CM_LUT_2_MODE_ENUM enum
//
// CM_LUT_4_CONFIG_ENUM enum
//
// CM_LUT_4_MODE_ENUM enum
//
// CM_LUT_CONFIG_MODE enum
//
// CM_LUT_NUM_SEG enum
//
// CM_LUT_RAM_SEL enum
//
// CM_LUT_READ_COLOR_SEL enum
//
// CM_LUT_READ_DBG enum
//
// CM_PENDING enum
//
// CM_POST_CSC_MODE_ENUM enum
//
// CM_WRITE_BASE_ONLY enum
//
// DPP_TOP Enums
//
// CRC_CUR_SEL enum
//
// CRC_INTERLACE_SEL enum
//
// CRC_IN_CUR_SEL enum
//
// CRC_IN_PIX_SEL enum
//
// CRC_SRC_SEL enum
//
// CRC_STEREO_SEL enum
//
// TEST_CLK_SEL enum
//
// DC_PERFMON Enums
//
// PERFCOUNTER_ACTIVE enum
//
// PERFCOUNTER_CNT0_STATE enum
//
// PERFCOUNTER_CNT1_STATE enum
//
// PERFCOUNTER_CNT2_STATE enum
//
// PERFCOUNTER_CNT3_STATE enum
//
// PERFCOUNTER_CNT4_STATE enum
//
// PERFCOUNTER_CNT5_STATE enum
//
// PERFCOUNTER_CNT6_STATE enum
//
// PERFCOUNTER_CNT7_STATE enum
//
// PERFCOUNTER_CNTL_SEL enum
//
// PERFCOUNTER_CNTOFF_START_DIS enum
//
// PERFCOUNTER_COUNTED_VALUE_TYPE enum
//
// PERFCOUNTER_CVALUE_SEL enum
//
// PERFCOUNTER_HW_CNTL_SEL enum
//
// PERFCOUNTER_HW_STOP1_SEL enum
//
// PERFCOUNTER_HW_STOP2_SEL enum
//
// PERFCOUNTER_INC_MODE enum
//
// PERFCOUNTER_INT_EN enum
//
// PERFCOUNTER_INT_TYPE enum
//
// PERFCOUNTER_OFF_MASK enum
//
// PERFCOUNTER_RESTART_EN enum
//
// PERFCOUNTER_RUNEN_MODE enum
//
// PERFCOUNTER_STATE_SEL0 enum
//
// PERFCOUNTER_STATE_SEL1 enum
//
// PERFCOUNTER_STATE_SEL2 enum
//
// PERFCOUNTER_STATE_SEL3 enum
//
// PERFCOUNTER_STATE_SEL4 enum
//
// PERFCOUNTER_STATE_SEL5 enum
//
// PERFCOUNTER_STATE_SEL6 enum
//
// PERFCOUNTER_STATE_SEL7 enum
//
// PERFMON_CNTOFF_AND_OR enum
//
// PERFMON_CNTOFF_INT_EN enum
//
// PERFMON_CNTOFF_INT_TYPE enum
//
// PERFMON_STATE enum
//
// HUBP Enums
//
// BIGK_FRAGMENT_SIZE enum
//
// CHUNK_SIZE enum
//
// COMPAT_LEVEL enum
//
// DPTE_GROUP_SIZE enum
//
// FORCE_ONE_ROW_FOR_FRAME enum
//
// HUBP_BLANK_EN enum
//
// HUBP_IN_BLANK enum
//
// HUBP_MEASURE_WIN_MODE_DCFCLK enum
//
// HUBP_NO_OUTSTANDING_REQ enum
//
// HUBP_SOFT_RESET enum
//
// HUBP_TTU_DISABLE enum
//
// HUBP_VREADY_AT_OR_AFTER_VSYNC enum
//
// HUBP_VTG_SEL enum
//
// H_MIRROR_EN enum
//
// LEGACY_PIPE_INTERLEAVE enum
//
// META_CHUNK_SIZE enum
//
// META_LINEAR enum
//
// MIN_CHUNK_SIZE enum
//
// MIN_META_CHUNK_SIZE enum
//
// PIPE_ALIGNED enum
//
// PTE_BUFFER_MODE enum
//
// PTE_ROW_HEIGHT_LINEAR enum
//
// ROTATION_ANGLE enum
//
// SWATH_HEIGHT enum
//
// USE_MALL_FOR_CURSOR enum
//
// USE_MALL_FOR_PSTATE_CHANGE enum
//
// USE_MALL_FOR_STATIC_SCREEN enum
//
// VMPG_SIZE enum
//
// VM_GROUP_SIZE enum
//
// HUBPREQ Enums
//
// DFQ_MIN_FREE_ENTRIES enum
//
// DFQ_NUM_ENTRIES enum
//
// DFQ_SIZE enum
//
// DMDATA_VM_DONE enum
//
// EXPANSION_MODE enum
//
// FLIP_RATE enum
//
// INT_MASK enum
//
// PIPE_IN_FLUSH_URGENT enum
//
// PRQ_MRQ_FLUSH_URGENT enum
//
// ROW_TTU_MODE enum
//
// SURFACE_DCC enum
//
// SURFACE_DCC_IND_128B enum
//
// SURFACE_DCC_IND_64B enum
//
// SURFACE_DCC_IND_BLK enum
//
// SURFACE_FLIP_AWAY_INT_TYPE enum
//
// SURFACE_FLIP_EXEC_DEBUG_MODE enum
//
// SURFACE_FLIP_INT_TYPE enum
//
// SURFACE_FLIP_IN_STEREOSYNC enum
//
// SURFACE_FLIP_MODE_FOR_STEREOSYNC enum
//
// SURFACE_FLIP_STEREO_SELECT_DISABLE enum
//
// SURFACE_FLIP_STEREO_SELECT_POLARITY enum
//
// SURFACE_FLIP_TYPE enum
//
// SURFACE_FLIP_VUPDATE_SKIP_NUM enum
//
// SURFACE_INUSE_RAED_NO_LATCH enum
//
// SURFACE_TMZ enum
//
// SURFACE_UPDATE_LOCK enum
//
// HUBPRET Enums
//
// CROSSBAR_FOR_ALPHA enum
//
// CROSSBAR_FOR_CB_B enum
//
// CROSSBAR_FOR_CR_R enum
//
// CROSSBAR_FOR_Y_G enum
//
// DETILE_BUFFER_PACKER_ENABLE enum
//
// MEM_PWR_DIS_MODE enum
//
// MEM_PWR_FORCE_MODE enum
//
// MEM_PWR_STATUS enum
//
// PIPE_INT_MASK_MODE enum
//
// PIPE_INT_TYPE_MODE enum
//
// PIXCDC_MEM_PWR_LIGHT_SLEEP_MODE enum
//
// CURSOR Enums
//
// CROB_MEM_PWR_LIGHT_SLEEP_MODE enum
//
// CURSOR_2X_MAGNIFY enum
//
// CURSOR_ENABLE enum
//
// CURSOR_LINES_PER_CHUNK enum
//
// CURSOR_MODE enum
//
// CURSOR_PERFMON_LATENCY_MEASURE_EN enum
//
// CURSOR_PERFMON_LATENCY_MEASURE_SEL enum
//
// CURSOR_PITCH enum
//
// CURSOR_REQ_MODE enum
//
// CURSOR_SNOOP enum
//
// CURSOR_STEREO_EN enum
//
// CURSOR_SURFACE_TMZ enum
//
// CURSOR_SYSTEM enum
//
// CURSOR_XY_POSITION_ROTATION_AND_MIRRORING_BYPASS enum
//
// DMDATA_DONE enum
//
// DMDATA_MODE enum
//
// DMDATA_QOS_MODE enum
//
// DMDATA_REPEAT enum
//
// DMDATA_UNDERFLOW enum
//
// DMDATA_UNDERFLOW_CLEAR enum
//
// DMDATA_UPDATED enum
//
// HUBBUB_SDPIF Enums
//
// RESPONSE_STATUS enum
//
// HUBBUB_RET_PATH Enums
//
// DCHUBBUB_DET_MEM_PWR_LIGHT_SLEEP_MODE enum
//
// DCHUBBUB_MEM_PWR_DIS_MODE enum
//
// DCHUBBUB_MEM_PWR_MODE enum
//
// MPC_CFG Enums
//
// MPC_CFG_ADR_CFG_CUR_VUPDATE_LOCK_SET enum
//
// MPC_CFG_ADR_CFG_VUPDATE_LOCK_SET enum
//
// MPC_CFG_ADR_VUPDATE_LOCK_SET enum
//
// MPC_CFG_CFG_VUPDATE_LOCK_SET enum
//
// MPC_CFG_CUR_VUPDATE_LOCK_SET enum
//
// MPC_CFG_MPC_TEST_CLK_SEL enum
//
// MPC_CFG_TEST_DEBUG_INDEX_MPC_CFG_TEST_DEBUG_WRITE_EN enum
//
// MPC_CRC_CALC_INTERLACE_MODE enum
//
// MPC_CRC_CALC_MODE enum
//
// MPC_CRC_CALC_STEREO_MODE enum
//
// MPC_CRC_SOURCE_SELECT enum
//
// MPC_DEBUG_BUS1_DATA_SELECT enum
//
// MPC_DEBUG_BUS2_DATA_SELECT enum
//
// MPC_DEBUG_BUS_DIRECT_OUT_DATA_SELECT enum
//
// MPC_DEBUG_BUS_MPCC_BYTE_SELECT enum
//
// MPC_OCSC Enums
//
// MPC_OCSC_COEF_FORMAT enum
//
// MPC_OCSC_TEST_DEBUG_INDEX_MPC_OCSC_TEST_DEBUG_WRITE_EN enum
//
// MPC_OUT_CSC_MODE enum
//
// MPC_OUT_DENORM_CONTROL_MPC_OUT_DENORM_MODE enum
//
// MPC_OUT_RATE_CONTROL_DISABLE_SET enum
//
// MPCC Enums
//
// MPCC_BG_COLOR_BPC enum
//
// MPCC_CONTROL_MPCC_ACTIVE_OVERLAP_ONLY enum
//
// MPCC_CONTROL_MPCC_ALPHA_BLND_MODE enum
//
// MPCC_CONTROL_MPCC_ALPHA_MULTIPLIED_MODE enum
//
// MPCC_CONTROL_MPCC_BOT_GAIN_MODE enum
//
// MPCC_CONTROL_MPCC_MODE enum
//
// MPCC_SM_CONTROL_MPCC_SM_EN enum
//
// MPCC_SM_CONTROL_MPCC_SM_FIELD_ALT enum
//
// MPCC_SM_CONTROL_MPCC_SM_FORCE_NEXT_FRAME_POL enum
//
// MPCC_SM_CONTROL_MPCC_SM_FORCE_NEXT_TOP_POL enum
//
// MPCC_SM_CONTROL_MPCC_SM_FRAME_ALT enum
//
// MPCC_SM_CONTROL_MPCC_SM_MODE enum
//
// MPCC_TEST_DEBUG_INDEX_MPCC_TEST_DEBUG_WRITE_EN enum
//
// MPCC_OGAM Enums
//
// MPCC_GAMUT_REMAP_COEF_FORMAT_ENUM enum
//
// MPCC_GAMUT_REMAP_MODE_ENUM enum
//
// MPCC_OGAM_LUT_2_CONFIG_ENUM enum
//
// MPCC_OGAM_LUT_CONFIG_MODE enum
//
// MPCC_OGAM_LUT_PWL_DISABLE_ENUM enum
//
// MPCC_OGAM_LUT_RAM_CONTROL_MPCC_OGAM_LUT_RAM_SEL enum
//
// MPCC_OGAM_LUT_RAM_SEL enum
//
// MPCC_OGAM_LUT_READ_COLOR_SEL enum
//
// MPCC_OGAM_LUT_READ_DBG enum
//
// MPCC_OGAM_LUT_SEL_ENUM enum
//
// MPCC_OGAM_MODE_MPCC_OGAM_MODE_ENUM enum
//
// MPCC_OGAM_NUM_SEG enum
//
// MPCC_OGAM_TEST_DEBUG_INDEX_MPCC_OGAM_TEST_DEBUG_WRITE_EN enum
//
// MPCC_MCM Enums
//
// MPCC_MCM_3DLUT_30BIT_ENUM enum
//
// MPCC_MCM_3DLUT_RAM_SEL enum
//
// MPCC_MCM_3DLUT_SIZE_ENUM enum
//
// MPCC_MCM_GAMMA_LUT_MODE_ENUM enum
//
// MPCC_MCM_GAMMA_LUT_PWL_DISABLE_ENUM enum
//
// MPCC_MCM_GAMMA_LUT_SEL_ENUM enum
//
// MPCC_MCM_LUT_2_MODE_ENUM enum
//
// MPCC_MCM_LUT_CONFIG_MODE enum
//
// MPCC_MCM_LUT_NUM_SEG enum
//
// MPCC_MCM_LUT_RAM_SEL enum
//
// MPCC_MCM_LUT_READ_COLOR_SEL enum
//
// MPCC_MCM_LUT_READ_DBG enum
//
// MPCC_MCM_MEM_PWR_FORCE_ENUM enum
//
// MPCC_MCM_MEM_PWR_STATE_ENUM enum
//
// ABM Enums
//
// DPG Enums
//
// ENUM_DPG_BIT_DEPTH enum
//
// ENUM_DPG_DYNAMIC_RANGE enum
//
// ENUM_DPG_EN enum
//
// ENUM_DPG_FIELD_POLARITY enum
//
// ENUM_DPG_MODE enum
//
// FMT Enums
//
// FMTMEM_PWR_DIS_CTRL enum
//
// FMTMEM_PWR_FORCE_CTRL enum
//
// FMT_BIT_DEPTH_CONTROL_25FRC_SEL enum
//
// FMT_BIT_DEPTH_CONTROL_50FRC_SEL enum
//
// FMT_BIT_DEPTH_CONTROL_75FRC_SEL enum
//
// FMT_BIT_DEPTH_CONTROL_SPATIAL_DITHER_DEPTH enum
//
// FMT_BIT_DEPTH_CONTROL_TEMPORAL_DITHER_DEPTH enum
//
// FMT_BIT_DEPTH_CONTROL_TEMPORAL_LEVEL enum
//
// FMT_BIT_DEPTH_CONTROL_TRUNCATE_DEPTH enum
//
// FMT_BIT_DEPTH_CONTROL_TRUNCATE_MODE enum
//
// FMT_CLAMP_CNTL_COLOR_FORMAT enum
//
// FMT_CONTROL_CBCR_BIT_REDUCTION_BYPASS enum
//
// FMT_CONTROL_PIXEL_ENCODING enum
//
// FMT_CONTROL_SUBSAMPLING_MODE enum
//
// FMT_CONTROL_SUBSAMPLING_ORDER enum
//
// FMT_DEBUG_CNTL_COLOR_SELECT enum
//
// FMT_DYNAMIC_EXP_MODE enum
//
// FMT_FRAME_RANDOM_ENABLE_CONTROL enum
//
// FMT_POWER_STATE_ENUM enum
//
// FMT_RGB_RANDOM_ENABLE_CONTROL enum
//
// FMT_SPATIAL_DITHER_FRAME_COUNTER_BIT_SWAP_CONTROL enum
//
// FMT_SPATIAL_DITHER_MODE enum
//
// FMT_STEREOSYNC_OVERRIDE_CONTROL enum
//
// FMT_TEMPORAL_DITHER_PATTERN_CONTROL_RGB1_BGR0 enum
//
// OPPBUF Enums
//
// OPPBUF_DISPLAY_SEGMENTATION enum
//
// OPP_PIPE Enums
//
// OPP_PIPE_CLOCK_ENABLE_CONTROL enum
//
// OPP_PIPE_DIGTIAL_BYPASS_CONTROL enum
//
// OPP_PIPE_CRC Enums
//
// OPP_PIPE_CRC_CONT_EN enum
//
// OPP_PIPE_CRC_EN enum
//
// OPP_PIPE_CRC_INTERLACE_EN enum
//
// OPP_PIPE_CRC_INTERLACE_MODE enum
//
// OPP_PIPE_CRC_ONE_SHOT_PENDING enum
//
// OPP_PIPE_CRC_PIXEL_SELECT enum
//
// OPP_PIPE_CRC_SOURCE_SELECT enum
//
// OPP_PIPE_CRC_STEREO_EN enum
//
// OPP_PIPE_CRC_STEREO_MODE enum
//
// OPP_TOP Enums
//
// OPP_ABM_DEBUG_BUS_SELECT_CONTROL enum
//
// OPP_DPG_DEBUG_BUS_SELECT_CONTROL enum
//
// OPP_FMT_DEBUG_BUS_SELECT_CONTROL enum
//
// OPP_OPPBUF_DEBUG_BUS_SELECT_CONTROL enum
//
// OPP_OPP_PIPE_DEBUG_BUS_SELECT_CONTROL enum
//
// OPP_TEST_CLK_SEL_CONTROL enum
//
// OPP_TOP_CLOCK_ENABLE_STATUS enum
//
// OPP_TOP_CLOCK_GATING_CONTROL enum
//
// DSCRM Enums
//
// ENUM_DSCRM_EN enum
//
// OTG Enums
//
// MASTER_UPDATE_LOCK_MASTER_UPDATE_LOCK enum
//
// MASTER_UPDATE_LOCK_SEL enum
//
// MASTER_UPDATE_MODE_MASTER_UPDATE_INTERLACED_MODE enum
//
// OTG_3D_STRUCTURE_CONTROL_OTG_3D_STRUCTURE_EN enum
//
// OTG_3D_STRUCTURE_CONTROL_OTG_3D_STRUCTURE_EN_DB enum
//
// OTG_3D_STRUCTURE_CONTROL_OTG_3D_STRUCTURE_STEREO_SEL_OVR enum
//
// OTG_3D_STRUCTURE_CONTROL_OTG_3D_STRUCTURE_V_UPDATE_MODE enum
//
// OTG_CONTROL_OTG_DISABLE_POINT_CNTL enum
//
// OTG_CONTROL_OTG_FIELD_NUMBER_CNTL enum
//
// OTG_CONTROL_OTG_FIELD_NUMBER_POLARITY enum
//
// OTG_CONTROL_OTG_MASTER_EN enum
//
// OTG_CONTROL_OTG_OUT_MUX enum
//
// OTG_CONTROL_OTG_START_POINT_CNTL enum
//
// OTG_COUNT_CONTROL_OTG_HORZ_COUNT_BY2_EN enum
//
// OTG_CRC_CNTL_OTG_CRC1_EN enum
//
// OTG_CRC_CNTL_OTG_CRC_CONT_EN enum
//
// OTG_CRC_CNTL_OTG_CRC_CONT_MODE enum
//
// OTG_CRC_CNTL_OTG_CRC_EN enum
//
// OTG_CRC_CNTL_OTG_CRC_INTERLACE_MODE enum
//
// OTG_CRC_CNTL_OTG_CRC_STEREO_MODE enum
//
// OTG_CRC_CNTL_OTG_CRC_USE_NEW_AND_REPEATED_PIXELS enum
//
// OTG_CRC_CNTL_OTG_OTG_CRC0_SELECT enum
//
// OTG_CRC_CNTL_OTG_OTG_CRC1_SELECT enum
//
// OTG_DIG_UPDATE_VCOUNT_MODE enum
//
// OTG_DOUBLE_BUFFER_CONTROL_OTG_DRR_TIMING_DBUF_UPDATE_MODE enum
//
// OTG_DOUBLE_BUFFER_CONTROL_OTG_UPDATE_INSTANTLY enum
//
// OTG_DRR_CONTROL_OTG_DRR_AVERAGE_FRAME enum
//
// OTG_DTMTEST_CNTL_OTG_DTMTEST_OTG_EN enum
//
// OTG_FLOW_CONTROL_OTG_FLOW_CONTROL_GRANULARITY enum
//
// OTG_FLOW_CONTROL_OTG_FLOW_CONTROL_POLARITY enum
//
// OTG_FLOW_CONTROL_OTG_FLOW_CONTROL_SOURCE_SELECT enum
//
// OTG_FORCE_COUNT_NOW_CNTL_OTG_FORCE_COUNT_NOW_CHECK enum
//
// OTG_FORCE_COUNT_NOW_CNTL_OTG_FORCE_COUNT_NOW_CLEAR enum
//
// OTG_FORCE_COUNT_NOW_CNTL_OTG_FORCE_COUNT_NOW_MODE enum
//
// OTG_FORCE_COUNT_NOW_CNTL_OTG_FORCE_COUNT_NOW_TRIG_SEL enum
//
// OTG_GLOBAL_CONTROL2_MANUAL_FLOW_CONTROL_SEL enum
//
// OTG_GLOBAL_CONTROL3_DIG_UPDATE_EYE_SEL enum
//
// OTG_GLOBAL_CONTROL3_DIG_UPDATE_FIELD_SEL enum
//
// OTG_GLOBAL_CONTROL3_MASTER_UPDATE_LOCK_DB_FIELD enum
//
// OTG_GLOBAL_CONTROL3_MASTER_UPDATE_LOCK_DB_STEREO_SEL enum
//
// OTG_GLOBAL_UPDATE_LOCK_EN enum
//
// OTG_GSL_MASTER_MODE enum
//
// OTG_HORZ_REPETITION_COUNT enum
//
// OTG_H_SYNC_A_POL enum
//
// OTG_H_TIMING_DIV_MODE enum
//
// OTG_H_TIMING_DIV_MODE_MANUAL enum
//
// OTG_INTERLACE_CONTROL_OTG_INTERLACE_ENABLE enum
//
// OTG_INTERLACE_CONTROL_OTG_INTERLACE_FORCE_NEXT_FIELD enum
//
// OTG_INTERRUPT_CONTROL_OTG_FORCE_COUNT_NOW_INT_MSK enum
//
// OTG_INTERRUPT_CONTROL_OTG_FORCE_COUNT_NOW_INT_TYPE enum
//
// OTG_INTERRUPT_CONTROL_OTG_FORCE_VSYNC_NEXT_LINE_INT_MSK enum
//
// OTG_INTERRUPT_CONTROL_OTG_FORCE_VSYNC_NEXT_LINE_INT_TYPE enum
//
// OTG_INTERRUPT_CONTROL_OTG_GSL_VSYNC_GAP_INT_MSK enum
//
// OTG_INTERRUPT_CONTROL_OTG_GSL_VSYNC_GAP_INT_TYPE enum
//
// OTG_INTERRUPT_CONTROL_OTG_SNAPSHOT_INT_MSK enum
//
// OTG_INTERRUPT_CONTROL_OTG_SNAPSHOT_INT_TYPE enum
//
// OTG_INTERRUPT_CONTROL_OTG_TRIGA_INT_MSK enum
//
// OTG_INTERRUPT_CONTROL_OTG_TRIGA_INT_TYPE enum
//
// OTG_INTERRUPT_CONTROL_OTG_TRIGB_INT_MSK enum
//
// OTG_INTERRUPT_CONTROL_OTG_TRIGB_INT_TYPE enum
//
// OTG_INTERRUPT_CONTROL_OTG_VSYNC_NOM_INT_MSK enum
//
// OTG_INTERRUPT_CONTROL_OTG_VSYNC_NOM_INT_TYPE enum
//
// OTG_MANUAL_FORCE_VSYNC_NEXT_LINE_OTG_MANUAL_FORCE_VSYNC_NEXT_LINE enum
//
// OTG_MASTER_UPDATE_LOCK_DB_EN enum
//
// OTG_MASTER_UPDATE_LOCK_GSL_EN enum
//
// OTG_MASTER_UPDATE_LOCK_VCOUNT_MODE enum
//
// OTG_SNAPSHOT_CONTROL_OTG_AUTO_SNAPSHOT_TRIG_SEL enum
//
// OTG_SNAPSHOT_STATUS_OTG_SNAPSHOT_CLEAR enum
//
// OTG_STATIC_SCREEN_CONTROL_OTG_CPU_SS_INT_CLEAR enum
//
// OTG_STATIC_SCREEN_CONTROL_OTG_CPU_SS_INT_ENABLE enum
//
// OTG_STATIC_SCREEN_CONTROL_OTG_CPU_SS_INT_TYPE enum
//
// OTG_STATIC_SCREEN_CONTROL_OTG_STATIC_SCREEN_OVERRIDE enum
//
// OTG_STATIC_SCREEN_CONTROL_OTG_STATIC_SCREEN_OVERRIDE_VALUE enum
//
// OTG_STEREO_CONTROL_OTG_FIELD_NUM_SEL enum
//
// OTG_STEREO_CONTROL_OTG_STEREO_EN enum
//
// OTG_STEREO_CONTROL_OTG_STEREO_EYE_FLAG_POLARITY enum
//
// OTG_STEREO_CONTROL_OTG_STEREO_SYNC_OUTPUT_POLARITY enum
//
// OTG_STEREO_FORCE_NEXT_EYE_OTG_STEREO_FORCE_NEXT_EYE enum
//
// OTG_TRIGA_CNTL_OTG_TRIGA_CLEAR enum
//
// OTG_TRIGA_CNTL_OTG_TRIGA_POLARITY_SELECT enum
//
// OTG_TRIGA_CNTL_OTG_TRIGA_RESYNC_BYPASS_EN enum
//
// OTG_TRIGA_CNTL_OTG_TRIGA_SOURCE_PIPE_SELECT enum
//
// OTG_TRIGA_CNTL_OTG_TRIGA_SOURCE_SELECT enum
//
// OTG_TRIGA_FALLING_EDGE_DETECT_CNTL enum
//
// OTG_TRIGA_FREQUENCY_SELECT enum
//
// OTG_TRIGA_RISING_EDGE_DETECT_CNTL enum
//
// OTG_TRIGB_CNTL_OTG_TRIGB_CLEAR enum
//
// OTG_TRIGB_CNTL_OTG_TRIGB_POLARITY_SELECT enum
//
// OTG_TRIGB_CNTL_OTG_TRIGB_RESYNC_BYPASS_EN enum
//
// OTG_TRIGB_CNTL_OTG_TRIGB_SOURCE_PIPE_SELECT enum
//
// OTG_TRIGB_CNTL_OTG_TRIGB_SOURCE_SELECT enum
//
// OTG_TRIGB_FALLING_EDGE_DETECT_CNTL enum
//
// OTG_TRIGB_FREQUENCY_SELECT enum
//
// OTG_TRIGB_RISING_EDGE_DETECT_CNTL enum
//
// OTG_UPDATE_LOCK_OTG_UPDATE_LOCK enum
//
// OTG_VERTICAL_INTERRUPT0_CONTROL_OTG_VERTICAL_INTERRUPT0_CLEAR enum
//
// OTG_VERTICAL_INTERRUPT0_CONTROL_OTG_VERTICAL_INTERRUPT0_INT_ENABLE enum
//
// OTG_VERTICAL_INTERRUPT0_CONTROL_OTG_VERTICAL_INTERRUPT0_INT_TYPE enum
//
// OTG_VERTICAL_INTERRUPT0_CONTROL_OTG_VERTICAL_INTERRUPT0_OUTPUT_POLARITY enum
//
// OTG_VERTICAL_INTERRUPT1_CONTROL_OTG_VERTICAL_INTERRUPT1_CLEAR enum
//
// OTG_VERTICAL_INTERRUPT1_CONTROL_OTG_VERTICAL_INTERRUPT1_INT_ENABLE enum
//
// OTG_VERTICAL_INTERRUPT1_CONTROL_OTG_VERTICAL_INTERRUPT1_INT_TYPE enum
//
// OTG_VERTICAL_INTERRUPT2_CONTROL_OTG_VERTICAL_INTERRUPT2_CLEAR enum
//
// OTG_VERTICAL_INTERRUPT2_CONTROL_OTG_VERTICAL_INTERRUPT2_INT_ENABLE enum
//
// OTG_VERTICAL_INTERRUPT2_CONTROL_OTG_VERTICAL_INTERRUPT2_INT_TYPE enum
//
// OTG_VERT_SYNC_CONTROL_OTG_AUTO_FORCE_VSYNC_MODE enum
//
// OTG_VERT_SYNC_CONTROL_OTG_FORCE_VSYNC_NEXT_LINE_CLEAR enum
//
// OTG_VSYNC_NOM_INT_STATUS_OTG_VSYNC_NOM_INT_CLEAR enum
//
// OTG_VUPDATE_BLOCK_DISABLE enum
//
// OTG_V_SYNC_A_POL enum
//
// OTG_V_SYNC_MODE enum
//
// OTG_V_TOTAL_CONTROL_OTG_DRR_EVENT_ACTIVE_PERIOD enum
//
// OTG_V_TOTAL_CONTROL_OTG_FORCE_LOCK_ON_EVENT enum
//
// OTG_V_TOTAL_CONTROL_OTG_FORCE_LOCK_TO_MASTER_VSYNC enum
//
// OTG_V_TOTAL_CONTROL_OTG_V_TOTAL_MAX_SEL enum
//
// OTG_V_TOTAL_CONTROL_OTG_V_TOTAL_MIN_SEL enum
//
// OTG_V_TOTAL_INT_STATUS_OTG_SET_V_TOTAL_MIN_EVENT_OCCURRED_ACK enum
//
// OPTC_MISC Enums
//
// OPTC_GSL_SOURCE_SELECT_GSL_TIMING_SYNC_SEL enum
//
// DMCUB Enums
//
// DC_DMCUB_INT_TYPE enum
//
// DC_DMCUB_TIMER_WINDOW enum
//
// RBBMIF Enums
//
// INVALID_REG_ACCESS_TYPE enum
//
// IHC Enums
//
// DMU_DC_GPU_TIMER_READ_SELECT enum
//
// DMU_DC_GPU_TIMER_START_POSITION enum
//
// IHC_INTERRUPT_DEST enum
//
// IHC_INTERRUPT_LINE_STATUS enum
//
// DMU_MISC Enums
//
// DC_SMU_INTERRUPT_ENABLE enum
//
// DMU_CLOCK_ON enum
//
// SMU_INTR enum
//
// DCCG Enums
//
// ALLOW_SR_ON_TRANS_REQ enum
//
// AMCLOCK_ENABLE enum
//
// CLEAR_SMU_INTR enum
//
// CLOCK_BRANCH_SOFT_RESET enum
//
// DCCG_AUDIO_DTO0_SOURCE_SEL enum
//
// DCCG_AUDIO_DTO2_SOURCE_SEL enum
//
// DCCG_AUDIO_DTO_SEL enum
//
// DCCG_AUDIO_DTO_USE_512FBR_DTO enum
//
// DCCG_DBG_BLOCK_SEL enum
//
// DCCG_DBG_EN enum
//
// DCCG_DEEP_COLOR_CNTL enum
//
// DCCG_FIFO_ERRDET_OVR_EN enum
//
// DCCG_FIFO_ERRDET_RESET enum
//
// DCCG_FIFO_ERRDET_STATE enum
//
// DCCG_PERF_MODE_HSYNC enum
//
// DCCG_PERF_MODE_VSYNC enum
//
// DCCG_PERF_OTG_SELECT enum
//
// DCCG_PERF_RUN enum
//
// DC_MEM_GLOBAL_PWR_REQ_DIS enum
//
// DIO_FIFO_ERROR enum
//
// DISABLE_CLOCK_GATING enum
//
// DISABLE_CLOCK_GATING_IN_DCO enum
//
// DISPCLK_CHG_FWD_CORR_DISABLE enum
//
// DISPCLK_FREQ_RAMP_DONE enum
//
// DPREFCLK_SRC_SEL enum
//
// DP_DTO_DS_DISABLE enum
//
// DS_HW_CAL_ENABLE enum
//
// DS_JITTER_COUNT_SRC_SEL enum
//
// DS_REF_SRC enum
//
// DVOACLKC_IN_PHASE enum
//
// DVOACLKC_MVP_IN_PHASE enum
//
// DVOACLKC_MVP_SKEW_PHASE_OVERRIDE enum
//
// DVOACLKD_IN_PHASE enum
//
// DVOACLK_COARSE_SKEW_CNTL enum
//
// DVOACLK_FINE_SKEW_CNTL enum
//
// DVO_ENABLE_RST enum
//
// ENABLE enum
//
// ENABLE_CLOCK enum
//
// FORCE_DISABLE_CLOCK enum
//
// HDMICHARCLK_SRC_SEL enum
//
// HDMISTREAMCLK_DTO_FORCE_DIS enum
//
// HDMISTREAMCLK_SRC_SEL enum
//
// JITTER_REMOVE_DISABLE enum
//
// MICROSECOND_TIME_BASE_CLOCK_SOURCE_SEL enum
//
// MILLISECOND_TIME_BASE_CLOCK_SOURCE_SEL enum
//
// OTG_ADD_PIXEL enum
//
// OTG_DROP_PIXEL enum
//
// PHYSYMCLK_FORCE_EN enum
//
// PHYSYMCLK_FORCE_SRC_SEL enum
//
// PIPE_PHYPLL_PIXEL_RATE_SOURCE enum
//
// PIPE_PIXEL_RATE_PLL_SOURCE enum
//
// PIPE_PIXEL_RATE_SOURCE enum
//
// PLL_CFG_IF_SOFT_RESET enum
//
// SYMCLK_FE_FORCE_EN enum
//
// SYMCLK_FE_FORCE_SRC enum
//
// TEST_CLK_DIV_SEL enum
//
// VSYNC_CNT_LATCH_MASK enum
//
// VSYNC_CNT_RESET_SEL enum
//
// XTAL_REF_CLOCK_SOURCE_SEL enum
//
// XTAL_REF_SEL enum
//
// HPD Enums
//
// HPD_INT_CONTROL_ACK enum
//
// HPD_INT_CONTROL_POLARITY enum
//
// HPD_INT_CONTROL_RX_INT_ACK enum
//
// DP Enums
//
// DPHY_8B10B_CUR_DISP enum
//
// DPHY_8B10B_RESET enum
//
// DPHY_ALT_SCRAMBLER_RESET_EN enum
//
// DPHY_ALT_SCRAMBLER_RESET_SEL enum
//
// DPHY_ATEST_SEL_LANE0 enum
//
// DPHY_ATEST_SEL_LANE1 enum
//
// DPHY_ATEST_SEL_LANE2 enum
//
// DPHY_ATEST_SEL_LANE3 enum
//
// DPHY_BYPASS enum
//
// DPHY_CRC_CONT_EN enum
//
// DPHY_CRC_EN enum
//
// DPHY_CRC_FIELD enum
//
// DPHY_CRC_MST_PHASE_ERROR_ACK enum
//
// DPHY_CRC_SEL enum
//
// DPHY_FEC_ENABLE enum
//
// DPHY_FEC_READY enum
//
// DPHY_LOAD_BS_COUNT_START enum
//
// DPHY_PRBS_EN enum
//
// DPHY_PRBS_SEL enum
//
// DPHY_RX_FAST_TRAINING_CAPABLE enum
//
// DPHY_SCRAMBLER_ADVANCE enum
//
// DPHY_SCRAMBLER_DIS enum
//
// DPHY_SCRAMBLER_KCODE enum
//
// DPHY_SCRAMBLER_SEL enum
//
// DPHY_SKEW_BYPASS enum
//
// DPHY_STREAM_RESET_DURING_FAST_TRAINING_ENUM enum
//
// DPHY_SW_FAST_TRAINING_START enum
//
// DPHY_TRAINING_PATTERN_SEL enum
//
// DP_COMPONENT_DEPTH enum
//
// DP_CP_ENCRYPTION_TYPE enum
//
// DP_DPHY_8B10B_EXT_DISP enum
//
// DP_DPHY_FAST_TRAINING_COMPLETE_ACK enum
//
// DP_DPHY_FAST_TRAINING_COMPLETE_MASK enum
//
// DP_DPHY_FAST_TRAINING_VBLANK_EDGE_DETECT_EN enum
//
// DP_DPHY_HBR2_PATTERN_CONTROL_MODE enum
//
// DP_DSC_MODE enum
//
// DP_EMBEDDED_PANEL_MODE enum
//
// DP_LINK_TRAINING_COMPLETE enum
//
// DP_LINK_TRAINING_SWITCH_MODE enum
//
// DP_ML_PHY_SEQ_MODE enum
//
// DP_MSA_V_TIMING_OVERRIDE_EN enum
//
// DP_MSE_BLANK_CODE enum
//
// DP_MSE_LINK_LINE enum
//
// DP_MSE_SAT_ENCRYPT0 enum
//
// DP_MSE_SAT_ENCRYPT1 enum
//
// DP_MSE_SAT_ENCRYPT2 enum
//
// DP_MSE_SAT_ENCRYPT3 enum
//
// DP_MSE_SAT_ENCRYPT4 enum
//
// DP_MSE_SAT_ENCRYPT5 enum
//
// DP_MSE_SAT_UPDATE_ACT enum
//
// DP_MSE_TIMESTAMP_MODE enum
//
// DP_MSE_ZERO_ENCODER enum
//
// DP_MSO_NUM_OF_SST_LINKS enum
//
// DP_PIXEL_ENCODING enum
//
// DP_PIXEL_PER_CYCLE_PROCESSING_NUM enum
//
// DP_SEC_ASP_CHANNEL_COUNT_OVERRIDE enum
//
// DP_SEC_ASP_PRIORITY enum
//
// DP_SEC_AUDIO_MUTE enum
//
// DP_SEC_COLLISION_ACK enum
//
// DP_SEC_GSP0_PRIORITY enum
//
// DP_SEC_GSP_SEND enum
//
// DP_SEC_GSP_SEND_ANY_LINE enum
//
// DP_SEC_GSP_SEND_PPS enum
//
// DP_SEC_LINE_REFERENCE enum
//
// DP_SEC_TIMESTAMP_MODE enum
//
// DP_STEER_OVERFLOW_ACK enum
//
// DP_STEER_OVERFLOW_MASK enum
//
// DP_SYNC_POLARITY enum
//
// DP_TU_OVERFLOW_ACK enum
//
// DP_UDI_LANES enum
//
// DP_VID_ENHANCED_FRAME_MODE enum
//
// DP_VID_M_N_DOUBLE_BUFFER_MODE enum
//
// DP_VID_M_N_GEN_EN enum
//
// DP_VID_N_MUL enum
//
// DP_VID_STREAM_DISABLE_ACK enum
//
// DP_VID_STREAM_DISABLE_MASK enum
//
// DP_VID_STREAM_DIS_DEFER enum
//
// DP_VID_VBID_FIELD_POL enum
//
// FEC_ACTIVE_STATUS enum
//
// DIG Enums
//
// DIG_BE_CNTL_HPD_SELECT enum
//
// DIG_BE_CNTL_MODE enum
//
// DIG_DIGITAL_BYPASS_ENABLE enum
//
// DIG_DIGITAL_BYPASS_SEL enum
//
// DIG_FE_CNTL_SOURCE_SELECT enum
//
// DIG_FE_CNTL_STEREOSYNC_SELECT enum
//
// DIG_FIFO_CTRL_FORCE_RECOMP_MINMAX enum
//
// DIG_FIFO_CTRL_USE_OVERWRITE_LEVEL enum
//
// DIG_FIFO_FORCE_RECAL_AVERAGE enum
//
// DIG_FIFO_OUTPUT_PROCESSING_MODE enum
//
// DIG_FIFO_OVERFLOW_UNDERFLOW_ERROR enum
//
// DIG_FIFO_READ_CLOCK_SRC enum
//
// DIG_INPUT_PIXEL_SEL enum
//
// DIG_OUTPUT_CRC_CNTL_LINK_SEL enum
//
// DIG_OUTPUT_CRC_DATA_SEL enum
//
// DIG_RANDOM_PATTERN_SEED_RAN_PAT enum
//
// DIG_SL_PIXEL_GROUPING enum
//
// DIG_TEST_PATTERN_EXTERNAL_RESET_EN enum
//
// DIG_TEST_PATTERN_HALF_CLOCK_PATTERN_SEL enum
//
// DIG_TEST_PATTERN_RANDOM_PATTERN_OUT_EN enum
//
// DIG_TEST_PATTERN_RANDOM_PATTERN_RESET enum
//
// DIG_TEST_PATTERN_TEST_PATTERN_OUT_EN enum
//
// DOLBY_VISION_ENABLE enum
//
// HDMI_ACP_SEND enum
//
// HDMI_ACR_AUDIO_PRIORITY enum
//
// HDMI_ACR_CONT enum
//
// HDMI_ACR_N_MULTIPLE enum
//
// HDMI_ACR_SELECT enum
//
// HDMI_ACR_SEND enum
//
// HDMI_ACR_SOURCE enum
//
// HDMI_AUDIO_DELAY_EN enum
//
// HDMI_AUDIO_INFO_CONT enum
//
// HDMI_AUDIO_INFO_SEND enum
//
// HDMI_CLOCK_CHANNEL_RATE enum
//
// HDMI_DATA_SCRAMBLE_EN enum
//
// HDMI_DEEP_COLOR_DEPTH enum
//
// HDMI_DEFAULT_PAHSE enum
//
// HDMI_ERROR_ACK enum
//
// HDMI_ERROR_MASK enum
//
// HDMI_GC_AVMUTE enum
//
// HDMI_GC_AVMUTE_CONT enum
//
// HDMI_GC_CONT enum
//
// HDMI_GC_SEND enum
//
// HDMI_GENERIC_CONT enum
//
// HDMI_GENERIC_SEND enum
//
// HDMI_ISRC_CONT enum
//
// HDMI_ISRC_SEND enum
//
// HDMI_KEEPOUT_MODE enum
//
// HDMI_METADATA_ENABLE enum
//
// HDMI_MPEG_INFO_CONT enum
//
// HDMI_MPEG_INFO_SEND enum
//
// HDMI_NO_EXTRA_NULL_PACKET_FILLED enum
//
// HDMI_NULL_SEND enum
//
// HDMI_PACKET_GEN_VERSION enum
//
// HDMI_PACKET_LINE_REFERENCE enum
//
// HDMI_PACKING_PHASE_OVERRIDE enum
//
// LVTMA_RANDOM_PATTERN_SEED_RAN_PAT enum
//
// TMDS_COLOR_FORMAT enum
//
// TMDS_CTL0_DATA_INVERT enum
//
// TMDS_CTL0_DATA_MODULATION enum
//
// TMDS_CTL0_DATA_SEL enum
//
// TMDS_CTL0_PATTERN_OUT_EN enum
//
// TMDS_CTL1_DATA_INVERT enum
//
// TMDS_CTL1_DATA_MODULATION enum
//
// TMDS_CTL1_DATA_SEL enum
//
// TMDS_CTL1_PATTERN_OUT_EN enum
//
// TMDS_CTL2_DATA_INVERT enum
//
// TMDS_CTL2_DATA_MODULATION enum
//
// TMDS_CTL2_DATA_SEL enum
//
// TMDS_CTL2_PATTERN_OUT_EN enum
//
// TMDS_CTL3_DATA_INVERT enum
//
// TMDS_CTL3_DATA_MODULATION enum
//
// TMDS_CTL3_DATA_SEL enum
//
// TMDS_CTL3_PATTERN_OUT_EN enum
//
// TMDS_DATA_SYNCHRONIZATION_DSINTSEL enum
//
// TMDS_PIXEL_ENCODING enum
//
// TMDS_REG_TEST_OUTPUTA_CNTLA enum
//
// TMDS_REG_TEST_OUTPUTB_CNTLB enum
//
// TMDS_STEREOSYNC_CTL_SEL_REG enum
//
// TMDS_SYNC_PHASE enum
//
// TMDS_TRANSMITTER_CONTROL_BYPASS_PLLA enum
//
// TMDS_TRANSMITTER_CONTROL_BYPASS_PLLB enum
//
// TMDS_TRANSMITTER_CONTROL_IDSCKSELA enum
//
// TMDS_TRANSMITTER_CONTROL_IDSCKSELB enum
//
// TMDS_TRANSMITTER_CONTROL_PLLSEL_OVERWRITE_EN enum
//
// TMDS_TRANSMITTER_CONTROL_PLL_ENABLE_HPD_MASK enum
//
// TMDS_TRANSMITTER_CONTROL_PLL_PWRUP_SEQ_EN enum
//
// TMDS_TRANSMITTER_CONTROL_PLL_RESET_HPD_MASK enum
//
// TMDS_TRANSMITTER_CONTROL_TDCLK_FROM_PADS enum
//
// TMDS_TRANSMITTER_CONTROL_TMCLK_FROM_PADS enum
//
// TMDS_TRANSMITTER_ENABLE_HPD_MASK enum
//
// TMDS_TRANSMITTER_ENABLE_LNKCEN_HPD_MASK enum
//
// TMDS_TRANSMITTER_ENABLE_LNKDEN_HPD_MASK enum
//
// DP_AUX Enums
//
// DP_AUX_ARB_CONTROL_ARB_PRIORITY enum
//
// DP_AUX_ARB_CONTROL_DONE_USING_AUX_REG enum
//
// DP_AUX_ARB_CONTROL_USE_AUX_REG_REQ enum
//
// DP_AUX_ARB_STATUS enum
//
// DP_AUX_CONTROL_HPD_SEL enum
//
// DP_AUX_CONTROL_TEST_MODE enum
//
// DP_AUX_DEFINITE_ERR_REACHED_ACK enum
//
// DP_AUX_DPHY_RX_CONTROL_ALLOW_BELOW_THRESHOLD_PHASE_DETECT enum
//
// DP_AUX_DPHY_RX_CONTROL_ALLOW_BELOW_THRESHOLD_START enum
//
// DP_AUX_DPHY_RX_CONTROL_ALLOW_BELOW_THRESHOLD_STOP enum
//
// DP_AUX_DPHY_RX_CONTROL_HALF_SYM_DETECT_LEN enum
//
// DP_AUX_DPHY_RX_CONTROL_PHASE_DETECT_LEN enum
//
// DP_AUX_DPHY_RX_CONTROL_RECEIVE_WINDOW enum
//
// DP_AUX_DPHY_RX_CONTROL_START_WINDOW enum
//
// DP_AUX_DPHY_RX_DETECTION_THRESHOLD enum
//
// DP_AUX_DPHY_TX_CONTROL_MODE_DET_CHECK_DELAY enum
//
// DP_AUX_DPHY_TX_REF_CONTROL_TX_RATE enum
//
// DP_AUX_DPHY_TX_REF_CONTROL_TX_REF_SEL enum
//
// DP_AUX_ERR_OCCURRED_ACK enum
//
// DP_AUX_GTC_SYNC_CONTROL_GTC_SYNC_BLOCK_REQ enum
//
// DP_AUX_GTC_SYNC_CONTROL_INTERVAL_RESET_WINDOW enum
//
// DP_AUX_GTC_SYNC_CONTROL_OFFSET_CALC_MAX_ATTEMPT enum
//
// DP_AUX_GTC_SYNC_ERROR_CONTROL_LOCK_ACQ_TIMEOUT_LEN enum
//
// DP_AUX_INT_ACK enum
//
// DP_AUX_LS_UPDATE_ACK enum
//
// DP_AUX_PHY_WAKE_PRIORITY enum
//
// DP_AUX_POTENTIAL_ERR_REACHED_ACK enum
//
// DP_AUX_RESET enum
//
// DP_AUX_RESET_DONE enum
//
// DP_AUX_RX_TIMEOUT_LEN_MUL enum
//
// DP_AUX_SW_CONTROL_LS_READ_TRIG enum
//
// DP_AUX_SW_CONTROL_SW_GO enum
//
// DP_AUX_TX_PRECHARGE_LEN_MUL enum
//
// DOUT_I2C Enums
//
// DOUT_I2C_ACK enum
//
// DOUT_I2C_ARBITRATION_ABORT_XFER enum
//
// DOUT_I2C_ARBITRATION_DONE_USING_I2C_REG enum
//
// DOUT_I2C_ARBITRATION_NO_QUEUED_SW_GO enum
//
// DOUT_I2C_ARBITRATION_SW_PRIORITY enum
//
// DOUT_I2C_ARBITRATION_USE_I2C_REG_REQ enum
//
// DOUT_I2C_CONTROL_DBG_REF_SEL enum
//
// DOUT_I2C_CONTROL_DDC_SELECT enum
//
// DOUT_I2C_CONTROL_GO enum
//
// DOUT_I2C_CONTROL_SEND_RESET enum
//
// DOUT_I2C_CONTROL_SEND_RESET_LENGTH enum
//
// DOUT_I2C_CONTROL_SOFT_RESET enum
//
// DOUT_I2C_CONTROL_SW_STATUS_RESET enum
//
// DOUT_I2C_CONTROL_TRANSACTION_COUNT enum
//
// DOUT_I2C_DATA_INDEX_WRITE enum
//
// DOUT_I2C_DDC_SETUP_CLK_DRIVE_EN enum
//
// DOUT_I2C_DDC_SETUP_DATA_DRIVE_EN enum
//
// DOUT_I2C_DDC_SETUP_DATA_DRIVE_SEL enum
//
// DOUT_I2C_DDC_SETUP_EDID_DETECT_MODE enum
//
// DOUT_I2C_DDC_SPEED_THRESHOLD enum
//
// DOUT_I2C_EDID_DETECT_CTRL_SEND_RESET enum
//
// DOUT_I2C_READ_REQUEST_INTERRUPT_TYPE enum
//
// DOUT_I2C_TRANSACTION_STOP_ON_NACK enum
//
// DIO_MISC Enums
//
// CLOCK_GATING_EN enum
//
// DAC_MUX_SELECT enum
//
// DIOMEM_PWR_DIS_CTRL enum
//
// DIOMEM_PWR_FORCE_CTRL enum
//
// DIOMEM_PWR_FORCE_CTRL2 enum
//
// DIOMEM_PWR_SEL_CTRL enum
//
// DIOMEM_PWR_SEL_CTRL2 enum
//
// DIO_DBG_BLOCK_SEL enum
//
// DIO_HDMI_RXSTATUS_TIMER_CONTROL_DIO_HDMI_RXSTATUS_TIMER_TYPE enum
//
// DX_PROTECTION_DX_PIPE_ENC_REQUIRED_TYPE enum
//
// ENUM_DIO_DCN_ACTIVE_STATUS enum
//
// GENERIC_STEREOSYNC_SEL enum
//
// PM_ASSERT_RESET enum
//
// SOFT_RESET enum
//
// TMDS_MUX_SELECT enum
//
// DME Enums
//
// DME_MEM_POWER_STATE_ENUM enum
//
// DME_MEM_PWR_DIS_CTRL enum
//
// DME_MEM_PWR_FORCE_CTRL enum
//
// METADATA_HUBP_SEL enum
//
// METADATA_STREAM_TYPE_SEL enum
//
// VPG Enums
//
// VPG_MEM_PWR_DIS_CTRL enum
//
// VPG_MEM_PWR_FORCE_CTRL enum
//
// AFMT Enums
//
// AFMT_ACP_TYPE enum
//
// AFMT_AUDIO_CRC_CONTROL_CH_SEL enum
//
// AFMT_AUDIO_CRC_CONTROL_CONT enum
//
// AFMT_AUDIO_CRC_CONTROL_SOURCE enum
//
// AFMT_AUDIO_PACKET_CONTROL2_AUDIO_LAYOUT_OVRD enum
//
// AFMT_AUDIO_PACKET_CONTROL_AUDIO_SAMPLE_SEND enum
//
// AFMT_AUDIO_PACKET_CONTROL_RESET_FIFO_WHEN_AUDIO_DIS enum
//
// AFMT_AUDIO_SRC_CONTROL_SELECT enum
//
// AFMT_HDMI_AUDIO_SEND_MAX_PACKETS enum
//
// AFMT_INFOFRAME_CONTROL0_AUDIO_INFO_SOURCE enum
//
// AFMT_INTERRUPT_STATUS_CHG_MASK enum
//
// AFMT_MEM_PWR_DIS_CTRL enum
//
// AFMT_MEM_PWR_FORCE_CTRL enum
//
// AFMT_RAMP_CONTROL0_SIGN enum
//
// AFMT_VBI_PACKET_CONTROL_ACP_SOURCE enum
//
// AUDIO_LAYOUT_SELECT enum
//
// HPO_TOP Enums
//
// HPO_TOP_CLOCK_GATING_DISABLE enum
//
// HPO_TOP_TEST_CLK_SEL enum
//
// DP_STREAM_MAPPER Enums
//
// DP_STREAM_MAPPER_DP_STREAM_LINK_TARGET enum
//
// HDMI_STREAM_ENC Enums
//
// HDMI_STREAM_ENC_DB_DISABLE_CONTROL enum
//
// HDMI_STREAM_ENC_DSC_MODE enum
//
// HDMI_STREAM_ENC_ENABLE_CONTROL enum
//
// HDMI_STREAM_ENC_ODM_COMBINE_MODE enum
//
// HDMI_STREAM_ENC_OVERFLOW_UNDERFLOW_ERROR enum
//
// HDMI_STREAM_ENC_OVERWRITE_LEVEL_SELECT enum
//
// HDMI_STREAM_ENC_PIXEL_ENCODING enum
//
// HDMI_STREAM_ENC_READ_CLOCK_CONTROL enum
//
// HDMI_STREAM_ENC_RESET_CONTROL enum
//
// HDMI_STREAM_ENC_STREAM_ACTIVE enum
//
// HDMI_TB_ENC Enums
//
// BORROWBUFFER_MEM_POWER_STATE_ENUM enum
//
// HDMI_BORROW_MODE enum
//
// HDMI_TB_ENC_ACP_SEND enum
//
// HDMI_TB_ENC_ACR_AUDIO_PRIORITY enum
//
// HDMI_TB_ENC_ACR_CONT enum
//
// HDMI_TB_ENC_ACR_N_MULTIPLE enum
//
// HDMI_TB_ENC_ACR_SELECT enum
//
// HDMI_TB_ENC_ACR_SEND enum
//
// HDMI_TB_ENC_ACR_SOURCE enum
//
// HDMI_TB_ENC_AUDIO_INFO_CONT enum
//
// HDMI_TB_ENC_AUDIO_INFO_SEND enum
//
// HDMI_TB_ENC_CRC_SRC_SEL enum
//
// HDMI_TB_ENC_CRC_TYPE enum
//
// HDMI_TB_ENC_DEEP_COLOR_DEPTH enum
//
// HDMI_TB_ENC_DEFAULT_PAHSE enum
//
// HDMI_TB_ENC_DSC_MODE enum
//
// HDMI_TB_ENC_ENABLE enum
//
// HDMI_TB_ENC_GC_AVMUTE enum
//
// HDMI_TB_ENC_GC_AVMUTE_CONT enum
//
// HDMI_TB_ENC_GC_CONT enum
//
// HDMI_TB_ENC_GC_SEND enum
//
// HDMI_TB_ENC_GENERIC_CONT enum
//
// HDMI_TB_ENC_GENERIC_LOCK_EN enum
//
// HDMI_TB_ENC_GENERIC_SEND enum
//
// HDMI_TB_ENC_ISRC_CONT enum
//
// HDMI_TB_ENC_ISRC_SEND enum
//
// HDMI_TB_ENC_METADATA_ENABLE enum
//
// HDMI_TB_ENC_PACKET_LINE_REFERENCE enum
//
// HDMI_TB_ENC_PIXEL_ENCODING enum
//
// HDMI_TB_ENC_RESET enum
//
// HDMI_TB_ENC_SYNC_PHASE enum
//
// INPUT_FIFO_ERROR_TYPE enum
//
// DP_STREAM_ENC Enums
//
// DP_STREAM_ENC_OVERFLOW_UNDERFLOW_ERROR enum
//
// DP_STREAM_ENC_OVERWRITE_LEVEL_SELECT enum
//
// DP_STREAM_ENC_READ_CLOCK_CONTROL enum
//
// DP_STREAM_ENC_RESET_CONTROL enum
//
// DP_STREAM_ENC_STREAM_ACTIVE enum
//
// DP_SYM32_ENC Enums
//
// ENUM_DP_SYM32_ENC_AUDIO_MUTE enum
//
// ENUM_DP_SYM32_ENC_CONTINUOUS_MODE enum
//
// ENUM_DP_SYM32_ENC_CRC_VALID enum
//
// ENUM_DP_SYM32_ENC_DP_COMPONENT_DEPTH enum
//
// ENUM_DP_SYM32_ENC_ENABLE enum
//
// ENUM_DP_SYM32_ENC_GSP_DEADLINE_MISSED enum
//
// ENUM_DP_SYM32_ENC_GSP_ONE_SHOT_TRIGGER_POSITION enum
//
// ENUM_DP_SYM32_ENC_GSP_PAYLOAD_SIZE enum
//
// ENUM_DP_SYM32_ENC_GSP_TRIGGER_PENDING enum
//
// ENUM_DP_SYM32_ENC_MEM_PWR_FORCE_ENUM enum
//
// ENUM_DP_SYM32_ENC_OVERFLOW_STATUS enum
//
// ENUM_DP_SYM32_ENC_PENDING enum
//
// ENUM_DP_SYM32_ENC_PIXEL_ENCODING enum
//
// ENUM_DP_SYM32_ENC_PIXEL_ENCODING_TYPE enum
//
// ENUM_DP_SYM32_ENC_POWER_STATE_ENUM enum
//
// ENUM_DP_SYM32_ENC_RESET enum
//
// ENUM_DP_SYM32_ENC_SDP_PRIORITY enum
//
// ENUM_DP_SYM32_ENC_SOF_REFERENCE enum
//
// ENUM_DP_SYM32_ENC_VID_STREAM_DEFER enum
//
// DP_DPHY_SYM32 Enums
//
// ENUM_DP_DPHY_SYM32_CRC_END_EVENT enum
//
// ENUM_DP_DPHY_SYM32_CRC_START_EVENT enum
//
// ENUM_DP_DPHY_SYM32_CRC_TAP_SOURCE enum
//
// ENUM_DP_DPHY_SYM32_CRC_USE_NUM_SYMBOLS enum
//
// ENUM_DP_DPHY_SYM32_ENABLE enum
//
// ENUM_DP_DPHY_SYM32_ENCRYPT_TYPE enum
//
// ENUM_DP_DPHY_SYM32_MODE enum
//
// ENUM_DP_DPHY_SYM32_NUM_LANES enum
//
// ENUM_DP_DPHY_SYM32_RATE_UPDATE_PENDING enum
//
// ENUM_DP_DPHY_SYM32_RESET enum
//
// ENUM_DP_DPHY_SYM32_RESET_STATUS enum
//
// ENUM_DP_DPHY_SYM32_SAT_UPDATE enum
//
// ENUM_DP_DPHY_SYM32_SAT_UPDATE_PENDING enum
//
// ENUM_DP_DPHY_SYM32_STATUS enum
//
// ENUM_DP_DPHY_SYM32_STREAM_OVR_ENABLE enum
//
// ENUM_DP_DPHY_SYM32_STREAM_OVR_TYPE enum
//
// ENUM_DP_DPHY_SYM32_TP_PRBS_SEL enum
//
// ENUM_DP_DPHY_SYM32_TP_SELECT enum
//
// APG Enums
//
// APG_AUDIO_CRC_CONTROL_CH_SEL enum
//
// APG_AUDIO_CRC_CONTROL_CONT enum
//
// APG_DBG_ACP_TYPE enum
//
// APG_DBG_AUDIO_DTO_BASE enum
//
// APG_DBG_AUDIO_DTO_DIV enum
//
// APG_DBG_AUDIO_DTO_MULTI enum
//
// APG_DBG_MUX_SEL enum
//
// APG_DP_ASP_CHANNEL_COUNT_OVERRIDE enum
//
// APG_MEM_POWER_STATE enum
//
// APG_MEM_PWR_DIS_CTRL enum
//
// APG_MEM_PWR_FORCE_CTRL enum
//
// APG_PACKET_CONTROL_ACP_SOURCE enum
//
// APG_PACKET_CONTROL_AUDIO_INFO_SOURCE enum
//
// APG_RAMP_CONTROL_SIGN enum
//
// DCIO Enums
//
// DCIO_BL_PWM_GRP1_FRAME_START_DISP_SEL enum
//
// DCIO_CLOCK_CNTL_DCIO_TEST_CLK_SEL enum
//
// DCIO_CLOCK_CNTL_DISPCLK_R_DCIO_GATE_DIS enum
//
// DCIO_DBG_ASYNC_4BIT_SEL enum
//
// DCIO_DBG_ASYNC_BLOCK_SEL enum
//
// DCIO_DCRXPHY_SOFT_RESET enum
//
// DCIO_DC_GENERICA_SEL enum
//
// DCIO_DC_GENERICB_SEL enum
//
// DCIO_DC_GENERIC_UNIPHY_FBDIV_CLK_DIV2_SEL enum
//
// DCIO_DC_GENERIC_UNIPHY_FBDIV_CLK_SEL enum
//
// DCIO_DC_GENERIC_UNIPHY_FBDIV_SSC_CLK_SEL enum
//
// DCIO_DC_GENERIC_UNIPHY_REFDIV_CLK_SEL enum
//
// DCIO_DC_GPIO_DEBUG_DPRX_LOOPBACK_ENABLE enum
//
// DCIO_DC_GPU_TIMER_READ_SELECT enum
//
// DCIO_DC_GPU_TIMER_START_POSITION enum
//
// DCIO_DC_REF_CLK_CNTL_GENLK_CLK_OUTPUT_SEL enum
//
// DCIO_DC_REF_CLK_CNTL_HSYNCA_OUTPUT_SEL enum
//
// DCIO_DIO_EXT_VSYNC_MASK enum
//
// DCIO_DIO_OTG_EXT_VSYNC_MUX enum
//
// DCIO_DPCS_INTERRUPT_MASK enum
//
// DCIO_DPCS_INTERRUPT_TYPE enum
//
// DCIO_DSYNC_SOFT_RESET enum
//
// DCIO_GENLK_CLK_GSL_MASK enum
//
// DCIO_GENLK_VSYNC_GSL_MASK enum
//
// DCIO_GSL_SEL enum
//
// DCIO_PHY_HPO_ENC_SRC_SEL enum
//
// DCIO_SWAPLOCK_A_GSL_MASK enum
//
// DCIO_SWAPLOCK_B_GSL_MASK enum
//
// DCIO_UNIPHY_CHANNEL_XBAR_SOURCE enum
//
// DCIO_UNIPHY_IMPCAL_SEL enum
//
// DCIO_UNIPHY_LINK_CNTL_CHANNEL_INVERT enum
//
// DCIO_UNIPHY_LINK_CNTL_ENABLE_HPD_MASK enum
//
// DCIO_CHIP Enums
//
// DCIOCHIP_AUX_ALL_PWR_OK enum
//
// DCIOCHIP_AUX_CSEL0P9 enum
//
// DCIOCHIP_AUX_CSEL1P1 enum
//
// DCIOCHIP_AUX_FALLSLEWSEL enum
//
// DCIOCHIP_AUX_HYS_TUNE enum
//
// DCIOCHIP_AUX_RECEIVER_SEL enum
//
// DCIOCHIP_AUX_RSEL0P9 enum
//
// DCIOCHIP_AUX_RSEL1P1 enum
//
// DCIOCHIP_AUX_SPIKESEL enum
//
// DCIOCHIP_AUX_VOD_TUNE enum
//
// DCIOCHIP_GPIO_MASK_EN enum
//
// DCIOCHIP_HPD_SEL enum
//
// DCIOCHIP_I2C_COMPSEL enum
//
// DCIOCHIP_I2C_FALLSLEWSEL enum
//
// DCIOCHIP_I2C_RECEIVER_SEL enum
//
// DCIOCHIP_I2C_VPH_1V2_EN enum
//
// DCIOCHIP_INVERT enum
//
// DCIOCHIP_MASK enum
//
// DCIOCHIP_PAD_MODE enum
//
// DCIOCHIP_PD_EN enum
//
// DCIOCHIP_REF_27_SRC_SEL enum
//
// PWRSEQ Enums
//
// PWRSEQ_BL_PWM_CNTL2_BL_PWM_OVERRIDE_BL_OUT_ENABLE enum
//
// PWRSEQ_BL_PWM_CNTL2_BL_PWM_OVERRIDE_PANEL_PWRSEQ_EN enum
//
// PWRSEQ_BL_PWM_CNTL2_DBG_BL_PWM_INPUT_REFCLK_SELECT enum
//
// PWRSEQ_BL_PWM_CNTL_BL_PWM_EN enum
//
// PWRSEQ_BL_PWM_CNTL_BL_PWM_FRACTIONAL_EN enum
//
// PWRSEQ_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN enum
//
// PWRSEQ_BL_PWM_GRP1_READBACK_DB_REG_VALUE_EN enum
//
// PWRSEQ_BL_PWM_GRP1_REG_LOCK enum
//
// PWRSEQ_BL_PWM_GRP1_UPDATE_AT_FRAME_START enum
//
// PWRSEQ_GPIO_MASK_EN enum
//
// PWRSEQ_PANEL_PWRSEQ_CNTL_PANEL_BLON enum
//
// PWRSEQ_PANEL_PWRSEQ_CNTL_PANEL_BLON_POL enum
//
// PWRSEQ_PANEL_PWRSEQ_CNTL_PANEL_DIGON enum
//
// PWRSEQ_PANEL_PWRSEQ_CNTL_PANEL_DIGON_POL enum
//
// PWRSEQ_PANEL_PWRSEQ_CNTL_PANEL_SYNCEN_POL enum
//
// PWRSEQ_PANEL_PWRSEQ_CNTL_TARGET_STATE enum
//
// PWRSEQ_PANEL_PWRSEQ_DELAY2_PANEL_VARY_BL_OVERRIDE_EN enum
//
// AZCONTROLLER Enums
//
// AZ_CORB_SIZE enum
//
// AZ_GLOBAL_CAPABILITIES enum
//
// AZ_RIRB_SIZE enum
//
// AZ_RIRB_WRITE_POINTER_RESET enum
//
// AZ_STATE_CHANGE_STATUS enum
//
// CORB_READ_POINTER_RESET enum
//
// DMA_POSITION_LOWER_BASE_ADDRESS_BUFFER_ENABLE enum
//
// GENERIC_AZ_CONTROLLER_REGISTER_ENABLE_CONTROL enum
//
// GENERIC_AZ_CONTROLLER_REGISTER_ENABLE_CONTROL_RESERVED enum
//
// GENERIC_AZ_CONTROLLER_REGISTER_STATUS enum
//
// GENERIC_AZ_CONTROLLER_REGISTER_STATUS_RESERVED enum
//
// GLOBAL_CONTROL_ACCEPT_UNSOLICITED_RESPONSE enum
//
// GLOBAL_CONTROL_CONTROLLER_RESET enum
//
// GLOBAL_CONTROL_FLUSH_CONTROL enum
//
// GLOBAL_STATUS_FLUSH_STATUS enum
//
// IMMEDIATE_COMMAND_STATUS_IMMEDIATE_COMMAND_BUSY enum
//
// IMMEDIATE_COMMAND_STATUS_IMMEDIATE_RESULT_VALID enum
//
// RIRB_CONTROL_RESPONSE_INTERRUPT_CONTROL enum
//
// RIRB_CONTROL_RESPONSE_OVERRUN_INTERRUPT_CONTROL enum
//
// STREAM_0_SYNCHRONIZATION enum
//
// STREAM_10_SYNCHRONIZATION enum
//
// STREAM_11_SYNCHRONIZATION enum
//
// STREAM_12_SYNCHRONIZATION enum
//
// STREAM_13_SYNCHRONIZATION enum
//
// STREAM_14_SYNCHRONIZATION enum
//
// STREAM_15_SYNCHRONIZATION enum
//
// STREAM_1_SYNCHRONIZATION enum
//
// STREAM_2_SYNCHRONIZATION enum
//
// STREAM_3_SYNCHRONIZATION enum
//
// STREAM_4_SYNCHRONIZATION enum
//
// STREAM_5_SYNCHRONIZATION enum
//
// STREAM_6_SYNCHRONIZATION enum
//
// STREAM_7_SYNCHRONIZATION enum
//
// STREAM_8_SYNCHRONIZATION enum
//
// STREAM_9_SYNCHRONIZATION enum
//
// AZENDPOINT Enums
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_CONVERTER_FORMAT_BITS_PER_SAMPLE enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_CONVERTER_FORMAT_NUMBER_OF_CHANNELS enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_CONVERTER_FORMAT_SAMPLE_BASE_DIVISOR enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_CONVERTER_FORMAT_SAMPLE_BASE_MULTIPLE enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_CONVERTER_FORMAT_SAMPLE_BASE_RATE enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_CONVERTER_FORMAT_STREAM_TYPE enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER_3_KEEPALIVE enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER_COPY enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER_DIGEN enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER_L enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER_NON_AUDIO enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER_PRE enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER_PRO enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER_V enum
//
// AZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER_VCFG enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_AUDIO_DESCRIPTOR_FORMAT_CODE enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_DOWN_MIX_INFO_DOWN_MIX_INHIBIT enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL01_ENABLE_MULTICHANNEL01_MUTE enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL1_ENABLE_MULTICHANNEL1_MUTE enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL23_ENABLE_MULTICHANNEL23_MUTE enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL3_ENABLE_MULTICHANNEL3_MUTE enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL45_ENABLE_MULTICHANNEL45_MUTE enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL5_ENABLE_MULTICHANNEL5_MUTE enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL67_ENABLE_MULTICHANNEL67_MUTE enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL7_ENABLE_MULTICHANNEL7_MUTE enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL_MODE_MULTICHANNEL_MODE enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_UNSOLICITED_RESPONSE_ENABLE enum
//
// AZALIA_F2_CODEC_PIN_CONTROL_WIDGET_CONTROL_OUT_ENABLE enum
//
// AZF0CONTROLLER Enums
//
// AZALIA_SOFT_RESET_REFCLK_SOFT_RESET enum
//
// MEM_PWR_DIS_CTRL enum
//
// MEM_PWR_FORCE_CTRL enum
//
// MEM_PWR_FORCE_CTRL2 enum
//
// MEM_PWR_SEL_CTRL enum
//
// MEM_PWR_SEL_CTRL2 enum
//
// AZF0ROOT Enums
//
// CC_RCU_DC_AUDIO_INPUT_PORT_CONNECTIVITY_INPUT_PORT_CONNECTIVITY enum
//
// CC_RCU_DC_AUDIO_PORT_CONNECTIVITY_PORT_CONNECTIVITY enum
//
// AZINPUTENDPOINT Enums
//
// AZALIA_F2_CODEC_INPUT_CONVERTER_CONTROL_CONVERTER_FORMAT_BITS_PER_SAMPLE enum
//
// AZALIA_F2_CODEC_INPUT_CONVERTER_CONTROL_CONVERTER_FORMAT_NUMBER_OF_CHANNELS enum
//
// AZALIA_F2_CODEC_INPUT_CONVERTER_CONTROL_CONVERTER_FORMAT_SAMPLE_BASE_DIVISOR enum
//
// AZALIA_F2_CODEC_INPUT_CONVERTER_CONTROL_CONVERTER_FORMAT_SAMPLE_BASE_MULTIPLE enum
//
// AZALIA_F2_CODEC_INPUT_CONVERTER_CONTROL_CONVERTER_FORMAT_SAMPLE_BASE_RATE enum
//
// AZALIA_F2_CODEC_INPUT_CONVERTER_CONTROL_CONVERTER_FORMAT_STREAM_TYPE enum
//
// AZALIA_F2_CODEC_INPUT_CONVERTER_CONTROL_DIGITAL_CONVERTER_DIGEN enum
//
// AZALIA_F2_CODEC_INPUT_PIN_CONTROL_MULTICHANNEL0_ENABLE_MULTICHANNEL0_MUTE enum
//
// AZALIA_F2_CODEC_INPUT_PIN_CONTROL_MULTICHANNEL1_ENABLE_MULTICHANNEL1_MUTE enum
//
// AZALIA_F2_CODEC_INPUT_PIN_CONTROL_MULTICHANNEL2_ENABLE_MULTICHANNEL2_MUTE enum
//
// AZALIA_F2_CODEC_INPUT_PIN_CONTROL_MULTICHANNEL3_ENABLE_MULTICHANNEL3_MUTE enum
//
// AZALIA_F2_CODEC_INPUT_PIN_CONTROL_MULTICHANNEL4_ENABLE_MULTICHANNEL4_MUTE enum
//
// AZALIA_F2_CODEC_INPUT_PIN_CONTROL_MULTICHANNEL5_ENABLE_MULTICHANNEL5_MUTE enum
//
// AZALIA_F2_CODEC_INPUT_PIN_CONTROL_MULTICHANNEL6_ENABLE_MULTICHANNEL6_MUTE enum
//
// AZALIA_F2_CODEC_INPUT_PIN_CONTROL_MULTICHANNEL7_ENABLE_MULTICHANNEL7_MUTE enum
//
// AZALIA_F2_CODEC_INPUT_PIN_CONTROL_UNSOLICITED_RESPONSE_ENABLE enum
//
// AZALIA_F2_CODEC_INPUT_PIN_CONTROL_WIDGET_CONTROL_IN_ENABLE enum
//
// AZROOT Enums
//
// AZALIA_F2_CODEC_FUNCTION_CONTROL_RESET_CODEC_RESET enum
//
// AZF0STREAM Enums
//
// AZ_LATENCY_COUNTER_CONTROL enum
//
// AZSTREAM Enums
//
// OUTPUT_STREAM_DESCRIPTOR_CONTROL_AND_STATUS_BUFFER_COMPLETION_INTERRUPT_STATUS enum
//
// OUTPUT_STREAM_DESCRIPTOR_CONTROL_AND_STATUS_DESCRIPTOR_ERROR enum
//
// OUTPUT_STREAM_DESCRIPTOR_CONTROL_AND_STATUS_DESCRIPTOR_ERROR_INTERRUPT_ENABLE enum
//
// OUTPUT_STREAM_DESCRIPTOR_CONTROL_AND_STATUS_FIFO_ERROR enum
//
// OUTPUT_STREAM_DESCRIPTOR_CONTROL_AND_STATUS_FIFO_ERROR_INTERRUPT_ENABLE enum
//
// OUTPUT_STREAM_DESCRIPTOR_CONTROL_AND_STATUS_INTERRUPT_ON_COMPLETION_ENABLE enum
//
// OUTPUT_STREAM_DESCRIPTOR_CONTROL_AND_STATUS_STREAM_RESET enum
//
// OUTPUT_STREAM_DESCRIPTOR_CONTROL_AND_STATUS_STREAM_RUN enum
//
// OUTPUT_STREAM_DESCRIPTOR_CONTROL_AND_STATUS_TRAFFIC_PRIORITY enum
//
// OUTPUT_STREAM_DESCRIPTOR_FORMAT_BITS_PER_SAMPLE enum
//
// OUTPUT_STREAM_DESCRIPTOR_FORMAT_NUMBER_OF_CHANNELS enum
//
// OUTPUT_STREAM_DESCRIPTOR_FORMAT_SAMPLE_BASE_DIVISOR enum
//
// OUTPUT_STREAM_DESCRIPTOR_FORMAT_SAMPLE_BASE_MULTIPLE enum
//
// OUTPUT_STREAM_DESCRIPTOR_FORMAT_SAMPLE_BASE_RATE enum
//
// AZF0ENDPOINT Enums
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_AMPLIFIER_PARAMETER_OVERRIDE enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_AUDIO_CHANNEL_CAPABILITIES enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_CONNECTION_LIST enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_DIGITAL enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_FORMAT_OVERRIDE enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_INPUT_AMPLIFIER_PRESENT enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_LR_SWAP enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_OUTPUT_AMPLIFIER_PRESENT enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_POWER_CONTROL enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_PROCESSING_WIDGET enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_STRIPE enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_TYPE enum
//
// AZALIA_F0_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_UNSOLICITED_RESPONSE_CAPABILITY enum
//
// AZALIA_F0_CODEC_PIN_CONTROL_MULTICHANNEL_MODE_MULTICHANNEL_MODE enum
//
// AZALIA_F0_CODEC_PIN_CONTROL_RESPONSE_HBR_HBR_CAPABLE enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_AMPLIFIER_PARAMETER_OVERRIDE enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_CONNECTION_LIST enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_DIGITAL enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_INPUT_AMPLIFIER_PRESENT enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_LR_SWAP enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_OUTPUT_AMPLIFIER_PRESENT enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_POWER_CONTROL enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_PROCESSING_WIDGET enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_STRIPE enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_TYPE enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_UNSOLICITED_RESPONSE_CAPABILITY enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_CAPABILITIES_BALANCED_I_O_PINS enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_CAPABILITIES_EAPD_CAPABLE enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_CAPABILITIES_HEADPHONE_DRIVE_CAPABLE enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_CAPABILITIES_IMPEDANCE_SENSE_CAPABLE enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_CAPABILITIES_INPUT_CAPABLE enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_CAPABILITIES_JACK_DETECTION_CAPABILITY enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_CAPABILITIES_OUTPUT_CAPABLE enum
//
// AZALIA_F0_CODEC_PIN_PARAMETER_CAPABILITIES_TRIGGER_REQUIRED enum
//
// AZF0INPUTENDPOINT Enums
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_AMPLIFIER_PARAMETER_OVERRIDE enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_AUDIO_CHANNEL_CAPABILITIES enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_CONNECTION_LIST enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_DIGITAL enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_FORMAT_OVERRIDE enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_INPUT_AMPLIFIER_PRESENT enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_LR_SWAP enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_OUTPUT_AMPLIFIER_PRESENT enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_POWER_CONTROL enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_PROCESSING_WIDGET enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_STRIPE enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_TYPE enum
//
// AZALIA_F0_CODEC_INPUT_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES_UNSOLICITED_RESPONSE_CAPABILITY enum
//
// AZALIA_F0_CODEC_INPUT_PIN_CONTROL_RESPONSE_HBR_HBR_CAPABLE enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_AMPLIFIER_PARAMETER_OVERRIDE enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_CONNECTION_LIST enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_DIGITAL enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_INPUT_AMPLIFIER_PRESENT enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_LR_SWAP enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_OUTPUT_AMPLIFIER_PRESENT enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_POWER_CONTROL enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_PROCESSING_WIDGET enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_STRIPE enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_TYPE enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES_UNSOLICITED_RESPONSE_CAPABILITY enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_CAPABILITIES_BALANCED_I_O_PINS enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_CAPABILITIES_DP enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_CAPABILITIES_EAPD_CAPABLE enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_CAPABILITIES_HDMI enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_CAPABILITIES_HEADPHONE_DRIVE_CAPABLE enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_CAPABILITIES_IMPEDANCE_SENSE_CAPABLE enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_CAPABILITIES_INPUT_CAPABLE enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_CAPABILITIES_JACK_DETECTION_CAPABILITY enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_CAPABILITIES_OUTPUT_CAPABLE enum
//
// AZALIA_F0_CODEC_INPUT_PIN_PARAMETER_CAPABILITIES_TRIGGER_REQUIRED enum
//
// DSCC Enums
//
// DSCC_BITS_PER_COMPONENT_ENUM enum
//
// DSCC_DSC_VERSION_MAJOR_ENUM enum
//
// DSCC_DSC_VERSION_MINOR_ENUM enum
//
// DSCC_ENABLE_ENUM enum
//
// DSCC_ICH_RESET_ENUM enum
//
// DSCC_LINEBUF_DEPTH_ENUM enum
//
// DSCC_MEM_PWR_DIS_ENUM enum
//
// DSCC_MEM_PWR_FORCE_ENUM enum
//
// POWER_STATE_ENUM enum
//
// DSCCIF Enums
//
// DSCCIF_BITS_PER_COMPONENT_ENUM enum
//
// DSCCIF_ENABLE_ENUM enum
//
// DSCCIF_INPUT_PIXEL_FORMAT_ENUM enum
//
// DSC_TOP Enums
//
// CLOCK_GATING_DISABLE_ENUM enum
//
// ENABLE_ENUM enum
//
// TEST_CLOCK_MUX_SELECT_ENUM enum
//
// DWB_TOP Enums
//
// DWB_CRC_CONT_EN_ENUM enum
//
// DWB_CRC_SRC_SEL_ENUM enum
//
// DWB_DATA_OVERFLOW_INT_TYPE_ENUM enum
//
// DWB_DATA_OVERFLOW_TYPE_ENUM enum
//
// DWB_DEBUG_SEL_ENUM enum
//
// DWB_MEM_PWR_FORCE_ENUM enum
//
// DWB_MEM_PWR_STATE_ENUM enum
//
// DWB_TEST_CLK_SEL_ENUM enum
//
// FC_EYE_SELECTION_ENUM enum
//
// FC_FRAME_CAPTURE_RATE_ENUM enum
//
// FC_STEREO_EYE_POLARITY_ENUM enum
//
// DWBCP Enums
//
// DWB_GAMUT_REMAP_COEF_FORMAT_ENUM enum
//
// DWB_GAMUT_REMAP_MODE_ENUM enum
//
// DWB_LUT_NUM_SEG enum
//
// DWB_OGAM_LUT_CONFIG_MODE_ENUM enum
//
// DWB_OGAM_LUT_HOST_SEL_ENUM enum
//
// DWB_OGAM_LUT_READ_COLOR_SEL_ENUM enum
//
// DWB_OGAM_LUT_READ_DBG_ENUM enum
//
// DWB_OGAM_MODE_ENUM enum
//
// DWB_OGAM_PWL_DISABLE_ENUM enum
//
// DWB_OGAM_SELECT_ENUM enum
//
// RDPCSPIPE Enums
//
// RDPCSPIPE_CLOCK_CNTL_LANE_CLK_EN enum
//
// RDPCSPIPE_CLOCK_CNTL_RDPCS_APBCLK_EN enum
//
// RDPCSPIPE_CLOCK_CNTL_RDPCS_PIPE_CLK_CLOCK_ON enum
//
// RDPCSPIPE_CLOCK_CNTL_RDPCS_PIPE_CLK_EN enum
//
// RDPCSPIPE_CLOCK_CNTL_RDPCS_PIPE_CLK_GATE_DIS enum
//
// RDPCSPIPE_CLOCK_CNTL_RDPCS_PIPE_PHYD32CLK_CLOCK_ON enum
//
// RDPCSPIPE_CLOCK_CNTL_RDPCS_SRAMCLK_CLOCK_ON enum
//
// RDPCSPIPE_CLOCK_CNTL_RDPCS_SRAMCLK_EN enum
//
// RDPCSPIPE_CLOCK_CNTL_RDPCS_SRAMCLK_GATE_DIS enum
//
// RDPCSPIPE_CLOCK_CNTL_RDPCS_SRAMCLK_PASS enum
//
// RDPCSPIPE_CNTL_RDPCS_PIPE_FIFO_EN enum
//
// RDPCSPIPE_CNTL_RDPCS_PIPE_FIFO_LANE_EN enum
//
// RDPCSPIPE_CNTL_RDPCS_PIPE_SOFT_RESET enum
//
// RDPCSPIPE_CNTL_RDPCS_SRAM_SOFT_RESET enum
//
// RDPCSPIPE_DBG_APB_COUNT_EXPIRE_MASK enum
//
// RDPCSPIPE_DBG_OCLA_SEL enum
//
// RDPCSPIPE_ENC_TYPE enum
//
// RDPCSPIPE_FIFO_EMPTY enum
//
// RDPCSPIPE_FIFO_FULL enum
//
// RDPCSPIPE_INTERRUPT_CONTROL_RDPCS_APB_PSLVERR_MASK enum
//
// RDPCSPIPE_INTERRUPT_CONTROL_RDPCS_DPALT_4LANE_TOGGLE enum
//
// RDPCSPIPE_INTERRUPT_CONTROL_RDPCS_DPALT_4LANE_TOGGLE_MASK enum
//
// RDPCSPIPE_INTERRUPT_CONTROL_RDPCS_DPALT_DISABLE_TOGGLE enum
//
// RDPCSPIPE_INTERRUPT_CONTROL_RDPCS_DPALT_DISABLE_TOGGLE_MASK enum
//
// RDPCSPIPE_INTERRUPT_CONTROL_RDPCS_PIPE_FIFO_ERROR_MASK enum
//
// RDPCSPIPE_INTERRUPT_CONTROL_RDPCS_REG_FIFO_ERROR_MASK enum
//
// RDPCSPIPE_MSG_BUS_COUNT_EXPIRE_MASK enum
//
// RDPCSPIPE_PACK_MODE enum
//
// RDPCSPIPE_PHY_CNTL0_RDPCS_PHY_CR_MUX_SEL enum
//
// RDPCSPIPE_PHY_CNTL0_RDPCS_PHY_CR_PARA_SEL enum
//
// RDPCSPIPE_PHY_CNTL0_RDPCS_PHY_REF_RANGE enum
//
// RDPCSPIPE_PHY_CNTL0_RDPCS_SRAM_EXT_LD_DONE enum
//
// RDPCSPIPE_PHY_CNTL0_RDPCS_SRAM_INIT_DONE enum
//
// RDPCSPIPE_PHY_CNTL11_RDPCS_PHY_DP_REF_CLK_MPLLB_DIV enum
//
// RDPCSPIPE_PHY_CNTL11_RDPCS_PHY_HDMI_MPLLB_HDMI_PIXEL_CLK_DIV enum
//
// RDPCSPIPE_PHY_CNTL12_RDPCS_PHY_DP_MPLLB_TX_CLK_DIV enum
//
// RDPCSPIPE_PHY_CNTL4_RDPCS_PHY_DP_TX_TERM_CTRL enum
//
// RDPCSPIPE_PHY_CNTL_RDPCS_PHY_DP_TX_DETRX_RESULT enum
//
// RDPCSPIPE_PHY_CNTL_RDPCS_PHY_DP_TX_RATE enum
//
// RDPCSPIPE_PHY_CNTL_RDPCS_PHY_DP_TX_WIDTH enum
//
// RDPCSPIPE_PHY_CNTL_RRDPCS_PHY_DP_TX_PSTATE enum
//
// RDPCSPIPE_PHY_IF_WIDTH enum
//
// RDPCSPIPE_PHY_RATE enum
//
// RDPCSPIPE_PHY_REF_ALT_CLK_EN enum
//
// RDPCSPIPE_TEST_CLK_SEL enum
//
// RDPCS_PIPE_CNTL_TX_LANE_PACK_FROM_MSB enum
//
// RDPCS_PIPE_SRAM_CNTL_RDPCS_MEM_PWR_FORCE enum
//
// RDPCS_PIPE_SRAM_CNTL_RDPCS_MEM_PWR_PWR_STATE enum
//
// RPDCSPIPE_CNTL_TX_LANE_BIT_ORDER_REVERSE_BEFORE_PACK enum
//
// GDS Enums
//
// GDS_PERFCOUNT_SELECT enum
//
// CB Enums
//
// BlendOp enum
//
// BlendOpt enum
//
// CBMode enum
//
// CBPerfClearFilterSel enum
//
// CBPerfOpFilterSel enum
//
// CBPerfSel enum
//
// CBRamList enum
//
// CmaskCode enum
//
// CombFunc enum
//
// MemArbMode enum
//
// SourceFormat enum
//
// SC Enums
//
// BinEventCntl enum
//
// BinMapMode enum
//
// BinSizeExtend enum
//
// BinningMode enum
//
// CovToShaderSel enum
//
// PkrMap enum
//
// PkrXsel enum
//
// PkrXsel2 enum
//
// PkrYsel enum
//
// RbMap enum
//
// RbXsel enum
//
// RbXsel2 enum
//
// RbYsel enum
//
// SC_PERFCNT_SEL enum
//
// ScMap enum
//
// ScUncertaintyRegionMode enum
//
// ScUncertaintyRegionMult enum
//
// ScXsel enum
//
// ScYsel enum
//
// SeMap enum
//
// SePairMap enum
//
// SePairXsel enum
//
// SePairYsel enum
//
// SeXsel enum
//
// SeYsel enum
//
// VRSCombinerModeSC enum
//
// VRSrate enum
//
// TC Enums
//
// TC_EA_CID enum
//
// TC_NACKS enum
//
// TC_OP enum
//
// TC_OP_MASKS enum
//
// GL2 Enums
//
// GL2_EA_CID enum
//
// GL2_NACKS enum
//
// GL2_OP enum
//
// GL2_OP_MASKS enum
//
// RLC Enums
//
// RLC_DOORBELL_MODE enum
//
// RLC_PERFCOUNTER_SEL enum
//
// RLC_PERFMON_STATE enum
//
// RSPM_CMD enum
//
// SPI Enums
//
// CLKGATE_BASE_MODE enum
//
// CLKGATE_SM_MODE enum
//
// SPI_FOG_MODE enum
//
// SPI_LB_WAVES_SELECT enum
//
// SPI_PERFCNT_SEL enum
//
// SPI_PNT_SPRITE_OVERRIDE enum
//
// SPI_PS_LDS_GROUP_SIZE enum
//
// SPI_SAMPLE_CNTL enum
//
// SPI_SHADER_EX_FORMAT enum
//
// SPI_SHADER_FORMAT enum
//
// SQ Enums
//
// SH_MEM_ADDRESS_MODE enum
//
// SH_MEM_ALIGNMENT_MODE enum
//
// SQG_PERF_SEL enum
//
// SQ_CAC_POWER_SEL enum
//
// SQ_EDC_INFO_SOURCE enum
//
// SQ_IBUF_ST enum
//
// SQ_IMG_FILTER_TYPE enum
//
// SQ_IND_CMD_CMD enum
//
// SQ_IND_CMD_MODE enum
//
// SQ_INST_STR_ST enum
//
// SQ_INST_TYPE enum
//
// SQ_LLC_CTL enum
//
// SQ_NO_INST_ISSUE enum
//
// SQ_OOB_SELECT enum
//
// SQ_PERF_SEL enum
//
// SQ_ROUND_MODE enum
//
// SQ_RSRC_BUF_TYPE enum
//
// SQ_RSRC_FLAT_TYPE enum
//
// SQ_RSRC_IMG_TYPE enum
//
// SQ_SEL_XYZW01 enum
//
// SQ_TEX_ANISO_RATIO enum
//
// SQ_TEX_BORDER_COLOR enum
//
// SQ_TEX_CLAMP enum
//
// SQ_TEX_DEPTH_COMPARE enum
//
// SQ_TEX_MIP_FILTER enum
//
// SQ_TEX_XY_FILTER enum
//
// SQ_TEX_Z_FILTER enum
//
// SQ_TT_MODE enum
//
// SQ_TT_RT_FREQ enum
//
// SQ_TT_TOKEN_MASK_INST_EXCLUDE enum
//
// SQ_TT_TOKEN_MASK_INST_EXCLUDE_SHIFT enum
//
// SQ_TT_TOKEN_MASK_REG_EXCLUDE enum
//
// SQ_TT_TOKEN_MASK_REG_EXCLUDE_SHIFT enum
//
// SQ_TT_TOKEN_MASK_REG_INCLUDE enum
//
// SQ_TT_TOKEN_MASK_REG_INCLUDE_SHIFT enum
//
// SQ_TT_TOKEN_MASK_TOKEN_EXCLUDE_SHIFT enum
//
// SQ_TT_UTIL_TIMER enum
//
// SQ_TT_WAVESTART_MODE enum
//
// SQ_TT_WTYPE_INCLUDE enum
//
// SQ_TT_WTYPE_INCLUDE_SHIFT enum
//
// SQ_WATCH_MODES enum
//
// SQ_WAVE_FWD_PROG_INTERVAL enum
//
// SQ_WAVE_IB_ECC_ST enum
//
// SQ_WAVE_SCHED_MODES enum
//
// SQ_WAVE_TYPE enum
//
// SQ_WAVE_TYPE value
//
pub const SQ_WAVE_TYPE_PS0: c_uint = 0x00000000;
//
// SQIND_PARTITIONS value
//
pub const SQIND_GLOBAL_REGS_OFFSET: c_uint = 0x00000000;
pub const SQIND_GLOBAL_REGS_SIZE: c_uint = 0x00000008;
pub const SQIND_LOCAL_REGS_OFFSET: c_uint = 0x00000008;
pub const SQIND_LOCAL_REGS_SIZE: c_uint = 0x00000008;
pub const SQIND_WAVE_HWREGS_OFFSET: c_uint = 0x00000100;
pub const SQIND_WAVE_HWREGS_SIZE: c_uint = 0x00000100;
pub const SQIND_WAVE_SGPRS_OFFSET: c_uint = 0x00000200;
pub const SQIND_WAVE_SGPRS_SIZE: c_uint = 0x00000200;
pub const SQIND_WAVE_VGPRS_OFFSET: c_uint = 0x00000400;
pub const SQIND_WAVE_VGPRS_SIZE: c_uint = 0x00000400;
//
// SQ_GFXDEC value
//
pub const SQ_GFXDEC_BEGIN: c_uint = 0x0000a000;
pub const SQ_GFXDEC_END: c_uint = 0x0000c000;
pub const SQ_GFXDEC_STATE_ID_SHIFT: c_uint = 0x0000000a;
//
// SQDEC value
//
pub const SQDEC_BEGIN: c_uint = 0x00002300;
pub const SQDEC_END: c_uint = 0x000023ff;
//
// SQPERFSDEC value
//
pub const SQPERFSDEC_BEGIN: c_uint = 0x0000d9c0;
pub const SQPERFSDEC_END: c_uint = 0x0000da40;
//
// SQPERFDDEC value
//
pub const SQPERFDDEC_BEGIN: c_uint = 0x0000d1c0;
pub const SQPERFDDEC_END: c_uint = 0x0000d240;
//
// SQGFXUDEC value
//
pub const SQGFXUDEC_BEGIN: c_uint = 0x0000c330;
pub const SQGFXUDEC_END: c_uint = 0x0000c380;
//
// SQPWRDEC value
//
pub const SQPWRDEC_BEGIN: c_uint = 0x0000f08c;
pub const SQPWRDEC_END: c_uint = 0x0000f094;
//
// SQ_DISPATCHER value
//
pub const SQ_DISPATCHER_GFX_MIN: c_uint = 0x00000010;
pub const SQ_DISPATCHER_GFX_CNT_PER_RING: c_uint = 0x00000008;
//
// SQ_MAX value
//
pub const SQ_MAX_PGM_SGPRS: c_uint = 0x00000068;
pub const SQ_MAX_PGM_VGPRS: c_uint = 0x00000100;
//
// SQ_EXCP_BITS value
//
pub const SQ_EX_MODE_EXCP_VALU_BASE: c_uint = 0x00000000;
pub const SQ_EX_MODE_EXCP_VALU_SIZE: c_uint = 0x00000007;
pub const SQ_EX_MODE_EXCP_INVALID: c_uint = 0x00000000;
pub const SQ_EX_MODE_EXCP_INPUT_DENORM: c_uint = 0x00000001;
pub const SQ_EX_MODE_EXCP_DIV0: c_uint = 0x00000002;
pub const SQ_EX_MODE_EXCP_OVERFLOW: c_uint = 0x00000003;
pub const SQ_EX_MODE_EXCP_UNDERFLOW: c_uint = 0x00000004;
pub const SQ_EX_MODE_EXCP_INEXACT: c_uint = 0x00000005;
pub const SQ_EX_MODE_EXCP_INT_DIV0: c_uint = 0x00000006;
pub const SQ_EX_MODE_EXCP_ADDR_WATCH0: c_uint = 0x00000007;
pub const SQ_EX_MODE_EXCP_MEM_VIOL: c_uint = 0x00000008;
//
// SQ_EXCP_HI_BITS value
//
pub const SQ_EX_MODE_EXCP_HI_ADDR_WATCH1: c_uint = 0x00000000;
pub const SQ_EX_MODE_EXCP_HI_ADDR_WATCH2: c_uint = 0x00000001;
pub const SQ_EX_MODE_EXCP_HI_ADDR_WATCH3: c_uint = 0x00000002;
//
// HW_INSERTED_INST_ID value
//
pub const INST_ID_PRIV_START: c_uint = 0x80000000;
pub const INST_ID_ECC_INTERRUPT_MSG: c_uint = 0xfffffff0;
pub const INST_ID_TTRACE_NEW_PC_MSG: c_uint = 0xfffffff1;
pub const INST_ID_HW_TRAP: c_uint = 0xfffffff2;
pub const INST_ID_KILL_SEQ: c_uint = 0xfffffff3;
pub const INST_ID_SPI_WREXEC: c_uint = 0xfffffff4;
pub const INST_ID_HW_TRAP_GET_TBA: c_uint = 0xfffffff5;
pub const INST_ID_HOST_REG_TRAP_MSG: c_uint = 0xfffffffe;
//
// SIMM16_WAITCNT_PARTITIONS value
//
pub const SIMM16_WAITCNT_EXP_CNT_START: c_uint = 0x00000000;
pub const SIMM16_WAITCNT_EXP_CNT_SIZE: c_uint = 0x00000003;
pub const SIMM16_WAITCNT_LGKM_CNT_START: c_uint = 0x00000004;
pub const SIMM16_WAITCNT_LGKM_CNT_SIZE: c_uint = 0x00000006;
pub const SIMM16_WAITCNT_VM_CNT_START: c_uint = 0x0000000a;
pub const SIMM16_WAITCNT_VM_CNT_SIZE: c_uint = 0x00000006;
pub const SIMM16_WAITCNT_DEPCTR_SA_SDST_START: c_uint = 0x00000000;
pub const SIMM16_WAITCNT_DEPCTR_SA_SDST_SIZE: c_uint = 0x00000001;
pub const SIMM16_WAITCNT_DEPCTR_VA_VCC_START: c_uint = 0x00000001;
pub const SIMM16_WAITCNT_DEPCTR_VA_VCC_SIZE: c_uint = 0x00000001;
pub const SIMM16_WAITCNT_DEPCTR_VM_VSRC_START: c_uint = 0x00000002;
pub const SIMM16_WAITCNT_DEPCTR_VM_VSRC_SIZE: c_uint = 0x00000003;
pub const SIMM16_WAITCNT_DEPCTR_HOLD_CNT_START: c_uint = 0x00000006;
pub const SIMM16_WAITCNT_DEPCTR_HOLD_CNT_SIZE: c_uint = 0x00000001;
pub const SIMM16_WAITCNT_DEPCTR_VA_SSRC_START: c_uint = 0x00000007;
pub const SIMM16_WAITCNT_DEPCTR_VA_SSRC_SIZE: c_uint = 0x00000001;
pub const SIMM16_WAITCNT_DEPCTR_VA_SDST_START: c_uint = 0x00000008;
pub const SIMM16_WAITCNT_DEPCTR_VA_SDST_SIZE: c_uint = 0x00000003;
pub const SIMM16_WAITCNT_DEPCTR_VA_VDST_START: c_uint = 0x0000000b;
pub const SIMM16_WAITCNT_DEPCTR_VA_VDST_SIZE: c_uint = 0x00000005;
//
// SIMM16_WAIT_EVENT_PARTITIONS value
//
pub const SIMM16_WAIT_EVENT_EXP_RDY_START: c_uint = 0x00000000;
pub const SIMM16_WAIT_EVENT_EXP_RDY_SIZE: c_uint = 0x00000001;
//
// SQ_WAVE_IB_DEP_COUNTER_SIZES value
//
pub const SQ_WAVE_IB_DEP_SA_SDST_SIZE: c_uint = 0x00000004;
pub const SQ_WAVE_IB_DEP_SA_EXEC_SIZE: c_uint = 0x00000002;
pub const SQ_WAVE_IB_DEP_SA_M0_SIZE: c_uint = 0x00000001;
pub const SQ_WAVE_IB_DEP_VM_VSRC_SIZE: c_uint = 0x00000004;
pub const SQ_WAVE_IB_DEP_HOLD_CNT_SIZE: c_uint = 0x00000001;
pub const SQ_WAVE_IB_DEP_VA_SSRC_SIZE: c_uint = 0x00000003;
pub const SQ_WAVE_IB_DEP_VA_SDST_SIZE: c_uint = 0x00000004;
pub const SQ_WAVE_IB_DEP_VA_VCC_SIZE: c_uint = 0x00000003;
pub const SQ_WAVE_IB_DEP_VA_EXEC_SIZE: c_uint = 0x00000002;
pub const SQ_WAVE_IB_DEP_VA_VDST_SIZE: c_uint = 0x00000005;
pub const SQ_WAVE_IB_DEP_LDS_DIR_SIZE: c_uint = 0x00000003;
//
// SQ_EDC_FUE_CNTL_BITS value
//
pub const SQ_EDC_FUE_CNTL_SIMD0: c_uint = 0x00000000;
pub const SQ_EDC_FUE_CNTL_SIMD1: c_uint = 0x00000001;
pub const SQ_EDC_FUE_CNTL_SIMD2: c_uint = 0x00000002;
pub const SQ_EDC_FUE_CNTL_SIMD3: c_uint = 0x00000003;
pub const SQ_EDC_FUE_CNTL_SQ: c_uint = 0x00000004;
pub const SQ_EDC_FUE_CNTL_LDS: c_uint = 0x00000005;
pub const SQ_EDC_FUE_CNTL_TD: c_uint = 0x00000006;
pub const SQ_EDC_FUE_CNTL_TA: c_uint = 0x00000007;
pub const SQ_EDC_FUE_CNTL_TCP: c_uint = 0x00000008;
//
// COMP Enums
//
// CSCNTL_TYPE enum
//
// CSDATA_TYPE enum
//
// CSDATA_TYPE_WIDTH value
//
pub const CSDATA_TYPE_WIDTH: c_uint = 0x00000002;
//
// CSDATA_ADDR_WIDTH value
//
pub const CSDATA_ADDR_WIDTH: c_uint = 0x00000007;
//
// CSDATA_DATA_WIDTH value
//
pub const CSDATA_DATA_WIDTH: c_uint = 0x00000020;
//
// CSCNTL_TYPE_WIDTH value
//
pub const CSCNTL_TYPE_WIDTH: c_uint = 0x00000002;
//
// CSCNTL_ADDR_WIDTH value
//
pub const CSCNTL_ADDR_WIDTH: c_uint = 0x00000007;
//
// CSCNTL_DATA_WIDTH value
//
pub const CSCNTL_DATA_WIDTH: c_uint = 0x00000020;
//
// GE Enums
//
// GE1_PERFCOUNT_SELECT enum
//
// GE2_DIST_PERFCOUNT_SELECT enum
//
// GE2_SE_PERFCOUNT_SELECT enum
//
// VGT_DETECT_ONE enum
//
// VGT_DETECT_ZERO enum
//
// VGT_DIST_MODE enum
//
// VGT_DI_INDEX_SIZE enum
//
// VGT_DI_MAJOR_MODE_SELECT enum
//
// VGT_DI_PRIM_TYPE enum
//
// VGT_DI_SOURCE_SELECT enum
//
// VGT_DMA_BUF_TYPE enum
//
// VGT_DMA_SWAP_MODE enum
//
// VGT_EVENT_TYPE enum
//
// VGT_GROUP_CONV_SEL enum
//
// VGT_GS_MODE_TYPE enum
//
// VGT_GS_OUTPRIM_TYPE enum
//
// VGT_INDEX_TYPE_MODE enum
//
// VGT_OUTPATH_SELECT enum
//
// VGT_OUT_PRIM_TYPE enum
//
// VGT_RDREQ_POLICY enum
//
// VGT_STAGES_ES_EN enum
//
// VGT_STAGES_GS_EN enum
//
// VGT_STAGES_HS_EN enum
//
// VGT_STAGES_LS_EN enum
//
// VGT_STAGES_VS_EN enum
//
// VGT_TESS_PARTITION enum
//
// VGT_TESS_TOPOLOGY enum
//
// VGT_TESS_TYPE enum
//
// WD_IA_DRAW_REG_XFER enum
//
// WD_IA_DRAW_SOURCE enum
//
// WD_IA_DRAW_TYPE enum
//
// GS_THREADID_SIZE value
//
pub const GSTHREADID_SIZE: c_uint = 0x00000002;
//
// GB Enums
//
// GB_EDC_DED_MODE enum
//
// VALUE_GB_TILING_CONFIG_TABLE_SIZE value
//
pub const GB_TILING_CONFIG_TABLE_SIZE: c_uint = 0x00000020;
//
// VALUE_GB_TILING_CONFIG_MACROTABLE_SIZE value
//
pub const GB_TILING_CONFIG_MACROTABLE_SIZE: c_uint = 0x00000010;
//
// GLX Enums
//
// CHA_PERF_SEL enum
//
// CHCG_PERF_SEL enum
//
// CHC_PERF_SEL enum
//
// GL1A_PERF_SEL enum
//
// GL1C_PERF_SEL enum
//
// GL1H Enums
//
// GL1H_REQ_PERF_SEL enum
//
// TA Enums
//
// TA_PERFCOUNT_SEL enum
//
// TEX_BC_SWIZZLE enum
//
// TEX_BORDER_COLOR_TYPE enum
//
// TEX_CHROMA_KEY enum
//
// TEX_CLAMP enum
//
// TEX_COORD_TYPE enum
//
// TEX_DEPTH_COMPARE_FUNCTION enum
//
// TEX_FORMAT_COMP enum
//
// TEX_MAX_ANISO_RATIO enum
//
// TEX_MIP_FILTER enum
//
// TEX_REQUEST_SIZE enum
//
// TEX_SAMPLER_TYPE enum
//
// TEX_XY_FILTER enum
//
// TEX_Z_FILTER enum
//
// TVX_TYPE enum
//
// TCP Enums
//
// TA_TC_ADDR_MODES enum
//
// TA_TC_REQ_MODES enum
//
// TCP_CACHE_POLICIES enum
//
// TCP_CACHE_STORE_POLICIES enum
//
// TCP_DSM_DATA_SEL enum
//
// TCP_DSM_INJECT_SEL enum
//
// TCP_DSM_SINGLE_WRITE enum
//
// TCP_OPCODE_TYPE enum
//
// TCP_PERFCOUNT_SELECT enum
//
// TCP_WATCH_MODES enum
//
// TD Enums
//
// TD_PERFCOUNT_SEL enum
//
// GL2C Enums
//
// GL2A_PERF_SEL enum
//
// GL2C_PERF_SEL enum
//
// GRBM Enums
//
// GRBM_PERF_SEL enum
//
// GRBM_SE0_PERF_SEL enum
//
// GRBM_SE1_PERF_SEL enum
//
// GRBM_SE2_PERF_SEL enum
//
// GRBM_SE3_PERF_SEL enum
//
// GRBM_SE4_PERF_SEL enum
//
// GRBM_SE5_PERF_SEL enum
//
// GRBM_SE6_PERF_SEL enum
//
// GRBM_SE7_PERF_SEL enum
//
// PIPE_COMPAT_LEVEL enum
//
// CP Enums
//
// CPC_LATENCY_STATS_SEL enum
//
// CPC_PERFCOUNT_SEL enum
//
// CPF_LATENCY_STATS_SEL enum
//
// CPF_PERFCOUNTWINDOW_SEL enum
//
// CPF_PERFCOUNT_SEL enum
//
// CPF_SCRATCH_REG_ATOMIC_OP enum
//
// CPG_LATENCY_STATS_SEL enum
//
// CPG_PERFCOUNTWINDOW_SEL enum
//
// CPG_PERFCOUNT_SEL enum
//
// CP_ALPHA_TAG_RAM_SEL enum
//
// CP_DDID_CNTL_MODE enum
//
// CP_DDID_CNTL_SIZE enum
//
// CP_DDID_CNTL_VMID_SEL enum
//
// CP_ME_ID enum
//
// CP_PERFMON_ENABLE_MODE enum
//
// CP_PERFMON_STATE enum
//
// CP_PIPE_ID enum
//
// CP_RING_ID enum
//
// SPM_PERFMON_STATE enum
//
// SEM_RESPONSE value
//
pub const SEM_ECC_ERROR: c_uint = 0x00000000;
pub const SEM_TRANS_ERROR: c_uint = 0x00000001;
pub const SEM_RESP_FAILED: c_uint = 0x00000002;
pub const SEM_RESP_PASSED: c_uint = 0x00000003;
//
// IQ_RETRY_TYPE value
//
pub const IQ_QUEUE_SLEEP: c_uint = 0x00000000;
pub const IQ_OFFLOAD_RETRY: c_uint = 0x00000001;
pub const IQ_SCH_WAVE_MSG: c_uint = 0x00000002;
pub const IQ_SEM_REARM: c_uint = 0x00000003;
pub const IQ_DEQUEUE_RETRY: c_uint = 0x00000004;
//
// IQ_INTR_TYPE value
//
pub const IQ_INTR_TYPE_PQ: c_uint = 0x00000000;
pub const IQ_INTR_TYPE_IB: c_uint = 0x00000001;
pub const IQ_INTR_TYPE_MQD: c_uint = 0x00000002;
//
// VMID_SIZE value
//
pub const VMID_SZ: c_uint = 0x00000004;
//
// SRCID_SECURE value
//
pub const SRCID_RLC: c_uint = 0x00000000;
pub const SRCID_RLCV: c_uint = 0x00000006;
pub const SRCID_SECURE_CP: c_uint = 0x00000007;
pub const SRCID_NONSECURE_CP: c_uint = 0x00000001;
pub const SRCID_SECURE_CP_RCIU: c_uint = 0x00000007;
pub const SRCID_NONSECURE_CP_RCIU: c_uint = 0x00000001;
//
// CONFIG_SPACE value
//
pub const CONFIG_SPACE_START: c_uint = 0x00002000;
pub const CONFIG_SPACE_END: c_uint = 0x00009fff;
//
// CONFIG_SPACE1 value
//
pub const CONFIG_SPACE1_START: c_uint = 0x00002000;
pub const CONFIG_SPACE1_END: c_uint = 0x00002bff;
//
// CONFIG_SPACE2 value
//
pub const CONFIG_SPACE2_START: c_uint = 0x00003000;
pub const CONFIG_SPACE2_END: c_uint = 0x00009fff;
//
// UCONFIG_SPACE value
//
pub const UCONFIG_SPACE_START: c_uint = 0x0000c000;
pub const UCONFIG_SPACE_END: c_uint = 0x0000ffff;
//
// PERSISTENT_SPACE value
//
pub const PERSISTENT_SPACE_START: c_uint = 0x00002c00;
pub const PERSISTENT_SPACE_END: c_uint = 0x00002fff;
//
// CONTEXT_SPACE value
//
pub const CONTEXT_SPACE_START: c_uint = 0x0000a000;
pub const CONTEXT_SPACE_END: c_uint = 0x0000a3ff;
//
// SX Enums
//
// SX_BLEND_OPT enum
//
// SX_DOWNCONVERT_FORMAT enum
//
// SX_OPT_COMB_FCN enum
//
// SX_PERFCOUNTER_VALS enum
//
// DB Enums
//
// CompareFrag enum
//
// ConservativeZExport enum
//
// DFSMFlushEvents enum
//
// DbMemArbWatermarks enum
//
// DbPRTFaultBehavior enum
//
// DbPSLControl enum
//
// ForceControl enum
//
// OreoMode enum
//
// PerfCounter_Vals enum
//
// PixelPipeCounterId enum
//
// PixelPipeStride enum
//
// RingCounterControl enum
//
// StencilOp enum
//
// ZLimitSumm enum
//
// ZModeForce enum
//
// ZOrder enum
//
// ZSamplePosition enum
//
// ZpassControl enum
//
// PA Enums
//
// SU_PERFCNT_SEL enum
//
// PH Enums
//
// PH_PERFCNT_SEL enum
//
// PhSPIstatusMode enum
//
// RMI Enums
//
// RMIPerfSel enum
//
// PMM Enums
//
// GCRPerfSel enum
//
// UTCL1 Enums
//
// UTCL1PerfSel enum
//
// IH Enums
//
// IH_CLIENT_TYPE enum
//
// IH_INTERFACE_TYPE enum
//
// IH_PERF_SEL enum
//
// IH_RING_ID enum
//
// IH_VF_RB_SELECT enum
//
// SEM Enums
//
// SEM_PERF_SEL enum
//
// LSDMA Enums
//
// LSDMA_PERF_SEL enum
//
// SMUIO_ROM Enums
//
// ROM_SIGNATURE value
//
pub const ROM_SIGNATURE: c_uint = 0x0000aa55;
//
// UVD_EFC Enums
//
// EFC_SURFACE_PIXEL_FORMAT enum
//
