//! Automatically rewritten from C to Rust
//! Source: tools/perf/scripts/perl/Perf-Trace-Util/Context.c
#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]

use core::ffi::*;

// --- Linux Kernel Primitives Prelude ---
pub type uid_t = u32;
pub type gid_t = u32;
pub type uid16_t = u16;
pub type gid16_t = u16;
pub type pid_t = i32;
pub type mode_t = u32;
pub type umode_t = u16;
pub type nlink_t = u32;
pub type off_t = i64;
pub type loff_t = i64;
pub type dev_t = u32;
pub type ino_t = u64;
pub type size_t = usize;
pub type ssize_t = isize;
pub type uintptr_t = usize;
pub type intptr_t = isize;
pub type ptrdiff_t = isize;
pub type clockid_t = i32;
pub type timer_t = i32;
pub type time64_t = i64;
pub type atomic_t = core::sync::atomic::AtomicI32;
pub type atomic64_t = core::sync::atomic::AtomicI64;
// ---------------------------------------


// SPDX-License-Identifier: GPL-2.0-or-later
//
// This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
// contents of Context.xs. Do not edit this file, edit Context.xs instead.
//
// ANY CHANGES MADE HERE WILL BE LOST!
//

//
// Context.xs.  XS interfaces for perf script.
//
// Copyright (C) 2009 Tom Zanussi <tzanussi@gmail.com>
//

    XS(XS_Perf__Trace__Context_common_pc); /* prototype to pass -Wmissing-prototypes */
    XS(XS_Perf__Trace__Context_common_pc)
    {

    dVAR; dXSARGS;

    dXSARGS;

    if (items != 1)
    Perl_croak(aTHX_ "Usage: %s(%s)", "Perf::Trace::Context::common_pc", "context");
    PERL_UNUSED_VAR(cv); /* -W */
    {
    let mut context: *mut scripting_context = INT2PTR(struct scripting_context *,SvIV(ST(0)));
    int	RETVAL;
    dXSTARG;
    RETVAL = common_pc(context);
    XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
    }
    XS(XS_Perf__Trace__Context_common_flags); /* prototype to pass -Wmissing-prototypes */
    XS(XS_Perf__Trace__Context_common_flags)
    {

    dVAR; dXSARGS;

    dXSARGS;

    if (items != 1)
    Perl_croak(aTHX_ "Usage: %s(%s)", "Perf::Trace::Context::common_flags", "context");
    PERL_UNUSED_VAR(cv); /* -W */
    {
    let mut context: *mut scripting_context = INT2PTR(struct scripting_context *,SvIV(ST(0)));
    int	RETVAL;
    dXSTARG;
    RETVAL = common_flags(context);
    XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
    }
    XS(XS_Perf__Trace__Context_common_lock_depth); /* prototype to pass -Wmissing-prototypes */
    XS(XS_Perf__Trace__Context_common_lock_depth)
    {

    dVAR; dXSARGS;

    dXSARGS;

    if (items != 1)
    Perl_croak(aTHX_ "Usage: %s(%s)", "Perf::Trace::Context::common_lock_depth", "context");
    PERL_UNUSED_VAR(cv); /* -W */
    {
    let mut context: *mut scripting_context = INT2PTR(struct scripting_context *,SvIV(ST(0)));
    int	RETVAL;
    dXSTARG;
    RETVAL = common_lock_depth(context);
    XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
    }

    extern "C"

    XS(boot_Perf__Trace__Context); /* prototype to pass -Wmissing-prototypes */
    XS(boot_Perf__Trace__Context)
    {

    dVAR; dXSARGS;

    dXSARGS;

    let mut file: *const c_char = __FILE__;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;
    newXSproto("Perf::Trace::Context::common_pc", XS_Perf__Trace__Context_common_pc, file, "$");
    newXSproto("Perf::Trace::Context::common_flags", XS_Perf__Trace__Context_common_flags, file, "$");
    newXSproto("Perf::Trace::Context::common_lock_depth", XS_Perf__Trace__Context_common_lock_depth, file, "$");
    if (PL_unitcheckav)
    call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
    }
